### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by daijun4you** [dooboolab/react-native-iap#1]

**Comment by JJMoon** [comment]
We are working on it. Sorry for misunderstanding.

**Comment by dooboolab** [comment]
Will be done in 1 week.

**Comment by daijun4you** [comment]
thx, very much. I want to be the first user, haha

**Comment by daijun4you** [comment]
by the way, I used react-native-in-app-utils to do purchase, but I found some user losed his order on production env, but I cannot reproduction, hope you can notice this.

**Comment by dooboolab** [comment]
Hi. We released beta version for this library today and will keep working on it to release the stable version which will be v1.0.0.

However, you can try this library these day so your feedback will help us for next release.
Currently subscribing is not supported yet. Only getItems => buyItems => getting receipt string is supported now.

Thank you for all your regrads.

**Comment by daijun4you** [comment]
Good! I will try it next week!

**Comment by hyochan** [comment]
## Sponsors

<img src="https://github.com/dooboolab-community/react-native-iap/assets/27461460/89d71f61-bb73-400a-83bd-fe0f96eb726e" width="600"/>

**Comment by hyochan** [comment]
## Sponsors
![revenuecat](https://github.com/dooboolab-community/react-native-iap/assets/27461460/1e387a47-afe0-4b85-ad78-1064ca6623fa)
