### ISSUE TITLE
IAP subscription purchase error.

### ISSUE THREAD

**Issue by Suraj-Tiwari** [dooboolab/react-native-iap#100]
### Version of react-native-iap
Latest
### Expected behavior
data 
### Actual behavior
Error
### Steps to reprodue the behabior
Well in my case, Install -> manual merge -> then this code
```
try {
//also tried RNIap.getSubscriptions().then((data) => ....);
    RNIap.getProducts().then((item_receipt) => {
                    console.log(item_receipt);
    }).catch(err => alert('errror :' + err))
} catch (err) {
alert('errror :' + err);
}
```

Error message: Type Error Cannot read property of getitems of undefined.

**Comment by dooboolab** [comment]
@Suraj-Tiwari Check the version and the readme. There is breaking changes in method name.

**Comment by Suraj-Tiwari** [comment]
Well that was an example 
```
RNIap.buySubscription('my.sub.id').then((item_receipt) => {
                    console.log(item_receipt);
                }).catch(err => alert('errror :' + err))
```
This code produce same error too.

> Error message: Type Error Cannot read property of 'buyProduct' of undefined.

**Comment by dooboolab** [comment]
Could you describe the issue properly? Because I am confused. You wrote `buySubscription` on the code but the error message is `buyProduct` of undefined. Please provide the problem thorougly, so we can understand the problem.

**Comment by Suraj-Tiwari** [comment]
Alright, Main issue is Both functions are firing `undefined` error for different variables and other functions too like getProducts() etc..
[this message is on simulator](https://github.com/dooboolab/react-native-iap/issues/100#issuecomment-378922176)

And same code gave this error on Physical device
> Type Error: undefined is not an object (evaluating 'i.buyProduct')

![Error](https://user-images.githubusercontent.com/22210490/38376661-b9e17bb4-3916-11e8-913d-4cb0e033c18d.png)

![Code](https://user-images.githubusercontent.com/22210490/38376685-caad869a-3916-11e8-89e4-70d94129a1d2.png)

**Comment by Suraj-Tiwari** [comment]
> Because I am confused. You wrote buySubscription on the code but the error message is buyProduct of undefined.

That's why i filed an issue because i was confused too #reopen this issue until it's resolved.
I'll try to Resolve from my end too.

**Comment by dooboolab** [comment]
Did you link the library properly? If you checked the version perperly and used the proper methods name, I think that would be the reason you get `undefined`.

If you did, provide us our `module version` and your `react-native version` for more info.

**Comment by Suraj-Tiwari** [comment]
Ok so this was happening because i forgot to add libRNIap.a 
but after adding i Got this #98 again
![ISSUE](https://user-images.githubusercontent.com/22210490/38404054-06556636-3985-11e8-8b9f-11bc6fb63676.png)

**Comment by Suraj-Tiwari** [comment]
### "react-native-iap": "^0.3.1",
### Successful purchase
### Errors 
### Install library > link manually IOS> and again compile error

**Comment by hungvu193** [comment]
i face this issue with react-native 0.5.4 and  react-native-iap : ^1.3.5

**Comment by andrideng** [comment]
@hungvu193 try to connect the library manually, it works for me. 👯‍♂️

**Comment by Suraj-Tiwari** [comment]
There are many fluctuations with latest react-native version.  IF facing any issue try to go previous build,
