### ISSUE TITLE
consumeAllItemsAndroid no purchases found

### ISSUE THREAD

**Issue by NewBieBR** [dooboolab/react-native-iap#1000]
### Version of react-native-iap
4.4.0
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
await RNIap.consumeAllItemsAndroid(); not return error

### Actual behavior
```
refreshItem No purchases found
```

### Tested environment (Emulator? Real Device?)
Real Device - Oppo
### Steps to reproduce the behavior
```js
    try {
      const result = await RNIap.initConnection();
      console.log('result await RNIap.initConnection()', result);
      await RNIap.consumeAllItemsAndroid();
      console.log("consumeAllItemsAndroid done")
      this.getItems();
    } catch (err) {
      console.warn(err.code, err.message);
    }
```

Output:
```
result await RNIap.initConnection() true
refreshItem No purchases found
```

## Context
This is for subscriptions in app purchases that are `Active` on google developer console

**Comment by hyochan** [comment]
@NewBieBR Could you try `4.4.4` or above and come back?

**Comment by ziftinpeki** [comment]
@hyochan It's the same for me.

"react-native": "0.62.2",
"react-native-iap": "^4.4.8",

**Comment by NewBieBR** [comment]
@hyochan Yes still the same problem

**Comment by IlinIgor** [comment]
@hyochan I have the same problem, my users complain to me they can't restore purchases.

**Comment by simplesthing** [comment]
I am also having this problem

**Comment by aravi365** [comment]
Any updates, workarounds or fixes for this issue? anyone

**Comment by jonathanmachado** [comment]
same problem

**Comment by FelipeMolinari** [comment]
Any solution?

**Comment by safciplak** [comment]
any solution?

**Comment by marcsumilang** [comment]
same problem using "react-native-iap": "^4.5.2"

**Comment by safciplak** [comment]
any update?
