### ISSUE TITLE
How to acknowledge in app products ? Why my in app purchases are being refunded ?

### ISSUE THREAD

**Issue by aj019** [dooboolab/react-native-iap#1003]
### Version of react-native-iap
^4.4.8
### Version of react-native
0.62.0
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
In app purchases should not be refunded
### Actual behavior
In app purchases are being refunded
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Integrated buying in app products not subscription
Listened for purchaseUpdateListener
The payment shows up in Google Console 
But after few days the amount is refunded

**Comment by creativemind1** [comment]
After updateListener is successful and you saved your receipt in DB call `RNIap.acknowledgePurchaseAndroid` with the `purchaseToken` in the request and you are all good!

**Comment by hakkikonu** [comment]
Did you try `RNIap.finishTransaction(purchase, true);` ?

```
// If consumable (can be purchased again)
RNIap.finishTransaction(purchase, true);
// If not consumable
RNIap.finishTransaction(purchase, false);
```


```
purchaseUpdateSubscription = purchaseUpdatedListener(
      async (purchase: InAppPurchase | SubscriptionPurchase) => {
        const receipt = purchase.transactionReceipt;
        if (receipt) {
          try {
            // if (Platform.OS === 'ios') {
            //   finishTransactionIOS(purchase.transactionId);
            // } else if (Platform.OS === 'android') {
            //   // If consumable (can be purchased again)
            //   consumePurchaseAndroid(purchase.purchaseToken);
            //   // If not consumable
            //   acknowledgePurchaseAndroid(purchase.purchaseToken);
            // }
           //**if consumable; second parameter must be true, otherwise false**
            const ackResult = await finishTransaction(purchase,true);
          } catch (ackErr) {
            console.warn('ackErr', ackErr);
          }

          this.setState({receipt}, () => this.goNext());
        }
      },
    );
```
