### ISSUE TITLE
RNIap.requestPurchase is not responding in iOS

### ISSUE THREAD

**Issue by emreakbaba** [dooboolab/react-native-iap#1005]
### Version of react-native-iap
4.4.8
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
```
await RNIap.requestPurchase(sku, false)
console.log('REQUEST OVER') 
```
REQUEST OVER to be printed.
### Actual behavior
In device i use sandbox tester account, it is responding and working well. But with any other devices or simulator it is not responding or resolving. This is vital since during app review, Apple keep rejecting my application with reason of tapping in BUY is not responding. 

There is no problem about `RNIap.getProducts(itemSkus)`

### Tested environment (Emulator? Real Device?)
Real Device and Simulator
### Steps to reproduce the behavior

```
 async componentDidMount() {
    RNIap.getProducts(itemSkus)
      .then((products) => {
        this.setState({ products: products })
      })
      .catch((error) => {
        console.log(error.message)
      })
  }
requestPurchase = async (sku) => {
    try {
      await RNIap.requestPurchase(sku, false)
      console.log('REQUESTED OVER')
    } catch (err) {
      console.warn(err.code, err.message)
    }
}

render() {
 const { products } = this.state
 return (
  <View>
    {products.map((p, i) => { return (
       <TouchableWithoutFeedback onPress={() => this.requestPurchase(p.productId)}>
          <Text> BUY </Text>
       </TouchableWithoutFeedback> ) })}
 </View>)
```

**Comment by Panda313** [comment]
Same here, however it seems to work on Android.

**Comment by Panda313** [comment]
I may have fixed it by adding 

`const result = await RNIap.initConnection();
await RNIap.consumeAllItemsAndroid();
console.log('result', result);`

At the begining of componentDidMount ;

Let me know if that help

**Comment by smarttouchtechnology** [comment]
Has anyone found a resolution to this? I am also experiencing the same problem in iOS. Its extremely frustrating, and I can't get past app review because calling RNIap.requestPurchase doesn't respond with the alert either promoting the user to agree to the subscription terms or confirming that the subscription is already active. If I force close the app and try it again, sometimes it works. I don't know if there is a problem with the sandbox or this library.

**Comment by hyochan** [comment]
@smarttouchtechnology Have you called `initConnection`? This is needed from `4.4.5`.

**Comment by Panda313** [comment]
It may be hard for @smarttouchtechnology to read the answer below that "solve" the "problem" ;)

**Comment by thaneros** [comment]
I had the same problem and @Panda313 suggestion to add `await RNIap.initConnection()` in `componentDidMount` worked.
Too bad this is not better documented...

**Comment by Oguntoye** [comment]
@Panda313 ... You just saved my 1 week sleepless night of apple rejection

**Comment by danleveille** [comment]
Could someone add this to the documentation so more people don't run into this issue? I'm not sure the best way to add it.

Would it just be to add a `componentDidMount` function before the line:

`  requestPurchase = async (sku: string) => {`

**Comment by EvgeniiKlepilin** [comment]
> I may have fixed it by adding
> 
> > const result = await RNIap.initConnection();
> > await RNIap.consumeAllItemsAndroid();
> > console.log('result', result);
> 
> At the begining of componentDidMount ;
> 
> Let me know if that help

For iOS, I didn't have any response from `requestSubscription`. I tried adding `await RNIap.initConnection();` in front of `RNIap.requestSubscription` and it worked for me. Now I am receiving purchase objects in listeners in the root of the app. And it also proceeds further down the code after it resolves either in error or in successful response.

**Comment by Mihai-github** [comment]
Hi... I have the same problem with apple pay... yesterday worked really nice got everything to work from fetching the products to getting the purchase history and validating the latest receipt and today for some kind of reason won't appear any more and there is no error or anything when calling requestPurchase..

```
RNIap.requestPurchase(resp[0].productId)
.then((purchase: any) => {
     alert(1);
     console.log({purchase});
})
   .catch((errorPurchase: any) => {
     alert(2);
     console.log({errorPurchase});
});
```

The `then` function never gets executed but also the `catch` never does... Any idea why?

**Comment by homiis** [comment]
@Mihai-github We are experiencing this issue too. How did you fix?
