### ISSUE TITLE
App Store Review Team has just rejected my binary (Verification failed, cannot connect to the Apple ID server)

### ISSUE THREAD

**Issue by zoftify** [dooboolab/react-native-iap#1007]
### Version of react-native-iap
4.4.6

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
App Store Review Team is able to verify IAP purchases

### Actual behavior
App Store Review Team is facing issue connecting to the Apple ID Server: ![image](https://user-images.githubusercontent.com/56393200/81878422-a7b97580-9590-11ea-9cc1-8efb1d10fe74.png)
In fact, this popup is a system one, so I don't really understand why they aren't able to connect to the Apple ID server. Our in-house devices work just fine.

### Tested environment (Emulator? Real Device?)
iPhone running iOS 13.4.1 on Wi-Fi.

Any help is much appreciated. Thanks!

**Comment by zoftify** [comment]
The issue happens while requesting a purchase. I've just tried to create a brand new sandbox account and I faced exactly the same issue, but with a production account, it works like a charm (yeah, when the app is downloaded from TestFlight). Do we mess things up or something to be fixed in a library?
Thanks!

**Comment by zoftify** [comment]
The issue has been resolved

**Comment by bidetaggle** [comment]
> The issue has been resolved

Please describe your solution when you find it, it may be useful for other people facing the same issue than you
