### ISSUE TITLE
Debugging E_IAP_NOT_AVAILABLE error

### ISSUE THREAD

**Issue by patreu22** [dooboolab/react-native-iap#1010]
### Version of react-native-iap
4.4.8

### Version of react-native
0.59.9

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
- Calling `initConnection()` should return `true` 
- `getSubscriptions(["iapSku"])` should return purchase
- `requestSubscription("iapSku")` should return something else

### Actual behavior
- initConnection returns false
- getSubscriptions returns error: `TypeError: null is not an object (evaluating RNIapIos.getItems)`
- requestSubscriptions returns error: `TypeError: null is not an object (evaluating RNIapIos.getItems)`

In addition they throw `Possible Unhandled Promise Rejection: Error: E_IAP_NOT_AVAILABLE`

### Tested environment (Emulator? Real Device?)
Both

I never used this package before and setting up IAPs for the first time on React Native. Therefore it would be great if anybody knows how to debug this problem or lead me to the point to resolve it.

**Comment by patreu22** [comment]
For everybody who might run into trouble here, what did the trick on iOS for me was linking the project manually - it worked after cleaning the build folder and installing Pods manually as well, hope it's useful to anybody!

As a feature request for future development it would be nice to know if a rejection is caused by the local setup or by Apple, I guess in the first case it would be possible to add some note to the error message that connecting to the native code didn't work out properly.

**Comment by Melissaelyas1400** [comment]
UQD9lYqnu6R2RAtWlLp7q1iKpMSXcYg99zgTD9M1CpwblhRs
