### ISSUE TITLE
Cannot connect to iTunes Store in TestFlight

### ISSUE THREAD

**Issue by mcchrish** [dooboolab/react-native-iap#1011]
### Version of react-native-iap
4.4.8
### Version of react-native
0.62.2
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
When running `requestPurchase`, prompts TestFlight user for password. Then successfully process the purchase.
### Actual behavior
When running `requestPurchase`, prompts TestFlight user for password. Afterwards receives an E_UNKNOWN error and "Cannot connect to iTunes Store" message.

The real strange behavior is that when running `getPendingPurchaseIOS` it prompts for the password of the sandbox user I previously used on this device (but running on Xcode). Instead of prompting me password for the TestFlight user.

Something tells me something is getting mixed up in the background outside of our control. Maybe directly an issue with Apple.

Maybe related to https://github.com/dooboolab/react-native-iap/issues/975

### Tested environment (Emulator? Real Device?)
Real iPhone

**Comment by Ivanov89** [comment]
Same bug here !

Version of react-native-iap
`4.4.3`

Version of react-native
`0.61.2`

Platforms you faced the error (IOS or Android or both?)
iOS  - Real Device

Any feedback will be apreciated !
Thanks!

**Comment by hansol775** [comment]
same issue. 
but TestFilght It works.
not working simulator.

**Comment by hyochan** [comment]
Will this help?

https://forums.developer.apple.com/thread/90594#273543

**Comment by yemd** [comment]
The exact same problem is still happening to me.

**Comment by gkeenleyTest** [comment]
I'm getting errors when I run getPurchaseHistory(), but on TestFlight only. When I run it from my computer it works fine.
