### ISSUE TITLE
Google Play: Error: An unknown or unexpected error has occured. Please try again later.

### ISSUE THREAD

**Issue by j-cheung** [dooboolab/react-native-iap#1013]
### Version of react-native-iap
4.4.8
### Version of react-native
0.61.1
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Make purchase / subscription, return receipt from Google Play Billing
### Actual behavior
returns 

Error: An unknown or unexpected error has occured. Please try again later.
E_UNKNOWN 

### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
RNIap.requestSubscription('android.test.purchased',false) or my test subscription product id

My app is in the internal test track, subscription is active, not sure what else do I need to set up?

Thanks.

**Comment by j-cheung** [comment]
It didnt work on RedMi phone

**Comment by nl-danish** [comment]
Hi @j-cheung,

Were you able to find any solution for this? We seem to be having the same issue, and not able to troubleshoot, as we're on internal with the build.
