### ISSUE TITLE
About publishing the app

### ISSUE THREAD

**Issue by fabio-C** [dooboolab/react-native-iap#1015]
Just a simple question.

[This guide](https://medium.com/dooboolab/react-native-in-app-purchase-121622d26b67) say to "Upload apk with billing permission".

Does the apk need to be published (with status: released) in Google Play Store or just uploaded?

As my app is in the not ready to be released to public, should I create a "**Internal test track**" release?

**Comment by hyochan** [comment]
You don't have to publish your apk.
