### ISSUE TITLE
purchaseUpdatedListener spams and fires multiple times if the user has cancelled/expired subsciption

### ISSUE THREAD

**Issue by dbilgin** [dooboolab/react-native-iap#1016]
### Version of react-native-iap
4.4.9

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
purchaseUpdatedListener to not spam when it's declared

### Actual behavior
As soon as I attach `purchaseUpdatedListener` it is called 28 times, even though I do nothing at all related to payments apart from that.

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
User purchases the subscription, then when the subscription is cancelled/expired and the user redirects to the page where the `purchaseUpdatedListener` is set. This doesn't happen if the user hasn't purchased anything yet.

Is this normal behaviour?

**Comment by tomerdev** [comment]
Maybe you didn't finish your transaction? (using finishTransaction)
The purchaseUpdatedListener should keep sending the receipt until it has been finished.
But i've seen the purchaseUpdatedListener event called multiple times myself, I think it could be related to the react-native live reload.

**Comment by dbilgin** [comment]
ah okay, thank you so much @tomerdev.
