### ISSUE TITLE
[BUG][ANDROID][0.3.2] cannot find symbol purchaseList

### ISSUE THREAD

**Issue by kasterlod** [dooboolab/react-native-iap#102]
### Version of react-native-iap
0.3.2
### Expected behavior
android build with succeed
### Actual behavior
node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:236: error: cannot find symbol
 if (purchaseList != null && responseCode == BillingClient.BillingResponse.OK) {
### Steps to reprodue the behavior
react-native run-android with react-native-iap: 0.3.2

possible solutions:
There's probably char missing, shouldn't be here
`if (purchasesList != null `
instead of
`if (purchaseList != null `
in RNIapModule.java:236 ?

![screen shot 2018-04-09 at 10 25 08](https://user-images.githubusercontent.com/10712198/38487492-a108812e-3be0-11e8-8c64-1af597589f6e.png)

PR for fix: https://github.com/dooboolab/react-native-iap/pull/103

**Comment by dooboolab** [comment]
@kasterlod Sorry for that. I've seen your PR but closed it since you commited to `master` branch. Please do this to `dev` branch and we've updated our module to `0.3.3` fixing this mistake. But didn't commited to github waiting for your PR.
