### ISSUE TITLE
another issues about empty product list

### ISSUE THREAD

**Issue by fabio-C** [dooboolab/react-native-iap#1023]
I will open another issue about empty products list. I tried everything I read in this repo, but with no success. Maybe someone should publish an article or a step by step tutorial?

Here is what I tried:

1) Create sign apk for your application.
2) Upload your apk on Google play store with Billing permissions in Manifest.xml. I started a rollout, now is in pending publication.

![alpha release](https://user-images.githubusercontent.com/53861680/83118847-31a82900-a0cf-11ea-87c3-78a29e860b4c.png)
![alphaRelease2](https://user-images.githubusercontent.com/53861680/83118866-379e0a00-a0cf-11ea-8278-5b6fecd1d5c1.png)

3) Create a product.

![store](https://user-images.githubusercontent.com/53861680/83118970-60be9a80-a0cf-11ea-9359-7d0d2f426d6e.png)

4) I waited 24 hours.

Now when I tried to get my product:

```

//Item to purchase
const itemSkus = Platform.select({
	ios: [
                'com.catcodetest3.active_pro_mode'
	],
	android: [
		''com.catcodetest3.active_pro_mode'
	]
});

getItems = async() => {
      try {
      	const result = await RNIap.initConnection();
      	console.log('result', result);

         const products = await RNIap.getProducts(itemSkus);
         console.log('Products', products);

         this.setState({ productList: products });

      } catch (err) {
      	console.warn(err.code, err.message);
      }
}
```

I got:
```
result true
Products []
```

I tried also to remove com.catcodetest3 from the itemSkus:

```
android: [
    "active_pro_mode"
]
```

But it didn't work.

------------------------------------------------------------------------
Android 9
React Native 0.62.2
React Native IAP ^4.4.8

**Comment by igeeganage** [comment]
I'm having the same issue. Did you find any solution for this?

**Comment by fabio-C** [comment]
@igeeganage no

**Comment by fabio-C** [comment]
@igeeganage 
Now that the app is published, I can see the products.
My account is new, can be related to that, or they changed policy.

**Comment by rodcisal** [comment]
Any idea if this would work if I try to get products for a published app that I'm administrator of?
