### ISSUE TITLE
black background when start purchase

### ISSUE THREAD

**Issue by AlexSeoven** [dooboolab/react-native-iap#1024]
### Version of react-native-iap
4.4.9

### Version of react-native
0.62.2

### Platforms you faced the error (IOS or Android or both?)
android

### Expected behavior
like in checkout demo, with opacity

### Actual behavior
![Screenshot_1590920038](https://user-images.githubusercontent.com/42401342/83349958-3d028b00-a341-11ea-928f-4420b21dfc16.png)

### Tested environment (Emulator? Real Device?)
screen from emulator, but testers have same on real devices

### Steps to reproduce the behavior
just start purchase

how can i add some opacity to background? is there any config for that in android?

**Comment by happyfloat** [comment]
@AlexSeoven Having the same problem how, did you fix find a way to fix it?
