### ISSUE TITLE
The processing of a receipt has failed.

### ISSUE THREAD

**Issue by radoman93** [dooboolab/react-native-iap#1028]
### Version of react-native-iap
"react-native-iap": "^4.4.9"
### Version of react-native
"react-native": "~0.61.5"
### Platforms you faced the error (IOS or Android or both?)
iOS for now
### Expected behavior
Could not get receipt to validate is it due to running in sandbox?
### Actual behavior
The processing of a receipt has failed.
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
I make the simple purchase from the device, and IAPHUB on the phone shoot me the purchase was successful alert, shortly after I receive that my receipt could not be validated.

**Comment by BenjaminWatts** [comment]
Hi I've had this issue too - is it fixable?

**Comment by sagarhspl** [comment]
Hi I've same issue too - is there any solution?

**Comment by fazal26** [comment]
Facing Receipt Validation Error once I switch to Production Environment, any guideline for the fix ?
