### ISSUE TITLE
empty products array

### ISSUE THREAD

**Issue by jonasgroendahl** [dooboolab/react-native-iap#1030]
### Version of react-native-iap
4.4.9

### Version of react-native
0.62.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
I expect to get an array of products

### Actual behavior
I get an empty array

### Tested environment (Emulator? Real Device?)
I tested on simulator, real device and even test flight

### Steps to reproduce the behavior
The code:

```

const itemSkus = Platform.select({
  ios: [
    'productidtest',
    'testing'
  ],
  android: []
});

const Payment: React.FC = () => {
  useEffect(() => {

    const initialRun = async () => {
      const wei = await iap.initConnection();
    };

    initialRun();
  }, []);

  const getProducts = async () => {
    const products = await iap.getProducts(itemSkus);
    console.log('prods', products);
    Alert.alert(JSON.stringify(products));
  };

  return (
    <View>
      <Button onPress={getProducts}>
        <Typography>Get products</Typography>
      </Button>
    </View>
  );
};
```

I enable in-app purchases in Xcode, added the appropiate bundle id and added two entries for the in-app purchases in app store connect. the app is not released and they both say "Missing metadata" in the in-app purchases list view because no review screenshot. not sure if that matters?

**Comment by summonerriftofficial** [comment]
same

**Comment by ixuz** [comment]
Ensure that you've completely filled out the section: "Agreements, Tax and Banking". Otherwise you'll only see empty arrays.

**Comment by jonasgroendahl** [comment]
I didn't do that actually, I will give it a try :)

**Comment by jonasgroendahl** [comment]
that worked!

**Comment by daheeahn** [comment]
> Ensure that you've completely filled out the section: "Agreements, Tax and Banking". Otherwise you'll only see empty arrays.

Thanks!
