### ISSUE TITLE
There is a bug in version 4.4.9. After successful payment, the callback function registered by purchaseUpdatedListener is not called

### ISSUE THREAD

**Issue by summonerriftofficial** [dooboolab/react-native-iap#1031]
### Version of react-native-iap
4.4.9
### Version of react-native
0.62.2
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
purchaseUpdatedListener fire after purchase
### Actual behavior
Nothing happens
### Tested environment (Emulator? Real Device?)
Real Device

**Comment by hyochan** [comment]
Have you properly called `initConnection?

**Comment by CoSNaYe** [comment]
@hyochan thank you! After calling `initConnection` first, the issue resolved.

**Comment by hyochan** [comment]
@CoSNaYe Sounds great!

**Comment by bidetaggle** [comment]
Hi,

I'm facing the same problem and I don't really know how to properly call `initConnection`.
@CoSNaYe  Could you give us a snippet of your working solution? A PR to update the documentation's example in `README.md` would be highly appreciated as well :)
