### ISSUE TITLE
How to Start?

### ISSUE THREAD

**Issue by KawaljeetSBagga** [dooboolab/react-native-iap#1033]
I am a newbie to the IAP world. Can you please guide me to where do I need to register myself for android and iOS to set up my account for this? What keys or information or anything is needed by react-native-iap and where to add it? How does firebase come into the picture? How does one link his bank account? Where does one link his bank account? I understand the usage part of this library but I don't quite understand the pre-requites. Can somebody please help me?

**Comment by ixuz** [comment]
> Can you please guide me to where do I need to register myself for android and iOS to set up my account for this?
You'll need to register your own account on Google Play Console and Apple Connect Store, see links below:

Register your account and application on: [Google Play Console](https://play.google.com/apps/publish)
Register your account and application on: [App Store Connect](https://appstoreconnect.apple.com/)

> What keys or information or anything is needed by react-native-iap and where to add it?

You'll have to register your iOS app for "In-App Purchases" capabilities in Xcode and in Apple Developer Portal.
You'll also have to completely fill out the "Agreements, Tax and Banking" in App Store Connect..

> How does firebase come into the picture?

What do you mean?

> How does one link his bank account?

Register your bank account to receive royalties on: [Google Play Console](https://play.google.com/apps/publish)
Register your bank account to receive royalties on: [App Store Connect](https://appstoreconnect.apple.com/)

> I understand the usage part of this library but I don't quite understand the pre-requites. Can somebody please help me?

I strongly recommend to read the following resources to understand the nuances of both Apple IAP and Google IAP, this will give you good insight on all steps needed to be completed to successfully implement IAP into your application (with or without react-native-iap).

- https://developer.apple.com/documentation/storekit/in-app_purchase
- https://developer.android.com/google/play/billing

**Comment by rodrigopasc** [comment]
@ixuz Do I have to change something in the code before publishing the app to the store? I mean, set an env for production or something like that?

I dind't find that in the docs.

Thank you very much!

**Comment by Pinwheeler** [comment]
@rodrigopasc Is your question "how do I publish a (React Native) app to the store?" That's sort of off topic. However, you just do the normal Android and deployments from within their individual projects. That information is abundantly available.

**Comment by rodrigopasc** [comment]
My problem is with iOS. Apparently it is not generating its receipt. (Only in production, in Test Flight and development works fine)

**Comment by Pinwheeler** [comment]
If you haven't already, you might try setting up a sandbox user https://help.apple.com/app-store-connect/#/dev8b997bee1 That might help you hone in on the problem.

**Comment by ixuz** [comment]
> My problem is with iOS. Apparently it is not generating its receipt. (Only in production, in Test Flight and development works fine)

We'll probably need a more detailed explanation of the problem to pinpoint the issue.

* Make sure that the purchase flow complete (StoreKit) for the end-user.
* When the purchase is completed, transmit it securely to your server.
* And if you're dealing with subscriptions, you should handle Real-Time Server Notifications from Apple Connect Store (basically Apple pushing updates to your server without involving the end-user).

**Comment by rodrigopasc** [comment]
I am validating the receipts in my backend, like the Node.js example mentioned in the README.

For Android is working perfectly fine. But iOS, only in production is not generating any receipt.

During development and in Test Flight (the production build) works fine.
