### ISSUE TITLE
Google Play cancel subscription and asking about confirmation

### ISSUE THREAD

**Issue by rmikhailenko** [dooboolab/react-native-iap#1041]
### Version of react-native-iap
4.4.3
### Version of react-native
0.62.2
### Platforms you faced the error (IOS or Android or both?)
Android
### Description
On Android after i bought subscription, it canceled after few days. In Google Play i can see that i need to confirm subscription or it gonna be canceled. Maybe i missed something in implementation?
I also trying update to latest version 4.5.0, but i get the same result.

**Comment by hyochan** [comment]
You should `acknowledge` the purchase which I've exposed as a `finishTransaction`
