### ISSUE TITLE
react-native-iap product list is empty

### ISSUE THREAD

**Issue by xhsynx** [dooboolab/react-native-iap#1042]
### Code
import React, {useEffect} from 'react';
import {SafeAreaView, Platform, Button} from 'react-native';
import * as RNIap from 'react-native-iap';

const itemSkus = Platform.select({
  ios: ['com.example.coins100'],
  android: ['com.example.coins100'],
});

export default function App() {
  useEffect(() => {
    const cleanup = RNIap.initConnection()
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
      });

    const products = RNIap.getProducts(itemSkus)
      .then((res) => {
        console.warn(res);
      })
      .catch((err) => {
        console.warn(err);
      });

    return () => {
      cleanup;
      products;
    };
  }, []);
  const buy = () => {
    RNIap.requestPurchase('com.example.coins100');
  };
  return (
    <SafeAreaView>
      <Button title="Buy" onPress={buy} />
    </SafeAreaView>
  );
}

**Comment by JordaoMemoria** [comment]
Same problem

**Comment by hyochan** [comment]
```
 await RNIap.initConnection()
```

You shuold resolve the promise!

**Comment by xhsynx** [comment]
### What is wrong this code. it is still returning empty array of product. Could you please help.

import React, {useEffect} from 'react';
import {SafeAreaView, Platform, Button} from 'react-native';
import * as RNIap from 'react-native-iap';
const itemSkus = Platform.select({
  ios: ['com.example.coins100'],
  android: ['com.example.coins100'],
});
export default function App() {
  useEffect(() => {
    async function build() {
      const result = await RNIap.initConnection();
      console.log(result); //true
      const products = await RNIap.getProducts(itemSkus);
      console.log(products); //[]
    }

    build();
  }, []);

  const buy = async () => {
    await RNIap.requestPurchase('com.example.coins100');
  };

  return (
    <SafeAreaView>
      <Button title="Buy" onPress={buy} />
    </SafeAreaView>
  );
}

**Comment by JordaoMemoria** [comment]
const result = await RNIap.initConnection();
        console.log('result', result);
        const products = await RNIap.getSubscriptions(itemSkus)
        console.log('Products: ',products)

I tried but it is not working, please help us

**Comment by dennis3124** [comment]
Make sure you have your bundle id set correctly. i was using iOS schemes to set different bundle IDs so it wasn't matching the one in itunes connect
