### ISSUE TITLE
I'm not getting consumable products in getProduct() call, I'm only getting auto-renewal product. Any idea?

### ISSUE THREAD

**Issue by agrawalsurabhi89** [dooboolab/react-native-iap#1043]

**Comment by hakkikonu** [comment]
did you cleared for sale your consumable products on App Store Connect?

**Comment by agrawalsurabhi89** [comment]
> did you cleared for sale your consumable products on App Store Connect?

I have ticked Cleared for sale but today i unticked but still not getting the consumable products? Any idea?

**Comment by hakkikonu** [comment]
Can you share your code here?

**Comment by agrawalsurabhi89** [comment]
> Can you share your code here?

<img width="778" alt="Screenshot 2020-07-20 at 3 20 20 PM" src="https://user-images.githubusercontent.com/56863342/87924796-fdccfc80-ca9c-11ea-84c8-049c052244c3.png">
Here is the call for getProducts

// Subscription items
const itemSubs = Platform.select({
    ios: [
        "monthly_hosting",
        "transaction_one_time_payment" // this should be the productid from Apple Itunes.
    ],
    android: [
        "INSERT YOUR SUBSCRIPTION ID ANDROID"
    ]
});

**Comment by agrawalsurabhi89** [comment]
Thanks @hakkikonu : It's my mistake .. I have not added pricing for the Consumable Product. That's why it was not coming in the getProduct method. 

Apart from that, I have one more question, Dynamic Pricing is not possible in iOS in-app purchase
