### ISSUE TITLE
How to handle auto renewable subscriptions?

### ISSUE THREAD

**Issue by kelokchan** [dooboolab/react-native-iap#1046]
### Version of react-native-iap
4.4.9
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
iOS
### Tested environment (Emulator? Real Device?)
Sandbox environment
### Steps to reproduce the behavior

I have the below code snippet to handle subscription purchase
```
// On button press
requestPurchase(sku);

// Purchase updated listener
this.purchaseUpdateSubscription = purchaseUpdatedListener((purchase) => {
      console.log('purchaseUpdatedListener', purchase);
      const receipt = purchase.transactionReceipt;
      await finishTransaction(purchase);
      await Firebase.updateUser({
        'subscription.ios': purchase
      })
    });

```

So far I was able to perform purchase and store the receipt onto Firebase. But my question is do I need to call `getAvailablePurchases` on every app launch to store the latest purchase receipt? Or do I only need to store the receipt when the user purchases the subscription for the first time? Also, how do I validate if the subscription has expired?

**Comment by hakkikonu** [comment]
I'am also wondering this approach. How can I validate if the subscription has expired? Should I check getAvailablePurchases() everytime?

**Comment by ziyoshams** [comment]
This is usually done using webhooks. For Apple you can enable [server-to-server notifications](https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/enabling_server-to-server_notifications) that will communicate with your server. Google has something similar, but setting it up is much more complicated and there is no docs on that. Android Developers has a basic doc [here](https://developer.android.com/google/play/billing/rtdn-reference), but what you want is a Pub/Sub system that google has.

Also this [StackOverflow question](https://stackoverflow.com/questions/60015435/server-side-validation-of-ios-and-android-auto-renewable-subscriptions-using-ser) has some good information

**Comment by camel113** [comment]
To validate if the subscription I'm doing that
```
const result = await validateReceiptIos(receiptBody, true);
const lastSubscriptionBasic = result.latest_receipt_info
        .filter(item => item.product_id === "subscription_basic") // keep only the "subscription_basic" subscriptions
        .sort((a, b) => b.expires_date_ms - a.expires_date_ms)[0]; // sort by expiration date and get the first one
const isSubscriptionBasicValid = lastSubscriptionBasic.expires_date_ms > moment() // check if expiration date is before now
```

**Comment by daithinh2401** [comment]
Hi @camel113, can you please explain what is the `receiptBody`, how can i correctly pass it to `validateReceiptIos()` ? Because I see it's type is `Record<string, unknown>`, not just a String
And how to work on Android ?
