### ISSUE TITLE
RNIap.getAvailablePurchases() returns different number of purchased items on reload

### ISSUE THREAD

**Issue by hakkikonu** [dooboolab/react-native-iap#1047]
Why result of `RNIap.getAvailablePurchases()` changing when I reload the page? I have subscription items on IOS.
### Version of react-native-iap
"react-native-iap": "^4.5.0",

### Version of react-native
"react-native": "0.63.1",

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
I don't know is it natural behavior or not.

### Actual behavior
Please clearly explain why this happen?

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior

call `RNIap.getAvailablePurchases()` in componentDidMount more than one time ( reload page). It returns different number of Purchases.

**Comment by sutefan1** [comment]
I've experienced similar behavior. `getAvailablePurchases` supposed to return a list of non-consumable or not yet consumed products, but it returns randomly products. However, `getPurchaseHistory` works as expected and returns all purchases.
