### ISSUE TITLE
How to detect expired auto renewable subscriptions?

### ISSUE THREAD

**Issue by hakkikonu** [dooboolab/react-native-iap#1048]
I'm currently using react-native-iap 4.5.0 and fetching my subscriptions with `RNIap.getAvailablePurchases()`

Also on my back-end server I'm requesting to https://sandbox.itunes.apple.com/verifyReceipt Apple endpoint for receipts.

That endpoint returns all receipts with this data. With some logic I can handle subscription status of my users at back-end. But it is more complicated in some situations.

```
{
                "quantity": "1",
                "product_id": "XXX",
                "transaction_id": "1000000694388870",
                "original_transaction_id": "1000000692806652",
                "purchase_date": "2020-07-14 15:06:37 Etc/GMT",
                "purchase_date_ms": "1594739197000",
                "purchase_date_pst": "2020-07-14 08:06:37 America/Los_Angeles",
                "original_purchase_date": "2020-07-17 10:42:15 Etc/GMT",
                "original_purchase_date_ms": "1594982535000",
                "original_purchase_date_pst": "2020-07-17 03:42:15 America/Los_Angeles",
                "expires_date": "2020-07-14 15:11:37 Etc/GMT",
                "expires_date_ms": "1594739497000",
                "expires_date_pst": "2020-07-14 08:11:37 America/Los_Angeles",
                "web_order_line_item_id": "1000000054037348",
                "is_trial_period": "false",
                "is_in_intro_offer_period": "false"
            },
```
My questions is;
How can I use only my app to check subscription's expire status without back-end service?

**Comment by jonasgroendahl** [comment]
I'm looking into the same thing right now, 

this seems useful: https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store

**Comment by hakkikonu** [comment]
I already doing this. I'm validating receipts at Apple servers. My questions is; is it possible to check only on device. As I know on Apple side it is possible. Because we only send post request to apple with receipt and secret key, but on Google side we need to have Google Play API.

**Comment by camel113** [comment]
I guess you could validate a subscription with the following code:
```
const result = await validateReceiptIos(receiptBody, true);
const lastSubscriptionBasic = result.latest_receipt_info
        .filter(item => item.product_id === "subscription_basic") // keep only the "subscription_basic" subscriptions
        .sort((a, b) => b.expires_date_ms - a.expires_date_ms)[0]; // sort by expiration date and get the first one
const isSubscriptionBasicValid = lastSubscriptionBasic.expires_date_ms > moment() // check if expiration date is before now
```

**Comment by hakkikonu** [comment]
why we are filtering latest_receipt_info? im validating receipt on my backend and latest_receipt_info always a single object. also your approach is very nice. afaik for google side, backend is a must. is not? because we’re using service account and google play billing api.

**Comment by camel113** [comment]
What I get from `const result = await validateReceiptIos(receiptBody, true)` is an array
