### ISSUE TITLE
how to identify payment is success or not when payment is done

### ISSUE THREAD

**Issue by cyberlobedeveloper** [dooboolab/react-native-iap#1052]
### Version of react-native-iap
4.4.4
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior

1) I use "finishTransactionIOS" method for the transaction. With particular function I am not able to get purchased item from apple so is there any mistake by me here to call function. Please find attached sources as well to check.
2) When open app at that using "requestPurchase" this method. With this function also I am not able to get product purchased by user. It is working fine with sandbox environment by not working with live. 

note : for android it works fine.
1. click purchase
![Screen Shot 2020-07-21 at 8 25 42 PM](https://user-images.githubusercontent.com/5137069/88071028-fa1aa200-cb90-11ea-8c8e-24ab9842da77.png)
2. check purchased (componentDidMount )
![Screen Shot 2020-07-21 at 8 27 16 PM](https://user-images.githubusercontent.com/5137069/88071118-0f8fcc00-cb91-11ea-8e94-0e4c93d11714.png)

**Comment by hyochan** [comment]
Also asked in #1100

**Comment by hyochan** [comment]
Well, the question seems pretty ambiguous. The payment is successful when it comes to `purchaseUpdatedListener`. You are calling `finishTransactionIOS` just to acknowledge the purchase so that it won't refund.
