### ISSUE TITLE
Retry logic for InitConnection with hooks

### ISSUE THREAD

**Issue by floelm** [dooboolab/react-native-iap#1054]
Hey,
are there any best practices how to handle failed connections to the billing services?
e.g. you get "Billing is unavailable." and i want to retry after some seconds, do you just wrap some custom timeout logic around it?

Thanks in advance

**Comment by hyochan** [comment]
Currently, I think what you came up with is the solution out so far (`timeout`).

**Comment by floelm** [comment]
ok thank you!

**Comment by roblingle** [comment]
Can someone explain this a little more? With hooks we're not supposed to call `initConnection()`, so what are we wrapping in a timeout?
