### ISSUE TITLE
How to prevent purchase screen for already purchased non-consumable

### ISSUE THREAD

**Issue by damialajogun** [dooboolab/react-native-iap#1055]
### Version of react-native-iap
4.3.2
### Version of react-native
0.59.10
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Click on already purchased non-consumable -> Game starts
### Actual behavior
Click on already purchased non-consumable -> Apple pay pops up -> "you've already purchased this. Would you like to get it again for free?" -> Game starts
### Tested environment (Emulator? Real Device?)
Real Device (App is in Production)
### Steps to reproduce the behavior
Hi everyone, sort of a long read so apologies in advance. I have a game app that has non-consumable products available for purchase. Ideally, users should purchase only once and then not have to go through the payment process again for that same product. However currently, when a user buys a non-consumable and wants to play the game again, Apple Pay still pops up as if the user would be charged. Only after they take the risk of attempting to purchase again do they see a pop up that says "you've already purchased this. Would you like to get it again for free?". Most users probably do not know that they won't be charged again because Apple Pay pops up and understandably may not want to risk paying again for something they should own. 
I would like to have a better user experience here, and so my question is, **is there a way to check if a user has already purchased a non-consumable and then go straight to the game as a result?** I'm sure there's a connection between users and what they have purchased seeing as the pop up later on says that they can play again for free, but I would like to eliminate the second Apple Pay pop-up in the first place.
My code is below:
```
async componentDidMount() {
        try {
            const result = await RNIap.initConnection();
            await RNIap.consumeAllItemsAndroid();
            const products: Product[] = await RNIap.getProducts(itemSkus);
            this.setState({ products }, () => {console.log(this.state.products)});
        } catch (err) {
            console.warn(err.code, err.message);
        }
```

        this.purchaseUpdateSubscription = purchaseUpdatedListener(async (purchase: InAppPurchase | SubscriptionPurchase | ProductPurchase) => {
            console.log('purchaseUpdatedListener', purchase);
            const receipt = purchase.transactionReceipt;
            if (receipt) {
                try {
                    // if (Platform.OS === 'ios') {
                    //   finishTransactionIOS(purchase.transactionId);
                    // } else if (Platform.OS === 'android') {
                    //   // If consumable (can be purchased again)
                    //   consumePurchaseAndroid(purchase.purchaseToken);
                    //   // If not consumable
                    //   acknowledgePurchaseAndroid(purchase.purchaseToken);
                    // }
                    const ackResult = await finishTransaction(purchase);
                } catch (ackErr) {
                    console.warn('ackErr', ackErr);
                }

                this.setState({ receipt }, () => this.goNext());
            }
        },
        );

        this.purchaseErrorSubscription = purchaseErrorListener(
            (error: PurchaseError) => {
                console.log('purchaseErrorListener', error);
            },
        );
    }
    componentWillUnmount() {
        if (this.purchaseUpdateSubscription) {
            this.purchaseUpdateSubscription.remove();
            this.purchaseUpdateSubscription = null;
        }
        if (this.purchaseErrorSubscription) {
            this.purchaseErrorSubscription.remove();
            this.purchaseErrorSubscription = null;
        }
    }`

Any help is greatly appreciated!

**Comment by sutefan1** [comment]
Hey @damialajogun ,

check out the documentation for `getPurchaseHistory` and `getAvailablePurchases`. The first one returns all purchases regardless the consumption status (like a list of receipts) and the latter supposed to return all purchases either non-consumable or not consumed yet (which isn't completely working for me and there are some issues with subscriptions, so I would recommend the first one for basic products. No warranty for subs as I haven't used them so far).

With that list, you can check for a certain `productId` for example an then start the game instead of calling `requestPurchase`. 

Hope that helps.

**Comment by damialajogun** [comment]
@sutefan1 This worked. Thank you so much!
