### ISSUE TITLE
RNIap.getSubscriptions(skuId) returns empty array. Am I missing something?

### ISSUE THREAD

**Issue by hakkikonu** [dooboolab/react-native-iap#1056]
I created a renewable subscription product on Google Play Developer console and its status is active.

I published alpha release but when I try to fetch that subscription item with `RNIap.getSubscriptions(skuId)`, array is empty.

On IOS side, it is working.

My steps;

* Give billing permission on AndroidManifest file
* Build with signed apk
* Create app on Google Play Console
* Release an alpha release
* Add a tester gmail account on Google Play Console
* Test on real device with that tester gmail account
* Wait more than 20 hours

result = empty array for products.

Am I missing something?

**Comment by infazA** [comment]
Still Im getting empty array, May I know how did you resolve this issue ?

**Comment by rjuevesano** [comment]
> Still Im getting empty array, May I know how did you resolve this issue ?

Me too.

**Comment by infazA** [comment]
@rjuevesano Bro, now its working for me. you have to upload your apk to Play store and it should be approved. then only it will work.

<img width="994" alt="Screenshot 2020-09-14 at 09 05 05" src="https://user-images.githubusercontent.com/7043609/93041190-90d37e80-f669-11ea-9f74-bd01bbc2a795.png">

**Comment by rjuevesano** [comment]
> @rjuevesano Bro, now its working for me. you have to upload your apk to Play store and it should be approved. then only it will work.
> 
> 
> 
> <img width="994" alt="Screenshot 2020-09-14 at 09 05 05" src="https://user-images.githubusercontent.com/7043609/93041190-90d37e80-f669-11ea-9f74-bd01bbc2a795.png">
> 
> 

Yeah. I used different bundleId/applicationId that's why it's not showing.
