### ISSUE TITLE
[iOS] promisesByKey is not thread-safe

### ISSUE THREAD

**Issue by lwansbrough** [dooboolab/react-native-iap#106]
### Version of react-native-iap
0.3.0-beta3

### Expected behavior
This dictionary can be accessed by multiple threads at the same time

### Actual behavior
This dictionary crashes when accessed by multiple threads at the same time.

### Steps to reproduce
Hard to reproduce, but here's a log:

<img width="940" alt="screen shot 2018-04-09 at 1 40 44 pm" src="https://user-images.githubusercontent.com/186674/38521940-f43e7e96-3bfb-11e8-84f2-3ccb809460a8.png">

The fix would probably be a semaphore or lock inside those add/remove methods.

**Comment by lwansbrough** [comment]
FYI I'm not working on a fix for this right now.

**Comment by JJMoon** [comment]
Thank you for your help. I will check.

**Comment by JJMoon** [comment]
@lwansbrough Looks like you got this error when you restore non-consumable purchases.
Did you add some other actions after you start the first action?

**Comment by JJMoon** [comment]
@lwansbrough I added some sync queue to manage the actions. I hope you check the source. It's on the PR.

**Comment by JJMoon** [comment]
This issue is applied on 1.0.4.
