### ISSUE TITLE
Google Play Billing Library 3.0

### ISSUE THREAD

**Issue by rammuk** [dooboolab/react-native-iap#1061]
Hi,

Is there a plan to upgrade google play billing library to version 3?

[https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html](url)

Thanks
Ram

**Comment by BlackbitNeueMedien** [comment]
I'd be interested in that, too. We have received a message from the Google Play Team with the following information.
It's about two settings that are mandatory as of November 1st. 

https://2.bp.blogspot.com/-cZmiQUESPdk/XvEUB7yxOSI/AAAAAAAAI74/_yFvnDbro2QR0xd9vymIweStskWkf2ynwCLcBGAsYHQ/s1600/Untitled%2Bdocument%2B%252812%2529.png

How is this handled with react-native-iap.

https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html

**Comment by hyochan** [comment]
What gradle version would this be? I thought we are already on version 3 if I am correct.
