### ISSUE TITLE
RefreshItems No Purchases Found

### ISSUE THREAD

**Issue by safciplak** [dooboolab/react-native-iap#1063]
### Version of react-native-iap
4.5.0
### Version of react-native
0.62.2
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Get Items
### Actual behavior
throw excepton RefreshItems No Purchases Found
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Just only run

**Comment by rizshivalli** [comment]
I have the same problem,
I have even submitted a beta release in android studio and it has been approved for over 4 days but still it is showing no purchases found (iOS working as expected).
How do we resolve this?

**Comment by rizshivalli** [comment]
````
  const initilizeIAPConnection = async () => {
    await initConnection()
      .then(async (connection) => {
        consumeAllItemsAndroid();
        await getItems();
        console.log('IAP result', connection);
      })
      .catch((error) => {
        console.warn(`IAP ERROR ${error.code}`, error.message);
      });
  };

  const getItems = async () => {
    try {
      const subscriptions = await getSubscriptions(itemSkus);
      console.log('Products', subscriptions);
      setSubscriptions(subscriptions);
    } catch (err) {
      console.warn(err.code, err.message);
    }
  };
  useEffect(() => {
    initilizeIAPConnection();
  }, []);

````

Try this.

I was able to resolve my issue with the above code
