### ISSUE TITLE
Empty Array after using getProducts()

### ISSUE THREAD

**Issue by mkamadeus** [dooboolab/react-native-iap#1065]
I'm currently having a problem when using this library related to the `getProducts()` function.

### Version of react-native-iap
I'm using version `4.5.0`.

### Version of react-native
I'm using version `0.63.1`.

### Platforms you faced the error (IOS or Android or both?)
Faced this problem on `Android`.

### Expected behavior
`initConnection()` : Showing `true` as a result.
`getProducts()` : Getting the list of active items registered on Google Play Developer Console.

### Actual behavior
`initConnection()` : Showing `true` as a result.
`getProducts()` : Getting an _empty array_ :(

### Tested environment (Emulator? Real Device?)
I've tested this using a *real device*, as suggested by other issues.

### Steps to reproduce the behavior
1. Add the `BILLING` permission to `AndroidManifest.xml` as follows:

In the `src/debug/` and `src/main/` folder I added both of this line.
```xml
<uses-permission android:name="com.android.vending.BILLING" />
```

2. Making a simple button using React Native, then have the button do an `onPress` action.
3. Create the `onPress` function to be tested. I created this to test:
```js
  const itemSkus = Platform.select({
    android: ['storeticket_0', 'storeticket_1', 'storeticket_2'],
  });
  ...
  const handleSubscription = async () => {
    try {
      setProcessing(true);

      await initConnection()
        .then(async (conn) => {
          console.log(conn); // Expected and Actual outputs true!
          return await getProducts(itemSkus);
        })
        .then((test) => {
          console.log(test); // Outputs an empty array (on my device)
          setProcessing(false);
        });
    } catch (err) {
      setProcessing(false);
    }
  };
```
My SKUs:
![image](https://user-images.githubusercontent.com/40513202/89267094-f98a0d00-d660-11ea-8a15-540466ae6eca.png)

4. Upload the APK file after building to the Play Console.

What I've been doing is following several guides and issues all over the place, but I have no success with it :( Here's what I've tried so far:
- Some people said that I'm required to wait several hours/days for the products to register on the console (Source: [this SO post](https://stackoverflow.com/questions/59486340/react-native-iap-getproducts-return-empty-array)). Waited for almost a week, still doesn't work.
- Fixed my codebase so the package name matches the package name on the Play Console, but still no luck.

Did I do something wrong? Or maybe the review time is just very long in my case? As in the console it's being announced that they are currently taking longer to review apps. My current state of the app on the Play Console:
![image](https://user-images.githubusercontent.com/40513202/89267809-e88dcb80-d661-11ea-81ac-a0666d7bc865.png)

What else do I need to do and setup in order to test for at least getting the in app products and for further testing (like testing the payment system)? Thanks in advance! :)

**Comment by kennguyen1506** [comment]
Hi there, i dont see anything wrong after looking over your code.
However I would suggest you check the status of your app on Google Play Console. We need google to complete its pending review before the API for your store items to be available for you to fetch.

It could take couple days though its best to wait and work on some other tasks now.

**Comment by mkamadeus** [comment]
@kennguyen1506 I see, thanks for the response. I'll wait for the status to be changed. I'll report back when it does.

**Comment by mkamadeus** [comment]
Sorry for the late reply, can confirm that may code already works and it is required to wait your app to be approved in the Play Console. Thanks for the help!

**Comment by puneetkansal04** [comment]
@mkamadeus @kennguyen1506 I am using react-native-iap for iOS the latest version 12.10.5 and I am getting empty array? is it required to get IAP plans approve on the App Store only then I can get products. But if I will do this how can I test my app to do code further without getting this in my first version?

**Comment by timothyerwin** [comment]
> @mkamadeus @kennguyen1506 I am using react-native-iap for iOS the latest version 12.10.5 and I am getting empty array? is it required to get IAP plans approve on the App Store only then I can get products. But if I will do this how can I test my app to do code further without getting this in my first version?

Exactly...this is confusing. In iOS the products are available before any approval. Seems Google has the cart before the horse here?

**Comment by timothyerwin** [comment]
Looking at the setup in Google Play Console it looks like they will approve for a closed track where you can do the testing before going live...I guess I'll find out in a minute lol

**Comment by son157** [comment]
any updates on this issue? Seems Google still wants to approve for a closed track to test

**Comment by Ali-Raza-Gill** [comment]
now i'm facing this issue, in my case getproduct() works on ios but gives empty array in android, i check and tested all the things, all things are ok and working well, but i get empty array, my code is this 	
export const availableProducts=async()=>await getProducts({skus:Object.values(Platform.OS==='android'?
VERBA_SUBSCRIPTION_OBJ.ANDROID:VERBA_SUBSCRIPTION_OBJ.IOS)}) 

and my sku is this : export const VERBA_SUBSCRIPTION_OBJ = {
	ANDROID: {
		MONTHLY: "sub_test_monthly",
		YEARLY: 'sub_test_yearly'
	},
	IOS: {
		MONTHLY: Config.VERBA_MONTHLY,
		YEARLY:  Config.VERBA_YEARLY
	}
}

so why i face this error, in google play console the status is active,
