### ISSUE TITLE
Promoted products on iOS not working since 4.4.1

### ISSUE THREAD

**Issue by vitali-kastsiuk** [dooboolab/react-native-iap#1066]
### Version of react-native-iap
4.5.2

### Version of react-native
0.62.2

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
I expect popup that asks to buy product after paste to safari 
`itms-services://?action=purchaseIntent&bundleId=<my_app_bundle_id>&productIdentifier=<product_id>`

### Actual behavior
Nothing happens with react-native-iap versions after 4.4.1

### Tested environment (Emulator? Real Device?)
iPhone 7 Plus, ios 13.6

### Steps to reproduce the behavior
I test like this - paste to safari 
`itms-services://?action=purchaseIntent&bundleId=<my_app_bundle_id>&productIdentifier=<product_id>`

I followed docs to configure ios promoted products
https://github.com/dooboolab/react-native-iap#how-do-i-handle-promoted-products-in-ios
(For 4.4.1 i add additional code to AppDelegate)
https://github.com/dooboolab/react-native-iap/tree/4.4.4#how-do-i-handle-promoted-products-in-ios

Am I doing something wrong? Mb i should test promoted products in other way, without `itms-services` link. Help please!

**Comment by EgorKazachenko** [comment]
bump :)

**Comment by vitali-kastsiuk** [comment]
https://github.com/dooboolab/react-native-iap/issues/1094#issuecomment-683320452
should use RNIap.initConnection();
