### ISSUE TITLE
Purchase with "Slow test card. Approves after a few minutes" triggers 2 consecutive succesful event on purchaseUpdatedListener

### ISSUE THREAD

**Issue by AmauryLiet** [dooboolab/react-native-iap#1074]
### Version of react-native-iap
4.5.2

### Version of react-native
0.62.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
When making a consummable purchase with "Slow test card. Approves after a few minutes", I expect to receive 1 success event on the purchaseUpdatedListener

### Actual behavior
2 events are send (~100ms apart), with 100% identical data

(I did not test with a non-consummable purchase, neither for subscriptions, as my app does not include any)

### Tested environment (Emulator? Real Device?)
Real Device
App published in closed alpha track
Licensed tester account (to get access to the fake card)

### Steps to reproduce the behavior
As stated above:
- make a consummable purchase with a "Slow test card. Approves after a few minutes" card
- either keep the app opened **or not** during the process
- the callback you passed to purchaseUpdatedListener will be called twice

----

Thanks for the great lib!

Hopefully I could get some time soon to investigate further

**Comment by AmauryLiet** [comment]
since I have been calling `initConnection` & `consumeAllItemsAndroid` on mount, I am unable to reproduce the issue. Maybe worth adding `initConnection` in the README examples?

**Comment by hrishiakhade** [comment]
@AmauryLiet  I am also calling initConnection & consumeAllItemsAndroid on mount . I am still facing this issue
