### ISSUE TITLE
Products are priced by default rather than in local currency

### ISSUE THREAD

**Issue by jeremyhalin** [dooboolab/react-native-iap#1075]
### Version of react-native-iap
4.5.2

### Version of react-native
0.62.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
`localizedPrice` should include taxes (20% in France for my case)

### Actual behavior
`localizedPrice` doesn't include taxes, so for example a €0.80 product displays as €0.80 in my app, whilst with taxes it shoud be a price of €0.99 in France.

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
1. create products on Google Paly Console
2. display those products in the app
3. check price in `product.localizedPrice`

**Comment by jeremyhalin** [comment]
It's working now... I've change absolutely nothing. If someone knows where it comes from. I'm closing this issue.

**Comment by hannojg** [comment]
Hm, experiencing the same :/
