### ISSUE TITLE
We’ve detected that your package ... is not always acknowledging in-app purchases or subscriptions. Starting with Billing Library 2.0, all purchases must be acknowledged within 3 days or they will be automatically refunded. 

### ISSUE THREAD

**Issue by cristea2017** [dooboolab/react-native-iap#1076]
### Version of react-native-iap
` "react-native-iap": "^4.5.2",`
### Version of react-native
`react-native: 0.61.2`
### Platforms you faced the error (IOS or Android or both?)
Android
### Tested environment (Emulator? Real Device?)
* real device
### Steps to reproduce the behavior
---

In `componentDidMount() {` 

```
 this.purchaseUpdateSubscription = purchaseUpdatedListener(async purchase => {
      this.billingPlugin.validateSubscription(purchase, success => {
        if (Platform.OS == 'android') {
          try {
            finishTransaction(purchase).then(e => {
```
according to documentation finishTransaction 

> This method works for both platforms and is recommended since version 4.1.0 or later. Equal to finishTransactionIOS + consumePurchaseAndroid and acknowledgePurchaseAndroid.

in response of finishTransaction i get this:
![Screenshot 2020-08-17 at 13 01 11](https://user-images.githubusercontent.com/28201006/90384456-3bb44500-e08a-11ea-9e70-d505cd10d400.png)

After last update on google play we received this alert:

> We’ve detected that your package com.craft .... is not always acknowledging in-app purchases or subscriptions. Starting with Billing Library 2.0, all purchases must be acknowledged within 3 days or they will be automatically refunded. 

But i call finish transaction that contains  acknowledge ...
So is this a bug in library or i am doing somethink wrong ?
Please help )
 
![Screenshot 2020-08-17 at 12 34 26](https://user-images.githubusercontent.com/28201006/90381423-073e8a00-e086-11ea-85df-5565b06aa68a.png)

**Comment by cristea2017** [comment]
Ok thanks for help #_# :
Solution :

i called  finishTransaction(purchase) above this one ` this.billingPlugin.validateSubscription(purchase, success => {`


References : 
[https://developer.android.com/google/play/billing/test#testing-subscriptions](url)

Also i found my tester account and verify subcription status:

**Comment by cristea2017** [comment]
Ok thanks for help #_# :
Solution :

i called  finishTransaction(purchase) above this one ` this.billingPlugin.validateSubscription(purchase, success => {`


References : 
[https://developer.android.com/google/play/billing/test#testing-subscriptions](url)

**Comment by Hasham24** [comment]
> Ok thanks for help #_# :
> Solution :
> 
> i called finishTransaction(purchase) above this one ` this.billingPlugin.validateSubscription(purchase, success => {`
> 
> References :
> [https://developer.android.com/google/play/billing/test#testing-subscriptions](url)

Right Now I have the exact same issue and the link you provide me it's giving me nothing so  kindly if you share your code it will be helpful and much appreciated. Thanks

**Comment by cristea2017** [comment]
> Right now I have the same issue with the latest version 8.2.2. @Hasham24 / @cristea2017 Could you please help me.. Thank you..

hi can you show your code ?

**Comment by mathews-p** [comment]
Tried _**finishTransaction**_ but it not acknowledged the purchase..

async componentDidMount(thisObj) {
    thisObjSet = thisObj;    
    try {
      await RNIap.initConnection();
      if (Platform.OS === 'android') {
        await RNIap.flushFailedPurchasesCachedAsPendingAndroid();
      } else {
        await RNIap.clearTransactionIOS();
      }
    } catch (err) {
      console.warn(err.code, err.message);
    }
    purchaseUpdateSubscription = purchaseUpdatedListener(
        async (purchase: InAppPurchase | SubscriptionPurchase) => {        
        const receipt = purchase.transactionReceipt
            ? purchase.transactionReceipt
            : purchase.originalJson;      
        
       if (receipt) {          
            try {
            await this.processPurchase(purchase, thisObjSet);
            const ackResult = await finishTransaction(purchase);          
            } catch (ackErr) {
            console.warn('ackErr', ackErr);
            }        
        }
        },
    );
};

**Comment by Hasham24** [comment]
@mathews-p sure you can approach me here so I can help you out,
 https://www.linkedin.com/in/ahmad-hasham-6a70a5104/
