### ISSUE TITLE
iOS build failed, cannot find IAPPromotionObserver.m

### ISSUE THREAD

**Issue by howg0924** [dooboolab/react-native-iap#1077]
### Version of react-native-iap

4.5.2, manual installation

### Version of react-native

0.59.9

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

build success

### Actual behavior

Build failed due to unable to find IAPPromotionObserver.m

This is because IAPPromotionObserver.m is removed in https://github.com/dooboolab/react-native-iap/pull/1039
but it is still referenced in ios/RNIap.xcodeproj/project.pbxproj

Remove that reference will fix the issue.

### Steps to reproduce the behavior

Manually install RNIap by adding RNIap.xcodeproj to xcode and build

**Comment by EgorKazachenko** [comment]
@howg0924 exactly so. no issue using pods

**Comment by hyochan** [comment]
`IAPPromotionObserver` is removed now in `iOS`. Feel free to reopen if you still find the issue with the recent version which is `4.6.3`.

**Comment by mkrn** [comment]
Believe there's still an issue with 4.6.3 while adding as a Library 

```
clang: error: no such file or directory: '/Users/mac/Sites/eventlivernnew/node_modules/react-native-iap/ios/IAPPromotionObserver.m'
clang: error: no input files
```

Adding as pod didn't work due to this error:
```
[!] Unable to find a specification for `React-Core` depended upon by `RNIap`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```

react-native is 0.59.9

**Comment by vish2595** [comment]
Believe there's still an issue with 4.6.3 while adding as a Library

clang: error: no such file or directory: '/Users/mac/Sites/eventlivernnew/node_modules/react-native-iap/ios/IAPPromotionObserver.m'
clang: error: no input files
Adding as pod didn't work due to this error:

[!] Unable to find a specification for `React-Core` depended upon by `RNIap`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

react-native is 0.59.9

**Comment by aidan2129** [comment]
Same issue here on react-native 0.59.10. Does it not support this version of react-native with pod install? working fine for andorid as i upgraded due to the new google billing library v3?

**Comment by LouisLeung** [comment]
Same issue.
clang: error: no such file or directory: '/Users/project-name/node_modules/react-native-iap/ios/IAPPromotionObserver.m'
clang: error: no input files

react-native is 0.59.9
react-native-iap:5.2.7
