### ISSUE TITLE
purchaseUpdatedListener() triggered on dev env with sandbox account but not working on TestFlight

### ISSUE THREAD

**Issue by bidetaggle** [dooboolab/react-native-iap#1078]
### Version of react-native-iap

^4.5.0

### Version of react-native

^0.62.2

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Trigger `purchaseUpdatedListener()` to request `https://mybackend.com/purchase-ios` and call `RNIap.finishTransaction()` when purchasing an item.

### Actual behavior

Works totally fine with a sandbox account on the dev environment (`npx react-native run-ios --device "bidetaggle's iPhone"`) but never finish the transaction from the app installed through TestFlight. Event listeners are not triggered and it never requests `https://mybackend.com/purchase-ios` as I can see from the server logs 

Here is `App.js`:

```
export default function App(props) {

...

useEffect(() => {
    // componentDidMount
    init();

    let purchaseUpdateSubscription = purchaseUpdatedListener((purchase: InAppPurchase | SubscriptionPurchase | ProductPurchase ) => {
      const receipt = purchase.transactionReceipt;
      if (receipt) {
        api(Platform.OS === "android" ? '/purchase' : '/purchase-ios', 'POST', { receipt: receipt })
        .then(async res => {
          await RNIap.finishTransaction(purchase, true);
        })
        .catch(async err => {
          await RNIap.finishTransaction(purchase, true);

          if(err.name == "Error 503") // Most likely a connection error
            this.props.navigation.navigate('Error');
          else if(err.name == "forbidden")
            this.props.navigation.navigate('Auth');

          Alert.alert(
            "Oops! Something wrong happened during the purchase :s",
            "Please send a screenshot to bidetaggle@pm.me along with your phone number to identify the problem.",
            [{ text: 'OK', onPress: async () => {
              console.log("pressed ok");
            } }],
            { cancelable: false }
          )
        })
      }
    })
    let purchaseErrorSubscription = purchaseErrorListener((error: PurchaseError) => {
      Alert.alert(
        "Oops! Come back later to chat with us :)",
        "This purchase couldn't be made :'(",
        [{ text: 'OK', onPress: async () => {
          console.log("pressed ok");
        } }],
        { cancelable: false }
      )
      console.log('purchaseErrorListener', error);
    });

    // componentWillUnmount
    return () => {
      if (this.purchaseUpdateSubscription) {
        purchaseUpdateSubscription.remove();
        purchaseUpdateSubscription = null;
      }
      if (this.purchaseErrorSubscription) {
        purchaseErrorSubscription.remove();
        purchaseErrorSubscription = null;
      }
    }
  }, []);

...

}
```

`purchaseErrorListener()` is never triggered neither

### Tested environment (Emulator? Real Device?)

Real device with sandbox account: Okay
TestFlight: doesn't work :(

**Comment by danleveille** [comment]
I believe the issue is that you need to call `await RNIap.initConnection()` in `componentDidMount`. Otherwise, the listener won't be called. This was missing from the readme.

Also could be the same issue as: #1005

**Comment by bidetaggle** [comment]
This is made in `init()` function, first instruction in `componentDidMount`

```
const init = async () => {
    try {
      // Keep on showing the SlashScreen
      await SplashScreen.preventAutoHideAsync();
      await loadResourcesAsync();
      if(Platform.OS === "ios"){
        let initConnectionResult = await RNIap.initConnection();
        console.log("initConnectionResult", initConnectionResult);
      }
    } catch (e) {
      console.warn(e);
    } finally {
      setLoadingComplete(true);
      // Hiding the SplashScreen
      await SplashScreen.hideAsync();
    }
}
```

On my dev environment (`npx react-native ios --device "Bide’s iPhone"`) I get `initConnectionResult true`

It perfectly works until I install it back from TestFlight, then it seems to never trigger the listeners.

**Comment by bidetaggle** [comment]
I moved `await RNIap.initConnection();` away from the `try {} catch {}` and it worked. There were a problem with SplashScreen (from expo) and it triggered the catch() before going to the RNiap initialization.
My bad.
