### ISSUE TITLE
Handling subscriptions without authentication.. 

### ISSUE THREAD

**Issue by Abdullah-Shamhan** [dooboolab/react-native-iap#1086]
So after purchasing a subscription it needs to be validated and stored in my db, but if the app dose not have authentication, how to  know which receipt belongs to which user? is it possible to get the user email after the purchasing process?

**Comment by EvgeniiKlepilin** [comment]
You could try generating a unique device ID to identify a user: https://aboutreact.com/react-native-get-unique-id-of-device/ or https://stackoverflow.com/questions/46452529/get-device-id-in-react-native . Ideally you should at least ask for an email. You would need to have a more robust system to keep subscriptions and user data safely.
