### ISSUE TITLE
getAvailablePurchases() is returning error 21105 on ios

### ISSUE THREAD

**Issue by genesy** [dooboolab/react-native-iap#1087]
### Version of react-native-iap
react-native-iap version 4.4.3,

### Version of react-native
react-native 0.63.2
### Platforms you faced the error (IOS or Android or both?)
ios
### Expected behavior
no error should show up

### Actual behavior
An alert appears saying "There is no information available for In-App Purchases. Try again later: 21105 [Environment: Sandbox]

### Tested environment (Emulator? Real Device?)
Real device ios 13.6.1
### Steps to reproduce the behavior
call getAvailablePurchases() method

**Comment by genesy** [comment]
Related to this thread. https://developer.apple.com/forums/thread/125164

**Comment by flexbox** [comment]
@genesy I got exactly the same error, did you found a solution?

**Comment by genesy** [comment]
no it's apple's internal server's issue. so this is safe to close
