### ISSUE TITLE
Example app getProducts() throws "UNKNOWN_ERROR" on IOS 14

### ISSUE THREAD

**Issue by vm02** [dooboolab/react-native-iap#1091]
### Version of react-native-iap
4.5.3

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Get a list of products

### Actual behavior
Getting "UNKNOWN_ERROR" (and no list of products)

### Tested environment (Emulator? Real Device?)
Emulator: Xcode 12 Beta 6 IPhone 11 IOS 14.0
(Emulator: Xcode 11.6 IPhone 11 IOS 13.6 works like expected)

### Steps to reproduce the behavior
Clone example app, upgrade react-native-iap to version 4.5.3 and run.

**Comment by edwardchen** [comment]
This might be it. Seems like bug in Apple's IAP sandbox where it doesn't return any products/subs.
https://developer.apple.com/forums/thread/125164

**Comment by 0hio-creator** [comment]
Seeing exact same behaviour 

xcode 12.0 Iphone 11 Pro IOS 14 (always returning UNKNOWN_ERROR)
xcode 12.0 Iphone 11 Pro IOS 13.2.2 works fine 

@vm02 were you able to resolve it?

**Comment by vm02** [comment]
@0hio-creator unfortunately i couldn't resolve the error yet. But my production app with react native version 0.62.2 and the latest react-native-iap version doesn't throw this error on a real IOS 14 device.

**Comment by sedoyjan** [comment]
I have the same problem in simulator iPhone 8 iOS 14 (

**Comment by ayberkanilatsiz** [comment]
same issue

**Comment by hyochan** [comment]
Looks like an issue on the Apple side. We should be waiting for the next updates.

**Comment by hyochan** [comment]
Looks related https://stackoverflow.com/questions/58020258/requesting-an-in-app-purchase-in-ios-13-fails/58065711#58065711
