### ISSUE TITLE
RNIap.requestSubscription never return promisse RN 63.2

### ISSUE THREAD

**Issue by dmorsoleto** [dooboolab/react-native-iap#1093]
### Version of react-native-iap
4.5.3 (tested on 4.5.2 also)

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Request subscription and return a promisse

### Actual behavior
When I call RNIap.requestSubscription nothing is returned and never ends the call, a promisse never return, nethern an error return. (Today I have an app in production mode with RN 0.61.5 and react-native-iap@4.4.4  thats using the same coding and all is working perfectly)

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by hyochan** [comment]
I recommend you to receive the purchase result via `purchaseUpdatedListener`. However, we might have to look into the regression issue you've provided.

**Comment by frknnay** [comment]
I have the same issue, and I think it generally happens calling getAvailablePurchases first then requestSubscription.
