### ISSUE TITLE
Promoted products. delegate does not respond to method paymentQueue:shouldAddStorePayment

### ISSUE THREAD

**Issue by EgorKazachenko** [dooboolab/react-native-iap#1094]
### Version of react-native-iap

4.5.0

### Version of react-native

0.61.5

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

`iap-promoted-product` event received inside the application

### Actual behavior

`[Daemon] [SKPaymentQueue]: Tried to send purchase intent: <PRODUCT_ID> to delegate, delegate does not respond to method paymentQueue:shouldAddStorePayment:forProduct` inside XCode logs when trying to test via `itms-services://?action=purchaseIntent&bundleId=<BUNDLE_ID>&productIdentifier=<PRODUCT_ID>`

callback for `iap-promoted-product` event isn't called

### Tested environment (Emulator? Real Device?)

Real device, IPhone XR 13.6.1

### Steps to reproduce the behavior

1. Set up an event-listener for promoted products (as in example inside this repo)
2. Open app
3. Change app's status from active to background
4. Open safari and past `itms-services://?action=purchaseIntent&bundleId=<ID>&productIdentifier=<ID>`
5. Open this link
6. Read the message (as in Actual behavior section) inside XCode logs

Thanks

**Comment by EgorKazachenko** [comment]
:D epic, can be closed i think. will be nice to add this hint into docs, i know that there is such hint for normal payment-flow, on my opinion it is a good idea add it to promoted-flow also 

<img width="521" alt="Screen Shot 2020-08-29 at 20 33 34" src="https://user-images.githubusercontent.com/23015635/91642810-0c60e900-ea37-11ea-8785-2d77e126fd9e.png">

**Comment by ngocdaothanh** [comment]
Apple's instruction about `itms-services://...` link:
https://developer.apple.com/documentation/storekit/in-app_purchase/testing_promoted_in-app_purchases

I write a link to Notes app.
When I tap on it, my app opens.

But in Xcode I see the error message as reported:
```
delegate does not respond to method paymentQueue:shouldAddStorePayment:forProduct
```

How to fix it please?

CC @EgorKazachenko

**Comment by ngocdaothanh** [comment]
Related issue:
TypeScript signature (or implementation) of getPromotedProductIOS is wrong
https://github.com/dooboolab/react-native-iap/issues/1287

**Comment by ngocdaothanh** [comment]
So iOS promo requires calling `initConnection` first.
I've created a PR to improve the README:
https://github.com/dooboolab/react-native-iap/pull/1288/files
