### ISSUE TITLE
Android Product Purchase Refunded but receiving error "you already own this item"

### ISSUE THREAD

**Issue by 0hio-creator** [dooboolab/react-native-iap#1096]
### Version of react-native-iap
4.5.3
### Version of react-native
0.61.5
Android
### Expected behavior
1. User has attempted to purchase a product.
2. Some issue has prevented the acknowledge
3. They are refunded
4. They attempt to repurchase

Expected to be able to repurchase. Or to receive a refunded status

Particularly looking at the case where the user purchases and there is an issue with acknowledge.

### Actual behavior
1. User has attempted to purchase a product.
2. Some issue has prevented the acknowledge
3. They are refunded
4. They are unable to purchase and Receiving the below error message after calling

```
RNIap.requestPurchase(sku, false);
```

```
purchaseErrorListener {"code": "E_ALREADY_OWNED", "debugMessage": "Item is already owned.", "message": "You already own this item.", "responseCode": 7}
 WARN  E_ALREADY_OWNED You already own this item.
```
### Tested environment (Emulator? Real Device?)
Tested on a device with an android billing test account

Does this just go away with some cool off period or there something else going on?

**Comment by hyochan** [comment]
Looks like we need minimal reproduction or additional information to handle this problem.

**Comment by leotm** [comment]
I've just got this in our sandbox env

<img width="234" alt="Screenshot 2020-12-11 at 15 02 28" src="https://user-images.githubusercontent.com/1881059/101918956-ed3f2f00-3bc1-11eb-891a-dbbe7f375ebd.png">

This is without a refund.

You can ignore the blank text there (data issue).

I think the message is probably right, I did buy this earlier today while doing some QA, but how do we remove the msg and allow purchase?

**Comment by leotm** [comment]
I'll try https://github.com/dooboolab/react-native-iap/issues/380#issuecomment-457221431

**Comment by felipecespedes** [comment]
I was experiencing the same issue and solved it by consuming the Android item
```js
RNIap.finishTransaction(purchase, true);
```

In order to avoid this issue make sure that when refunding non-consumable items you check the `Remove entitlement` checkbox as in the following image:

![screenshot_162](https://user-images.githubusercontent.com/11846311/106501906-b1259d80-6491-11eb-92de-16f1c4ed4309.png)

**Comment by andresesfm** [comment]
Closing as solved
