### ISSUE TITLE
Validating subscription receipt on Android..

### ISSUE THREAD

**Issue by Abdullah-Shamhan** [dooboolab/react-native-iap#1097]
So i manged to validate the receipt on ios for auto renewal subscription, and when i want to check if the subscription is still active i can send the receipt again to my server to get the new expiration date.. 
but what about android? is it the same process? I just send the receipt to my server and send it again whenever i need the updated expiration date?  and how the validation response will look like?

**Comment by hyochan** [comment]
@iaphub Can you handle this question? I use to handle `receipt` with other modules in my other app. You may find something like [node-iap](https://github.com/Wizcorp/node-iap).

**Comment by andresesfm** [comment]
If you call `getSubscriptions()` and your subscription is returned, it means that your subscription is active
