### ISSUE TITLE
Question: How to request upgrade and downgrade of subscription in ios and android?

### ISSUE THREAD

**Issue by rizshivalli** [dooboolab/react-native-iap#1099]
### Version of react-native-iap
^4.5.0
### Version of react-native
0.63.0
### Platforms you faced the error (IOS or Android or both?)
Both iOS and Android
### Expected behavior
Not applicable
### Actual behavior
not applicable
### Tested environment (Emulator? Real Device?)
Rel Device
### Steps to reproduce the behavior

I have gone through the documentation and could not find any references to upgrade and downgrade of subscription on both Android and iOS.

if you have any references please share.

regards

**Comment by andresesfm** [comment]
Look in here: https://github.com/dooboolab/react-native-iap/blob/master/README.md search for `requestSubscription` the key is to pass the new `sku` and the `oldSkuAndroid` in the same call. Please reopen if needed
