### ISSUE TITLE
iOS - Subscription offer codes

### ISSUE THREAD

**Issue by belal-mazlom** [dooboolab/react-native-iap#1103]
[Question]

Any plan to support new feature coming to iOS devices "Subscription offer codes"?
https://developer.apple.com/app-store/subscriptions/#offer-codes
https://developer.apple.com/documentation/storekit/skpaymentqueue/3566726-presentcoderedemptionsheet

**Comment by hyochan** [comment]
Releated #1102

**Comment by karltaylor** [comment]
How easy or difficult would it to be to add a RN.IAP method to call `presentCodeRedemptionSheet()`? I'd be out of my depth if I took a stab at it but would that be enough to use the Offer Codes functionality?
