### ISSUE TITLE
`This In-App Purchase has already been bought` message for consumable product

### ISSUE THREAD

**Issue by indapublic** [dooboolab/react-native-iap#1105]
### Version of react-native-iap
4.5.2

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Product is consumable, multiple purchases are allowed

### Actual behavior
Received "This In-App Purchase has already been bought" message for consumable product

### Tested environment (Emulator? Real Device?)
Real device and sandbox mode

### Steps to reproduce the behavior

```
await initConnection()
clearProductsIOS()
const products = await getProducts([productId])
...
purchaseUpdatedListener(async (purchase) => {	
})
purchaseErrorListener(error => {	
})
await requestPurchase(productId, false)
```

**Comment by indapublic** [comment]
![image](https://user-images.githubusercontent.com/856260/92717432-e7139980-f3ab-11ea-840e-75dae4eeb4ee.png)

**Comment by tolgaberk** [comment]
Hi, have you found any solution? i am facing the same issue.

**Comment by indapublic** [comment]
Hi @tolgaberk be honest I don't remember ) Seems it was related to my wrong code or meta in App Store.
