### ISSUE TITLE
support promo codes android

### ISSUE THREAD

**Issue by Robert-van-Barlingen** [dooboolab/react-native-iap#1107]
Why is there no support for redeeming promo codes in app on android yet? Is there a technical reason why this is especially difficult or something?

**Comment by hyochan** [comment]
I just am so busy today. Forgive me.

**Comment by jkz27** [comment]
Custom code redemption works on android I can confirm

**Comment by StefanoCremona** [comment]
@jkz27 is there any documentation we can follow? Once I redeem a code in the Google store, I call getAvailablePurchases() and I get an empty array. 😭

**Comment by jkz27** [comment]
@StefanoCremona the custom code redemption process is the same as initiating a regular purchase, except you apply the custom code at the android purchase pop-up (there is a redemption code option), and once you apply the code, the purchase goes just like a regular transaction.... 

PS: Custom Code you only need to handle in-app redemption

**Comment by andresesfm** [comment]
Closing resolved

**Comment by khan8901** [comment]
can some give me  some code sample of its  working , I have been trying for days for it to work , I want to redeem the codes that  are generated via google play store console . @jkz27

**Comment by khan8901** [comment]
I am generating code  which enables  user subscription but I am having difficulty in redeeming it ? How should   do it through IAP
