### ISSUE TITLE
Recurring Payment using react-native-iap

### ISSUE THREAD

**Issue by vnitMendapara** [dooboolab/react-native-iap#1108]
react-native-iap version = 4.5.3
react-native = 0.61.4

how to implement Recurring Payment or update user recurring subscription on database in detached  react native ios app?

Tested environment = real device with xcode

**Comment by hyochan** [comment]
You may look into `receipt`. Here is a great article https://savvyapps.com/blog/how-setup-test-auto-renewable-subscription-ios-app.
