### ISSUE TITLE
How to test/debug the code on Android?

### ISSUE THREAD

**Issue by mag1cDev** [dooboolab/react-native-iap#1109]
I know the code has to be tested on an actual device and I know it needs to be uploaded to the play store.

But does it have to be reuploaded every time there is a change to the code or just the first one?

That would make it extremely tiresome.

**Comment by southerneer** [comment]
> I know the code has to be tested on an actual device

I'm testing it on an emulator (iOS + Android) with no issues.

> does it have to be reuploaded every time there is a change to the code

No

**Comment by hyochan** [comment]
Thanks for the question and the answer!
