### ISSUE TITLE
Error (SKErrorDomain error 0.) when fetching subscriptions with .getSubscriptions()

### ISSUE THREAD

**Issue by KristineTrona** [dooboolab/react-native-iap#1111]
### Version of react-native-iap

v.4.5.3

### Version of react-native

v.0.62.2

### Platforms you faced the error (IOS or Android or both?)

iOS (currently not developing for Android)

### Expected behavior

Retrieve a list of subscriptions from Apple with each subscription productId, price, etc.

### Actual behavior

I get the following error:

<img width="506" alt="Screenshot 2020-09-14 at 12 06 03" src="https://user-images.githubusercontent.com/39855778/93073091-aacd8b00-f682-11ea-9ee0-0ae7befb2d0b.png">

### Tested environment (Emulator? Real Device?)

Emulator

### Steps to reproduce the behavior

In `App.js`

```

const iapSkus = [ 'ProductId1', 'ProductId2', 'ProductId3' ] // These match the product ids defined in Appstore

  useEffect(() => {
    fetchSubscriptions();
  }, []);

  const fetchSubscriptions = async () => {
    try {
      const subscriptions = await inAppPurchase.getSubscriptions(iapSkus);
    } catch (e) {
      console.log('Error fetching subscriptions', e);
    }
  };
```

When I first created this part of the app, everything was working as expected. Both on device and emulator. Now for some reason I am getting this error. Any ideas on what could be missing/what could be causing this?

I've also checked and made sure the bundle Identifier in Appstore and in Xcode matches. 
I've also checked and made sure that the 'In-App Purchase' capability in xcode is enabled.

**Comment by hyochan** [comment]
What is your `ios` emulator version? The iap is having a problem in ios 14 especially in the emulator followed by the issues.
