### ISSUE TITLE
IAP Promoted Subscription Flow? 

### ISSUE THREAD

**Issue by BStenfors9119** [dooboolab/react-native-iap#1113]
### Version of react-native-iap
4.5.4

### Version of react-native: 
0.62.0

### Platforms you faced the error (IOS or Android or both?): 
iOS

### Expected behavior
Not sure

### Actual behavior
Invalid product id

### Tested environment (Emulator? Real Device?)
Real Device iPhone 6s iOS 13.6.1

This is not an issue but rather a request for help on understanding how the IAP promoted product/subscription flow works.

I am able to test successfully IAP auto-renewing subscription on a real device via a sandbox user.
I was hoping after a successful purchase I could allow users to enter a promo code that unlocks the app for a period of time.

I keep getting confused between a "promoted product" and a "promotional code". 

I am currently trying to allow the user to "buy" the promoted product via the following code.
My response is always "Invalid product id".  I have created the product promo in app store connect, waited 48 hours, it is in "Ready for Submit" mode and I am using the correct product id but no luck.
`
       if(Platform.OS === "ios") {
            let signingKey = await getSigningKey(promoCode);

            console.log('signing key');
            console.log(signingKey);

            const offer = {
                identifier: promoCode.toString().toUpperCase(),
                keyIdentifier: signingKey.keyID,
                nonce: signingKey.nonce,
                signature: signingKey.signature,
                timestamp: signingKey.timestamp
            };

            const sku = 'tsr-social';
            const uid = '';

            try {
                const resp = await RNIap.buyPromotedProductIOS(sku, uid, offer);

                console.log('buy offer resp');
                console.log(resp);
            }
            catch(err) {
                console.log('buying promo offer err');
                console.log(err);
            }

        }
`
Thanks!

**Comment by EightPool** [comment]
I think you are looking for `requestPurchaseWithOfferIOS`

The method `buyPromotedProductIOS` should be used for promoted products. These are the in-app products that are displayed directly in the App Store. You need to use a [listener](https://github.com/dooboolab/react-native-iap#how-do-i-handle-promoted-products-in-ios) for that.

**Comment by BStenfors9119** [comment]
@EightPool you're a genius!!  I was using "." intellisense and that method wasn't appearing.

Then with your suggestion I put on my helmet and noticed I was able use it via "Import {}".

It's all working!! 

Been struggling on this for a month or more!

Cheers!!
