### ISSUE TITLE
README question

### ISSUE THREAD

**Issue by SrBrahma** [dooboolab/react-native-iap#1121]
### Version of react-native-iap
4.5.3

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
Only tested on Android

### Tested environment (Emulator? Real Device?)
Real, Xiaomi Redmi Note 8

### Steps to reproduce the behavior
I am using https://github.com/iaphub/react-native-iaphub. When running its init() function, I get a `[TypeError: null is not an object (evaluating 'RNIapModule.startListening')]`. Looks like I haven't installed this lib properly.

Me question is:
There is a Mostly auto installation and a Manual installation. I am really not sure, as my problem persists after trying both "with Android Support" and "with AndroidX", if I have to also do the Manual installation.

**Comment by SrBrahma** [comment]
Managed to get the error go away with the Manual Installation.



In`buildscript {
  ext { ... } }
`, do I have to overwrite my current version values (
```
buildToolsVersion = "29.0.2"
minSdkVersion = 16
compileSdkVersion = 29
targetSdkVersion = 29
```
) or just add the additional lines? Also, it uses twice '#' as commentary, which probably should be "//" (or it was meant to be removed).

Also, the Mostly auto installation could have something like this "If you have android.useAndroidX=true in your android/gradle.properties"... as like me, I didn't know if I was using AndroidX or not.

Anyway, thanks for the lib!

**Comment by hyochan** [comment]
@iaphub Can you help this question?

**Comment by iaphub** [comment]
@SrBrahma , correct the library was definitely not installed correctly for some reason.
The sdk version you're using to compile your project is up to you, I recommend using the latest version available.
Using AndroidX also depends on your project, if you don't have any third party library using the old compat library you shouldn't have any issue using AndroidX so I would recommend using it.

**Comment by SrBrahma** [comment]
I have already managed to make it work, but this README and the https://github.com/iaphub/react-native-iaphub README still confuses me:

Does the Manual Installation steps must always be executed, or just the Automatic steps?
