### ISSUE TITLE
Has developerId and accoundId when requesting purchase or subscription been removed?

### ISSUE THREAD

**Issue by ammarahm-ed** [dooboolab/react-native-iap#1125]
### Platforms you faced the error (IOS or Android or both?) Android

From the [release notes of Google Billing Library v3.0](https://developer.android.com/google/play/billing/release-notes):

> In BillingFlowParams, renamed setAccountId() to setObfuscatedAccountId(), and documented length restriction of 64 characters and restriction disallowing Personally Identifiable Information (PII) in this field. setAccountId() has been marked as deprecated and will be removed in a future library version.

Any reason why has this been removed instead of updating it to the new changes?

**Comment by hyochan** [comment]
Resolved #1141
