### ISSUE TITLE
Resubscribe feature. Billing 3.0.0 Android

### ISSUE THREAD

**Issue by Akeuuh** [dooboolab/react-native-iap#1126]
### Version of react-native-iap
4.6.1

### Version of react-native
0.63.2
### Platforms you faced the error (IOS or Android or both?)
Android

I have to implement the new feature of play billing 3.0.0 on my project: Resubscribe
You can find the documentation on this [link](https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html)

My question is:
Does this lib (RNiap) take care of the feature or do I have to create some more code to achieve it?

Thanks

**Comment by hyochan** [comment]
Thank you for sharing the new feature. You can make a `PR` and help others and maintain this library!

**Comment by ramazanarslan** [comment]
it will be good to add this feature.

**Comment by tatsianaBukzheleva** [comment]
Good question!
What about implementing the new feature of play billing - account hold?
It's very actual for now!
Restore and account hold will be mandatory.

**Comment by roots-ai** [comment]
Playstore has put the deadline of November to implement this feature.

**Comment by ramazanarslan** [comment]
I am new for react native, i integrated iap, but i am afraid if google payment crash because of this changes. Do you have idea? Android users can freeze and resubscribe after cancel iap. Do you concerned? Will google change iap api response? 🙏

**Comment by hyochan** [comment]
Nov 1 is coming soon so let me look into this. Can someone clarify that what we need is [account-hold](https://developer.android.com/google/play/billing/subs#account-hold) feature?

![image](https://user-images.githubusercontent.com/27461460/96543998-9d8a6880-12e0-11eb-9319-ca345aa4d4c9.png)

We already have a restore feature so we need another account-hold which is mandatory from Nov 1. Is this all we need?

Also, please provide a doc on implementing this feature that can be helpful.

**Comment by hyochan** [comment]
Looks like this should be handled on the server-side. Feel free to ask to reopen if it should.
