### ISSUE TITLE
Apple verify receipt still returns 21002

### ISSUE THREAD

**Issue by boreales** [dooboolab/react-native-iap#1127]
### Version of react-native-iap
4.6.1
### Version of react-native
0.63.2
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Getting the JSON response from Apple VerifyReceipt service
### Actual behavior
Getting a status 21002 error
### Tested environment (Emulator? Real Device?)
Both
### Steps to reproduce the behavior

Here's my React Native code : 

```
if (Platform.OS === 'ios') {
  console.log('PURCHASE IOS IS DONE');
  console.log('Transaction Receipt', JSON.stringify({ transaction: purchase }));
  RNIap.getReceiptIOS().then(async result => {
    console.log('Purchase Receipt', result);
  });
}
```

It returns me this purchaseReceipt : 

`MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwGggCSABIIBbTGCAWkwDwIBAAIBAQQHDAVYY29kZTALAgEBAgEBBAMCAQAwFQIBAgIBAQQNDAtuZWFydHJpcC5pbzAPAgEDAgEBBAcMBTIuMS4yMBACAQQCAQEECOG5uScNAAAAMBwCAQUCAQEEFELyZOL0JTlhofkxQmPT76dFJFO6MAoCAQgCAQEEAhYAMCICAQwCAQEEGhYYMjAyMC0wOS0yM1QxNjowNzozOCswMjAwMIGcAgERAgEBBIGTMYGQMAwCAgalAgEBBAMCAQEwGgICBqYCAQEEEQwPcHJlbWl1bV9tZW5zdWVsMAwCAganAgEBBAMMATAwIwICBqgCAQEEGhYYMjAyMC0wOS0yMlQxMTo0NTo0OSswMjAwMCMCAgasAgEBBBoWGDIwMjAtMTAtMjJUMTE6NDU6NDkrMDIwMDAMAgIGtwIBAQQDAgEAMCICARUCAQEEGhYYNDAwMS0wMS0wMVQwMTowMDowMCswMTAwAAAAAAAAoIIDeDCCA3QwggJcoAMCAQICAQEwDQYJKoZIhvcNAQELBQAwXzERMA8GA1UEAwwIU3RvcmVLaXQxETAPBgNVBAoMCFN0b3JlS2l0MREwDwYDVQQLDAhTdG9yZUtpdDELMAkGA1UEBhMCVVMxFzAVBgkqhkiG9w0BCQEWCFN0b3JlS2l0MB4XDTIwMDQwMTE3NTIzNVoXDTQwMDMyNzE3NTIzNVowXzERMA8GA1UEAwwIU3RvcmVLaXQxETAPBgNVBAoMCFN0b3JlS2l0MREwDwYDVQQLDAhTdG9yZUtpdDELMAkGA1UEBhMCVVMxFzAVBgkqhkiG9w0BCQEWCFN0b3JlS2l0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA23+QPCxzD9uXJkuTuwr4oSE+yGHZJMheH3U+2pPbMRqRgLm/5QzLPLsORGIm+gQptknnb+Ab5g1ozSVuw3YI9UoLrnp0PMSpC7PPYg/7tLz324ReKOtHDfHti6z1n7AJOKNue8smUAoa4YnRcnYLOUzLT27As1+3lbq5qF1KdKvvb0GlfgmNuj09zXBX2O3v1dp3yJMEHO8JiHhlzoHyjXLnBxpuJhL3MrENuziQawbE/A3llVDNkci6JfRYyYzhcdtKRfMtGZYDVoGmRO51d1tTz3isXbo+X1ArXCmM3cLXKhffIrTX5Hior6htp8HaaC1mzM8pC1As48L75l8SwQIDAQABozswOTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIChDAWBgNVHSUBAf8EDDAKBggrBgEFBQcDAzANBgkqhkiG9w0BAQsFAAOCAQEAsgDgPPHo6WK9wNYdQJ5XuTiQd3ZS0qhLcG64Z5n7s4pVn+8dKLhfKtFznzVHN7tG03YQ8vBp7M1imXH5YIqESDjEvYtnJbmrbDNlrdjCmnhID+nMwScNxs9kPG2AWTOMyjYGKhEbjUnOCP9mwEcoS+tawSsJViylqgkDezIx3OiFeEjOwMUSEWoPDK4vBcpvemR/ICx15kyxEtP94x9eDX24WNegfOR/Y6uXmivDKtjQsuHVWg05G29nKKkSg9aHeG2ZvV6zCuCYzvbqw45taeu3QIE9hz1wUdHEXY2l3H9qWBreYHY3Uuz/rBldDBUvig/1icjXKx0e7CuRBac9TzGCAY8wggGLAgEBMGQwXzERMA8GA1UEAwwIU3RvcmVLaXQxETAPBgNVBAoMCFN0b3JlS2l0MREwDwYDVQQLDAhTdG9yZUtpdDELMAkGA1UEBhMCVVMxFzAVBgkqhkiG9w0BCQEWCFN0b3JlS2l0AgEBMA0GCWCGSAFlAwQCAQUAMA0GCSqGSIb3DQEBCwUABIIBAGWKp8uaHfNBrVrXEqxS3fjsskoTHPKdTi3bXsGg1X4xEeSh5HWuYTeQ9wZMjq/qJwVz4rtJUGP6Cmk7wvPwNWAM772O+D8PeRjVGAwmzRyllslzDh/m05eTNSKBRLT/cKLs+ygU441L12Nh8JG19YB4HCoE6ccrqh+TBKIcu+StapzqUy/RRpTTcLIQjtAzm90Fr7/Ku1ZSqbkHSMNG5UoqTSOgx8YGYWOObM+BDWY55xcLUKYY7IuhUyu5LzjL6zcPjrTulIWPWtU14Id8aDx91dqriT1bQycqKJ1YlcpIjF7JdtQul35IWBErzQ1Hp01rWkvDKNOTWqIo60SVUysAAAAAAAA=`

When I'm trying to send it through postman or any other way, the Apple response is forever :

`{
"status": 21002
}`

And yes I add the password field with my shared secret key to the request.

I know it means that the current receipt is mal-formatted or something but I don't know what do to with it as it seems already to be base64 encoded.

Any idea ?

**Comment by f-ricci** [comment]
I ran into the same issue and for now my only guess is that I setup the [new StoreKit local testing](https://developer.apple.com/videos/play/wwdc2020/10659/) that uses other validations methods. I won't be able to confirm if this is the cause until I get to submit my app to the app store and test the IAP there.

**Comment by hyochan** [comment]
@iaphub How do you think of integrating the feature @f-ricci has provided in `react-native-iap`? Since this seems to have the same role that you are responsible for, I might have to ask you beforehand.

Also, have you tried `validateReceiptIos` @boreales @f-ricci? I am not sure if this is still working today which by the way isn't recommended in production.

**Comment by EndLess728** [comment]
Me too was facing the issue but I got it working in Postman. I Passed the Body in Raw format in Postman and I got the Response. Don't know how can I do this in react-native-iap with  ```validateReceiptIos``` method

**Comment by Kladislav** [comment]
any update?

**Comment by Kladislav** [comment]
i have same problem

**Comment by Kladislav** [comment]
fixed by replace axios to native fetch

**Comment by gurol** [comment]
All of a sudden I have started to receive 21002 status -always. I appreciate any solution

**Comment by boreales** [comment]
The validation of receipt doesn't work on Simulator and EITHER on real device. You must test it with a download from Testflight.
This is how I finally achieved this.

**Comment by kalmahik** [comment]
@boreales Are you sure about that? but how to debug in this case? Use Alert?😬

**Comment by benjaminfiliatrault** [comment]
If you are using the StoreKit it's normal that the receipt is not valid because the certificate is created on your computer so the both sandbox and prod doesn't accept the receipt

https://developer.apple.com/forums/thread/650879

**Comment by Shiviagg** [comment]
HIi, I am facing the same issue? can someone help it

**Comment by Shiviagg** [comment]
For Discussion

**Comment by roots-ai** [comment]
Any updates here?

**Comment by andresesfm** [comment]
`12.0.3`

**Comment by roots-ai** [comment]
> 12.0.3

Do you mean we need to upgrade to `12.0.3` to make this work?

**Comment by matej-podzemny** [comment]
any updates on this one?

**Comment by bmitioglov** [comment]
same issue

**Comment by bhavesh-kreeti** [comment]
any update on this?

**Comment by oloyedewaris** [comment]
Please help us with this error, it's frustrating not being able to complete this

**Comment by lossen** [comment]
Any updates? Same error

**Comment by MohamedAhmed122** [comment]
why this issue has been close? 
I still have the same issue

**Comment by Mourad-Tlili** [comment]
Still facing the same issue on real device

**Comment by algotechnologies** [comment]
Still facing this issue!!!
