### ISSUE TITLE
RNIapModule.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by stam-ops** [dooboolab/react-native-iap#1135]
### Version of react-native-iap
4.6.3
### Version of react-native
0.63.2
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
compile ok
### Actual behavior
compile ko

node_modules\react-native-iap\android\src\main\java\com\dooboolab\RNIap\RNIapModule.java uses or overrides a deprecated API.

### Tested environment (Emulator? Real Device?)
real device
sdk 29

### Steps to reproduce the behavior
react-native run-android on the new project with react native iap installed.

**Comment by hyochan** [comment]
@stam-ops Could you kindly confirm that this warning message still appears in `react-native-iap@5.0.+`?

**Comment by andresesfm** [comment]
This is addressed here: https://github.com/dooboolab/react-native-iap/pull/1333/files

**Comment by andresesfm** [comment]
Merged
