### ISSUE TITLE
Not getting callback after successfully subscribed to any plan in ios

### ISSUE THREAD

**Issue by leelaprasadsahu22** [dooboolab/react-native-iap#1137]

**Comment by jordangrant** [comment]
Might take a while

**Comment by cwmilazzo** [comment]
I have the same issue.  I've done both subscriptions and purchases of consumable products, and never get any callbacks.  I'm on react-native-iap 5.0.0  (tried with 4.6.1 and same issue)

**Comment by lordkiz** [comment]
+1

**Comment by Tayyab304** [comment]
Update listener is called on first time when call this method if you don't clear Transaction then 2nd time it's not being called. Clear Transaction in iOS case when first time update listener is called in purchaseUpdatedListener() like below

purchaseUpdateSubscription = purchaseUpdatedListener(
        async (purchase: InAppPurchase | SubscriptionPurchase) => {
          
          const receipt = purchase.transactionReceipt;
        
          if (receipt) {

            try {
              if (Platform.OS === 'ios') {
                finishTransactionIOS(purchase.transactionId ?? "");
              } else if (Platform.OS === 'android') {
               If consumable (can be purchased again)
              //   consumePurchaseAndroid(purchase.purchaseToken);
              //   // If not consumable
              //   acknowledgePurchaseAndroid(purchase.purchaseToken);
              }
              const ackResult = await finishTransaction(purchase);
            } catch (ackErr) {
              console.warn('ackErr', ackErr);
            }
          
          }
          
        },
      );
