### ISSUE TITLE
getProducts is empty in android. iOS working fine.

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [dooboolab/react-native-iap#1143]
hi friends,

i had integrate react-native-iap for in-app purchase for ios and android. i had added the product ids on both store iTunes and play console. i also follow the code as example. the product list gets successfully in ios. but in android there will be blank.

Code : 

    const itemSkus = Platform.select({
        ios: [
            'com.mapta.mepta.coin10',
        ],
        android: [
            'com.mapta.mepta.coin10',
        ]
    });

    const products = await RNIap.getProducts(itemSkus);
    setProducts(products)
    console.log("=== products ===", products)

iOS Will get the products, But in android it's blank. please help me.

Thanks.

**Comment by odanicola** [comment]
@kiritm-nimblechapps you must upload the apk to Close / Open tracking just once then wait sometimes like a half day to get the product list, or you can try the one of test IDs: **android.test.purchased**, this is not required to upload the signed APK. 
Hope this help you.

**Comment by kiritm-nimblechapps** [comment]
@odanicola But I had create product ids before upload the apk, then it's okay or not?

**Comment by odanicola** [comment]
@kiritm-nimblechapps that's okay you can get the created products after you submit the signed APK to Alpha or Beta release. Just make sure you open the url of the testing apk from the opt-in url.

**Comment by kiritm-nimblechapps** [comment]
@odanicola thanks, I will wait for build upload on store, once approve i get also product list in debug mode. right ?

**Comment by odanicola** [comment]
@kiritm-nimblechapps oh yeah, i was getting the product by this morning (yesterday was publishing the apk). 
Good luck!

**Comment by kiritm-nimblechapps** [comment]
@odanicola thanks

**Comment by iaphub** [comment]
@odanicola is correct, you can find more details about configuring your android sandbox environement [here](https://www.iaphub.com/docs/set-up-android/configure-sandbox-testing).

**Comment by odanicola** [comment]
@kiritm-nimblechapps did you get success on IOS? did you use real device or simulator?

**Comment by hyochan** [comment]
Looks like this issue can be resolved with configuration

**Comment by baronha** [comment]
I have the same problem with android. I try to publish my aab in open testing / close testing  and I am waiting for 2 days. but it not solve
But I download my app in CHPlay ver. Close Testing. It worked. But it not worked on debugging (I use a real device).
Help me, please!
