### ISSUE TITLE
Billing unavailable for this package and user

### ISSUE THREAD

**Issue by K12AZ** [dooboolab/react-native-iap#1144]
Hello world,

Good day, Did anyone know the reason for getting "Billing unavailable for this package and user". 

Normal android test IN-App purchases work fine. 

This is the first time, I am trying to implement the in-App purchase to Android app. 

Looking forward to hearing from you,

**Comment by pxmage** [comment]
I got this error as well, and I have no idea why, I download other apps from Google Play and their IAB works fine, which means my account is properly set and logined.

**Comment by andresesfm** [comment]
https://stackoverflow.com/questions/64812448/android-billing-3-0-issues-billing-unavailable-for-this-package-and-user

Closing stale
