### ISSUE TITLE
subscription renew issue 

### ISSUE THREAD

**Issue by abdulahad96** [dooboolab/react-native-iap#1145]
### Version of react-native-iap 
^4.4.0

### Version of react-native 
0.61.3

### Platforms you faced the error (IOS or Android or both?) 
Android

### Expected behavior 
when subscription renew listener occurr 

### Actual behavior 
no updatepurchase listener occur

### Tested environment (Emulator? Real Device?) 
real device

### Steps to reproduce the behavior   
await RNIap.requestSubscription(productID)
  this.purchaseUpdateSubscription = purchaseUpdatedListener(purchase => {
 const res = await api.IAPTransactionvalidate(Purchase);
       await RNIap.finishTransaction(purchase);
    });
please help me about this concern

**Comment by floelm** [comment]
Hey,

for recurring subscriptions it is recommended to use the real time developer notifications for android. Here are the docs:

https://developer.android.com/google/play/billing/rtdn-reference

I am not sure if this packages listener is supposed to be triggered with recurring purchases too.

**Comment by abdulahad96** [comment]
I need a functionality that realize my app that subscription renewed and i can reward user after hit an api.
your solution can create problem when i neglected push notification.
please help me

**Comment by floelm** [comment]
With the Real Time Developer Notifications you can directly hit your API (Google Pub/Sub) and give or extend the users reward based on the notification you receive. It should help you to keep track or a users subscription (cancelled, renewed, ...).  

I am not sure what you mean by that: "your solution can create problem when i neglected push notification"

**Comment by andresesfm** [comment]
Looks like it's been answered, if more info please reopen
