### ISSUE TITLE
PurchaseUpdateListners not being called on production iOS build

### ISSUE THREAD

**Issue by ashish3303** [dooboolab/react-native-iap#1146]
Hello everyone,

I am not sure what actually happen with my code. I integrated the react-native-iap plugin into my iOS application. And it was working fine on local build or testflight build but when i release the mobile version of application and i made the subscription but nothing happened next. I assumed that purchaseUpdateListeners are not working on production build then i removed the listeners and write the code just after the requestSubscription send the response. And released the next version of application but still the same issue even getReceiptIOS not called. I am stuck into this. Help me to find out from this. 

Here is my code : - 

const purchases = await RNIap.requestSubscription(productId);
console.log(purchases, "purchase...")
this.validateTransactionReceipt(purchases);

validateTransactionReceipt method : - 

validateTransactionReceipt = (purchase) => {
        const receipt = purchase.transactionReceipt;
        if (receipt) {
            AppEventsLogger.logEvent("Subscription transaction receipt validated", { type: 'owner' });
            const receiptBody = {
                'receipt-data': purchase.transactionReceipt,
                'password': subscriptionSecret
            };

            RNIap.validateReceiptIos(receiptBody, true).then(receipts => {
                let lastReceipt = receipts.latest_receipt_info[receipts.latest_receipt_info.length - 1];
                console.log(lastReceipt, "lastReceipt...")
                let params = {
                    productId: purchase.productId,
                    transactionId: purchase.transactionId,
                    autoRenew: purchase.hasOwnProperty("originalTransactionDateIOS") ? true : false,
                    // autoRenew: true,
                    transactionDate: purchase.transactionDate,
                    status: "success",
                    transactionReceipt: lastReceipt,
                    paymentMode: receipts.environment,
                    originalTransactionDateIOS: purchase.hasOwnProperty("originalTransactionDateIOS") ? purchase.originalTransactionDateIOS : purchase.transactionDate,
                    originalTransactionIdentifierIOS: purchase.hasOwnProperty("originalTransactionIdentifierIOS") ? purchase.originalTransactionIdentifierIOS : purchase.transactionId
                }

                console.log(params, "params-1");
                this.subscriptionSaveHandler(params);
            });
            if (Platform.OS === 'ios') {
                RNIap.finishTransactionIOS(purchase.transactionId).then(response => {
                    console.log(response, "finish");
                });
            }
        }
    }

Thanks

**Comment by the-dut** [comment]
I think you need to initially call validateReceiptIos with a false parameter first, and then if that call returns a 21007 then you call it with true.  That way it will work in both prod and sandbox.  That's something I ran into.

**Comment by BStenfors9119** [comment]
I am having this same issue even with "isTest" set to "false" in calling RNIap.validateReceiptIos().

Testing on an actual device with "isTest" set to "true" seems to work but when pushed to production is does not work.
Some how Apple's testers approve my app which I am not sure how.

**Comment by the-dut** [comment]
Definitely when you validate the receipt validate in production (use false param), then if that returns with a status of 21007, validate in the sandbox (use true param).

Then after calling finishTransactionIOS(), also call finishTransaction().  

Hope that helps!

**Comment by BStenfors9119** [comment]
@the-dut awesome!  Going to give that configuration a try.

Will report back what happens :D.

I just wish Apple and Google had more solid abilities for devs to test before going through the process of release flows just to fined out our code doesn't work :/.

**Comment by BStenfors9119** [comment]
@the-dut ok now I am getting endless password / log in prompts after calling RNIap.requestSubscription([productId])

**Comment by the-dut** [comment]
It could be all the previous requests coming through that were never finalized.  Could be hundreds or thousands based on how much you've tested. Maybe once you get through them you might be ok.  

ALso, are you testing on a real device?  Local or TestFlight? Are you using a Sandbox user or a production id?   And if sandbox user, do you have that id set up in your phone as a Sandbox user?  

I never saw that issue.  But I can try to help.

**Comment by BStenfors9119** [comment]
ALso, are you testing on a real device? 
**Real Device via XCode :: iOS 13.6.1**

Local or TestFlight? 
**Local**

Are you using a Sandbox user or a production id?
**Sandbox User Id** 

And if sandbox user, do you have that id set up in your phone as a Sandbox user?
**They are set up**

here is my code

**purchaseUpdatedListener():**

```

await RNIap.clearTransactionIOS();
            let receipt = purchase.transactionReceipt;

            validatePurchase(receipt).then(async resp => {
                console.log('validated purchase');
                console.log(resp);
                // let iosTransactionFinished = await finishTransactionIOS(purchase.transactionId);
                let transactionFinished = await finishTransaction(purchase, false);
                let result = await successfullySubscribed(purchase);


                if (result.success && !fullFirstLaunchFlow) {
                    goTo('Home');
                }
            });

```
**validatePurchase():**

```
const receiptBody = {
                    'receipt-data': receipt,
                    'password': '<shared secret>'
                };

                console.log('validating purchase');

                let validReceipt = await RNIap.validateReceiptIos(receiptBody, false);
                console.log('valid receipt');
                console.log(validReceipt);
                if(validReceipt.status === 21007){
                    validReceipt = await RNIap.validateReceiptIos(receiptBody, true);
                    console.log('valid receipt was 21007');
                    console.log(validReceipt);
                }

```

**Comment by the-dut** [comment]
Is there a reason you have the finishTransactionIOS commented out?  You should do both finishTransactionIOS() and then finishTransaction()

**Comment by BStenfors9119** [comment]
I could be confused but I thought this description in the README meant to only use "finishTransaction" if using v4.1.0 or later.
I am currently using v4.5.4.

```
iOS only
Finish a transaction. Use finishTransaction instead for both platforms since version 4.1.0 or later.
```

**Comment by the-dut** [comment]
Great point!  I do both just in case.

**Comment by BStenfors9119** [comment]
well, either way it never gets to those lines yet, lol.

I will uncomment that line.  Anymore I am willing to try anything to get this working :D

**Comment by BStenfors9119** [comment]
Just upgraded to v5.0.0 hoping something might of changed but no dice.

Still getting multiple pwd prompts.

I am getting 2 at a time and after second prompt it errors out with "E_UNKNOWN" cannot connect to iTunes.

**Comment by the-dut** [comment]
Does it all start happening right when you add your updatedpurchaselistener?  If so, you may need to just get through all of the unfinished transactions first.  Or.. use your real apple id instead of the test user.

**Comment by BStenfors9119** [comment]
it all happens right at "requestSubscription()".  I never see another console log after that.

The only console log I see after requestSubscription executes is "Purchase Started !".

The next console log is "Purchase Failed!!" followed by the "E_UNKNOWN" errors inside of "puchaseErrorListener".

**Comment by the-dut** [comment]
Did you try with your real Apple ID?

**Comment by BStenfors9119** [comment]
I have not tried that yet.  Do I need to add my real Apple ID as a tester?

**Comment by the-dut** [comment]
No.  You can just use it I would think.

**Comment by BStenfors9119** [comment]
Using my Apple ID it only prompts me once and gives the "E_UNKOWN" error immediately.

**Comment by BStenfors9119** [comment]
just tried testing with a newly created Sandbox User but no dice.

2 pwd prompts and error.

**Comment by BStenfors9119** [comment]
what's really odd and I know it's not suppose to be this way now, is I use to have "finishTransaction()" before validating the receipt and it worked that way.

**Comment by BStenfors9119** [comment]
Quick update.

@the-dut  I submitted a build with everything setup how you suggested and it worked!! So now I am throwing caution to the wind and submitted it for production.

**Comment by the-dut** [comment]
That's great news!  Let us know how it goes!

**Comment by hyochan** [comment]
Thanks to all having discussions and sharing benefits in the current thread ❤️

**Comment by BStenfors9119** [comment]
Sorry for the delayed report.  

Forgot to add it works in production!!

Next up....accepting promotions so I can give my app for free to friends and family 😁

**Comment by rodrigopasc** [comment]
@BStenfors9119 what was the problem at all? Can you share exactly how you solve the problem? Thank you very much.

**Comment by c-info** [comment]
let receipt = purchase.transactionReceipt; 

does not return anything returns empty string
