### ISSUE TITLE
Get "An unknown error occurred" by Apple review.

### ISSUE THREAD

**Issue by oolionoo** [dooboolab/react-native-iap#1147]
### Version of react-native-iap 
3.3.7

### Version of react-native
0.60.4

### Platforms you faced the error
IOS (May be iOS 14 and Apple test environment only)

### Expected behavior
Able purchase, and return receipt

### Actual behavior
"An unknown error occurred" was return in purchaseErrorListener()

### Tested environment (Emulator? Real Device?)
When review by Apple.
I tried in Testflight with sanbox account not reproduce this issue

### Steps to reproduce the behavior
Make a purchase item in app.

Does anyone know how to handle this?

**Comment by chasepoirier** [comment]
Facing the same issue here, must be related to iOS 14?

**Comment by oolionoo** [comment]
I have never been reproduce this issue. It occured when reviewing by apple at iOS 14.
After updating the latest version (5.0.1), It has passed the review.

**Comment by ogntech** [comment]
Sorry @oolionoo . What do you update to version 5.0.1 ?

**Comment by oolionoo** [comment]
i updated this lib to 5.0.1.

And my package.json looklike below:
`"react-native-iap": "5.0.1",`

**Comment by Desintegrator** [comment]
faced this issue on 5.2.14

**Comment by DanielFredriksson** [comment]
Faced this issue on 6.0.0

**Comment by ilyasbat** [comment]
Same issue

**Comment by noway** [comment]
Happens to me too on the latest version of `react-native-iap` (6.0.6) and with IAP capability added. Can this be reopened?

**Comment by liannguyentribal** [comment]
2024 and it's happening to me too. Does anyone have any ideas?
