### ISSUE TITLE
[Question] - Receipts and Auto-renewing Subscriptions

### ISSUE THREAD

**Issue by the-dut** [dooboolab/react-native-iap#1148]
### Version of react-native-iap
4.4.9

### Version of react-native
0.62.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior (using TestFlight)
- When a user subscribes to a subscription I save the receipt in my database.
- When I start up my app, I grab the receipt from the database, validate it and check if the subscription date is still valid.

This all works even when the subscription auto-renews.  When I pull the receipt from my database and validate it, the new subscription data is there and it all looks great!  It's all working with the original receipt from the original purchase.
Is it supposed to work this way?  I thought each renewal of a subscription had a new receipt.

It's working great in TestFlight, but I want to make sure this is how it works in production as well.  I just worry that in production things will stop working when the subscription auto-renews.   

### Actual behavior
(See above)

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
(see  above)

**Comment by the-dut** [comment]
I found out the answer to this from Apple.  And what I described above is working that way by design and should work fine in production.  They did caution me against using client validation though, and that longer term it's more secure to move receipt validation to your secure server. That's on the backlog, so I should be good.

**Comment by sufyan297** [comment]
Hey @the-dut could you please help me with the Auto Renewable subscriptions?
**Issue:** My Transactions are not getting finished. i got alert box "**Purchase completed successfully**", but when i restart app and go to Subscription Page, **purchaseUpdatedListener** again getting called. I am receiving receipt again.

Please man, will appreciate it, been stuck for over 10 days :(
 Apple documentation are not clear 

Here is my code

```import React from 'react';
import { View, Text, Button, Alert } from 'react-native';
import * as RNIap from 'react-native-iap';
import { get } from 'lodash';

let purchaseUpdateSubscription;
let purchaseErrorSubscription;
export default class PremiumMembership extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      subscription: {},
      receiept: false
    }
  }

  componentDidMount() {
    this.getSubscriptions();

    purchaseUpdateSubscription = RNIap.purchaseUpdatedListener(
      async purchase => {
        const receipt = purchase.transactionReceipt;
        if (receipt) {
          console.log('receipt', receipt);
          try {
            if (Platform.OS === 'ios') {
              const finishTransactionIOS = await RNIap.finishTransactionIOS(
                purchase.transactionId,
              );
              console.log("FinishTransactionIOS: ", finishTransactionIOS)
              Alert.alert('finishTransactionIOS', finishTransactionIOS);
            }
          } catch (ackErr) {
            Alert.alert('ackErr', ackErr);
          }
          this.setState({receipt});
        }
      },
    );

    purchaseErrorSubscription = RNIap.purchaseErrorListener(error => {
      console.log('purchaseErrorListener', error);
      Alert.alert('purchaseErrorSubscription error:', JSON.stringify(error));
    });
  }

  componentWillUnmount() {
    if (purchaseUpdateSubscription) {
      purchaseUpdateSubscription.remove();
      purchaseUpdateSubscription = null;
    }
    if (purchaseErrorSubscription) {
      purchaseErrorSubscription.remove();
      purchaseErrorSubscription = null;
    }
    RNIap.endConnection();
  }

  async getSubscriptions() {
    try {
      await RNIap.initConnection();
      const subscriptions = await RNIap.getSubscriptions(['test_subscription']);
      console.log("Subscription: ", subscriptions);
      this.setState({subscription: subscriptions[0]});
    } catch (error) {
      console.log("Unable to get Subscriptions...", error);
    }
  }

  async onSubscribe() {
    try {
      await RNIap.requestSubscription('test_subscription', true);
    } catch (error) {
      console.log("Unable to subscribe...", error);
    }
  }

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Text>Subscription Screen</Text>
        <Text>Subscription Name: {get(this.state,'subscription.title', null)}</Text>
        <Text>Price: {get(this.state, 'subscription.localizedPrice', null)}</Text>
        <Text>Receiept: {get(this.state, 'receipt', false)  ? 'true' : 'false'}</Text>
        <Button title={'Subscribe'} onPress={() => this.onSubscribe()}/>
      </View>
    )
  }
}
`
