### ISSUE TITLE
[Question]: Android - verify subscription valid (renewable and non-renewable)

### ISSUE THREAD

**Issue by lbuljan** [dooboolab/react-native-iap#1151]
### Version of react-native-iap
5.0.1
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
Android

I have a project on hand that has multiple subscription options - monthly, yearly and lifetime subscriptions, but I am not exactly sure how to handle verifying if the subscription is still active on Android.

On iOS, I do this:

`const validation = await validateReceiptIos({
        'receipt-data': privateProfile.purchase.transactionReceipt,
        password: 'xxx',
      });

      if (!validation) {
        // Store subscription inactive
        return;
      }

      if (!validation.receipt.expiration_date) {
        // Lifetime subscription, store as active
        return;
      }

      const isActive = isAfter(
        new Date(validation.receipt.expiration_date),
        Date.now(),
      );
      // Store is active state;`

.. whereas on Android, I am a bit stumped and I can't find any definitive answer in any of the documentation on hand.
This is as far as I got: 

`if (Platform.OS === 'android') {
      const purchases = await getAvailablePurchases();
      if (!purchases.length) {
        // Store as inactive
        return;
      }
    }`

Any pointers?

**Comment by hyochan** [comment]
I think @iaphub could be a great candidate to help you out.

**Comment by andresesfm** [comment]
If you call `getSubscriptions()` and the subscription is valid, you'll get it in the array, otherwise, it means that it's no longer valid
