### ISSUE TITLE
React Native IAP Android Product List Empty Array

### ISSUE THREAD

**Issue by xhsynx** [dooboolab/react-native-iap#1153]
"react-native-iap": "^4.6.2",

"react-native": "~0.61.5",

Android

Get ProductList Array

Empty ProductList Array

Real Device

Upload package with <uses-permission android:name="com.android.vending.BILLING" /> release test

JS Code

import {
  Alert,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import RNIap, {
  InAppPurchase,
  PurchaseError,
  SubscriptionPurchase,
  acknowledgePurchaseAndroid,
  consumePurchaseAndroid,
  finishTransaction,
  finishTransactionIOS,
  purchaseErrorListener,
  purchaseUpdatedListener,
} from "react-native-iap";
import React, { Component } from "react";
import { Button } from "react-native";

// App Bundle > com.dooboolab.test

const itemSkus = Platform.select({
  ios: ["com.app.month1", "com.app.month3", "com.app.month6"],
  android: ["com.app.month1", "com.app.month3", "com.app.month6"],
});

let purchaseUpdateSubscription;
let purchaseErrorSubscription;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: Platform.select({
      ios: 0,
      android: 24,
    }),
    paddingTop: Platform.select({
      ios: 0,
      android: 24,
    }),
    backgroundColor: "white",
  },
  header: {
    flex: 20,
    flexDirection: "row",
    alignSelf: "stretch",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTxt: {
    fontSize: 26,
    color: "green",
  },
  content: {
    flex: 80,
    flexDirection: "column",
    justifyContent: "center",
    alignSelf: "stretch",
    alignItems: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
  },
  btn: {
    height: 48,
    width: 240,
    alignSelf: "center",
    backgroundColor: "#00c40f",
    borderRadius: 0,
    borderWidth: 0,
  },
  txt: {
    fontSize: 16,
    color: "white",
  },
});

export default class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      productList: [],
      receipt: "",
      availableItemsMessage: "",
    };
  }

  async componentDidMount() {
    try {
      const result = await RNIap.initConnection();
      await RNIap.flushFailedPurchasesCachedAsPendingAndroid();
      console.log("result", result);
    } catch (err) {
      console.warn(err.code, err.message);
    }

    purchaseUpdateSubscription = purchaseUpdatedListener(async (purchase) => {
      const receipt = purchase.transactionReceipt;
      if (receipt) {
        try {
          // if (Platform.OS === 'ios') {
          //   finishTransactionIOS(purchase.transactionId);
          // } else if (Platform.OS === 'android') {
          //   // If consumable (can be purchased again)
          //   consumePurchaseAndroid(purchase.purchaseToken);
          //   // If not consumable
          //   acknowledgePurchaseAndroid(purchase.purchaseToken);
          // }
          const ackResult = await finishTransaction(purchase);
        } catch (ackErr) {
          console.warn("ackErr", ackErr);
        }

        this.setState({ receipt }, () => this.goNext());
      }
    });

    purchaseErrorSubscription = purchaseErrorListener((error) => {
      console.log("purchaseErrorListener", error);
      Alert.alert("purchase error", JSON.stringify(error));
    });
  }

  componentWillUnmount() {
    if (purchaseUpdateSubscription) {
      purchaseUpdateSubscription.remove();
      purchaseUpdateSubscription = null;
    }
    if (purchaseErrorSubscription) {
      purchaseErrorSubscription.remove();
      purchaseErrorSubscription = null;
    }
    RNIap.endConnection();
  }

  goNext = () => {
    Alert.alert("Receipt", this.state.receipt);
  };

  getItems = async () => {
    try {
      const products = await RNIap.getProducts(itemSkus);
      console.log("Products", products);
      this.setState({ productList: products });
    } catch (err) {
      console.warn(err.code, err.message);
    }
  };

  getAvailablePurchases = async () => {
    try {
      console.info(
        "Get available purchases (non-consumable or unconsumed consumable)"
      );
      const purchases = await RNIap.getAvailablePurchases();
      console.info("Available purchases :: ", purchases);
      if (purchases && purchases.length > 0) {
        this.setState({
          availableItemsMessage: `Got ${purchases.length} items.`,
          receipt: purchases[0].transactionReceipt,
        });
      }
    } catch (err) {
      console.warn(err.code, err.message);
      Alert.alert(err.message);
    }
  };

  // Version 3 apis
  requestPurchase = async (sku) => {
    try {
      RNIap.requestPurchase(sku);
    } catch (err) {
      console.warn(err.code, err.message);
    }
  };

  requestSubscription = async (sku) => {
    try {
      RNIap.requestSubscription(sku);
    } catch (err) {
      Alert.alert(err.message);
    }
  };

  render() {
    const { productList, receipt, availableItemsMessage } = this.state;
    const receipt100 = receipt.substring(0, 100);

    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.headerTxt}>react-native-iap V3</Text>
        </View>
        <View style={styles.content}>
          <ScrollView style={{ alignSelf: "stretch" }}>
            <View style={{ height: 50 }} />
            <Button
              title="available purchases"
              onPress={this.getAvailablePurchases}
              activeOpacity={0.5}
              style={styles.btn}
              textStyle={styles.txt}
            />

            <Text style={{ margin: 5, fontSize: 15, alignSelf: "center" }}>
              {availableItemsMessage}
            </Text>

            <Text style={{ margin: 5, fontSize: 9, alignSelf: "center" }}>
              {receipt100}
            </Text>

            <Button
              title="get items"
              onPress={() => this.getItems()}
              activeOpacity={0.5}
              style={styles.btn}
              textStyle={styles.txt}
            />

            {productList.map((product, i) => {
              return (
                <View
                  key={i}
                  style={{
                    flexDirection: "column",
                  }}
                >
                  <Text
                    style={{
                      marginTop: 20,
                      fontSize: 12,
                      color: "black",
                      minHeight: 100,
                      alignSelf: "center",
                      paddingHorizontal: 20,
                    }}
                  >
                    {JSON.stringify(product)}
                  </Text>
                  <Button
                    // onPress={(): void => this.requestPurchase(product.productId)}
                    title="Request purchase for above product"
                    onPress={() => this.requestSubscription(product.productId)}
                    activeOpacity={0.5}
                    style={styles.btn}
                    textStyle={styles.txt}
                  />
                </View>
              );
            })}
          </ScrollView>
        </View>
      </View>
    );
  }
}

**Comment by xhsynx** [comment]
it took a one with but i could not resolve issue still could you please help me. Thank you.

**Comment by AmauryLiet** [comment]
@xhsynx maybe #1143 could help you?

**Comment by xhsynx** [comment]
> @xhsynx maybe #1143 could help you?

I have already followed #1143 this post. I used test id for android it is fine. But it is still returning empty array for my product ids. I sent my app for internal test also i sent my app alpha test and google approved. But still product list is empty.

**Comment by floelm** [comment]
I would recommend to change your existing products again (e.g. change the title) because i noticed sometimes there is some weird caching in place. I think making changes clear this cache. If this does not work you could also try to create a new IAP-Product and try to load that one inside your app.

Also did you add the billing permission to your Manifest?

Those are the things that come to my head first, maybe something works for you.

**Comment by xhsynx** [comment]
@floelm 
It is not about google it is about react native 0.61.5 and react-native-iap. I include expo-in-app-purchases and call getproductlist no problem all productlist comes. Additionally i also followed your steps again.
