### ISSUE TITLE
RNIapModule.buyItemByType got 8 arguments, expected 7

### ISSUE THREAD

**Issue by bcbcbcbcbcl** [dooboolab/react-native-iap#1154]
### Version of react-native-iap
4.6.3

### Version of react-native
0.60.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Able to purchase subscription or consumable

### Actual behavior
Got the error as shown in image below
<img src="https://user-images.githubusercontent.com/39854319/95878366-b8705080-0da7-11eb-9857-0aeddcb982d2.jpg" width="300">

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
1. Purchase a subscription/consumable.

**Comment by nochkin** [comment]
Posting your issue in several places makes it confusing for you in the first place.
Anyway, the version you are using is pretty old. You need to update to the latest (currently it is 5.0.1) as the fix is present in newer versions.
I actually just tried it on Google Play and Amazon App Store based devices with no issues.

**Comment by bcbcbcbcbcl** [comment]
The version I'm using (v4.6.3) is released 18 days ago. There is no error when I switched to v4.6.1

**Comment by nochkin** [comment]
4.6.3 is not the latest version which makes your bug report obsolete.
Not sure why you are going back to 4.6.1 instead of going forward. Please update to the latest one going forward. It has the fix for the issue you described.

**Comment by hyochan** [comment]
It is always recommended to try the latest version. However, it is good to know that there might be a regression issue. There were breaking changes in bumping up a version `4.6.1` to `4.6.3` internally which I've removed some arguments that do not exist anymore in the new android billing sdk which is version 3.

It was my fault for not bumping up the version correctly based on [semver](https://www.npmjs.com/package/semver). It will not update your dependency correctly not upgrading the first letter `4`. You may try to remove `node_modules` and `yarn.lock` and re-install them and confirm if `4.6.3` works correctly.

Feel free to come back if you have any progress. Closes for now.
