### ISSUE TITLE
[Question] RN 0.60 and RN IAP v2

### ISSUE THREAD

**Issue by Simon-44** [dooboolab/react-native-iap#1156]
Hello,

Is it possible to keep the v2 version of RN IAP and still upgrade the app to RN 0.60? I don't feel like migrating the payment system for now, but I've no choice but migrating to RN 0.60.

The weird thing is I just tested on my dev environment with RN 0.60 and RN IAP v4 without changing anything in my code, except renaming `buySubscription` in `requestSubscription`, and everything worked fine like before. I'm a bit confused since I thought the workflow had changed.

Also, I read this: "For ios under version 12, it is compatible until react-nativep-iap version 2.4.8. From 2.4.9, it will support ios >= 12." Does it mean that RN IAP versions from 2.4.9 **don't** support iOS prior to 12 anymore? Or does it mean that RN IAP versions under 2.4.8 don't support iOS 12?

Thanks a lot.

**Comment by hyochan** [comment]
Thanks for asking questions. We generally focus on the latest version and compatibility so we might not handle lower versions that existed previously. However, they might be working fine today as long as `android` and `ios` did not drop those compatibilities although they changed their apis afterward.

The design for the purchase flow has changed but the APIs that `react-native-iap` is using are similar so it won't affect the native compatibilities.

Lastly, we don't actually support iOS version under version 12 and have concluded to end support in `< 3.0.0`. They might however be working in recent native sdks however we don't guarantee them. It is your choice to handle that either.
