### ISSUE TITLE
Verify the purchase is auto-renew or non-renew on iOS

### ISSUE THREAD

**Issue by dungle-groove** [dooboolab/react-native-iap#1157]
### Version of react-native-iap
4.5.2

### Version of react-native
0.60.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
When I call requestSubscription() and listen the purchase data. I want to determine the purchase is auto-renew or non-renew. I see there is a property with Android but for iOS currently I don't know how to detect it

### Actual behavior
(see above)

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
(see above)

**Comment by hyochan** [comment]
You might have to check that with the `receipt` returned when making a purchase. Followed by the [one of the libraries](https://github.com/Wizcorp/node-iap) that handles receipt data, you can retrieve the `renewal date` in iOS and this seems to be possible by checking the receipt.
