### ISSUE TITLE
iOS free trial Promotion offer is not Applying. 

### ISSUE THREAD

**Issue by igeeganage** [dooboolab/react-native-iap#1158]
### Version of react-native-iap
4.4.9

### Version of react-native
react-native-cli: 2.0.1
react-native: 0.62.2

### Platforms you faced the error (IOS or Android or both?)
iOS 
App target version is iOS 12.2 and up

### Expected behavior
In my subscription is indicating that a free trial is available.  however when the user is going  to buy the product, the Apple-controlled screen indicates no free trial, instead they are signing up for the subscription right away without trial period. 

My Product object
{
    "productId": "xxx",
    "subscriptionPeriodUnitIOS": "MONTH",
    "description": "Upgrade to Family HQ Basic features",
    "introductoryPrice": "",
    "title": "Basic Features",
    "introductoryPriceSubscriptionPeriodIOS": "",
    "introductoryPriceNumberOfPeriodsIOS": "",
    "discounts": [
      {
        "localizedPrice": "$0.00",
        "numberOfPeriods": "2",
        "type": "SUBSCRIPTION",
        "identifier": "xxx-xx",
        "paymentMode": "FREETRIAL",
        "price": "0",
        "subscriptionPeriod": "WEEK"
      }
    ],
    "type": "Do not use this. It returned sub only before",
    "localizedPrice": "$0.99",
    "introductoryPricePaymentModeIOS": "",
    "price": "0.99",
    "currency": "AUD",
    "subscriptionPeriodNumberIOS": "1"
  }

### Actual behavior
Purchase amount should be deducted after the trial period (14 days). 

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by hyochan** [comment]
I think we need a contributor for testing this out and enhancing reliability.

**Comment by j-cheung** [comment]
hi, any idea if this has been fixed? or any workarounds?

thanks.

**Comment by pm-moritz** [comment]
hi, i got the same problem and would be interested in any solutions too. Thanks!

**Comment by apfritts** [comment]
If it's on the Apple-controlled screen, then there is a configuration problem with your in-app purchases. iOS doesn't provide developers with a mechanism for controlling whether a user can or should start a free trial or not, it's all handled by the App Store.

**Comment by pm-moritz** [comment]
thanks a lot, we contacted our customer and this was exactly the problem 🙈
