### ISSUE TITLE
How to validate receipt for XCODE 12 -> StoreKit Framework local enviornment. 

### ISSUE THREAD

**Issue by bhavnasohpaul** [dooboolab/react-native-iap#1164]
### Version of react-native-iap
5.0.1
### Version of react-native
0.62.2
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
There should be some option to validate receipt locally for  "StoreKit Test Enviornment". Suggested some code following by Apple on this link (https://developer.apple.com/documentation/xcode/setting_up_storekit_testing_in_xcode)
"" 
#if DEBUG
    let certificate = “StoreKitTestCertificate” 
#else
    let certificate = “AppleIncRootCertificate” 
#endif
""

### Actual behavior
validateReceiptIos() allowed to validate receipt only for Production(https://sandbox.itunes.apple.com/verifyReceipt) and Sandbox(https://buy.itunes.apple.com/verifyReceipt) ONLY.
### Tested environment (Emulator? Real Device?)
XCODE 12 -> simulator

**Comment by hyochan** [comment]
Good point. We might have to think how to handle this. I used to test sandbox in #Debug mode. However, if we change all that to `StoreKitTestCertificate`, it might confuse devs who use sandbox in #DEBUG flag.

What would be your idea?

**Comment by gurol** [comment]
This feature should be supported urgent. It will definitely enhance our testing process (no need to test subscriptions in the device, testing different scenarios and automation support). I don't know how but maybe you can enable this debug code when there is a "StoreKitTestCertificate.cer" file in "ios" folder (default location to save the certificate), otherwise test sandbox.

**Comment by Exilz** [comment]
I agree, being able to fully test the payment inside the simulator would be a great plus. Setting up your storekit validation is easy but there's no straightforward way of validating the receipts.

**Comment by cjpete** [comment]
It's a shame this got closed with inactivity - it's still a valid concern. Anyone following the apple documentation will likely reach the same conclusion here, which is that using `react-native-iap` and storekit testing in XCode aren't really compatible.

Ideally developers can specify their own development environment, e.g. with setting some flags in AppDelegate or by initialising the react-native-iap library with some settings?

**Comment by pvroosendaal** [comment]
Would love to see a solution for this as well. I'm not very experienced in react native yet, so not able to contribute to this repo directly, but I'd love to think along.

**Comment by jimmyrheereckon** [comment]
Do we have any update on `Storekit testing`?

It would be really nice to have it compatible with `react-native-iap`
