### ISSUE TITLE
Validate Google receipt get UNSPECIFIED_STATE

### ISSUE THREAD

**Issue by binhchili** [dooboolab/react-native-iap#1169]
### Steps to reproduce the behavior
When I touch buy button , emulator prompt to screen Google 's purchase UI with 1-click buy button. Then I touch it and it shows me the purchase is successful. I try to log out `purchase` object and note that there are 2 fields: `purchaseState` in `transactionReceipt` return 0 and `purchaseStateAndroid` return 1, which make me really confused. After that I send my purchase to back-end server to validate receipt. The server uses `InAppPy` library to validate the receipt (here its link : https://github.com/dotpot/InAppPy) and give me this response: 
```
{"data": {"bundle_id": "com.zenga.hoc68", 
"order_id": "GPA.3337-2127-6788-25984", "product_id": "com.zenga.h68.nap100k", 
"purchase_state": "UNSPECIFIED_STATE"}}
```
As far I know `UNSPECIFIED_STATE` means the product is not purchased yet. But in my Google Console account all the purchases are successful and I always get an email from GooglePlay inform that transaction is completed. Anyone can explain this situation ?

This is my code below:
```
useEffect(() => {
        RNIap.getAvailablePurchases().then(purchase => {
            console.log('All purchase: ' + purchase);
        }).catch(e => console.log(e))
        async function prepare() {
            try {
                const result = await RNIap.initConnection();
                // const consume = await RNIap.consumeAllItemsAndroid();
                await RNIap.flushFailedPurchasesCachedAsPendingAndroid();
                console.log('result', result);
                setConnected(true);
            } catch (err) {
                console.log(JSON.stringify(err));
            }
        };

        prepare();


        purchaseUpdateSubscription = purchaseUpdatedListener(
            async (purchase) => {
                console.log('done');
                const receipt = purchase.transactionReceipt;
                if (receipt) {

                    const signature = Platform.OS == 'android' ? purchase.signatureAndroid : '';
                    const device = Platform.OS == 'android' ? 'ANDROID' : 'IOS';
                    console.log(purchase);


                    ///call api
                    Purchase.valiadateGoogleApple(stateTree.user.token_key, receipt, signature, device).then(res => {
                        console.log(res.data);
                    }).finally(() => {
                        finishTransaction(purchase, true);//ket thuc giao dich
                    }).catch(e => console.log(e));


                }
            }
        );

        purchaseErrorSubscription = purchaseErrorListener(
            async (error) => {
                try {

                    Alert.alert('purchase error', JSON.stringify(error));
                } catch (ex) {
                    console.log('fatal error' + ex);
                }

            }
        );
        return function cleanUp() {
            if (purchaseUpdateSubscription) {
                purchaseUpdateSubscription.remove();
                purchaseUpdateSubscription = null;
            }
            if (purchaseErrorSubscription) {
                purchaseErrorSubscription.remove();
                purchaseErrorSubscription = null;
            }
            RNIap.endConnection();
        };

    }, [])
```

**Comment by hyochan** [comment]
Thanks for the detailed review. However, I think this should be asked in https://github.com/dotpot/InAppPy rather than `react-native-iap` since I think the android SDK is returning correct values which is `Purchased` and the receipt has the wrong data.

I hope, you can give further information to this.

**Comment by Decoder3-14** [comment]
@binhchili Hi, have you figure out the problem? I am using the same library for backend verification. I cannot seem to have the purchaseState to be 1 or acknowledged to be true no matter how many changes I make.

**Comment by andresesfm** [comment]
@binhchili have you tried on a real device? I agree with @hyochan this looks more like a problem with your backend service. If you get the receipt, it means that the purchase worked as expected. 

Closing it as it's stale, please feel free to open if more info
