### ISSUE TITLE
RNIap.getPurchaseHistory() never resolves nor rejects

### ISSUE THREAD

**Issue by cwmilazzo** [dooboolab/react-native-iap#1170]
### Steps to reproduce the behavior
     try {
           await RNIap.initConnection();
            console.log('Getting available purchases already completed)');
            const purchaseHistory = await RNIap.getPurchaseHistory();
            console.log('DONE Getting available purchases already completed)');
        } catch (error) {
            console.error('Error was thrown waiting for getPurchaseHistory()')
        }

The code above prints the first log message (Getting ...) but never prints either the error message or the "DONE" message.

**Comment by cwmilazzo** [comment]
Interestingly, I reverted back to 4.63, and I see the same behavior.  I'm trying with a brand new test account so there should be no purchase history.

**Comment by andresordonezfm** [comment]
Yes it stop working... I was reviewing library code and paymentQueueRestoreCompletedTransactionsFinished, restoreCompletedTransactionsFailedWithError is not firing..

**Comment by cwmilazzo** [comment]
Not sure if it's related or not, but I'm also noticing that my purchaseUpdatedListener is never getting called either

**Comment by andresordonezfm** [comment]
Yes me too the same problem

**Comment by andresordonezfm** [comment]
Hi dude, my problem with Listener was that I didn't calling 
await RNIap.initConnection(); 
Before start the listeners

And in componentWillUnmount
RNIap.endConnection();

But I still having problems with response time getPurchaseHistory service, and also when I call RNIap.getPurchaseHistory () before the RNIap.requestSubscription (sku)

**Comment by StefanoCremona** [comment]
Any luck? I have the same problem on iOS. 
It was working one month ago 😭

Version of react-native-iap : 5.0.1
Version of react-native: 0.60.6
