### ISSUE TITLE
purchaseUpdatedListener called multiple times even after purchase 

### ISSUE THREAD

**Issue by marcibk** [dooboolab/react-native-iap#1172]
### Version of react-native-iap
5.0.1
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
purchaseUpdatedListener not getting called multiple times 
### Actual behavior
purchaseUpdatedListener getting called on startup multiple times, sometimes even in between
### Tested environment (Emulator? Real Device?)
Real device (iOS 14, 13 in Test Flight and in AppStore)
### Steps to reproduce the behavior

(Navigator Component)

```
const itemSkus = ['01', '02'];

const processNewPurchase = async (purchase) => {
  const { productId, transactionReceipt } = purchase;
  if (transactionReceipt !== undefined && transactionReceipt) {
       //backend call with fetch - validating receipt 
        if (data.ack === 'success') {
          console.log('finished');
          await finishTransaction(purchase);
      } else if (data.ack === 'failure') {
          props.setProcessing(false);
          console.log('error');
      }
    }
};


const getProductsIAP = useCallback(async () => {
  await clearProductsIOS();
  await clearTransactionIOS();

 try {
   const result = await initConnection();
   const products = await getProducts(itemSkus);
   props.setProducts(products);
   console.log('result', result);
 } catch (err) {
   console.warn(err.code, err.message);
 }

  purchaseUpdateSubscription = purchaseUpdatedListener(
    async (purchase) => {
      const receipt = purchase.transactionReceipt;
      console.log('purchaseUpdatedListener');
      if (receipt) {
        try {
          await processNewPurchase(purchase);
        } catch (ackErr) {
           console.log('ackErr', ackErr);
        }
      } else {
        console.log('purchaseUpdatedListener error: receipt');
      }
    },
  );

  purchaseErrorSubscription = purchaseErrorListener(
    (error: PurchaseError) => {
      console.log('purchaseErrorListener', error);
      console.log(JSON.stringify(error));
    },
  );

  setLoading(false);
}, []);


useEffect(() => {
  getProductsIAP();

  return () => {
    if (purchaseUpdateSubscription) {
      purchaseUpdateSubscription.remove();
      purchaseUpdateSubscription = null;
    }
    if (purchaseErrorSubscription) {
      purchaseErrorSubscription.remove();
      purchaseErrorSubscription = null;
    }
  };
}, []);

```

**Comment by hyochan** [comment]
Does the event fire the same purchase results?

**Comment by traingethermarc** [comment]
Yes, it fires with the successful results/receipt. If there is no current receipt it fires too, but fails on the validation server.

**Comment by hyochan** [comment]
Could you please check if your component is not rerendered? There were lots of issue when the component rerendered and listeners started several times occationally. Well that should be released tough but we need to reproduce your case.

**Comment by traingethermarc** [comment]
Well, it's the "NavigatorContainer" means I am setting different states, updating stuff and so on. But <NavigatorContainer/> only renders one and then "rerenders" for the update of different states, props...

But that's what is for - to unsubscribe to the listeners/to avoid this. ```
useEffect(() => {
  getProductsIAP();

  return () => {
    if (purchaseUpdateSubscription) {
      purchaseUpdateSubscription.remove();
      purchaseUpdateSubscription = null;
    }
    if (purchaseErrorSubscription) {
      purchaseErrorSubscription.remove();
      purchaseErrorSubscription = null;
    }
  };
}, []);
```

**Comment by hyochan** [comment]
> Well, it's the "NavigatorContainer" means I am setting different states, updating stuff and so on. But only renders one and then "rerenders" for the update of different states, props...
> 
> But that's what is for - to unsubscribe to the listeners/to avoid this.
> 
> ```
> useEffect(() => {
>   getProductsIAP();
> 
>   return () => {
>     if (purchaseUpdateSubscription) {
>       purchaseUpdateSubscription.remove();
>       purchaseUpdateSubscription = null;
>     }
>     if (purchaseErrorSubscription) {
>       purchaseErrorSubscription.remove();
>       purchaseErrorSubscription = null;
>     }
>   };
> }, []);
> ```

Yes I have also mentioned this. Just shared the previous issue I remember. We need the reproduction.

Also, cleariing transaction or trying with different testflight account might help.

**Comment by traingethermarc** [comment]
```
const getProductsIAP = useCallback(async () => {
  await clearProductsIOS();
  await clearTransactionIOS();

.....
```

Tested in in TestFlight, production and different devices.

**Comment by hyochan** [comment]
Different account?

**Comment by traingethermarc** [comment]
Yes, same result.

**Comment by hyochan** [comment]
Strange. Could you also try the code snippet in our `IapExample` project?

**Comment by edo1493** [comment]
I have the following behaviour.

1) User buys IAP.
2) purchaseUpdatedListener gets called.
3) User uninstalls the app.
4) User comes back to the app.
5) purchaseUpdatedListener gets triggered and goes in a loop.

**Comment by chiporgar7** [comment]
> Tengo el siguiente comportamiento.
> 
> 1. El usuario compra IAP.
> 2. Se llama a purchaseUpdatedListener.
> 3. El usuario desinstala la aplicación.
> 4. El usuario vuelve a la aplicación.
> 5. purchaseUpdatedListener se activa y forma un bucle.
> 
> Estoy usando clases, pero no veo ninguna repetición.
> 
> Estoy en "react-native-iap": "4.4.1" y "react-native": "0.63.3".
> 
> Intenté actualizar a 5.0.0, pero obtengo el mismo comportamiento.

you found a solution to this ?? , i am having this problem. I've been looking to solve this for a long time



`
    let purchaseUpdateScription

    useEffect(() => {

        IAP.initConnection().then(()=>{

            console.log('connected store')
            
            IAP.getProducts(productIds).then(res => {
                setProducts(res)
            });
            
            purchaseUpdateScription =  IAP.purchaseUpdatedListener(
                (purchase) => {

                    if(purchase.transactionReceipt) {

                        console.log('Call Back')

                          

                            IAP.finishTransaction(purchase)
                        

                        }
                    },
                );

            })

        return () => {
            purchaseUpdateScription.remove()
        };
      
    },[])

`



that's my code i have, but when i enter IAP.purchaseUpdatedListene
stays cycled

**Comment by chiporgar7** [comment]
> Tengo el siguiente comportamiento.
> 
> 1. El usuario compra IAP.
> 2. Se llama a purchaseUpdatedListener.
> 3. El usuario desinstala la aplicación.
> 4. El usuario vuelve a la aplicación.
> 5. purchaseUpdatedListener se activa y forma un bucle.
> 
> Estoy usando clases, pero no veo ninguna repetición.
> 
> Estoy en "react-native-iap": "4.4.1" y "react-native": "0.63.3".
> 
> Intenté actualizar a 5.0.0, pero obtengo el mismo comportamiento.




Hello one question. did you find the solution to this?

**Comment by traingethermarc** [comment]
Still same problem. Looks like it´s purchaseUpdatedListener is broken. Please fix this asap. No solution found.

**Comment by kenljv** [comment]
Having same issue with this. How is it possible that it's not fixed for months? Is this not a critical issue or has someone found a workaround for this? Also if it helps, I think I only encountered this issue when I upgraded my device from iOS 13 to iOS 14. As far as I could recall it was working fine on iOS 13 but I could be mistaken.

**Comment by apperside** [comment]
Same issue here.
I noticed that it happens every time I save the code and the app is hot reloaded.
In this scenario the root component is unmounted, and then remounted.

This is my `useIap()` hook

```
const useIap=()=>{

const purchaseUpdateSubscription = useRef<EmitterSubscription[]>([]);
    const purchaseErrorSubscription = useRef<EmitterSubscription[]>([]);

const init = useCallback(async () => {
        console.taggedLog(logTag, 'call iap init');

        await RNIap.initConnection();

        await RNIap.flushFailedPurchasesCachedAsPendingAndroid();

        purchaseUpdateSubscription.current.push(RNIap.purchaseUpdatedListener(async purchase => {
            console.taggedLog(logTag, 'purchaseUpdatedListener', purchase);

            try {
                await finalizePurchase(purchase);
            } catch (err) {
                handleFailedPurchase();
            }
        }));

        // use array to be sure to not accidentally overwrite subscriptions and lose access to them.
        // being an array I can always iterate and call `remove` on them
        purchaseErrorSubscription.current.push(RNIap.purchaseErrorListener(error => {
            handleFailedPurchase(error);
        }));

        updateProducts();
        return clear;
    }, []);

  const clear = useCallback(() => {
        console.taggedLog(logTag, 'clearing all');
        clearPurchaseEventListeners();
    }, [clearPurchaseEventListeners]);


 const clearPurchaseEventListeners = useCallback(() => {
        console.taggedLog(logTag, 'clearing purchase event listener', purchaseUpdateSubscription.current.length, purchaseErrorSubscription.current.length);
        purchaseUpdateSubscription.current.forEach(sub => sub.remove());
        purchaseErrorSubscription.current.forEach(sub => sub.remove());
        purchaseUpdateSubscription.current = [];
        purchaseErrorSubscription.current = [];
    }, []);

return {init,clear}
}
```

And then i use this code in the root component


```
const iap=useIap();
 useEffect(() => {
        console.log("root component mounted");
        iap.init();

        return () => {
            console.log("root component unmounted");
            iap.clear();
        };
    }, []);
```

The root component can happen to get unmounted and remounted, the `clear` method is called though, and I also see the log 'clearing purchase event listener',1,1, which means it's going to clear them.

Even in this situation, the purchase purchaseUpdatedListener is still called many times, es

**Comment by musakhani** [comment]
any solution?

**Comment by RixBai** [comment]
Have the same issue.
Any updates on this?

**Comment by Silavin** [comment]
Same issue for me. It calls the past receipts when the iap initialises the next time.

**Comment by GleidsonDaniel** [comment]
I had the same problem and I realized that the same was happening because I was not assembling and disassembling the component correctly, thus making several listeners open at the same time.

`  componentWillUnmount() {
    if (this.purchaseUpdateSubscription) {
      this.purchaseUpdateSubscription.remove();
      this.purchaseUpdateSubscription = null;
    }
    if (this.purchaseErrorSubscription) {
      this.purchaseErrorSubscription.remove();
      this.purchaseErrorSubscription = null;
    }
  }`
  
 Every time a purchase is made and the component is disassembled it is necessary to remove the listener and add a new one when assembling the component.

**Comment by MrShakes** [comment]
A possible workaround, testing I noticed that it sometimes shows the past receipts(sent to the server) so what I did is immediately store the transactionId of each notification received, so you always check the database first for if this transactionId has been processed and if so then ignore(it's a duplicate) if not then you can proceed. If the notification comes first to the App(rather than the server) then you can put some logic to control this i.e you should only receive 1 after a certain button has been clicked etc.
After testing extensively it stopped duplicating after a while, something's going on there.

**Comment by traingethermarc** [comment]
Yes, there are some sketchy workarounds, but all are pretty .... 
Please just fix this issue. This is definitely a critical and project breaking bug since October 2020....

**Comment by chiporgar7** [comment]
There is only one solution, is to use  **: Revenuecat ;)**

**Comment by chiporgar7** [comment]
> ¿alguna solución?

Revenuecat

**Comment by Desintegrator** [comment]
same issue

**Comment by hyochan** [comment]
Have you guys checked `getPendingPurchasesIOS()` and try finishing it after checking the status?

**Comment by hyochan** [comment]
Please look into below information and see if these helps.
```
What you're seeing with multiple process purchase calls is actually normal in the case of auto-renewing subscriptions. When you test in the sandbox those subscriptions renew very quickly (how fast depends on sub period) and you can often see several of those appear in the queue after an app restart. Also, if a purchase hasn't been successfully completed (which is likely given those exceptions) then they can remain in the queue and result in multiple calls to your ProcessPurchase on every app restart until the problem is resolved.
```
from https://forum.unity.com/threads/solved-processpurchase-event-get-called-multiple-times.506574.

Also, [The stackoverflow](https://stackoverflow.com/questions/20121981/skpaymenttransactionstatepurchased-called-multiple-times-by-error).

**Comment by Desintegrator** [comment]
@hyochan nope
> checked `getPendingPurchasesIOS()` and try finishing it
How to do this properly? Or better (easier for me i think) just cancel them?

**Comment by hyochan** [comment]
@Desintegrator Try that and check if the payment is fine to `finishTransaction`. Then finish it!

Also as I've mentioned in https://github.com/dooboolab/react-native-iap/issues/1172#issuecomment-789582501, this usually happens in sandbox mode. Did you face this in `production`?

**Comment by Desintegrator** [comment]
> @Desintegrator Try that and check if the payment is fine to `finishTransaction`. Then finish it!
> 
> Also as I've mentioned in [#1172 (comment)](https://github.com/dooboolab/react-native-iap/issues/1172#issuecomment-789582501), this usually happens in sandbox mode. Did you face this in `production`?

@hyochan for now I found in the docs and implemented clearTransactionIOS instead of finishing its. I'm just moving to this library and testing it, so faced in TestFlight and dev environment only. app is not published yet.

**Comment by Matteo-Peronnet** [comment]
I have the impression it happens when you call `getAvailablePurchases()` and the test account has a large number of purchases (I had at least 40). I just tried with a new account on the Sandbox, I can't reproduce the problem anymore. Maybe that's why it doesn't happen in production?

I reproduced the problem with the version with hooks and without

**Comment by laurpantelimon** [comment]
So I'm having a nasty problem, because on android, after a requestPurchase, the purchaseUpdatedListener is called 3 times with the same payload and I therefore make 3 circles of "give rewards in backend -> finish transaction". The first time it is all good but the second and third time they fail because the transaction is finished the first time. On IOS it's all good, only one time the purchaseUpdatedListener is called. Any ideas?

**Comment by deep-dot** [comment]
Possible Unhandled Promise Rejection (id: 0):
Error: Not initialized, Please call initConnection() found in purchaseUpdatedListener.

purchaseUpdateSubscription = IAP.purchaseUpdatedListener(async (purchase) => {
        const receipt = purchase.transactionReceipt;
        console.log('purchaseUpdatedListener', receipt);
        try {
        if (receipt) {
          validate(receipt);
          await IAP.finishTransaction(purchase, false);
         // await IAP.finishTransaction(purchase, true);
        }
      } catch (error) { }
      });

**Comment by jsallstrom** [comment]
This is happening in our app frequently, only in sandbox fortunately but its still annoying to deal with. Pls fix this as soon as you can <3

**Comment by roots-ai** [comment]
Any updates here?

**Comment by andresesfm** [comment]
Can somebody please confirm this is happening on 8.x.x? If so, can somebody please provide a way to reproduce using IapExaple?

**Comment by andresesfm** [comment]
I have found the following as something that is expected from the native SDK: https://stackoverflow.com/a/3633571/570612
If it still happens on 8.x.x and the above doesn't fix. We'll reopen. Thank you

Note: I'm not trying to minimize the issue. I see there are multiple posts about it in various forms and I'm trying to make sense of it but with no help and it being reported on such an old version of the library is close to impossible. Thank you for understanding

**Comment by jeremyhalin** [comment]
I just updated to `8.3.0` and still have the issue.
I updated my API so it can skip previously saved orders.
I don't see side effects on my side even if behavior is weird.

**Comment by BLOCKMATERIAL** [comment]
any workhound ?

**Comment by dprajapati1179** [comment]
Any solution I am facing the same issue of calling both purchaseUpdatedListener purchaseErrorListener multiple times (more than 15 times)

I am using the latest released version  "react-native-iap": "10.0.1"
@andresesfm respond me if there is any specific fixes for the same.

**Comment by andresesfm** [comment]
Can you please share what kind of events are you getting?

Could it be previous transaction that were not finished?

**Comment by dprajapati1179** [comment]
> Can you please share what kind of events are you getting?
> 
> Could it be previous transaction that were not finished?

Yes it gets called imiidatly for multiple times with the same purchase,

I want to call My API to store the recipt for the subscription and due to multiple call backend will be confused

Any solution to stop I am also finishing transaction after calling my API but before finishing it get called again and again.

**Comment by dprajapati1179** [comment]
@andresesfm  also note that the same is happening for purchaseErrorListener.

I am attaching the screenshot of the already having subscription error after pressing the ok button from the popup.

1. 
![image](https://user-images.githubusercontent.com/67822877/187840919-ea18eeb2-9c61-44b2-98a4-50da9f105184.png)

2. 
![image](https://user-images.githubusercontent.com/67822877/187841570-19c261ac-1185-4340-85f5-a7a1189d15fd.png)

**Comment by andresesfm** [comment]
Please try 10.0.3 that adds clean up on disconnect. Please open a new ticket if this is still an issue. Even if the symptoms are the same, the code has changed too much to trace back. Thank you for understanding

**Comment by dprajapati1179** [comment]
> Please try 10.0.3 that adds clean up on disconnect. Please open a new ticket if this is still an issue. Even if the symptoms are the same, the code has changed too much to trace back. Thank you for understanding

Okay, I will try with the 10.0.3 and update you here.
Thank you for the replay @andresesfm

**Comment by dprajapati1179** [comment]
Hello @andresesfm,

I used the latest version 10.0.5 but still, the listeners are called 3-4 times.
Am I making any mistake?

**Comment by dprajapati1179** [comment]
Hi @andresesfm 

I tried with the latest version but still the same is happening for purchaseErrorListener and purchaseUpdatedListener.
Now the listeners are called 3-4 times not more than that.

Anything else I can try?

**Comment by andresesfm** [comment]
@dprajapati1179 the listeners will get every purchase transaction

**Comment by ToniNikolaev23** [comment]
@andresesfm Hello i have some questions about transactions and updateListener.I start to use react-native-iap and for testing i used sandbox like everybody i think..when i make purchase for any product everything is good i get receipt, sending to my server to validate, if server send me status okey i finishTransaction (this method always return undefined). And sandbox make multiple payments every 3-5 minutes.I saw that we have 2 statuses of payments(Available and Pending) i console.log to see what happen everytime with them.When statuses are in Available -> updateListener work correctly, but sometimes a lot statuses come to Pending and crash my server.I find out one flow that make my purchases to Pending -> I pay 1 subscription for example, my server validate and i finish transaction..after 15 minutes i goes to paymentscreen and click again to this subscription i receive status that already own this product, click okey and after return again to this page i saw a lot purchases goes to Pending.So i try to understand how that work.Also why after finish any trasanction they again goes to AvailableProducts, and how to understand that i finishTransaction works correctly when return me undefined.And what if for example i finishTransaction only in one screen..and if i make first purchase and leave page, after 30 minutes i log again, sandbox will make auto 5-6 payments, should i make 1 loop before updateListener to finish all new upcomming Pending transactions?

**Comment by andresesfm** [comment]
@ToniNikolaev23 You might get many duplicate transactions on sandbox as you are making many purchases with the same account. This is not typical in production

**Comment by krushalikevadiya** [comment]
Same issue for me also.purchaseUpdatedListener calling when user enter into the screen as well.

**Comment by c-info** [comment]
const processNewPurchase = async (purchase) => {
  const { productId, transactionReceipt } = purchase;
  if (transactionReceipt !== undefined && transactionReceipt) {
       //backend call with fetch - validating receipt 
        if (data.ack === 'success') {
          console.log('finished');
          await finishTransaction(purchase);
      } else if (data.ack === 'failure') {
          props.setProcessing(false);
          console.log('error');
      }
    }
};

What if transactionReceipt is get empty  ?

**Comment by Haseeba393** [comment]
I'm using latest version 12.10.2 and still getting this problem, Please help me out in this

**Comment by nervouscat** [comment]
same here!

**Comment by saeedtkh** [comment]
the same problem? any updates?

**Comment by karuzo17** [comment]
I currently have the same issue on Android. I get at least two listeners, which is quite problematic. On iOS everything seems to be fine for me. I am using 

"react-native-iap": "^12.10.4"

Any ideas how to fix it?

**Comment by mohak54e** [comment]
> I currently have the same issue on Android. I get at least two listeners, which is quite problematic. On iOS everything seems to be fine for me. I am using
> 
> "react-native-iap": "^12.10.4"
> 
> Any ideas how to fix it?

Any fix for this issue?

**Comment by Haider-Ali-7** [comment]
I had the same issue. Purchase listener was running two times. I made the function which will do nothing when listener run more than once. You can set `executeOnce` value to `false` after calling the `finishTransaction` function. Leaving it here as many folks experiencing this issue. Hope it helps somebody.

```
let executeOnce = false;
let purchaseUpdateSubscription;
let purchaseErrorSubscription;

const IAPScreen = () => {
const getProductsIAP = useCallback(async () => {
If (ios) {
  await clearProductsIOS();
  await clearTransactionIOS();
  }
  
if(android){
  await flushFailedPurchasesCachedAsPendingAndroid();
}

 try {
   const result = await initConnection();
   const products = await getProducts(itemSkus);
   props.setProducts(products);
   console.log('result', result);
 } catch (err) {
   console.warn(err.code, err.message);
 }

  purchaseUpdateSubscription = purchaseUpdatedListener(
    async (purchase) => {
    
      var runOnce = (() => {
        return () => {
          if (!executeOnce) {
            executeOnce = true;
            
            console.log('[RUN ONCE] Function ran once!');
            const receipt = purchase.transactionReceipt;
            
            if (receipt) {
               // validation receipt api
             } 
             
          }
        };
      })();
      runOnce();
    },
  );

  purchaseErrorSubscription = purchaseErrorListener(
    (error: PurchaseError) => {
      console.log('purchaseErrorListener', error);
      console.log(JSON.stringify(error));
    },
  );

}, []);


useEffect(() => {
  getProductsIAP();

  return () => {
    if (purchaseUpdateSubscription) {
      purchaseUpdateSubscription.remove();
      purchaseUpdateSubscription = null;
    }
    if (purchaseErrorSubscription) {
      purchaseErrorSubscription.remove();
      purchaseErrorSubscription = null;
    }
  };
}, []);
}

export default IAPScreen;
```

**Comment by Saphirah** [comment]
Isn't this expected behavior? You are calling "await finishTransaction(purchase);" in the purchaseUpdatedListener.
This will update your subscription, calling another "purchaseUpdatedListener" to fire because your subscription got updated. 
This will happen in an infinite loop. Just had the same issue. Workaround is store the last processed transaction in a variable. Similar to the executeOnce of @Haider-Ali-7 

```js
//Global Scope
let lastTransactionRecipe = null;

purchaseUpdateSubscription = purchaseUpdatedListener(
            (purchase) => {
                if (purchase.transactionReceipt) {
                    if(lastTransactionRecipe === purchase.transactionReceipt) return;
                    //Do recipe validation check
                    lastTransactionRecipe = purchase.transactionReceipt;
                    finishTransaction({purchase, isConsumable: false});
                }
            }
        );
```

**Comment by daibing1976** [comment]
any new update? we have the same problem.

**Comment by GemsGame** [comment]
there is we have only crutch as solution in closed topic

**Comment by congduong97** [comment]
I found a solution for the workaround.  You can use  a flag to mark payment finished and using debounce like below.
<img width="410" alt="Screenshot 2023-12-25 at 11 25 25" src="https://github.com/dooboolab-community/react-native-iap/assets/39731881/8d5a7b2d-16ec-4b16-b5e4-8a05a4ff1f9f">
<img width="456" alt="Screenshot 2023-12-25 at 11 25 57" src="https://github.com/dooboolab-community/react-native-iap/assets/39731881/dc32b5c8-0195-4dd1-961d-7bc9662f3869">

**Comment by mrtawil** [comment]
+1

**Comment by nguoingulanh** [comment]
My version: "react-native-iap": "^12.13.0"
I follow this https://github.com/dooboolab-community/react-native-iap/blob/main/IapExample/src/screens/ClassSetup.tsx
Everything ok with me

**Comment by Karthik-V26** [comment]
Any Solution for this issue?

**Comment by JuGit-pk** [comment]
### What's the conclusion? I need a solution as I'm still encountering this issue on iOS. 
Please take a look at my implementation.

**1.  INIT IAP**

```
  const initializeIAP = async () => {
    try {
      const isConnected = await initConnection();
      if (Platform.OS === 'android') {
        await flushFailedPurchasesCachedAsPendingAndroid();
      } else if (Platform.OS === 'ios') {
        console.log('CLEARTING IOS clearTransactionIOS');
        await clearTransactionIOS();
      }
    } catch (error) {
      console.error('Error initializing IAP: ', error);
    }
  };
  useEffect(() => {
    initializeIAP();

    return () => {
      endConnection();
    };
```

**2. Method to Request Subscription**
```
  const handleBuySubscription = async () => {
    if (selectedPackage) {
      try {
        // ios
        let subsParams: RequestSubscription = {
          sku: selectedPackage.productId,
          andDangerouslyFinishTransactionAutomaticallyIOS: false,
        };
        if (Platform.OS === 'android' && currentSubscriptionOffer) {
          const sku = currentSubscription?.productId as string;
          const offerToken = currentSubscriptionOffer.offerToken;

          subsParams = {
            sku,
            ...(offerToken && {subscriptionOffers: [{sku, offerToken}]}),
          };
        }

        requestSubscription(subsParams);
      } catch (err: any) {
        console.warn(err.code, err.message);
      }
    }
  };
```

**3. Purchase Listener**


```
 useEffect(() => {
    // Initialize purchase listeners
    let purchaseUpdateSubscription = purchaseUpdatedListener(async purchase => {
      const receipt = purchase.transactionReceipt;
      if (receipt) {
        try {
          const payload = {
            receipt,
            os_type: Platform.OS,
          };
          debouncedAcknowledgementReceiptAPI(payload, {
            onSuccess: async () => {
              qc.invalidateQueries({queryKey: ['billing-details']});
              if (isBillingModalVisible) {
                setIsBillingModalVisible(false);
              }
              setIsModalVisible(true);
              await finishTransaction({purchase, isConsumable: false});
              await getPurchaseHistory();
            },
          });
        } catch (error) {
          console.error('Error during purchase handling:', error);
        }
      }
    });

    let purchaseErrorSubscription = purchaseErrorListener(error => {
      console.error('Purchase error:', error);
    });

    // Cleanup listeners on unmount
    return () => {
      lastTransactionRecipe.current = null;
      purchaseUpdateSubscription.remove();
      purchaseUpdateSubscription = null as any;
      purchaseErrorSubscription.remove();
      purchaseErrorSubscription = null as any;
    };
  }, [
    debouncedAcknowledgementReceiptAPI,
    getPurchaseHistory,
    qc,
    isBillingModalVisible,
    setIsBillingModalVisible,
    profileData?.email,
  ]);
```

**Comment by ashuvssut** [comment]
### Maybe use `debounce` to fix it?

I think we should use a `debounce` function (from lodash or es-toolkit). This will prevent multiple subsequent calls — only the last one within the given delay (in milliseconds) will actually run.

if you use `@mantine/hooks` then you can use `useDebouncedCallback`
