### ISSUE TITLE
RNIapModule.buyItemByType got 7 arguments, expected 9

### ISSUE THREAD

**Issue by teddelicious** [dooboolab/react-native-iap#1175]
### Version of react-native-iap
5.0.1
### Version of react-native
4.13.0
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Able to subscribe to an auto-renewal subscription by SKU on click (working as of version 4.6.3)
### Actual behavior
Error as shown on click (stopped after upgrading to 5.0.1)
![image](https://user-images.githubusercontent.com/9597150/97938406-53c56780-1d4f-11eb-9789-fdbe6964f244.png)
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
Clicking the subscription button to initiate the subscription process

**Comment by heyoppa-admin** [comment]
It worked fine and then this error appear again. I have the latest version... is this module really stable ? I wonder

**Comment by alpha0010** [comment]
For me, `npx react-native start --reset-cache` fixed the problem.
