### ISSUE TITLE
requestSubscription causes COMING SOON screen

### ISSUE THREAD

**Issue by LazUIC** [dooboolab/react-native-iap#1177]
### Version of react-native-iap
4.6.3

### Version of react-native
tvos-0.63.1

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Make a successful purchase

### Actual behavior
The purchase throws E_UNKNOWN error randomly then the AppleTV shows the COMING SOON screen.

### Tested environment (Emulator? Real Device?)
Real Device - TVOS 14.0.2

### Steps to reproduce the behavior
After the requestSubscription call, the user can set a password on the iTunes Sign-in screen.
Right after the user push the DONE button the purchase will be failed and AppleTV shows the COMING SOON screen.

**XCode debug shows the following errors:**

 <SKPaymentQueue: 0x283995360>: Payment completed with error: Error Domain=ASDServerErrorDomain Code=2034 "Sign In to the iTunes Store" UserInfo={NSLocalizedDescription=Sign In to the iTunes Store}

Purchase Failed  !!

**The purchaseErrorListener gives back the following error:**

{ 
  responseCode: '0',
  code: 'E_UNKNOWN',
  debugMessage: 'An unknown error occurred',
  message: 'An unknown error occurred',
  productId: 'iapname'
}

**Comment by TomWrd** [comment]
I am experiencing the same issue on my iOS device while testing with latest version of react-native-iap

**Comment by Desintegrator** [comment]
same issue

**Comment by hyochan** [comment]
I've not had yet developed tvOS. Can someone share how to debug this in tvOS briefly?
