### ISSUE TITLE
Unable to change subscription plan 

### ISSUE THREAD

**Issue by rishabh1608** [dooboolab/react-native-iap#1181]
### Version of react-native-iap
4.6.1

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
If user have an active subscription and tries to change subscription(eg: 1 month -> 6 month subscription),then subscription must get upgraded from the next billing cycle for user and get reflected in play store.

### Actual behavior
If user have an active subscription and tries to change subscription(eg: 1 month -> 6 month subscription),then 2 subscriptions get created in the playstore instead of getting upgraded.

### Tested environment (Emulator? Real Device?)
Real Device (Closed Testing)

### Steps to reproduce the behavior
1. Buy a subscription.
2. Open manange subscription in app and change the plan.
3. Open playstore to verify, two subscriptions will be present there.

await RNIap.requestSubscription(newSku, false, oldSku);

**oldSku** is not being used to upgrade subscription.

**Comment by prathasaxena** [comment]
#1128

**Comment by rishabh1608** [comment]
> #1128 Please refer to this issue

Thanks
