### ISSUE TITLE
Duplicate items get displayed to the user on IOS emulator.

### ISSUE THREAD

**Issue by Decoder3-14** [dooboolab/react-native-iap#1185]
### Version of react-native-iap
4.6.1
### Version of react-native
0.63.0
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Showing products/subscriptions identical and equal to the product ids that were passed to the getProducts/getSubscriptions functions.
### Actual behavior
Showing duplicate items after fetch. For instance, one product id resulted in two pricing plans displayed to the user.
### Tested environment (Emulator? Real Device?)
Emulator

**Comment by rwichmann** [comment]
Might be related to https://github.com/dooboolab/react-native-iap/issues/1167
