### ISSUE TITLE
android getSubscriptions given empty array for my ids but work with this "android.test.purchased'" test id 

### ISSUE THREAD

**Issue by Hamashassan** [dooboolab/react-native-iap#1189]
### Version of react-native-iap
4.3.0
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
should give an array of my subscription that I added on my google console.
### Actual behavior
gives an empty array
### Tested environment (Emulator? Real Device?)
"android.test.purchased" working both on the emulator and real device but my ids are not working empty array always
### Steps to reproduce the behavior

<img width="912" alt="Screen Shot 2020-11-21 at 2 54 03 AM" src="https://user-images.githubusercontent.com/25038442/99853730-5a543b80-2ba5-11eb-9d97-d48b8c794fbb.png">

Please help me out with this it's working fine for iOS. Even I put my app on alpha and testing reviews are also done.

Q2. One more question I need to know is it mandatory to verify the receipts from the backend what if I leave this step?

**Comment by ronal2s** [comment]
Same issue, any updated?

**Comment by Hamashassan** [comment]
No luck till now don't know why this issue is happening

**Comment by ronal2s** [comment]
I'm on the same situation, iOS is working fine and ready to submit but android is not. I think I followed all the steps but getSubscriptions is always retuning empty

**Comment by Hamashassan** [comment]
Did you send your android app to review the alpha test? I was thinking to publish the app first in production then I'll try again maybe it requires the app to be in production. However can you please let me know is it mandatory to verify the receipt from the backend? What if I don't want to?

**Comment by ronal2s** [comment]
Yes, my app is already in alpha track since yesterday, also I go into the URL for tester, got registered in and when I tap download app is not working. 

Verify Receipt is not mandatory but is recommended, it's not difficult to do, I did it on Nodejs for iOS purchases. Playstore verify still missing due this weird problem

**Comment by Hamashassan** [comment]
Okay great, basically I don't have a Node server I am using firebase for my database. maybe I will implement with the firebase cloud function, can you please share the example of receipt verification?

Annndddd someone please help us with the android subscription :3

**Comment by ronal2s** [comment]
I'm using Firebase too, this is my Nodejs code verification receipt, is running on Heroku
```
app.post("/verifyReceipt", (req, res) => {
  const { receiptData } = req.body;
  console.log(process.env.APPLE_PASSWORD)
  axios.post(verifyURL, {
    'password': process.env.APPLE_PASSWORD,
    'receipt-data': receiptData,
    "exclude-old-transactions": true
  })
    .then(result => {
      if (result.data.receipt) {

        const length = result.data.receipt.in_app.length;
        let subscriptionActive = false;
        let subscription = { active: false };
        for (let i = 0; i < length; i++) {
          const element = result.data.receipt.in_app[i];
          if (moment(parseInt(element.expires_date_ms)).isAfter()) {
            subscriptionActive = true;
            subscription = {
              active: subscriptionActive,
              product_id: element.product_id,
              purchase_date: element.purchase_date_pst,
              expires_date: element.expires_date_pst
            }
            break;
          }
        }
        subscription = { ...subscription, pending_renewal_info: result.data.pending_renewal_info }
        console.log(subscription)
        res.send(subscription)
      } else {
        console.log("Data don't corresponding: ", receiptData)
        res.send({ active: false });
      }

    })
    .catch(error => console.log(error));
})
```

**Comment by Hamashassan** [comment]
Thank you so much, Ronal! Please let me know if you find any workaround for android. Good Luck (Y)

**Comment by Hamashassan** [comment]
Hey, I get my subscription in an array finally it's not empty. Ok so to get the subscription/products you must have to release your app on Open Testing / Closed Testing / Internal Testing. once you are able to see your app on the play store as a beta. Then you are able to get the subscription or products in the array. Hope this works for you to Cheers!

**Comment by ronal2s** [comment]
@Hamashassan how may days did you wait? I published on closed testing few days ago and the URL beta download button keep loading after click download 
![Screenshot_20201124-002636_Chrome](https://user-images.githubusercontent.com/20154989/100048680-c6c07c00-2deb-11eb-9d8e-0f34676ee731.jpg)
![Screenshot_20201124-002732_Google Play Store](https://user-images.githubusercontent.com/20154989/100048716-dc35a600-2deb-11eb-9882-68118fbdc979.jpg)

**Comment by Hamashassan** [comment]
Yes, the same thing was happening for me at first because the app is not being published at playstore as a beta. That's why when we open the URL it didn't find it on the play store. Make sure in your google play console dashboard there is a button "View on play store" when you click it you should see your app on play store as internal beta testing. also, I release the app in production too!
