### ISSUE TITLE
How can I use Apple's Promotional Offers with the library?

### ISSUE THREAD

**Issue by makarsky** [dooboolab/react-native-iap#1197]
Here is the feature:
https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_promotional_offers_in_your_app

Which RNIap method to use?

**Comment by makarsky** [comment]
Found the requestPurchaseWithOfferIOS method. It would be great if it was mentioned in the README.

**Comment by EdDevs2503** [comment]
How you used it? i don't know which params need the method **requestPurchaseWithOfferIOS**

**Comment by makarsky** [comment]
@EdDevs2503 Here's the list of params
https://github.com/dooboolab/react-native-iap/blob/master/index.ts#L776

Here's the official doc
https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_promotional_offers_in_your_app
