### ISSUE TITLE
requestPurchase on iOS is taking some time to load

### ISSUE THREAD

**Issue by RocKhalil** [dooboolab/react-native-iap#1198]
### Version of react-native-iap
5.1.1

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Calling `RNIap.requestPurchase(sku)` should open directly

### Actual behavior
Calling `RNIap.requestPurchase(sku)` is taking between 20 and 30 seconds to show Apple's payment modal when downloading the app from TestFlight / release. However, when testing it on Emulator / debug, it's opening directly.

### Tested environment (Emulator? Real Device?)
Both

### Steps to reproduce the behavior
No specific steps

**Comment by gkhngyk** [comment]
Same issue 👍

**Comment by sami3898** [comment]
@RocKhalil 
the payment popup not open on my simulator
will you please help me?

**Comment by acostalima** [comment]
See https://github.com/dooboolab/react-native-iap/issues/1120 as it might be related to this.

**Comment by scchess** [comment]
Same here.

**Comment by scchess** [comment]
@sami3898 You need a real device.

**Comment by hyochan** [comment]
Looks related to #1244 which is expected.

**Comment by RocKhalil** [comment]
@hyochan how is this expected ? it's loading directly when in debug mode but takes 30 seconds to open in production ?
