### ISSUE TITLE
Apple IAP flow?

### ISSUE THREAD

**Issue by dancixx** [dooboolab/react-native-iap#1200]
Hi guys!

I need some help witi IAP. My state is now, i created a sandbox tester, can test the iap, but apple always drop the review back, cause if they can test the iap is nothing happening, because the subscription products not loaded till they approve the first review.
So if u have any experience what the f.ck apple want at iap pls share me or help me.

- Mechant ID - done
- IAP (renewable subs) creation - done
- Banking tasks - done
- Sandbox user - done
- Test purchase with sandbox user - done
- Subs. cancellation with sandbox user - done

what should be the next steps?
Thx for helping me.

**Comment by lfoliveir4** [comment]
> Hi guys!
> 
> I need some help witi IAP. My state is now, i created a sandbox tester, can test the iap, but apple always drop the review back, cause if they can test the iap is nothing happening, because the subscription products not loaded till they approve the first review.
> So if u have any experience what the f.ck apple want at iap pls share me or help me.
> 
> * Mechant ID - done
> * IAP (renewable subs) creation - done
> * Banking tasks - done
> * Sandbox user - done
> * Test purchase with sandbox user - done
> * Subs. cancellation with sandbox user - done
> 
> what should be the next steps?
> Thx for helping me.

can you help me how you set up the sandbox?

**Comment by dancixx** [comment]
Hi,

go to appstoreconnect, users&permissions, there you will be find a menu with title Test Users. Here you can add an user, but you should give email without icloud accout i think.
Then you can generate a test purchase, what you should to write to the support after if they drop your app back, then you can continoue the release process. :)

**Comment by lfoliveir4** [comment]
> Hi,
> 
> go to appstoreconnect, users&permissions, there you will be find a menu with title Test Users. Here you can add an user, but you should give email without icloud accout i think.
> Then you can generate a test purchase, what you should to write to the support after if they drop your app back, then you can continoue the release process. :)

I just didn't understand this part:
"Then you can generate a test purchase, what you should write to the support after if they drop your app back, then you can continue the release process. :)" "

Could you describe me better? My user in the sandbox is already created and I have the storekit configured in my environment, but the store kit is not working in the testflight. Would it have a different configuration?

**Comment by dancixx** [comment]
You cant generate test-purchase in simulator. You should test, hogy in app purchase on real device. I got always iap error at review from apple, that they cant find and use iap feature in my app. The solution for was that create the sandbox user, then with this user generate a purchase in testflight mode on real device. I wrote for support if did this and that was enough, they approved my app.

I hope this help you.

**Comment by lfoliveir4** [comment]
> You cant generate test-purchase in simulator. You should test, hogy in app purchase on real device. I got always iap error at review from apple, that they cant find and use iap feature in my app. The solution for was that create the sandbox user, then with this user generate a purchase in testflight mode on real device. I wrote for support if did this and that was enough, they approved my app.
> 
> I hope this help you.

So did you go over the review and mention the sandbox user? I have my user created in the sandbox and I have the same problem that you had and for weeks ... Can I have any contact with you? Can you help me?

**Comment by dancixx** [comment]
Were you able to solve the problem?

**Comment by lfoliveir4** [comment]
> Were you able to solve the problem?

No, I submitted my application for review again and did what you mentioned: Notify the Apple staff of the user who is registered in the sandbox. I am waiting for the response from apple. After I sent my applications for review, the status of the products went from "awaiting review" to "under review".

**Comment by lfoliveir4** [comment]
> Were you able to solve the problem?

UPDATE !!!


I solved my problem by doing what you did: Resending the application with updated prices with details and identified the Apple sandbox user.

Finally, with all this correct data they approved the prices and the application together.

**Comment by dancixx** [comment]
Haha. Congrat. :) If i can advice you, should you react-native-iaphub, cause the validation with own backend is really shit. React-native-iaphub use react-native-iap as dependency.
