### ISSUE TITLE
How to detect subscription renewal?

### ISSUE THREAD

**Issue by henrik-d** [dooboolab/react-native-iap#1202]
Is `purchaseUpdatedListener` called again, when a subscription is renewed? If not, what is the best way to detect this event, when not using server notifications?

**Comment by lahivee** [comment]
@henrik-d did you figure this out already? I am asking myself the same question

**Comment by henrik-d** [comment]
My observation was that `purchaseUpdatedListener` as called on the next app-start after a renewal, **but only on iOS**! So that was not a solution for us. Instead we check the status of the subscription on every app start manually, by validating the receipt again with our server. That way we get the latest information about expiryDate etc.

Hope this helps!

**Comment by lahivee** [comment]
@henrik-d That definitely helps! Thank you!

**Comment by lahivee** [comment]
I have done some more research and it seems that the official way to achieve this is to use server-notifications: https://developer.apple.com/documentation/appstoreservernotifications

have you had experiences with this? @henrik-d

**Comment by henrik-d** [comment]
Using server notifications is definitely the more robust way to implement this. We decided against it, because it seems very complicated, especially when you need support for iOS and Android. It might be worth to check out https://www.iaphub.com/ or https://www.revenuecat.com/ which take the heavy lifting for you.

**Comment by lahivee** [comment]
Thanks for confirming!

**Comment by lahivee** [comment]
If anyone is using Laravel, this seems to be the best package that handles all of the server notifications and receipt validation stuff: https://github.com/imdhemy/laravel-in-app-purchases

**Comment by henrik-d** [comment]
@kayamy Yes, here is the basic function:
```
private async checkForSubscriptionUpdates() {
    // check if user was subscribed (information is stored in redux store)
    if (!this.isUserSubscribed()) return;

    if (Platform.OS === 'ios') {
      const receipt = await IAP.getReceiptIOS();
      await this.processReceipt(receipt);
    }
    if (Platform.OS === 'android') {
      const subscriptionPurchase = await this.getMostRecentSubscriptionPurchase(); // uses IAP.getAvailablePurchases()
      if (subscriptionPurchase) {
        await this.processReceipt(subscriptionPurchase.transactionReceipt);
      } else {
        await this.store.dispatch(user.actions.revokeProSubscription());
      }
    }
  }
```
`processReceipt()` sends the receipt to the server to check if the subscription is still active.

**Comment by kayamy** [comment]
@henrik-d thanks! I'm guessing you keep track of the subscription status serverside?

**Comment by henrik-d** [comment]
@kayamy As stated early, keeping track on the server using server notifications is the more robust solutions, but also way more complicated to implement. We only check the subscription status on the client side.

**Comment by hyochan** [comment]
You need to validate `receipt` in order to do this progress which is recommended to handle in the server-side.

**Comment by kayamy** [comment]
@henrik-d do you know if it's possible to rely on the initial receipt that you get when calling `requestSubscription` ?

in your approach you're not relying at all on the `purchaseUpdatedListener` for renewals right?
i found that the second, 3rd etc. time that `purchaseUpdatedListener` gets called it returns a different receipt (on iOS)

i'm wondering if i can just stop using `purchaseUpdatedListener` after the initial purchase and use an api call to my server to keep the subscription active.

and as a side-note, have you tested re-enabling the subscription outside of the app? (under the appstore settings)
if you're not using `purchaseUpdatedListener` the app will never know that the user re-enabled the subscription via the settings. 

thanks so much for your help so far @henrik-d @hyochan  :)

**Comment by henrik-d** [comment]
@kayamy 
> do you know if it's possible to rely on the initial receipt that you get when calling requestSubscription ?

As far as I know you can use the original receipt on iOS, not sure about Android. Nevertheless we always use the latest receipt.

> in your approach you're not relying at all on the purchaseUpdatedListener for renewals right?
i found that the second, 3rd etc. time that purchaseUpdatedListener gets called it returns a different receipt (on iOS)

Yes, we do not rely on `purchaseUpdatedListener` for renewals, but calling `IAP.getReceiptIOS()` will give the latest receipt. 

> and as a side-note, have you tested re-enabling the subscription outside of the app? (under the appstore settings)
if you're not using purchaseUpdatedListener the app will never know that the user re-enabled the subscription via the settings.

We don't use `purchaseUpdatedListener` for renewals, but for subscriptions made outside the app. So you should register the callback on every app start anyway.

**Comment by nes123** [comment]
The original receipt should work, at least in my experience. Did anyone experience something else?

**Comment by nes123** [comment]
Now i wonder if there is a risk in updating the receipt. Or is it going to be validated the same as the original token..didn't find any documentation on what is the healthiest approach.

**Comment by lunatolun** [comment]
I was also wondering if the transactionDate is updated on each renewal, or if its stored the same regardless of the renewal cycle. If the package gives new transaction date on each successful renewal, then it's pretty simple... Save in the server and handle by date, however the documentation doesn't state a lot of things.
Any info?

**Comment by yenpn** [comment]
@henrik-d Hi you, I am also planning to use IAPHUB as you suggested. Can you tell me more when renew subscription is activated, how can IAPHUB call the API on my server to update a specific field, specifically isPremium true? in my database?

**Comment by darimuhittinhey** [comment]
@henrik-d 

> const subscriptionPurchase = await this.getMostRecentSubscriptionPurchase(); // uses IAP.getAvailablePurchases()

does `getMostRecentSubscriptionPurchase` function gets the 0th element from IAP.getAvailablePurchases() ?

**Comment by darimuhittinhey** [comment]
> I was also wondering if the transactionDate is updated on each renewal, or if its stored the same regardless of the renewal cycle. If the package gives new transaction date on each successful renewal, then it's pretty simple... Save in the server and handle by date, however the documentation doesn't state a lot of things. Any info?

No, i tried and nothing updates after renewal happens.

**Comment by umerdogar** [comment]
We might need to implement web hooks , we. did but still the hook which is responsible for tracking renewal doesn’t get triggered when a renewal happens. Any one else who tried?
