### ISSUE TITLE
getProducts() returns only Product fields: price, currency, productId

### ISSUE THREAD

**Issue by OlegPanfyorov** [dooboolab/react-native-iap#1203]
### Version of react-native-iap
5.2.0

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
When I call getProducts() or getSubscriptions() it should return me a Product objects array with all fields described in docs similar to this

`{ 
    productId: 'com.XXX.sdk38.annual',
    subscriptionPeriodUnitIOS: 'YEAR',
    description: 'Activate Premium features on XXX',
    introductoryPrice: '',
    title: 'Annual',
    introductoryPriceSubscriptionPeriodIOS: '',
    introductoryPriceNumberOfPeriodsIOS: '',
    discounts: 
     [ { localizedPrice: '€0,00',
         numberOfPeriods: '1',
         type: 'SUBSCRIPTION',
         identifier: 'com.XXX.sdk38.tryannual',
         paymentMode: 'FREETRIAL',
         price: '0',
         subscriptionPeriod: 'MONTH' } ],
    type: 'Do not use this. It returned sub only before',
    localizedPrice: '€54,99',
    introductoryPricePaymentModeIOS: '',
    price: '54.99',
    currency: 'EUR',
    subscriptionPeriodNumberIOS: '1'
 }`

### Actual behavior
When I call getProducts() or getSubscriptions() it returns me a product with only 3 fields (see attached screenshot):
- price
- currency
- productId
` {price: "19.99", currency: "USD", productId: "hiii.premium1a"}`

### Tested environment (Emulator? Real Device?)
Real device. Production scheme with build configuration Debug and Debug executable set to true. But generally, we've noticed the same behavior on prod.

**Comment by NSNJRGL** [comment]
Hi @OlegPanfyorov, can you get items on android using getProducts()? If yes, how you solve it? Thanks :)

**Comment by TimPetricola** [comment]
I've had the same problem when upgrading from 5.1.1 to 5.1.3. It doesn't affect every device/account, but we saw it happening in production for ~800 users. I could not find a specific pattern, but reverting to 5.1.1 fixed it.

**Comment by calluna18** [comment]
We have also noticed this issue for random users after 5.1.2. I noticed that it seems like it is the properties after the newly added `countryCode` that gets left out so probably an issue related to this.
https://github.com/dooboolab/react-native-iap/pull/1186/files#

Probably good to revert or fix as soon as possible since it is hard to notice this issue when it only affects random apple users.

Thanks for a good lib otherwise!

**Comment by leethree** [comment]
Seeing the same issue on a lot of users. Probably related to #1186

**Comment by scchess** [comment]
Same issue.

**Comment by scchess** [comment]
Any update? We need to fix it.

**Comment by johnfrancisgit** [comment]
+1 any update on this?

**Comment by johnfrancisgit** [comment]
Having to downgrade to 5.1.1 until resolved

**Comment by loiclouvet** [comment]
I'm just having this issue on v5.2.3. Everything was working on multiple devices.
We submitted yesterday, a new app with in-app products but today, on the same devices, we are not retrieving all the fields.
Reverting to 5.1.1 did the trick, thank you @TimPetricola 🙏

**Comment by ninjaboy** [comment]
Started seeing this for random users too, this is such a shame

**Comment by ninjaboy** [comment]
@hyochan, Hyo, can we have this landed? how can we get a new release cut?

**Comment by hyochan** [comment]
Have you people tried creating own StoreKit?
https://stackoverflow.com/questions/58020258/requesting-an-in-app-purchase-in-ios-13-fails/58065711#58065711

**Comment by hyochan** [comment]
#1246 has been released to `5.2.6`. Let's see how it goes.
