### ISSUE TITLE
No visible @interface for 'SKPaymentQueue' declares the selector 'presentCodeRedemptionSheet'

### ISSUE THREAD

**Issue by junedomingo** [dooboolab/react-native-iap#1204]
### Version of react-native-iap
5.2.0
### Version of react-native
0.62.2
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Able to run/build the app using Xcode or terminal
### Actual behavior
Build failed due to this error
```No visible @interface for 'SKPaymentQueue' declares the selector 'presentCodeRedemptionSheet'```
ios/RNIapIos.m at line 330
### Tested environment (Emulator? Real Device?)
Simulator
Xcode version 11.6 
### Steps to reproduce the behavior
- yarn add react-native-iap
- npx pod-install
- xed ./ios 
- run the app

**Comment by leotm** [comment]
Same, RN 0.61.5, XCode 11.5, tried XCode Clean too

**Comment by leotm** [comment]
Downgrading to `"react-native-iap": "5.1.3"` builds, sticking with it for now

<img width="1680" alt="Screenshot 2020-12-09 at 16 16 14" src="https://user-images.githubusercontent.com/1881059/101656087-382e3a80-3a3a-11eb-9c76-0d806dda64dc.png">

Possibly related to my old XCode 11.5 version, not yet on 12.1

**Comment by junedomingo** [comment]
Thanks @leotm , it worked.
error is related to this pr https://github.com/dooboolab/react-native-iap/pull/1201

**Comment by chgsilva** [comment]
same error here

**Comment by iaphub** [comment]
Xcode >= 12 required, otherwise use react-native-iap `5.1.3` 👍
