### ISSUE TITLE
getProducts give me a strange object

### ISSUE THREAD

**Issue by Piero87** [dooboolab/react-native-iap#1206]
Hello,
I'm trying to use react-native-iap, I add in app store connect one item, then my code is:

```
const itemSkus = Platform.select({
  ios: [
    'betatest1month'
  ],
  android: [
    'betatest1month'
  ]
});

    RNIap.initConnection().then(() => {
      try {
        const products = RNIap.getProducts(itemSkus);
        console.log(products);
      } catch (err) {
        console.log(err);
      }
    });
```

I get this:

`{"_U": 0, "_V": 3, "_W": {"_U": 0, "_V": 0, "_W": null, "_X": null}, "_X": null}`

What is?

### Version of react-native-iap
5.2.0
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
iPhone 11 iOS 14.2 
### Tested environment (Emulator? Real Device?)
Real Device and Emulator

**Comment by kalmahik** [comment]
RNIap.getProducts returns Promise, and you should resolve promise like that:
`            RNIap.initConnection().then(() => {
                try {
                    RNIap.getProducts(itemSkus).then((products) => {
                        console.log(products);
                    });
                } catch (err) {
                    console.log(err);
                }
            });
            `

**Comment by Piero87** [comment]
@kalmahik shame on me :D thank you very much.
Now I get an `UNKNOWN_ERROR` on iOS 14, and on iOS 13 I get an **empty** array though I have add a product in the App Store Connect.
I see there is already a ticket open: https://github.com/dooboolab/react-native-iap/issues/1118 and they talk about use a Store kit configuration file, my question now is this Store kit configuration file is only for testing or I need it also on production?

**Comment by kalmahik** [comment]
@Piero87 yes, I had the same issue, Store kit configuration file only for testing

**Comment by kalmahik** [comment]
@Piero87 new info. Don't use the Store kit file, cause you can't validate it. Be sure that your tax section on app store connect is correctly configured

**Comment by Piero87** [comment]
@kalmahik Because then I can use the products added on the app store connect without using the store kit for testing?

**Comment by kalmahik** [comment]
@Piero87 sorry, don't understand you. Store kit file need when you'd like to test purchases without AppStore at all (it works even in the simulator). And it doesn't work in production. And I don't recommend using the store kit file. 

If you want to test purchases correctly, you need to access them from the app store connect.
My problem was I didn't finish taxes, and I get an empty array and UNKNOWN_ERROR. After fixing that everything is ok

**Comment by iaphub** [comment]
It could be because Itunes isn't configured correcty like @kalmahik is saying or because you're using a simulator, I recommend using a real device.
Also like @kalmahik, the issue of using the StoreKit file is that you won't be able to validate the receipts on your server.

**Comment by Piero87** [comment]
@kalmahik @iaphub Ok now it's all clear thank you, so if I use a real device and I install the app via Xcode I can get the products configured in app store connect without using the Storekit file? (I have tried but I get an empty array)

**Comment by kalmahik** [comment]
@Piero87 you're welcome)
yes, you are right. But pay attention to the tax and finance category
