### ISSUE TITLE
Purchase multiple products

### ISSUE THREAD

**Issue by patrickbattisti** [dooboolab/react-native-iap#1208]
Hi,

I want know if it is possible make multiple purchase and subscription in the same request purchase.

e.g: I have a P1 product priced at $300, a P2 product priced at $120 and a subscription priced at $10/month. Can I process the both product and a subscription in same requestPurchase or requestSubscription?

Thank's for your time.

**Comment by iaphub** [comment]
Hi @patrickbattisti, unfortunately it isn't possible.
