### ISSUE TITLE
General Question: How to handle purchases between different platform stores?

### ISSUE THREAD

**Issue by appjitsu** [dooboolab/react-native-iap#1209]
Let's say that you have a user who creates an account on the web. They download the iphone app and purchase a subscription. They then lose their iphone and buy android. How to sync their ios iap between ios, android and the web. Does that make sense?

I was thinking about a central database and some endpoints to track the purchases across the platforms. Any suggestions?

**Comment by iaphub** [comment]
You need to validate receipts on your server to keep track of the subscription status, [react-native-iaphub](https://github.com/iaphub/react-native-iaphub) does that for you 👍
