### ISSUE TITLE
Implement canMakePayments for iOS

### ISSUE THREAD

**Issue by vshab** [dooboolab/react-native-iap#121]
Hello.

According to Apple guidline https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/ShowUI.html
>Display a store only if the user can make payments. To determine whether the user can make payments, call the canMakePayments class method of the SKPaymentQueue class. If the user can’t make payments (for example, because of parental restrictions), either display UI indicating that that the store isn’t available or omit the store portion of your UI entirely.

It would be really nice to have `canMakePayments`(https://developer.apple.com/documentation/storekit/skpaymentqueue/1506139-canmakepayments?language=objc) exposed to JS.

Thanks.

**Comment by JJMoon** [comment]
OK. We will implement the function soon.

**Comment by dooboolab** [comment]
@vshab This is released in `react-native-iap@1.2.4`. Sorry for late update. JJMoon hasn't been working on this one! Please reopen when there is an issue.
