### ISSUE TITLE
The operation couldn’t be completed. (SKErrorDomain error 2.)

### ISSUE THREAD

**Issue by AdamGerthel** [dooboolab/react-native-iap#1210]
### Version of react-native-iap
4.6.3

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Purchase succeeds

### Actual behavior
Error occurs, see https://sentry.io/share/issue/d8d09e708b064ae5a9639ab5bbb13cbc/

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
I've only come across this in production logs (i.e. real users are affected), and I haven't been able to reproduce it. It started appearing in logs after I upgraded from 4.5.3 to 4.6.3.

**Comment by chrisozgo99** [comment]
Facing same issue

**Comment by AdamGerthel** [comment]
Question: Are we supposed to run `finishTransaction` on failures as well? I'm currently only using it in `purchaseUpdatedListener` and not in `purchaseErrorListener`, but [this](https://developer.apple.com/forums/thread/51621) thread seems to indicate that I should (although that's not RN-iap specific).

**Comment by hyochan** [comment]
> Question: Are we supposed to run `finishTransaction` on failures as well? I'm currently only using it in `purchaseUpdatedListener` and not in `purchaseErrorListener`, but [this](https://developer.apple.com/forums/thread/51621) thread seems to indicate that I should (although that's not RN-iap specific).

[The link] best answers your question. Shortly, Your app needs to finish every transaction, regardless of whether the transaction succeeded or failed.

**Comment by AdamGerthel** [comment]
@hyochan so the [example app](https://github.com/hyochan/DoobooIAP/blob/master/src/components/screen/Main.tsx) is doing it wrong as well? My own app implements RN-iap in the same way as the sample.

**Comment by hyochan** [comment]
@AdamGerthel I don't think this is a problem with the `example` code. When does that error message appear? During the purchase?
