### ISSUE TITLE
{Question} - Preparing for Strong Customer Authentication transactions in the EU.

### ISSUE THREAD

**Issue by the-dut** [dooboolab/react-native-iap#1211]
I just got an email from apple about the above subject talking about some new EU requirements around in app purchasing.  Does this impact the code or the react-native-iap library at all?  Or is it not something we need to worry about?   Here is the article:
https://developer.apple.com/support/psd2/

**Comment by iaphub** [comment]
The react-native-iap library is fine but you have to be sure you're handling interrupted/deferred/pending purchases correctly.

We just posted an article about it 🙂 
https://www.reddit.com/r/reactnative/comments/kk76n6/are_your_inapp_puchases_ready_for_sca_strong/
