### ISSUE TITLE
getPurchaseHistory triggers Sign in with Apple ID prompt

### ISSUE THREAD

**Issue by calluna18** [dooboolab/react-native-iap#1212]
### Version of react-native-iap
5.1.1

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Being able to call getPurchaseHistory without prompting user for credentials

### Actual behavior
Both in local development and in TestFlight, the user is prompted for credentials when I call getPurchaseHistory

### Tested environment (Emulator? Real Device?)
Device (XCode & Testflight), have not tested production.

### Steps to reproduce the behavior
Call getPurchaseHistory

## Question
With a brief look at the code, I see that both `getPurchaseHistory` and `getAvailablePurchases` seem to use the same implementation with `getAvailableItems` that in turn uses `restoreCompletedTransactions`. Apple says [here](https://developer.apple.com/documentation/storekit/in-app_purchase/restoring_purchased_products) that restoring purchases will trigger a sign in prompt so you should avoid doing it without preparing the user for it.

In the docs this is clarified for `getAvailablePurchases` but not for `getPurchaseHistory`. If it is correct that it is the exact same implementation on iOS, this should probably be clarified in the Readme.

I also wonder if there is any way to get the receipt on iOS without triggering a credentials prompt?

Thanks for a good library!

**Comment by ShivamJoker** [comment]
I'm also having the same issue I would like to know if iOS has some ways to know what products user has without triggering the sign in.

In Android it doesn't ask but in iOS it does.

**Comment by hyochan** [comment]
I believe this is expected. This won't happen in the actual app (not test flight).
