### ISSUE TITLE
requestSubscription always return error Invalid product Id?

### ISSUE THREAD

**Issue by abdulwahabcs** [dooboolab/react-native-iap#1213]
### Version of react-native-iap
5.1.1
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
it should be subscribed to the particular subscription.
### Actual behavior
I can see my device be able to pull all subscriptions from apple store connect but  when i trigger request Subscription by using the particular product id it always return error E_Developer_Error Invalid product id. Working fine on Android. 
### Tested environment (Emulator? Real Device?)
Both

I also tried with apple test user still same behavior my subscriptions  are in state Ready to Submit.

**Comment by bilawal-liaqat** [comment]
@hyochan @JJMoon @lwansbrough 

I'm facing same issue

**Comment by Ahsanwarsi** [comment]
Stacked into this issue for a couple of days, quick help would be really appreciated.
@hyochan @JJMoon @lwansbrough @jvandenaardweg

**Comment by hyochan** [comment]
I've just seen this. How is this closed? Looks like you've found the solution though.

Mostly, this is not a problem with the module.

**Comment by indapublic** [comment]
@abdulwahabcs iOS 14?

**Comment by AngelDev727** [comment]
Same here.
How can I solve this issue?
