### ISSUE TITLE
One Time trial was already activated in past question

### ISSUE THREAD

**Issue by alesmraz** [dooboolab/react-native-iap#1214]
### Version of react-native-iap
4.6.1

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
return info that user can use trial subscription period without paying

### Actual behavior
not sure which function return this?

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Setup free period in stores.

This is question, not a bug. I need to know when user already bought a subscription with onetime trial period, use this onetime trial period and then unsubscribe. I found some solution for iOS here: https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_introductory_offers_in_your_app

I would like achieve this: condition for show/hide trial text:
1. It can be also turned on/off from the store. 
2. User might not be eligible for the trial offer (= already had the trial activated in the past)

Did anyone has experience with this please? :)

**Comment by montoyaaguirre** [comment]
I would also like to know this.
