### ISSUE TITLE
Subscription Purchase

### ISSUE THREAD

**Issue by abdulahad96** [dooboolab/react-native-iap#1216]

**Comment by ramirobg94** [comment]
+1

**Comment by abdulahad96** [comment]
is any solution found?

**Comment by Yann-prak** [comment]
If you're on sandbox, sometimes it can take a lot of times to just show the payment popup. You can wait several minutes. Don't why it happens, but happens quite frequently.

**Comment by worldzb** [comment]
version of 4.4.0 still exist
