### ISSUE TITLE
purchaseUpdatedListener is always called at start-up (Amazon) 

### ISSUE THREAD

**Issue by avoloshko** [dooboolab/react-native-iap#1221]
### Version of react-native-iap
5.2.0
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
purchaseUpdatedListener should only be called when a user subscribes for in-app subscriptions
### Actual behavior
purchaseUpdatedListener is called at start up (once the listener is registered)
### Tested environment (Emulator? Real Device?)
Real device, GalaxyS9, Android 10
### Steps to reproduce the behavior
- Install an app from Amazon Store
- listen to purchaseUpdatedListener events

**Comment by hyochan** [comment]
@iaphub Do you have any idea with this?

**Comment by iaphub** [comment]
I don't see the issue, don't think we should prevent amazon from triggering a receipt, we're just a wrapper around the library.

**Comment by andresesfm** [comment]
This works as designed, please see the SDK's documentation here: https://developer.amazon.com/docs/in-app-purchasing/iap-implement-iap.html#3-get-user-information in your code you can decide when/if you want to trigger some logic on the purchase listener. Closing for now, feel free to reopen if more information
