### ISSUE TITLE
iOS RNIap.buyProductWithoutFinishTransaction(productId) never resolves.

### ISSUE THREAD

**Issue by owenhope** [dooboolab/react-native-iap#1223]
### Version of react-native-iap
2.5.5

### Version of react-native
59.8

### Platforms you faced the error (IOS or Android or both?)
IOS only

### Expected behavior
Calling

let purchase = await RNIap.buyProductWithoutFinishTransaction(productId)

should resolve with a purchase 

### Actual behavior

never resolves, just continues to wait for a response.

### Tested environment (Emulator? Real Device?)

Real Device

----

I have an older project, that is in a production environment that suddenly stopped working.

I have tried to change RNIAP.buyProduct(productId) as well, but it doesn't resolve either.

```
  await RNIap.clearTransaction();
  let purchase = await RNIap.buyProductWithoutFinishTransaction(productId);
  console.log(purchase)
  return await serverAction(purchase)
    .then(function (response) {
      RNIap.finishTransaction();
      return response;
    })

```
Any suggestions?

I can't really at the moment upgrade to a newer version of RNIAP or React Native.

Thanks.

**Comment by hyochan** [comment]
I think this is a compatibility issue with recent `iOS` updates. Could you also provide `iOS` simulator version and the xcode version?

**Comment by TAM360** [comment]
Hey, I am experiencing the same issue. RNIap.buyProductWithoutFinishTransaction(productId) neither resolves nor it gets rejected, as if it was never triggered in the same place. Following the environment details

- React Native version: ^0.63.4
- iOS version: 14.6
- environment: production
- device: iPhone X (physical)
- RNIap version: 2.5.5

Does anyone have any clue as to what is triggering this behavior?
