### ISSUE TITLE
GetProducts() on Android 10 is completely broken

### ISSUE THREAD

**Issue by jason11ac** [dooboolab/react-native-iap#1224]
This call is crashing immediately on Android 10. Worked nicely on Android 9, but as soon as we updated it crashes. 

const products: Product[] = await RNIap.getProducts(itemSkus);

Are others seeing this?

**Comment by hyochan** [comment]
Oh! I really want to tackle this.

**Comment by andresesfm** [comment]
Closing as stale, please feel free to reopen if more info
