### ISSUE TITLE
verifyReceipt always 21002 IOS

### ISSUE THREAD

**Issue by MacMillan13** [dooboolab/react-native-iap#1229]
### Version of react-native-iap
5.0.1
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Normal response from https://sandbox.itunes.apple.com/verifyReceipt
### Actual behavior
Response "status": 21002
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
I try to use validateReceiptIos, but get status: 21002
I tried REST Client, parameters password, and receipt-data, but nothing. 

Please help.
<img width="629" alt="Снимок экрана 2021-01-09 в 22 27 34" src="https://user-images.githubusercontent.com/18086617/104108062-4c2fbb00-52ca-11eb-9b6b-46a17b94e93d.png">
<img width="1076" alt="Снимок экрана 2021-01-09 в 22 25 39" src="https://user-images.githubusercontent.com/18086617/104108063-4df97e80-52ca-11eb-9fbe-685c25bafd9d.png">

**Comment by nguyenmtuanctk35** [comment]
I'm facing this issue too. Can anyone help?

**Comment by pockiii** [comment]
Use an real device bro :)

**Comment by MacMillan13** [comment]
@pockiii thanks, helped.

**Comment by dharmasat** [comment]
@pockiii Facing issue in real device... 
Note: no StoreKit configuration made

**Comment by Revolt9k** [comment]
Same issue, on real device trough TestFlight app just crashes on pay press. In Xcode environment it returns 21002 status. Any suggestions?

**Comment by ftaibi** [comment]
Same issue I am using my iPhone

**Comment by azeezWebsultanate** [comment]
Same issue on real device ( iPhone 11 ) 
react native (0.67.4)
react-native-iap : (^8.0.7)

**Comment by roots-ai** [comment]
Any updates here?

**Comment by andresesfm** [comment]
`12.0.3`

**Comment by Mourad-Tlili** [comment]
Same issue on real device
