### ISSUE TITLE
Android app crashes randomly

### ISSUE THREAD

**Issue by ilyakar** [dooboolab/react-native-iap#123]
### Version of react-native-iap
0.2.17

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
No crashing

### Actual behavior
App crashes randomly for some users

### Steps to reprodue the behabior
It only happened once for me and was quite random. But a crash ocurred for 40% of my users. I have a Crashlytics stacktrace for you
![13f9384c-3d7e-4c19-92d0-aaf4384c97a9](https://user-images.githubusercontent.com/1760709/38718255-715d469e-3eec-11e8-9712-e6a0b84a2b45.png)

I’m not 100% certain the crash is causes by this plugin but it seems likeit from the stacktrace.

Is it a version thing? Should I update to the latest?

**Comment by ilyakar** [comment]
Here are the devices affected:

![610f5ce3-a67c-461a-898f-198bd0b1e0b1](https://user-images.githubusercontent.com/1760709/38718352-f984cbaa-3eec-11e8-9354-6302ca2803bc.png)

**Comment by dooboolab** [comment]
@ilyakar Hi. Thank you for the kind report. Hm... could you please try version `0.3.10` and try to release the connection by calling `endConnection` when you leave the billing page? I think there could be an issue for handling billing services.

**Comment by ilyakar** [comment]
Thank you for the reply. I’ll try that today. And will also test the podfile issue we discussed last week.

Kind regards,
Ilya

**Comment by ilyakar** [comment]
Okay I tried the latest version, but what's with this new endConnection function? I tried implementing it when the user leaves the billing page, but if the user decides he wants to make a purchase after all, then there is no connection and no purchase screen is opened.

Anyway, I'll try pushing version 0.3.10 to Google Play and see if the app keeps crashing for people.

**Comment by dooboolab** [comment]
@ilyakar endConnection is to finish the billing thread in android. So if you want to reopen the billing service you need to`prepare` again. So it is recommended to use `prepare` method in `componentDidMount` and `endConnection` in `componentWillUnMount`.

**Comment by ilyakar** [comment]
Oh I see. Great timing @dooboolab I was about to publish the way it way. I made the necessary changes and will give this a shot. I'll get back in a few days if this solved the crashing. Thank you!

**Comment by dooboolab** [comment]
@ilyakar what is SQ7 device? Hm, are you sure that they're able to use play service? Some Chinese device might crash like that because they don't have the playstore installed. We'll support feature like `isBillingAvailable` method in future.

**Comment by ilyakar** [comment]
Unfortunately I don’t have more information than that. I’ll let you know if the crashes increase to a drastic rate.

Kind regards,
Ilya
