### ISSUE TITLE
Exception "Billing is unavailable. This may be a problem with your device, or the Play Store may be down." till Google Play storage hadn't cleaned

### ISSUE THREAD

**Issue by torcoste** [dooboolab/react-native-iap#1230]
### Version of react-native-iap
4.6.3, 5.2.0

### Version of react-native
0.63.3

### Platforms you faced the error
Android

### Expected behavior
Lack of exceptions in production.

### Actual behavior
I see exceptions "Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down." in sentry.
I also got the behavior in one real device. There were not any subscriptions data from `RNIap.getSubscriptions`.
I've updated rn-iap from 4.6.3 to 5.2.0, but behavior was the same. 

Then I cleared the storage/cache of the "Google Play" and "Google Play services" apps. It helped. 
So, problem looks like a solved, but I'm sure that user will not go to settings to clear Google Play services cache.

### Tested environment (Emulator? Real Device?)
Real device - Google Pixel 3
Production mode

### Steps to reproduce the behavior
1. Open a production app in airplane mode and get some of exceptions trying purchase.
2. Turn on wifi/network, and reboot app.
3. The exceptions is still there 

Thank you for your efforts!

**Comment by torcoste** [comment]
My user had another problem (He had seen subscriptions, but couldn't buy - `requestSubscription` didn't work) which had been fixed only by cleaning storage of Google Play Store.
It looks like related issue.

Please, take a look at this case. It's crucial.

**Comment by hyochan** [comment]
@torcoste Have you tried finishing all pending transactions when you start your app?

**Comment by torcoste** [comment]
@hyochan No, I missed that up. Thank you a lot for the answer!

Could you please also tell me do you know how to reproduce bug? For checking that it's fix the problem.
