### ISSUE TITLE
getProducts and getSubscriptions are empty

### ISSUE THREAD

**Issue by ajouve** [dooboolab/react-native-iap#1231]
### Version of react-native-iap

5.2.3

### Version of react-native

0.63.4

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

getProducts and getSubscriptions should not return an empty array

### Actual behavior

getProducts and getSubscriptions return an empty array

### Tested environment (Emulator? Real Device?)

Real device

### Steps to reproduce the behavior

I already configured it on IOS the app is working fine

On Android I published the app on internal test and my main account on the internal test release in among the test users.

My product is a subscription I do not know if I have to do something else 

My subscription is active 

My release is accessible for internal test

**Comment by MaoPeng94** [comment]
Same here?
Is there any way to resolve this problem?

**Comment by torcoste** [comment]
Please try to clean cache of Google Play Services app and try again.
Please let me know if it changed something

**Comment by MaoPeng94** [comment]
It was solved with easy solution. I did sync google playstore account again. After sync completed, it is working.

**Comment by hyochan** [comment]
@MaoPeng94 Looks like this is many asked question. Could you kindly support more direction in this thread on syncing account?

**Comment by hyochan** [comment]
Also here is [a great article(https://medium.com/bleeding-edge/testing-in-app-purchases-on-android-a6de74f78878) to handle such an issue.

**Comment by andresesfm** [comment]
Closing for now, please feel free to reopen if needed

**Comment by ZeeshanAhmadKhalil** [comment]
is there any solution for iOS 
i am getting this issue for iOS

**Comment by NoatToan** [comment]
@ZeeshanAhmadKhalil Please try to add the storekit if you're testing on simulator
Then if the release on testlight. Plese check your apple account whether you processed the payment info.
