### ISSUE TITLE
how I can delete or disable purchase in the apple connect ?? Thank you.

### ISSUE THREAD

**Issue by minh-dai** [dooboolab/react-native-iap#1232]

**Comment by nguyentrannhan** [comment]
+1

**Comment by hyochan** [comment]
As far as I know, you can't refund purchases from the service-provider side. If the user-requested a refund from `Apple`, and succeeded you can verify receipt so that the user is still subscribed or consumed.

Related: https://developer.apple.com/forums/thread/11626
