### ISSUE TITLE
getSubscriptions returns an empty array

### ISSUE THREAD

**Issue by isonlaxman** [dooboolab/react-native-iap#1234]
### Version of react-native-iap
5.2.3

### Version of react-native
0.63

### Platforms you faced the error (IOS or Android or both?)
iOs

### Expected behavior
I should see my subscription product in the array

### Actual behavior
The resulting array is empty

### Tested environment (Emulator? Real Device?)
Real Device (iPhone 8)

### Steps to reproduce the behavior
My app is currently in development (I have not submitted to AppStore but have been testing with 20+ TestFlight users). Towards the end of our development, we finally tackled payments and I'm using this library for it. 

I added an 'Auto Renewable Subscription' to my app in AppStoreConnect and saved it. I've added pricing for one localization (US). 

I then installed the library and in componentDidMount on my subscribe screen, I called initConnection followed by getSubscriptions with the correct product ID. However, getSubscriptions returns an empty array.

### What I've tried
- getProducts instead of getSubscriptions, but same result - an empty array
- confirmed that the bundle ID is correct

### To note
I haven't submitted my app for review yet, is that an important step that I need to take to get rn-iap to work?

**Comment by AndreaGiulianini** [comment]
Update?

**Comment by salman-pixarsart** [comment]
Hi @isonlaxman  Have you filled all the forms in the Agreements, Tax, and Contracts section for Paid apps?

**Comment by hyochan** [comment]
Related #1235 

I've managed to use `StoreKit` for now. Hope there is a better track.
