### ISSUE TITLE
Not able to get products (empty product array) on xCode 12.3. But working successfully on xCode 11.3 & 12.1

### ISSUE THREAD

**Issue by mitesh-db** [dooboolab/react-native-iap#1235]
### Version of react-native-iap
"react-native-iap": "^5.1.1"

### Version of react-native
"react": "16.13.1",
"react-native": "0.63.2",

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Should Load products which are defined in apple console on xCode 12.3

### Actual behavior
Getting empty array of products when calling `RNIap.getProducts(itemSkus);`
It is successfully working on xCode 11.3 & 12.1 but not getting products on 12.3 

### Tested environment (Emulator? Real Device?)
Both Real device and Simulator

### Steps to reproduce the behavior
1. Building project on xCode 12.3
2. try to load products using `RNIap.getProducts(itemSkus);`
3. Getting empty list of products

**Comment by jimsideout** [comment]
Any luck on this?

**Comment by RahulRijhwani** [comment]
i think you should try with storekit configuration

**Comment by jimsideout** [comment]
@RahulRijhwani Just set up the storekit configuration file and enabled it in my scheme, but still returning undefined.

**Comment by enestatli** [comment]
I am getting undefined , any update on this?

**Comment by RahulRijhwani** [comment]
you need to add your products and subscriptions on Storekit configuration.

**Comment by enestatli** [comment]
@RahulRijhwani I am new to the Apple products, no idea how to set

**Comment by AndreaGiulianini** [comment]
I have a real device, all made in App Store Connect, because the array
 it's empty? I don't want to configure Storekit because the app crashes when entered

**Comment by hyochan** [comment]
Looks related to this. Currently, I am also using `StoreKit`. https://stackoverflow.com/questions/58020258/requesting-an-in-app-purchase-in-ios-13-fails/58065711#58065711.

Still wondering how I can avoid this.

**Comment by MutableLoss** [comment]
I dealt with this issue a lot in iOS, and I found there could be a lot of causes for an empty result, all depending on the environment and setup. I went ahead and wrote a checklist in #723 

@hyochan Would it be feasible to throw an error when passing an empty array to getProducts in the iOS wrapper? Since the _getItems_ module won't throw an error when an empty array is passed, I can imagine that could be one contributor to the empty getProducts result.

**Comment by ilyakar** [comment]
Tried everything. Confirmed, for me it was the need to add a StoreKit file (even when debugging on a real device). Then, don't forget to link the StoreKit file in Product -> Schemes -> Edit Scheme:
![image](https://user-images.githubusercontent.com/1760709/136253663-f9aa00a6-a270-4005-92a3-ef7c4c822f84.png)

**Comment by Mihai-github** [comment]
Where do I get this storekitConfig file?

**Comment by andresesfm** [comment]
This was reported long ago and with a very old version of the library. Please reopen/ create a new issue if this is still happening on 8.x.x

**Comment by Norcy** [comment]
> Where do I get this storekitConfig file?

Try this: https://developer.apple.com/documentation/xcode/setting-up-storekit-testing-in-xcode

**Comment by andresesfm** [comment]
For reference we have included one in the example app: https://github.com/dooboolab/react-native-iap/blob/main/IapExample/ios/Configuration.storekit

**Comment by darthjaja6** [comment]
Trying storekit now, hope it works...but also curious: is Storekit a must?
