### ISSUE TITLE
[Announcement] The plan for 2021 maintenance

### ISSUE THREAD

**Issue by hyochan** [dooboolab/react-native-iap#1241]
Hello there. Hope you are doing well with `react-native-iap`.

I've not had much time recently to maintain this module and hopefully waiting for contributors to make this module healthy. The problem with maintaining this module was caused by dropping our startup business which heavily relied on `in-app-purchase` as told in #855.

As I am always struggling to seek new industries to contribute to survive, it is not easy to come back and keep up with the latest things I've done in the past (there are so many). Best of all, I reviewed the PR when it came up.

The latest thing, I've tried was to earn money in [react-native-iap opencollectives](https://opencollective.com/react-native-iap) and give them to the people who maintain our module. I've always wanted to make a firm example project that runs this module but the project, [DoobooIAP](https://github.com/hyochan/doobooiap) have been stopped since there is not much motivation to move this forward for just to provide an example.

Therefore, I am thinking of creating a project that runs `react-native-iap` near future and gets live sponsorships with `react-native-iap` project instead of opencollectives. That way people can download and see the working examples and contribute to the project and make our module much much more healthy. It would take approximately 2 months (estimating my free time) from now and our module `react-native-iap` will grow slowly.

Lastly, to bump up the motivation, I'd like to know who is using `react-native-iap`. Badges, logos are welcomed if you are in organizations.

Thank you all for using this 🙏

**Comment by ninjaboy** [comment]
Sad to see you dropping this, so far this is the only viable alternative in the react-native ecosystem for small startups to integrate with in-app purchases and abandoning this package will mean we are left with no alternative.

**Comment by hyochan** [comment]
> Sad to see you dropping this, so far this is the only viable alternative in the react-native ecosystem for small startups to integrate with in-app purchases and abandoning this package will mean we are left with no alternative.

I think you have miss understanding. I am not dropping it. I am trying to support this with the live example in nearly 2 months.

I had dropped my startup product in 2019 which made me 
stick to this module because iap feature was really important in our product. However, our product ended and I could not participate as much as before working on other things. Therefore, this module wasn't maintained well. These stories are what I have above and in the past.

In 2021, I am trying to overcome the problem until there is a better option. Hope the mesaage is clear now.

**Comment by ninjaboy** [comment]
Yes, sir, the message is clear. Glad to hear this!

**Comment by iaphub** [comment]
Thanks for your commitment to this awesome open-source module @hyochan, will of course continue helping maintaining it in 2021 🙂 
There is a lot of cases to handle since In-App purchases are unfortunately not easy but I can say that when implemented correctly the module is working perfectly.
Just curious, what would be the difference with the [DoobooIAP](https://github.com/hyochan/doobooiap) example?

Also if anyone is looking for a battle tested example using react-native-iap with the validation of the receipts on the server (highly recommended if you do not want users with jailbroken phones to buy your in-app purchases for free), the [code of react-native-iaphub](https://github.com/iaphub/react-native-iaphub/blob/master/src/index.js) is open source and there is an [example project](https://github.com/iaphub/react-native-iaphub/tree/master/Example) as well.

Feel free to look at it if you're developing your own IAP implementation with server validation, you won't find anything more complete and the code is updated regularly 🤗

**Comment by hyochan** [comment]
@iaphub It would be on top of [DoobooIAP](https://github.com/hyochan/doobooiap). The core difficulty in maintaining `iap` is that 90% of the time it is working fine but there are many unknown issues in other areas.

To report these issues to platform providers or look into them to make a workaround, we need a reproducible example or at least some codes that are driven along with platform updates. Currently, we don't have that.

I'm looking toward integrating `iap` with a working example and a live example that will be published in both appstore and playstore. I'll try to update those continuously as this module is maintained.

This will also help to integrate and test new features provided by the platform providers. Currently, we are a bit outdated.

**Comment by benjaminMatteJean** [comment]
We use this library and we are very happy about it.

Thank you for maintainig it. It really was a game changer

**Comment by hyochan** [comment]
@benjaminMatteJean Thanks for sharing! Could you kindly share this once again in #1247? It'd be greater if you can share where you belong to.

**Comment by mifi** [comment]
Keep up the great work! I'll be donating every time I'm using this module.

**Comment by hyochan** [comment]
Hey there. I've tried to build my project in https://github.com/hyochan/dooboolab.com integrating our `react-native-iap` module. This mostly is ported in [Sponsor page](https://github.com/hyochan/dooboolab.com/blob/master/src/components/pages/Sponsor.tsx).

I was hoping to make a live example project with [dooboolab.com](https://github.com/hyochan/dooboolab.com) which is available in [android playstore](https://play.google.com/store/apps/details?id=com.dooboolab.app) however has been rejected by Apple and I've tried some other things to get this app approved but I think I have to work on the other one instead.

Therefore, sorry for the delay in building a live example for `iOS` and continuous development which use `react-native-iap`. I'd have to work on the other project using it. I wish I can come back with it in 2021.

However, you may see a better example in the source code provided in [dooboolab.com repository](https://github.com/hyochan/dooboolab.com).

**Comment by mars-lan** [comment]
Thanks for this great library, @hyochan! We've been using `react-native-iap` in our app, [TrayMinder](https://trayminder.com) since almost day one. Would definitely be interested in helping out with the ongoing maintenance.
