### ISSUE TITLE
Invalid product ID when i try RNIap.requestPurchase('SKU') 

### ISSUE THREAD

**Issue by joeljerushan** [dooboolab/react-native-iap#1242]
### Version of react-native-iap
"react-native-iap": "^5.2.0",

### Version of react-native
"react-native": "0.63.1",

### Platforms you faced the error (IOS or Android or both?)
IOS & Android

### Expected behavior
Purchase complete and display [Environment: Sandbox] end of the purchase

### Actual behavior
![IMG_1949](https://user-images.githubusercontent.com/10111309/106415051-284c3900-6474-11eb-9fba-a5da3b541026.jpg)
![image](https://user-images.githubusercontent.com/10111309/106415134-57fb4100-6474-11eb-8781-e49b3d7ed687.png)

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

```
// Version 3 apis - function
requestPurchase = async (sku): void => {
    try {
      RNIap.requestPurchase(sku);
    } catch (err) {
      console.warn(err.code, err.message);
    }
};

//render method
<NativeButton
    onPress={(): void =>
      this.requestPurchase('sb001')
    }>
    Request purchase for above product
</NativeButton>
```

**Comment by hyochan** [comment]
Looks like you are testing our example project. You need to get invited by us to make this happen. Try to test this in your own project! [Here is how you can configure iap in each project](https://github.com/dooboolab/react-native-iap).
