### ISSUE TITLE
Android [Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.]

### ISSUE THREAD

**Issue by MacMillan13** [dooboolab/react-native-iap#1243]
### Version of react-native-iap
5.0.1
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Have to see products.
### Actual behavior
Have this error in terminal - 
[Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.]

### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
I tried to check the configs of react-native-iap, everything is okay.
By the way, I'm logged in Play Store. But I use an old phone with an old android.

**Comment by MacMillan13** [comment]
By the way, I'm logged in Play Store..

**Comment by hyochan** [comment]
Could you give more information on this? What device and `OS` are you using?

**Comment by rogerdribeiro** [comment]
same issue. 
I'm using android emulator in version 10.
In emulator iOS that's working.

**Comment by zholmes1** [comment]
@rogerdribeiro 

This is expected in the Android emulator. This library does not work on emulators.

**Comment by avonipenti** [comment]
We see this error on devices or emulators with no play store app on android. However, it does fill up our error reporting even though its not a real crash. Is there a way to make this a warning instead of an error?

**Comment by zholmes1** [comment]
@avonipenti 

You can catch the error and not report it to your error handling service

**Comment by TaylorDale** [comment]
Where would you catch this error for @next with hooks? I believe try/catching useIAP(); would be against how hooks work given they are not guaranteed to execute every time then

**Comment by zholmes1** [comment]
Yeah definitely should not be catching a hook. Maybe there needs to be an optional `onError` parameternfor the hook?

**Comment by MacMillan13** [comment]
@rzholmes1 I connected the phone, but don't get any products. Just when I try to IAP.getProducts - then catch "Error: The service is unreachable. This may be your internet connection, or the Play Store may be down. " ....

**Comment by MacMillan13** [comment]
@hyochan I use an old phone with android 5.1.

**Comment by MacMillan13** [comment]
I bought a new test device with android 10 and that works. Thank everyone for the answers.

**Comment by Traviskn** [comment]
I found that this error will occur on any android device that does not have any account signed in under the device settings.

**Comment by cervebar** [comment]
> I found that this error will occur on any android device that does not have any account signed in under the device settings.

To make this answer complete:
- you need to create your emulator with Google Play
- then you have to log in to Google Play on that emulator

<img width="1000" alt="Screenshot 2023-09-07 at 11 48 27" src="https://github.com/dooboolab-community/react-native-iap/assets/2403914/319d210e-60e8-46e3-bf5c-46700e999ce4">


note:
- when you wipe your data (as I did 🤦‍♀️ ) then you need to login again

**Comment by kulakowka** [comment]
If you are using Expo, try `npx expo start --clear`. It helped me.

**Comment by pixlerSanjay** [comment]
Helllo i got same issue 
i ahve used 
import {Platform} from 'react-native';
import {APP_STORE_SECRET} from './config';
import * as RNIap from 'react-native-iap';

export const getAllPurchasePlans = async productSkus => {
  try {
    let checkIt = await RNIap.initConnection();
    console.log('=========', checkIt); // This should print something if initialization is successful

    // Flush failed purchases cached as pending on Android
    if (Platform.OS === 'android') {
      const isFlushSuccessful =
        await RNIap.flushFailedPurchasesCachedAsPendingAndroid();

      if (!isFlushSuccessful) {
        console.log('No failed purchases cached as pending.');
        // Handle the case where there are no failed purchases cached as pending
      } else {
        console.log('Failed purchases cached as pending flushed successfully.');
      }
    }
    const products = await RNIap.getProducts({skus: productSkus});
    console.log('-products----------->->->->', productSkus, products);
    return products;
  } catch (error) {
    console.error('Error fetching products:', error);
    return [];
  }
};


and i got same error in catch block Error fetching products: [Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.]

**Comment by DevHeauk** [comment]
it also can be related supporting paid service country of play store 
refer this page. https://support.google.com/googleplay/answer/143779?sjid=6123458031532873966-AP

**Comment by chuchuva** [comment]
For me the issue was calling `finishTransaction` method for a subscription and not passing `isConsumable: false`. It should be:

    finishTransaction({purchase, isConsumable: false})

**Comment by hyochan** [comment]
> finishTransaction

This is bit strange because   `isConsumable = false` is default and should be true when it is `Subscription` 🤔

**Comment by chuchuva** [comment]
Are you sure? This code is from [subscriptions example](https://hyochan.github.io/react-native-iap/docs/examples/subscription-manager#4-process-successful-purchase):

      // Finish the transaction
      await finishTransaction({
        purchase,
        isConsumable: false, // Subscriptions are non-consumable
      });

**Comment by hyochan** [comment]
@chuchuva Yes https://github.com/hyochan/react-native-iap/blob/0fa3f4ae004382cd61cfb4d73b6bb359fbb3d461/src/index.ts#L351

That is just an example code to show that there is extra arg

**Comment by chuchuva** [comment]
It must be something else that fixed that error for me, sorry for confusion.

**Comment by dagumb77-hub** [comment]
> ### Version of react-native-iap
> 5.0.1
> 
> ### Version of react-native
> 0.63.3
> 
> ### Platforms you faced the error (IOS or Android or both?)
> Android
> 
> ### Expected behavior
> Have to see products.
> 
> ### Actual behavior
> Have this error in terminal - [Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.]
> 
> ### Tested environment (Emulator? Real Device?)
> Real Device
> 
> ### Steps to reproduce the behavior
> I tried to check the configs of react-native-iap, everything is okay. By the way, I'm logged in Play Store. But I use an old phone with an old android.
