### ISSUE TITLE
iOS requestPurchase really slow, is this due to RNIAP?

### ISSUE THREAD

**Issue by kyle-ssg** [dooboolab/react-native-iap#1244]
### Version of react-native-iap
5.2.5

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
requestPurchase returns in a reasonable time.

### Actual behavior
Call to this is taking ~20 seconds sometimes.

### Tested environment (Emulator? Real Device?)
iPhone 12 Pro

### Steps to reproduce the behavior
Call RNIap.requestPurchase(sku) with a valid TestFlight user against an unreleased product, perhaps this is quicker in production?

**Comment by kyle-ssg** [comment]
An additional note on this, I probably have a lot of purchases consumed at this point, if that's a possible cause.

**Comment by GuilhermeHCDias** [comment]
Same problem here =(

**Comment by juliatiemi** [comment]
I am experiencing the same issue

**Comment by ninjaboy** [comment]
This is a known issue for sandbox accounts. Many people constantly face this. The usual workaround is to try creating a fresh account and use that.
As such this might be a problem with RNIAP performance too, but I guess nobody digged this enough.

**Comment by kyle-ssg** [comment]
Ah ok, if this is just sandbox then that's not a big deal.

**Comment by nandowastaken** [comment]
@kyle-ssg did it appeared faster at production?

**Comment by aerohh** [comment]
@kyle-ssg @nandowastaken

Did the same slow behavior persisted in the sandbox environment or is there a fix ?

For me the initial purchases are not that slow, however with time on the same sandbox account and as the number of consumed purchases increase, the purchase popup gets more slow.

**Comment by nandowastaken** [comment]
@aerohh For me, in production and development the purchase popup are fast. They were slow for a while, but this resolved, I don't remember if it was something I did, but I believe it was something that weirdly fixed itself.

By the way, I am using RevenueCat in a side project, and, honestly, I am thinking it is way easier than react-native-iap, unless you have a good reason not to, you should give it a try, react-native-iap gives a lot of headaches... yikes!
