### ISSUE TITLE
Who are using react-native-iap?

### ISSUE THREAD

**Issue by hyochan** [dooboolab/react-native-iap#1247]
Let me know so that I can see how this is valued 🙏 

Please continue current thread to https://github.com/dooboolab/react-native-iap/discussions/1343

**Comment by ws333** [comment]
Hi Hyochan,

I'm using react-native-iap in my new app.

It seems like this package is more important than ever since all in-app payments in Android apps now has to go through Google Play as far as I've understood.

So your package is highly appreciated!

**Comment by n0umankhan** [comment]
I'm using it, it was all working fine thank you so much for all of your efforts, since few days i got stuck with storeKit configuration as i'm a javascript developer instead native one but yes many thanks for all of your support

**Comment by kalmahik** [comment]
I'm using this module in many projects. Thank you  🙏

**Comment by hyochan** [comment]
Thanks for sharing 👍 It'd be better if you can share your apps either.

**Comment by Iamscaredofcode** [comment]
Here too!

**Comment by ixuz** [comment]
Love this package! We use this in our first app with in-app subscriptions. Works great and super appreciated! 👍

**Comment by lahivee** [comment]
Thank you for this great package! It is the only viable option!!

**Comment by FelipeMolinari** [comment]
I'm using this module for a while. . 
Thank you for this great lib. 👍

**Comment by hyochan** [comment]
Thanks for sharing everyone. Since many of you shared interests here, I've worked out on making `hooks` this weekend. Thanks for all your kindness.

Here is the [medium post](https://medium.com/p/96c7ffd3f19a) on how to use it.

Lastly, I think I'd be more wonderful if you can share your apps or your organizations 🙂🙏☺️

**Comment by noahfpf** [comment]
We're using this library for [Front Porch Forum on iOS](https://apps.apple.com/us/app/front-porch-forum/id1458651656).  Thanks for all your work on it!

**Comment by edersonfaccin** [comment]
Hello, I followed your tutorial and the getsubscriptions part brings an empty array, but if I put the sales code in the requestSubscription fixed it opens the purchase confirmation screen normally. I am testing on a real device.

**Comment by hyochan** [comment]
@noahfpf Thanks for sharing the app for the first time! This is wonderful ❤️

**Comment by mralj** [comment]
We have been using it at Madbarz ([Android](https://play.google.com/store/apps/details?id=com.madbarz.madbarzApp&hl=en&gl=US), [iOS](https://apps.apple.com/us/app/madbarz-bodyweight-workouts/id969057083)) for ~6mnths now, the project is really awesome 😁, thank you really much for all the hard work! 💪

**Comment by ixuz** [comment]
I'm using this library for the app "Wondertales".

**Comment by marf** [comment]
We are using this module for the music app eSound ([iOS](https://apps.apple.com/us/app/id1224933860) & [Android](https://play.google.com/store/apps/details?id=com.esound&hl=en&gl=US)).

Thank you for it!

**Comment by phillmill** [comment]
I'm using it for my app Gandr ([iOS ](https://apps.apple.com/us/app/gandr/id1401102974)& [Android](https://play.google.com/store/apps/details?id=app.gandr))

**Comment by 0hio-creator** [comment]
We are using it for One Small Step ([iOS](https://apps.apple.com/au/app/one-small-step-green-living/id1495609545) & [Android](https://play.google.com/store/apps/details?id=com.tneapp&hl=en_AU&gl=US) )

**Comment by jackspiva** [comment]
We're using it for Tinyhood Online Parenting Classes ([iOS](https://apps.apple.com/us/app/tinyhood-parenting-classes/id916353160))! Hopefully on Android as well soon.

**Comment by ethanwc** [comment]
Using it on something :)

**Comment by Yann-prak** [comment]
Using it on 2 of my apps :)

**Comment by EvelinJK** [comment]
We are moving our existing App from Cordova to React Native and will be using this plugin too.
Many thanks for the `hook` @hyochan 🙌  🎉   
We're not a small company anymore and have quite a chunk of subs coming in each month, so we heavily rely on a smoothly working plugin. Great to see this being maintained again.

**Comment by sayem314** [comment]
I'm using it on [Loader (Media Player)](https://loaderapp.info/)

**Comment by edersonfaccin** [comment]
I'm using GarageFix, [android](https://play.google.com/store/apps/details?id=com.carangomobile) [ios](https://apps.apple.com/us/app/garagefix/id1554131935)

**Comment by kayamy** [comment]
@hyochan I'm using it in a plugin for adalo -> https://twitter.com/AdaloHQ/status/1362089284031897615

Thanks to this repo many non-coding people can easily set up in app purchases in their app :)

**Comment by aubert-creation** [comment]
At [Okast.tv](https://okast.tv/en/), we using it (Work in Progress)
on iOS and Android for our clients ([Qwest.tv](https://qwest.tv/), [Museum.tv,](https://www.museumtv.art/) [Dini](https://www.dini.fr/), [MyZen,](https://www.myzen.tv/) [MotionLive](https://www.motionlive-tv.com/))

Many thanks for this incredible work, and for Hooks 😸

**Comment by garfiaslopez** [comment]
Hello! @hyochan 

We are currently using at [Beek.io](https://www.beek.io) we are a small startup. 
Our iOS app subscription flow have this module integrated for subscription services. 

Thanks a lot for your work!

**Comment by hbarylskyi** [comment]
We're using it on mobile @ virpp.com.

**Comment by hyochan** [comment]
Thank you so much for sharing! They all look incredible :100: 

I hope we can gather some sponsors in https://opencollective.com/react-native-iap to give some gifts to awesome maintainers like @andresesfm as a monthly maintenance fee.

Let's continue this thread further in https://github.com/dooboolab/react-native-iap/discussions/1343 to seek how we can seek ways to continue the project and help many others.

Thank you very much again for your warmness :bow:

**Comment by raquelmsmith** [comment]
Just wanted to pop in here and say I am using this package for my recipe publishing platform, Brunch (brunch.so/download). Thank you for creating and maintaining this package!!

**Comment by berk9595** [comment]
Hi, I am using it too. So far so good. I created subscription-based and purchase-based apps thanks to you <3

**Comment by goguda** [comment]
We're using it at [iROOMit](https://www.iroomit.com/) for our iOS & Android app.

Many thanks for this great module!

**Comment by Matiassimone** [comment]
Here Gol-Ball use it too! iOS + Android

https://lnkd.in/ed7NB-PU

**Comment by mzruiz** [comment]
Hola hola,

Currently using for a number of projects:

1. pencilbible.com
2. pocketcaddie.ai

**Comment by ccdwyer** [comment]
I used it for Dictionary.com's mobile app.

**Comment by shubhamdeol** [comment]
I use it

**Comment by hyochan** [comment]
Hey everyone 👋 We just launched a **"Who uses OpenIAP?"** showcase on [openiap.dev](https://www.openiap.dev) — and we'd love to feature the apps shared in this thread!

Since this thread is now read-only, submissions have moved here:

👉 **https://github.com/hyodotdev/openiap/issues/280**

You can also reply to our [announcement on X](https://x.com/hyodotdev/status/2084648736119312497) or email **hyo@hyo.dev** with:

- App name + one-line description
- Square logo (PNG/SVG)
- App Store / Google Play links
- Which library you use (react-native-iap, expo-iap, …)

Apps are featured only with your permission — you can request changes or removal anytime. 🙏
