### ISSUE TITLE
Trial eligibility on Android

### ISSUE THREAD

**Issue by montoyaaguirre** [dooboolab/react-native-iap#1248]
Client side check for trial eligibility:
In order to toggle the copy of a button between "start trial" or "start subscription" for IAPs, we need to know if the Google Play account of our user is eligible for trial. 

**- Does react-native-iap provide a simple way to verify trial eligibility? (Android)**

At the moment we are doing the following to determine trial eligibility:
1. Fetch the purchase history. `getPurchaseHistory() `
2. If there's at least 1 subscription, the user does not qualify fro trial.
3. We also wanted to check PurchaseStateAndroid to ensure that the state was Purchased but its returned as undefined.

**Comment by hyochan** [comment]
Looks like I need more detailed information to tackle this to actually grab what you expect! Since I've not had your scenario implemented previously, I am not getting where you said `If there's at least 1 subscription, the user does not qualify fro trial.`.

Also, in which case `PurchaseStateAndroid` is undefined? Could you provide some codes?

Thanks.

**Comment by montoyaaguirre** [comment]
Maybe a more general question would be, how to determine trial eligibility. I know that the PlayStore will not offer a trial to users who had a trial for the app in the past. However, if the user qualifies, I would like to make it explicit in my UI. At the moment, I'm guessing trial eligibility from the user purchase history. I say guessing because I'm assuming that if the user has any subscriptions in the purchase history, they will not be eligible for trial. This of course, doesn't hold true all the time. Does anyone know if the Android SDK or react-native-iap expose trialEligibility for the PlayStore user?

**Comment by andresesfm** [comment]
When calling  `getProducts()` one of the fields is  `freeTrialPeriodAndroid`. According to the documentation: https://developer.android.com/google/play/billing/subscriptions#free-trial :

> When showing your users products available for sale, you can use the SkuDetails.getFreeTrialPeriod() method to display that a free trial is available for a product.

Closing, feel free to reopen if needed

**Comment by adorum** [comment]
@andresesfm Hello, does `freeTrialPeriodAndroid` works for you when checking trial eligibility on android? I am getting a string response `P7W` all the time. Should `freeTrialPeriodAndroid` be different in case when user is eligible and if not? Thanks
