### ISSUE TITLE
PurchaseUpdatedListner is not firing up at every app re launch in ios

### ISSUE THREAD

**Issue by TeamDlxx** [dooboolab/react-native-iap#1249]
Version of react-native-iap 5.1.1

 Version of react-native 0.62.2

**Comment by hyochan** [comment]
Can you share how you've initialized `react-native-iap`?

**Comment by TeamDlxx** [comment]
**THIS IS HOW I PASS THE SKUS TO IAP**
const itemSkus = Platform.select({
  ios: [
    '******************'
  ],
  android: [
    '******************'
  ]
});


**THIS IS MY CODE TO REQUEST A PURCHASE**
    try {
      const purchase = await RNIap.requestPurchase('com.apprebel.audiolifts.premium', false)
        .catch(err => {
        });
    } catch (err) {
   
    }
  }
  
  
  ** AND HERE IS MY LISTENER THAT I WANT TO BE INITIATED AT EVERY APP LAUNCH BUT IT NEVER TRIGGERS**
  
    await RNIap.initConnection()

      this.purchaseUpdateSubscription = purchaseUpdatedListener(async (purchaseFromStore) => {

        console.log(purchaseFromStore, "purchase from store home screen");
        await AsyncStorage.setItem('purchase', JSON.stringify(purchaseFromStore));
      })

**Comment by hyochan** [comment]
Are you on simulator?? Try to run it on the real device either

**Comment by TeamDlxx** [comment]
I am testing on real device

**Comment by hyochan** [comment]
The error might have been thrown. Please check purchaseErrorListener either.

**Comment by TeamDlxx** [comment]
purchaseErrorListener does not call , but i can check again

**Comment by hyochan** [comment]
@TeamDlxx See if your code looks similar to provided here https://github.com/hyochan/DoobooIAP/blob/master/src/components/screen/Main.tsx.

Closing this for now. Feel free to tell if you still need help.

**Comment by TeamDlxx** [comment]
Okay, Thank you so much :) i will come back if the issue still persists.
