### ISSUE TITLE
buySubscription returning E_UNKNOWN on iOS

### ISSUE THREAD

**Issue by bakedbean** [dooboolab/react-native-iap#125]
### Version of react-native-iap
0.3.10

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
A subscription purchase receipt is returned 

### Actual behavior
'E_UNKNOWN', 'An unknown or unexpected error has occured. Please try again later.'

I've followed the setup instructions and am able to call `getSubscriptions()` and get back a valid subscription product.

When I call `buySubscription(myValidProductId)`  I get back the unknown error noted above.  Neither my app, nor the in-app purchase have been reviewed or approved as of yet, I'm still in development and testing phase.  Should I be able to test actually purchasing a subscription in this way? 

This has been tried both at the simulator and with app installed to my device.

**Comment by JJMoon** [comment]
You can test 'getProducts' in the simulators, but the other methods in the real devices.
I hope you implement and test as in the example. https://github.com/dooboolab/react-native-iap/blob/master/RNIapExample/src/components/pages/First.js
The apple IAP server sometimes work slowly, or does not work, test it several hours later.

**Comment by bakedbean** [comment]
thanks @JJMoon I appreciate the feedback.  I got it working, it turned out that I needed to be logged into the device using an itunes connect sandbox test user account.

**Comment by baytkod** [comment]
> thanks @JJMoon I appreciate the feedback. I got it working, it turned out that I needed to be logged into the device using an itunes connect sandbox test user account.

thanks !!

**Comment by hsparihar-systango** [comment]
@JJMoon 
I am facing the same issue on ios, the situation is once I successfully purchased 12 months recurring subscription. Then on sandbox environment on the device when I try to purchase 3 months or any other subscription less than 12 months I asked for sandbox user creds It shows purchase is a success then suddenly getting pop up which says An unknown or unexpected error has occurred." getting this error :
{ [Error: An unknown or unexpected error has occurred. Please try again later.]
framesToPop: 1,
code: 'E_UNKNOWN',
nativeStackIOS:
[ '0 RadioSpirit 0x0000000102bfd3e8 RCTJSErrorFromCodeMessageAndNSError + 152',
'1 RadioSpirit 0x0000000102b96b24 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.218 + 176',
'2 RadioSpirit 0x0000000102aeeb64 -[RNIapIos rejectPromisesForKey:code:message:error:] + 512',
'3 RadioSpirit 0x0000000102af10ec __45-[RNIapIos paymentQueue:updatedTransactions:]_block_invoke + 348',
'4 libdispatch.dylib 0x0000000104534dc8 _dispatch_client_callout + 16',
'5 libdispatch.dylib 0x000000010454382c _dispatch_lane_barrier_sync_invoke_and_complete + 124',
'6 RadioSpirit 0x0000000102af0e74 -[RNIapIos paymentQueue:updatedTransactions:] + 908',
'7 libdispatch.dylib 0x0000000104533824 _dispatch_call_block_and_release + 24',
'8 libdispatch.dylib 0x0000000104534dc8 _dispatch_client_callout + 16',
'9 libdispatch.dylib 0x0000000104542a78 _dispatch_main_queue_callback_4CF + 1360',
'10 CoreFoundation 0x0000000220894df4 + 12',
'11 CoreFoundation 0x000000022088fcbc + 1964',
'12 CoreFoundation 0x000000022088f1f0 CFRunLoopRunSpecific + 436',
'13 GraphicsServices 0x0000000222b08584 GSEventRunModal + 100',
'14 UIKitCore 0x000000024dbe6d40 UIApplicationMain + 212',
'15 RadioSpirit 0x0000000102996d70 main + 124',
'16 libdyld.dylib 0x000000022034ebb4 + 4' ],
userInfo: { NSLocalizedDescription: 'Cannot connect to iTunes Store' },
domain: 'SKErrorDomain',
line: 2268,
column: 26,
sourceURL: 'http://192.168.1.107:8081/index.bundle?platform=ios&dev=true&minify=false' }

Please help me understand and resolve this situation.

**Comment by Desintegrator** [comment]
same here
