### ISSUE TITLE
getAvailablePurchases() should throw meaningful error in case of purchases are denied

### ISSUE THREAD

**Issue by voxspox** [dooboolab/react-native-iap#1250]
### Version of react-native-iap
4.5.2
### Version of react-native
0.63.2
### Platforms you faced the error (IOS or Android or both?)
iOS only
### Expected behavior
`getAvailablePurchases()` should throw meaningful error and don't cause pop-up flood.

for error types see also #1179

### Actual behavior

if purchase permission are denied in iOS "Settings" App the following happens.

Many annoying pop-ups ("Purchases are denied") are plopping up about one per second. This is started by a call to `getAvailablePurchases()` on app start. Also this function throws `E_USER_ERROR` 

    "error": {
      "code": "E_USER_ERROR",
      "message": "The operation couldn\u2019t be completed. (SKErrorDomain error 4.)",
      "domain": "SKErrorDomain",
      "userInfo": {
        "NSUnderlyingError": {
          "code": "1050",
          "message": "underlying error",
          "domain": "ASDErrorDomain",
          "userInfo": {
            "NSDebugDescription": "In-app purchases not allowed on this device"
          },
    ...

If the user has denied purchases I don't want to bother the user with error messages.

Is it possible to ask this permission upfront?

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
- deny purchases globally in iOS Settings App
- call getAvailablePurchases()

**Comment by hyochan** [comment]
I am a bit confused. Why does this matter when you try to show the user that the purchases are not available until the user has made them available?

Could you clarify how the flow should be?

**Comment by voxspox** [comment]
The problem is that the user is flooded with popups triggered by one call to getAvailablePurchases.

**Comment by TfADrama** [comment]
@voxspox @hyochan 
About getAvailablePurchases, 
It returns an array of valid purchases made? Or all purchases made, even if they already expired?

I have an app with subscriptions and this is really confusing...
The documentation didn't help.

**Comment by Yann-prak** [comment]
`getAvailablePurchases` send all purchases no matter what. Even if they are expired. I've tried it in sandbox. When I tried to implement RestorePurchases, it sent me a lot of expired purchases. I don't know if this is the desired behavior but it is certainly annoying.
