### ISSUE TITLE
Not able to redirect to app after successful Payment from Device Settings: Issue in Live Payment

### ISSUE THREAD

**Issue by Prabh70** [dooboolab/react-native-iap#1253]
### Version of react-native-iap
5.2.3
### Version of react-native
0.62.2
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
After successful in app purchase payment control should be directed to home screen of app from device settings 
### Actual behavior
I am trying to purchase subscription from app but card details are not added in my account, am navigated to my device settings to fill all card details from app, after filling all the details subscription is purchased but am not navigated to my app and not able to get receipt of Payment when I open my app or resume it from background to foreground, How can I handle this scenario?
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
1. Clicked on Monthly plan from app then navigated to device settings to fill Card Details
2. Subscription Plan purchased Successfully
3. Pressed back button comes to Main Settings Screen
4. open App from Background

**Comment by hyochan** [comment]
Hi there 😃  This is exactly why I've redesigned `react-native-iap` from `v3` as [posted in the medium](https://medium.com/dooboolab/react-native-iap-v3-1259e0b0c017). And [here is live example](https://firebasestorage.googleapis.com/v0/b/cooni-ebee8.appspot.com/o/Github_iOS_iap_COONI_2018-12-17.mp4?alt=media&token=43ff6f97-d0e5-40c6-8e71-cdc914a8b1fc).

Well, I've managed to solve this situation by `purchaseUpdatedListener`. The `purchaseUpdatedListener` should fire when you comeback.

**Comment by Sneha1231** [comment]
@hyochan While app is in background this is working. In case I have force quit the app before entering the details in settings, then the transaction will be lost. How to cancel the initiated purchase when we force quit or send the app in background .https://github.com/dooboolab/react-native-iap/issues/1350
