### ISSUE TITLE
Payments using Gpay are not triggering purchaseUpdatedListener event

### ISSUE THREAD

**Issue by azharuddinkhan8898** [dooboolab/react-native-iap#1254]
### Version of react-native-iap
3.5.9

### Version of react-native
0.59.9

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
purchaseUpdatedListener event should trigger so that I can record the payment

### Actual behavior
purchaseUpdatedListener event is not getting triggered event after the payment

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by hyochan** [comment]
Can you verify that this only happend in `GPay`?

**Comment by azharuddinkhan8898** [comment]
> Can you verify that this only happens in `GPay`?

The issue is observed only on gpay.

**Comment by andresesfm** [comment]
Can you please try with the latest build of rn-iap? please re-open if this is still an issue
