### ISSUE TITLE
getSubscriptions(subs) gives blank array on iOS

### ISSUE THREAD

**Issue by avrutisavaliya-logistic** [dooboolab/react-native-iap#1255]
## ### Version of react-native-iap  
(5.2.7)

### Version of react-native 
(0.63.4)

### Platforms you faced the error (IOS or Android or both?) 
iOS

### Expected behavior

get subscriptions details

### Actual behavior

get blank array

### Tested environment (Emulator? Real Device?)

Real Device

**Comment by edersonfaccin** [comment]
i am with the same problem (android and ios)

**Comment by hyochan** [comment]
This mostly is a configuration issue. Please check the [readme in Q&A section](https://github.com/dooboolab/react-native-iap#getproducts-returns-empty-array).
