### ISSUE TITLE
getPendingPurchasesIOS doesn't return pending purchases after restart the app

### ISSUE THREAD

**Issue by zhekix** [dooboolab/react-native-iap#1257]
### Version of react-native-iap
5.2.3, 6.0.0-rc.19, maybe others too

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
getPendingPurchasesIOS return pending purchases after restart the app

### Actual behavior
getPendingPurchasesIOS doesn't return pending purchases after restart the app

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
buy product, not run 'finishTransaction' method, kill app, start app, check 'getPendingPurchasesIOS' response

**Comment by zhekix** [comment]
🙏  help wanted

**Comment by kukadiyaAni** [comment]
+1
