### ISSUE TITLE
Headers in not a constructor in ValidateReceiptIos and ValidateReceiptAndroid

### ISSUE THREAD

**Issue by avrutisavaliya-logistic** [dooboolab/react-native-iap#1258]
### Version of react-native-iap
(5.2.7)
### Version of react-native
(0.63.4)
### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
get Receipt Validation data
### Actual behavior
Error :- Headers in not a constructor
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
const result = await RNIap.validateReceiptAndroid(
                  purchases.packageNameAndroid,
                  purchases.productId,
                  purchases.purchaseToken,
                  token,
                  true,
                );

**Comment by hyochan** [comment]
Looks like `fetch` api has changed. Previously it didn't have any problem.
I updated it in `5.2.11`.

**Comment by avrutisavaliya-logistic** [comment]
Thank you22.02.2021, 19:28, "Hyo" <notifications@github.com>:
Looks like fetch api has changed. Previously it didn't have any problem.
I updated it in 5.2.11.
