### ISSUE TITLE
initConnection of undefined

### ISSUE THREAD

**Issue by maharleeeka** [dooboolab/react-native-iap#1260]
### Version of react-native-iap
5.2.11

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
No error and should initialize as expected

### Actual behavior
Shows the error messages below

![Image from iOS (1)](https://user-images.githubusercontent.com/15627208/108815168-f8193580-75ee-11eb-89a1-5dcb75052a2c.png) ![Image from iOS](https://user-images.githubusercontent.com/15627208/108815173-fa7b8f80-75ee-11eb-8998-65af962c7b41.png)![Image from iOS (2)](https://user-images.githubusercontent.com/15627208/108815172-f94a6280-75ee-11eb-8bf2-555c5f723cf5.png)

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

```
import RNIap from 'react-native-iap';

async componentDidMount(): Promise<void> {
      try {
        await RNIap.initConnection();
      } catch (err) {
        // handle err
      }
}

 componentWillUnmount(): void {
    if (this.purchaseUpdateSubscription) {
      this.purchaseUpdateSubscription.remove();
      this.purchaseUpdateSubscription = null;
    }
    if (this.purchaseErrorSubscription) {
      this.purchaseErrorSubscription.remove();
      this.purchaseErrorSubscription = null;
    }
    RNIap.endConnection();
  }
```

Thank you for any help.

**Comment by avrutisavaliya-logistic** [comment]
use for import this code import * as RNIap from 'react-native-iap';
