### ISSUE TITLE
Broken import after upgrading to 5.2.11

### ISSUE THREAD

**Issue by yanush** [dooboolab/react-native-iap#1261]
### Version of react-native-iap
5.2.11
### Version of react-native
0.63.4
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
import package successfully
### Actual behavior
imported package is undefined
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
Just trying to import the package `import RNIap from 'react-native-iap'` and then `RNIap.initConnection()` results in `ExceptionsManager.js:179 TypeError: Cannot read property 'initConnection' of undefined`
This is not happening after downgrading to 5.2.7

**Comment by hyochan** [comment]
Oppps I have exported that as a default. Sorry will fix it. Currently use destructured funtion from imports

**Comment by avrutisavaliya-logistic** [comment]
use this import * as RNIap from 'react-native-iap';

**Comment by hyochan** [comment]
Related  #1260 

Please use this way for now.
