### ISSUE TITLE
How to handle same Apple ID but different emails for subscriptions?

### ISSUE THREAD

**Issue by isonlaxman** [dooboolab/react-native-iap#1263]
### Version of react-native-iap
5.1.3

### Version of react-native
0.63

### Problem statement
I want to discuss a situation that may arise - a user subscribes to my app on Apple ID 'A' with email (app credentials) 'eA'. Then, their friend also tries to subscribe to my app with same Apple ID 'A' and email 'eB'. We don't want to let this happen, and want to show the second user an error and tell them to login with email 'eA'. 

### Attempted solutions
1. First, I used getAvailablePurchases to check if user has an active subscription to my app on their Apple ID. If they do, and they don't have a subscription on their current app credentials, I tell them to logout. However, this method causes the user to be prompted to Sign In, which is not a good experience for the user. Hence, I ditched this.
2. I then tried to use getPurchaseHistory to achieve the same goal. However, this method was super slow. Sometimes, getPurchaseHistory takes as long as 10 minutes, and then requestSubscription takes another ten minutes. This was true for both development version and testflight version of the app. We're yet to publish the app to AppStore so I can't talk about the performance in that environment.
3. Finally, I noticed that sometimes the rn-iap error update listener would be triggered when user tries to subscribe and they already have a subscription, but it doesn't always trigger.

### Help wanted with
Any of the following solutions would work for me:
1. Getting no sign-in prompt with getAvailablePurchases
2. Getting getPurchaseHistory to work faster
3. Getting an error more consistently in the error listener if user is already subscribed.

### Environment
Sandbox (development and testflight)

**Comment by hyochan** [comment]
Looks like this is great one to open up a discussion. May you create one here?
https://github.com/dooboolab/react-native-iap/discussions

Closing this issue since I'd like to organize an issue board on the bug only to manage the threads.
