### ISSUE TITLE
_reactNativeIap.default.initConnection undefined is not an object (Android)

### ISSUE THREAD

**Issue by sami3898** [dooboolab/react-native-iap#1264]
### Version of react-native-iap
react-native-iap: ^5.2.13

### Version of react-native
react-native: 0.63.3

### Platforms you faced the error (IOS or Android or both?)
Platform: Android

### Expected behavior
initConnection() must be initialize connection

### Actual behavior
getting error on run time "undefined undefined is not an object (evaluating '_reactNativeIap.default.initConnection')"

### Tested environment (Emulator? Real Device?)
Real Device: Samsung Galaxy M51 (Android 10)

### Steps to reproduce the behavior
=> import RNIap from react-native-iap
=> Add RNIap.initConnection() in componentDidMount()

**Comment by hyochan** [comment]
Related #1260 and #1261.

Please do `import * as RNIap from react-native-iap`
