### ISSUE TITLE
Request Subscription: The item you were attempting to purchase could not be found

### ISSUE THREAD

**Issue by simdanonline** [dooboolab/react-native-iap#1266]

**Comment by OlegPanfyorov** [comment]
We've faced the same issue 😔

**Comment by AlexSirenko** [comment]
Same here

**Comment by iMJumpmxn** [comment]
+1

**Comment by ilysander** [comment]
same problem, any update?

**Comment by hyochan** [comment]
Have you gone through [Q&A section in the readme](https://github.com/dooboolab/react-native-iap#q--a)? Currently, there is some issues in integration on `iOS` which can be solved using storekit.

![image](https://user-images.githubusercontent.com/27461460/117569534-17f5cb00-b101-11eb-9b19-eaa680856211.png)
