### ISSUE TITLE
how to validate if a user buy a product and change his device.. 

### ISSUE THREAD

**Issue by hafeez-ullah-khan** [dooboolab/react-native-iap#1268]
how to check if a user purchased a product ..but later on he/she change his/her phone  and in that case how to validate that he/she already purchased  or not from his new phone?

**Comment by codal-hkrishnani** [comment]
@hafeez-ullah-khan for that you need to keep track of your purchases in your own server, for iOS you may validate without server by using this method **validateReceiptIos** 
But having your own Server is recommended

**Comment by indapublic** [comment]
when iphone is changed, appleid should be same. are you asking about products or subscriptions?

**Comment by hafeez-ullah-khan** [comment]
> @hafeez-ullah-khan for that you need to keep track of your purchases in your own server, for iOS you may validate without server by using this method **validateReceiptIos**
> But having your own Server is recommended

i have only one product, and how can i validate that in android? if the the userer purchased that product, but later on he change his phone ,at that time how to check if the user has purchased or not?

**Comment by hafeez-ullah-khan** [comment]
> when iphone is changed, appleid should be same. are you asking about products or subscriptions?
i am asking about product, and plateform is for now android?

**Comment by hyochan** [comment]
Yes @codal-hkrishnani is right. Logically, you need to match with some unique userId so that the purchased items can be tracked.
