### ISSUE TITLE
requestSubscription iOS not resolved and purchaseUpdatedListener not triggered

### ISSUE THREAD

**Issue by raienko** [dooboolab/react-native-iap#1269]
### Version of react-native-iap
reproduced on: 5.1.1, 5.2.13, 5.2.14
### Version of react-native
0.63.4
### Platforms you faced the error (IOS or Android or both?)
iOS, Android
### Expected behavior
Receive receipt as a result of following call:
```const receipt = await RNInApp.requestSubscription(productId, false);```
Or at least in `purchaseUpdatedListener`.
### Actual behavior
Promise not resolved:
```
console.log('Everything ok');
const receipt = await RNInApp.requestSubscription(productId, false); // Purchase popup shown and purchased successfully
console.log('This console.log never triggered on iOS');
```
And `purchaseUpdatedListener` not triggered at all.
### Tested environment (Emulator? Real Device?)
iOS 14.4, 13.3. Both - emulator (StoreKit) and real device debug and testFlight builds
### Steps to reproduce the behavior
No specific steps.
Everything worked fine 2-3 weeks ago. Previous app release works fine as well.
But now in-app purchases flow broken on new builds.
`purchaseUpdatedListener` not triggered at all on `both` platforms.
Requests wrapped in `try / catch` but no errors caught.

For android we receive receipt as result of `requestSubscription` call.
For iOS `requestSubscription` promise never resolved.

Our backend receives events from store as it should be, native purchase popup appears and works as expected.
But can't get `receipt` anyhow.

P.S Added `clearTransactionIOS` before purchase, but it didn't help.

**Comment by OlegPanfyorov** [comment]
We've faced exactly the same issue! @hyochan Help, please 🙏

**Comment by hyochan** [comment]
I am recently making a new example [here](https://github.com/hyochan/dooboolab.com/blob/master/src/components/pages/Sponsor.tsx), and have not yet faced any problem.

Actually, I am a bit frustrated when I get these reports because actually, this wasn't reproducible at all in my case. Hope more people reach here and try to investigate the problem.

**Comment by raienko** [comment]
@hyochan managed to resolve issue, hard to say which step helped.

Did following:

0. `cleaned all cache` (xcode, node_modules, pods)
1. upgraded from `5.1.1` to `5.2.14`
2. added `clearTransactionIOS` before new purchase
3. trigger `initConnection` right after app launch
4. added extra checks to prevent any lib requests if `initConnection` not yet triggered or returned `false` value
5. new sandbox users
