### ISSUE TITLE
undefined is not an object evaluating reactNative_Iap.default.requestSubscription

### ISSUE THREAD

**Issue by Sandeep155Vibhuti** [dooboolab/react-native-iap#1270]
### Steps to reproduce the behavior

Any help would be appreciated .Issue arise after updating react-native-iap to 5.2.14 from react-native-iap 3.3.7

**Comment by Roopal78** [comment]
I am getting Same Issue on iOS

**Comment by Duya3fithou** [comment]
try `import * as RNIap`

**Comment by Roopal78** [comment]
> try `import * as RNIap`

Thanks this works for me @Duya3fithou

**Comment by grantgeorge** [comment]
This should be flagged as a breaking change in my opinion

**Comment by RimApp** [comment]
@Duya3fithou 
Works for me thank you !

**Comment by Sandeep155Vibhuti** [comment]
@Duya3fithou
Works for me too thank you !
