### ISSUE TITLE
[v6] Require cycle warning

### ISSUE THREAD

**Issue by betoharres** [dooboolab/react-native-iap#1271]
### Version of react-native-iap
react-native-iap@^6.0.0-rc.23

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
Android - ios not tested

### Expected behavior
no warning

### Actual behavior
warning showing

### Tested environment (Emulator? Real Device?)
emulator

### Steps to reproduce the behavior
Run command `yarn add react-native-iap@next && yarn android`

Similar to this issue: https://github.com/joltup/rn-fetch-blob/issues/183

![Screenshot_1615228147](https://user-images.githubusercontent.com/1681530/110365322-a8d9f880-8023-11eb-8ba4-a5ce9d9540eb.png)

**Comment by hengkx** [comment]
same

**Comment by hyochan** [comment]
Found https://stackoverflow.com/questions/55664673/require-cycles-are-allowed-but-can-result-in-uninitialized-values-consider-ref.

I'll hopefully look into this.

**Comment by Beyazatli** [comment]
If anyone interested, i found a solution. 👇👇👇
If you do not have to use version 6.0, you can get rid of this error by downgrading the version to the previous version (5.2.13).

**What need do you do?**
Just re-install package. 🙄

Firstly;
`npm uninstall react-native-iap`

And then;
`npm install --save react-native-iap@5.2.13`

If you follow these steps, your problem will be resolved. 🥳
Best regards.
