### ISSUE TITLE
[V6] How to mock this library?

### ISSUE THREAD

**Issue by betoharres** [dooboolab/react-native-iap#1273]
Hey, thanks for the hard work on this library, I just installed and I'm trying to use it.
After I installed, I tried to run the project specs and the component using this library is failing the snapshot test. I think that's because I didn't mock this library.
I already tried myself doing something like this but didn't work:
```
__mocks__/react-native-iap.js

const iap = {
  useIAP: jest.fn(() => {
    return {
      getSubscriptions: jest.fn(),
    }
  }),
}

export default iap
```
can someone help me? I'm not sure what to do

### Version of react-native-iap
react-native-iap@^6.0.0-rc.23

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
Jest

### Expected behavior
Run test successfully

### Actual behavior
throwing this error when I add `useIAP` hook
```
    TypeError: (0 , _reactNativeIap.useIAP) is not a function
     11 | export default function UpgradePro({navigation}) {
     12 |   const {getSubscriptions} = useIAP()
```

### Tested environment (Emulator? Real Device?)
jest

### Steps to reproduce the behavior
install the library on your react native project
add to your component 
try to run a jest test

**Comment by hyochan** [comment]
Try to watch the sample here.

https://github.com/hyochan/dooboolab.com/blob/master/__mocks__/react-native-iap.ts

Feel free to tell me if you need additional assists :)

**Comment by betoharres** [comment]
Thanks a lot @hyochan it worked flawlessly! Awesome job on the library btw!

**Comment by LcsGrz** [comment]
> Try to watch the sample here.
> 
> https://github.com/hyochan/dooboolab.com/blob/master/__mocks__/react-native-iap.ts
> 
> Feel free to tell me if you need additional assists :)

@hyochan, where i can find the solution?

**Comment by curthipster** [comment]
@LcsGrz here's what I'm doing in my jest setup file:

```
jest.mock('react-native-iap', () => ({
  useIAP: {
    connected: true,
    getProducts: jest.fn(),
    getSubscriptions: jest.fn(),
    products: [],
    subscriptions: [],
  },
  withIAPContext: jest.fn((fxn) => fxn),
  purchaseErrorListener: jest.fn(),
  purchaseUpdatedListener: jest.fn(),
  setup: jest.fn(),
}));
```
