### ISSUE TITLE
user canceled payment but the payment proceeded

### ISSUE THREAD

**Issue by Shrayyef** [dooboolab/react-native-iap#1274]
### Version of react-native-iap
5.2.0
### Version of react-native
0.62.2
### Platforms you faced the error (IOS or Android or both?)
iOS 
### Expected behavior
payment should be canceled
### Actual behavior
payment proceeded purchaseUpdatedListener gave a receipt and it was successfully validated on the server
### Tested environment (Emulator? Real Device?)
Real device

https://user-images.githubusercontent.com/7762079/110717615-72b29980-821a-11eb-9d38-298e7e14f3dd.MP4

**Comment by hyochan** [comment]
@Shrayyef Could you verify that this still occurs in the recent version? I've not had this case testing the recent ones neither the previous ones (curious 🤔 )
