### ISSUE TITLE
OFFER CODE redemption does not get captured, iap does not get a response(IOS & Android) (How to know which user redeemed the code???)

### ISSUE THREAD

**Issue by jkz27** [dooboolab/react-native-iap#1276]
**Version of react-native-iap**
5.2.0

**Version of react-native**
0.63.4

**Scenario:**

My RNIAP is currently working on both platforms with no problem with an auto-renewing subscription where the initial purchase is caught in the event listener where I have both my user's Id and the purchase Receipt where I can give the correct use the subscription, I have also set up Server to Server Notification.

However, after redeeming the offer code, the purcahseEventlistener **DOES NOT** seem to capture the purchase! 

When the user redeems the code on IOS: 

1. What I am currently doing is mask the redemption URL (redeemURL + offer code) inside the app, when the user enters the correct code, it opens the redemption URL for them, so they just need to hit the redeem button.

- I tried this on test flight (apparently offer code can only be tested in production), the code is redeemed and added to my real app account, BUT the app **DOES NOT** capture the redemption!

2. I have also tried the method presentRedemptionIOS() method, which directs me to the app store and asks me to put in the code, then it lets me redeem the code, but again the app **DOES NOT** capture the redemption!

Suspect Problem: The redemption process is outside the app (inside the app store), and the event listener does not see it as a "purchase"

**Problem:**

**So there are currently no way for me to know which user redeemed subscriptions (No way to link the userId with the originalTransactionIOSId) and I should give them the upgraded status, the server to server notification sends me information regarding to this redemption purchase but also offers me no information on who has made this purchase.....**

On the Android side, the redemption process is a bit different, I will update more when I have more information on the Android, but the same concern exists that the purcahseEventLisener might not catch the purcahse.

I tried looking around online, but there seem to be very limited source on this topic.

**Help Wanted**
How do people go about engineer their promo-code for auto-renewable subscriptions...?

Any advice would be greatly appreciated, and if this is an issue other people have experienced as well?  @hyochan 

**Environment**
TestFlight (OfferCode on IOS only work on testflight)

Side Note: I have checked #400, #450 it seems like that issue has not been resolved

**Comment by jkz27** [comment]
Custom Code (Redemption in app) works on android, but I don't know if it will capture the purchase outside of the app

**Comment by hyochan** [comment]
@jkz27 I hope you can post this in [Discussion](https://github.com/dooboolab/react-native-iap/discussions) to handle further.
