### ISSUE TITLE
Logic of understanding cancelled or expired subscription to undo premium features 

### ISSUE THREAD

**Issue by ugrdursun** [dooboolab/react-native-iap#1280]
Hello,

Firstly, thanks for this beautiful library! Forgive me if i miss this on the docs because i am so confused and want to know how this job is done.

My question is: After a succesfully subscription, how we should understand user cancelled subscription or expired etc. to take premium features back ? 

If you going to say **check on every app start with getAvailablePurchases()** function, then what is **Restore Purchases** for ? (On the docs we restore purchases with getAvailablePurchases() too)

**Or is there an other proper way to check is subscription active or not ?**

I am trying to understand the logic behind this, Thanks for reading and assist.

**Comment by ixuz** [comment]
You should setup an endpoint in your server to receive and handle notifications from app store/google play..

See the following references:
- https://developer.android.com/google/play/billing/rtdn-reference#sub
- https://developer.apple.com/documentation/appstoreservernotifications

**Comment by ugrdursun** [comment]
> You should setup an endpoint in your server to receive and handle notifications from app store/google play..
> 
> See the following references:
> 
> * https://developer.android.com/google/play/billing/rtdn-reference#sub
> * https://developer.apple.com/documentation/appstoreservernotifications

Thanks for answer.

What is the disadvantage of doing "check on every app start with getAvailablePurchases()" instead of this ?

Plus, lets assume a user subscribed for 1 month and cancelled at 20th day, so he got 10 more premium days. getAvailablePurchases returns a json in that 10 days, after 10 days it returns null so we can understand subscription is active or not  by return.

How is the way you suggested handles this scenario ?

**Comment by ixuz** [comment]
By handling server notifications, your server is notified immediately when the user's subscription changes in any way.

In your example, your server would be notified exactly when the user cancels their subscription, and you can perform the appropriate action (not having to wait until they open the app).

**Comment by ugrdursun** [comment]
> By handling server notifications, your server is notified immediately when the user's subscription changes in any way.
> 
> In your example, your server would be notified exactly when the user cancels their subscription, and you can perform the appropriate action (not having to wait until they open the app).

Thanks a lot for your explanation :) No lies, checking on app launches seemed easier to me :\

**Comment by SrBrahma** [comment]
> By handling server notifications, your server is notified immediately when the user's subscription changes in any way.
> 
> In your example, your server would be notified exactly when the user cancels their subscription, and you can perform the appropriate action (not having to wait until they open the app).

Do you have any open code for this server handling? I will do it in Cloud Functions, but the code may be using any platform
