### ISSUE TITLE
[Android] invalid orderID

### ISSUE THREAD

**Issue by heekyu-pu** [dooboolab/react-native-iap#1281]
### Version of react-native-iap
5.2.7

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
valid order ID

### Actual behavior
invalid order ID
VALID : GPA.1111-1111-1111-11111
**INVALID : 5695468975122650103.5506614023640432**

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Cannot reproduce.
Some users have this problem

**Comment by dimaischenko** [comment]
Have the same issue

**Comment by heekyu-pu** [comment]
@dimaischenko Nope. this error occurs everyday.

**Comment by dimaischenko** [comment]
@heekyu-pu It's interesting that after getting this invalid `orderID` there is no any payment and orders in Google Play Console. But `receipt` have all needed other fields, purchasToken, names e.t.c. Have you tried updating to react-native-iap 6.2.0 version?

**Comment by dimaischenko** [comment]
@heekyu-pu May be it's fraud and fake purchases. I read that some soft like `Lucky Patcher` can generate fake purchases with `orderId` without `GPA.`

**Comment by dimaischenko** [comment]
Yeah, #460 have the same situation. It's `lucky patcher` hack tool

**Comment by andresesfm** [comment]
Thank you for the information, will close as per the discussion doesn't seem to be a problem with the library itself

**Comment by Desintegrator** [comment]
same issue
all invalid tokens are without GPA. and with "." instead of "-" separation
