### ISSUE TITLE
how to check if the subscription is active?

### ISSUE THREAD

**Issue by rogerdribeiro** [dooboolab/react-native-iap#1282]
My app only has subscriptions. I want to check if the user's subscription is still active.

Can I use the getAvailablePurchases method for this?
If a subscription is canceled before the end date. Will this method return it?
And after the end of the subscription period, does the method return it?

To keep only active users using the premium version, I thought about checking with this method periodically, like every 10 days. or storing the end date of the user's existing subscription, in the storage and run only after this date.
Would that be a viable way?

**Comment by ixuz** [comment]
See my comments at this issue: https://github.com/dooboolab/react-native-iap/issues/1280

**Comment by hyochan** [comment]
You can see the sample [source code in my repo](https://github.com/hyochan/dooboolab.com/blob/5805e020139785ced8f0666234a136b878b8be2a/src/components/pages/Sponsor.tsx#L62-L110).
