### ISSUE TITLE
It won't update the product information after changing it in the store

### ISSUE THREAD

**Issue by InsideT** [dooboolab/react-native-iap#1283]
### Version of react-native-iap
6.0.1

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Update product information.

### Actual behavior
It won't update with the newest information of the product.

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

Retrieve the products and subscriptions 
```
const skus = ["test_sku"];
let products = [];
const subscription = await RNIap.getSubscriptions(skus);
products = await RNIap.getProducts(skus);
products.push(subscription[0]);
```

Then change the information of your product.

**Comment by hyochan** [comment]
I also want to investigate this further. Could you kindly share this in [Discussion](https://github.com/dooboolab/react-native-iap/discussions) to open discussion? I'll close this issue.
