### ISSUE TITLE
Could not download billing-3.0.0.aar (com.android.billingclient:billing:3.0.0)

### ISSUE THREAD

**Issue by alejo90103** [dooboolab/react-native-iap#1284]
### Version of react-native-iap
6.0.0
### Version of react-native
0.62
### Platforms you faced the error (IOS or Android or both?)
Android
### Actual behavior
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not download billing-3.0.0.aar (com.android.billingclient:billing:3.0.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/billingclient/billing/3.0.0/billing-3.0.0.aar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/billingclient/billing/3.0.0/billing-3.0.0.aar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by hyochan** [comment]
Could you try our recent version and come back? I Will close it for now only there is anything new.
