### ISSUE TITLE
react native iap should be always active?

### ISSUE THREAD

**Issue by Piero87** [dooboolab/react-native-iap#1286]
Hello,
I'm trying to implement you great library in my project, I have an architectural doubt, the purchaseUpdatedListener should be always active in the application? or con be added in a component that it's mounted only when I open the page to buy subscriptions?

Thank you for all your work

**Comment by Mkassabov** [comment]
We have ours in a custom hook that makes it only available in components that call that hook. I know it doesn't necessarily answer your question, but it leads me to believe that running it directly in a component would be no issue

**Comment by hyochan** [comment]
I'd recommend to `init` the iap service only when you need the purchase the occur.
