### ISSUE TITLE
TypeScript signature (or implementation) of getPromotedProductIOS is wrong

### ISSUE THREAD

**Issue by ngocdaothanh** [dooboolab/react-native-iap#1287]
Version of react-native-iap: 6.0.1

The signature:

```ts
export declare const getPromotedProductIOS: () => Promise<Product>;
```

But at runtime, the actual result is simply a string.

**Comment by hyochan** [comment]
Could you kindly push a `PR` for current typo?

**Comment by andresesfm** [comment]
Fixed here:
https://github.com/dooboolab/react-native-iap/pull/1393

**Comment by andresesfm** [comment]
merged
