### ISSUE TITLE
Payment sandbox environment

### ISSUE THREAD

**Issue by sz3jdii** [dooboolab/react-native-iap#1289]
### Version of react-native-iap
    "react-native-iap": "^6.0.0-rc.23",

### Version of react-native
    "react-native": "0.64.0",

### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
I can test the payment process
### Actual behavior
App forces me to use real card
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
  Run ` requestPurchase('SKU_ID')`

Hello,
when I run `requestPurchase('SKU_ID')` method Google Pay shows with valid price but I cant test if it's going ok because of need to input the valid credit/debit card. I'm newbie in react native but as far as I understand in DEV environment, on emulator which is logged in with invited tester account, the expected behaviour is to pass the payment without need of transfering real money.
What am I doing wrong?

**Comment by steven-sh** [comment]
I think you need to add the Google account you're logging with on the emulator to the "License Testing" list in the Google Play console (it's under 'Settings').

**Comment by sz3jdii** [comment]
Thank you! that's correct :) it works now.
