### ISSUE TITLE
Any built-in way to deep link to corresponding subscription section in store?

### ISSUE THREAD

**Issue by SrBrahma** [dooboolab/react-native-iap#1293]
Google recommends this: https://developer.android.com/google/play/billing/subscriptions#deep-link

I am thinking to add it to my app. Does this package have a built-in way to do it?

**Comment by steven-sh** [comment]
I just use the React Native 'Linking' library and call it like this:

`Linking.openURL('https://play.google.com/store/account/subscriptions?package=com.my.package&sku=mySKU');`

**Comment by SrBrahma** [comment]
> I just use the React Native 'Linking' library and call it like this:
> 
> `Linking.openURL('https://play.google.com/store/account/subscriptions?package=com.my.package&sku=mySKU');`

Thanks, will try it out. Do you think it should be integrated in the iap package? I could make a PR to add it.

**Comment by hyochan** [comment]
@SrBrahma Since this is just an extra functionality that doesn't need additional installation, `PR` would be nice.

**Comment by andresesfm** [comment]
Implemented here: https://github.com/dooboolab/react-native-iap/pull/1394 credit to @steven-sh

**Comment by andresesfm** [comment]
Merged
