### ISSUE TITLE
How to correctly finish transaction for Apple subscription?

### ISSUE THREAD

**Issue by indapublic** [dooboolab/react-native-iap#1295]
### Version of react-native-iap

4.6.3

### Version of react-native

0.63.4

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Transaction should be finished and appeared in My subscriptions

### Actual behavior

No errors but subscription is not appeared

### Tested environment (Emulator? Real Device?)

Real Device, production mode

### Steps to reproduce the behavior

```
await RNIAP.initConnection()
RNIAP.clearProductsIOS()
const products = await RNIAP.getProducts([productId])
RNIAP.purchaseUpdatedListener(async (purchase) => {	
	// Checking for prod mode first
	let result = await RNIAP.validateReceiptIos({
		"receipt-data": purchase.transactionReceipt,
		"password": env.IOS_IAP_SECRET,
	}, false)
	// Then for sandbox mode
	if (result.status === 21007) {
		result = await RNIAP.validateReceiptIos({
			"receipt-data": purchase.transactionReceipt,
			"password": env.IOS_IAP_SECRET,
		}, true)
	}
	if (result.status !== 0) {
		return
	}
	RNIAP.finishTransaction(purchase, true)
})
RNIAP.purchaseErrorListener(error => {
	reject(error)
})

return RNIAP.requestSubscription(productId, false)
```

**Comment by PazuC10** [comment]
I have the same problem!
I use RNIAP.finishTransaction(purchase) after the receipt checking
everything works until i use getPurchaseHistory() / getAvailablePurchase()
when i use the above functions, clicking the subscription button become checking the old receipt validation, instead of showing the purchase

**Comment by Ulisses1478** [comment]
I think you shouldn't be doing the validation in the client side if the user try to intercept the requests with a proxy and override the IOS_IAP_SECRET by Reverse engineering your app this should give premium access or features with a very simple atack

**Comment by indapublic** [comment]
Hi @Ulisses1478 Thanks for your answer, but my question was different. In real life backend checks receipt.

**Comment by PazuC10** [comment]
please check my repy on other question
[#1312](https://github.com/dooboolab/react-native-iap/issues/1312#issuecomment-869145788)
hope this can help you

**Comment by indapublic** [comment]
@PazuC10 What's your version? Your code is almost same as mine

**Comment by PazuC10** [comment]
> @PazuC10 What's your version? Your code is almost same as mine

iap: 6.0.2,
react-native: 0.64.0
