### ISSUE TITLE
React-native ios subscription issue

### ISSUE THREAD

**Issue by vickypathak123** [dooboolab/react-native-iap#1297]
"react-native-iap": "^6.0.1",

"react-native": "~0.63.4",

In the ios when I click on the purchase button the first time then subscription dialog not open whenever I'm click on second time it's work fine

It's not proper work

First time, not open subscription dialog

i'm check in real device

Please follow above mention step

**Comment by Ulisses1478** [comment]
Yeah, with me too but is not a bug is simply because the subscription is already made and the time for some reason is not reduced. Probably just canceling go to config -> appstore -> sandbox or something like this and try to find something that cancel and say here if it worked

**Comment by jakobwak** [comment]
Same with my project. In the settings, mentioned by Ulisses1478, there is shown that the subscription is expired. But it's the same behaviour as described by the originator. This is the error, which is thrown: [Error: Product already purchased, if not returned in the active products it may be owned by a different user (restore needed)] . I am using "react-native-iaphub@^6.2.0", which is building up on this library.
