### ISSUE TITLE
Is it possible to implement a free trial period in iOS with react-native-iap

### ISSUE THREAD

**Issue by tanoto-the-explorer** [dooboolab/react-native-iap#1299]
Hi, I read few threads on this repo about my question and read the README.md but I can't find any concrete answer. I want to implement a 30 day trial period and then charge user after that, is this possible with react-native-iap?

**Comment by pm-moritz** [comment]
Hey @tanoto-the-explorer could you solve your problem, and if so can you please provide any solutions? Thanks in advance!
