### ISSUE TITLE
purchaseUpdatedListener not called until restart on iOS

### ISSUE THREAD

**Issue by JeroenVanSteijn** [dooboolab/react-native-iap#1300]
### Version of react-native-iap

6.0.2

### Version of react-native

0.62.2

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

purchaseUpdateListener to be called quite soon after purchase of a subscription

### Actual behavior

purchaseUpdateListener only called after restarting the app

### Tested environment (Emulator? Real Device?)

Real device, in test flight and through xcode

### Steps to reproduce the behavior

1. setup code like this:

```
    useEffect(() => {
        RNIap.initConnection()
            .then(() => {
                getSubscriptions(subSkus);
                RNIap.purchaseUpdatedListener(
                    (
                        purchase:
                            | RNIap.InAppPurchase
                            | RNIap.SubscriptionPurchase
                            | RNIap.ProductPurchase
                    ) => {
                        const receipt = purchase.transactionReceipt;
                        if (Platform.OS === "ios" && purchase.transactionId) {
                            verifyReceipt(
                                receipt,
                                purchase.productId,
                                navigateToSucces
                            );
                            RNIap.finishTransactionIOS(purchase.transactionId);
                        } else if (
                            Platform.OS === "android" &&
                            purchase.purchaseToken
                        ) {
                            verifyReceipt(
                                purchase.purchaseToken,
                                purchase.productId,
                                navigateToSucces
                            );
                            RNIap.acknowledgePurchaseAndroid(
                                purchase.purchaseToken
                            );
                        } else {
                            Sentry.captureException(
                                `PurchaseListener could not recognize platform: ${Platform.OS}`
                            );
                        }
                    }
                );
            })
            .catch(Sentry.captureException);
        return () => {
            RNIap.endConnection();
        };
    }, []);
```

2. purchase subscription
3. observe that purchase listener (and thus verifyreceipt) is not called
4. Restart the app
5. observe that verifyreceipt is called

**Comment by hyochan** [comment]
Could you `expose` how `verifyReceipt` looks like? I can't see how it isn't working.

**Comment by JeroenVanSteijn** [comment]
@hyochan verifyReceipt is a redux function that calls our server separately. But it never gets called (not even `const receipt = purchase.transactionReceipt;` gets called) so it shouldn't be relevant. For now I added the purchase listener in the component instead of in App.tsx. My guess is that I am initializing this too early in App.tsx for some other process, (even after initconnection I guess), and therefor it does work when it's in the component instead.
