### ISSUE TITLE
Getting Error While calling getProducts: "Google is indicating that we have some issue connecting to payment."

### ISSUE THREAD

**Issue by rajtejani** [dooboolab/react-native-iap#1305]
It was working before but somehow suddenly it started giving an error.
### This is my code
```
 try {
      const result = await RNIap.initConnection();
      const products = await RNIap.getProducts(itemSkus);
    } catch (err) {
      console.log('RNIap err====>>>', err);
    }
```

### Version of react-native-iap
4.5.2
### Version of react-native
0.61.2

### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
To get product SKUs without errors

### Actual behavior
Getting Error 
**Android Logcat:** ``` W/BillingClient: getSkuDetails() failed. Response code: 5```
**Js console:**
```
   RNIap err====>>> Error: Google is indicating that we have some issue connecting to payment.
    at Object.fn [as getItemsByType] (VM4 index.bundle:4791)
    at VM4 index.bundle:243003
    at step (VM4 index.bundle:242794)
    at Object.next (VM4 index.bundle:242724)
    at VM4 index.bundle:242696
    at tryCallTwo (VM4 index.bundle:27347)
    at doResolve (VM4 index.bundle:27511)
    at new Promise (VM4 index.bundle:27370)
    at __awaiter (VM4 index.bundle:242675)
    at android (VM4 index.bundle:242997)
```

### Tested environment (Emulator? Real Device?)
Both

**Comment by hyochan** [comment]
Current issue loos like a configuration issue. Also please try the recent version of `react-native-iap`.

Related #1308
