### ISSUE TITLE
[TypeError: null is not an object (evaluating 'RNIapModule.getInstallSource')]

### ISSUE THREAD

**Issue by yasikrehman** [dooboolab/react-native-iap#1306]
### Version of react-native-iap
6.0.2
### Version of react-native
0.61
### Platforms you faced the error (IOS or Android or both?)
Android only 
### Expected behavior
if we use RNIap.initConnection() function, app should be connected.  
### Actual behavior
But it displays as [TypeError: null is not an object (evaluating 'RNIapModule.getInstallSource')]
### Tested environment (Emulator? Real Device?)
Real Device

**Comment by hakeemsyd** [comment]
+1

**Comment by iamsydali** [comment]
+1

**Comment by yasikrehman** [comment]
Linking is not working properly,thats the issue.
