### ISSUE TITLE
How to debug the code on Android for in app purchase?

### ISSUE THREAD

**Issue by pbade123** [dooboolab/react-native-iap#1307]

**Comment by jessicazu** [comment]
I'd like to know, too. Right now, I'm working on a test version uploaded to the store to see how it works.

**Comment by hyochan** [comment]
Are you asking that you want to know how to debug our native modules in your app?

**Comment by andresesfm** [comment]
This is the documentation on how to test: https://developer.android.com/google/play/billing/test . please open a discussion if more questions (or post on stackoverflow)
