### ISSUE TITLE
{"code": "E_DEVELOPER_ERROR", "debugMessage": "", "message": "Google is indicating that we have some issue connecting to payment.", "responseCode": 5}

### ISSUE THREAD

**Issue by EasonWang01** [dooboolab/react-native-iap#1308]
### Version of react-native-iap
5.0.1
### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
Android 
### Expected behavior
Using `IapExample` and change product Id to the my custom product on the android play console
### Actual behavior
```
{"code": "E_DEVELOPER_ERROR", "debugMessage": "", "message": "Google is indicating that we have some issue connecting to payment.", "responseCode": 5}
```
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
I try to change the build version to match the android store's app version and also running it using `npx react-native run-android --variant=release` but still got this error.

I also facing the same problem using another module, so is it because of the wrong build version, or need to sign the app using the release key?

https://developer.android.com/google/play/billing/billing_reference.html

**Comment by dinhnhatbang** [comment]
Try this:
```
6. Test account(s) is added in developer console.
....
3. Test account (not developer) - is the main account on the device. (Main account might be not necessary - according to @MinosL comment)
```
https://stackoverflow.com/questions/11068686/this-version-of-the-application-is-not-configured-for-billing-through-google-pla

**Comment by EasonWang01** [comment]
Cool, it works thanks!
