### ISSUE TITLE
Why does this lib haven't subscription a product with a specified quantity?

### ISSUE THREAD

**Issue by letruonglamit** [dooboolab/react-native-iap#1309]
Let's me see in the "requestPurchaseWithQuantityIOS(sku: string, quantity: number)" function have a quantity field. I am using the "requestSubscription" function for auto-renew but this function don't have "quantity" input. 
So can I use "requestPurchaseWithQuantityIOS" function for auto-renew subscription?

![image](https://user-images.githubusercontent.com/22797715/115815287-e1d9fb00-a420-11eb-9448-c25e3d634077.png)
![image](https://user-images.githubusercontent.com/22797715/115815226-ca027700-a420-11eb-8f55-927d2d2e3e6d.png)

**Comment by hyochan** [comment]
If I remember correctly, yes you can.
