### ISSUE TITLE
Interrupt Purchases (terms & conditions acceptance) return E_UNKNOWN error

### ISSUE THREAD

**Issue by venux92** [dooboolab/react-native-iap#1311]
I'm getting an `E_UNKNOWN` error when I have my tester set to Interrupt purchase
```
purchaseErrorSubscription = purchaseErrorListener(
   (error: PurchaseError) => {
       console.log(error)
  },
)
```

### Version of react-native-iap
6.0.2

### Version of react-native
0.64.0

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Get the correct error.
I can see from [index.ts](https://github.com/dooboolab/react-native-iap/blob/d067d5181ec6a976b39f8345acb14d28805d4d4f/index.ts)
There is `E_DEFERRED_PAYMENT',` and `E_NOT_ENDED` maybe more adapted

Unless there is a better way to handle this case where the user needs to accept the agreement before pursuing his payement.

### Actual behavior
I have a **subscription** product
I'm getting `{"code": "E_UNKNOWN", "debugMessage": "An unknown error occurred", "message": "An unknown error occurred", "productId": "xxxxxxxx", "responseCode": "0"}`

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Go to Apple Connect -> Users and Access -> Testers then select a user and
![image](https://user-images.githubusercontent.com/20675272/115994753-99d2f800-a61b-11eb-9268-504fb367e8e1.png)

Try a payment, once the Apple Agreement is displayed the `error` will be thrown

**Comment by antoinesaliba** [comment]
has anyone figured out a way around this? Seems like even if the user agrees to the terms & conditions, the purchaseUpdatedListener isn't triggered even though the transaction is successful.

**Comment by Great-hijack** [comment]
This issue blocks my app from passing the Apple review.

**Comment by ahmetkuslular** [comment]
I have the same problem too!

**Comment by mikeportanova** [comment]
Did anyone resolve this?

**Comment by ahmetkuslular** [comment]
> Did anyone resolve this?

All tax information needs to be entered and approved by apple. Also, it cannot be tested on the simulator. There is no problem with real device.

**Comment by RuiSoares** [comment]
Hi! Does anyone have news on this issue? If not how are you saving the purchase when the user has agreed to the terms and conditions? Since the listener won't catch it.
Do you just show an error and then the user needs to tap a restore button to get the purchase to the backend?

Also is it only me getting a "Cannot connect" with a non-working "Retry" button in the sandbox/testflight Terms and Conditons modal after updating to iOS 15.4? (I assume it's a bug from apple)

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1921

**Comment by andresesfm** [comment]
10.0.5 has been published with the fix
