### ISSUE TITLE
Payment flow does not trigger after subscription auto-renewal expires

### ISSUE THREAD

**Issue by wy1024** [dooboolab/react-native-iap#1312]
### Version of react-native-iap
6.0.2

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
ios

### Expected behavior
After subscription auto-renews for 6 times, the subscriptions expires. When the user tries to purchase the subscription again, the payment flow should trigger.

### Actual behavior
Payment modal does not show up, instead, purchaseUpdatedListener is called directly with expired list of receipts.

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
- User purchases auto-renewal subscription
- Subscription auto-renews and expires after 6 renews
- User attempts to purchase the subscription again
- Apple payment modal doesn't show up, and code jumps to line
```
const receipt = purchase.transactionReceipt;
```

Here's the code
```
    await initConnection();
      const prods = await getProducts([productId]);
      const sub = await requestSubscription(productId, false);
      flushFailedPurchasesCachedAsPendingAndroid()
      .then(() => {
        this.purchaseUpdateSubscription = purchaseUpdatedListener(
          async (
            purchase: InAppPurchase | SubscriptionPurchase | ProductPurchase,
          ) => {
            const receipt = purchase.transactionReceipt;

            if (receipt) {
              // validate receipt
             ...
            }
      }
}


```

**Comment by TfADrama** [comment]
This is happening to me as well but I'm using hooks, i thought it would be the hook implementation, but it's apparently.
@wy1024 did you find a solution?

For me, the purchase flow for that item only triggers again after i buy another item.

**Comment by wangjaso** [comment]
@TfADrama No I haven't found a solution yet, I wonder if this is different in prod. But so far in sandbox, buying the same subscription would auto fail.

**Comment by PazuC10** [comment]
I have this problem too!
My code:
1. subscription trigger listener
2. listener get the receipt and send to backend do the logic
3. when the backend finish the job, call finishTransaction()

After 6 renewals, the item on pendingPurchase increase by 6
Apple payment modal doesn't show up in clicking subscription until i click 7 times subscription  to finish all transaction

**Comment by lc3t35** [comment]
Same problem with SDK42, rn-iap 7.3.0. It's not clear how to solve this : I need a sandbox to work to validate before submission.
On ios, in `await IAP.finishTransaction(purchase, false, '')` -> false is useless, only used by android.

**Comment by nes123** [comment]
Works on android but await IAP.finishTransaction(purchase, false, '') just waits forever on IOS

**Comment by chvik** [comment]
I think it's a critical issue. Even though users can renew their expired subscriptions in Settings, an App Store reviewer could start reviewing the app submission by using a sandbox account that already has one or more expired subscription purchases. In this case the payment popup wouldn't be shown and the app would be rejected.

**Comment by andresesfm** [comment]
@nes123 can you please confirm this is happening on the latest 8.x.x? There was a bug fix for `finishTransaction` not resolving the promise that I recently fixed

**Comment by andresesfm** [comment]
Can you please help us check if this is still an issue on 8.x.x for iOS? 
If it still happens on 8.x.x  We'll reopen. Thank you

Note: I'm not trying to minimize the issue. I see there are multiple posts about it in various forms and I'm trying to make sense of it but with no help and it being reported on such an old version of the library is close to impossible. Thank you for understanding

**Comment by nes123** [comment]
It seems to work fine
