### ISSUE TITLE
requestSubscription

### ISSUE THREAD

**Issue by nirbhaisingh1313** [dooboolab/react-native-iap#1318]
>Hi there, Im getting issue on try requestSubscription,request completes successfully but it works like product purchase in sandbox testing it show only five minutes then expired, user have to subscribe his subscription from google play store ,

it was working before

### Tested environment Real Device

![Screenshot 2021-05-05 at 9 16 59 AM](https://user-images.githubusercontent.com/73397362/117094961-afb28c80-ad82-11eb-98f8-af2b5c1d5a96.png)

**Comment by SSinfo302** [comment]
getting same issue

**Comment by hyochan** [comment]
Looks like you are registered as a test user in playstore. Please check that.

**Comment by avneesh74** [comment]
I checked with non test user as well but it was still showing on tap to pay rather than showing subscribe. I have to go to playstore to manually subscribe to subscription once the payment is done here.
![Screenshot_20210510-113217__01](https://user-images.githubusercontent.com/44198692/117613092-f2f66c00-b183-11eb-89ef-37bbd8dfe01b.jpeg)

**Comment by avneesh74** [comment]
> > Hi there, Im getting issue on try requestSubscription,request completes successfully but it works like product purchase in sandbox testing it show only five minutes then expired, user have to subscribe his subscription from google play store ,
> 
> it was working before
> 
> ### Version of react-native-iap : 6.0.3
> ### Version of react-native :0.59.9
> ### Platforms you faced the error Android
> ### Expected behavior :Need to show sub price/time or auto subscribe from playstore
> ### Actual behavior, have to subscribe forcefully from play store
> ### Tested environment Real Device
> ![Screenshot 2021-05-05 at 9 16 59 AM](https://user-images.githubusercontent.com/73397362/117094961-afb28c80-ad82-11eb-98f8-af2b5c1d5a96.png)

did you find any solution for this

**Comment by nirbhaisingh1313** [comment]
> > > Hi there, Im getting issue on try requestSubscription,request completes successfully but it works like product purchase in sandbox testing it show only five minutes then expired, user have to subscribe his subscription from google play store ,
> > 
> > 
> > it was working before
> > ### Version of react-native-iap : 6.0.3
> > ### Version of react-native :0.59.9
> > ### Platforms you faced the error Android
> > ### Expected behavior :Need to show sub price/time or auto subscribe from playstore
> > ### Actual behavior, have to subscribe forcefully from play store
> > ### Tested environment Real Device
> > ![Screenshot 2021-05-05 at 9 16 59 AM](https://user-images.githubusercontent.com/73397362/117094961-afb28c80-ad82-11eb-98f8-af2b5c1d5a96.png)
> 
> did you find any solution for this

not at the moment ,but i automatically opens subscribe dialog to subscribe no need to subscribe from playstore
,

**Comment by nirbhaisingh1313** [comment]
hi there any once can help me for upgrading or downgrading subscription, unable to find any documentation for this. i'm stuck.
help will be appreciate.
 you can contact me by email saggu4530@gmail.com 
Thanks

> Looks like you are registered as a test user in playstore. Please check that.

**Comment by avneesh74** [comment]
> > > > Hi there, Im getting issue on try requestSubscription,request completes successfully but it works like product purchase in sandbox testing it show only five minutes then expired, user have to subscribe his subscription from google play store ,
> > > 
> > > 
> > > it was working before
> > > ### Version of react-native-iap : 6.0.3
> > > ### Version of react-native :0.59.9
> > > ### Platforms you faced the error Android
> > > ### Expected behavior :Need to show sub price/time or auto subscribe from playstore
> > > ### Actual behavior, have to subscribe forcefully from play store
> > > ### Tested environment Real Device
> > > ![Screenshot 2021-05-05 at 9 16 59 AM](https://user-images.githubusercontent.com/73397362/117094961-afb28c80-ad82-11eb-98f8-af2b5c1d5a96.png)
> > 
> > 
> > did you find any solution for this
> 
> not at the moment ,but i automatically opens subscribe dialog to subscribe no need to subscribe from playstore
> ,

Can you please tell me how did you open the subscribe dialog, will be really helpful.

**Comment by aadityapaliwal94** [comment]
@hyochan What is the meaning of test user in Playstore? I have added my account in the internal testing in Play store, so that I am able to get build for testing. Earlier, it was working fine for this user and showing **Subscribe** button instead of **1-tap buy**. If we remove user from their, we won't be able to get the build.

Can you please explain it? Seems very strange issue. We need to go live and stuck because of this.

**Comment by nirbhaisingh1313** [comment]
@aadityapaliwal94 hello sir have you found any solution regarding this, me also stuck at here,

### as you have said it was working fine, and it should be,
***Please let me know if you found any explanation,

**purchaseUpdateListener is running 4 time do you also facing this issue,   

thanks
