### ISSUE TITLE
Do I need my own Database?

### ISSUE THREAD

**Issue by Sebastian-Schuchmann** [dooboolab/react-native-iap#1319]
Hello,

I have a question regarding restoring purchases. If I use `getAvailablePurchases()` and my App only has non-consumable purchases available is there any need for a database / a custom Backend?

At the beginning of the readme you write the following:

> you'll have to implement the server side to validate your receipts (which is probably the most time consuming part to do it correctly)

and I am a bit confused if this is necessary in all cases. From my testing (only in Sandbox) just using `getAvailablePurchases()` to restore all purchases made seems to work fine and everything else too, so is a server side component really required?

Thanks for the great work!

**Comment by hyochan** [comment]
Validating receipt is recommended to be done in your own server-side to prevent man in the middle attack and other reliability issues.

Related - https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store

Next time please use the [discussions](https://github.com/dooboolab/react-native-iap/discussions) for questions.
