### ISSUE TITLE
0.3.14 Won't compile on iOS

### ISSUE THREAD

**Issue by christophercotton** [dooboolab/react-native-iap#133]
### Version of react-native-iap
0.3.14

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Compile

### Actual behavior
node_modules/react-native-iap/ios/RNIapIos.m:214:39: String literal must be prefixed by '@' 

### Steps to reprodue the behabior
compile the app.

Looks like the 0.3.14 has an error that makes it not compile on iOS. Just need to fix the string literal (I put a comment in the merge request).

I had just done a new install today and got 0.3.14, so I guess I was unlucky to just get it.

**Comment by christophercotton** [comment]
`return [NSString stringWithFormat:"%@ (Error code: %d)", descriptions[0], code];`

should be changed to:

`return [NSString stringWithFormat:@"%@ (Error code: %d)", descriptions[0], code];`

**Comment by dooboolab** [comment]
@christophercotton I saw you reviewed the PR. I've just fixed this. Also follow the readme that version that is not mentioned in `changelog` may occur some bug because I've not tested that yet.

**Comment by christophercotton** [comment]
Is there a way to only have tested items show up in NPM? It seems quite difficult for new people using the project like me, and wondering why it wasn't working.

**Comment by benevbright** [comment]
I'm sorry my bad. 
I tried to compile it at this time and made PR again.
Sorry again.
