### ISSUE TITLE
requestSubscription()

### ISSUE THREAD

**Issue by nirbhaisingh1313** [dooboolab/react-native-iap#1332]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

##### Hi dev, user isn't able to purchase subscription, this is the showing me something went wrong from our end in testing mode, purchase completes successfully but it cancels automatically  cancel reason 1, unable to subscribe,

*****Please give some detail 

###  Thanks  ##

![Screenshot 2021-05-11 at 11 58 35 AM](https://user-images.githubusercontent.com/73397362/117769584-834eb280-b251-11eb-8237-5dae8da93129.png)

**Comment by nirbhaisingh1313** [comment]
@andresesfm Hello sir, can you please explain anything , if possible,

**Comment by andresesfm** [comment]
Hello @nirbhaisingh1313 . In my experience, this kind of error comes from either a bad google account or most likely some kind of problem with the billing information associated with that account.

**Comment by andresesfm** [comment]
closing for now, please reopen if you have more information to share

**Comment by AnkitKh095** [comment]
I am Getting the same error in android Ios it works fine.

currently using  
react-native-iap: 12.10.5,
react-native:0.68.0



![MicrosoftTeams-image](https://github.com/dooboolab-community/react-native-iap/assets/135791878/a43ee834-4dee-4166-a2b4-e463713ac1b9)

    let { offerToken } = productList[0]?.subscriptionOfferDetails[0];
            console.log("---offerToken---", offerToken);


            await RNIap.requestSubscription({
                sku: productList[0]?.productId,
                subscriptionOffers: [{ sku: productList[0]?.productId, offerToken }],
            })
                .then(async (purchase) => {
                    console.log("---Purchase---", purchase);
                    dispatch(CommonAction.stopLoading())
                })
                .catch((err) => {
                    dispatch(CommonAction.stopLoading())
                    console.warn(`IAP req ERROR %%%%% ${err.code}`, err, err.message);
                });
                
getting these error E_UNKNOWN [Error: An unknown or unexpected error has occurred. Please try again later.] 

Please Hlp
