### ISSUE TITLE
Buying Subscription is not working for licensed tester.

### ISSUE THREAD

**Issue by aadityapaliwal94** [dooboolab/react-native-iap#1334]
### Steps to reproduce the behavior

1. Have a monthly subscription.
2. Buy subscription via requestSubscription(productId)
3. purchaseUpdatedListener invoked but the receipt is not gets validated on the server.

Here is the data I got in the purchase listener -

> {"orderId":"GPA.34-39-684-83348","packageName":"xyz","productId":"com.xyz.subs","purchaseTime":1620821085092,"purchaseState":0,"purchaseToken":"nddfdmdblbicbidelkpdpklcxcvdsfdsfsdsdf.AO-J1OwFId4mU2GdsFsLrgNLVjR0gpf_MJCR_XyZnzG71a529LPIEtuXLNfbkzr0JmLB3tfcP5vvGfbV60evrPjRiJwL6rBaMg","autoRenewing":true,"acknowledged":false}

It has purchaseState as 0, which means UN_SPECIFIED_STATE. 

When I try to send this data in my API which uses [in-app-purchase](https://github.com/voltrue2/in-app-purchase) to verify the receipt. It returns the below data - 

> {
"acknowledgementState": "0",
"autoRenewing": "false",
"cancelReason": "1",
"countryCode": "IN",
"developerPayload": "",
"expiryTimeMillis": "1620821379507",
"kind": "androidpublisher#subscriptionPurchase",
"orderId": "GPA.39-37-114-881",
"packageName": "",
"paymentState": "1",
"priceAmountMicros": "79000000",
"priceCurrencyCode": "INR",
"purchaseToken": "ehjfbgnmdlci.AO-J1OzrOiOo3YIULKk629lj1wWi529b8khszu_r6HdPugtRgz-ILYt1wyraXwm_gGFtbqOFBIelkTGpCQ",
"purchaseType": "0",
"service": "google",
"startTimeMillis": "1620821085092",
"status": "0"
}

It has cancelReason value as 1, in the document it says, "Subscription was canceled by the system, for example because of a billing problem"

I am not so sure about it. But one more thing has changes in Google play subscription UI. Earlier, it was showing **Subscription** button but now it has **1-tap buy** button.

Here are the references - 

- https://developer.android.com/reference/com/android/billingclient/api/Purchase.PurchaseState
- https://developers.google.com/android-publisher/archive/v2/purchases/subscriptions

**Comment by andresesfm** [comment]
Hello @aadityapaliwal94, have you tried a newer version? latest is `6.0.6`

**Comment by aadityapaliwal94** [comment]
@andresesfm Do you think it would fix it? I mean a few days back it was working really well with **Subscribe** button and now it's showing **1-tap buy** and causing this issue.

Still, let me try to update it.

**Comment by aadityapaliwal94** [comment]
Still getting the same issue and response as defined above.

**Comment by nirbhaisingh1313** [comment]
@aadityapaliwal94 same issue

**Comment by aadityapaliwal94** [comment]
It's even not working for the real purchase. I have added the amount to buy it from the prod app which uploaded on internal testing. It seems like the above issue, not able to verify it. Even it's showing me a subscription on the Play store Manage Subscription.

If I try to restore purchase in my app, it won't return anything.

See the screenshot of Play store Manage Subscription - 

![IMG-20210513-WA0006](https://user-images.githubusercontent.com/16901281/118085207-a0b18700-b3df-11eb-88f5-34058517933c.jpeg)

**Comment by aadityapaliwal94** [comment]
I also checked the other receipt which was purchased earlier but still valid. It doesn't have the **cancelReason** attribute. Why this new receipt have it even if the purchase was successful and Play store deducted amount from my account.

**Comment by nirbhaisingh1313** [comment]
i checked by reverting the previous version of the library but still same case, also listener is running multiple time with same receipt. cancelReason: 1, unable to find any solution.

**Comment by andresesfm** [comment]
Can you please confirm that you are calling `acknowledgePurchase` once you validated the purchase?

**Comment by aadityapaliwal94** [comment]
@andresesfm Yes, I am doing it after validating the purchase from the server. But validation itself is a problem. If the server says the purchase got cancel itself and it's not valid, there is no reason to `acknowledgePurchase`, right? Here are the steps I performed -

1. `requestSubscription` with productId
2. It invokes `purchaseUpdatedListener` with the transaction.
3. I try to validate the same transaction with my server.
4. If it's valid, we call the `acknowledgePurchaseAndroid` method. 

But here the server does not validate it.

**Comment by andresesfm** [comment]
Hello @aadityapaliwal94 At this point I think stackoverflow would be a better resource. Also take a look at this: https://github.com/voltrue2/in-app-purchase/issues/124

**Comment by nirbhaisingh1313** [comment]
Hello @aadityapaliwal94 have you found anything

**Comment by aadityapaliwal94** [comment]
@nirbhaisingh1313 Not yet.

**Comment by aadityapaliwal94** [comment]
Opened an issue here - https://stackoverflow.com/questions/67563856/android-google-play-subscription-gets-canceled-after-buying-it

**Comment by nirbhaisingh1313** [comment]
Hello @aadityapaliwal94 There is also another issue purchaseUpdateListener is running multiple time , i have 
verified the code

**Comment by aadityapaliwal94** [comment]
@andresesfm @nirbhaisingh1313 It's because of this change of Google play https://tech.hindustantimes.com/tech/news/google-play-to-pause-auto-renewing-subscriptions-free-trials-in-india-report-71619875378816.html

**Comment by andresesfm** [comment]
Good find, closing this issue, feel free to reopen if needed
