### ISSUE TITLE
Missing Amazon receipt validation

### ISSUE THREAD

**Issue by andmau90** [dooboolab/react-native-iap#1338]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
6.0.6
### Version of react-native
0.63.4
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
see the tutorial
https://developer.amazon.com/it/docs/in-app-purchasing/iap-rvs-examples.html

```javascript
function validateReceipt(developerSecret, userId, receiptId) {
    const url = `https://appstore-sdk.amazon.com/version/1.0/verifyReceiptId/developer/${developerSecret}/user/${userId}/receiptId/${receiptId}`;
    return fetch(url, { method: "GET", headers: new Headers({ Accept: "application/json" }) });
}
```

**Comment by andresesfm** [comment]
@andmau90 So you think this method should be added to the API?

**Comment by hyochan** [comment]
@andresesfm I think it'd be good to be added since we also provide this in both `ios` and `android` as local validation. Although this isn't officially recommended, it will help to debug.

**Comment by andresesfm** [comment]
@andmau90 this kind of validation should be done server-side. The hint is that the method you mention implies having the `developerSecret` in your client which is not secure

**Comment by andresesfm** [comment]
Having said that, for debugging purposes should be fine: https://github.com/dooboolab/react-native-iap/pull/1392
