### ISSUE TITLE
No confirmation bottom sheet in production on iOS (working on TestFlight)

### ISSUE THREAD

**Issue by rostaingc** [dooboolab/react-native-iap#1339]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Expected behavior
When clicking subscribe button in the app, the user should see a bottom sheet to confirm the purchase.

![IMG_3729](https://user-images.githubusercontent.com/37388803/118398036-6b2fc680-b689-11eb-8863-9ec5fbad69a9.PNG)

### Actual behavior
In TestFlight, it is working fine.
In production, the app hangs and no bottom sheet is shown.

### Tested environment (Emulator? Real Device?)
Real device 

### Steps to reproduce the behavior
Open the app
Go to in-app purchasing page
Click on subscribe

**Comment by rb162215** [comment]
getting same issue on ios14, no confirmation popup and payment sheet, directly success listener is called with old expired receipt.

**Comment by rassemdev** [comment]
Have you found any solution? My confirmation modal not showing after one successful purchase, even in development.

**Comment by andresesfm** [comment]
Please check if the user already owns the item, or if the previous transaction hasn't been finished
