### ISSUE TITLE
Error when upgrade/downgrade subscription on Android

### ISSUE THREAD

**Issue by JERRINTKG** [dooboolab/react-native-iap#1340]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap

    "react-native-iap": "^6.0.0"

### Version of react-native

    "react-native": "0.62.2"

### Platforms you faced the error (IOS or Android or both?)

     Android

### Expected behavior

When upgrade/downgrade a subscription ,current subscription must replaced with new sku and new purchase token.

### Actual behavior

Triggering new subscription along with old one (we can see two subscriptions(skus) same time).

### Tested environment (Emulator? Real Device?)

Real Device - sandbox

### Steps to reproduce the behavior

1)  Initiate one subscription

2) Upgrade/Downgrade the subscription with the function call requestSubscription(newSku,false,oldSku,oldPurchaseToken,4) ( 4: DEFERRED)

3) subscription prompt will show (like new subscription along with the old one).

**Comment by andresesfm** [comment]
@JERRINTKG could this be a duplicate of https://github.com/dooboolab/react-native-iap/issues/888 ?

**Comment by hyochan** [comment]
@andresesfm Thanks this can be closed.
