### ISSUE TITLE
This subscription will not automatically renew

### ISSUE THREAD

**Issue by hrishiakhade** [dooboolab/react-native-iap#1344]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap 
"react-native-iap": "^4.6.3",

### Version of react-native
"react-native": "^0.63.2",

### Platforms you faced the error (IOS or Android or both?)
Android 

### Expected behavior
Subscribe option should be there while purchasing a Subscription.

### Actual behavior
One-tap buy is displayed while purchasing a Subscription.

### Tested environment (Emulator? Real Device?)
Real Device

I have created 2 subscriptions in the Google play console, when I click on the buy option, it gives me the following popup.

[Image](https://ibb.co/q1Y2FwS)

Instead of subscribe, it gives me One-tap buy options along with  "This subscription will not automatically renew".

I would like to Subscribe option which will auto-renew the subscription.

```
 products = await IAP.getSubscriptions(productIds);


IAP.requestSubscription(item.productId).then(res => {

        })
```

Please let me know if  I am missing anything.

**Comment by hyochan** [comment]
This is very informative. Thanks for sharing :)

Hope you are safe with Covid Virus.

**Comment by hrishiakhade** [comment]
> This is very informative. Thanks for sharing :)
> 
> Hope you are safe with Covid Virus.

Thanks :)
