### ISSUE TITLE
To manage In App purchase when app is in Background

### ISSUE THREAD

**Issue by Sneha1231** [dooboolab/react-native-iap#1350]
Hi,

I initiated an in app purchase from my app, then I force quit the app. After that I got In app purchase prompt and able to do the purchase at apple side. Since I the app is not at the foreground, we missed the server updation and this trasaction won't be saved any where.

How to manage this situation.
Is there a way to identify when the app is in foreground and disable purchase button in In app purchase prompt if not.

**Comment by hyochan** [comment]
The transaction might not be finished then. You may check the pending transaction.

`getPendingPurchasesIOS()`
