### ISSUE TITLE
How to customize Apple Pay payment sheet?

### ISSUE THREAD

**Issue by HappyCodingLover** [dooboolab/react-native-iap#1352]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
^5.1.3

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
![image (1)](https://user-images.githubusercontent.com/71419620/119506194-441b7800-bda0-11eb-898d-07fe2ab3a5be.png)
I want to edit Price section in this sheet to show like 30 days trial

### Actual behavior
Only shows *.** $ per 3 months.

### Tested environment (Emulator? Real Device?)
Both tested on Emulator and Real Device

### Steps to reproduce the behavior
I have implemented Apple payment by following the Readme

Any help would be highly appreciated.

**Comment by apfritts** [comment]
Trial information is configured in App Store Connect @HappyCodingLover
