### ISSUE TITLE
ProxyBillingActivity?

### ISSUE THREAD

**Issue by trops** [dooboolab/react-native-iap#136]
### Version of react-native-iap
0.3.15

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Making a purchase should work

### Actual behavior
Getting the error 
```
Unable to find explicit activity class ...billingclient.api.ProxyBillingActivity...
```
### Steps to reprodue the behabior
Install react-native-iap with Android manual installation instructions. iOS is running fine it seems through testing, Android can get the subscriptions, but fails when attempting to purchase.

**Comment by dooboolab** [comment]
@trops Can you share the code in which you face the error? That might be helpful for us to guess the problem.

**Comment by trops** [comment]
In the error it asks if I have declared "this activity in your AndroidManifest.xml". so it seems something during the installation went awry

Here is how I am calling it, also, I can load the products successfully.
```
export const subscribeToRNProduct = (subscriptionIdentifier) => {
    console.log('RN SUBSCRIBE TO ', subscriptionIdentifier);
    return new Promise((resolve, reject) => {
        return RNIap.buySubscription(subscriptionIdentifier)
            .then((result) => {
                console.log('BUY RESULT', result);
                return resolve(result);
            }).catch(e => {
                console.log('RN SUB ERROR', e);
                return reject(e);
            });
    });
};
```

**Comment by trops** [comment]
Turns out, just like the error suggests, the activity was missing. This isn't part of the installation instructions so I was a bit confused when I saw it.

Here is what I added to the AndroidManifest.xml file
```
<application>
...
 <activity
            android:name="com.android.billingclient.api.ProxyBillingActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />
</application>
```

**Comment by dooboolab** [comment]
@trops Sounds happy that it is solved. However, this is strange because most users didn't need that step to use our module. Also, it wasn't mentioned in android guideline too. Which one is your project created with `react-native init` or `CRNA` or `expo`?
Anyway thank you for your work. I'll update my readme for those who may have problem as you do.
