### ISSUE TITLE
requestPurchase() failing multiple times with error "E_USER_CANCELLED"

### ISSUE THREAD

**Issue by victoriaSh** [dooboolab/react-native-iap#1361]
### Version of react-native-iap
6.0.3

### Version of react-native
0.64.1

### Platforms you faced the error (IOS or Android or both?)
IOS

### Actual behavior
When trying to purchase many users get "E_USER_CANCELLED" error. After that they are trying to purchase again several times and get the same error. This issue is very similar to [#412](https://github.com/dooboolab/react-native-iap/issues/412) but it marked as resolved in v.3.
<img width="1046" alt="Снимок экрана 2021-05-29 в 03 33 20" src="https://user-images.githubusercontent.com/8823284/120052656-fd8f7d00-c02e-11eb-8b79-a8cd1f0296bd.png">

Statistics for unique users who attempted to purchase (7-8 from 10 of "E_USER_CANCELLED" tried it several times)

<img width="1053" alt="Снимок экрана 2021-05-29 в 03 08 35" src="https://user-images.githubusercontent.com/8823284/120051942-755ba880-c02b-11eb-8ec9-e5ed925a9a18.png">

### Tested environment (Emulator? Real Device?)
Real devices, production.

### Steps to reproduce the behavior
I can't reproduce it on my devices.
Am I missing something? Double-checked everything and can't get why it's happening. I would be very grateful for any help.

On click purchase button: 

```

purchasePremium: async () => {
    if (Platform.OS == 'ios'){
            try {
                const canMakePayments = await RNIap.initConnection();
            } catch (err){
                amplitude.getInstance().logEvent("init_connection_error");
                return false
            }
            const clearTransaction = await RNIap.clearTransactionIOS();
            const clear = await RNIap.clearProductsIOS();
            try {
                let products = await RNIap.getProducts(itemSkus);
            } catch (err){
                amplitude.getInstance().logEvent("get_product_error", {code: err.code, message: err.message});
                return false
            }
            try {
                let premium = await RNIap.requestPurchase("full_alphabet", false)
                return true
            } catch (err){
                amplitude.getInstance().logEvent("subscription_error",{code: err.code, 
                        responseCode: err.responseCode ? err.responseCode : "no code", message: err.message});
                return false
            }
    } else { ... }
}

```

Listeners in the root component: 

````
RNIap.initConnection()
	.then(() => {
		purchaseUpdateSubscription = RNIap.purchaseUpdatedListener(async (purchase) => {
			try {
				if (Platform.OS === 'ios') {
					const receipt = purchase.transactionReceipt;
					if (receipt) {
						let result = await SubscriptionActions.verifyReceipt(receipt);
						if (result == true){
							await RNIap.finishTransaction(purchase, false);
							await RNIap.clearTransactionIOS();
							amplitude.getInstance().logEvent("subscription_success");
							setPurchaseActive();
						} else {
							amplitude.getInstance().logEvent("verify_receipt_error");
							setPurchaseInactive();
						}
					}
				} else if (Platform.OS === 'android') {
					...
				}
			} catch (ackErr) {
				amplitude.getInstance().logEvent("subscription_listener_error",{message: ackErr});
			}
		});

		purchaseErrorListener = RNIap.purchaseErrorListener(async (purchase) => {
			setPurchaseInactive();
			if (purchase && purchase.code){
				let message = '';
				if (purchase.message){
					message = purchase.message;
				}
				amplitude.getInstance().logEvent("pack_subscription_error",{code: purchase.code, message: message});
			} else {
				amplitude.getInstance().logEvent("pack_subscription_error");
			}
			try {
				const ackResult = await RNIap.finishTransaction(purchase);
			} catch (ackErr) {
				amplitude.getInstance().logEvent("finish_transaction_error",{error: ackErr})
			}
			await RNIap.clearTransactionIOS();
		});
	}
);
```

**Comment by harryfb** [comment]
We are seeing the same issue, also in production. Our DB logs show multiple `E_USER_CANCELLED` errors generated from successive subscription attempts by users. The timestamps on these are only a few seconds apart. Could the subscription prompt have been displayed to them again, as has been seen previously in the sandbox (#1192)?

react-native-iap => 6.0.3
react-native => 0.63.3
Platform => iOS

Any help on this would be appreciated.

**Comment by gtebbutt** [comment]
Does anyone have any further info on this? It's currently blocking us from releasing updated iOS builds, but it's proving almost impossible to debug in the sandbox. 

Any chance @iaphub could shed any light? I imagine you've got more logs to work from than the rest of us put together!

**Comment by allenmanning** [comment]
I've just started seeing in on Android.  My purchases are down by a large amount after switching to this library.  I'm seeing multiple Sentry logs showing `E_USER_CANCELLED`.  I'm not sure if this is actually cancelled transactions or if there is a problem with this library or how we are using it.

**Comment by hyochan** [comment]
There are some unknown issues related to purchases which also made me burden when I was working on the `IAP` product. The last updates I've provided as an example are opened in https://github.com/hyochan/dooboolab.com/blob/master/src/components/pages/Sponsor.tsx.

I am not currently working on `IAP` so very sorry but hope I can provide some effort if I can see what I can do.

**Comment by harryfb** [comment]
After some more investigation, it turns out the issue in our case was related to #1210 (the `E_USER_CANCELLED` error message is applied to underlying `SKErrorDomain 2` Store Kit errors by `IAP`. You must finish both successful and failing transactions as documented in this [thread](https://stackoverflow.com/questions/24654241/should-i-call-finishtransation-on-failed-transactions-during-in-app-purchases).

We were previously on `IAP` version 3.4.11 and using the `buySubscription` function to handle subscriptions. In this version, the handler calls `buyProduct`, while always setting `andDangerouslyFinishTransactionAutomatically` true. As a result, our existing implementation was not designed to manually finish failing transactions and they were completed automatically. Interestingly, the `requestPurchase` function in this version outputs a console warning about dangerously finishing transactions automatically but `buySubscription` does not!

Migrating to the most recent library release meant that our failing transactions were no longer finished automatically. Calling `finishTransaction` on failing transactions has fixed the issue and we have confirmed this in production.

**Comment by mklb** [comment]
I am facing the same issue. I have over 150 reported error message that show me errors like `E_USER_CANCELED` or `SKErrorDomain error 2`

@harryfb so you call `RNIap.finishTransaction` in your `purchaseErrorListener` ?

How do you do that? Since the method just returns an error object (Code is from the sample app, yours is different). 

```
purchaseErrorSubscription = purchaseErrorListener(
  (error: PurchaseError) => {
    // there is no purchase object here
  },
);
```

**Comment by victoriaSh** [comment]
@harryfb it seems that it's different issue. As you can see in my example above I call `finishTransaction` on failed purchases too. And next "E_USER_CANCELED" errors appears after user trying to purchase again after a minute or two. 

Currently I'm trying to use expo purchases but not sure that I will use it in next versions of my app. I see the same situation in my stats and some really bad errors when user paid for item but didn't get it. I guess I will come back to react-native-iap.

@hyochan do you recommend to use iap with hooks? Or is it the same? And should I finish "canceled" transaction or not? I have suggestion that sometimes error listener with "E_USER_CANCELED" error can be called several milliseconds before `purchaseUpdatedListener` and finishing transaction in first called listener can cause this situation. I've seen several double calls in one of the previous versions of my app but cannot find it in stats and say confidently did I finished transaction in that versions or not.

**Comment by arshad-slate** [comment]
I got a step where I am able to reproduce E_USER_CANCELED error in the sandbox environment. 

Start a purchase and cancel the payment pop-up.  At this time E_USER_CANCELED error will come as expected. But if you try to purchase the same product again it will throw an error E_USER_CANCELED and then will continue normal purchase flow.

**Comment by belyylis** [comment]
Pay => Google Popup => Cancel => Multiple "E_USER_CANCELLED" error in console.

Have you already found a solution?

react-native => 0.64.0
react-native-iap => 6.2.4

**Comment by andresesfm** [comment]
@belyylis for Android we have changed the way the init code is executed. Can you please try the latest 8.x.x?

**Comment by andresesfm** [comment]
@victoriaSh can you please help us check if this is still an issue on 8.x.x for iOS? 

I have found the following as something that is expected from the native SDK: https://stackoverflow.com/a/3633571/570612
If it stil happens on 8.x.x and the above doesn't fix. We'll reopen. Thank you
