### ISSUE TITLE
Localized Description is not returned for other regions

### ISSUE THREAD

**Issue by basemanabulsi** [dooboolab/react-native-iap#1362]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
Version `6.0.9` and `4.6.1`

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
I added localized description to an in-app-purchase subscription for some regions in apple itunes portal  and expected to get the description I set in portal, for example France I expect to get the french description when I use testing account with French Region and the language of the device has been changed to France.

but I only get English title and description.

### Actual behavior
What I am facing is that  I only get English title and description, this is the object I get 

```
{
 "countryCode": "FRA", 
 "currency": "EUR", 
"description": "3 Months Subscription", 
"discounts": [], 
"introductoryPrice": "", 
"introductoryPriceAsAmountIOS": "", 
"introductoryPriceNumberOfPeriodsIOS": "", 
"introductoryPricePaymentModeIOS": "", 
"introductoryPriceSubscriptionPeriodIOS": "", 
"localizedPrice": "€48,99", 
"price": "16.33", 
"productId": 
"discount_three_month", 
"subscriptionPeriodNumberIOS": "3", 
"subscriptionPeriodUnitIOS": "MONTH", 
"title": "3 Months Subscription", 
"type": "subs"}
```

### Steps to reproduce the behavior
<img width="1082" alt="Screen Shot 2021-05-29 at 5 12 34 PM" src="https://user-images.githubusercontent.com/14277303/120073465-133d8a80-c0a1-11eb-9be1-96e26af1a4a1.png">

**Comment by basemanabulsi** [comment]
Finally after long time of trying, I discovered the following:

1. get_products() returns the localized description of subscription.
2. get_subscriptions() doesn't return the localized description of the subscriptions.


I don't know if I should consider it as a bug or not. 
But this is my issue and solution of it

**Comment by andresesfm** [comment]
Hello @basemanabulsi This logic seems to apply to both Products and Subscriptions: https://github.com/dooboolab/react-native-iap/blob/master/ios/RNIapIos.m#L653 do you have any more insights?

**Comment by hyochan** [comment]
@basemanabulsi Have you also provided localized strings to `storekit`?

**Comment by basemanabulsi** [comment]
Hello guys, where can I add the localized string to `storekit`?

**Comment by andresesfm** [comment]
Could it be related to https://developer.apple.com/forums/thread/660817 ? Please reopen if this is still an issue on 8.x.x
