### ISSUE TITLE
requestSubscription - Infinite load when user cancels the automatic renewal

### ISSUE THREAD

**Issue by nextrie** [dooboolab/react-native-iap#1363]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
6.0.2

### Version of react-native
5.0.1-alpha.2

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
User get a subscription popup

### Actual behavior
Infinite load on the requestSubscription method without displaying anything to the user

### Tested environment (Emulator? Real Device?)
Real device (TestFlight)

### Steps to reproduce the behavior
- Subscribe to an automatic renewal subscription
- Cancel your automatic renewal
- Wait for the subscription to end
- Come back on the app and try to subscribe again

Thank you and have a nice day !

**Comment by j-cheung** [comment]
Hi, 

I am experiencing this as well, what did you do to get it working? 

Thanks.
