### ISSUE TITLE
getSubscriptions from useIAP always returns undefined. but working fine without hook

### ISSUE THREAD

**Issue by vinaygoyal20** [dooboolab/react-native-iap#1364]
it. Please report issue if there is a bug.
There is issue in the hooks introduced.I just followed the medium article mentioned in the doc. I just followed the same mentioned steps but i was always getting undefined for both getSubscriptions and getProducts using the below mentioned code

const {
    connected,
    products,
    subscriptions,
    getProducts,
    getSubscriptions,
    finishTransaction,
    currentPurchase,
    currentPurchaseError,
  } = useIAP();
   getSubscriptions(skus)
  
  
  But when i tried using it without hook just like the older way 
  import IAP from 'react-native-iap';
  IAP.getSubscriptions(skus);
  
  I was able to get the products.
  
  Please fix this issues and till that if possible just update the medium article as it took alot of time to debug this kind of issue especially when you are integrating it for the first time.

**Comment by hyochan** [comment]
Could you compare the codebase to the [working repo with a hook](https://github.com/hyochan/dooboolab.com/blob/master/src/components/pages/Sponsor.tsx)?

I've not faced that earlier

**Comment by vinaygoyal20** [comment]
Sorry it was my mistake.I was trying to get the products using
`getSubscriptions(skus).then(res=>{
        console.log(res);
        //thinking subscriptions will be returned by promise
        
      })`
      
    but what i should be doing was 
    to call the method using
    1=>`getSubscriptions(skus)`;
    
 and then extract subscriptions from  useIAP hook  to get the subscriptions just like
   ` const {subscriptions}=useIAP()`
    
    
    Thank you for a quick response.

**Comment by ManhVuTien** [comment]
@vinaygoyal20 Can you show me your code, I log connected true but subscriptions still empty, thanks
