### ISSUE TITLE
[iOS 15] - Good News.  No issues testing with iOS 15 Beta

### ISSUE THREAD

**Issue by the-dut** [dooboolab/react-native-iap#1367]
Just thought I'd share some good news.  iOS 15 Beta was released by Apple today.  I tested out my IAP app and everything seemed to work fine.  After the issues with iOS 14, I was worried.  But I was happily surprised that I didn't see any.  :)

**Comment by hyochan** [comment]
Very very good news!! :100:

**Comment by 24ark** [comment]
@the-dut One thing I noticed on iOS 15 Beta is that the `purchaseUpdatedListener` is fired even after calling `finishTransaction`. This worked fine on iOS 14 but doesn't work as expected on iOS 15 Beta

**Comment by 24ark** [comment]
> @the-dut One thing I noticed on iOS 15 Beta is that the `purchaseUpdatedListener` is fired even after calling `finishTransaction`. This worked fine on iOS 14 but doesn't work as expected on iOS 15 Beta

Looks like the issue is fixed on iOS 15 Beta 3

**Comment by andresesfm** [comment]
Thank you for the info
