### ISSUE TITLE
Validating the receipt through server and add the item to database

### ISSUE THREAD

**Issue by akaoppa** [dooboolab/react-native-iap#1368]
Hello,

We manage to make our validation from our server side but we still have some issue. So far we dont have middleman attack anymore. 
We have a listener that check if the purchase is complete before using self.purchaseDone(purchase.productId); to give the gold to the user.
However sometimes the payment took time to validate for some users and even when it's complete, they didnt receive anything from self.purchaseDone(purchase.productId); 

Second bug, sometimes the user is purchasing several items, but only one is processing to the firebase database : 
![image](https://user-images.githubusercontent.com/60573069/121321116-1bea5800-c90e-11eb-8621-2c3af8501e35.png)

![image](https://user-images.githubusercontent.com/60573069/121321209-2f95be80-c90e-11eb-83d1-fb8ca3ad9976.png)

We do not understand why ? The listener should proc when it's not consume yet right ?

We werent be able to reproduce this bugs... But here is how we tested in our side and it worked fine (the gold were given) : 

1) Purchase 1 item with "Slow test card" (which approve payment after a few minutes), quit the app and come later => the listener still proc and the gold were add to the our user
2) Purchase 2 items with "Slow test card", switching screen, reducing the app then coming back and the gold were given as well.

Here is the code edited with the call to the server side. Any help to understand that, would be really appreciated !

async componentDidMount() {
    this.getItems();
    const self = this;

    RNIap.initConnection().then(() => {
      // we make sure that "ghost" pending payment are removed
      // (ghost = failed pending payment that are still marked as pending in Google's native Vending module cache)
      RNIap.flushFailedPurchasesCachedAsPendingAndroid().catch(() => {
        // exception can happen here if:
        // - there are pending purchases that are still pending (we can't consume a pending purchase)
        // in any case, you might not want to do anything special with the error
        console.log("flushFailedPurchasesCachedAsPendingAndroid");
      }).then(() => {

          self.purchaseUpdateSubscription = purchaseUpdatedListener(
            async (purchase: InAppPurchase | SubscriptionPurchase) => {
              console.log('purchaseUpdatedListener', purchase);
              const receipt = purchase.transactionReceipt;
              console.log(receipt);
              if (receipt) {

     const response = await  #fetch('https://domain.com:2028/accessToken');
      const androidToken = await response.text();

      var ResultValidateReceipt = false;
     const ResultValidateReceiptReponse = RNIap.validateReceiptAndroid(purchase.packageNameAndroid, purchase.productId, purchase.purchaseToken, androidToken)
          .then((result)=>{
                      console.log(result.purchaseState);
                      console.log("Validate Receipt Android==>"+JSON.stringify(result))
                      if (result.purchaseState == 0){
                          ResultValidateReceipt = true;
                      }
                      else{
                           ResultValidateReceipt = false;
                      }

                   })
                   .catch((error) => {
                                 console.log('Validate ', error);

                   });

                       try {
                            const ackResult = await RNIap.finishTransaction(purchase, true);
                              if (ackResult){
                                if (ackResult.code == "OK" && ResultValidateReceipt){
                                   self.purchaseDone(purchase.productId);
                                   //console.log("insert database");
                                }
                              }
                          } catch (ackErr) {
                            console.warn('ackErr', ackErr);
                            let toastDiamond = Toast.show(translate("awaitingPayment"), {
                                    duration: Toast.durations.SHORT,
                                    position: Toast.positions.TOP,
                                    shadow: false,
                                    animation: true,
                                    hideOnPress: true,
                                    delay: 0,
                                    opacity: 0.8
                                });
                                  setTimeout(function () {
                                      Toast.hide(toastDiamond);
                                  }, 3000);
                          }

               }

          });
          self.purchaseErrorSubscription = purchaseErrorListener(
            (error: PurchaseError) => {
              console.log('purchaseErrorListener', error);
              Alert.alert('purchase error', JSON.stringify(error));
            },
          );
  });
});

}

**Comment by akaoppa** [comment]
Any one have an idea ?

**Comment by andresesfm** [comment]
Looks like you are checking for the receipt to be valid here: 
```
if (ackResult.code == "OK" && ResultValidateReceipt){
                               self.purchaseDone(purchase.productId);
                               //console.log("insert database");
                            }
```
you should print or store what happened there, what the `ackResult.code` was, and if ResultValidateReceipt is true. Closing for now, if you need more help please open a discussion or a stackoverflow question.

**Comment by akaoppa** [comment]
> Looks like you are checking for the receipt to be valid here:
> 
> ```
> if (ackResult.code == "OK" && ResultValidateReceipt){
>                                self.purchaseDone(purchase.productId);
>                                //console.log("insert database");
>                             }
> ```
> 
> you should print or store what happened there, what the `ackResult.code` was, and if ResultValidateReceipt is true. Closing for now, if you need more help please open a discussion or a stackoverflow question.

Thanks for the reply. So I have to store it because sometimes the payment is still pending and "const ackResult = await RNIap.finishTransaction(purchase, true);" may not proc again right ?
