### ISSUE TITLE
release build failed for Android after update

### ISSUE THREAD

**Issue by abcabccd** [dooboolab/react-native-iap#1372]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
6.1.0
### Version of react-native
0.64.2
### Platforms you faced the error (IOS or Android or both?)
android
### Expected behavior
build success
### Actual behavior
build failed
### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior
update version of react-native-iap
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeReleaseAssets'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve project :react-native-iap.
     Required by:
         project :app
      > The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'. However we cannot choose between the following variants of project :react-native-iap:
          - amazonReleaseRuntimeElements
          - playReleaseRuntimeElements
        All of them match the consumer attributes:
          - Variant 'amazonReleaseRuntimeElements' capability UnlockMe:react-native-iap:unspecified declares a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'amazonRelease' but the consumer didn't ask for it
                  - Provides attribute 'store' with value 'amazon' but the consumer didn't ask for it
          - Variant 'playReleaseRuntimeElements' capability UnlockMe:react-native-iap:unspecified declares a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'playRelease' but the consumer didn't ask for it
                  - Provides attribute 'store' with value 'play' but the consumer didn't ask for it
        The following variants were also considered but didn't match the requested attributes:
          - Variant 'amazonDebugApiElements' capability UnlockMe:react-native-iap:unspecified:
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
          - Variant 'amazonDebugRuntimeElements' capability UnlockMe:react-native-iap:unspecified declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
          - Variant 'amazonReleaseApiElements' capability UnlockMe:react-native-iap:unspecified declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release':
              - Incompatible because this component declares an API of a component and the consumer needed a runtime of a component
          - Variant 'playDebugApiElements' capability UnlockMe:react-native-iap:unspecified:
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
          - Variant 'playDebugRuntimeElements' capability UnlockMe:react-native-iap:unspecified declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
          - Variant 'playReleaseApiElements' capability UnlockMe:react-native-iap:unspecified declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release':
              - Incompatible because this component declares an API of a component and the consumer needed a runtime of a component

**Comment by JosePatricio** [comment]
Same here :(

**Comment by hsource** [comment]
I see this error as well!

I followed the instructions later in the file in the "Manual installation" section to add the lines to my android/app/build.gradle

```gradle
    defaultConfig {
        applicationId "com.mycompany.myapp"
        // ... random stuff

        // Added from https://github.com/dooboolab/react-native-iap/tree/6.2.0#android
        // Even though this is supposedly only needed for manual linking, we
        // get these errors without it:
        //
        // The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'. However we cannot choose between the following variants of project :react-native-iap:
        //        - amazonDebugRuntimeElements
        //        - playDebugRuntimeElements
        missingDimensionStrategy 'store', 'play'
    }
```

**Comment by hengkx** [comment]
I use `react-native-camera`.Already config `missingDimensionStrategy 'react-native-camera', 'general'`. How to resolve? Thanks.

**Comment by hengkx** [comment]
> I use `react-native-camera`.Already config `missingDimensionStrategy 'react-native-camera', 'general'`. How to resolve? Thanks.

```
missingDimensionStrategy 'react-native-camera', 'general'
missingDimensionStrategy 'store', 'play'
```

**Comment by mortezacruise** [comment]
> > I use `react-native-camera`.Already config `missingDimensionStrategy 'react-native-camera', 'general'`. How to resolve? Thanks.
> 
> ```
> missingDimensionStrategy 'react-native-camera', 'general'
> missingDimensionStrategy 'store', 'play'
> ```

it worked for me

**Comment by allenmanning** [comment]
>  Even though this is supposedly only needed for manual linking

It seems like this requires a doc update in the README.

**Comment by hyochan** [comment]
It is provided https://react-native-iap.dooboolab.com/docs/installing

**Comment by Akifcan** [comment]
I can list  the subscription in my app but this error throws anyway
