### ISSUE TITLE
Type error in the interface ReceiptValidationResponse

### ISSUE THREAD

**Issue by hardmaster92** [dooboolab/react-native-iap#1376]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
6.2.0

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
The `latest_receipt_info` property of the interface `ReceiptValidationResponse` (used for validating app store receipts) should be an array as described in [the official documentation of the receipt response](https://developer.apple.com/documentation/appstorereceipts/responsebody). In this case I would expect a type like `Record<string, unknown>[]`.

### Actual behavior
The type of `latest_receipt_info` property is described as `Record<string, unknown>` which as mentioned above is incorrect.

### Tested environment (Emulator? Real Device?)
Both Emulator and Real Device.

### Steps to reproduce the behavior

1. Try to implement simple receipt validation using the `validateReceiptIos` method of IAP
2. Try to use the `latest_receipt_info` property in the resolved promise  as an array
3. You should get a type error since the currently defined type of the prop is not an array

**Comment by andresesfm** [comment]
Hello @hardmaster92, Looking at the documentation for that type: https://github.com/dooboolab/react-native-iap/blob/master/src/types/apple.ts#L203-L205 it looks like it's dependent on the iOS version. I don't know if this could be a problem for backward compatibility. Let me know of your thoughs

**Comment by hardmaster92** [comment]
> Hello @hardmaster92, Looking at the documentation for that type: https://github.com/dooboolab/react-native-iap/blob/master/src/types/apple.ts#L203-L205 it looks like it's dependent on the iOS version. I don't know if this could be a problem for backward compatibility. Let me know of your thoughs

If you want to support iOS 6 style receipts then the only solution that I suggest is using a union type so it would become `Record<string, unknown> | Record<string, unknown>[]` and then the developers could verify OS versions and cast it as desired

**Comment by andresesfm** [comment]
I think it's safe to say that iOS 6 is no longer used :)  Here is the fix: https://github.com/dooboolab/react-native-iap/pull/1402
