### ISSUE TITLE
How to get expiry date from suscription after buy it

### ISSUE THREAD

**Issue by techday84** [dooboolab/react-native-iap#1382]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.
Hi, it isn't a bug but I don't know how to check the expiry date of a suscription.

After requestSuscription when RNIap.purchaseUpdatedListener fires, i get this fields:

purchaseStateAndroid
obfuscatedProfileIdAndroid
autoRenewingAndroid
isAcknowledgedAndroid
signatureAndroid
dataAndroid:
    orderId
    packageName
    productId
    purchaseTime
    purchaseState
    purchaseToken
   autoRenewing
   acknowledged
  transactionDate
  transactionId
  purchaseToken"
 obfuscatedAccountIdAndroid

But how to get any reference to when will expire this suscription? i don't find any doc.

I need to check the expiry date to remove premium content.

Thanks for your help.

### Version of react-native-iap
 "react-native-iap": "^6.0.0-rc.23",

### Version of react-native
"react-native": "0.64.0",

### Platforms you faced the error (IOS or Android or both?)
android

### Tested environment (Emulator? Real Device?) 
Real Device.

**Comment by andresesfm** [comment]
@techday84 from the client-side you'll need to check if calling `getProducts` returns your subscription. If it does,  then the subscription is active.

**Comment by andresesfm** [comment]
In order to get more details, you might want to use the backend calling this API: https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions
