### ISSUE TITLE
RNIap.getSubscriptions() returns nothing and does not give an error 

### ISSUE THREAD

**Issue by fieldesigner** [dooboolab/react-native-iap#1391]
Hi guys, I'm having a strange situation here, when I'm looking for the signatures it doesn't show me anything and it doesn't show me any error either. If anyone can help I appreciate it 

### Version of react-native-iap
"react-native-iap": "^6.2.2",

### Version of react-native
react-native-cli: 2.0.1
react-native: 0.61.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
I expected to have any kind of feedback 

### Actual behavior
It currently doesn't return anything and doesn't show me an error 

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior

 const itemSubs = Platform.select({
    ios: [],
    android: ['assinatura.trimestralmob'],
  });  

  async function getSubscriptions() {
    try {
      console.tron.log('ini get subs');
      const products = await RNIap.getSubscriptions(itemSubs);
      console.tron.log('products');
      console.tron.log(products);
      setProdutos(products);
    } catch (err) {
       console.tron.warn(err.code, err.message);
    }
    console.tron.log('end get subs');
  }

  useEffect(() => {
    async function iapgetProducts() {
      try {
        const result = await RNIap.initConnection();
        await RNIap.flushFailedPurchasesCachedAsPendingAndroid();
         console.tron.log('result', result);
      } catch (err) {
         console.tron.warn(err.code, err.message);
      }
      getSubscriptions();
    }
    iapgetProducts();
  }, []);

I get from the console: 
1º [ 'result': true ]
2º ini get subs
3º should receive something about the products, but nothing arrives... neither any kind of error nor the end 'end get subs'.
apparently when it comes to const products = await RNIap.getSubscriptions(itemSubs); everything stop.

Does anyone have any tips or ideas of what might be happening? 

i am using this same script in another app (published) and it works perfectly.

**Comment by andresesfm** [comment]
@fieldesigner 
Did you try `6.2.3` by any chance? it has a fix for a bug introduced when we split the app stores, it prevented errors from bubbling up

**Comment by fieldesigner** [comment]
@andresesfm , Thanks, i updated now, but still the same problem

**Comment by andresesfm** [comment]
Have you noticed that you are not passing the skus to `getSubscriptions`?

**Comment by fieldesigner** [comment]
wouldn't it be the itemSubs constant?
was set in:
   const itemSubs = Platform.select ...........
and passed in:
    const products = await RNIap.getSubscriptions(itemSubs); 

Anyway i did two tests,
the first see if the a constane itemSubs was being received a row before const products = await RNIap.getSubscriptions(itemSubs); and yes she is coming.

Another test was to pass the itemSubs to the call getSubscriptions(itemSubs) function; but even so, no change continues in the same way.

I think I will redo everything

**Comment by gazedash** [comment]
I have the same problem on iOS, but I am not sure if this is linked to sandbox account or not...

Same error on android also, but I need to investigate, maybe this is something on my side

**Comment by fieldesigner** [comment]
I redid the entire process.
First I updated all the packages of the project, fixed all the errors and some warnings, only later I installed the IAP.
I just added the:
  - supportLibVersion = "28.0.0" inside buildscript {ext {}} in android/build.gradle file
- added <uses-permission android:name="com.android.vending.BILLING" /> to manifest
- added missingDimensionStrategy 'store', 'play' inside defaultConfig {} in android/app/build.gradle file

and....................... IT WORKED :)
thanks for the help guys
