### ISSUE TITLE
setInstallSourceAndroid is deprecated and will be removed in the future

### ISSUE THREAD

**Issue by machowski** [dooboolab/react-native-iap#1395]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

Hi, after upgrading to 6.2.4 console warrning is displayed on each initConnection. Message: "setInstallSourceAndroid is deprecated and will be removed in the future"

### Version of react-native-iap
6.2.4

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
No console warning shown in emulator

### Actual behavior
Console warning displayed on every init connection

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
call initConnection in the coee

**Comment by subinsuresh** [comment]
Getting the same error in the latest version on a real devices as well.

**Comment by hardmaster92** [comment]
I also get the same warning with version 6.4.2

**Comment by fieldesigner** [comment]
same problem here, with version 6.2.4
react-native-cli: 2.0.1
react-native: 0.64.2

i updated for 6.3.0 and the same warning present

**Comment by andresesfm** [comment]
`setInstallSourceAndroid` is technically no longer required but it was set in case somebody was still using it. Since this issue is related to the warning itself. I'll create a ticket to remove the method instead of issuing the warning

**Comment by andresesfm** [comment]
https://github.com/dooboolab/react-native-iap/pull/1401

**Comment by hyochan** [comment]
Fixed and released in `7.0.0` with android new billing client which is `4.0.0`.
