### ISSUE TITLE
requestPurchase return error "An unknown or unexpected error has occurred. Please try again later."

### ISSUE THREAD

**Issue by sohanpc** [dooboolab/react-native-iap#1399]
I have get error response in the catch ```An unknown or unexpected error has occurred```. Please try again later. but payment successfully. After some time check payment history and payment is canceled. How I handle this?

It urgent please help me!!
```
const requestNonConsumablePurchase = async (sku) => {
    setShowLoader(true);
    try {
      RNIap.requestPurchase(sku)
        .then(async (purchase) => {
          const reciept = purchase.transactionReceipt;
          if (reciept) {
            // Android
            if (
              purchase.purchaseStateAndroid === 1 &&
              !purchase.isAcknowledgedAndroid
            ) {
              //  RNIap.consumePurchaseAndroid(purchase.purchaseToken)
              const ackResult = await RNIap.acknowledgePurchaseAndroid(
                purchase.purchaseToken
              );
              console.log("ackResult", purchase);
            }
            // IOS
            if (Platform.OS == "ios") {
              // alert(purchase.transactionId)
              await RNIap.finishTransactionIOS(purchase.transactionId);
            }
            await RNIap.finishTransaction(purchase, false);
            purchaseConfirmed(purchase);
          }
          setShowLoader(false);
        })
        .catch((err) => {
          console.log("purchase error", err);
          setShowLoader(false);
        });
    } catch (error) {
      console.log("buy error", error);
      setShowLoader(false);
    }
  };
```

**Comment by andresesfm** [comment]
Please provide the information required in the template. It looks like you are trying to run the Amazon build, is that what you intended?

**Comment by sohanpc** [comment]
I have tired with the Android App (Google play In-App-Purchase). I have create product on the google play console. get product id and pass as a string in the ```RNIap.requestPurchase``` method. after purchase I got error ```An unknown or unexpected error has occurred. Please try again later.``` 

Please let me know if any other information you want @andresesfm 

Thank you

**Comment by andresesfm** [comment]
That error message comes from the Amazon flavor of the app. Make sure you run your app with `--variant=PlayDebug`

**Comment by andresesfm** [comment]
Closing for now, please feel free to re-open if more info
