### ISSUE TITLE
Installation in Cocoapods project

### ISSUE THREAD

**Issue by robyweb** [dooboolab/react-native-iap#14]
I'm building an ejected Expo app which uses cocoapods in the xcode project. To install the IAP component, I followed the manual install. When I add the link to libRNIap.a, the build fails with the error: 

'React/RCTDefines.h' file not found

Is there a way to install using cocoapods or can you help me figure out how to get around this issue?

Thanks!

**Comment by dooboolab** [comment]
@robyweb 
Hi there! Yes this is known issue in cocoapod installation. Actually you don't need to manually install this even you are in pod project. After you installed in manually or by react-native link, you should add `$(SRCROOT)/../../../ios/Pods/Headers/Public` header path as `recursive` in RNIap Header Search Path. Could you try this? Check the screenshot below also.

<img width="866" alt="2018-01-25 10 24 47" src="https://user-images.githubusercontent.com/27461460/35365880-14e18084-01ba-11e8-9cb7-b8f160be74a0.png">

**Comment by robyweb** [comment]
That worked perfectly!

Thank you!

Fred
