### ISSUE TITLE
[Android] getProducts return always an empty array

### ISSUE THREAD

**Issue by martinberbesson** [dooboolab/react-native-iap#140]
### Version of react-native-iap
0.3.15

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Get All products

### Actual behavior
All work fine on iOS but getProducts return always an empty array on android.
I think its a config problem however i followed each step... 

APK upload with billing permission / merchant account set up / Create in app purchase...

**Comment by vadermemo** [comment]
Same issue here

My snippet:

      RNIap.prepare().then(responsePrepare => {
        console.log("=============>responsePrepare:" + responsePrepare);
        RNIap.getProducts(itemSkus).then(response => {
            this.setState({ items  : response});
            console.log("=============>response:" + JSON.stringify(response));
        });
      });

My response on adb.logcat (Android)


208 28473 28524 I ReactNativeJS: Running application "testingIap" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
04-25 17:04:04.228  1140  1150 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
04-25 17:04:04.230  1140  2059 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
04-25 17:04:04.232 24842 24933 I Finsky  : [4061] com.google.android.finsky.billing.iab.ab.b(46): com.projectbundle: Account from first account - [uuAJBL1tLX2MAj69S-olEslXXXX]
04-25 17:04:04.233 28473 28473 D RNIapModule: billing client ready
04-25 17:04:04.303 28473 28524 I ReactNativeJS: =============>responsePrepare:null
04-25 17:04:04.308 28473 28524 I ReactNativeJS: =============>responsePrepare:null
04-25 17:04:04.328  1140  2107 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
04-25 17:04:04.330  1140  1896 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
04-25 17:04:04.339  1140  2095 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
04-25 17:04:04.340  1140  1679 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
04-25 17:04:04.343 24842 24854 I Finsky  : [4020] com.google.android.finsky.billing.iab.ab.b(46): com.projectbundle: Account from first account - [uuAJBL1tLX2MAj69S-olEslXXXX]
04-25 17:04:04.347 24842 24853 I Finsky  : [4019] com.google.android.finsky.billing.iab.ab.b(46): com.projectbundle: Account from first account - [uuAJBL1tLX2MAj69S-olEslXXXX]
04-25 17:04:04.626 28473 28525 D RNIapModule: responseCode: 0
04-25 17:04:04.628 28473 28525 D RNIapModule: responseCode: 0
04-25 17:04:04.669 28473 28524 I ReactNativeJS: =============>response:[]
04-25 17:04:04.693 28473 28524 I ReactNativeJS: =============>response:[]

But with iOS I get the array with the datas well format.

PD1 I get the recommendation from https://medium.com/@dooboolab/react-native-in-app-purchase-121622d26b67

PD2 "Help me Obi Wan Kenobi you're my only hope"

**Comment by dooboolab** [comment]
Hi~ Could you share your js code for `itemSkus`? Did you set up like below code?
```
export const PURCHASE_ITEMS = Platform.select({
  ios: [
    'productid_1',
    'productid_2',
  ],
  android: [
    'productid_1',
    'productid_2',
  ],
});
```

**Comment by vadermemo** [comment]
Hi @dooboolab 

This is my data
const itemSkus = Platform.select({
  ios: [
  	'com.iap.cart',
        'com.iap.doublecoins'
  ],
  android: [
    'double',
    'cart_1500'
  ],
});




Best regards

**Comment by dooboolab** [comment]
@vadermemo this souds really bad to me.. sorry for that. It works fine in my environment. I will debug more tommorow and surely get back tommorow!

**Comment by martinberbesson** [comment]
i think i need to have a alpha release... Upload a apk with billing permission is not enough

**Comment by vadermemo** [comment]
@dooboolab  Well, if there exists a something help for you, maybe is next point:

when I put the configuration on react-native-billing I putted in the resources file "string.xml" the param  <string name="RNB_GOOGLE_PLAY_LICENSE_KEY">
but in react-native-iap I can't see this parameter in action.


The try-catch that you required throws the next log:


1. Change my itemsSkus

const itemSkus = Platform.select({
  ios: [
    'predictorcart_1500',
  ],
  android: [
    'predictorcart_1500',
    'android.test.purchased',
    'android.test.canceled',
    'android.test.refunded',
    'android.test.item_unavailable',
  ],
});


2. change on componentDidMount

  async componentDidMount(){
    try {
      await RNIap.prepare();
      await this.getItems();

    }
    catch (err) {
      console.warn(err.code, err.message);
    }
  }

3.   Change the get data 

  getProductDetails = async() => {
      try {
        const products = await RNIap.getProducts(itemSkus);
        console.log('=======>Products::::', products);
        this.setState({ productDetails: products });
      } catch (err) {
        console.warn(err.code, err.message);
      }
    }


4. Put a button 
  <Button onPress={this.getProductDetails} title="Get product details" />

5. Put the app on device
 react-native run-android --variant=release

6.Finally the log is the next:
04-26 12:53:11.335 16749 16759 I Finsky  : [11707] com.google.android.finsky.billing.iab.ab.b(46): com.projectbundle: Account from first account - [uuAJBL1tLX2MAj69S-olEl331212]
04-26 12:53:11.401   226  1177 V audio_hw_primary: do_output_standby in
04-26 12:53:11.409 20362 20432 D RNIapModule: responseCode: 0
04-26 12:53:11.426   226  1177 W audio_hw_primary: do_output_standby.mode:0 
04-26 12:53:11.426   226  1177 V audio_hw_primary: do_output_standby in out
04-26 12:53:11.427  1140  2106 D PowerManagerService: releaseWakeLockInternal: lock=87714678 [AudioMix], flags=0x0, total_time=3166ms
04-26 12:53:11.444 20362 20431 I ReactNativeJS: '=======>Products::::', [ { description: 'Descripción de muestra para el producto: android.test.canceled.',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     title: 'Título de muestra',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     localizedPrice: '$18.65',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     type: 'inapp',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     currency: 'MXN',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     price: '18.65',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     productId: 'android.test.canceled' },
04-26 12:53:11.444 20362 20431 I ReactNativeJS:   { description: 'Descripción de muestra para el producto: android.test.item_unavailable.',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     title: 'Título de muestra',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     localizedPrice: '$18.65',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     type: 'inapp',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     currency: 'MXN',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     price: '18.65',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     productId: 'android.test.item_unavailable' },
04-26 12:53:11.444 20362 20431 I ReactNativeJS:   { description: 'Descripción de muestra para el producto: android.test.purchased.',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     title: 'Título de muestra',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     localizedPrice: '$18.65',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     type: 'inapp',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     currency: 'MXN',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     price: '18.65',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     productId: 'android.test.purchased' },
04-26 12:53:11.444 20362 20431 I ReactNativeJS:   { description: 'Descripción de muestra para el producto: android.test.refunded.',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     title: 'Título de muestra',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     localizedPrice: '$18.65',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     type: 'inapp',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     currency: 'MXN',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     price: '18.65',
04-26 12:53:11.444 20362 20431 I ReactNativeJS:     productId: 'android.test.refunded' } ]



@martinberbesson I have an app on alpha release, even I can't get the products. I think is another thing, maybe a configuration in react-native-iap or google console.

**Comment by vadermemo** [comment]
@martinberbesson @dooboolab  Incredible!!

I made another app with the same steps and the app is working on iOS and Android!!. I can`t believe it.

I don´t know which is the reason, but I think is something configuration on code or google console.

PD I was waiting 5 hours to get the correct itemSkus.
PD2 The old app not get itemsSkus even with 24 hours .
PD3 @dooboolab Now You can sleep quiet. :)
PD4 I will develop the buy process, I hope that is easy

Best regards,

**Comment by dooboolab** [comment]
@vadermemo Glad that it is working.

**Comment by systemride** [comment]
Per #124 I think this is still occurring - at least for existing apps which it would be good to have a solution for this as well.

**Comment by jordanmkoncz** [comment]
For anyone who's still running into this issue, you should first of all read https://stackoverflow.com/a/35132936/1374827 and ensure you've met all the requirements outlined in that post.

If that stuff is all good, check that you are calling the appropriate function. For me, I had an app where I was only using Subscription in-app purchases, but I was mistakenly calling `RNIap.getProducts` and of course getting back an empty array. I had to instead call `RNIap.getSubscriptions` and the subscriptions were then returned.

**Comment by Prudwell** [comment]
Ok after wrestling with this, my issue turned out to be my inexperience with android. I had been messing with the package name in dev and while it ran fine on the device, the package name not being set up perfectly is why it was returning an empty array. After following [these steps](https://stackoverflow.com/a/37390022/4766311) and [these](https://stackoverflow.com/questions/13117081/the-item-you-requested-is-not-available-for-purchase/35132936#35132936) it's all looking good.

**Comment by bharatidudhjiya** [comment]
I also getting empty array,
And I am confused with https://developer.android.com/google/play/billing/billing_testing#draft_apps doc, that I need test account and add tester, so please any one can help me for this.

Thanks!

**Comment by tmjordan** [comment]
same

**Comment by hyochan** [comment]
@bharatidudhjiya @tmjordan If you guys are facing configuration issue, I'd like you to try pure android `iap` project first and see if it works correctly. That would also help you understand better on android's `iap` sdk.

**Comment by tmjordan** [comment]
@hyochan thanks, it's a good idea. I will do that

**Comment by hyochan** [comment]
@tmjordan This is quite old but [this](https://github.com/hyochan/android-iap-example) might help you basic setup.

**Comment by tmjordan** [comment]
thank you man @hyochan

**Comment by ManalLiaquat** [comment]
I solved it! I am using these versions,

`react-native-iap: ^4.3.0`
`react-native: 0.60.5`

just do it like this
```
const itemSkus = Platform.select({
    ios: [
        '100coins' // just remove bundle id from product id
    ],
    android: [
        '100coins' // just remove bundle id from product id
    ]
});
```

**Comment by Mussabaheen** [comment]
Make Sure you have the correct package name for your application.

and in case you have changed it from react-native command. it won't still work.

You have to do it manually and then clean the project using ./gradlew clean in the android folder.

after that give it a try.

Happy Coding.

**Comment by rahulkarkande0707** [comment]
I got empty array response can any one help me I have spent 3 days

**Comment by zeeshan-shabbir** [comment]
did anyone resolved? i am also getting empty array regardless of doing every step
