### ISSUE TITLE
Error E_IAP_NOT_AVAILABLE thrown

### ISSUE THREAD

**Issue by machowski** [dooboolab/react-native-iap#1404]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

Hi, since upgrade to 7.0.0 I have troubles using library - E_IAP_NOT_AVAILABLE error is thrown.

### Version of react-native-iap
7.0.0

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
Android (play store)

### Expected behavior
react-native-iap initialised

### Actual behavior
error thrown: E_IAP_NOT_AVAILABLE

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
run RNIap.initConnection()

**Comment by freezen82** [comment]
Same environment with @machowski  excepts react-native version 0.63.4

useIAP hooks connect => get false

none using useIAP hooks and RNIap.initConnection() => get true 
but get error E_IAP_NOT_AVAILABLE when getSubscriptions() after initConnection

**Comment by hyochan** [comment]
> Same environment with @machowski excepts react-native version 0.63.4
> 
> useIAP hooks connect => get false
> 
> none using useIAP hooks and RNIap.initConnection() => get true
> but get error E_IAP_NOT_AVAILABLE when getSubscriptions() after initConnection

Can you compare you code with [example here](https://github.com/hyochan/dooboolab.com/blob/master/src/components/pages/Sponsor.tsx)?

**Comment by githubbla** [comment]
I have same issue with 7.0 on android E_IAP_NOT_AVAILABLE
when requesting list of products.

**Comment by nikmedoed** [comment]
I updated the package yesterday to 7.0.0
Before everything worked on 3.3.7

After initConnection, I get the error `E_IAP_NOT_AVAILABLE` when trying to get skus descriptions (`getProducts`, `getSubscriptions`)


```
RNIap.initConnection().then(result => {
      log.trace("initialIAPSetup connection inited", result)
      RNIap.flushFailedPurchasesCachedAsPendingAndroid().catch((error) => {
        log.warn("flushFailedPurchasesCachedAsPendingAndroid Error", error)
      }).then(async () => {
        this.purchaseUpdateSubscription = purchaseUpdatedListener(
          (purchase: InAppPurchase | SubscriptionPurchase | ProductPurchase) => {
            log.debug('purchaseUpdatedListener', purchase);
            const receipt = purchase.transactionReceipt;
            if (receipt) {
              RNIap.finishTransaction(purchase, false);
            }
            else {
              log.warn('No transactionReceipt', purchase);
            }
          }
        )

        this.purchaseErrorSubscription = purchaseErrorListener((error: PurchaseError) => {
          log.warn('purchaseErrorListener', error);
        })
        
        RNIap.getProducts(items).catch(err => { log.error('getProducts catalogs error', err.message, err.code) }) 

        RNIap.getProducts(productsCatalogs).catch(err => {
           log.error('getProducts catalogs error', err.message, err.code) 
        })
        RNIap.getSubscriptions(subscriptionVariants)
          .then(subs => {
            log.debug("initialIAPSetup ", subs)
      })
    }).catch(err => log.error('products fetch error', err.message, err.code))
}
```

`getProducts` and `getSubscriptions` throw `E_IAP_NOT_AVAILABLE`, but other methods work properly and connection inited

**Comment by marcpechaitis** [comment]
I am seeing the same E_IAP_NOT_AVAILABLE error introduced in v7.0.0 (android device, 0.63.4)

my code:   
```
const getProducts = useCallback(async (): Promise<void> => {
    console.log('🟣🟣🟣🟣🟣🟣 getting products');
    try {
      const results: RNIap.Product[] = await RNIap.getProducts(skus);
      setProducts(results);
    } catch (err) {
      console.warn('😡😡😡😡😡', err);
      setError(true);
    }
  }, [skus]);
```
 console results:
```
[Mon Jul 05 2021 15:28:47.843]  LOG      🟣🟣🟣🟣🟣🟣 getting products
[Mon Jul 05 2021 15:28:47.929]  WARN     😡😡😡😡😡 [Error: E_IAP_NOT_AVAILABLE]
```

The exact same code works fine for me on 6.3.0.

**Comment by hyochan** [comment]
Hm. Very strange that downgrading to `6.3.0` works fine. The major update for `7.0.0` was in #1400 which is upgrading android billingClient to `4.0.0`.

Could you check that if you've set `billingClient` version manually? This should be `4.0.0` from react-native-iap `7.0.0`

**Comment by marcpechaitis** [comment]
@hyochan -- I have searched through my code and string `billingClient` does not appear, so it does not look like that I am not overriding it manually.

What happens on your end when you upgrade the example app to 7.0.0? 

Just wondering, are there any additional steps that we need to perform when upgrading to 7.0.0 that weren't mentioned in the Changelog?

**Comment by gigadeplex** [comment]
It's because you guys are throwing an error at [checkNativeAmazonAvailable](https://github.com/dooboolab/react-native-iap/blob/3d619e331b1d077c133480dc745bb623692c0120/src/iap.ts#L45). This is called at [fillProductsAdditionalData](https://github.com/dooboolab/react-native-iap/blob/3d619e331b1d077c133480dc745bb623692c0120/src/iap.ts#L146) which is called at both [getProducts](https://github.com/dooboolab/react-native-iap/blob/3d619e331b1d077c133480dc745bb623692c0120/src/iap.ts#L200) and [getSubscriptions](https://github.com/dooboolab/react-native-iap/blob/3d619e331b1d077c133480dc745bb623692c0120/src/iap.ts#L226). Guess I have to moonwalk back to my last working version until you update this package again.

**Comment by hyochan** [comment]
> It's because you guys are throwing an error at [checkNativeAmazonAvailable](https://github.com/dooboolab/react-native-iap/blob/3d619e331b1d077c133480dc745bb623692c0120/src/iap.ts#L45). This is called at [fillProductsAdditionalData](https://github.com/dooboolab/react-native-iap/blob/3d619e331b1d077c133480dc745bb623692c0120/src/iap.ts#L146) which is called at both [getProducts](https://github.com/dooboolab/react-native-iap/blob/3d619e331b1d077c133480dc745bb623692c0120/src/iap.ts#L200) and [getSubscriptions](https://github.com/dooboolab/react-native-iap/blob/3d619e331b1d077c133480dc745bb623692c0120/src/iap.ts#L226). Guess I have to moonwalk back to my last working version until you update this package again.

Will this happen even `amazon` flavor is not included in `Android`?

```
amazon{
  dimension "appstore"
  missingDimensionStrategy "store", "amazon"
}
```

If the above is not provided the code related to `amazon` should be ignored. If not, then we should change the above code as @gigadeplex mentioned.

@andresesfm Could you kindly check this thread?

**Comment by FloMueh** [comment]
@hyochan i do it exactly like you mention it. Get the same error with version 7.0. 

Everything is working fine with version 6.3. 

@gigadeplex i analysed the code like you and came to the same result!

**Comment by mmskvortsov** [comment]
Hello there, I've faced the same issue today, just installed and configured the library (version 7.0.0) and got **E_IAP_NOT_AVAILABLE** error. 6.3 does seem to work for me as well

**Comment by andresesfm** [comment]
Hello, thank you for the report, I'll look into it

**Comment by andresesfm** [comment]
Here is the fix: https://github.com/dooboolab/react-native-iap/pull/1407 @hyochan  please review at your earliest convenience 🙏

**Comment by hyochan** [comment]
Should be resolved in `7.0.1`. Thanks to @andresesfm

**Comment by marcpechaitis** [comment]
@hyochan and @andresesfm -- I just tested 7.0.1 on Android device and made a successful test purchase.  Thanks for the quick fix!!

**Comment by mmskvortsov** [comment]
New version works perfectly! Thank you guys for your efforts, you're making this world better!

**Comment by messycoding** [comment]
I encountered this error on version 7.0.0 and version 7.2.1 . . I will try the 7.0.1

**Comment by egulhan** [comment]
I got the same error. In my case, I had only setup sandbox for IAP on App Store, (not hadn't setup Android for IAP at all yet). to solve, I removed function calls of RNIap.initConnection() and RNIap.flushFailedPurchasesCachedAsPendingAndroid() inside RNIap.initConnection() and I only left the function call of RNIap.purchaseUpdatedListener() and RNIap.purchaseErrorListener() and it worked. it is like below: 

`
componentDidMount() {
this.purchaseUpdateSubscription = RNIap.purchaseUpdatedListener((purchase) => {
     //
});

this.purchaseErrorSubscription = RNIap.purchaseErrorListener((error) => {
    //
});
`

NOTE: You should add function calls of RNIap.initConnection() and RNIap.flushFailedPurchasesCachedAsPendingAndroid() when you setup IAP on Google Play.

**Comment by Mihai-github** [comment]
Still having the issue with version ^8.0.5.......

**Comment by YASH6004** [comment]
this solution worked for me 

1. Delete node module 
2. Add react-native-iap in package.json
3.  add these 2 lines in android/app/build.gradle

![image](https://github.com/dooboolab-community/react-native-iap/assets/102504196/58ed0a6b-dee7-4e7d-a957-d94dd6a5daab)

for more refer this :

https://github.com/dooboolab-community/react-native-iap/issues/1372#issuecomment-905789793

**Comment by YASH6004** [comment]
.
