### ISSUE TITLE
iOS crash right after a successful subscription

### ISSUE THREAD

**Issue by tezqa** [dooboolab/react-native-iap#1408]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
6.3.0

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Get a `SubscriptionPurchase` after calling `RNIap.requestSubscription` or at least an error.

### Actual behavior
A native crash visible in Xcode.

### Tested environment (Emulator? Real Device?)
Tested on both

### Steps to reproduce the behavior

```
const [subscription]: RNIap.Subscription[] = await RNIap.getSubscriptions([
    productId,
  ]);
console.log(subscription); // OK
const purchase = await RNIap.requestSubscription(subscription.productId);
```

Xcode logs about the crash:

```
2021-07-07 15:33:30.876687+0200 MyApp[1059:199421] 




 Purchase Successful !! 




.
2021-07-07 15:33:30.876724+0200 MyApp[1059:199421] 


 requestReceiptDataWithBlock with force refresh: NO 

.
2021-07-07 15:33:30.877045+0200 MyApp[1059:199421] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI_Transfer objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x19d226754 0x1b1ced7a8 0x19d298a18 0x19d23e274 0x102768e00 0x106cfc0b4 0x106cfdde0 0x106d0e0a8 0x19d1a0398 0x19d19a270 0x19d199360 0x1b47d7734 0x19fc14584 0x19fc19df4 0x102770efc 0x19ce55cf8)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI_Transfer objectAtIndex:]: index 0 beyond bounds for empty array'
terminating with uncaught exception of type NSException
```

**Comment by tezqa** [comment]
Resolved, it was a just a conflict with an old in app purchase library used on my project.

**Comment by joomaiotrung** [comment]
> Resolved, it was a just a conflict with an old in app purchase library used on my project.

How did you solve it?

**Comment by tezqa** [comment]
I just removed the other (and unused) library, previously installed by another developer.
