### ISSUE TITLE
App Crashed on RNIap.buyProduct

### ISSUE THREAD

**Issue by vadermemo** [dooboolab/react-native-iap#142]
### Version of react-native-iap
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-iap": "^0.3.19"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
 List<Purchase> purchases not empty
### Actual behavior
Nullpointer
### Steps to reprodue the behabior
0. Get products from RNIap.getProducts(itemSkus);
1.  Render the items list of SKUS
2 Click over a SKU item.
3 Call a custom method onPressSku(item)
4. Use example snippet from examples, on onPressSku(item):
  RNIap.buyProduct(item.productId).then(purchase => {
      this.setState({
        receipt: purchase.transactionReceipt, // save the receipt if you need it, whether locally, or to your server.
        progressTitle: 'Purchase Successful!',
        coins: this.state.coins + 100
      });
    }).catch(err => {
      // resetting UI
      console.warn("XXXXXXXXXXXX Error:" + err); // standardized err.code and err.message available
      this.setState({ progressTitle: 'Buy 100 Coins for only $0.99' });
      alert(err.message);
    })
2. Buy the item 

3. Get the log
insky.billing.acquire.AcquireActivity t1533}}}
04-26 18:46:10.758  1140  2095 V WindowManager: Pausing WindowToken AppWindowToken{9cf8e6 token=Token{516fb41 ActivityRecord{7267228 u0 com.testingbilling/com.android.billingclient.api.ProxyBillingActivity t1533}}}
04-26 18:46:10.763  1140  2095 D PowerManagerService: acquireWakeLockInternal: lock=246812737, flags=0x1, tag="*launch*", ws=WorkSource{10155}, uid=1000, pid=1140
04-26 18:46:10.764  8005  8005 W BillingHelper: Couldn't find purchase lists, trying to find single data.
04-26 18:46:10.764  8005  8005 W BillingHelper: Received a bad purchase data.
04-26 18:46:10.764  8005  8005 W BillingHelper: Couldn't find single purchase data as well.
04-26 18:46:10.764  8005  8005 D RNIapModule: Purchase Updated Listener
04-26 18:46:10.764  8005  8005 D RNIapModule: responseCode: 0
04-26 18:46:10.764  8005  8005 D AndroidRuntime: Shutting down VM
04-26 18:46:10.765  8005  8005 E AndroidRuntime: FATAL EXCEPTION: main
04-26 18:46:10.765  8005  8005 E AndroidRuntime: Process: com.testingbilling, PID: 8005
04-26 18:46:10.765  8005  8005 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule$7.onPurchasesUpdated(RNIapModule.java:364)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
04-26 18:46:10.765  8005  8005 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
04-26 18:46:10.767  1140  1679 W ActivityManager:   Force finishing activity com.testingbilling/.MainActivity
04-26 18:46:10.767  1140  1679 V WindowManager: Pausing WindowToken AppWindowToken{ebaa687 token=Token{c8846c6 ActivityRecord{4954a1 u0 com.testingbilling/.MainActivity t1533}}}
04-26 18:46:10.768  1140  1679 D WindowManager: Input focus has changed to Window{d823a06 u0 com.testingbilling/com.testingbilling.MainActivity}
04-26 18:46:10.779  1140  1679 D WindowManager: Input focus has changed to null
04-26 18:46:10.838  1140  8054 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:763 com.android.server.am.ActivityManagerService$21.run:12841 <bottom of call stack> <bottom of call stack> <bottom of call stack> 
04-26 18:46:10.845  1140  1154 D WindowManager: Input focus has changed to Window{54ee191 u0 Application Error: com.testingbilling}

Finally, I don't know why is null on line RNIapModule.java:364

@dooboolab sorry bro, a bug again  :(

**Comment by dooboolab** [comment]
@vadermemo NP bro. What is your test environment by the way?

                 Do's
1)Create sign apk for your application.
2)Upload your apk on Google play store.
3)Create product for your application.
4)wait for 6-12 hour for update item's on store.
5)Give Billing permissions in Manifest.xml

                   Don't
1)Don't use emulator for testing its does not support Billing Services.
2)Don't use unsigned apk for Billing services.

Read more: http://www.androidhub4you.com/2013/03/how-to-inegrate-in-app-purchase-billing.html#ixzz5DqRctVJp

**Comment by dooboolab** [comment]
@vadermemo Could you share some repo having problem? So I can debug in your environment. Mine with some others I know of works fine.

**Comment by dooboolab** [comment]
@vadermemo I really want to hear back from you. Also your experience in other module too.

**Comment by puckey** [comment]
After calling:
```javascript
      try {
        const purchase = await RNIap.buyProduct(sku);
        this.props.onPurchased(sku);
        console.info(purchase);
        return true;
      } catch (err) {
        if (err.message !== 'Cancelled.') {
          Alert.alert(err.message);
        }
        console.warn(err.code, err.message);
        return false;
      }
```

I experienced the following crash:

(After starting the app again, it seems the purchase did go through)

```
05-01 04:45:10.615  9224  9224 D RNIapModule: Purchase Updated Listener
05-01 04:45:10.615  9224  9224 D RNIapModule: responseCode: 0
05-01 04:45:10.620  9224  9224 D AndroidRuntime: Shutting down VM
05-01 04:45:10.620  9224  9224 E AndroidRuntime: FATAL EXCEPTION: main
05-01 04:45:10.620  9224  9224 E AndroidRuntime: Process: com.jonathanpuckey.radiogarden, PID: 9224
05-01 04:45:10.620  9224  9224 E AndroidRuntime: com.facebook.react.bridge.ObjectAlreadyConsumedException: Map already consumed
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.facebook.react.bridge.WritableNativeArray.pushNativeMap(Native Method)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.facebook.react.bridge.WritableNativeArray.pushMap(WritableNativeArray.java:53)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:187)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:32)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:30)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule.resolvePromisesForKey(RNIapModule.java:461)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule.access$300(RNIapModule.java:44)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule$7.onPurchasesUpdated(RNIapModule.java:376)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-01 04:45:10.620  9224  9224 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-01 04:45:10.622   897  2139 W ActivityManager:   Force finishing activity com.jonathanpuckey.radiogarden/.MainActivity
05-01 04:45:10.626  9224  9260 I ReactNativeJS: { purchaseToken: 'ioflnhcblefhneidmcpoooca.AO-J1OzAdOvv20_VfnZy_Es0kxH7-wunDo-Gap7G4rcq8KCtVVa7YYZeBBSf2Hmm8YexasuCTlL_1_D6DFGV5RQNR3YcTkdLdGNRfWM5dHrznOL7AjPp_IJ9vE6ZRVS3AOCrb24NqzzpKXY1-P9VMjePutKEW0Yvmw',
05-01 04:45:10.626  9224  9260 I ReactNativeJS:   signature: 'PwA7b+p808ShJYyQMdRS4wn7KB+61Z0/XnzLFXkALRQsMuAq3xiBsY3of84sjzxbecv67vwAuj2WQfHDyvZjH6uOaPboHOR6ZSGOgftKvSBKk92yNO/kckXBrZJvcZFVtfiSXRrD1H9sosOsT7XKTNamYB7PIEPJ9lb5hms5W49lvxYW/ZCpTM7BXlhjv7TFc2rsTq4Ta/APVWPoy3+Gf1Y38jvnv7y8sUbcvRR55Hj5LRNPLWuD/I4rthrDufFHyL/aaxlPOWVTQ79WnfW71RZfO1MJbMQR5Psd1WE2FMfwxdbZNmPi8ySmpsD2LERFtbmpahIWdfG9wHE8v20KEQ==',
05-01 04:45:10.626  9224  9260 I ReactNativeJS:   autoRenewing: false,
05-01 04:45:10.626  9224  9260 I ReactNativeJS:   data: '{"orderId":"GPA.3378-0159-9028-67172","packageName":"com.jonathanpuckey.radiogarden","productId":"remove_advertising2","purchaseTime":1525164296617,"purchaseState":0,"purchaseToken":"ioflnhcblefhneidmcpoooca.AO-J1OzAdOvv20_VfnZy_Es0kxH7-wunDo-Gap7G4rcq8KCtVVa7YYZeBBSf2Hmm8YexasuCTlL_1_D6DFGV5RQNR3YcTkdLdGNRfWM5dHrznOL7AjPp_IJ9vE6ZRVS3AOCrb24NqzzpKXY1-P9VMjePutKEW0Yvmw"}',
05-01 04:45:10.626  9224  9260 I ReactNativeJS:   transactionReceipt: 'ioflnhcblefhneidmcpoooca.AO-J1OzAdOvv20_VfnZy_Es0kxH7-wunDo-Gap7G4rcq8KCtVVa7YYZeBBSf2Hmm8YexasuCTlL_1_D6DFGV5RQNR3YcTkdLdGNRfWM5dHrznOL7AjPp_IJ9vE6ZRVS3AOCrb24NqzzpKXY1-P9VMjePutKEW0Yvmw',
05-01 04:45:10.626  9224  9260 I ReactNativeJS:   transactionDate: '1525164296617',
05-01 04:45:10.626  9224  9260 I ReactNativeJS:   transactionId: 'GPA.3378-0159-9028-67172',
05-01 04:45:10.626  9224  9260 I ReactNativeJS:   productId: 'remove_advertising2' }
05-01 04:45:10.665   897   936 I ActivityManager: Showing crash dialog for package com.jonathanpuckey.radiogarden u0
05-01 04:45:10.751   897  9586 I OpenGLRenderer: Initialized EGL, version 1.4
05-01 04:45:10.751   897  9586 D OpenGLRenderer: Swap behavior 2
05-01 04:45:11.083   897   935 W ActivityManager: Activity pause timeout for ActivityRecord{8ec895 u0 com.jonathanpuckey.radiogarden/com.android.billingclient.api.ProxyBillingActivity t131 f}
```

**Comment by dooboolab** [comment]
@puckey Could you try `react-native-iap@0.3.23`? I am not quite sure why this is happening. Also, it looks like you are receiving the purchase data correctly. I've just avoided exception rejection in another thread in `react-native-iap@0.3.23`, hope you can try this one.

**Comment by puckey** [comment]
The problem went away when I upgraded to 0.3.22.. I will do some more testing to be certain though. (Thanks for the amazing library by the way!)

**Comment by vadermemo** [comment]
@dooboolab  All is fine. Please close this horrible bug

Thanks a lot.

**Comment by dooboolab** [comment]
@vadermemo NP. Sorry that it wasn't working well in your environment. Unlike `ios`, android may have more issues depends on the device. There still remains issues in pure android's `IAP` module though. We will keep maintain this issue and support for problems. Thank you. I will close this.
