### ISSUE TITLE
subscription upgrade/downgrade not working in android 

### ISSUE THREAD

**Issue by shivanitp** [dooboolab/react-native-iap#1426]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report the issue if there is a bug.

getting an error when update  or downgrade the current subscription

ReactNativeJS: 'check the error of subscriptions', '**E_DEVELOPER_ERROR**'
DoobooUtils: Error Code : 5
ReactNativeJS: '**check the error of subscriptions', 'Google is indicating that we have some issue connecting to payment.'**
W/BillingHelper: Couldn't find purchase lists, trying to find single data.
W/BillingHelper: Received a bad purchase data.
W/BillingHelper: Couldn't find single purchase data as well.

I'm using this code for upgrade subscription  
**var purchase = await RNIap.requestSubscription(newsku, false, oldsku, purchaseToken, ProrationModesAndroid.DEFERRED);**

### Version of react-native-iap 
6.3.0

### Version of react-native
0.64.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
subscription plan must be changed

### Actual behavior
no any plan change and returning error 
**'Google is indicating that we have some issue connecting to payment.'**

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Follow instructions as per doc
At first-time when purchase subscription get successfully but  after that upgrade /downgrade not working 

Help me with this

**Comment by andresesfm** [comment]
This has been fixed in 7.0.4 please kindly confirm

**Comment by ronakb** [comment]
@andresesfm  Thanks. I and @shivanitp work on the same project.

We tried the latest release. But now it throws. 

purchaseErrorListener', { message: 'The service is unreachable. This may be your internet connection, or the Play Store may be down.',
      debugMessage: '',
      code: 'E_SERVICE_ERROR',
      responseCode: 2 }
      
      
The subscription works the first time. When we try to upgrade/downgrade, it doesn't work. We tried Closed Alpha/Internal Testing with the non-Licensing users. We also tried different prorated methods.

**Comment by andresesfm** [comment]
Have you tried: https://stackoverflow.com/a/53866277/570612 ?

**Comment by ronakb** [comment]
Thanks, @andresesfm. 

I tested 6.3 with a US billing profile and it worked. Apparently, Google India has paused [auto-renewable](https://stackoverflow.com/questions/67824355/the-subscription-cant-have-the-first-charge-for-free-errorcode-developer-erro) [subscriptions](https://support.google.com/googleplay/answer/2476088?co=GENIE.Platform%3DAndroid&hl=en#zippy=%2Cimportant-subscription-information-for-users-in-india).

**Comment by andresesfm** [comment]
Thank you for the info. Closing since it's not related to the library then

**Comment by Nikhil-MathBud** [comment]
hi @ronakb , I am facing upgradation issue ,is this because of google's policy, i guess it must have changed till now. Can you please confirm??
Also can you please help in my issue https://github.com/hyochan/react-native-iap/issues/2940
Thanks
