### ISSUE TITLE
getting status":21002" while validateReceiptIos 

### ISSUE THREAD

**Issue by dharmasat** [dooboolab/react-native-iap#1433]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Steps to reproduce the behavior

USING Sandbox environment

  const receiptBody = {
        "receipt-body": receipt,
        "password":IOSsharedKey,
    }
 const validateReceipt = await RNIap.validateReceiptIos(receiptBody, true)
        .then((receipt) => {
            console.log('receipt' + JSON.stringify(receipt)) 
})

**Comment by prawee** [comment]
Same problem

**Comment by tkapu** [comment]
Same. JS Example works. TS implementation doesn't. The receipt is way shorter as well. iap Version: 7.5.1

**Comment by jcrunge** [comment]
Did you try change the "receipt-body" with 'receipt-data'? https://react-native-iap.dooboolab.com/docs/usage_instructions/receipt_validation
