### ISSUE TITLE
Task 'installDebug' not found in project ':app' when we used flavorDimensions in build.gradle

### ISSUE THREAD

**Issue by tarbundiyahitesh21** [dooboolab/react-native-iap#1435]
i used 

### Version of react-native :"0.63.4"

whenever i added below code in build.gradle inside andorid/app build.gradle file.

    `

    android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId 'com.akg.happigenius'
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2
        versionName "1.0.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file('release.jks')
            storePassword 'android'
            keyAlias 'androiddebugkey=='
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    
    flavorDimensions "appstore"
    productFlavors{
        googlePlay{
            dimension "appstore"
            missingDimensionStrategy "store", "play"
        }
        amazon{
            dimension "appstore"
            missingDimensionStrategy "store", "amazon"
        }
    }
  

`

getting error to run application.

my environment variable set is perfect.

**Error like this**

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

**How to solve this ? any solution ?**

**Comment by andresesfm** [comment]
Use `playDebug` and `amazonDebug` instead

**Comment by tarbundiyahitesh21** [comment]
> Use `playDebug` and `amazonDebug` instead

thanks for answer, but when we run 
`react-native android-run`
that time we get this issue, so what we change?

**Comment by andresesfm** [comment]
you have to specify the variant like so: 
```
yarn android --variant=MY_VARIANT
```
where MY_VARIANT is PlayDebug or AmazonDebug

**Comment by tarbundiyahitesh21** [comment]
> yarn android --variant=MY_VARIANT

same error not working

**Comment by andresesfm** [comment]
According to your config, it should be:
```yarn android --variant=GooglePlayDebug```
