### ISSUE TITLE
Android: subscription upgrade not working since 7.0.0 with various issues (see included list)

### ISSUE THREAD

**Issue by EvelinJK** [dooboolab/react-native-iap#1436]
### Version of react-native-iap
all versions tested from `6.3.0` to `7.0.5`

### Version of react-native
`0.64.1`

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Upgrade on Android works as per documentation.
```
requestSubscription(
          productId, // new sku
          false,
          oldSku,
          oldPurchaseToken,
          ProrationModesAndroid.IMMEDIATE_WITH_TIME_PRORATION, // for upgrade
        )
```

### Actual behavior
- Upgrade broken since release `7.0.0` with the migration to billing client 4.0.0
- Different, reproducable issues with each version (see below).

**How we tested:** 
- Tested with exact same code and same products.
- Only changed plugin version, deployed to a device and tested `regular purchase` and `upgrade` (multiple times)
- (We use the `useIAP` hook from the plugin, if that's important).

**Reproducable behaviours on `upgrade` with these plugin versions:**

`6.3.0` – purchase/upgrade/downgrade working fine  ✅

`7.0.0`–  getting no products from `getSubscriptions()` (no purchase possible)

`7.0.1` – nothing happens after `requestSubscription()` (no store dialog)

`7.0.2` – a regular purchase is started instead of an upgrade although `oldSkuAndroid` and  `purchaseTokenAndroid` are passed to `requestSubscription()` --> if the user buys he will have two active subscriptions in the store instead of changing the original one.

`7.0.3` – same as with `7.0.2`

`7.0.4` – `requestSubscription()` works on regular purchase but on upgrade leads to a `IAPErrorCode.E_SERVICE_ERROR` "The service is unreachable. This may be your internet connection, or the Play Store may be down."
(--> although there is no actual connection issue, nor is the Store down)

`7.0.5` – same as with `7.0.4`

### Tested environment
Real Device
Huawaii Mate 20
Android 9.10

### Steps to reproduce the behavior
See above code example, which we use for upgrading subscription.
We fetch the purchase history to get the latest sku and token. This works fine in all the above versions.

Otherwise we just implemented purchase like shown here: 
https://github.com/hyochan/dooboolab.com/blob/master/src/components/pages/Sponsor.tsx

Since it's working fine on `6.3.0` with the exact same code on our side, there might be undocumented adjustments that are needed to make an upgrade work (?) or the plugin code is not working as expected after the changes introduced since `7.0.0`

**Comment by andresesfm** [comment]
Hello @EvelinJK , thank you for the detailed report. I looked at the code and `E_SERVICE_ERROR` is returned in 2 situations:
1) You might be running the amazon variant on a Google Play device
2) The native billing client is returning `BillingResponseCode.FEATURE_NOT_SUPPORTED`: 
https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode#FEATURE_NOT_SUPPORTED. In this case it could have multiple causes that I can foresee:
a) Google Play Services is not up to date on your device
b) You are not signed into the device with a google account
c) Your device/Android OS is no longer supported by the new native library
d) You are attempting to sell a subscription in an area that does not support it. We've seen people from India for example report that some subscriptions are no longer supported in their region: https://github.com/dooboolab/react-native-iap/issues/1426 https://github.com/dooboolab/react-native-iap/issues/1344

Some of them are farfetched but still worth investigating. Please let us know if any of the apply to your case.

Andres

**Comment by aleemilu75** [comment]
@andresesfm @EvelinJK 
I am also facing an exactly similar issue. Tested on various versions of the library and different proration modes.
1. version 7.0.2 and 7.0.3: 
while doing update oldSkuAndroid and purchaseTokenAndroid are passed to requestSubscription() --> google pop up comes up and after buying it, the user will have two active subscriptions in the store instead of changing the original one.
2. version 7.0.4 and 7.0.5: 
while upgrading no matter which proration mode is used google pop-up always throws the same error. 
{"message": "The service is unreachable. This may be your internet connection, or the Play Store may be down.","code":"E_SERVICE_ERROR", "debugMessage":"","responseCode":2}

a. Google Play services are up to date.
b. Signed in to the device google account and play store too.
c. Android version is 10. (not an outdated one).
d. Also, not trying to upgrade the subscription in India as we are aware that Google India has restrictions regarding auto-renewable subscriptions. 
So we are using a different country billing account where auto-renewable subscriptions are active and subscriptions are being auto-renewed. 

Only, upgrade scenario is not working.

**Comment by EvelinJK** [comment]
Hi @andresesfm 

Thanks for the quick feedback. 

**I'm fairly certain that 1. and 2. a) to d) are not causing the issue:**
- We definitely don't run the amazon variant.
- Device is fairly new, supported by the library and everything is up to date and it's not a general purchase issue, but only on update.
- We test with our setup that is already in use in production since we're only "migrating" our App from Cordova to RN. So our store setup, products, backend validation, sandbox environment etc. are all fine and working, and we purchase from the location where the products are sold/supported.

As mentioned, everything worked fine with version `6.3.0` of the plugin. 
I think it's unlikely that the issues are caused on our side since I tested all versions after each other, using the exact same code, products and device.

_UNLESS there are changes needed on how to handle upgrades with the plugin with the subsequent versions after `6.3.0`, that I can not find any documentation for (?)_ 

**For e)** 
We use the `useIAP` hook on startup. According to the instructions `initConnection()` is not necessary anymore with the hook:
https://medium.com/dooboolab/announcing-react-native-iap-hooks-96c7ffd3f19a

> With useIAP hook, these are handled automatically. You do not have to call initConnection imperatively and calling useIAP() is enough for that



We reverted to `6.3.0` for now, but with that we're missing some bug fixes obviously.

But, yeah. Exactly the same issues with the versions that @aleemilu75 reported above.

**Comment by andresesfm** [comment]
Looks like there was some legacy code that was causing some confusion. Here is the fix for the issue you are reporting @EvelinJK  @aleemilu75 : https://github.com/dooboolab/react-native-iap/pull/1438 . Would you be so kind to test and confirm it fixes it.

**Comment by EvelinJK** [comment]
Thanks for the quick adjustment @andresesfm 

I removed the oldPurchaseSku as shown in your changes and tested your fix.
The update subscription dialog from the store is now shown correctly – showing info of the old and the new product – after
`requestSubscription(
          productId, // new sku
          false,
          oldPurchaseToken,
          ProrationModesAndroid.IMMEDIATE_WITH_TIME_PRORATION, // for upgrade
        )` 
        

**BUT:** 
After the purchase dialog from Play Store is finished, I'm not getting the receipt with this branch. 
`currentPurchase` is not updating from the `useIAP` hook, so I cannot validate and finish the receipt.
Not for an update and also not for a regular subscription purchase.

Maybe @aleemilu75 can test the branch too? Not sure what causes this.

In `7.0.5` the `currentPurchase` still updates correctly after a regular purchase.

But I did have to do some magic to get our project to do a debug build with the branch from your fork since it's a non-npm package. So I'm not 100% sure if it might be related to that... (or if there's an easier way to test this? :D)

**Comment by andresesfm** [comment]
Thank you for trying @EvelinJK an easy way to try is to change `"react-native-iap":"7.0.5"` to `"react-native-iap":"git://github.com/andresesfm/react-native-iap.git#4440c644ca34bb57b79d8d3054126be6ddc33a08"` and then running `yarn` or `npm install`

**Comment by hyochan** [comment]
Closes via #1438

**Comment by EvelinJK** [comment]
Thanks @andresesfm
I just tested with the new release `7.1.0` and it seems to work fine now. 
The receipt issue was probably due to the wonky installation :) 

Thanks for the quick fix again 👍

**Comment by hyochan** [comment]
Yes, huge thanks to @andresesfm for continuing maintenance and being a life savior for many others.

@andresesfm Please submit $100 in https://opencollective.com/react-native-iap for a small gift 🙏

**Comment by andresesfm** [comment]
Especial thanks to @EvelinJK and @aleemilu75  for a detailed description of the issue and following up. Thank you @hyochan, I'm happy to help the community

**Comment by aleemilu75** [comment]
@andresesfm @EvelinJK I tested it too. Seems to be working fine without any glitches.
Though I have just 1 question, is there any particular reason why an "oldSKU" is not required while upgrading the subscriptions?

**Comment by andresesfm** [comment]
The reason is that it got removed by the native library version 4.0.0. to which we migrated recently

**Comment by iamyamar** [comment]
hey using react-native-iap v7.6.5 does these issue still persist in latest version of library or should i upgrade to latest?
