### ISSUE TITLE
Support for SKPaymentTransactionObserver

### ISSUE THREAD

**Issue by karapish** [dooboolab/react-native-iap#1437]
Hello,

As part of an IAP product submission into App Store, there is the option to include IAP promotion and feature it in the store. More details available via this link https://help.apple.com/app-store-connect/#/dev84b80958f. 
![image](https://user-images.githubusercontent.com/9142734/127303172-37fb2c6a-b04e-42e9-a97b-e5a4d9229743.png)

Does RN IAP package implements or supports SKPaymentTransactionObserver?

Ty

**Comment by phillip-kic** [comment]
Yes it looks like `RNIapIos` interface implements `SKPaymentTransactionObserver`.

And there's a FAQ describing how to use this: https://react-native-iap.dooboolab.com/docs/faq#how-do-i-handle-promoted-products-in-ios

**Comment by andresesfm** [comment]
Thank you for the reference @phillip-kic. Closing this issue
