### ISSUE TITLE
iOS RNIap.buyProductWithoutFinishTransaction(productId) neither resolves nor rejects

### ISSUE THREAD

**Issue by TAM360** [dooboolab/react-native-iap#1442]
### Version of react-native-iap
2.5.5
### Version of react-native 
63.4
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
buyProductWithoutFinishTransaction() either should resolve or reject with error.
### Actual behavior
nothing happens, application continues to wait for the response
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior

I am currently using RNIap in a legacy application. For in app purchases, I am using **RNIap.buyProductWithoutFinishTransaction(productId)** together with **RNIap.getProducts(sku)**. Mostly, it works fine and returns a successful transaction. In other cases however, the API neither resolves nor rejects. getProducts() API always returns the result (I verified this couple of times). Similar [issue](https://github.com/dooboolab/react-native-iap/issues/1223) was reported earlier this year but got no response. Here's the code snippet.

```javascript
RNIap.getProducts(sku)
    .then(product => {
        console.log("product", product);
        RNIap.buyProductWithoutFinishTransaction(productId)
             .then(purchase => {
                 /*some internal processing*/
             })
             .catch(error => {
                 console.log(error);
             });
    })
    .catch(error => { console.log(error) });
```

What could be the reason behind this issue? For further context, I observed this issue in iOS v14.6 in iPhone X & iPhone 6 devices.

**Comment by andresesfm** [comment]
Hello @TAM360 , `buyProductWithoutFinishTransaction` has been deprecated and removed for a long time. Please update your version of `react-native-iap` to the latest. I'll close since this is no longer supported. Please feel free to  reopen if you encounter any other issues.
