### ISSUE TITLE
RNIap.purchaseUpdatedListener callback returns undefined

### ISSUE THREAD

**Issue by jeremiahlachica** [dooboolab/react-native-iap#1446]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
4.5.4 (I'm trying to upgrade to newer version but failing because of my react-native version. This is the latest version I can use for my project.)

### Version of react-native
0.59.8

### Platforms you faced the error (IOS or Android or both?)
iOS only (haven't set up Android yet)

### Expected behavior
RNIap.purchaseUpdatedListener(()) callback should return a value

### Actual behavior
```
RNIap.purchaseUpdatedListener((purchase) => {
  console.log(purchase); // undefined
}) 
```

### Tested environment (Emulator? Real Device?)
Simulator: I can only test on simulator
Real Device: I don't why when I call getProducts() it just returns empty array. This might be another issue.

### Steps to reproduce the behavior
- Purchase a product
- Confirm
- Dialog will show saying: "You're all set. Your purchase was successful. [Environment: Xcode]"
- purchaseUpdatedListener callback doesn't return any value or transaction receipt. It's just undefined.

**Comment by andresesfm** [comment]
@jeremiahlachica can you please share more context on what makes it difficult to use the latest version?
> (I'm trying to upgrade to newer version but failing because of my react-native version. This is the latest version I can use for my project.) 

Do you see an error while compiling?
I'm curious as to how we can make it available to more people

**Comment by jeremiahlachica** [comment]
@andresesfm 

If I try to use the latest version or any version above 4.5.4, I get this when doing pod install:

```
[!] Unable to find a specification for `React-Core` depended upon by `RNIap`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by lay-mand** [comment]
Had the same issue. Had configurated .storekit for testing IAP locally. Always got same **Dialog will show saying: "You're all set. Your purchase was successful. [Environment: Xcode]"**, but listener returns **undefined** 

Created manager as on example: https://react-native-iap.dooboolab.com/docs/usage_instructions/purchase
Package ver. 6.0.6 (also same on latest)

**Comment by lay-mand** [comment]
@andresesfm also got **requestReceiptDataWithBlock with force refresh: NO.**  on xCode terminal. How can I get valid receipt data?

**Comment by Janak-Nirmal** [comment]
Any update on this ? I have debugged the purchase scenario on iOS and it seems following function is returning nil and thus callback is returning null. 

```
- (NSData *) receiptData {
    NSURL *receiptURL = [[NSBundle mainBundle]appStoreReceiptURL];
    NSData *receiptData = [[NSData alloc]initWithContentsOfURL:receiptURL];
    return receiptData;
}
```

This was working perfectly fine until couple of days back and all of a sudden it started returning undefined

**Comment by andresesfm** [comment]
> @andresesfm
> 
> If I try to use the latest version or any version above 4.5.4, I get this when doing pod install:
> 
> ```
> [!] Unable to find a specification for `React-Core` depended upon by `RNIap`
> 
> You have either:
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> ```

This is most likely due to the `react-native` version you are using. I had to do these changes to the sample app to get it to compile: https://github.com/dooboolab/react-native-iap/pull/1465/files

**Comment by Singed-jj** [comment]
Any update exists? I met same issue.
