### ISSUE TITLE
7.1.0 crashes on Android when making a purchase

### ISSUE THREAD

**Issue by mars-lan** [dooboolab/react-native-iap#1448]
See https://github.com/dooboolab/react-native-iap/pull/1438#discussion_r682532329 for root cause.

**Comment by sdiaz** [comment]
`Fatal Exception: com.facebook.react.bridge.NativeArgumentsParseException
RNIapModule.buyItemByType got 9 arguments, expected 8`

**Comment by jonathangilbert02** [comment]
See #1452
