### ISSUE TITLE
Crash on android when calling getProducts()

### ISSUE THREAD

**Issue by mathmania** [dooboolab/react-native-iap#1454]
### Version of react-native-iap
"react-native-iap": "^7.2.0",
### Version of react-native
"react-native": "0.63.3",
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
The function `getProducts()` should use the android module and return a list of products.
### Actual behavior
When calling `getProducts()` the function `getIosModule()` is called even if the OS is android. I then get the error `IAPErrorCode.E_IAP_NOT_AVAILABLE` throwned in `checkNativeiOSAvailable()`.
### Tested environment (Emulator? Real Device?)
Real Device, Samsung SM-G950U1
### Steps to reproduce the behavior
1. Purchase a product on android
2. The error E_IAP_NOT_AVAILABLE is thrown

I'll try to push a fix ASAP!

**Comment by hyochan** [comment]
I've just made a `PR` in #1455. I found a miss intention code on android.

@mathmania
Could you kindly test out `7.2.1-rc2` by `yarn add react-native-iap@next`?

**Comment by andresesfm** [comment]
Hello @hyochan @mathmania . This is my proposed fix: https://github.com/dooboolab/react-native-iap/pull/1456 I identified the problem as being that I went too far removing the wrapping blocks causing the ios check to evaluate every invocation of the method regardless of the platform. Please excuse the inconvenience

**Comment by feruzm** [comment]
@hyochan I am getting same error `E_IAP_NOT_AVAILABLE` on both iOS and Android. rn 63.4, latest iap

**Comment by hyochan** [comment]
> @hyochan I am getting same error `E_IAP_NOT_AVAILABLE` on both iOS and Android. rn 63.4, latest iap

What version are you using? Please try 7.2.1

**Comment by feruzm** [comment]
> > @hyochan I am getting same error `E_IAP_NOT_AVAILABLE` on both iOS and Android. rn 63.4, latest iap
> 
> What version are you using? Please try 7.2.1

It was v7.2.0.
Looks like 7.2.1 working 🎉  Thank you!
