### ISSUE TITLE
`getSubscriptions` returning only one subscription product

### ISSUE THREAD

**Issue by andrewdazs** [dooboolab/react-native-iap#1459]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap

`7.1.0`

### Version of react-native

`0.61.5`

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

I'm passing to `getSubscriptions` method and array of skus and it should return all subscription products at once.

### Actual behavior

The method only return one subscription product

### Tested environment (Emulator? Real Device?)

Real device

### Steps to reproduce the behavior

Just call `getSubscriptions` passing an array with all skus and it will return just one subscription product.

**Comment by andrewdazs** [comment]
Sorry guys but I was using StoreKit to get the subscriptions without realizing it.

**Comment by andresesfm** [comment]
@andrewdazs does this mean we can close this issue?

> Sorry guys but I was using StoreKit to get the subscriptions without realizing it.

**Comment by andrewdazs** [comment]
@andresesfm Yes we can, thank you.
