### ISSUE TITLE
The E_IAP_NOT_AVAILABLE error occurrs in RNIap.clearTransactionIOS since v7.2.0.

### ISSUE THREAD

**Issue by kkoudev** [dooboolab/react-native-iap#1464]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap

7.2.0 (7.1.0 works fine)

### Version of react-native

0.64.2

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

E_IAP_NOT_AVAILABLE error not occur.

### Actual behavior

Always throw E_IAP_NOT_AVAILABLE error.

### Tested environment (Emulator? Real Device?)

Real Device

### Steps to reproduce the behavior

1. call RNIap.initialize()
2. call RNIap.clearTransactionIOS()

**Comment by andresesfm** [comment]
Hello @kkoudev, could you please try `7.3.0`? we had some stability issues with `7.2.0`

**Comment by kkoudev** [comment]
@andresesfm This issue also occurs in 7.3.0.

**Comment by andresesfm** [comment]
Hello @kkoudev, I have tested using the sample app with these updates: https://github.com/dooboolab/react-native-iap/pull/1465 It doesn't fail with the error you mention. I noticed that it failed when calling an `android`-only method such as `RNIap.flushFailedPurchasesCachedAsPendingAndroid();` which now fails if you call it from iOS, a simple check for the platform fixes it

**Comment by kkoudev** [comment]
@andresesfm Certainly, I was calling RNIap.flushFailedPurchasesCachedAsPendingAndroid () after the initConnection was completed. By determining the platform, the error no longer appears. thank you!!
