### ISSUE TITLE
[question] Check product was consumed

### ISSUE THREAD

**Issue by charleston10** [dooboolab/react-native-iap#1472]
Is it possible to check if the product has been consumed?

Because in function has `await iap.finishTransaction(inAppPurchase, true);`
First param - object InAppPurchase
Second param - isConsumable boolean

### Version of react-native-iap
7.3.0

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
Android

**Comment by andresesfm** [comment]
"consuming" a product is up to you. The logic is as follows: 
Make a purchase
If successful, grant user access to the content/coins, level, etc.
Call finish transaction. This will acknowledge that the item has been consumed by the user.

Note: id you are referring to `isConsumable`, the term is used to distinguish between one-time purchases and subscriptions

**Comment by charleston10** [comment]
@andresesfm thanks by your help

I ran a new test leaving the consumable parameter as false
And now the message 'error you already own this item' appears

The scenario I need to do is that the user can buy an item once, then use it and after use he can buy the same item again. As if it were coins.

If the logic remains in my system, I would have to give the user the possibility to buy the same item several times

I tried to take a look at the documentation, but I didn't find it.
Can you tell me if this is possible? Thanks

**Comment by andresesfm** [comment]
It looks like you are indeed looking to use consumable products. In which case, you'll need to pass true to `isConsumable`. Going back to your original question. It's up to you to decide if they are consumable or non-consumable. If you mark them as consumable (by passing `isConsumable` as true), then the next time the user tries to purchase they will be available to purchase again. 

From. my previous answer: 

The logic is as follows:
Make a purchase
If successful, grant user access to the content/coins, level, etc.  <-------- Here is your chance to either store the result locally or in your backend. Backend is safer as it can be combined with receipt validation. ---------<
Call finish transaction. This will acknowledge that the item has been consumed by the user.

 
I hope this helps

**Comment by charleston10** [comment]
I understood; now it made sense

I did a new test, marking it as consumable
On the google panel in the purchase history you have the following view

**Status**
-> Payment pending
-> Chargeable (The customer's form of payment was authorized for 0.00 and passed all risk checks)

This means that to finish the consumable product I need to use the function to finish the transaction (acknowledgePurchaseAndroid)

After call **acknowledgePurchaseAndroid**

**Status**
-> Payment pending
-> Chargeable (The customer's form of payment was authorized for 0.00 and passed all risk checks)
-> Charged (The customer's form of payment was successfully charged for 0.00)

it helped a lot
