### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ahmed3ly** [dooboolab/react-native-iap#1473]
i can not build the application i try to install 
yarn add react-native-iap
    "react-native-iap": "^7.3.0",
i have try to link it but same error any help ? 
also i try 
yarn android --variant=GooglePlayDebug

<img width="1440" alt="Screen Shot 2021-08-28 at 2 25 37 PM" src="https://user-images.githubusercontent.com/89412911/131217863-114a4802-41bc-4ff8-873f-1f7bef1abbfe.png">

**Comment by lc3t35** [comment]
Did you add `missingDimensionStrategy 'store', 'play'` in app/build.gradle as requested by [documentation](https://react-native-iap.dooboolab.com/docs/installing/) ?

**Comment by charleston10** [comment]
> Did you add `missingDimensionStrategy 'store', 'play'` in app/build.gradle as requested by [documentation](https://react-native-iap.dooboolab.com/docs/installing/) ?

This worked for me
