### ISSUE TITLE
Android Plugin [id: 'com.github.sherter.google-java-format', version: '0.9'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by tgreco** [dooboolab/react-native-iap#1474]
### Version of react-native-iap
7.3
### Version of react-native
0.63.2
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
App builds 
### Actual behavior
App fails to compile on android with error Plugin [id: 'com.github.sherter.google-java-format', version: '0.9'] was not found in any of the following sources:
### Tested environment (Emulator? Real Device?)
Real device 
### Steps to reproduce the behavior
Build app

**Comment by andresesfm** [comment]
Do you have `mavenCentral` in your gradle repos?

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1498
