### ISSUE TITLE
Error E_IAP_NOT_AVAILABLE And iOS 14: RNIap.getProducts()/RNIap.getSubscriptions Unknown Error  thrown 

### ISSUE THREAD

**Issue by praful1021** [dooboolab/react-native-iap#1478]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
7.3.0

### Version of react-native
0.61.4

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
products/subscription to be fetched.

### Actual behavior
unknown error being returned
error thrown: E_IAP_NOT_AVAILABLE

### Tested environment (Emulator? Real Device?)
Real Device/ iOS Simulator

### Steps to reproduce the behavior
Just call RNIap.getProducts() or RNIap.getSubscriptions().

**Comment by devuco** [comment]
I am experiencing the same issue in iOS real device
Did you resolve it?

**Comment by kabus202** [comment]
any update on this matter?

**Comment by fbotalla** [comment]
Same here

**Comment by dmitryusikriseapps** [comment]
+1

**Comment by dmitryusikriseapps** [comment]
I've found the reason. I called methods for the android platform without a condition `Platform.OS === 'android'`. It produces an error now if it's called for the different platforms.

**Comment by caoyongfeng0214** [comment]
same here.
iOS 15

```js
        RNIap.initConnection().then(() => {
            
        }).catch(ex => {
            alert(ex.message); // catched exception:  E_IAP_NOT_AVAILABLE
        })
```

Is there some configuration or prerequisites required?

**Comment by catmans1** [comment]
@caoyongfeng0214 
```
/**
 * Init module for purchase flow. Required on Android. In ios it will check wheter user canMakePayment.
 * @returns {Promise<boolean>}
 */
export declare const initConnection: () => Promise<boolean>;
```
Because of this above.
on iOS don't need implement it.
We can change the code a bit
```
if (Platform.OS === 'android') {
        RNIap.initConnection().then(() => {
            
        }).catch(ex => {
            alert(ex.message); // catched exception:  E_IAP_NOT_AVAILABLE
        })
}
```

**Comment by liquidvisual** [comment]
@catmans1 Does this mean we don't need to initConnection for iOS at all? I wish the docs mentioned that.

**Comment by princefishthrower** [comment]
@liquidvisual - did you find this was actually the case?
