### ISSUE TITLE
requestPurchase promise never settles when user cancels 

### ISSUE THREAD

**Issue by henninghall** [dooboolab/react-native-iap#1479]
### Version of react-native-iap
7.3.0

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
iOS, not tested on android

### Expected behavior
`requestPurchase()` returns a promise. When the user cancels the payment I expect the promise to reject. 

### Actual behavior
When a user cancels the payment the promise from `requestPurchase` is not settled, neither resolved nor rejected.

I believe the problem lays in this conditional, preventing the rejection from happening:
https://github.com/dooboolab/react-native-iap/blob/b527d2bcd0678f42ffe80fd3e2846b58622ef226/ios/RNIapIos.m#L465

### Steps to reproduce the behavior
1. Use this code

```javascript
try {
    await requestPurchase(productId)
    // never gets here
} catch(e) {
    // never gets here
}
```
2. Cancel payment when the payment sheet is shown. Either by pressing the cancel button or touching outside the bottom sheet.

**Comment by andresesfm** [comment]
I agree that this is a problem

**Comment by andresesfm** [comment]
I have created a release with this fix on my fork: https://www.npmjs.com/package/@iap.dev/react-native-iap/v/7.3.1

**Comment by andresesfm** [comment]
https://github.com/andresesfm/react-native-iap/commit/f0496266791a3c3118268c8a441f152aa0d3e8d2

**Comment by jaaywags** [comment]
+1 Seeing this issue too

**Comment by FMiscia** [comment]
Same

**Comment by mvrty** [comment]
Same problem on Android (with React Native 0.65.1)

**Comment by textual** [comment]
feels like this is happening to me with ios subscriptions
