### ISSUE TITLE
Prices are gone on IOS without doing anything

### ISSUE THREAD

**Issue by ugrdursun** [dooboolab/react-native-iap#1489]
Hello,

I am using v5.2.0 with RN 0.61.5. Everything was ok, I am getting prices with:

```
    RNIap.getSubscriptions(itemSkus).then((info) => {


      info.map(item => {

        if(item.productId == 'lite_plan') this.setState({ liteprice: item.localizedPrice });
        if(item.productId == 'pro_plan') this.setState({ proprice: item.localizedPrice });

      })





    }).catch(e => {

   
      Alert.alert(e)


    })
```

The problem is, this is not working anymore, prices are not coming up (I did not update app or changed anything)

My new build is rejected by apple because of this. I checked the **live version which is already on app store** (approved 1 month ago) and that one is also same (prices not appearing). So its not code related, was working perfectly maximum 2-3 weeks ago.

All other functions are working (purchase and restore)

Do you have any idea why this happened ?

### Version of react-native-iap

5.2.0

### Version of react-native

0.61.5

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

Returning prices normally

### Actual behavior

Prices not returning

### Tested environment (Emulator? Real Device?)

Both

**Comment by Cavech84** [comment]
I have the same problem, it seems that in the object there is no more localizedPrice but only price

**Comment by ugrdursun** [comment]
> I have the same problem, it seems that in the object there is no more localizedPrice but only price

You are right. On android, there is no problem. But returning object from AppStore contains just price, currency and product id. 

I made a temporary fix by changing localizedPrice to price for iOS but i wonder why this happened and is there anything else to consider.....

**Comment by mifi** [comment]
For us this also suddenly started happening in production without any code changes. But I'm not getting **any** data returned from `getSubscriptions`. Just and empty list `[]`. Getting the same in dev now sow will investigate.

**Comment by ugrdursun** [comment]
> For us this also suddenly started happening in production without any code changes. But I'm not getting **any** data returned from `getProducts`. Just and empty list `[]`. Getting the same in dev now sow will investigate.
> 
> Update 1: Our issue was due to Agreements for Paid Apps had expired in apple developer console. After accepting, the products returned correctly by `getProducts`. For reference: the entries **do** have `localizedPrice` as well.
> Update 2: Turns out, even after accepting the agreement, `getSubscriptions` is still returning an empty list in production, but not in dev...
> Update 3: After an hour or so, `getSubscriptions` eventually also returned the correct data.

Thanks for investigation, but getSubscriptions are returning OK on me. Also paid apps agreement status shows Active (theres nothing to accept or no update). I think we deal with different issues here.

**Comment by mifi** [comment]
Yes, I eventually realized it's a different issue. Just wanted to leave it in case someone else goes searching for the problem.

in the case of your issue, could it have to do with language on the phone? or available markets/countries for the in app subscirptions? it's very strange that only localizedPrice is missing...

**Comment by mouhcine007** [comment]
Guys did anyone find a solution for this?. We are facing the same issues as well from our end some prices working fine and some prices above 499.99$ not working

**Comment by andresesfm** [comment]
Can you please help us check if this is still an issue on 8.x.x for iOS? 
If it still happens on 8.x.x  We'll reopen. Thank you

Note: I'm not trying to minimize the issue. I see there are multiple posts about it in various forms and I'm trying to make sense of it but with no help and it being reported on such an old version of the library is close to impossible. Thank you for understanding
