### ISSUE TITLE
empty data on AvailablePurchases or purchaseHistory

### ISSUE THREAD

**Issue by vadermemo** [dooboolab/react-native-iap#149]
### Version of react-native-iap
0.3.20
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
An  array not empty of AvailablePurchases or purchaseHistory
### Actual behavior
Empty data on iOS, on Android all is fine

### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior
Send the next snippet

const purchases = await RNIap.getAvailablePurchases();
      console.log("purchases.stringify:" + JSON.stringify(purchases));

and the purchases always are empty.

**Comment by JJMoon** [comment]
How many products in your application?

**Comment by JJMoon** [comment]
The method actually calls restoreCompletedTransactions. So, if you don't have pre-purchased non-consumable products with that id (sandbox tester), it will return empty list.

**Comment by vadermemo** [comment]
@JJMoon  I got 5 products, 3 consumable y 2 non-consumable

I have this message on all the products "This In-App purchase has already been bought. It will be restored for free". So I think can get those 2 non.consumables products with getPurchaseHistory or getAvailablePurchases, but I only get a empty array.

**Comment by vadermemo** [comment]
@JJMoon Woooow! With a new sandbox tester all is fine, bro.
I think I make a mistake with the other user tester' data.
Thanks a lot.
This bug is not real, please close it. My bad.

**Comment by JJMoon** [comment]
@vadermemo Congrats!! 
That happens all the time. Never mind.. 
Closing this issue.  Thank you for your concern...
