### ISSUE TITLE
getIosModule(...).getItems(...).filter is not a function when I try to get the subscriptions 

### ISSUE THREAD

**Issue by saeedtkh** [dooboolab/react-native-iap#1490]
**Hi everyone, when I try to get the products from app store using the flowing code I got the error as below:**
```
getIosModule(...).getItems(...).filter is not a function
    at VM4 index.bundle:285771
    at step (VM4 index.bundle:285625)
    at Object.next (VM4 index.bundle:285555)
    at VM4 index.bundle:285527
    at tryCallTwo (VM4 index.bundle:3428)
    at doResolve (VM4 index.bundle:3592)
    at new Promise (VM4 index.bundle:3451)
    at __awaiter (VM4 index.bundle:285506)
    at Object.getSubscriptions (VM4 index.bundle:285765)
    at eval (InAppPurchaseScreen.…dule=false&shal…:94)
```
**Here is my code:**
```
import IAP from "react-native-iap";
const pItems = Platform.select({
  ios: [
    'xxx',
  ],
  android: [
    'xxx',
  ],
});

useEffect(() => {
    IAP.initConnection().catch((e) => {
      console.log("error in connection to store", e);
    }).then(() => {
      console.log("pippo1 connection to store");
      IAP.getSubscriptions(pItems).catch((e) => {
        console.log("pippo1 error in collecting items from store", e);
      }).then((res) => {
        console.log("pippo1 collecting items from store");
        setProducts(res)
        console.log("pippo1 res", res);
      })
    })
  }, [])

```

**Here are other some info:**

### Version of react-native-iap: 
    "react-native-iap": "^7.2.1-rc3",

### Version of react-native: 
0.63.2

### Platforms you faced the error (IOS or Android or both?) 
iOS

### Expected behavior: 
Getting the products from app store

### Actual behavior: 
I am receiving the above error -> the error can be seen in the console.log of "pippo1 error in collecting items from store".

### Tested environment (Emulator? Real Device?) 
Real device

### Steps to reproduce the behaviour:
 just put my code with my react-native version and try to get product data from app store. 

Thank you very much in advance.

**Comment by andresesfm** [comment]
`getItems` returns a promise

**Comment by andr50** [comment]
I'm seeing this same issue, though it's triggering from simply getting the store items (no subscriptions, just one iAP)

` const products = await RNIap.getProducts(storeItems).catch((e)=> {
                console.log("error in getting products", e);
            });`

That's throwing this error:

`error in getting products [TypeError: getIosModule().getItems(skus).filter is not a function. (In 'getIosModule().getItems(skus).filter(function (item) {
                  return skus.includes(item.productId);
                })', 'getIosModule().getItems(skus).filter' is undefined)]`

Using:  "react-native-iap": "^9.0.0-beta",

**Comment by andresesfm** [comment]
Thank you for the info @andr50, @saeedtkh . the new beta4 should have it as it was fixed with this https://github.com/dooboolab/react-native-iap/pull/1767
