### ISSUE TITLE
Error Meet Google Play Billing Library Version 3

### ISSUE THREAD

**Issue by alexol91** [dooboolab/react-native-iap#1493]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

Version of react-native-iap: 7.4.1

Version of react-native: 0.64.2

Platforms: Android

Message Error:
We have detected that this app uses an unsupported version of Play Billing. Please update to version 3 (or later) of the Billing Library to publish this application. More information on version 3 of the Billing Library

Description:
I'm trying to upload a new Application and it shows me a message saying that new applications after September 2 must have version 3 of the Billing Library. I have updated react-native-iap to the latest version and the error persists. Checking the Change log, I thought this was resolved in version 7.0.0 (I'm using 7.4.1)

Best!

**Comment by mayconline** [comment]
check it in `/android/app/build.gradle , ln 190,`

change `billing_version` to `def billing_version = "3.0.0"`

v4 already exists, but I haven't tested it yet to see if it works

**Comment by alexol91** [comment]
I have checked my gradle and I don't have that variable. I tried to put it and it did not work, but what I did was add in my build.gradle the same implemantatio that has the node module of react-native-iap

I added in the first line of dependencies:
implementation "com.android.billingclient: billing: 4.0.0"

**Comment by nguyenvanphuc2203** [comment]
same issue for me! any update?

**Comment by nguyenvanphuc2203** [comment]
> I have checked my gradle and I don't have that variable. I tried to put it and it did not work, but what I did was add in my build.gradle the same implemantatio that has the node module of react-native-iap
> 
> I added in the first line of dependencies: implementation "com.android.billingclient: billing: 4.0.0"

thanks, it resolve issue! save my day! 🗡️
