### ISSUE TITLE
NativeEventEmitter warnings on ReactNative 0.65

### ISSUE THREAD

**Issue by yspektor** [dooboolab/react-native-iap#1496]
### Version of react-native-iap
7.4.1

### Version of react-native
0.65.1

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
No warnings

### Actual behavior
Multiple Logbox warnings: 
```
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
1. Upgrade to reactnative 0.65.x
2. Run `yarn android` to start app on android device

**Comment by yspektor** [comment]
To fix, add this to `RNIapModule.java`

```java
  @ReactMethod
  public void addListener(String eventName) {
    // Keep: Required for RN built in Event Emitter Calls.
  }

  @ReactMethod
  public void removeListeners(double count) {
    // Keep: Required for RN built in Event Emitter Calls.
  }
```

**Comment by mayconline** [comment]
same problem =/

**Comment by SergiOnGit** [comment]
Same here

**Comment by andkom** [comment]
same in 7.5.0

**Comment by sbin1211** [comment]
@hyochan , it happens since RN0.65,  i created one pull request for it, pls have a review. thanks.

**Comment by fernandoVicentei** [comment]
> Para solucionarlo, agregue esto a `RNIapModule.java`
> 
> ```java
>   @ReactMethod
>   public void addListener(String eventName) {
>     // Keep: Required for RN built in Event Emitter Calls.
>   }
> 
>   @ReactMethod
>   public void removeListeners(double count) {
>     // Keep: Required for RN built in Event Emitter Calls.
>   }
> ```

En que lugar se tiene que agregar esas lineas de codigo estimado?

**Comment by LuisNetSpot** [comment]
Im getting this error on iOS with RN 0.66.3

Is there any way to solve it?

Thanks

**Comment by mifi** [comment]
can confirm this is fixed in 7.5.1

**Comment by victoriaSh** [comment]
Got the same warnings with react-native@0.66.4 and react-native-iap@8.0.0-rc.4 
Added this code to RNIapModule.kt and warnings disappeared. 
I'm not good at Kotlin. Correct me If something is wrong, please. 
```
    @ReactMethod
    fun addListener(type: String?) {
        // Keep: Required for RN built in Event Emitter Calls.
    }

    @ReactMethod
    fun removeListeners(type: String?) {
        // Keep: Required for RN built in Event Emitter Calls.
    }

```

**Comment by junedomingo** [comment]
https://github.com/dooboolab/react-native-iap/issues/1496#issuecomment-995397029

Can confirm this. I'm on rn@66.4 and riap@8.0.1

**Comment by mifi** [comment]
I think this is because the addListener and removeListener functions were removed from v7 to v8.

See this commit that fixed v7: https://github.com/dooboolab/react-native-iap/pull/1544/files

v8 (master) does not have this code anymore:
https://github.com/dooboolab/react-native-iap/blob/main/android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt

So somehow they got lost in translation upon rewriting to kotlin. Should be pretty easy to re-add though! I'll reopen this

**Comment by ralppppy** [comment]
Any update on this?

**Comment by mifi** [comment]
I don't speak kotlin but PR is welcome!

**Comment by sajorahasan** [comment]
As suggested by @victoriaSh adding below code in node_modules/react-native-iap/android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt file fix the warning.

`@ReactMethod
    fun addListener(type: String?) {
        // Keep: Required for RN built in Event Emitter Calls.
    }

    @ReactMethod
    fun removeListeners(type: Double?) {
        // Keep: Required for RN built in Event Emitter Calls.
    }`

**Comment by mifi** [comment]
I believe this is fixed.
