### ISSUE TITLE
Can't receive the receipt

### ISSUE THREAD

**Issue by rmoreira0** [dooboolab/react-native-iap#15]
Hi!

I'm having a problem when i buy a item. Everything works great, i can prepare the function, load the products from the store but when i purchase the item, i can't receive the receipt, doesn't show anything. This is the code i'm using when trying to buy:

```
RNIap.buyItem(productId).then(receipt => {
    alert(JSON.stringify(receipt));
}).catch(error => {
    alert(JSON.stringify(error))
});
```
The purchase works because i receive the email from google and in the android studio i can see the purchase:

![Image](https://i.imgur.com/liJheeA.png)

Thanks for the great work!

**Comment by dooboolab** [comment]
@rmoreira0
Hi there. The screenshot you pasted seems you are getting the receipt correctly.
Can you give me more specific information? Or if you don't know what receipt should look like in android, the json string you printed
```
return : {"orderId".....
```
is correct receipt.

**Comment by rmoreira0** [comment]
@dooboolab 
The problem is i can't receive the receipt in the react native. I think there is a problem firing the callback, in this line

` buyItemCB.invoke(null, purchases.get(0).getOriginalJson());`

Thank you.

**Comment by dooboolab** [comment]
@rmoreira0 
Ah.. I now got what you mean. Maybe it is because I let android method to consume item right away when purchasing it. Therefore I am suspecting if your item is not consumable, it may occur something wrong. I just get rid of it now in npm package 0.2.6. Could you try this?

Also it would be good if you share any error messages.

**Comment by rmoreira0** [comment]
Your last version didn't work and unfortunately there is no error messages :/

I experimented put two alerts, one inside the RNIapModule.buyItem and the other one outside. The first one "Need to call 1" appears, but the other one "Need to call 2" don't appears

```
export const buyItem = (item) => {
    if (Platform.OS === 'ios') {
        return new Promise(function (resolve, reject) {
            // RCT_EXPORT_METHOD(purchaseItem:(NSString *)keyJson callback:(RCTResponseSenderBlock)callback) {
            RNIapIos.purchaseItem(item, (err, purchase) => {
                if (err) {
                    reject(err);
                    return;
                }
                // return string
                resolve(purchase);
            });
        });
    } else if (Platform.OS === 'android') {
        return new Promise(function (resolve, reject) {
            alert("Need to call 1")
            RNIapModule.buyItem(item, (err, purchase) => {
                alert("Need to call 2")
                if (err) {
                    reject(err);
                    return;
                }
                resolve(purchase);
            });
        });
    }
};
```

Thank you.

**Comment by dooboolab** [comment]
@rmoreira0 
I've just tested in android device and I could not reproduce your problem.
Could you please share more codes of yours where it is not receiving receipt?

Thank you.

**Comment by rmoreira0** [comment]
@dooboolab

Oh man... Everything is working great, the problem is that i was expecting to see the alert and the alert never appears. So i save the receipt in the state and its there xD

I'm sorry for this and thank you so much for the help!
Keep up the great work!

**Comment by dooboolab** [comment]
@rmoreira0
Great that it is working. Yeah~ Since Alert is happening in UI thread, your code will be interrupted with UI thread being used by Android after purchase. Therefore to avoid it you should give some delay with timeout or use InteractionManager to make your Alert being called. I knew it but I’ve missed that from your question tough.

Thank you.
