### ISSUE TITLE
withIAPContext freeze my custom context

### ISSUE THREAD

**Issue by ithustle** [dooboolab/react-native-iap#1502]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
7.4.1

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
Update state of my Providers.
I read data from local database and save on my context and the data does not update.

### Actual behavior
Using `withIAPContext` State data does not update

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
````
import React from "react";
import { Provider } from "react-redux";
import { MenuProvider } from 'react-native-popup-menu';
import { NativeBaseProvider } from 'native-base';
import { withIAPContext } from 'react-native-iap';

import AppNavigation from "./src/routes";
import store from "./src/utils/store";
import { TabProvider } from "./src/utils/TabProvider";

const Root = () => (
    <Provider store={store}>
        <NativeBaseProvider>
            <TabProvider>
                <MenuProvider>
                    <AppNavigation />
                </MenuProvider>
            </TabProvider>
        </NativeBaseProvider>
    </Provider>
)

export default withIAPContext(Root);
````

My app stuck on loading because the value on my custom context doesn't update.

**Comment by hyochan** [comment]
@r0b0t3d  May you kindly check this issue as a contributor of #1482? :pray:

**Comment by r0b0t3d** [comment]
Hi @ithustle , Let me try to reproduce this case. But could you please clarify
1. Where is the data that didn't update? In redux's state or your custom context?
2. Your app works well without `useIAPContext`?

**Comment by ithustle** [comment]
Hi @r0b0t3d. Sorry for delay.

1. My custom context. Redux state works fine.
2. Yep. For now, I had to downgrade to v6.

**Comment by r0b0t3d** [comment]
Hi @ithustle , I created a sample repo here https://github.com/r0b0t3d/IapExample.
In this example, I have a custom context that load data from async storage. But I could not reproduce the issue, the value is loaded successfully after refreshing.

![simulator_screenshot_02B68B92-E390-48A3-8BBD-4C696560F155](https://user-images.githubusercontent.com/8109285/134108059-09359edb-1ce0-4716-aaf1-0ecd957826dc.png)
