### ISSUE TITLE
Fatal exception in production build

### ISSUE THREAD

**Issue by axelkennedal** [dooboolab/react-native-iap#151]
### Version of react-native-iap
0.3.23

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
No crashing

### Actual behavior
Application crash

### Tested environment (Emulator? Real Device?)
Android 7.0 running on an LG G6

### Steps to reproduce the behavior

1. Set up an IAP product as described in the Medium article
2. Call `getProducts(itemSKUs)` and `getPurchaseHistory()` in `componentDidMount()` of a component visible when the app starts
3. Follow [this guide](https://stackoverflow.com/questions/36113347/is-it-possible-to-debug-locally-google-plays-in-app-billing-in-android-studio/36126865) on how to get debug output when testing IAP
4. Run the app with `react-native run-android --variant=release`

Note: The application sucessfully fetches the product and the (empty) purchase history when I'm running the app with just `react-native run-android`, but I need to run the release version to test the full purchase flow.

## Update
This crash also happens when running the production version installed through Google Play (via an Alpha test)

**Comment by axelkennedal** [comment]
Here is the stacktrace from `adb logcat`:

```
05-04 17:37:02.783 14663 14771 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-04 17:37:02.783 14663 14771 E AndroidRuntime: Process: com.kimer, PID: 14663
05-04 17:37:02.783 14663 14771 E AndroidRuntime: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:28)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at com.facebook.react.bridge.PromiseImpl.reject(PromiseImpl.java:68)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at com.facebook.react.bridge.PromiseImpl.reject(PromiseImpl.java:36)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule.rejectPromiseWithBillingError(RNIapModule.java:386)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule.access$200(RNIapModule.java:44)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule$4.onPurchaseHistoryResponse(RNIapModule.java:289)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at com.android.billingclient.api.BillingClientImpl$4$1.run(BillingClientImpl.java:484)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
05-04 17:37:02.783 14663 14771 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
05-04 17:37:02.792  1667 14367 W ActivityManager:   Force finishing activity com.kimer/.MainActivity
```

**Comment by axelkennedal** [comment]
After thinking a little bit about it I realized it seemed like the issue was that the functions of module were somehow not called in the intended order and that it had to do with timing, so I figured out the source of the problem. I changed the componentDidMount from this:

```js
 componentDidMount() {
        this.getProductInfo();
        this.getPreviousPurchases();
    }

    getProductInfo = async() => {
        try {
            await InAppPurchase.prepare();
            const products = await InAppPurchase.getProducts(itemSKUs);
            console.log("finished call to get products", products);
            this.setState({premiumProduct: products[0]});
        } catch (err) {
            console.warn(err);
        }
    }

    getPreviousPurchases = async() => {
        try {
            const purchases = await InAppPurchase.getPurchaseHistory();
            console.log("previous purchases: ", purchases);
        } catch (e) {
            console.warn(err);
        }
    }
```

to this:

```js
    async componentDidMount() {
        await this.getProductInfo();
        await this.getPreviousPurchases();
    }

```

My confusion came from the fact that I thought the `await`s in `getProductInfo()` and `getPreviousPurchases()` would be enough.

**Comment by SlZeroth** [comment]
I have same error .. did you found solution

**Comment by vsingh-techracers** [comment]
@SlZeroth 
prepare() method is used for android according to docs on this module so need to end the connection for android. If we do not end the connection get the error "java.lang.RuntimeException: Illegal callback invocation from native module"

**add this in your code file**
  async componentWillUnmount() {
    await RNIap.endConnection();
  }
