### ISSUE TITLE
[iOS] calling clearTransaction with none pending transactions breaks StoreKit systemwide

### ISSUE THREAD

**Issue by serjek** [dooboolab/react-native-iap#1514]
### Version of react-native-iap
7.4.1

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Calling `IAP.clearTransactionIOS()` at any time is safe and either rejects or resolves with `void/[]`

### Actual behavior
Calling `IAP.clearTransactionIOS()` when there are lots of transactions for renewable subscriptions and none for consumable items causes storekit to die silently. **Even downloading/updating from appstore or testflight and inapp purchases in other apps stop working until device is rebooted.**

### Tested environment (Emulator? Real Device?)
Real device, iPhone 12, iOS 15.0

### Steps to reproduce the behavior
- Have renewable subscription as inapp purchase
- Buy and cancel several dozens times (this is particular use case for developers when testing purchases before submit). Properly process and finish each purchase.
- At some point call `IAP.clearTransactionIOS()`. There will be log entry `***  clear remaining XX Transactions. Call this before make a new transaction` and then storekit will not respond anymore.

**Comment by serjek** [comment]
Worth mention that storekit crash happens at `[[SKPaymentQueue defaultQueue] finishTransaction:transaction];` if transaction is a renewable subscription, so calling default `getAvailablePurchases()` with similar conditions results in same behaviour.

**Comment by andresesfm** [comment]
@serjek looks like it was fixed as per the last comment on the other ticket. Please reopen if needed
