### ISSUE TITLE
[IOS 15] - Library not working in sandbox environment and breaking access to App Store after using

### ISSUE THREAD

**Issue by semenetsvladislav** [dooboolab/react-native-iap#1515]
Subscriptions not working in apple sandbox (prod app is working). After first app launch it's getting subscriptions list and some purchases history and then something breaks and I'm not able to request subscription... Apple payment modal never appears. On next launch subscription items not loading at all and seems library stops working.
After that I've not able even get access to AppStore -> Profile ... getting infinite loading there. Only device reboot helps.
It seems like problem with StoreKit.

### Platforms you faced the error (IOS or Android or both?)
IOS 15

### Expected behavior
Be able to make inapp purchases 
### Actual behavior
In sandbox environment it breaks StoreKit
### Tested environment (Emulator? Real Device?)
Real Device (iPhone XR, 12)

**Comment by serjek** [comment]
I think it's the same as #1514

**Comment by semenetsvladislav** [comment]
Yes, it's similar...

**Comment by MadsonDouglas** [comment]
I am in a similar situation.
The first call to getSubscriptions() works, but from the second it fails without throwing an error.
I need to reboot the device, but it only works once again.

iOS15.0 Real Device ,SandBox
react-native-iap@5.2.3
react-native@0.62.2

**Comment by semenetsvladislav** [comment]
Any progress here?

**Comment by RFG-G** [comment]
@MadsonDouglas, do you have any problems with the getProducts()?

**Comment by nishik-t** [comment]
Try the following steps.

1.Setting-> AppStore-> SANDBOX-> Sign-out
2.Reboot your device.
3.Create a new SANDBOX account.
4.Setting-> AppStore-> SANDBOX-> Sign-in

In my case, this issue has been fixed.

> I am in a similar situation. The first call to **getAvailablePurchases()** works, but from the second it fails without throwing an error. I need to reboot the device, but it only works once again.
> 
> iOS15.0 Real Device ,SandBox react-native-iap@7.5.0 react-native@0.63.3

**Comment by nishik-t** [comment]
sorry.
After a few purchase tests, the situation was the same as before.
I wonder if it will fail when the purchase history is accumulated there.
It includes auto-renewal subscriptions.

> Try the following steps.
> 
> 1.Setting-> AppStore-> SANDBOX-> Sign-out 2.Reboot your device. 3.Create a new SANDBOX account. 4.Setting-> AppStore-> SANDBOX-> Sign-in
> 
> In my case, this issue has been fixed.
> 
> > I am in a similar situation. The first call to **getAvailablePurchases()** works, but from the second it fails without throwing an error. I need to reboot the device, but it only works once again.
> > iOS15.0 Real Device ,SandBox react-native-iap@7.5.0 react-native@0.63.3

**Comment by andresesfm** [comment]
has anyone tried version `8.0.0-rc2`?

**Comment by serjek** [comment]
> has anyone tried version `8.0.0-rc2`?

I did but it has same issue. Apparently problem is in storekit sandbox and apple doesn't care much.

**Comment by serjek** [comment]
My solution is to comment out `[[SKPaymentQueue defaultQueue] finishTransaction:transaction];` at `paymentQueueRestoreCompletedTransactionsFinished` but my case is specifically auto-renewable subscriptions. I believe this will not work for other cases.

**Comment by semenetsvladislav** [comment]
> has anyone tried version `8.0.0-rc2`?

Yes, I also tried this version, but have the same result unfortunately 🥲

**Comment by andresesfm** [comment]
Marking as resolved. As per the last comment. Please feel free to reopen if any more details
