### ISSUE TITLE
getPurchaseHistory does nothing

### ISSUE THREAD

**Issue by SethThoburn** [dooboolab/react-native-iap#1516]
### Version of react-native-iap
7.4.0

### Version of react-native
0.64.1

### Platforms you faced the error (IOS or Android or both?)
iOS, only iOS 15, dev environment

### Expected behavior
getPurchaseHistory returns the purchase history or at least throws an error

### Actual behavior
getPurchaseHistory fails silently

### Tested environment (Emulator? Real Device?)
Real device, iPhone 11

### Steps to reproduce the behavior
Run getPurchaseHistory on iOS 15 in a dev environment

**Comment by valentinsld** [comment]
You do use a ShareSecretKey, you have a tuto here : https://www.appypie.com/faqs/how-can-i-get-shared-secret-key-for-in-app-purchase 

You replace the password in this :
`  const receiptBody = {
    'receipt-data': purchase.transactionReceipt,
    'password': '******'
  };
  const result = await RNIap.validateReceiptIos(receiptBody, false);
  console.log(result);`

**Comment by gkeenleyTest** [comment]
@SethThoburn Were you able to resolve this?

**Comment by SethThoburn** [comment]
I don't remember now the details, but it is working. Thanks for following up!
