### ISSUE TITLE
[iOS] 8.0.0 does not compile in iOS

### ISSUE THREAD

**Issue by serjek** [dooboolab/react-native-iap#1518]
### Version of react-native-iap
8.0.0 installed both from `@next` and from branch `release/8.0.0`

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Project compiles

### Actual behavior
Compilation errors in `RNIapIos.m`

### Tested environment (Emulator? Real Device?)
Device

### Steps to reproduce the behavior
`yarn add react-native-iap@next` or `yarn add https://github.com/dooboolab/react-native-iap#release/8.0.0`
`pod install`
Compile project in xcode

**Comment by andresesfm** [comment]
@serjek thank you for the report. Could you please share the compilation errors you see? Thank you

**Comment by serjek** [comment]
with rc.2 it compiles just fine, thanks!
