### ISSUE TITLE
Proper way to wait until prepare is done

### ISSUE THREAD

**Issue by axelkennedal** [dooboolab/react-native-iap#152]
### Version of react-native-iap
0.3.23

### Platforms you faced the problem (IOS or Android or both?)
Android

### Problem
Some methods of this library are getting called before `prepare()` is done.

### Description
I'm wondering what the recommended way is for waiting until the library is ready to process requests on Android.  The example provided in the README cannot really be applied directly to my application, since what I'm doing is I've created a class with `static` functions for handling In App Purchases (kind of an abstraction on top of this library).  In my `App.js` I call  `prepare()` in `componentDidMount()`, and so the issue is that the other component of my app will load and call `getProducts(itemSKUs)` before `componentDidMount()` (and therewith `prepare()`) is done executing.

My current (not very pleasing) solution is to just set a timeout of 1 second in the other component before calling `getProducts(itemSKUs)`  from it.

I had an idea about setting a boolean like this and then making it so that the other functions have to wait for it to be true before they can execute, but I'm not sure how to accomplish that.

```js
export default class IAPManager {
    static hasUnlockedPremium = undefined;
    static productInfo = undefined;
    static isReady = undefined;

    static async prepare() {
        const isConnected = await NetInfo.isConnected.fetch();
        if (isConnected) {
            try {
                await InAppPurchase.prepare();
                IAPManager.isReady = true;
            } catch (e) {
                console.log("Could not prepare IAP", e);
                IAPManager.isReady = false;
            }
        } else {
            IAPManager.isReady = false;
        }
    }
...
}
```

**Comment by dooboolab** [comment]
What happens if you try to prepare with `await` before calling `getProducts` in `componentDidMount`?

**Comment by axelkennedal** [comment]
The point is that I want my class to be a manager of all things related to IAP in my app. and it should be initialized when the app launches. I want to use it in another component aswell, so I don't think putting the `prepare()` in the `componentDidMount()` in my other component (not `App.js`) would be the best idea.

Can I call `prepare` multiple times without any issues? If I use functions from this library in multiple places, should I just `prepare()` everywhere in my code before I use the library functions? Seems like bad design, I'd like to just prepare once and then be able to use it once it's ready.

**Comment by axelkennedal** [comment]
Perhaps a mutex could be used to solve this issue? I'm thinking that the mutex would be locked in the beginning of the `prepare()` of my class, and that the other functions of my class would wait until that mutex is unlocked. I found [this](https://www.npmjs.com/package/async-mutex) library for JS mutexes.

**Comment by dooboolab** [comment]
@axelkennedal You can use `prepare` method anywhere, but be sure that you call `endConnection` when you are not needing it. Therefore, call `prepare` in `componentDidMount` and call `endConnection` in `componentWillUnmount` will be fine.

**Comment by axelkennedal** [comment]
But what if I use the library in two components that load at the same time? Isn't it highly likely then that `prepare()` will be called simultaneously in both components and this creating a race condition?

**Comment by dooboolab** [comment]
@axelkennedal You need your programming skill to solve this kind of problem currently. If I were you, I would set one global variable that manages if you've called `prepare` method or not. I'll write some code that might help you to solve this kind of problem. You may find better solution tough.
```
let openedBilling = false;  // this variable will stay globally somewhere like `global.js`

// component 1
componentDidMount() {
  if (!openBilling) {
    RNIap.prepare();
  }
  RNIap.getProducts(skus);
}

componentWillUnmount() {
  if (openBilling) {
    RNIap.endConnection();
  }
}

// component 2
componentDidMount() {
  if (!openBilling) {
    RNIap.prepare();
  }
  RNIap.getProducts(skus);
}

componentWillUnmount() {
  if (openBilling) {
    RNIap.endConnection();
  }
}
```

**Comment by axelkennedal** [comment]
Yeah, that might be the beginning of a solution, but I think it needs to be paired with a mutex, otherwise there is still the chance that both components call `prepare()` at the same time (the second one manages to call it before the first one has finished and set the global variable). I'll see what I can do, though I think this library should handle this sort of thing built-in.

**Comment by dooboolab** [comment]
@axelkennedal 
Alright, I will consider your opinion. However, there is very very low chances(close to 0) to assign variable at the same time because once it is being assigned, it will be blocked from the memory based on computer science theory. Therefore, I guess above code will be working fine beyond your concern.

**Comment by axelkennedal** [comment]
The way that you describe it there are two possible ways of interpreting it.

1. Use a global variable `ready` which is `false` before any call to the library, and `true` once `prepare()` has finished running

OR

2. Use a global variable `openBilling` which is `false` before any call to the library and set to `true` in the very beginning of the implementation of `prepare()`

For interpretation 1 this is possible to happen (c1 is a component and c2 is another component):

![20180509_200218](https://user-images.githubusercontent.com/8863787/39831763-b8b361ca-53c5-11e8-86a0-519b88ad886f.jpg)

And for interpretation 2 this can happen:

![20180509_200816](https://user-images.githubusercontent.com/8863787/39831780-c4be4732-53c5-11e8-80cd-e9f019d64945.jpg)

And I'm sure there are more ways it can fail. It seems to me that your approach is too naive and doesn't work in all cases. When you have two components that load at the same time and try to interact with the library at the same time these things do happen (as I've seen when experimenting with it).

**Comment by dooboolab** [comment]
@axelkennedal I exactly agree with what you've described above. I just posted the starter solution for your problem. It could be improved, like when you call `getProducts` and get failure message you can call it again after few seconds setting `timeout` method. Also, using `mutex` must be a better solution and for sure I should manage this in the native side. Will come back to you if I've done it.

**Comment by axelkennedal** [comment]
I'm happy to hear you agree 😄 Yes, this should for sure be handled on the native side 👍

**Comment by dooboolab** [comment]
@axelkennedal I've released `1.0.5` fixing this. When you called `prepare` method, then before you call `endConnection` it won't start billing client again. I'll close the issue. Please reopen it when you still have problem in `1.0.5`.

**Comment by axelkennedal** [comment]
I'm not sure I understand what you mean. Are you telling me that the other functions of the library will now wait until `prepare` has finished?

**Comment by nico1510** [comment]
@dooboolab do you know of any disadvantages of calling `prepare` just once for the whole application lifetime instead of before every API call ? I don't plan to use this library in components but in a redux saga which is running the whole time.

**Comment by nico1510** [comment]
@dooboolab thanks I'll follow your advice :)
