### ISSUE TITLE
Using hooks, getting Not initialized, Please call initConnection()

### ISSUE THREAD

**Issue by roblingle** [dooboolab/react-native-iap#1526]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
7.5.0

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
Android only

### Expected behavior
I should not have to call initConnection using hooks

### Actual behavior
After `connected` is true we `getSubscriptions(ids)` but it throws an error `Not initialized, Please call initConnection()`

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior

App.js is wrapped and exported as `withIAPContext(App)`

The code:

```
export const useSubscription = () => {
  // initConnection();  // <-- In dev, this will avoid the error. Not in production.
  const {
    connected,
    subscriptions,
    finishTransaction,
    getSubscriptions,
    currentPurchase,
    currentPurchaseError,
  } = useIAP();
  
  ...
  
  useEffect(() => {
    if (connected) {
      getSubscriptions(subscriptionIds).catch((err) => { // <-- Error here
        Sentry.Native.captureException(err)
      });
    }
  }, [connected]);

 ...
```

**Comment by jeremyhalin** [comment]
I thought with hooks it wasn't mandatory to initConnection and that hooks took care of this part. But I'm not sure.

Anyway, purchases seem to work on emulator and real devices, but I keep getting a lot of `Not initialized, Please call initConnection()` errors. I don't understand what should I do to fix this error. Documentation about using hooks is not very clear. I can't reproduce this error in emulator.

I'm using `react-native: 0.66.1` and `react-native-iap: 7.5.0`

**Comment by jeremyhalin** [comment]
I wonder if it's related to https://github.com/dooboolab/react-native-iap/issues/1562 

Any update on this? What should be done to fix error on `7.5.1`?

**Comment by okcompewter** [comment]
+1

**Comment by okcompewter** [comment]
Seems to happen on emulated devices that do not have the Play Store and when using hooks implementation.

I'm able to no longer get this LobBox warning by updating **\src\hooks\withIAPContext.js, line 102**, by catching the error, but is there a better way/place to implement this?
```
        useEffect(function () {
            initConnection().then(setConnected).catch(error => console.log(error));
        }, []);
```

**Comment by okcompewter** [comment]
Still an ongoing issue for me, any help?

**Comment by tpagram-pwc** [comment]
I am seeing these errors in production for a subset of users. Has anyone been able to reproduce this locally? I'm struggling to emulate this

**Comment by okcompewter** [comment]
I can reproduce it locally using an emulated device that does not have Google Play Store/services.

**Comment by andresesfm** [comment]
Billing Services are not available on Emulators

**Comment by rajeshrthl** [comment]
I keep getting a lot of "Not initialized, Please call initConnection() errors". Looks like still an ongoing issue.

**Comment by andresesfm** [comment]
Did you call `initConnection` ?

**Comment by rajeshrthl** [comment]
Yes I did. It is there since we started using this library.

**Comment by danicunhac** [comment]
Same, I'm using version 7.1.0 but it's not with hooks
```js
  async componentDidMount() {
    await RNIap.initConnection();

    try {
      await RNIap.flushFailedPurchasesCachedAsPendingAndroid();
      this.purchaseUpdateSubscription = this.connectUpdateSubscription();
      this.purchaseErrorSubscription = this.connectErrorSubscription();
    } catch (error) {
      console.error(error);
    }
  }
```

**Comment by andresesfm** [comment]
you have to check the result of `initConnection` and wrap it in a `try-catch` as it might not be available on a device or it may fail to initialize

**Comment by danicunhac** [comment]
> you have to check the result of `initConnection` and wrap it in a `try-catch` as it might not be available on a device or it may fail to initialize

That's what I did actually, I put it inside the try-catch below and it shows me the following
```bash
E_NOT_PREPARED Not initialized, Please call initConnection()
```
Should I be using a real device to test/develop using this library?

**Comment by danicunhac** [comment]
@andresesfm I found another issue and saw that I wasn't connected to the play store.

**Comment by andresesfm** [comment]
@GeorgeVidIq, it is closed because: 
* It was stale (see above), 
* There are possible causes such as @danicunhac 's comment or my comment about Play Services not available
* This was reported on an old version of the library.

If you have any more information to contribute such as the return code when you call `initConnection` and have updated to a recent version of the library, please create a new ticket with all the details. otherwise, it's very difficult to guess what your situation is.
