### ISSUE TITLE
iOS 15 fails to fetch products.

### ISSUE THREAD

**Issue by arshad-slate** [dooboolab/react-native-iap#1528]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap 

`react-native-iap 7.3.0` (tried in 7.5.0 also)
### Version of react-native
 
`react-native: 0.64.0`
### Platforms you faced the error (IOS or Android or both?)

iOS, version 15.0
### Expected behavior
`getSubscriptions` call should populate `subscriptions`  (`useIAP`)
### Actual behavior

* `getSubscriptions` will never trigger callback. 
* In the log I am getting -> ` Background Task 88 ("SKProductsRequest"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`

Looks like an iOS 15 related issue.

### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior

* Install app in the device which already has an expired device (Not sure about fresh install)
*  `currentPurchase` will get populated with older purchase details.
* Quit the app and try again. No product will be fetched, `getSubscriptions` will continue forever.
* At this time TestFlight app turns into `renew` status.

Refer threads

* https://developer.apple.com/forums/thread/691663?login=true
* https://developer.apple.com/forums/thread/688416?login=true

**Comment by rkoshti** [comment]
Any luck as i am facing the same issue in iOS 15 @andresordonezfm @arshad-slate  ?

**Comment by darkhorse-coder** [comment]
Definitely the same for me.
I can't get available purchases and subscriptions from `getSubscriptions` and `getAvailablePurchases`. 
What is the main reason? `react-native-iap` version problem or any other things?
Needed help!

**Comment by jblancoh** [comment]
@darkhorse-coder I was reading about the problem in the apple forums, apparently it is a problem with iOS 15.

Check this
[691663](https://developer.apple.com/forums/thread/691663
)
[688416](https://developer.apple.com/forums/thread/688416
)
[688416](https://developer.apple.com/forums/thread/688416)

**Comment by hyochan** [comment]
I doubt this is a test flight issue. Please share any news if anyone solve the problem.

**Comment by meowofficial** [comment]
Does it work on iOS 15.4 for you, guys?

**Comment by JorenVos** [comment]
The promise is not resolving at all. 

```
import { useIAP } from 'react-native-iap';

getSubscriptions(['MONTHLY']).then(() => {
   console.log('Done');
}).catch(() => {
   console.log('Error')
});
```
`Done` or `Error` is never logged.

**Comment by ImersivDev** [comment]
Does not work for me on TestFlight with iOS 15.4 and React Native 0.66.0

**Comment by andresesfm** [comment]
Please help us test the alpha version of 11.0.0 Migrates to storekit 2 that targets ios 15 and above
