### ISSUE TITLE
Crash when consuming product [ANDROID]

### ISSUE THREAD

**Issue by alanlanglois** [dooboolab/react-native-iap#153]
### Version of react-native-iap
0.3.23

### Platforms you faced the error (IOS or Android or both?)
Android (seems to work on iOS)

### Expected behavior
Consume product without crashing

### Actual behavior
It crashes the app

### Tested environment (Emulator? Real Device?)
Real Device (nexus 5X)

### Steps to reproduce the behavior

Prepare iap, buy inapp and consume it:

```
const receipt = await RNIap.buyProduct(productID)
const result = await RNIap.consumePurchase(receipt)
```

The app doesn't crash when doing it this way:
```
  var purchases = await RNIap.getAvailablePurchases();
  for (let purchase of purchases) {
    if (purchase.productId == productID) {
      var result = await RNIap.consumePurchase(purchase.transactionReceipt)
    }
  }
```

But it's a little overkill, why can't I do it using the receipt from buyProduct?
Also I think the doc is not up to date. You'll find consumeProduct in the method list while the new method is not consumeProduct anymore but consumePurchase.

**Comment by dooboolab** [comment]
@alanlanglois Thanks I will update the doc soon.

**Comment by umeshpatadiya** [comment]
How to consume product once it's purchased? I don't have the product details I bought.
