### ISSUE TITLE
React-native run-ios doesn't copy over the storekit setting and thus no in-app-purchases

### ISSUE THREAD

**Issue by ilyakar** [dooboolab/react-native-iap#1532]
So, to get in-app-purchases in the debug environment it seems we have to use Storekit. Did that. Works well when running 
the debug app from XCode.

![image](https://user-images.githubusercontent.com/1760709/136434046-30a47055-cd9d-4d5f-84fb-ce4b0b0e3097.png)
![IMG_3638](https://user-images.githubusercontent.com/1760709/136434136-2d8a1080-af89-405f-bf25-ab4435be3df0.PNG)

However, when trying to run from terminal, it seems the StorekitConfiguration file setting is not set.
`react-native run-ios --device "Ilya’s iPhone" --configuration Debug --scheme ChatDevelopment`:
![IMG_AD7E0D217DF6-1](https://user-images.githubusercontent.com/1760709/136434639-96cda593-5fb8-4997-b2d1-0518817291b5.jpeg)

```
"react-native": "0.65.1",
"react-native-iap": "^7.5.0",

iOS: 14.7.1
XCode: 13.0
```

Thoughts? :)

**Comment by VChertukhin** [comment]
Fallen into the same problem

**Comment by andresesfm** [comment]
Not sure if it's even possible. I googled around but was not able to find any info. If you find something, please let us know. I'd be happy to include it

**Comment by nthegedus** [comment]
Hi @ilyakar, do you have any updates about this issue?

I'm facing the same problem. Configuration.storekit only works in Xcode build.
Besides that, when I generate the builds using fastlane, the ad-hoc versions crash when open the app.

Env:
"react": "18.2.0",
"react-native": "0.71.3",
"react-native-iap": "^12.7.4",
Xcode 14.2.0

**Comment by ilyakar** [comment]
@nthegedus I've just been building with XCode for the past 2 years because of this issue :)

**Comment by nthegedus** [comment]
Hi @ilyakar, don't you have any problems in yours distributions? I'm using fastlane, and seems not working too
