### ISSUE TITLE
termSku value missing in response from AmazonIAP

### ISSUE THREAD

**Issue by Kabilan34** [dooboolab/react-native-iap#1536]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
7.5.0

### Version of react-native
react-native-tvos@0.63.4-0

### Platforms you faced the error (IOS or Android or both?)
Android - Amazon

### Expected behavior
purchaseSubscription in Amazon IAP module should return termSku or sku

### Actual behavior
purchaseSubscription in Amazon IAP module does not return termSku and sku returned is null

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Purchase Subscription with terms in Amazon IAP

**Comment by andresesfm** [comment]
Hello @Kabilan34,  This is a valid request. In the meantime, you can access it like so: `purchase.transactionReceipt?.termSku`

**Comment by andresesfm** [comment]
sku is returned as "productId"
