### ISSUE TITLE
Task :react-native-iap:verifyGoogleJavaFormat FAILED

### ISSUE THREAD

**Issue by mozadeh** [dooboolab/react-native-iap#1539]
### Version of react-native-iap  
7.5.0
### Version of react-native 
0.66.0
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Doesn't build
### Actual behavior
Won't build
I'm getting

> Task :react-native-iap:verifyGoogleJavaFormat FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-iap:verifyGoogleJavaFormat'.
> com/google/googlejavaformat/java/JavaFormatterOptions$Style has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by andresesfm** [comment]
The message is correct, we could have pinned the plugin version to the last one that uses java 1.8. We are in the process of moving to Kotlin. So this would not be needed after v8.0.0. If you need it sooner, just set the formatter as described

**Comment by neiracausevic1** [comment]
I had to update to Java 11 to get it to work.

in the terminal (Mac):
`brew tap AdoptOpenJDK/openjdk`
`brew install --cask adoptopenjdk11`

add the following in the file ~/.zshrc:
`export JAVA_HOME=$(/usr/libexec/java_home -v 11)`

apply the changes by running in the terminal:
`source ~/.zshrc`

confirm by running in the terminal:
`java -version`

expected outcome:
```openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by andresesfm** [comment]
We've removed this check on release/8.0.0
