### ISSUE TITLE
Multiple calls purchase update listener when request exist subscription (IOS)

### ISSUE THREAD

**Issue by ProkhoDim** [dooboolab/react-native-iap#1543]
### Version of react-native-iap
7.5.0
### Version of react-native
0.64.1
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior

When you click on the "buy" button, the system window "this subscription has already been purchased" pops up. This window offers two actions: "Manage" and "OK". Clicking on "OK" closes the window and nothing happens (or catch an error). If you minimize the application and reopen it, nothing happens.

### Actual behavior

When you click on the "buy" button, the system window "this subscription has already been purchased" pops up. This window offers two actions: "Manage" and "OK". When you click on "OK", the window closes and the listener catches the paid payment and sends it to the server. If you minimize the application and reopen it, the listener catches all the subscriptions that have ever been purchased and sends it to the server.
Also, on first launch, the listener catches all subscriptions ever purchased and sends them to the server.

### Tested environment (Emulator? Real Device?)
Debug mode with sandbox account on Real Device
### Steps to reproduce the behavior
Look at expected/actual behavior

 ### Comment
 
As far as I know, Apple Sandbox has a shortened subscription duration for renewal testing. Is it okay that:
1. The license renewal is activated by pressing the "OK" button (the Android application does not have this);
2. When you open the application, all previously purchased subscriptions are activated

**Comment by iSued** [comment]
I have the same issue using useIap() hook.

`const {
    connected,
    products,
    requestSubscription,
    subscriptions,
    getProducts,
    getSubscriptions,
    currentPurchase,
    currentPurchaseError,
  } = useIAP();`

as you can see i imported the previous methods and bindings from useIap()

then:
`useEffect(() => {
    if (connected) {
      getSubscriptions(props.products).then(() => console.log(subscriptions));
    }
  }, [connected, getProducts, getSubscriptions]);`
i'm fetching products using this useEffect.
and then i am waiting for the Purchase with this useEffect.
` useEffect(() => {
    const checkCurrentPurchase = async (purchase?: Purchase): Promise<void> => {
      if (purchase) {
        console.log(purchase.transactionId, "this is the purchase");
        const receipt = purchase.transactionReceipt;
        if (receipt) {
          try {
            await finishTransaction(purchase).then((response) => {
              console.log(response);
            });
          } catch (ackErr) {
            Alert.alert("ackErr", JSON.stringify(ackErr));
          }
        }
      }
    };
    checkCurrentPurchase(currentPurchase);
    return () => {};
  }, [currentPurchase, finishTransaction]);`

The same behavior described above by @ProkhoDim is happening to me.
I know that once the user pays the button shouldn't be rendered but also if this button continue stay there this should not happen.

**Comment by iSued** [comment]
@hyochan I've read your article about hooks on medium. 
Can you give any help on this issue?

**Comment by iSued** [comment]
I tried converting the code in a class Based one and this happens also in the class based component following documentation you can find on Website.

**Comment by andresesfm** [comment]
This issue has been reported in multiple tickets. Could this be the issue: https://developer.apple.com/forums/thread/74556 ? Please reopen if that's not the case and it still happens on 8.x.x
