### ISSUE TITLE
How to send external user data with requestSubscription

### ISSUE THREAD

**Issue by elinahovakimyan** [dooboolab/react-native-iap#1545]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
7.5.0

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
To be able to send user ID or email with subscription data, so that server will get it by Google API and identify the subscription. What options are there to do this? Trying to get subscription details from Google API is just returning null for emailAddress and the other user related fields.

### Actual behavior
When trying to send as `obfuscatedAccountIdAndroid` or `obfuscatedProfileIdAndroid` the user email or ID in our DB, the app is just crashing. 

### Tested environment (Emulator? Real Device?)
Real device

**Comment by rb162215** [comment]
Facing same problem, there is no way we can identify for which user transaction receipt is received. 
That will we good if we can add user spacefic data while start purchase and same information can be received with receipt.

**Comment by andresesfm** [comment]
`requestPurchase` now accepts a parameter `applicationUsername`

**Comment by hubciorz** [comment]
@andresesfm This is only true for `requestPurchase`, not `requestSubscription`.

**Comment by andresesfm** [comment]
For iOS the parameter name has changed to `appAccountToken` And for Android, you could use `obfuscatedAccountIdAndroid,
  obfuscatedProfileIdAndroid`

**Comment by dineshmahajan** [comment]
@andresesfm  How i can use obfuscatedAccountIdAndroid, obfuscatedProfileIdAndroid. in requestSubscription() method android reactnative

**Comment by andresesfm** [comment]
You pass them when making a purchase and you'll get them when querying for that purchase

**Comment by dineshmahajan** [comment]
@andresesfm  Can you please send me a sample code?

**Comment by TahseenSust** [comment]
@dineshmahajan you can use like this
`if (Platform.OS === "android") {
        const sku = subscription as SubscriptionAndroid;

        const offerToken = isAndroid
          ? sku?.subscriptionOfferDetails[0]?.offerToken
          : null;

        const purchaseData = await requestSubscription({
          sku: sku?.productId,
          ...(offerToken && {
            subscriptionOffers: [{ sku: sku?.productId, offerToken }],
          }),
          obfuscatedAccountIdAndroid: user?.id,
          obfuscatedProfileIdAndroid: user?.id,
        });

        console.log("purchase data", purchaseData); // after successfully purchase, we'll get purchase information
      } else if (Platform.OS === "ios") {
        const sku = subscription as SubscriptionIOS;

        const purchaseData = await requestSubscription({
          sku: sku.productId,
          andDangerouslyFinishTransactionAutomaticallyIOS: false,
          appAccountToken: user?.id,
        });

        console.log("purchase data", { purchaseData }); // after successfully purchase, we'll get purchase information
      }`
