### ISSUE TITLE
getProducts(), getAvailablePurchases() never resolves on devices without Google Play Services

### ISSUE THREAD

**Issue by andkom** [dooboolab/react-native-iap#1547]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap

7.5.0

### Version of react-native

0.66.1

### Platforms you faced the error (IOS or Android or both?)

Android 

### Expected behavior

getProducts(), getAvailablePurchases() resolves a promise with error on devices without Google Play Services

### Actual behavior

getProducts(), getAvailablePurchases() never resolves a promise

### Tested environment (Emulator? Real Device?)

Emulator
Android 11, Pixel 2 API 30, initConnection() returns false
Android 8.1, Pixel 2 API 27, initConnection() returns false
Android 5.1, Pixel 3 API 22, initConnection() returns false
Android 5.0, Pixel 2 API 21, initConnection() returns true

### Steps to reproduce the behavior

```
await RNIap.initConnection();
await RNIap.getProducts([...]); // never resolves
// or
await RNIap.getAvailablePurchases(); // never resolves
```

**Comment by andresesfm** [comment]
If Google Play Services is not available, `initConnection()` will resolve to `false` I will also log:
```
Google Play Services are not available on this device
```
To adb

**Comment by andkom** [comment]
@andresesfm on Android 5.0 ` initConnection()` resolves to `true` even if Google Play Services are not available.

**Comment by andresesfm** [comment]
@andkom We are using the recommended API: https://github.com/dooboolab/react-native-iap/blob/master/android/src/play/java/com/dooboolab/RNIap/RNIapModule.java#L104 how are you fixining in your app?

**Comment by andkom** [comment]
@andresesfm I don't wait until `getProducts` or `getAvailablePurchases` promise resolves. It seems I should check if connection was initialized.
