### ISSUE TITLE
Empty Array after using getSubscriptions or getProducts (IOS)

### ISSUE THREAD

**Issue by Desintegrator** [dooboolab/react-native-iap#1551]
I'm currently having a problem when using this library related to the `getProducts()` and `getSubscriptions()` functions.
They are not loading not products nor subscriptions. All in-apps has `ready to submit` status. It's more than 24h since in-apps configured and got `ready to submit` status.
`In-App purchases capability` enabled

### Version of react-native-iap

I'm using version `6.0.6`

upd. latest version (`7.5.0`) showing same behaviour

### Version of react-native

I'm using version `0.66.1`

### Platforms you faced the error (IOS or Android or both?)

Faced this problem on `IOS`. Android works well.

### Expected behavior

`initConnection()`: Showing true as a result.

`getProducts()`: Getting the list of all active products registered on App Store Connect
`getSubscriptions()`: Getting the list of all active subscriptions registered on App Store Connect

`getProducts([id])` : Getting the requested product
`getSubscriptions([id])`: Getting the requested subscription

### Actual behavior

`initConnection()`: Showing true as a result.

`getProducts()`: Getting an _empty_ array
`getSubscriptions()`: Getting an _empty_ array

`getProducts([id])`: Getting an _empty_ array
`getSubscriptions([id])`: Getting an _empty_ array

### Tested environment (Emulator? Real Device?)

I've tested both: `Emulator` and `real device` (including TestFlight app version)

### Steps to reproduce the behavior

for `6.0.6`:
1. `clearTransactionIOS()`
2. `initConnection()`
3. `flushFailedPurchasesCachedAsPendingAndroid()` // used for android
4. `getSubscriptions([id])` or `getProducts([id])` // with or without id array

for `7.5.0`:
1. `initConnection()`
2. `clearTransactionIOS()` // also tested withoud this call
3. `getSubscriptions([id])` or `getProducts([id])`

**Comment by stevenmusumeche** [comment]
I am having the same problem

**Comment by Desintegrator** [comment]
the problem was due to not submitted tax form

**Comment by venux92** [comment]
@jblancoh Worked for me. (15.1) I was on 15.0.2 previously

What will happened to my users using iOS 15? Would they be able to make a purchase?
My app was already live.

**Comment by pgqueme** [comment]
Same as @Desintegrator, it stopped working only on iOS without any code changes. That was the reason, after accepting the paid apps form it worked normally again.

**Comment by Rohit-vinfotech** [comment]
I am also not getting products , @Desintegrator where I can submit tax form can you please help me 

I am facing a issue of not getting products for IOS after Testflight upload , but working when I debug (run) locally on physical device. I want to validate receipt

I tried below methods
1.    const itemData= await getIosModule().getItems(constants.productSkus)
       alert("itemData ==>" + JSON.stringify(itemData))

2.    const product= await getProducts({ skus: constants.productSkus });   // by hook useIAP()
              alert("product=> "+JSON.stringify(product))

3.    const product= await IAP.getProducts({ skus: constants.productSkus });
              alert("product=> "+JSON.stringify(product))


Please help me to resolve this :)
I hope you will reply soon

**Comment by gevorg-movs** [comment]
> I am also not getting products , @Desintegrator where I can submit tax form can you please help me
> 
> I am facing a issue of not getting products for IOS after Testflight upload , but working when I debug (run) locally on physical device. I want to validate receipt
> 
> I tried below methods
> 
> 1. const itemData= await getIosModule().getItems(constants.productSkus)
>    alert("itemData ==>" + JSON.stringify(itemData))
> 2. const product= await getProducts({ skus: constants.productSkus });   // by hook useIAP()
>    alert("product=> "+JSON.stringify(product))
> 3. const product= await IAP.getProducts({ skus: constants.productSkus });
>    alert("product=> "+JSON.stringify(product))
> 
> Please help me to resolve this :) I hope you will reply soon

I have the same issue
