### ISSUE TITLE
Question/Suggestion: Check connection state

### ISSUE THREAD

**Issue by ospfranco** [dooboolab/react-native-iap#1559]
Hi, thanks a lot for the package!

We are facing some issues, we initialize the connection on app start because we have a lot of upsell dialogs and other user prompts to trigger payment/subscription. The problem is, however, that since we open the connection on app start and we need to keep it open if the app goes into the background, it appears that we lose the connection at different points and payments start behaving erratically.

Is there any way to query for the connection state and/or close it programmatically? is this a valid use case, of the connection should always remain open once the initConnection method has been called?

**Comment by mifi** [comment]
Maybe this can be closed because the functionality was added?
