### ISSUE TITLE
Init Connection not working

### ISSUE THREAD

**Issue by Robebou** [dooboolab/react-native-iap#1570]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
7.5.1
### Version of react-native
0.64.3
### Platforms you faced the error (IOS or Android or both?)
android / iOS when not build with Xcode
### Expected behavior
init connection 
### Actual behavior
init connection not working / TypeError: null is not an object (evaluating 'getNativeModule().initConnection')]
### Tested environment (Emulator? Real Device?)
Real device  -->  production application(android). It is working for real deal IOS when using Xcode.
### Steps to reproduce the behavior
Try to use init connection 
I tried to unlink / link
I also tried to Manuel check this installation

**Comment by BStenfors9119** [comment]
Seeing the same issue:

React-Native: 0.64.2

React-Native-IAP: 7.5.1

Below is a screen shot of the error I am getting from my try/catch wrapped around the initConnection():

![Screen Shot 2021-12-03 at 1 41 51 PM](https://user-images.githubusercontent.com/58486833/144676495-6eaa5189-8ccb-4ce9-abf7-d0aab5fd423f.png)

**Comment by andresesfm** [comment]
Please reopen if you see this issue again
