### ISSUE TITLE
Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported`

### ISSUE THREAD

**Issue by tonsnoei** [dooboolab/react-native-iap#1571]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
7.5.1

### Version of react-native
0.66.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
No error

### Actual behavior
Following error when running ./gradlew assembleRelease

```
> Task :react-native-iap:processAmazonReleaseManifest FAILED
/Users/ton.snoei/Documents/dev.nosync/trilab/IEXv7/src/reactnative/node_modules/react-native-iap/android/src/main/AndroidManifest.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```

### Tested environment (Emulator? Real Device?)
n/a

### Steps to reproduce the behavior
Use the following app/build.gradle settings
```
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
```

**Comment by gollobo** [comment]
I have the same problem, apparently the AndroidManifest.xml inside `/react-native-iap/android/src/amazon/` doesn’t have the `android:exported` value in the `<receiver/>` but I don’t know the correct value

**Comment by tonsnoei** [comment]
You can resolve it yourself by replace the contents of the file `/node_modules/react-native-iap/android/src/amazon/AndroidManifest.xml` with

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.dooboolab.RNIap">
<application android:exported="true">
    <receiver android:name = "com.amazon.device.iap.ResponseReceiver"
        android:permission = "com.amazon.inapp.purchasing.Permission.NOTIFY" 
        android:exported="true">
        <intent-filter>
            <action android:name = "com.amazon.inapp.purchasing.NOTIFY" />
        </intent-filter>
    </receiver>
</application>
</manifest>
```

And the file `/node_modules/react-native-iap/android/src/main/AndroidManifest.xml`
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          android:exported="true"
          package="com.dooboolab.RNIap">

</manifest>
```

**Comment by SergiOnGit** [comment]
Same error here.

**Comment by SergiOnGit** [comment]
@tonsnoei Your fix is working but must be fixed in package itself. We mustn't have to write a code in node_modules.

**Comment by hyochan** [comment]
Thanks for investigating this. Please give a `PR` if you think this should be updated.

**Comment by fkodaz** [comment]
> 

thank you its work

**Comment by fkodaz** [comment]
> You can resolve it yourself (for the time being) by replace the contents of the file `/node_modules/react-native-iap/android/src/amazon/AndroidManifest.xml` with
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>           package="com.dooboolab.RNIap">
> <application android:exported="true">
>     <receiver android:name = "com.amazon.device.iap.ResponseReceiver"
>         android:permission = "com.amazon.inapp.purchasing.Permission.NOTIFY" 
>         android:exported="true">
>         <intent-filter>
>             <action android:name = "com.amazon.inapp.purchasing.NOTIFY" />
>         </intent-filter>
>     </receiver>
> </application>
> </manifest>
> ```
> 
> And the file `/node_modules/react-native-iap/android/src/main/AndroidManifest.xml`
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>           android:exported="true"
>           package="com.dooboolab.RNIap">
> 
> </manifest>
> ```

thank you its work!!!

**Comment by SergiOnGit** [comment]
@hyochan I have created a pull request.

**Comment by SergiOnGit** [comment]
Would be great if you release it soon.
