### ISSUE TITLE
[DOUBT] getPurchaseHistory gets only the current app purchases?

### ISSUE THREAD

**Issue by Girum** [dooboolab/react-native-iap#1575]
Hi! Following several tutorials, and having not able to use the sandbox account in de appStore, when I use getPurchaseHistory, in the sandbox account, thats ok it returns all the purchases for my app. But, when I will use in production, how it procced? It will return all the purchases for my app, or ALL the purchases I have in appStore? Because it was too dificult to filter.

**Comment by andresesfm** [comment]
This is better suited for stackoverflow
