### ISSUE TITLE
[iOS] AppAccountToken for App Store Server Notifications

### ISSUE THREAD

**Issue by AnthonyHaykal** [dooboolab/react-native-iap#1576]
Hello,

iOS has a new JWSTransactionDecodedPayload which contains the following property:

appAccountToken: A UUID that associates the transaction with a user on your own service. If your app doesn’t provide an appAccountToken, this string is empty. For more information, see appAccountToken(_:).

Linked [here](https://developer.apple.com/documentation/appstoreservernotifications/jwstransactiondecodedpayload?changes=latest_major)

I would like to ask you if we can add the appAcountToken property when we purchase and get it from "App Store Server Notifications"

Thank you for all the hard work :).

**Comment by ManetJun** [comment]
We have the similar requirement as this.
We also need to send the UUID as part of the product purchase option.
`Product.PurchaseOption.appAccountToken(UUID)`

Not sure if this is already in the roadmap and when could it probably be available?

Thanks.

**Comment by Wanes-Tutunjian** [comment]
Hello

We are also facing this issue in our products, it would be a a lot easier if we can set a user identifier token for IOS purchases the way it is feasible for Android 

We were wondering if there is any update regarding this feature, and if it will be added anytime soon @hyochan 

Thanks for all your efforts :)

**Comment by mklsk** [comment]
Likewise - would be awesome to have this capability added!

CC: @hyochan

**Comment by sampsonjoliver** [comment]
Also +1'ing this.

As I understand this would be blocked by https://github.com/dooboolab/react-native-iap/issues/1403 ?

**Comment by Wanes-Tutunjian** [comment]
> As I understand it, this would not be blocked by migrating to StoreKit v2.
> 
> In the original implementation of StoreKit there is a field in the `SKMutablePayment` object that allows you to tag a payment to a specific user with an arbitrary string.
> 
> If that string happens to be a `UUID`, then the receipt will include the `appAccountToken` field with that `UUID` value.
> 
> https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername
> 
> This would make `applicationUserName` field analogous to `appAccountToken`.

thanks for pointing this out... we added the applicationUsername parameter to the request subscription function and patched the package... works like a charm 👍🏿

**Comment by He1nr1chK** [comment]
Hi @Wanes-Tutunjian, would you mind posting what you changed and how etc? Would love to do this myself. Thanks

**Comment by jeffy2007** [comment]
A little more info here, when the subscription is renew from a expired subscription via App Store Manage Subscription page, the uuid you provided previously would not be included.

**Comment by He1nr1chK** [comment]
Hi @jeffy2007 thanks a lot. Really appreciate that you took the time to help out.

**Comment by CawanTavares** [comment]
> 

from which version of RNIap is the applicationUsername included in the subscription function?

**Comment by MadsonDouglas** [comment]
> > As I understand it, this would not be blocked by migrating to StoreKit v2.
> > In the original implementation of StoreKit there is a field in the `SKMutablePayment` object that allows you to tag a payment to a specific user with an arbitrary string.
> > If that string happens to be a `UUID`, then the receipt will include the `appAccountToken` field with that `UUID` value.
> > https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername
> > This would make `applicationUserName` field analogous to `appAccountToken`.
> 
> thanks for pointing this out... we added the applicationUsername parameter to the request subscription function and patched the package... works like a charm 👍🏿

from which version of RNIap is the applicationUsername included in the subscription function?

**Comment by sampsonjoliver** [comment]
https://github.com/dooboolab/react-native-iap/tree/8.4.0

**Comment by andresesfm** [comment]
Please help us test 11.0.0-alpha1 (Migration to Storekit 2) Otherwise this has been merged on main. Can be found on the latest 10.x.x
