### ISSUE TITLE
Iap not working on production

### ISSUE THREAD

**Issue by Girum** [dooboolab/react-native-iap#1581]
Hi!

I submitted the app yesterday to apple, and the comment is that the app dont load the informations. When I tested in debug and release mode, the app brings the products very well. BUt, when I test in the Beta Testing, for example, the app dont bring any information.

Anyone with this?

**Comment by Girum** [comment]
I solved partially the problem. the IAP.getPurchaseHistory() brings back other purchases made by user, not only the purchases of the app... theres a way to purchase only the receipts from the current app?

**Comment by andresesfm** [comment]
https://developer.apple.com/documentation/storekit/skpaymentqueue/1506123-restorecompletedtransactions

**Comment by gkeenleyTest** [comment]
@Girum What did you do in order to resolve this? For me getPurchaseHistory() throws an error on TestFlight only, even though it works fine when run in Debug and Release mode locally.
