### ISSUE TITLE
iOS Receipt Validation

### ISSUE THREAD

**Issue by RocKhalil** [dooboolab/react-native-iap#1582]
### Version of react-native
7.5.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Received receipt should be valid

### Actual behavior
Received receipt is not valid

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Purchase any product, take the receipt and call Apple's verifyReceipt API.

If I'm not mistaken, old Apple receipt used to be `ewo` and now they are `MII`.
The receipt I'm getting from react-native-iap is `MIAG` which is an invalid receipt ( error 21002 ).
Any suggestion on how to fix this ?

 ( tried to validate via `validateReceiptIos` and via Postman )

**Comment by pvroosendaal** [comment]
Similar issue here, but I thought this was causing it for me: https://github.com/dooboolab/react-native-iap/issues/1164. Going to try your setup and see if that fails too.

**Comment by RocKhalil** [comment]
@pvroosendaal I found out what the issue was and forgot to comment here.
You'll get a valid receipt ONLY thought testflight. You have to build the app and push it to TF in order to get it.
Even running the app on a real device as release won't work.

Hope this helps,

**Comment by pvroosendaal** [comment]
Ok thanks. So you were not calling the sandbox verifyReceipt API but the production version? I'm running into this issue on the sandbox endpoint.

**Comment by RocKhalil** [comment]
It's not about which endpoint you're calling, it's more about the receipt you're getting.

The valid Apple receipt starts with `MIAG` instead of `MII`; once you get the `MIAG` receipt, you can call production endpoint then the sandbox endpoint if you get the status `20007`

**Comment by pvroosendaal** [comment]
Oh right, of course. Thanks again.

**Comment by roots-ai** [comment]
> It's not about which endpoint you're calling, it's more about the receipt you're getting.
> 
> The valid Apple receipt starts with `MIAG` instead of `MII`; once you get the `MIAG` receipt, you can call production endpoint then the sandbox endpoint if you get the status `20007`

Can you please share the code? (unsure how to get this done)

**Comment by darde** [comment]
I'm facing the same issue. For me, it's working on the sandbox, but it's now working on production. I've got a valid receipt on the sandbox starting with `MII` and received the correct response.

**Comment by Rohit-vinfotech** [comment]
> @pvroosendaal I found out what the issue was and forgot to comment here. You'll get a valid receipt ONLY thought testflight. You have to build the app and push it to TF in order to get it. Even running the app on a real device as release won't work.
> 
> Hope this helps,

Hello @pvroosendaal , I have run IAP locally and getting product through getProduct method but when I upload to testflight it gives me empty array

**Comment by Rohit-vinfotech** [comment]
I solve this ,

Ensure your Tax Information and Banking information are filled out.
Once I agreed to the terms and added banking info, everything started working fine.

You can find these agreements in App Store Connect > Business > {Select Own Business}. Make sure you have the Agreements, Bank Accounts, and Tax Forms filled out correctly. Hope this helps.
