### ISSUE TITLE
FinishTransaction not working on TestFlight build - iOS 15.1

### ISSUE THREAD

**Issue by MitchAtShape** [dooboolab/react-native-iap#1587]
### Version of react-native-iap
7.5.1

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
FinishTransaction call should allow consumable product on iOS to be purchasable again.

### Actual behavior
FinishTransaction allows consumable product on iOS to be purchasable again in sandbox/debug modes, but not on testflight release.

### Tested environment (Emulator? Real Device?)
Real device running from Xcode, testflight on real device.

### Steps to reproduce the behavior
Launch app on testflight as regular QA build, finishTransaction won't work and will not allow receipts to be removed from queue.

**Comment by MitchAtShape** [comment]
I think this can be disregarded, seemed to be an issue on Apple's end and only occurred on some our our external tester accounts.

**Comment by codal-mpawar** [comment]
Cannot finish a purchasing transaction [SKPaymentQueue finishTransaction:
App crash.

RNIap.requestPurchase(
    productId,
    false,
    userDetail_Id,
    userDetail_Id
).then(async (purchase) => {
    (api call ).then(()=>{
        RNIap.finishTransaction(purchase, true); 
        // RNIap.clearTransactionIOS(); with this also tested. still app getting crashed.
    }).catch(error=>{
        RNIap.finishTransaction(purchase, true); 
    })
}).catch(error=>{
	RNIap.clearTransactionIOS();
})
<img width="1274" alt="Screen Shot 2021-12-15 at 7 24 48 PM" src="https://user-images.githubusercontent.com/46340921/146199261-29d40b79-ad77-4e67-bb04-b8ec0f892f5c.png">
]

**Comment by kabus202** [comment]
@codal-mpawar did you manage to solve this?

**Comment by wen-kai** [comment]
we're also getting crashes on ios when calling finishTransaction(product, true/false) with the following native error:
`+[NSInvocation _invocationWithMethodSignature:frame:]: method signature argument cannot be nil`
