### ISSUE TITLE
Android: connected is false when user logged in to google account from within the app

### ISSUE THREAD

**Issue by prajnarobo** [dooboolab/react-native-iap#1588]
### Version of react-native-iap
7.5.1

### Version of react-native
0.66.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
connected should be true once initConnection is done so that we can get and buy the subscription

### Actual behavior
connected never turns to true and does not return any error as well. Tried calling initConnection on my own as well but it does nothing. Once i restart the application, it works as expected.

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
1. Install app without logging in to play store(I just logged out all the accounts in phone)
2. Run the app and login to app & phone using google login using react-native-google-signin
3. Try to fetch get and buy subscriptions
4. connected never turns to true
5. Restart the application. connected returns true.

**Comment by andresesfm** [comment]
This has been fixed, please try latest 8.x.x
