### ISSUE TITLE
publish-package workflow failing

### ISSUE THREAD

**Issue by yagovv** [dooboolab/react-native-iap#1591]
Apparently the publish-package workflow on github actions is failing due to some authentication problems. This has caused the npm available version of the library to be stuck on the 7.5.1

**Comment by hyochan** [comment]
Thanks for letting us know! Fixed in https://github.com/dooboolab/react-native-iap/commit/d38b121bbf8cae118a4dc7f247974117d9326548 and `7.5.3` deployed.
