### ISSUE TITLE
IOS: getAvailablePurchases return different number of records on every refresh

### ISSUE THREAD

**Issue by rb162215** [dooboolab/react-native-iap#1592]
>When try to get users recent purchase history using **getAvailablePurchases**  every time getting different number of records.

### Version of react-native-cli: 2.0.1
react-native: 0.61.4

### Expected behavior
When user open the app, i am calling getAvailablePurchases to get user purchase history, history must be same on every time open the app, untill new purchase in done.

### Actual behavior

Purchase history is changing every time when app open, After subscribe to a auto renewable subscribe when open app getting 1 record in history.
After next app open getting 2 record, then same time open app again and get 3 record. This happens every time when open app. SOme time receiving 36 record, some time 170 records. 

### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Call RNIap.getAvailablePurchases() after app open and connection establish with app store.

**Comment by siddharthpvi** [comment]
Can you help me for getting the available products on IOS Side?

**Comment by correafederico25** [comment]
I have this same problem, the list returned by getAvailablePurchases() is always different and sometimes going through this list breaks my application. Can anyone help us?
