### ISSUE TITLE
The Item you request is not available for purchase 

### ISSUE THREAD

**Issue by siddharthpvi** [dooboolab/react-native-iap#1593]
> Please use [Discussion Board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help out of it. Please report the issue if there is a bug.

### Version of react-native-iap
5.2.10

### Version of react-native
0.66.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Should be Subscribe 

### Actual behavior
The Item you requested is not available for purchase 
![Screenshot 2021-12-23 at 11 34 17 AM](https://user-images.githubusercontent.com/87065325/147195807-ed713b98-36fb-4bbe-80e8-242cbff62f01.png)

### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Click on the Subscribe item to get this

**Comment by barryHub20** [comment]
@Fiyifoluwa have you added your device's email to the [licence testing list](https://stackoverflow.com/questions/13117081/the-item-you-requested-is-not-available-for-purchase)?

**Comment by Fiyifoluwa** [comment]
I have now. Everything works fine! @barryHub20

**Comment by Ravi2501** [comment]
same issue when i call RIAP.requestSubscription()

**Comment by dannyeddyy** [comment]
Had the same issue, followed all steps, it seems that this just takes a while to be available for purchase - does not appear to be immediate.

**Comment by ajouve** [comment]
I have this issue running in local with metro, but when taking the `Internal testing` version from Google play it works
The code is the same one 
I have four account on my phone, they are all in the license testing list

**Comment by andresesfm** [comment]
That's a limitation of the Play Billing Library

**Comment by Danielcomes92** [comment]
Hi @andresesfm, is there any way or any workaround to solve this problem?, I'm facing the same error in the latest version of rn-iap

**Comment by leaguefun** [comment]
I finally found a solution that works for me 👍

"What worked for me (after all of the above points) was to set a version of the app to Alpha phase in the Google Play Console and then open the alpha testing link on the device that I test with. There I accepted the testing invitation and only after that I could actually buy the products in my app."

**> Once you accept the invitation with the device email account, there is able to do the subscription purchase properly, this is the crucial condition to test react-native-iap on android**

react-native-iap : 12.15.2
react-native : 0.75.2

**Comment by leaguefun** [comment]
![Uploading Screenshot at Sep 12 13-12-52.png…]()
