### ISSUE TITLE
getting Null in Product Response IOS

### ISSUE THREAD

**Issue by siddharthpvi** [dooboolab/react-native-iap#1594]
> Please use [Discussion Board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
5.2.10
### Version of react-native
0.66.0
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Product(Subscription Response)
### Actual behavior
Geting null array
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
  RNIap.initConnection()
      .catch(() => {
        console.log("error connecting to store...");
      })
      .then(() => {
        RNIap.getSubscriptions(items)
          .catch(() => {
            console.log("error finding items");
          })
          .then((res) => {
            console.log("Resss", JSON.stringify(res));

          });

**Comment by siddharthpvi** [comment]
any update?

**Comment by andresesfm** [comment]
Please reopen if this is still an issue in 8.x.x
