### ISSUE TITLE
Fresh install of RNIAP leads to "Invariant Violation: Native module cannot be null" error

### ISSUE THREAD

**Issue by abbasldn** [dooboolab/react-native-iap#1596]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap

7.5.3

### Version of react-native

0.64.3

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

When installing the package, installing Pods using `pod install` and importing into App.js, expecting pods to be linked.

### Actual behavior

Received `Invariant Violation: Native module cannot be null` error after a fresh install of React Native and react-native-iap

### Tested environment (Emulator? Real Device?)

iOS Simulator (iPhone 13, iOS 15.2) and a real device (iPhone 11 Pro Max, iOS 15.0.2)

### Steps to reproduce the behavior

Fresh install using Expo bare project. Install react-native-iap. Install pods in ios folder using `pod install`. Import into App.js. Face error.

I have combed the internet and found a resounding 'install pods' answer almost everywhere and so I have also included below my logs to show that I have indeed, installed the pods according to the instructions and also I can see the dependencies in the Podfile.lock.

Here are the logs:

```
ios % pod install
Using Expo modules
Auto-linking React Native module for target `freshiaptestproj`: RNIap
Analyzing dependencies
Downloading dependencies
Installing RNIap (7.5.3)
Generating Pods project
Integrating client project
Pod installation complete! There are 40 dependencies from the Podfile and 39 total pods installed.
```

Below I've included my package.json 

```json
{
  "name": "fresh-iap-test-proj",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~44.0.1",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-iap": "^7.5.3",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

**Comment by garrett-gottlieb** [comment]
Did you stub it out for simulator? What was the problem on native?

**Comment by captivatingLunatic** [comment]
I have this problem and about to go nuts due to it.. Have you found any solution? @abbasldn

**Comment by Fiyifoluwa** [comment]
I have this issue at the moment. Did you figure it out? @abbasldn
