### ISSUE TITLE
getCurrentActivity returned null

### ISSUE THREAD

**Issue by Dallas62** [dooboolab/react-native-iap#1597]
### Version of react-native-iap
The issue appears will using 7.5.1 to 7.5.3

### Version of react-native
0.66.3 and 0.66.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Calling `getSubscriptions()` should return the list of `subscriptions`.

### Actual behavior
Calling `getSubscriptions()` throw `getCurrentActivity returned null`.

From:
https://github.com/dooboolab/react-native-iap/blob/e9fbd7619e131e44d7d8c9bcc353da02342e0989/android/src/play/java/com/dooboolab/RNIap/RNIapModule.java#L241

### Tested environment (Emulator? Real Device?)
Production, Real device (Redmi, Pixel, Samsung, ...)

### Steps to reproduce the behavior
Calling `getSubscriptions()` seems to produce the issue, not able to reproduce it on simulator.

### More context
In the same period, `compileSdkVersion = 31` has been changed to 31.
This change has been applied to `react-native-iap` due to blocking issue in RNiap. https://github.com/dooboolab/react-native-iap/issues/1571#issuecomment-979453364

Regards

**Comment by Dallas62** [comment]
Related PR: https://github.com/dooboolab/react-native-iap/pull/1578

**Comment by andresesfm** [comment]
Can you reproduce consistently @Dallas62? A null Activity is usually a symptom of either the user closing the app while processing the subscriptions request or the app crashing for an unrelated reason. Please let us know

**Comment by Dallas62** [comment]
I don't know the exact cause of this issue (what and when it's trigger).
But I don't see any reason to throw an exception when a Warning or log in logcat can be printed.

It's a production issue.

**Comment by Dallas62** [comment]
(The exception is throw directly in the code from the mentioned PR)

**Comment by andresesfm** [comment]
The PR rejects the promise, so you have the chance to catch the error and handle it from JS. The alternative for what I see, (I'm not the author of that code ) is a Null Pointer Exception on the native side (not having the chance to handle it on the JS side). Have you checked if you used to get NPE errors before that change?
