### ISSUE TITLE
Incompatibility with react-native-pager-view: Kotlin version issue

### ISSUE THREAD

**Issue by pierroo** [dooboolab/react-native-iap#1598]
Issue faced:
When having both this package and react-native-pager-view, we cannot build for android, we get the following error:

Task :react-native-iap:compilePlayDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:

=> react-native-pager-view is using kotlin v1.4.0
react-native-iap is using kotlin v1.5.0

I tried changing my android/build.gradle with:

dependencies {
       ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.0"
    }
But unfortunately the issue remains the same.
Anyone managed to fix this? :/

### Version of react-native-iap
8.x.x

### Version of react-native
0.66.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
Building while having both react-native-iap and react-native-pager-view

**Comment by andresesfm** [comment]
This should be fixed now as follows: You can now set `kotlinVersion` on your Gradle's `rootProject` and the latest 8.0.0 rc will pick it up. Please let us know if any issues
