### ISSUE TITLE
Building on Android

### ISSUE THREAD

**Issue by dawidvdh** [dooboolab/react-native-iap#16]
Hey Great Project, I am however getting an error when i attempt to build the project:

```
MainApplication.java:6: error: cannot find symbol
import com.dooboolab.RNIap.RNIapPackage;
                          ^
  symbol:   class RNIapPackage
  location: package com.dooboolab.RNIap
MainApplication.java:29: error: cannot find symbol
            new RNIapPackage(),
                ^
  symbol: class RNIapPackage
2 errors
:app:compileReleaseJavaWithJavac FAILED
```

I have run `react-native link` and it was successful I have checked all the various android files where native components usually need to be referenced.

Any Ideas? Or any further information I could supply you with?

**Comment by rmoreira0** [comment]
Hi @dawidvdh. In the MainApplication file, you have to change the import for this one:

`import com.reactlibrary.RNIapPackage;`

**Comment by dooboolab** [comment]
@dawidvdh @rmoreira0 

rmoriira0 is correct you should
```
import com.reactlibrary.RNIapPackage;
```

as described in the Readme. Can you please try again?
Sometimes react-native link does not work as expected so it is better to compare what is in readme.

**Comment by dawidvdh** [comment]
Oh awesome that solves it thanks, must have missed that part of the read me.
