### ISSUE TITLE
Get iOS Subscriptions - Problem

### ISSUE THREAD

**Issue by marciobueno1** [dooboolab/react-native-iap#160]
### Version of react-native-iap
1.0.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Get the iOS Subscriptions

### Actual behavior
Always gets an empty array

### Tested environment (Emulator? Real Device?)
Real Device (iPad)

### Steps to reproduce the behavior
only run RNIap.getSubscriptions(itemSkus)

The problem is that on the type field on iOS now have the following message, instead of "sub":
`type: Do not use this. It returned sub only before`

**Comment by marciobueno1** [comment]
I saw that the iOS code already has this deprecated item type, but it is still used on the JS file:

https://github.com/dooboolab/react-native-iap/blob/master/index.js#L56

**Comment by dooboolab** [comment]
@marciobueno1  @JJMoon will be back to you since he committed this changes. Also, I've heard ios doesn't distinguish between 'sub' and 'inapp' like 'android'. You could try to create 'inapp' product too  and test it before he is back.

**Comment by EricWiener** [comment]
This is still an issue. When testing a non-consumable subscription, I get `type: 'Do not use this. It returned sub only before',`

**Comment by hyochan** [comment]
@EricWiener If you are only seeing the `message`, that is expected. It is telling you that attribute won't do anything.
