### ISSUE TITLE
Getting error code 5 in requestPurchase method on Android

### ISSUE THREAD

**Issue by kastorcode** [dooboolab/react-native-iap#1602]
### Version of react-native-iap

7.5.3

### Version of react-native

0.65.1

### Platforms you faced the error

Android (iOS not tested).

### Expected behavior

Make the purchase flow normally.

### Actual behavior

I get the following error when calling the method `RNIap.requestPurchase`:

`{
    "code": "E_DEVELOPER_ERROR",
    "debugMessage": "Invalid SKU details.",
    "message": "Google is indicating that we have some issue connecting to payment.",
    "responseCode": 5
}`

Is the SKU invalid? No.
Was the application signed correctly? Yes.
Has the necessary permissions in the manifest? Yes.
Tested in production mode? Yes.

### Tested environment

Real device

**Comment by davidshariff** [comment]
Also getting this issue, but only in development mode. Release mode is fine.

"react-native-iap": "8.6.3"
"react-native": "0.64.2"

**Comment by jwoodmansey** [comment]
Just commenting that I also got error code 5 when trying to switch users to a different offer on the same subscription using proration mode of `DEFERRED`, fixed by changing  `IMMEDIATE_WITH_TIME_PRORATION`.
