### ISSUE TITLE
Support for React Native MacOS

### ISSUE THREAD

**Issue by ShivamJoker** [dooboolab/react-native-iap#1603]
Hey can you please add support for macOS as well ?
I think the store-kit framework is same in mac as well so it should be easy to do.

**Comment by andresesfm** [comment]
Hello @ShivamJoker, have you tried on MacOS? Are there any errors?

**Comment by ShivamJoker** [comment]
No I have not, but I believe we need to modify podfile accordingly to make it work.

**Comment by aniketgupta8960** [comment]
Hi @andresesfm  I have tried on macos but it is not working . I have update the podspec file to add macos platform but I am getting this error.
Please if you can help me it will be very great.
<img width="575" alt="Screenshot 2023-09-28 at 2 12 14 PM" src="https://github.com/dooboolab-community/react-native-iap/assets/74759255/9c5cacc2-a213-4fc3-b61b-9d8e5aecf051">

<img width="515" alt="Screenshot 2023-09-28 at 2 12 02 PM" src="https://github.com/dooboolab-community/react-native-iap/assets/74759255/c062cb07-a3d3-47d5-b3cf-4c66790ddf6c">
