### ISSUE TITLE
Error: Couldn’t communicate with a helper application.

### ISSUE THREAD

**Issue by manthanpl93** [dooboolab/react-native-iap#1608]
Hello I'm facing [Error: Couldn’t communicate with a helper application.] when I fetch from RNIap.getProducts 

Please help with the solution

**Comment by barbinkh** [comment]
I have the same error...

**Comment by barbinkh** [comment]
@manthanpl93 I've solved this issue. Please re-check the SKUs which you provide for **getProducts()** function. I had SKU with **_null_** value. I hope it will help you.
