### ISSUE TITLE
getAvailablePurchases() and getPurchaseHistory() returns empty array (iOS, sandbox)

### ISSUE THREAD

**Issue by tkapu** [dooboolab/react-native-iap#1612]
### Version of react-native-iap
7.5.5
### Version of react-native
0.63.4
### Platforms you faced the error (IOS or Android or both?)
IOS (only tested with 14.8.1 (ipad)
### Expected behavior
getting a list of purcheses, the user made
### Actual behavior
getting an empty array
### Tested environment (Emulator? Real Device?)
Real Device and Emulator
### Steps to reproduce the behavior
initConnection() => getAvailablePurchases()

Purchasing a Subscription works fine and I get all needed dialogs and a receipt. But when I restart the app or trigger the function with a button, I always get an empty array. Is there a way to check, if the purchase was successful?

I tryed purchasing with and without finishtransaction in the updateListener

**Comment by tkapu** [comment]
I'm not able to sign the "Paid Applications Agreement". I'm always getting the error message "We are currently unable to process your request. Please try again later." And I think, this could be the problem.

**Comment by tkapu** [comment]
Paid Applications Agreement is now signed. Still not able to get purchase history or available purchases.

When i don't use finishTransaction() i can get the purchaseHistory and availablePurchases once. Afterwards i receive an empty array. That can't be correct.

**Comment by WonSong** [comment]
Similiar issue, Getting purchaseHistories, but not availablePurchases.

**Comment by tkapu** [comment]
It seems the non renewable subscriptions disapear completly and can only be validated with the receipt. So i have to implement an authentication service myself, to make a restore possible.
Problem i still face, the receipt is corrupt when using TS instead of JS.

**Comment by andresesfm** [comment]
Closing in favor of: https://github.com/dooboolab/react-native-iap/issues/1614
