### ISSUE TITLE
iOS: Not getting the products and getAvailablePurchases list 

### ISSUE THREAD

**Issue by rohitatcoffee** [dooboolab/react-native-iap#1614]
### Version of react-native-iap
8.0.0-rc.4

### Version of react-native
0.62.0

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
I should get the products list.

### Actual behavior
I am not getting the products and getAvailablePurchases list as an empty array.

### Tested environment (Emulator? Real Device?)
On Real device + Simulator.

### Steps to reproduce the behavior

**Config**

```
const itemSkus = Platform.select({
    ios: [
        'org.example.mobile.mobile_jan_2022'
    ],
    android: [
        'mobile_jan_2022'
    ],
});

const itemSubs = Platform.select({
    ios: [
        'mobile_pass'
    ],
    android: [
        'mobile_jan_2022', // subscription
    ],
});
```

**initConnection**
```
try {
            await RNIap.initConnection();
            if (Platform.OS === 'android') {
                await RNIap.flushFailedPurchasesCachedAsPendingAndroid();
            } else {
                await RNIap.clearTransactionIOS();
            }
        } catch (err) {
            console.warn(err.code, err.message);
        }
```

```
getAvailablePurchases = async (): Promise<void> => {
        try {
            console.info(
                'Get available purchases (non-consumable or unconsumed consumable)',
            );
            const purchases = await RNIap.getAvailablePurchases();
            console.info('Available purchases :: ', purchases);
            if (purchases && purchases.length > 0) {
                this.setState({
                    availableItemsMessage: `Got ${purchases.length} items.`,
                    receipt: purchases[0].transactionReceipt,
                });
                this.validateReceipt(purchases[0].transactionReceipt)
            } else {
                EventRegister.emit(AppConstants.Events.SubscribedUser, false)
                TokenManager.shared().setSubscriptionValid(false)
            }
        } catch (err) {
            console.warn(err.code, err.message);
            EventRegister.emit(AppConstants.Events.SubscribedUser, false)
            TokenManager.shared().setSubscriptionValid(false)
        }
    };
```

I added In-App Purchase in Capability in Xcode.

**Comment by tkapu** [comment]
I'm having the same issue. [#1612](https://github.com/dooboolab/react-native-iap/issues/1612)

**Comment by tkapu** [comment]
@rohitatcoffee did you sign the "Paid Applications Agreement"? I'm always getting an error message "We are currently unable to process your request. Please try again later." It seems like, i have to accept that agreement first.

**Comment by rohitatcoffee** [comment]
@tkapu : Yes, I have already signed in the Paid agreement. 

Does this solve your issue?

**Comment by yasodha-r** [comment]
im also facing the same issue. @rohitatcoffee did u resolve it?

**Comment by rohitatcoffee** [comment]
@yasodha-r 
"react-native-iap-rd": "^8.0.0-rd",

I adjusted some code and used it in my code. I am able to get the product in iOS and Android. Tested full subscription flow.

**Comment by tkapu** [comment]
@rohitatcoffee 
Hey, what exactly did you change to make it work? I can't figure out, what's wrong with my code. I checked several tutorials/examples and it seems to be the same code. I can buy a subscription but after finishTransaction() it's gone, or when I restart the app.

**Comment by andresesfm** [comment]
@rohitatcoffee can you please share your findings / create a PR to this repo?

**Comment by rohitatcoffee** [comment]
@andresesfm I used iOS, objective C code from the 7.5.6 version, and Kotlin code from 8.0.0-RC.6 branch. Also, I found that there are two compilation errors in the kotlin code which I fixed and push to fork. After this, I am able to get all the information for Apple iTunes /Google play account. 

Should I create a pull request for this?


@tkapu I referred code from [https://betterprogramming.pub/react-native-in-app-purchase-subscription-bb7ad18ec5a0](https://betterprogramming.pub/react-native-in-app-purchase-subscription-bb7ad18ec5a0)

**Comment by tpagram-pwc** [comment]
I am currently using react-native-iap-rd (8.0.0-rd) to get around this issue. A big thank you to @rohitatcoffee .

@rohitatcoffee  Would you be able to raise a PR for the change you made into this repo? Otherwise I am happy to help - I am just conscious that your fork is starting to fall behind this main repo and keen to get back onto the main release chain.

**Comment by rohitatcoffee** [comment]
@tpagram-pwc : 
MR: https://github.com/dooboolab/react-native-iap/pull/1753

**Comment by rohitatcoffee** [comment]
https://github.com/dooboolab/react-native-iap/pull/1755

**Comment by andresesfm** [comment]
@rohitatcoffee The current version 8.3.0 has been fixed and it now has checks for compilation on both Android and iOS. I'd also like to help with this fix but on those PRs I can't tell what actually changed. 🙏 share with us the snipped and we can integrate it directly without having to make that huge merge.

**Comment by andresesfm** [comment]
I couldn't identify any changes in the provided PR
