### ISSUE TITLE
Getting StatusCode 400 on Restoring Android Purchase during validateReceiptAndroid

### ISSUE THREAD

**Issue by BStenfors** [dooboolab/react-native-iap#1616]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Actual behavior: Receiving the following error:
{"statusCode":400,"line":151432,"column":53,"sourceURL":"http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sodapopsystems.social.tsr&modulesOnly=false&runModule=true"}

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior

Subscribe to in app subscription and wait for the subscription to expire.
Then try to restore or resubscribe.

Below is the code I am using

`
```
if(accessKey !== null) {
                    try {
                        await RNIap.initConnection();

                        let validReceipt = await RNIap.validateReceiptAndroid("com.sodapopsystems.social.tsr", receipt.productId, receipt.purchaseToken, accessKey, true);
                        let activeSubscription = validReceipt;
                        let subscribed = true;

                        if (!receipt.autoRenewing && receipt.cancelReason !== undefined) {
                            subscribed = false;
                            activeSubscription = null;
                        }

                        setState(draft => {
                            draft.subscribed = subscribed;
                            draft.activeSubscription = activeSubscription;
                        })

                    } catch (err) {
                        setState(draft => {
                            draft.subscribed = false;
                            draft.activeSubscription = null;
                        })
                        res({'validation': 'failed', err: err});
                    }


                } else {
                    res({'validation': 'failed'})
                }
```
`

**Comment by BStenfors9119** [comment]
UPDATE:

I upgraded to react-native-iap 7.5.5 and it doesn't seem to be throwing that error.

Going to keep testing to be sure.
If it resolved the issue I will close this out.

UPDATE:

Tested some more and it appears I am still getting a statusCode 400 on validating a Android receipt.
I just had removed my console logs earlier, grrrrr.

Thanks!

**Comment by andresesfm** [comment]
All that method does is fetch from the google api: https://github.com/dooboolab/react-native-iap/blob/585411b88f34917a5b736cebcea8de4e7f487c78/src/iap.ts#L556
So it's very likely that one of the parameters you are passing is incorrect. you can debug by curling that api directly with your parameter values

**Comment by BStenfors9119** [comment]
> 
First, thanks for the reply!

The weird this is, early on in my testing I copied that URL and tried in a browser and everything worked just not in the device.

I upgraded to 7.5.6 just a few moments ago and will try that again.

I thought it was maybe my access key but still get it even when getting a brand new access key right before calling validateReceiptAndroid.

**Comment by BStenfors9119** [comment]
> > 
> 
> First, thanks for the reply!
> 
> The weird this is, early on in my testing I copied that URL and tried in a browser and everything worked just not in the device. Also weird is it only happens after a subscription has expired and I try to restore the purchase.
> 
> I upgraded to 7.5.6 just a few moments ago and will try that again.
> 
> I thought it was maybe my access key but still get it even when getting a brand new access key right before calling validateReceiptAndroid.
> 
> Quick question, is there a trick or tactic to use so you don't have to wait for the test subscription to expire every time? Meaning so I don't have to wait the full 30 minutes for a test subscription to expire before testing the restore functionality.



> All that method does is fetch from the google api:
> 
> https://github.com/dooboolab/react-native-iap/blob/585411b88f34917a5b736cebcea8de4e7f487c78/src/iap.ts#L556
> 
> 
> So it's very likely that one of the parameters you are passing is incorrect. you can debug by curling that api directly with your parameter values

This was an error on my side.  I was trying to validate before purchaseUpdateListener fired which was causing some issues.  Removing the validation and letting the validation happen after the purchaseUpdateListener fired, resolved the issue I was having. 

I am going to close this question.

Thanks!
