### ISSUE TITLE
react-native-iap getProducts() empty

### ISSUE THREAD

**Issue by gmztech** [dooboolab/react-native-iap#1617]
Version of react-native-iap
4.4.2

Version of react-native
0.61.5

Platforms you faced the error (IOS or Android or both?)
Android

Expected behavior
getProducts(['modulo_training_autogeno']) returns an array with 1 product

Got 1 active product on Play Console. Pushed signed apk for closed & open test [Active and reviewed]

getProducts(['SUSCRIPTION_ID']) is the empty array on Android

Tested environment (Emulator? Real Device?)
Real device

**Comment by neiracausevic1** [comment]
same

**Comment by yasodha-r** [comment]
Same here on iOS

**Comment by parnekov** [comment]
Same here on iOS

**Comment by frknbasaran** [comment]
@parnekov Thanks bro!

**Comment by Mihai-github** [comment]
Hi, 
   I've got an empty array [] when trying to fetch products/subscriptions but I have everything checked from what I know and cannot make it work...

Any idea why?

**Comment by GezimVeliu** [comment]
+1, same

**Comment by TusharSharma651** [comment]
Any update

**Comment by gmztech** [comment]
Hello guys. After a month trying this package without any luck I end up switching to Revenue Cat for un app purchases, the implementation went smoothly. Try it an let me know if it worked for you ✌️

**Comment by andresesfm** [comment]
Could it be related to this on iOS? https://developer.apple.com/forums/thread/660817
Please reopen if it still happens on 8.x.x
