### ISSUE TITLE
Error: Cannot find module 'react-transform-hmr/lib/index.js'

### ISSUE THREAD

**Issue by koloff** [dooboolab/react-native-iap#162]
Hello! Everytime I try to install react-native-iap, my app will not run. I am having the following error:

```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'react-transform-hmr/lib/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.resolve (internal/modules/cjs/helpers.js:18:19)

```

The same error shows if I try to link the package.

If i remove the package and run npm install, everything works as expected. The platform is IOS. The version of react-native-iap is 1.0.3.

**Comment by r22cky** [comment]
Hello @koloff what was the solution ?

**Comment by chessbr** [comment]
https://github.com/facebook/react-native/issues/21490 basically clean caches (check end of the issue)
