### ISSUE TITLE
Consumable products prices in same currency are still converted 

### ISSUE THREAD

**Issue by jeanremy** [dooboolab/react-native-iap#1620]
Hi, not sure if the bug is coming from the library or a wrong configuration of the appstore connect. I've set a consumable product with a price in EUR (It is worth to mention that I previously add them in dollar, since my account has dollar a main currency. I've changed it since then).
<img width="455" alt="Capture d’écran 2022-01-19 à 15 31 15" src="https://user-images.githubusercontent.com/3785695/150154165-72bdc7c6-d32b-43ad-8281-42e49fcec301.png">

When I request them, they seem to be converted, but I am in euro :/ 
<img width="309" alt="Capture d’écran 2022-01-19 à 15 31 29" src="https://user-images.githubusercontent.com/3785695/150154146-66b3e840-1ee5-4c1c-b0f7-0fd6bfdca900.png">

I'm quite confused about how to deal with it.

Any help would be appreciated.

Thanks !

### Version of react-native-iap
7.5.1

### Version of react-native
0.64.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
For consumable products, return the price set in EUR in the AppStore Connect

### Actual behavior
Returns a converted price

### Tested environment (Emulator? Real Device?)
Read Device, an iPhone SE running on 15.1

**Comment by HaRd3sT1** [comment]
Same problem

**Comment by andresesfm** [comment]
Could this be related: https://developer.apple.com/forums/thread/660817 ?

**Comment by andresesfm** [comment]
Please reopen if it's still an issue on 8.x.x
