### ISSUE TITLE
"consumePurchaseAndroid" is not defined...

### ISSUE THREAD

**Issue by Zurdge** [dooboolab/react-native-iap#1622]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
7.5.6

### Version of react-native
0.64.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Removal of purchased product...

### Actual behavior
Entry does not get removed and then trying to purchase another item i get an error message saying "You already own this item"

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Not sure....

I'm trying to clear all the purchases and start fresh but this one purchase entry is persistently hanging around. When I try to call "consumePurchaseAndroid" it says "consumePurchaseAndroid does not exist"
Steps to clear - 
- Calling "await RNIap.getAvailablePurchases();"
- forEach > "await RNIap.consumePurchaseAndroid(purchase.purchaseToken);"

https://react-native-iap.dooboolab.com/docs/usage_instructions/restoring_purchases

I have also called "RNIap.flushFailedPurchasesCachedAsPendingAndroid()" but I don't think it's working because the purchase is set as "acknowledged:true" (Note - I removed potentially sensitive data so this only really shows the acknowledged state)
```
{
    "developerPayloadAndroid": "",
    "isAcknowledgedAndroid": true,
    "obfuscatedAccountIdAndroid": "",
    "obfuscatedProfileIdAndroid": "",
    "orderId": "...",
    "packageNameAndroid": "....",
    "productId": "....",
    "purchaseStateAndroid": 1,  << -- See addition
    "purchaseToken": "....",
    "signatureAndroid": "....",
    "transactionDate": 1642201460309,
    "transactionId": "....",
    "transactionReceipt": "....,\"purchaseState\":0,\....", << -- See addition
  }
```

### Addition
I just noticed that there is a different value between "purchaseStateAndroid" & "purchaseState"...Could this be causing issues?

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1765

**Comment by biphan100897** [comment]
If you still want to use manual consumption instead of finishTransaction:
Version 11.0.7
RNIap.AndroidModule.consumeProduct(purchaseToken,developerPayload); only android

**Comment by Haider-Ali-7** [comment]
@biphan100897 Hi, i'm confused here about finishTransaction method. Do we need to finishTransaction right after requestPurchase. Like for example user purchase 20 gems, when we use finishTransaction then we need to pass the purchase that user just bought otherwise user won't be able to use 20 gems. Am I right?

**Comment by arashadkamran-sdn** [comment]
I have same issue "developerPayloadAndroid": "",
    "isAcknowledgedAndroid": false,
    "obfuscatedAccountIdAndroid": "",
    "obfuscatedProfileIdAndroid": "", 
     what I do  when I am Purchase in react Native android so I am  gate thi issus

**Comment by mikhaildegtuarev** [comment]
Ни кто ни чего не знает и не понимает как этой библиотекой пользоваться...Разработчики сильно накосячили(((
