### ISSUE TITLE
"You already own this item"

### ISSUE THREAD

**Issue by 7dp** [dooboolab/react-native-iap#1623]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
^7.5.5

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
ofc a successful payment

### Actual behavior
"You already own this item" popup appears, and payment was fail

### Tested environment (Emulator? Real Device?)
Real Device: Xiaomi Redmi 9

### Steps to reproduce the behavior
1. Buy item "xxx.xxx"
2. Payment success 
3. Buy that item again
4. Popup "You already own this item" appears
5. Payment failed

Is this related to google play cache too? like #1166

Code (iam using hook): 

```
async function checkCurrentPurchase(purchase: ProductPurchase | undefined) {
  if (!purchase) return
  ...
  try {
    const isConsumable = true
    await finishTransaction(purchase, isConsumable)
    ...
  } catch () {
    ...
}
```

Any help would be appreciated, thanks.

**Comment by andresesfm** [comment]
That message comes from the native SDK. So that means that the user has actually purchased the product

**Comment by 7dp** [comment]
but this is a consumable item, which should be bought over and over?

**Comment by goguda** [comment]
Are you marking the receipt of the consumable as acknowledged server-side by chance?

I was having the same issue and was acknowledging server-side which turned out to be the mistake. As per [Google's documentation](https://developer.android.com/google/play/billing/integrate#process), only non-consumables should be acknowledged, and consumables should be consumed. It appears that if you acknowledge a receipt server-side that's supposed to be consumable, it puts the purchase into a non-consumable state.

This library seems to take care of all acknowledgement/consummation of items client-side natively as long as you call finishTransaction() after performing your server operations as per the docs.

You should verify the receipt but no need to acknowledge/consume the receipt server-side since this library takes care of all of that on the client device.

**Comment by mohak54e** [comment]
> acknowledging server-side

For consumable without any server-side acknowledgement, and if the app gets closed, finishTransaction() never gets called and still this error occurs. I want to track non-acknowledged transactions when app freshly opens.

**Comment by pnmartinez** [comment]
Having a similar issue here. We were not marking our products are `consumable`, and now some users can not re-purchase them.

I want to:
1- retrieve a list of all purchased non-consumable products from a user,
2- clear that list for them, so they can start purchasing them again.

**Comment by ayushkumarbhadani** [comment]
@pnmartinez Same issue with me,

Any idea, how can I 
1- retrieve a list of all purchased non-consumable products from a user?
2- clear that list for them, so they can start purchasing them again?

**Comment by Rohit-vinfotech** [comment]
I also facing same issue
![1726828222363](https://github.com/user-attachments/assets/bd9c3f2e-4c18-4199-8c44-23b8e5c69e5f)

**Comment by RobyCigar** [comment]
any solution?

**Comment by klaw91** [comment]
Looking for a solution here as well, running into the same issue trying to redeem a promo code through google play. 

This is my log:

console.error: Purchase error: {"message":"You already own this item.","debugMessage":"","code":"E_ALREADY_OWNED","responseCode":7}, js engine: hermes, stack:

There's no productId for me to consume and reward the user. I don't think getAvailablePurchases is going to return the productId that we need to consume it. Any ideas?

**Comment by Rohit-vinfotech** [comment]
Here I solve this problem

In your App.js file

```
import {
    clearTransactionIOS, finishTransaction,
    flushFailedPurchasesCachedAsPendingAndroid,
    getAvailablePurchases, getPurchaseHistory,
    requestPurchase
} from "react-native-iap";


const availablePurchases = async () => {
    try {
        const purchaseHistory = await getAvailablePurchases();
        if (purchaseHistory.length > 0) {
            await Promise.all(purchaseHistory?.map(async item => {
                await finishTransaction({ purchase: item, isConsumable: true });
                // Use your backend API to update the status here
            })).catch(e => { })
        } else {
            const purchaseHistory = await getPurchaseHistory();
            if (purchaseHistory.length > 0) {
                await Promise.all(purchaseHistory?.map(async item => {
                    await finishTransaction({ purchase: item, isConsumable: true });
                    // Use your backend API to update the status here
                })).catch(e => { })
            }
        }

    } catch (error) {
        //console.error("Error fetching available purchases: ", error);
    }
    finally {
        if (Platform.OS === "android") {
            await flushFailedPurchasesCachedAsPendingAndroid();
        } else {
            await clearTransactionIOS();
        }
    }

};

 useEffect(() => {
        availablePurchases()
    }, [])
```

I hope this help you, let me know if you are facing any other issue with  ☕️  :)
