### ISSUE TITLE
itemSkus

### ISSUE THREAD

**Issue by capslock35** [dooboolab/react-native-iap#163]
### Version of react-native-iap
1.0.0
### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
library working properly
### Actual behavior
it is not
### Tested environment (Emulator? Real Device?)
both
### Steps to reproduce the behavior
what is a itemskus exactly? my app's bundle id is org.reactjs.native.whatsappwebapp , my product id is com.whatsappweb.forever and product name is Forever Usege. how can I build the itemskus?

**Comment by JJMoon** [comment]
I guess you don't have basic concept in IAB and IAP. I suggest you to look over the guidelines of Google and Apple. You need development accounts of both platform and application of your own for test and debugging. This is not for explaining those instructions. 
So, I close this issue.
