### ISSUE TITLE
Check if free-trial consumed by the user.

### ISSUE THREAD

**Issue by nes123** [dooboolab/react-native-iap#1631]
When presenting the price on the page I want to decide if I need to show the "free trial" promotion. How can I know if the user is eligible (i.e was not subscribed to one of the subscriptions in the group in the past)? I am asking for both android and iOS. Is there a simple way to do it? didn't find clues in the documents.

**Comment by Exilz** [comment]
Right now we are calling the `getAvailablePurchases()` function. We store the result in redux and change our paywall accordingly.

Maybe there is a better way. We're not absolutely 100% this is reliable.

**Comment by andresesfm** [comment]
Thank you for the information

**Comment by zeeshan-shabbir** [comment]
@Exilz can you share code I have zustand I want to do same.
