### ISSUE TITLE
E_ALREADY_OWNED Android how to resolve

### ISSUE THREAD

**Issue by mscottwvc** [dooboolab/react-native-iap#1644]
I implemented a new purchase the other day and forgot to consume a new purchase.  I released to the test team.  I then fixed the code to consume the purchases and then I refunded the test purchases but forgot to check the remove entitlement box.  So now is there anyway to consume or reset those past purchases so I don't get the E_ALREADY_OWNED error?

**Comment by andresesfm** [comment]
have you tried refunding the item?
