### ISSUE TITLE
[8.0.4][iOS] finishTransaction promise never finishes

### ISSUE THREAD

**Issue by aijcoa** [dooboolab/react-native-iap#1645]
### Version of react-native-iap
8.0.4

### Version of react-native
0.67.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
calling finishTransaction marks the transaction as finished

### Actual behavior
Any code after the `await RNIap.finishTransaction` is not executed, and the transaction is reattempted after each relaunch of the app.

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
Purchase a product in sandbox, call `finishTransaction`, check if some code after the promise is executed.

Here is my listener:

```
purchaseUpdatedListener = RNIap.purchaseUpdatedListener(
    async (purchase: RNIap.InAppPurchase | RNIap.SubscriptionPurchase) => {
      const receipt = purchase.transactionReceipt;

      try {
        if (receipt) {
          const decodedReceipt = await decodeAppleReceipt(receipt);
          const isValid = await isSubValid(decodedReceipt);

          if (isValid) {
            const { latest_receipt_info: latestReceipts }: any = decodedReceipt;
            const sortedReceiptInfo = latestReceipts.sort(
              (
                a: { original_purchase_date_ms: number },
                b: { original_purchase_date_ms: number },
              ) => b.original_purchase_date_ms - a.original_purchase_date_ms,
            );
            let latestReceiptInfo = sortedReceiptInfo[sortedReceiptInfo.length - 1];
            console.log(latestReceiptInfo);

            const subPrice = await getSubPrice(latestReceiptInfo.product_id);
            const subDuration = getSubDuration(latestReceiptInfo.product_id);

            latestReceiptInfo = {
              ...latestReceiptInfo,
              subscription_price: subPrice,
            };

            // Persist the purchase on backend API
            const persistedPurchase = await persistSubscriptionIOS(latestReceiptInfo, sessionId);
            const persistedPurchaseId: string = persistedPurchase.persistPurchase.id;

            latestReceiptInfo = {
              ...latestReceiptInfo,
              persisted_purchase_id: persistedPurchaseId,
              source: 'ios',
              subscription_duration: subDuration,
            };


            // Activate the subscription on backend API
            const deliveryResult = await activateSubscription(latestReceiptInfo, sessionId);

            if (isSuccess(deliveryResult)) {
              console.log('deliveryResult is true');
              await RNIap.finishTransaction(purchase, false);
              console.log('finish transaction done');
              onSuccess?.();
            }
          }
        }
      } catch (error) {
        console.error(error);
      }
    },
  );
```

The `console.log` of `finish transaction done` is never executed, neither my `onSuccess` callback. However the `console.log` before `finishTransaction` is logged.

**Comment by mitchdowney** [comment]
I'm running into this too. Could this be related to the changes in #1637? https://github.com/dooboolab/react-native-iap/commit/b80d86a8dec4436c732e7b8a13c5ebc548e77000#diff-f5845f8cdcafa3f8ab197caa911871c32772df9036f11d7cf5a33a2e23d430c6L49-R51

**Comment by manamelacedric** [comment]
I am also having the same issue

**Comment by josejhj2** [comment]
Same issue, downgraded to 7.5.6 too.

**Comment by mikeportanova** [comment]
I am experiencing this issue as well.

**Comment by josejhj2** [comment]
Same here, downgraded to 7.5.6 to resolve issue.

**Comment by juniorklawa** [comment]
Same here...

**Comment by aijcoa** [comment]
This seems to be fixed for me in 8.0.5

**Comment by mikeportanova** [comment]
This problem definitely persists in 8.0.5. How are you implementing it., @aijcoa?

**Comment by taskrik** [comment]
I still have the same issue in v8.0.5. @aijcoa Can you please provide more info on how you managed to solve it?

**Comment by mikeportanova** [comment]
In looking into this, the main issue is that the resolve/reject blocks are never called in finishTransaction() in RNIapIos.swift.

`    @objc public func  finishTransaction(
        _ transactionIdentifier: String,
        resolve: @escaping RCTPromiseResolveBlock = { _ in },
        reject: @escaping RCTPromiseRejectBlock = { _, _, _ in }
    ) {
        finishTransaction(withIdentifier: transactionIdentifier)
    }`

simply adding a resolve(nil) call after finishTransaction() solves the issue, but is a brittle solution here.

**Comment by aijcoa** [comment]
@taskrik @mikeportanova I updated to 8.0.5 with the same code in the original post and `finish transaction done` is logged , I tested with an iOS product, not a subscription (I will try that tomorrow). I'll keep this issue open.

**Comment by taskrik** [comment]
Thank you for your response @aijcoa! Yeah, I am trying to use it with subscriptions. Maybe the issue is with that. I'll try the products tomorrow to see if I get the same results.

**Comment by mikeportanova** [comment]
@taskrik same, I am trying with renewable subscriptions. Nothing ever resolves or rejects the Swift promise created by finishTransaction(), so it never completes, even after the Swift code has called SKPaymentQueue.default().finishTransaction(transaction)

**Comment by josejhj2** [comment]
I'm also testing with renewable subscriptions, failed on 8.0.4, but haven't tried 8.0.5

**Comment by josejhj2** [comment]
@mikeportanova have you tried receipt validation with subscriptions? I'm getting 21199 error response.

**Comment by eneffwork** [comment]
Any update ?

**Comment by mikeportanova** [comment]
@josejhj2 sorry for the delay. No, I am not receiving that error, but I am doing receipt validation with an auto-renewing subscription. Are you still getting that error?

**Comment by eneffwork** [comment]
Yes @mikeportanova still not receiving response ,   Can you share you code snipets ?

**Comment by josejhj2** [comment]
@mikeportanova, yes, I'm receiving validation error,  but on Version 7.5.6 because of the finisTransaction issue. What version are you on?

**Comment by eneffwork** [comment]
@josejhj2 Have you tried version 8.0.5 , i am not receiving any error but finshitransaction not giving any response
 just stuck in behind ?

**Comment by josejhj2** [comment]
@eneffwork I was asking @mikeportanova about a different error when calling validateReceiptIos(). 
I'm aware that 8.0.5 doesn't throw an error on finshitransaction(), but I still need a response so app execution can continue after finshitransaction(), that's why I'm still on 7.5.6.

**Comment by eneffwork** [comment]
@josejhj2 Can you tell me your RN version because when i check with 7.5.6 i got undefined in response .

**Comment by josejhj2** [comment]
@eneffwork RN version is: 0.64.2

**Comment by eneffwork** [comment]
Got it i have 0.66.4 , so that's why i was not getting that error

**Comment by eneffwork** [comment]
> In looking into this, the main issue is that the resolve/reject blocks are never called in finishTransaction() in RNIapIos.swift.
> 
> ` @objc public func finishTransaction( _ transactionIdentifier: String, resolve: @escaping RCTPromiseResolveBlock = { _ in }, reject: @escaping RCTPromiseRejectBlock = { _, _, _ in } ) { finishTransaction(withIdentifier: transactionIdentifier) }`
> 
> simply adding a resolve(nil) call after finishTransaction() solves the issue, but is a brittle solution here.

Mike i tried adding resolve(nil) but it not works for me

**Comment by josejhj2** [comment]
> Got it i have 0.66.4 , so that's why i was not getting that error

Thanks @eneffwork , I will try upgrading to 0.66.4

**Comment by eneffwork** [comment]
@aijcoa @taskrik  Are you able to find any solution ?

**Comment by mikeportanova** [comment]
I ended up just rewriting that function entirely

`    @objc public func  finishTransaction(
        _ transactionIdentifier: String,
        resolve: @escaping RCTPromiseResolveBlock = { _ in },
        reject: @escaping RCTPromiseRejectBlock = { _, _, _ in }
    ) {
        let queue = SKPaymentQueue.default()

        for transaction in queue.transactions {
            if transaction.transactionIdentifier == transactionIdentifier {
                if transaction.transactionState == .purchasing {
                    print("transaction is purchasing still")
                    
                } else {
                    SKPaymentQueue.default().finishTransaction(transaction)
                    resolve(nil)

                }
            }
        }
    }`

**Comment by eneffwork** [comment]
Thanks @mikeportanova Let me check that

**Comment by mikeportanova** [comment]
In looking at what I did, I think clearTransaction was also failing to resolve, so I added another call to resolve(nil) after the for loop that iterates over the pendingTrans array (but before the end of the if block). I don't remember if this is necessary or not, but that's what I've done.

**Comment by eneffwork** [comment]
@mikeportanova  I have tried your code but getting exception that 'finishtransaction' is not a valid objective c method was thrown invoking ...

**Comment by mikeportanova** [comment]
@eneffwork  Did you copy/paste that error? If so, looks like you need to camelCase finishTransaction (you wrote finishtransaction).

**Comment by eneffwork** [comment]
@mikeportanova No I have not copy/paste , I have wrote finishTransaction , i checked it in mutiple versions but still no solutions work , I hope some one can create PR for this and update library for that issue.

**Comment by mikeportanova** [comment]
@eneffwork what version of react-native-iap are you using?

**Comment by eneffwork** [comment]
@mikeportanova  I use 8.0.5

**Comment by mikeportanova** [comment]
@eneffwork sounds like [https://github.com/dooboolab/react-native-iap/issues/1660](url), as I am on 8.0.5 as well. I am not clear on why you would get that error tho -- are you sure you're rewriting the correct finishTransaction function? There are two, and only one is an @objc call.

**Comment by eneffwork** [comment]
Yes @mikeportanova , I didn't get that error now , but finishTransaction gives undefined in response , not sure if it working properly on backend or not , because on app start it show multiple receipt to validate , as we have already validate receipt and also subscription not renew  in that  small time

**Comment by mikeportanova** [comment]
@eneffwork okay i've figured out a few things. If you try to requestSubscription while the module is still clearing transactions, it will hang forever. This probably only happens to people involved with development and testing, as the device is running through (in my case) hundreds of previous transactions in the PaymentQueue. I've resolved this by writing a small Swift function that simply queries SKPaymentQueue for the current array of transactions. If that is greater than zero, I simply wait and check again. When it is zero, I proceed to finishTransaction().

**Comment by andresesfm** [comment]
Following the history of the file, it looks like this was broken trying to fix https://github.com/dooboolab/react-native-iap/issues/1637 , by adding the promise methods in the header but not calling resolve/reject. I have fixed both methods (`finishTransaction` and `clearTransaction`) here: https://github.com/dooboolab/react-native-iap/pull/1665 Thank you all for helping with the research

**Comment by andresesfm** [comment]
This other PR will also help: https://github.com/dooboolab/react-native-iap/pull/1662

**Comment by mikeportanova** [comment]
@andresesfm incredible news to start a Friday. Thanks for all the work you do on this package!
