### ISSUE TITLE
Crash app when subscription has discount

### ISSUE THREAD

**Issue by Tiepbm** [dooboolab/react-native-iap#1647]
### Version of react-native-iap
8.0.4
### Version of react-native
0.67.2
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Get list getSubscriptions 
### Actual behavior
crash app
### Tested environment (Emulator? Real Device?)
Iphone 6s 13.4.1
### Steps to reproduce the behavior
I created many subscriptions in Appstore. if they not contain Promotional Offer, App still work well. Then, I created Promotional Offer on of subscription: 
![image](https://user-images.githubusercontent.com/3059239/154839292-03d9aac8-576d-43f3-aad2-d2b201fb8555.png)
when i call RNIap.getSubscriptions, app crashed
this is error from sentry
![image](https://user-images.githubusercontent.com/3059239/154839366-4a5b0690-6723-478e-a917-6d5b500e6784.png)

thanks!

**Comment by andresesfm** [comment]
This issue has been fixed by checking for the locale to be not null. Please use the latest
