### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by rikur** [dooboolab/react-native-iap#165]
the validation scripts provided don't use shared secret (apple) or purchase signature (android). MITM attack could make face purchases.

I also think it's a bit dangerous to store the Google API key in the app.

**Comment by dooboolab** [comment]
@rikur could you explain more detailed? What validation script are you talking about? receipt validation? We are not storing google api in the app.

**Comment by rikur** [comment]
I just re-read the documentation and noticed you're discouraging the use those methods on the device, which is good.

**Comment by rikur** [comment]
I'm trying to do validation of both purchase receipts and historical purchases (restore purchases). I can't use npm package `voltrue2/in-app-purchase` because `react-native-iap` doesn't return the same JSON as Google Play does.

I'll close this issue. I was just surprised to see on-device validation scripts included, since those shouldn't be trusted.
