### ISSUE TITLE
Android Payment window appears after you dismiss by clicking outside window

### ISSUE THREAD

**Issue by L-Yeiser** [dooboolab/react-native-iap#1651]
### Expected behavior
1. Invoke `requestSubscription`.
2. Click outside the payment window to dismiss.
3. The payment window dismisses

### Actual behavior
1. Invoke `requestSubscription`.
2. Click outside the payment window to dismiss.
3. The payment window dismisses
4. The payment window re-appears

**Comment by andresesfm** [comment]
This is the behavior at the system level. We are not in control of it. Once we launch the intent, the OS is the one that displays that dialog
