### ISSUE TITLE
Apple requestPurchase inconsistent with showing the popup for confirm  payment.

### ISSUE THREAD

**Issue by Mihai-github** [dooboolab/react-native-iap#1654]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
"react-native-iap": "7.2.1",
### Version of react-native
"react-native": "^0.64.1",
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Apple pop-up to pay to work every time without having to create another user into the sandbox and make all apple's validation steps to start testing again...
### Actual behavior
For unknown reasons Apple's pop-up when calling `requestPurchase` does not appear suddenly and there is no error thrown or anything I'm not sure how to debug this issue or what is the issue and creating a new email account -> register in Sandbox -> doing every verification step to start testing again is not fun...
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior

Calling this method with different productIds and testing the actual behavior having both more than 1 product/subscription (for testing purposes);
```

RNIap.requestPurchase(productId)
.then((purchase: any) => {
   console.log({purchase});
})
.catch((errorPurchase: any) => {
   console.log({errorPurchase});
});

```

**Comment by andresesfm** [comment]
The user probably already owns the product

**Comment by ahsanihsan** [comment]
Probably? Probably he owns the purchase and the issue is closed. It's still popping up in some cases and just if the purchase is consumable. The user can still end up buying the same product multiple times. How can we cater that @andresesfm

**Comment by ahsanihsan** [comment]
@andresesfm strange that you closed the issue but dont you think if a product is consumable, any user can own it multiple time (Until his/her card runs out of money). For me this popped up in iOS on versoin 7.5.6 and I had to publish this old application so i bumped it down to 5.x.x which solved this issue for me. Which ofcourse is not a good approach and I am planning to fix it in next revamp stage

**Comment by andresesfm** [comment]
@ahsanihsan I have no problem reopening it, feel free to do so but please keep in mind this is pretty old. The code has changed so much since that version.

**Comment by rebeccahsu** [comment]
Same issue with version "11.0.0"

**Comment by hasanafzal8485** [comment]
facing exactly same issue in sandbox env. Deleting the sandbox apple id from connected and rebuilding the app shows the popup only for the first time.
