### ISSUE TITLE
iOS: Uncaught Error new NativeEventEmitter requires a non-null argument

### ISSUE THREAD

**Issue by bAngerman** [dooboolab/react-native-iap#1655]
### Version of react-native-iap
8.0.5
### Version of react-native
0.66.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
No Uncaught error related to new NativeEventEmitter()

### Actual behavior
Requiring module "node_modules/react-native-iap/index.js", which threw an exception: Invariant Violation: `new NativeEventEmitter()` requires a non-null argument. I have also tried downgrading my react-native-iap version to 7.5.1 with the same result (noted in an Android related issue this issue was resolved at that version). I believe this is a new requirement of the react-native version I am using.

### Tested environment (Emulator? Real Device?)
Both emulator and real device.

### Steps to reproduce the behavior
Create react native environment using provided versions
Add `import * as RNIap from 'react-native-iap';` import
App has uncaught error.

**Comment by bAngerman** [comment]
Discovered that my debug app was compiling with `arm64` as an excluded architecture. Now that I have removed that and my debug/release builds are not excluding any architectures this issue no longer persists.

Feel free to close, or look further into fixing it for when that arch is excluded.

**Comment by andresesfm** [comment]
Thank you for the info @bAngerman
