### ISSUE TITLE
Is the way to detect that subscription is valid - not paused - not cancelled?

### ISSUE THREAD

**Issue by dguard** [dooboolab/react-native-iap#1658]
### Discussed in https://github.com/dooboolab/react-native-iap/discussions/1657

<div type='discussions-op-text'>

<sup>Originally posted by **dguard** March  2, 2022</sup>
Hey guys!

I am using `react-native-iap` and do code like that:
```
const purchases = await RNIap.getAvailablePurchases()
if (purchases && purchases.length > 0) {
  console.log('purchases[0].transactionReceipt', purchases[0].transactionReceipt)
  setReceipt(purchases[0].transactionReceipt as any)
}
```

output of a receipt like this:
```
{"autoRenewingAndroid": true, "developerPayloadAndroid": "", "isAcknowledgedAndroid": true, "obfuscatedAccountIdAndroid": "", "obfuscatedProfileIdAndroid": "", "orderId": "GPA.3399-2621-3956-29995", "packageNameAndroid": "com.capturescreen", "productId": "capturescreen_subscription_1_month", "purchaseStateAndroid": 1, "purchaseToken": "golpaeeialmaaplnaejmmegl.AO-J1OxgAO4mklW2lYqY_rjGr5LNmm7COrd2j_pVNq-euurt4A9N5S8CX-soqqPLGnmPGCMFvUlz8ZCEfRiAKcbvmPpezgo_8w", "signatureAndroid": "G7uNSvkvLiyCDjFJNIeGGUkG2SFbJbXQ4FKtysun1xxq/J8XEUMe/eO6x95E90LgYGNrZg30L2kkA958lrhQq9VyEwAuCwU4IuMpWUfxTBT13G6jHPlgVSTRDlgatl0AlRKKqlvc/F2/F+SXgfMviquA0Ha/8bI+eGF1weX6mCklncsYDpph4MSUh35sfgyaALIK0UV6J0PZoz1SORZjbWPtMWwTFdwUliRcov0+y/dTLkpeO6wpQcH3vD4y/ecgLPA6f8oWXsB9tov/vsZI2SdUNoKIuIeDjdjzKflcWb5Z5DHQDB229K5Q5q8Du/xTRoIXUf2Gl2wYBzCHIWG2iA==", "transactionDate": 1646219943407, "transactionId": "GPA.3399-2621-3956-29995", "transactionReceipt": "{\"orderId\":\"GPA.3399-2621-3956-29995\",\"packageName\":\"com.capturescreen\",\"productId\":\"capturescreen_subscription_1_month\",\"purchaseTime\":1646219943407,\"purchaseState\":0,\"purchaseToken\":\"golpaeeialmaaplnaejmmegl.AO-J1OxgAO4mklW2lYqY_rjGr5LNmm7COrd2j_pVNq-euurt4A9N5S8CX-soqqPLGnmPGCMFvUlz8ZCEfRiAKcbvmPpezgo_8w\",\"quantity\":1,\"autoRenewing\":true,\"acknowledged\":true}"}
```
and I want to know - is there a way to know that subscription is cancelled and paused?
internally receipt is not changed in any way - it is just a receipt

I found that I may get more details about subscription in this way:
https://androidpublisher.googleapis.com/androidpublisher/v3/applications/{PACKAGE_NAME}/purchases/subscriptions/{SUBSCRIPTION_ID}/tokens/{PURCHASE_TOKEN}

But it requires authentication - on client side for customer - why on client side? ... Is there other way to do same thing

Thanks,
Alex
</div>

**Comment by steven-sh** [comment]
I think that URL is supposed to be called by you on your server to validate a subscription (the authentication is your dev account, not the user's google account).

What I've found in practice on Android is that only active subscriptions are returned by getAvailabilePurchases() so I just get one entry per subscription, and I can send the purchase token to my server to validate.

iOS seems to be a bit more complicated - the StoreKit method that's called by RNIap under the hood is restoreCompletedTransactions() which returns "each previously completed transaction that can be restored".  This seems to include not only expired subscriptions, but each renewal that's occurred for every subscription.  The only useful information in the purchase objects is the SKU, transaction receipt, and the purchase date.  I can verify the transactions by using server-side verification, but that takes a couple of seconds per transaction and I can easily get up to 80 transactions returned if I've been testing for a couple of hours.

What I've taken to doing is checking the SKU and transaction date, and if the transaction is more than that subscription's renewal period (plus a buffer) in the past, treat it as invalid and only check newer purchases against the server.

I'd like to know if what I'm doing is the right way to handle it?  What I'd really like is for RNIap to expose this method from the new StoreKit API, which returns just currently active subscriptions: https://developer.apple.com/documentation/storekit/transaction/3851204-currententitlements

**Comment by andresesfm** [comment]
For Android, if the subscription is returned, it means that it's active.
For iOS the suggested way is to persist the transaction on your backend. Discussion: https://stackoverflow.com/questions/63362493/how-to-check-if-subscription-is-active-in-ios-on-app-restart-or-reinstall

**Comment by pencilcheck** [comment]
I noticed if I pause the subscription, getAvailablePurchases will be empty on the cycle that it is paused. I guess it will be the same for cancel. For Android, google only does cancellation on the next cycle, not the current cycle, so I have to wait a bit.
