### ISSUE TITLE
Compile error on Android

### ISSUE THREAD

**Issue by heks** [dooboolab/react-native-iap#1659]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
8.0.5

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
Android
### My setup

```
buildscript {
    ext {
        kotlinVersion = '1.5.20'
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 30
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

### Getting this compile error:

```
react-native-iap/android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt: (215, 37): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-iap:compilePlayDebugKotlin'.
```

**Comment by aubert-creation** [comment]
Same here

**Comment by heks** [comment]
> `npm install --save-dev jetifier` then `npx jetify` work for me

this didn't work for me jetifier is automatically run with ```react-native run-andoid```

**Comment by Akashdeep312** [comment]
hi @heks @aubert-creation please try to downgrade to "react-native-iap": "^7.5.6"

**Comment by andresesfm** [comment]
@heks Have you tried it with a more recent version of rn? I think the minimum rn version as of rn-iap 8.0.0 is `0.65.1`

**Comment by heks** [comment]
> hi @heks @aubert-creation please try to downgrade to "react-native-iap": "^7.5.6"

Downgrading worked for me. I have not tried updated react-native as that will mess up many of my other packages, but I dont think that should affect it ?

**Comment by KamranZafar19** [comment]
getting same error...Downgrading the version  to "react-native-iap": "^7.5.6" didn't work for me.

**Comment by andresesfm** [comment]
Closing as it has been merged
