### ISSUE TITLE
uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by grubstarstar** [dooboolab/react-native-iap#1661]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap

8.0.5

### Version of react-native

0.64.0

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

The app doesn't crash.

### Actual behavior

The app crashes with the following error message:

    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSInvocation _invocationWithMethodSignature:frame:]: method signature argument cannot be nil'
    
And the thread dies because of the `com.facebook.react.RNIapIosQueue`

![image](https://user-images.githubusercontent.com/1732170/158002322-e60c547a-4562-4df2-81ed-dfa46834dacb.png)

### Tested environment (Emulator? Real Device?)

Real iPhone 8 device - iOS 15.3.1

### Steps to reproduce the behavior

Upgrade from `react-native-iap@7.5.0` to `react-native-iap@8.0.5`

Run pod install successfully outputting `Installing RNIap 8.0.5 (was 7.5.0)` to the console.

I thought it might be something to do with the header bridging file, but I added a bridging file to my project and I still get this error. Is there anything specific I need to put in there? I couldn't find anything in the documentation.

**Comment by andresesfm** [comment]
@grubstarstar what does your JS code look like?
