### ISSUE TITLE
RNIap.getSubscriptions(itemSkus) is not working

### ISSUE THREAD

**Issue by GezimVeliu** [dooboolab/react-native-iap#1663]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap 
8.0.5

### Version of react-native 
0.67.3

### Platforms you faced the error (IOS or Android or both?)
Android

RNIap.getSubscriptions(itemSkus) is not working, the RNIap.initConnection() connected but not working subscriptions, I did all the steps base on documentation, but the response from getSubscriptions return empty array [], any idea?

### Tested environment (Emulator? Real Device?)
Real Devices

**Comment by romulojjunior** [comment]
Hi @GezimVeliu,

I was facing the same issue that you.
Maybe these tips will help you and other developers.

**1 - If you are publishing / enabling subscription the first time:**
- Try to use internal test channel (it will publish your app faster than close channel (alpha))

**2 - If you are using close channel (Alpha)**
-  It may take 24h to update google play server around the world.

**3 - Check your products / subscriptions ids**
- Go to Google Play console, open subscriptions and check if the ids are the same that you are trying to fetch.

**4 - Check if you are a user tester**
- Inside Internal test / closed test, you need to create a group of testers.
- Add your user (it needs to be the same that you are using in your device)
- After your app be published, look for the link to accept the tester invite ex: https://play.google.com/apps/internaltest/123456789

5 - Add your user in **License testing** 
- it allows you to use a google play sandbox to buy items and subscriptions.

If you follow these steps, I believe  you will get the subscriptions items from GooglePlay.

Good luck. :)

**Comment by andresesfm** [comment]
Thank you for the details @romulojjunior
