### ISSUE TITLE
Infinite loop in "General Terms of multimedia services which have changed"

### ISSUE THREAD

**Issue by lc3t35** [dooboolab/react-native-iap#1668]
### Tested environment : real device with app from TestFlight

On ios Testflight, start the purchase process, after typing the password of the account and having the popup allowing the purchase, there is another popup about validating "General Terms of multimedia services which have changed" with 2 buttons : Cancel and OK.
![IMG_1877](https://user-images.githubusercontent.com/921372/159178650-43642a1f-d769-4019-b8e1-e9e4d1bffa0a.PNG)

If I cancel on this popup the process is canceled.
If I click on OK, it opens another popup with "connexion impossible", and retry button (no effect), no way to indicate how to connect, only a cancel button at top of popup -> nothing happens anymore after this.
![IMG_1878](https://user-images.githubusercontent.com/921372/159178655-737131a4-886a-4036-8c05-a6a56bc21ce4.PNG)

If I quit the app, then I have suddenly the popup displayed to accept "General Terms of multimedia services Apple", with Accept button. 
![IMG_1879](https://user-images.githubusercontent.com/921372/159178671-d40c694b-48e7-43be-a313-89b3c8ffec18.PNG)

If I accept, the popup disappear and the screen doesn't display the app list on desktop, I have to click on the bottom button to display them again !
![IMG_1880](https://user-images.githubusercontent.com/921372/159178673-037d8153-aa83-4136-b8ea-cb53f4255ec5.PNG)

**Comment by MacroBet** [comment]
same issue

**Comment by MacroBet** [comment]
@lc3t35 I solved the issue upgrading the device's S.O.
Anyway is a problem related to the specific device and not to this library i suppose.

https://discussions.apple.com/thread/253556197

**Comment by ilya-raevskiy** [comment]
Helped to log in from another device and accept the agreement from there

**Comment by andresesfm** [comment]
I just merged an specialized error for this case of interrupted purchase
