### ISSUE TITLE
Registered RNIap.purchaseUpdatedListener is being called before RNIap.requestPurchase resovles.

### ISSUE THREAD

**Issue by grubstarstar** [dooboolab/react-native-iap#1670]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap

7.5.6

### Version of react-native

0.64.0

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

The promise for `RNIap.requestPurchase(productId, false)` returns before the event handler registered at `RNIap.purchaseUpdatedListener()` starts execution

I need this because I am relying on the result of the resolved promise to keep track of feature parameters that I want to associate with the transaction when the `purchaseUpdatedListener` is called.

    // When making a purchase...
    const productPurchase = await RNIap.requestPurchase(productId, false)
    saveFeatureParamForTransactionID(productPurchase.transactionId, featureParams)

    // The purchaseUpdatedListener handler.
    function(purchase: InAppPurchase | SubscriptionPurchase) {
	    const featureParams = getSavedFeatureParamsForTransactionID(purchase.transactionReceipt)
	    await saveRemotelyInBackend(purchase.transactionReceipt, featureParams)
    }

### Actual behavior

The `purchaseUpdatedListener` handler starts execution before `RNIap.requestPurchase(productId, false)` has returned meaning the `getSavedFeatureParamsForTransactionID()` function will be called before the featureParams have been saved in `saveFeatureParamForTransactionID()` meaning the feature params are not retrieved.

### Tested environment (Emulator? Real Device?)

Real Device - Pixel 3.

### Steps to reproduce the behavior

See code example above.

**Comment by andresesfm** [comment]
`requestPurchase` will return `true` if the purchase was successful but the actual purchase will be in the listener. If listener is being called earlier than the purchase execurinting. It might be that you have some pending transactions
