### ISSUE TITLE
RNIapQueue.shared as undefined in AppDelegate for promoted products in ios

### ISSUE THREAD

**Issue by rush86999** [dooboolab/react-native-iap#1676]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
8.0.0
### Version of react-native
0.67
### Platforms you faced the error (IOS or Android or both?)
ios
### Expected behavior
Able to add listener for SKPaymentQueue in AppDelegate
### Actual behavior
RNIapQueue module is not available if your create an AppDelegate.swift file with bridging header?
### Steps to reproduce the behavior
1. create new swift file with name AppDelegate.swift
2. xcode asks to create Bridging Header file and click yes
3. follow Troubleshooting instructions
```
import UIKit
import StoreKit

class AppDelegate: UIResponder, UIApplicationDelegate {
                ....
    // Attach an observer to the payment queue.
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        SKPaymentQueue.default().add(RNIapQueue.shared)
        return true
    }

    // Called when the application is about to terminate.
    func applicationWillTerminate(_ application: UIApplication) {
        // Remove the observer.
        SKPaymentQueue.default().remove(RNIapQueue.shared)
    }
                ....
}
```

RNIapQueue.shared shows as undefined and build fails

**Comment by aaggarwa88** [comment]
Hi, yes this seems to be an issue with the documentation or something not being update.  I am also trying to setup and can't figure out how to do it correctly.

**Comment by andresesfm** [comment]
@rush86999 Do you mean that `RNIapQueue` is undefined and `RNIapQueue.shared is undefined`? It's a strange error since I can see it being declared as a static method: https://github.com/dooboolab/react-native-iap/blob/main/ios/RNIapQueue.swift#L18

**Comment by alburdette619** [comment]
I'm in this position currently.  Following the docs here is very rough if you have an objective c `AppDelegate` & aren't as knowledgable outside the JS context.

<img width="1007" alt="Screen Shot 2022-07-05 at 10 11 26 AM" src="https://user-images.githubusercontent.com/22638838/177347953-83728538-ccb8-413c-8eee-b2b9a04670a2.png">

**Comment by alburdette619** [comment]
After some research, I set all of targets `Objective-C Generated Interface Header Name` to the same & attempted to use `#import <{ProductName}-Swift.h>` but the build still failed with the same error.
