### ISSUE TITLE
iOS: 'buyProductWithOffer:forUser:withOffer:resolve:reject: is not a recognized Objective-C method.'

### ISSUE THREAD

**Issue by Mkolakoglu** [dooboolab/react-native-iap#1683]
Hello, 

We are trying to use `requestPurchaseWithOfferIOS` in our app but it's throwing this error:

<img width="366" alt="Screen Shot 2022-04-27 at 15 24 58" src="https://user-images.githubusercontent.com/16003411/165528256-c5a65b9c-ffa8-4de8-ab25-ab19b461a130.png">

Here is how we are calling `requestPurchaseWithOfferIOS`:
```
RNIap.requestPurchaseWithOfferIOS(productId, userId, { identifier, keyIdentifier: keyId, nonce, signature, timestamp })
```

We are creating the signature in our server, and verified that it's correct with the method mentioned in this video at 11:52:
https://developer.apple.com/videos/play/wwdc2019/305

We also have `{projectName}-Bridging-Header` file in our app. Here is how it looks:
<img width="820" alt="Screen Shot 2022-04-27 at 15 30 53" src="https://user-images.githubusercontent.com/16003411/165530041-7f95e011-56f5-40e8-a44e-2a7f33852b30.png">

Any help would be appreciated!

### Version of react-native-iap
8.0.8
### Version of react-native
0.65.1
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
`requestPurchaseWithOfferIOS` should work without error
### Actual behavior
`requestPurchaseWithOfferIOS` is throwing `buyProductWithOffer:forUser:withOffer:resolve:reject: is not a recognized Objective-C method.` error
### Tested environment (Emulator? Real Device?)
Real device - iPhone Xs
### Steps to reproduce the behavior
Trigger a subscription by using `RNIap.requestPurchaseWithOfferIOS` API.

**Comment by Mkolakoglu** [comment]
I've tested this on the version `7.5.6` and seems to work. So, probably, the issue has appeared after migration to swift from ObjectiveC

**Comment by hyochan** [comment]
@Mkolakoglu Thanks for opening this 🙏 @andresesfm Could you kindly check this if you are available?

**Comment by Mkolakoglu** [comment]
Hi @hyochan @andresesfm,

I created a PR to fix this issue. Could you please check it and create a new version? https://github.com/dooboolab/react-native-iap/pull/1698

Thanks in advance!

**Comment by Dallas62** [comment]
Hi,
Does #1698 fix this issue ?
Regards
