### ISSUE TITLE
Recurring subscription purchase for a specific user - iOS

### ISSUE THREAD

**Issue by yasodha-r** [dooboolab/react-native-iap#1684]
### Platforms you faced the error (IOS)
Can we have a method to purchase a  recurring subscription with a user-name as described in [#485](https://github.com/dooboolab/react-native-iap/issues/485) and [#322](https://github.com/dooboolab/react-native-iap/issues/322)

**Comment by andresesfm** [comment]
Thank you for your contribution @yasodha-r
