### ISSUE TITLE
Cannot read property 'buyProduct'

### ISSUE THREAD

**Issue by andrideng** [dooboolab/react-native-iap#169]
### Version of react-native-iap
"react-native-iap": "^1.0.5",

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Can buy Product

### Actual behavior
Can't buy product. got this error.
Screen shoot: [https://ibb.co/mhzeBT](url)

### Tested environment (Emulator? Real Device?)
Emulator.

### Steps to reproduce the behavior
When click to trigger buyProduct('ProductID')

**Comment by JJMoon** [comment]
You cannot make purchase test in iOS simulator. Please use actual device. I will close this some days later for your review.

**Comment by JJMoon** [comment]
@andrideng Your screen shot link is broken. 
Did you solve the problem?

**Comment by andrideng** [comment]
yes. it solved. thanks 👍
