### ISSUE TITLE
The sku was not found. Please fetch products first by calling getItems when I requestSubscription in Android

### ISSUE THREAD

**Issue by phuocantd** [dooboolab/react-native-iap#1695]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

Not showing the payment modal when requestSubscription even though I have getSubscriptions. The package side works fine

### Version of react-native-iap
^8.0.8
### Version of react-native
0.68.0
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
open modal payment subscription when requestSubscription
### Actual behavior
not show modal payment when requestSubscription
### Tested environment (Emulator? Real Device?)
real device

**Comment by professorkolik** [comment]
Can this be a new introduction of new Subscription Management from Google?

**Comment by phuocantd** [comment]
I solve with getProduct and getSubscription
