### ISSUE TITLE
getProducts and getSubscriptions return the same data

### ISSUE THREAD

**Issue by mtnt** [dooboolab/react-native-iap#1697]
### Version of react-native-iap
8.0.8

### Version of react-native
0.68.1

### Platforms you faced the error (IOS or Android or both?)
iOS (15.4) (did not check android yet)

### Expected behavior
`getProducts` and `getSubscriptions` return separate lists of products and subscriptions

### Actual behavior
both methods return products and subscriptions according to productsIds passed into parameters

### Tested environment (Emulator? Real Device?)
Device (iPhone X)

### Steps to reproduce the behavior
```
await RNIap.initConnection()
this.purchaseUpdateSubscription = RNIap.purchaseUpdatedListener(() => {})
await RNIap.clearProductsIOS();

const products = await RNIap.getSubscriptions(['subscriptionId', 'concumableId']);
or 
const products = await RNIap.getProducts(['subscriptionId', 'concumableId']);
```

**Comment by andresesfm** [comment]
We could filter them using https://developer.apple.com/documentation/storekit/skproduct/2936884-subscriptionperiod

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1760
