### ISSUE TITLE
getSubscriptions not returning offers from new Google play api

### ISSUE THREAD

**Issue by RafSafeSocial** [dooboolab/react-native-iap#1699]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.
Hi everyone. 
There is a problem with getting offers for base plans which were set after new changes to Google play api. 
Shape of products with offers changed , so right now only base plans are returned while calling 
```
const {getSubscriptions} = useIAP()
getSubscriptions(skus); 
```
All base plans are active , offers as well.
Probably due change of api some amendments should be made in android code base.

### Version of react-native-iap 
8.0.1

### Version of react-native
0.66.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
useIAP hook should return subscriptions with offers

### Actual behavior
Receiving only base plan from subscription

### Tested environment (Emulator? Real Device?)
Both

### Steps to reproduce the behavior
invoke getSubscriptions() after initialisation for getting subscriptions with offers. Only base plans are returned.

**Comment by pi0trpietruszewski** [comment]
☝️  Is there plan to support Billing Library 5?

**Comment by seanDeCoder** [comment]
Did you test using a licensed tester?

**Comment by RafSafeSocial** [comment]
Yes ... Licensed tester is configured. New Subscriptions plans are returned , no new api offers returned.

**Comment by Vuconghieu2022** [comment]
Play console has been updated:
--> "Recent changes to subscriptions in Play Console" (https://support.google.com/googleplay/android-developer/answer/12124625)

**Comment by SimonDamberg** [comment]
I am also only getting one base plan per subscription, not able to get my other plan. The one that is returned is the one I select to be backwards-compatible.

**Comment by Tharinducn** [comment]
After adding the offer with two phases (Single payment and Free trial) and selecting "Use for deprecating billing methods" I received the offer. 

<img width="299" alt="1" src="https://user-images.githubusercontent.com/35630380/171783422-857456f2-49fa-4b24-a44f-e8f1a9cf0908.png">

<img width="431" alt="2" src="https://user-images.githubusercontent.com/35630380/171785113-97be0f6d-bf91-463a-8d48-a7889d142f69.png">

But it can only be applied for a single offer in a Base plan at the moment

**Comment by SimonDamberg** [comment]
@Tharinducn I have one baseplan with a montly subscription and an attached offer of a free trial for two weeks. When I call `requestSubscription(sku)`, the free trial does not show up in the dialog.

**Comment by Desintegrator** [comment]
same

**Comment by yisselda** [comment]
Any more information about how to get all the plans currently?

**Comment by dannyeddyy** [comment]
**For anyone who finds this thread because they do not see offers they have added**: it seems to be taking between 12-24 hours for Google to make the offers available in our `getSubscriptions()` response.

**Comment by andresesfm** [comment]
Implemented here: https://github.com/dooboolab/react-native-iap/pull/1762

**Comment by andresesfm** [comment]
Created release 9.0.0-beta. Please create tickets against that if you find any issues

**Comment by zeeshan-shabbir** [comment]
> **For anyone who finds this thread because they do not see offers they have added**: it seems to be taking between 12-24 hours for Google to make the offers available in our `getSubscriptions()` response.

didnt see offer i added yet its more than 48 hours
