### ISSUE TITLE
getProducts: Empty product array 

### ISSUE THREAD

**Issue by guzza82** [dooboolab/react-native-iap#170]
### Version of react-native-iap
the lastest version for now

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Read and buy product

### Actual behavior
After RNiap.prepare, I invoke the getProducts method on a static array of bundle ids associated with products already loaded and approved on iTunesConnect. The response is empty array, What could be the problem?

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by cliff** [comment]
I had the same problem and I checked all the steps multiple times, in the end this fixed my problem: 

1. Use only the ProductID not the BundleID + ProductID for SKUs (instead of "com.example.myapp.product1" use just "product1")
2. I had to submit the app and then "developer reject" it right after.

**Comment by younes200** [comment]
Same here for me, bot ProductID and BundleID+ProductID not working at least for iOS, not tested yet on android.
@cliff what do mean by "developer reject" it right after ? you app didn't get validated because of that ?

**Comment by JJMoon** [comment]
@younes200 'Developer reject' means you apply app (product) review (to Apple company in iTunesConnect) and reject it before the review. But, it is not necessary. I test without this process.
I guess you should check the IDs on iTunesConnect and strings in JS array.

**Comment by lc3t35** [comment]
@younes200  @guzza82 did you solve this issue ?

**Comment by dawidvdh** [comment]
Having the exact same issue, even having a in app purchase Product ID being: `com.product.product.allitems` and just using `allitems` for the sku did also not work.

**Comment by lc3t35** [comment]
I've closed this issue https://github.com/dooboolab/react-native-iap/issues/198 that can give you some steps to success ;)

**Comment by dawidvdh** [comment]
Thanks @JJMoon realised that I was doing something dumb elsewhere (hadn't set u all the tax info on itunesconnect), all works on my end thats for the help.

**Comment by younes200** [comment]
Thanks @JJMoon.  it seems that contact info was misssing, I'll re-check that after the Apple finish processing my infos.
