### ISSUE TITLE
How to send external data with requestSubscription on iOS

### ISSUE THREAD

**Issue by elinahovakimyan** [dooboolab/react-native-iap#1701]
### Version of react-native-iap

7.5.0

### Version of react-native

0.67.3

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Hello. We need to send some external user data with iOS subscription as the app user can have a different email, etc. For Android, we use `obfuscatedAccountIdAndroid` and `obfuscatedProfileIdAndroid` in the `requestSubscription` method. What can we use for iOS? 

Thanks!

**Comment by Wanes-Tutunjian** [comment]
@elinahovakimyan please check out this comment on a similar issue, i think it would be useful to your case  https://github.com/dooboolab/react-native-iap/issues/1576#issuecomment-1084989032 

You will have to patch the package to keep the changes, and you will be limited to only using UUID's in the given applicationUsername field; however you could assign users UUIDs and use them on your server to identify them if you don't already use them

**Comment by andresesfm** [comment]
`requestPurchase` now supports `applicationUsername`

**Comment by andresesfm** [comment]
It's there: `appAccountToken`
