### ISSUE TITLE
[iOS] getSubscriptions and getProducts return empty discounts

### ISSUE THREAD

**Issue by yaroslavnikiforov** [dooboolab/react-native-iap#1702]
### Version of react-native-iap
8.0.9

### Version of react-native
0.67.1

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
`getSubscriptions` should return not empty discounts array if a subscription has promotional offers.

### Actual behavior
`getSubscriptions` stopped returning newly added to the subscription promotional offers.

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Add a new promotional offer to the subscription and call `getSubscriptions` or `getProducts`. The `discounts` array will not include the new offer. It used to work and these methods return promotional offers that were added some time ago. If you delete some of the old offers, `discounts` will be updated and they also will not be returned. But any of the new offers are not included. 

Some breaking changes in StoreKit?

**Comment by CodingByJerez** [comment]
I have the same problem

**Comment by jkfurog** [comment]
I am also getting empty discounts issue

**Comment by Mandoliiin** [comment]
I also have this issue and it is very critical to have it resolved as soon as possible since we can't make any updates to the subscriptions right now. Hope there will be a solution soon!

**Comment by Desintegrator** [comment]
same

**Comment by andresesfm** [comment]
This is the only condition I see that would prevent discounts from being populated: https://github.com/dooboolab/react-native-iap/blob/main/ios/RNIapIos.swift#L766 . Is that the case for you?

**Comment by Skarabei007** [comment]
https://github.com/dooboolab/react-native-iap/pull/1769

**Comment by andresesfm** [comment]
Closing, please reopen if it's still an issue on latest

**Comment by Rohit-vinfotech** [comment]
Not getting products for IOS after Testflight upload , but working when I debug (run) locally on physical device. I want to validate receipt

I tried below methods
1.    const itemData= await getIosModule().getItems(constants.productSkus)
        alert("itemData ==>" + JSON.stringify(itemData))

2.    const product= await getProducts({ skus: constants.productSkus });   // by hook useIAP()
               alert("product=> "+JSON.stringify(product))

3.    const product= await IAP.getProducts({ skus: constants.productSkus });
               alert("product=> "+JSON.stringify(product))
