### ISSUE TITLE
How to implement changes in the user subscription plan (downgrade or upgrade) or cancel the subscription

### ISSUE THREAD

**Issue by fergalindez** [dooboolab/react-native-iap#171]
### Version of react-native-iap
1.0.5
### Platforms you faced the error (IOS or Android or both?)
Both

**Comment by JJMoon** [comment]
In iOS you can cancel subscription in `setting` app.

**Comment by dooboolab** [comment]
For android, users can view the status of all of their subscriptions and cancel them if necessary from the app's screen in the Play Store app. Currently, the In-app Billing API does not provide support for programmatically canceling subscriptions from inside the purchasing app.

**Comment by fergalindez** [comment]
thanks a lot @JJMoon @dooboolab

**Comment by vshab** [comment]
@dooboolab I think there is a method to upgrade or downgrade subscriptions on Android: https://developer.android.com/google/play/billing/billing_subscriptions#Allow-upgrade

>However, when upgrading or downgrading, you pass the product IDs for the current subscription and the future (upgraded or downgraded) subscription to the BillingFlowParams object using the addOldSku() method.

Do you think we can have this? :)
