### ISSUE TITLE
[iOS] getSubscriptions not returning introductory offers in the IOS production app

### ISSUE THREAD

**Issue by Tharinducn** [dooboolab/react-native-iap#1711]
### Version of react-native-iap

7.5.6 

### Version of react-native

0.63.4

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

React Native IAP should return the available introductory offers in both production and sandbox environment

### Actual behavior

React Native IAP only returns the available introductory offers in the sandbox environment

### Tested environment (Emulator? Real Device?)

Real Device

### Steps to reproduce the behavior

1. Add an active introductory offer to a subscription
2. Check introductory offer is returned in the sandbox environment
3. Check introductory offer is returned in the production environment

**Comment by andresesfm** [comment]
@Tharinducn can you clarify why you expect that behavior? Do you have a link to the native documentation that supports this expectation?

**Comment by Tharinducn** [comment]
@andresesfm this worked on both staging and production in the same way previously. But after adding an introductory offer to the App Store Connect yesterday I'm getting the introductory offer only in the staging environment now. 

Found a similar issue [here](https://developer.apple.com/forums/thread/706677).

**Comment by Tharinducn** [comment]
I received the offer. It took more than a day to receive it after creating the offer. Seems like an issue from App Store Connect side
