### ISSUE TITLE
Suscription getSubscription getting empty array also requestSubscription not return anything

### ISSUE THREAD

**Issue by Ravi2501** [dooboolab/react-native-iap#1712]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap

8.0.10

### Version of react-native

0.66.4

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

React native IAP return empty array 

### Actual behavior

React native IAP test purchased working fine but problem with subscription product

### Tested environment (Emulator? Real Device?)

Real Device

### Steps to reproduce the behavior
1. follow all step for upload app in internal testing
2. Add tester in license testing

**Comment by andresesfm** [comment]
@Ravi2501  What is being returned instead of the empty list?

**Comment by Ravi2501** [comment]
Now its working with auto renewal product but what about prepaid??

**Comment by andresesfm** [comment]
Glad to hear it's working. For prapaid use prorationMode = `IMMEDIATE_AND_CHARGE_FULL_PRICE` as per native documentation: https://developer.android.com/google/play/billing/subscriptions#prepaid-plans feel free to re-open or create a separate issue for that
