### ISSUE TITLE
Product in getProducts() returns correct currency but incorrect price (iOS only)

### ISSUE THREAD

**Issue by FabianTauriello** [dooboolab/react-native-iap#1713]
### Version of react-native-iap

4.6.3

### Version of react-native

0.62.2

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

The product should return the correct currency and associated price.

### Actual behavior

When testing my in-app purchase, the product that's returned includes the correct currency (GBP) but the incorrect price.

### Tested environment (Emulator? Real Device?)

Real device

### Steps to reproduce the behavior

1. Create an in-app purchase on App Store connect 
2. Test the app on a real device, with a UK-based sandbox account.

I'm testing an in-app purchase for our app but the price I get back from the app store is incorrect. I'm based in the UK and the phone I'm testing our app on is using a UK Apple Id but the price for the product seems to return the US price instead of the GBP price. Here is the object I get back from getProducts() - note, some props are not included here:

   {
      "introductoryPrice":"",
      "introductoryPriceSubscriptionPeriodIOS":"",
      "introductoryPriceNumberOfPeriodsIOS":"",
      "discounts":[],
      "localizedPrice":"£11.99",
      "introductoryPricePaymentModeIOS":"",
      "price":"11.99",                                                        
      "currency":"GBP",                                                   
      "subscriptionPeriodNumberIOS":"0" 
   }

But in our app store connect page:

<img width="1249" alt="Screenshot 2022-06-06 at 14 10 25" src="https://user-images.githubusercontent.com/25223061/172167602-ccc27614-d929-4bf1-92ff-45fd8836d384.png">

So, `localizedPrice` should be £9.99 and `price` should be 9.99. I'm having this problem on IOS only.

**Comment by andresesfm** [comment]
@FabianTauriello I would advise you to update the library. It's probably been fixed since the version you are using is pretty dated. Reopen if issue persists

**Comment by ajdobson** [comment]
Afternoon @FabianTauriello can you confirm how you fixed this? Am getting the same error? What version did you upgrade to? I dont really want to have to upgrade my react native version etc. Let me know

**Comment by FabianTauriello** [comment]
Hi ajdobson. I updated the library to the latest version but that didn't fix my issue. Strangely, if I use a sandbox account from a different region (e.g. Australia), the correct value is returned so it seems to be an issue with the GBP price locale only. Though it's probably an issue with Apple and not this library.

**Comment by AdamGerthel** [comment]
I've had the same problem. Even Apple's own reviewers noticed and complained about it, but I told them it had to be an error on their end and they let it go.
