### ISSUE TITLE
Unable to cancel subscription from settings

### ISSUE THREAD

**Issue by karel-suchomel-uhk** [dooboolab/react-native-iap#1715]
This is more of a question, I don't know if it is related to this package, but I haven't found anything. Everything works fine, I can successfully purchase the subscription, receive a receipt and validate it, but I cannot cancel it from the settings.
Any help or feedback would be appreciated.

### Version of react-native-iap
8.0.10
### Version of react-native
0.66.0
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Purchased auto-renewable subscription should show in in Subscriptions Settings
### Actual behavior
Purchased subscription not showing up in the Setting, therefore the user is unable to cancel the subscription and the subscription is automatically getting renewed
### Tested environment (Emulator? Real Device?)
Real Device

**Comment by andresesfm** [comment]
All I can think about is that maybe the sku you are purchasing is not a subscription after all. I'm closing this since the actual subscription is handled by the OS/Apple, and as such this is better suited for stackoverflow
