### ISSUE TITLE
bundleRelease error on jitsi-meet project

### ISSUE THREAD

**Issue by vovBorya** [dooboolab/react-native-iap#1716]
Our project cloned from [jitsi-meet](https://github.com/jitsi/jitsi-meet) . I'm trying install for Android your package manually using this guide https://react-native-iap.dooboolab.com/docs/manual_install/ . For [jitsi-meet](https://github.com/jitsi/jitsi-meet) repository there are [some different places](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile-jitsi-meet/#adding-extra-dependencies) where lines have to be inserted. When I installed manually following both guides, my project doesn't launch. 

For example, I got this error (screenshot) 
<img width="1644" alt="Screenshot 2022-06-07 at 2 30 40 pm" src="https://user-images.githubusercontent.com/49486301/172369087-ed0d1f64-bb05-4aba-80a8-d47eb49d86c0.png">

when I run `./gradlew bundleRelease` in android folder. As I understand something with this string `missingDimensionStrategy 'store', 'play'` ( from [this guide](https://react-native-iap.dooboolab.com/docs/manual_install/)).

The [jitsi-meet](https://github.com/jitsi/jitsi-meet) repo has 3 possible places with android `defaultConfig {}`
1. `android/sdk/build.gradle`
2. `android/app/build.gradle`
3. `twa/app/build.gradle`

Actually, for [jitsi-meet](https://github.com/jitsi/jitsi-meet) we need install packages in this file `android/sdk/build.gradle`
But my error appears for all 3 places where a tried to past this line `missingDimensionStrategy 'store', 'play'`

### Version of react-native-iap
`"react-native-iap": "^8.0.10"`

### Version of react-native
`"react-native": "0.67.4"`

### Platforms you faced the error (IOS or Android or both?)
`Android`

### Expected behavior
Build finished success 
after`./gradlew bundleRelease` and ` react-native run-android` commands

### Actual behavior
There is the error (screenshot above)

### Tested environment (Emulator? Real Device?)
Both

**Comment by andresesfm** [comment]
@vovBorya By the looks of the error you posted, the build process is not finding the rn-iap itself. please make sure the path is correct when added to settings.gradle. I'll close as this is better suited for stackoverflow. I hope this helps
