### ISSUE TITLE
[Android] Return storeReceipt.data in getAvailablePurchases

### ISSUE THREAD

**Issue by kristfal** [dooboolab/react-native-iap#172]
### Version of react-native-iap

Latest

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Calling `getAvailablePurchases` should return the full purchase object, similar to the purchase object returned during a purchase, eg:

```
autoRenewing: {Boolean},
productId: {String},
purchaseToken: {String},
transactionDate: {String},
transactionId: {String},
transactionReceipt: {String},
signature: {String},
data: {String},
```

### Actual behavior

Right now, data is omitted. The result is an array of:

```
autoRenewing: {Boolean},
productId: {String},
purchaseToken: {String},
transactionDate: {String},
transactionId: {String},
transactionReceipt: {String},
```

### Tested environment (Emulator? Real Device?)

Real device

### Steps to reproduce the behavior

Call `getAvailablePurchases` on an Android device.

### Proposed implementation

[This seems to be the best practice](https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L273-L300).

**Comment by kristfal** [comment]
Looking at the code, you seem to return data in `getPurchaseHistory`, however that method fails with:

```
code: "E_UNKNOWN"
framesToPop: 1
message: "An unknown or unexpected error has occured. Please try again later."
```

Any advise on how to move forward?

**Comment by dooboolab** [comment]
@kristfal Will this help? I will update npm for your [PR](https://github.com/dooboolab/react-native-iap/pull/173).

**Comment by kristfal** [comment]
Thanks for the merge. Yes, that resolves my issues. Keep in mind that I was still unable to make `getPurchaseHistory` work, but I don't need it for my use case now that `getAvailablePurchases` returns all fields. Closing for now.
