### ISSUE TITLE
CI for iOS

### ISSUE THREAD

**Issue by axdra** [dooboolab/react-native-iap#1723]
There should be CI workflow for iOS for pull requests and release.

#1722

**Comment by andresesfm** [comment]
Thank you for your suggestion @axdra. I agree we should have it. Any interest in helping with a PR?

**Comment by axdra** [comment]
I've began looking into it but just at the moment I don't have the time to do it. But for sure I'm interested in helping.

**Comment by andresesfm** [comment]
https://github.com/dooboolab/react-native-iap/pull/1752
