### ISSUE TITLE
Not getting any result in purchaseUpdatedListener

### ISSUE THREAD

**Issue by shashank-shinde** [dooboolab/react-native-iap#1725]
### Version of react-native-iap: 
8.1.1

### Version of react-native: 
0.67.4

### Platforms you faced the error (IOS or Android or both?): 
iOS

### Code snippet 

  ```
useEffect(() => {
    let purchaseUpdateSubscription;
    let purchaseErrorSubscription;
    RNIap.initConnection()
      .then((connected) => {
        purchaseUpdateSubscription = purchaseUpdatedListener((purchase) => {
          console.log('purchaseUpdatedListener', purchase);
          const receipt = purchase.transactionReceipt;
          console.log('receipt', receipt);
        });

        purchaseErrorSubscription = purchaseErrorListener((error) => {
          console.log('purchaseErrorListener', error);
        });
      })
      .catch((e) => {
        console.log(e);
      });
    return () => {
      if (purchaseUpdateSubscription) {
        purchaseUpdateSubscription.remove();
      }
      if (purchaseErrorSubscription) {
        purchaseErrorSubscription.remove();
      }
    };
  }, []);
```

### Expected behavior
Whenever we make a purchase, `purchaseUpdatedListener` should return a response of the type `InAppPurchase | SubscriptionPurchase | ProductPurchase`. 

### Actual behavior
Always getting undefined in `purchaseUpdatedListener`. I have configured the store kit configuration file. 
`purchaseErrorListener` does work fine. I have tried with useIap() hook also but getting the same undefined in  `purchaseUpdatedListener`

### Tested environment (Emulator? Real Device?): 
Emulator

**Comment by harshsanghani** [comment]
+1

**Comment by andresesfm** [comment]
@shashank-shinde do you mean that the listener never gets called or that the purchase you get is undefined?

**Comment by Abdelalim-dev** [comment]
@andresesfm what was the fix for this issue?

**Comment by andresesfm** [comment]
Not able to reproduce in the latest version and no response from reporter. Closed as stale

**Comment by Abdelalim-dev** [comment]
I have reproduced it. How can I help you figure it out?
In my case, the listener is called but the purchase is undefined.
I am testing with StoreKit on a simulator running iOS 15.5

**Comment by andresesfm** [comment]
In that case, you can start by creating a new issue using the new template. Please include as much information as you can.

**Comment by jorgerojas26** [comment]
I'm having exactly the same issue.

I'm using Simulator, IPhone 12 Pro, IOS 15.4.

I have a local Storekit config file.

- The getSubscriptions() function works as expected
- The requestSubscription() works as respected showing the UI with the "Subscribe" Button
- When i press Subscribe, the subscription is bought correctly
- The purchaseUpdateListener gets undefined
