### ISSUE TITLE
Subscription not returning after changing App Store Connect account + Bundle ID

### ISSUE THREAD

**Issue by garrett-gottlieb** [dooboolab/react-native-iap#1728]
After switching to a new App Store Connect account and Bundle ID, my new subscription (which is "Available" on App Store Connect) is not being returned from `getSubscriptions()`. The Product ID is `unlimited_monthly` on App Store Connect, and so I'm using `getSubscriptions(['unlimited_monthly'])`. Why isn't this working anymore?

### Version of react-native-iap
7.5.4

### Version of react-native
0.64.3

### Platforms you faced the error (IOS or Android or both?)
iOS/

### Expected behavior
`getSubscriptions` loads the subscription

### Actual behavior
`subscriptions` is empty

### Tested environment (Emulator? Real Device?)
Real device, running from XCode to iPhone 13 Pro

### Steps to reproduce the behavior
1. Create subscription
2. Call `getSubscriptions`
3. Notice nothing in `subscriptions`

**Comment by Desintegrator** [comment]
same (android and ios)
android - can not get subscriptions but can get products

**Comment by Skarabei007** [comment]
https://github.com/dooboolab/react-native-iap/pull/1769
