### ISSUE TITLE
unable to purchase same item twice or multiple time in android

### ISSUE THREAD

**Issue by sandeep14** [dooboolab/react-native-iap#1732]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
8.0.8

### Version of react-native
0.67

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
allow to purchase same item multiple times

### Actual behavior
not allowing to purchase it twice, it shown you already bought this item

### Tested environment (Emulator? Real Device?)
RealDevice

### Steps to reproduce the behavior
Just try to purchase same item in any android phone

**Comment by andresesfm** [comment]
What type of product? for example, subscriptions would not allow you to repurchase. Seems more suitable for stackoverflow

**Comment by sandeep14** [comment]
I am talking about consumable product in android. not about subscription.

**Comment by jokernomade** [comment]
The documentation isn't clear. To make it work I had to do
`finishTransaction({purchase: purchase, isConsumable:true})` and not `finishTransaction(purchase, true)`

**Comment by andresesfm** [comment]
Fixed documentation here: https://github.com/dooboolab/react-native-iap/pull/2035
