### ISSUE TITLE
purchaseUpdatedListener not getting called for subscription renewals if i keep the app in foreground

### ISSUE THREAD

**Issue by javier2409** [dooboolab/react-native-iap#1737]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
8.2.1
### Version of react-native
0.66.2
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
1.  User purchases a monthly subscription
2. Listener gets called
3. App sends the purchase to my backend to unlock content for the user until the expiration date
4. App calls finishTransaction
5. Wait 5 minutes for renewal
6. Listener gets called again with new purchase (renewal)
7. Repeat from step 3
### Actual behavior
1.  User purchases a monthly subscription
2. Listener gets called
3. App sends the purchase to my backend to unlock content for the user until the expiration date
4. App calls finishTransaction
5. Wait 5 minutes for renewal
6. Nothing happens even after 10 or 15 minutes
7. Send the app to background or restart
8. Send the app to foreground
9. Listener gets called with new purchase (renewal)
10. Repeat from step 3

The thing is that I can probably assume that in production users will send the app to background at least once between the moment apple renews the subscription and the current subscription expiration because the time is longer. But I'd rather have everything working right in sandbox mode before releasing to production.

### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior

This is the code i'm using, it is a simple useIAP hook that is called in ```<App/>```, which initializes the connection and sets up the listener when mounted. The listener does what I mentioned before, constructing the subscription object in the format that my backend accepts using the information provided by the listener argument and then calls the respective endpoint to store the subscription and unlock the premium content.
```javascript
export const useIAP = ({setIAPError}: IAPConfig) => {
  const dispatch = useServiceCall()

  const [connected, setConnected] = useState(false);

  const purchaseListener = async (purchase:  IAP.SubscriptionPurchase | IAP.InAppPurchase) => {
    console.log('Purchase received');
    if (purchase.isAcknowledgedAndroid) return;

    console.log('Successfully purchased', purchase.productId)

    const subscription: SentSubscription | undefined = getPlatformSpecificSubscription(purchase)

    if (!subscription) return;

    if (purchase.purchaseStateAndroid == null || purchase.purchaseStateAndroid === IAP.PurchaseStateAndroid.PURCHASED) {
      dispatch(addSubscription(subscription))
        .then(async (res) => {
          if (isRight(res)) {
            await finishTransaction(purchase, 'Finished successful transaction');
            if (isOnScreen(ScreenId.GoPremium)) {
              navigate(ScreenId.SubscriptionSuccess);
            }
          } else {
            const store = Platform.select({ios: 'App Store', android: 'Play Store'})
            setIAPError(`Error processing purchase, please check your subscription in your ${store} account.`)
          }
        })
    } else {
      await finishTransaction(purchase, 'Finished failed transaction');
    }
  }

  const purchaseErrorListener = (error: IAP.PurchaseError) => {
    setIAPError(`There was an error with the purchase with code ${error.code}: ${error.message}`)
    console.log(`Purchase error: ${error.debugMessage}`);
  };

  useEffect(() => {
    console.log('Trying to connect to IAP store.')
    let subscription: EmitterSubscription;
    let subscriptionError: EmitterSubscription;
    IAP.initConnection()
      .then(() => {
        setConnected(true)
        console.log('Listening to IAP updates')
        subscription = IAP.purchaseUpdatedListener(purchaseListener)
        subscriptionError = IAP.purchaseErrorListener(purchaseErrorListener)
      })
      .catch(e => {
        console.log('Error connecting to IAP store:', e)
      })
    return () => {
      console.log('IAP provider unmounted')
      subscription.remove()
      subscriptionError.remove()
      IAP.endConnection().catch(reason => {
        console.log('Error ending connection:', reason)
      })
    }
  }, [])

  return connected;
};
```

**Comment by andresesfm** [comment]
Can you please clarify if `Wait 5 minutes for renewal` if this is waiting for the Apple store or your own server? I ask because if you called finish transaction, what would we be waiting for at that point? And if this gets resolved by putting the app in the background and restarting it. I way to debug would be by calling end connection after the 5 min and `initConnection` again

**Comment by javier2409** [comment]
`Wait 5 minutes for renewal` means waiting for the apple store to renew the monthly subscription, which is 5 minutes in sandbox mode. And yes, I called finished transaction but isn't the renewal a new transaction that needs to be finished with finishTransaction? Maybe I am wrong but at least that's what I'm understanding from what 's happening, because the listener is being called with the new transaction (the renewal) at some point (after I send the app to background and to foreground again). And also, everything seems to work fine after that, the recept is sent from the app to my backend and the verification using apple's endpoint succeeds, giving me the new transaction info with an expiration date 5 minutes later than the previous one as expected.
Also, I will try what you suggested about calling endConnection and initConnection again.

**Comment by andresesfm** [comment]
Let me know if this helps: https://developer.apple.com/forums/thread/74556
