### ISSUE TITLE
Getting  TypeError: null is not an object (evaluating 'getNativeModule().initConnection')

### ISSUE THREAD

**Issue by luco** [dooboolab/react-native-iap#1738]
### Version of react-native-iap
8.2.1 (also tried with 7.5.3)

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Actual behavior
Getting `TypeError: null is not an object (evaluating 'getNativeModule().initConnection')`

![image](https://user-images.githubusercontent.com/246373/177206766-f876bd3d-6f29-4f20-b372-244dd6b3e750.png)

### Tested environment (Emulator? Real Device?)
Emulator

**Comment by andresesfm** [comment]
When the native module is undefined, it means that you are not linking (or auto-linking is failing) for the native module.

**Comment by andresesfm** [comment]
feel free to reopen if you still think this is an issue with this library. Otherwise, I'd suggest posting on stackoverflow

**Comment by luco** [comment]
I think it's something to do with this library since every module I installed autolinked properly. It's only IAP on Android.
I also tried manually linking and had no success.
