### ISSUE TITLE
In app purchase in expo 

### ISSUE THREAD

**Issue by Swyanmitra** [dooboolab/react-native-iap#174]
Hello,

We are using Expo to create our project. In our project one important topic is in-app purchase. Could you help me
how to implement in-app purchase using expo and what are necessary steps we need to follow to implement this.

**Comment by EvanBacon** [comment]
Simply:
* create a new branch `detached`
* run `exp detach`
* do all the same stuff you would normally do
* switch back to `master` to add js code
* when coding in `master` wrap your IAP module code with the following:
```js
import { NativeModules } from 'react-native';
const { RNIapModule } = NativeModules;
function hasIAP() {
  return !!NativeModules.RNIapModule;
}
```
* This way your code won't crash when calling IAP methods
* When deploying or testing IAP use the detached branch - or just skip the branches altogether and go rogue >:)

The general idea here being `exp detach` just surfaces a `/ios` & `/android` folder so you can use your project as a RN app. 
You will still get all the functionality of a regular Expo app, just use fastlane to deploy so you don't need to use too much native stuff.
Finally, the branches are useful for updating SDK versions. If you for some reason have a problem updating, you could just detach again and add this lib once more.

**Comment by KevinColemanInc** [comment]
@ImArtur 

At least for me, Expo development environment is much easier to work with than having to create native builds.  Also, having a free multi-platform push notification service with a singular interface is also super convenient.

**Comment by dooboolab** [comment]
@KevinColemanInc Yes. I understand because I've been heavy expo user earlier. I really want expo to integrate the `iap` module however I understand it isn't easy for expo to maintain it's environment including `iap` feature. Apple will reject `Expo Client` app in app store firstly.

**Comment by KevinColemanInc** [comment]
@dooboolab 

Heck, as others have proposed, I'd be cool if it was just stubbed out for testing.  I just like expo for the dev experience.

I am considering breaking it out into its own branch in git and keep the dev branch expo friendly.  Once its time for deployment, I could merge in the ejected code, test it, and them deploy the app.

**Comment by EvanBacon** [comment]
@ImArtur the question is "In app purchase in expo". You can read about the pros and cons of Expo here: https://docs.expo.io/versions/latest/introduction/why-not-expo

**Comment by cellis** [comment]
Hello and thanks for creating this library! I'm wondering if ( after detaching ) you're supposed to continue to build with exp, or with xcode, in the "detached" branch? Thanks!

**Comment by edoantonioco** [comment]
If I know I will need in-app purchases at some point of the development, should I still use CRNA? or go directly to RN native from the start?

**Comment by cellis** [comment]
@edoantonico I’ve gotten this working with expo. I just make a page with iap buttons for purchasing items and only press those buttons when I’m testing purchases. Otherwise I build with expo. Works great!

**Comment by EvanBacon** [comment]
Sorry for the delay. When you detach, you add native code and build it onto your device. You then use that build like the expo client (except only for your singular app). I would still recommend sticking with Expo. CRNA is maintained by Expo and our focus is mostly on making the libraries work in that environment. Vanilla React Native will require a lot of unneeded setup and will require that you know a lot more about the inner workings of modules.

**Comment by inglesuniversal** [comment]
Hello, now that you bring up the subject. If in app purchases is kind of "hard" to handle by Expo. What are the suggested roadmaps to monetize an App without detaching it from Expo, since for me, like many others, I make use of Expo for the fact that the overall experience is much friendlier than RN and far less complex than going native on both platforms. So, can you just use a subscription plan with PayPal or receive payments through credit cards? Is that allowed by Google and Apple to be built in, inside your Expo App by using a web view for example? Thanks.

**Comment by KevinColemanInc** [comment]
@inglesuniversal 

If its worth anything, we ended up dumping expo because we got tired of waiting for issues like this to be resolved.

It definitely adds friction to testing and to supporting some features (like notifications), but at least my dev can stop telling me, "that is impossible because expo doesn't support it".

**Comment by hyochan** [comment]
Expo has announced [this](https://blog.expo.io/expokit-2019-1e5cb02106f8) recently about the future plan in 2019. You will be able to link `native modules` then.

**Comment by TheInternet** [comment]
I have been trying to make @EvanBacon's code above work but my NativeModules is empty and as a result RNIapModule is undefined.  (on iOS at least)

Have others encountered this issue?  Does this mean I am not correctly linked?

FWIW, react-native link appears to have worked but I suspect I may need to link manually which thus far I haven't been able to do.
`$ react-native link react-native-iap
rnpm-install info Linking react-native-iap ios dependency 
rnpm-install info Platform 'ios' module react-native-iap has been successfully linked 
rnpm-install info Linking react-native-iap android dependency 
rnpm-install info Platform 'android' module react-native-iap has been successfully linked `

**Comment by Coinizy1** [comment]
@cellis  can you tell me more how you made the inapp work i am trying for 1 week now can you show the code please?
thanks
and did you build with expo or xcode after pod install?
thanks

**Comment by Coinizy1** [comment]
do all the same stuff you would normally do
switch back to master to add js code
when coding in master wrap your IAP module code with the following:
@EvanBacon  what is the meaning of above lines?

**Comment by MartinMasek** [comment]
> Simply:
> 
> * create a new branch `detached`
> * run `exp detach`
> * do all the same stuff you would normally do
> * switch back to `master` to add js code
> * when coding in `master` wrap your IAP module code with the following:
> 
> ```js
> import { NativeModules } from 'react-native';
> const { RNIapModule } = NativeModules;
> function hasIAP() {
>   return !!NativeModules.RNIapModule;
> }
> ```
> 
> * This way your code won't crash when calling IAP methods
> * When deploying or testing IAP use the detached branch - or just skip the branches altogether and go rogue >:)
> 
> The general idea here being `exp detach` just surfaces a `/ios` & `/android` folder so you can use your project as a RN app.
> You will still get all the functionality of a regular Expo app, just use fastlane to deploy so you don't need to use too much native stuff.
> Finally, the branches are useful for updating SDK versions. If you for some reason have a problem updating, you could just detach again and add this lib once more.

Hi Evan,
thank you for the suggestion. I've followed the advice and I have no errors (I've linked react-native-iap manually). However, the hasIAP function is returning false even though RNIap.initConnection(); returns true. I test it with this simple piece of code.
`async componentDidMount() {
    try {
      const result = await RNIap.initConnection();
      console.log("hasIAP " + hasIAP())
      console.log('result', result);
    } catch (err) {
      console.warn(err.code, err.message);
    }
  }`

Do you know what could be the issue? (Or anyone reading this)

**Comment by withinboredom** [comment]
According to the docs, https://docs.expo.io/versions/v32.0.0/sdk/payments/, have you set up payments on your device? (simulator wouldn't make sense to test this with)

**Comment by inglesuniversal** [comment]
Please keep it open and help us from a way make this a reality starting Expo SDK versión 33.0

**Comment by krean93** [comment]
Has anyone any updates on this issue?

**Comment by kkarkos** [comment]
https://docs.expo.io/versions/latest/sdk/in-app-purchases/

**Comment by holgersindbaek** [comment]
@kkarkos Using Expo's own in-app-purchase module, you’d still have to eject your Expo app (for the foreseeable future), so it doesn't really solve the issue.

If anyone can give a more thorough guide as to how to trick that @EvanBacon us describing, then please share. Maybe even a demo app?

**Comment by EdmundMai** [comment]
@TheInternet I'm running into the same issue with the missing "Libraries" folder. Did you find out how to install this properly on iOS?

**Comment by dragoonzx** [comment]
@inglesuniversal 
I`m interesting, have you found interesting ways to monetize an app without detaching it from expo?

**Comment by dragoonzx** [comment]
Can we use e-payments with webView? Is it legal?

**Comment by inglesuniversal** [comment]
As far as I know you can use 3rd party solutions as a web app (like stripe or PayPal) but inside the AppStore or PlayStore you can’t. Otherwise your app may be kicked out or removed until you do it the right way through the API we’ve all been waiting for since I started using Expo.

**Comment by callyb** [comment]
> Simply:
> 
> * create a new branch `detached`
> * run `exp detach`
> * do all the same stuff you would normally do
> * switch back to `master` to add js code
> * when coding in `master` wrap your IAP module code with the following:
> 
> ```js
> import { NativeModules } from 'react-native';
> const { RNIapModule } = NativeModules;
> function hasIAP() {
>   return !!NativeModules.RNIapModule;
> }
> ```
> 
> * This way your code won't crash when calling IAP methods
> * When deploying or testing IAP use the detached branch - or just skip the branches altogether and go rogue >:)
> 
> The general idea here being `exp detach` just surfaces a `/ios` & `/android` folder so you can use your project as a RN app.
> You will still get all the functionality of a regular Expo app, just use fastlane to deploy so you don't need to use too much native stuff.
> Finally, the branches are useful for updating SDK versions. If you for some reason have a problem updating, you could just detach again and add this lib once more.

Sorry to be so dense, but does this mean that you add the IAP code to each branch separately (if you have to ‘wrap’ it for the expo branch) & then just re-eject on a new branch every time you’ve added expo code to the master or are you merging branches at any point??!  And is this still the best way to add IAP’s to a managed expo app? I’m just finishing up my first big app and need to add this functionality somehow & doing it in a branch seems a good safe option maybe - I just want to make sure I understand the workflow! I also have to say I love expo! It’s been a brilliant way to get into react native and without it I would never have got this far so thank you and keep up the good work!!!

**Comment by yaoonline** [comment]
> > Simply:
> > 
> > * create a new branch `detached`
> > * run `exp detach`
> > * do all the same stuff you would normally do
> > * switch back to `master` to add js code
> > * when coding in `master` wrap your IAP module code with the following:
> > 
> > ```js
> > import { NativeModules } from 'react-native';
> > const { RNIapModule } = NativeModules;
> > function hasIAP() {
> >   return !!NativeModules.RNIapModule;
> > }
> > ```
> > 
> > 
> > 
> > * This way your code won't crash when calling IAP methods
> > * When deploying or testing IAP use the detached branch - or just skip the branches altogether and go rogue >:)
> > 
> > The general idea here being `exp detach` just surfaces a `/ios` & `/android` folder so you can use your project as a RN app.
> > You will still get all the functionality of a regular Expo app, just use fastlane to deploy so you don't need to use too much native stuff.
> > Finally, the branches are useful for updating SDK versions. If you for some reason have a problem updating, you could just detach again and add this lib once more.
> 
> Sorry to be so dense, but does this mean that you add the IAP code to each branch separately (if you have to ‘wrap’ it for the expo branch) & then just re-eject on a new branch every time you’ve added expo code to the master or are you merging branches at any point??! And is this still the best way to add IAP’s to a managed expo app? I’m just finishing up my first big app and need to add this functionality somehow & doing it in a branch seems a good safe option maybe - I just want to make sure I understand the workflow! I also have to say I love expo! It’s been a brilliant way to get into react native and without it I would never have got this far so thank you and keep up the good work!!!

Hi! Did you find the answer? How did you implement it?
