### ISSUE TITLE
requestInIAPPurchase go to screen with cannot connect message

### ISSUE THREAD

**Issue by moYousefAlarand** [dooboolab/react-native-iap#1750]
I use sandbox apple Id  to test in-app-purchase when I call  requestInIAPPurchase after I confirm the terms & conditions dialog go to  a screen with cannot connect message
![Image from iOS](https://user-images.githubusercontent.com/85170567/179919657-b1de3723-08cc-49d9-afd0-f109574a561f.png)

### Version of react-native-iap
8.2.2

### Version of react-native
0.67.4

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
return Succesful

### Actual behavior
return with screen can't connect

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
call requestInIAPPurchase and login with sandbox apple Id then purchase and confirm terms and conditions dialog

**Comment by andresesfm** [comment]
@moYousefAlarand that looks like a system-level dialog that we don't control from this library. Please consider using stackoverflow
