### ISSUE TITLE
Prepaid" base plans attached to subscription are NOT returned from Google Play Billing API.   Only subscriptions supported by react-native-iap  which have "Auto renew" base plan attached. This is because the Android module uses a deprecated method for querying SKU details which is not supported by "Prepaid" base plans

### ISSUE THREAD

**Issue by GaneshDanu** [dooboolab/react-native-iap#1754]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

**Comment by andresesfm** [comment]
Implemented here: https://github.com/dooboolab/react-native-iap/pull/1762

**Comment by andresesfm** [comment]
Created release 9.0.0-beta. Please create tickets if you find issues with it. Thank you
