### ISSUE TITLE
deepLinkToAndoridSubscription  is not working

### ISSUE THREAD

**Issue by firemanx07** [dooboolab/react-native-iap#1768]
Version of react-native-iap
  `  "react-native-iap": "^8.3.0",`
Version of react-native
```
react: 17.0.2 => 17.0.2
react-native: 0.68.2 => 0.68.2
```

Platforms you faced the error (IOS or Android or both?)
Android

Expected behavior
Redirection to subscription account 
Actual behavior
Product not found (wrong packageName)

Tested environment (Emulator? Real Device?)
Real Device

Possible Issue : **RNIapModule.getPackagname() is not returning the correct value .**

**Comment by andresesfm** [comment]
Thank you for the report @firemanx07. Can you please be more specific on how the package is returned incorrectly?

**Comment by professorkolik** [comment]
@andresesfm this method `NativeModules.RNIapModule.getPackageName()` is now returning `{}`
May be you can specify from which attribute it should get the value, there is a possibility that smth wrong with our flavors config

**Comment by andresesfm** [comment]
Thank you @professorkolik. The method is only defined for the GooglePlay flavor. Amazon doesn't implement it. Should we?

**Comment by andresesfm** [comment]
I just confirmed it working on the IapExample app by calling the method directly on a Google Play build

**Comment by professorkolik** [comment]
@andresesfm thank you for quick response
And sorry by flavor I meant we have staging and `production`
Could you please point out from which field the method `getPackageName()` it retrieves the value?

in our app/build.gradle we have
```
productFlavors {
  staging {
    // Pre-compile run ENVFILE=.env.staging
    dimension "version"
    applicationIdSuffix ".staging"
  }
  production {
    // Pre-compile run ENVFILE=.env.production
    dimension "version"
    applicationIdSuffix ""
  }
}
```

and `applicationId` is set in defaultConfig
So WE expect to get from method =>   `app.package.name.staging`

I'll also run the IapExample and play with it

**Comment by andresesfm** [comment]
Any updates on this @professorkolik , @firemanx07 ? I've tested using the example app and it seems to work as expected

**Comment by professorkolik** [comment]
@andresesfm Sorry to not update, yes I checked example app as well, and it works, so the problem in our config
