### ISSUE TITLE
Android - Crash on requestPurchase 9.0.0-beta3

### ISSUE THREAD

**Issue by ntcong91** [dooboolab/react-native-iap#1775]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
9.0.0-beta3
### Version of react-native
0.67.4
### Platforms you faced the error (IOS or Android or both?)
Android
### Tested environment (Emulator? Real Device?)
Real Device SM-A31
### Steps to reproduce the behavior
await iap.requestPurchase({ 
            sku: 'com.iap.item', 
            andDangerouslyFinishTransactionAutomaticallyIOS: false,
            obfuscatedAccountIdAndroid: userId,
            obfuscatedProfileIdAndroid: userId, 
})
![z3602697932275_98add0114e0cb557360ee583c197a91c](https://user-images.githubusercontent.com/8979249/181678145-d9295a78-6f48-48e4-922f-cf663b066e58.jpg)

**Comment by ntcong91** [comment]
add before initConnection
```
    iap.setAndroidNativeModule(NativeModules.RNIapModule);
```
=> no longer crash -> but no IAP popup from google play showed!

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1776
