### ISSUE TITLE
Facing issue in IOS.

### ISSUE THREAD

**Issue by coldfins** [dooboolab/react-native-iap#178]
Hey @dooboolab  I am facing issue 

> Cannot read property 'getAvailableItems' of undefined in Ios 
It's working fine in Android. Every setup is done correctly for IOS.
<img width="1437" alt="screen shot 2018-06-05 at 3 18 54 pm" src="https://user-images.githubusercontent.com/30524626/40968705-d6e8f3e4-68d3-11e8-9be9-56981b2546f0.png">

**Comment by andrideng** [comment]
@coldfins try to connect the module manually. :D

**Comment by chris-divvito** [comment]
+1 same issue at the moment, checking out the manual connection option now

**Comment by coldfins** [comment]
@JJMoon & @andrideng thanks for your suggestions. iOS link was broken fixed it by manually linking.  :D

**Comment by chris-divvito** [comment]
Can confirm, manual linking worked fine - of note, I had to also remove the line from the podfile as per the ejected expo app suggestion (although mine is not an ejected app)
