### ISSUE TITLE
requestPurchaseWithOffer cause app crash

### ISSUE THREAD

**Issue by khj3132** [dooboolab/react-native-iap#1785]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
v8.5.1
### Version of react-native
v0.66.3
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
`requestPurchaseWithOffer` work
### Actual behavior
`requestPurchaseWithOffer` cause app crash
### Tested environment (Emulator? Real Device?)
real device - iphone 12 mini
### Steps to reproduce the behavior
1. get subscription info having a promotional offer to use getSubscription(sku)
2. generate signature like this
    - const combinedString = bundleId + '\u2063' + keyIdentifier + '\u2063' + subscriptionId + '\u2063' + offerId + '\u2063' + userId(applicationUserName) + '\u2063' + nonce + '\u2063' + timeStamp;
3. signed the combinedString with our private key
4. convert signed combinedString to base64 string
When I used `requestPurchaseWithOfferIOS(subscriptionId, userId, withOffer)` function, app crash occured.
This is an error log. This is all the thing.
```
Could not cast value of type '__NSCFNumber' (0x131dfe8c0) to 'NSString' (0x131df5dd8).
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb) 
```
Is there any problem with what I did?
Let me know if anything else can help.
Thank you.

**Comment by ydv0121** [comment]
+1
same here

**Comment by andresesfm** [comment]
@khj3132 the method respects `withOffer` to be an object please take a look at the documentation

**Comment by Dallas62** [comment]
@andresesfm The issue is more: 
The change wasn't documented in the Changelog.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/3429329/187087080-923d2c48-aa6b-470e-8eaa-53a5a0d94fd8.png">

...
