### ISSUE TITLE
IOS thumb purchase.

### ISSUE THREAD

**Issue by coldfins** [dooboolab/react-native-iap#179]
Hello, Is there any way I can Purchase using thumb imprint in IOS? Is there any workaround for that?

**Comment by benevbright** [comment]
Because you’re testing it in the sandbox. 
It will be Ok with using thumbs when it’s in production.

**Comment by JJMoon** [comment]
I have no clue how to do it. There are several authorizing methods out there, we have to arrange those methods first.

**Comment by JJMoon** [comment]
Wel.. @benevbright answered very well. We will close this issue after some time. 
@coldfins Thank you for your concern.
