### ISSUE TITLE
getSubscriptions does not return Android offers - v9.0.0-beta7

### ISSUE THREAD

**Issue by Mkolakoglu** [dooboolab/react-native-iap#1791]
Hello, 

I am trying to use `getSubscriptions` to fetch the offers. However, there is no offer data in the object it returns:
<img width="300" alt="Screen Shot 2022-08-02 at 17 41 20" src="https://user-images.githubusercontent.com/16003411/182416128-65db5b99-5fc1-47c6-bba4-ac74a86ad563.png">

When I check `RNIapModule.kt`, I see that the new classes from Google Play Billing v5 are not recognized. It might have not been installed properly. This can be the reason of why it does not work.
<img width="468" alt="Screen Shot 2022-08-02 at 17 34 39" src="https://user-images.githubusercontent.com/16003411/182416621-4789e423-c9ef-400b-b9eb-7c918cdbb794.png">

Any help would be appreciated.

Thanks in advance!

---

### Version of react-native-iap
9.0.0-beta7

### Version of react-native
0.69.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
`getSubscriptions` should return Android offers

### Actual behavior
`getSubscriptions` does not return Android offers

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Use `getSubscriptions` on a subscription with offer. You will see that it does not return the offer

**Comment by andresesfm** [comment]
Hello, I have made some fixes, please try version `9.0.0-beta9`

**Comment by lvhiep** [comment]
Hi @andresesfm, i still facing this issue on version 9.0.0-beta9 and version 9.0.0-rc1
getSubscriptions(["id"]) alway return empty. 
btw, getSubscriptions with more than 1 sku will work but sometime not return all items.

**Comment by andresesfm** [comment]
Hello @lvhiep si you are saying that passing a single element array makes it not return any subscription?

Also, if you are are getting mixed results, can you please add more detail? Any errors or stack trace? 

Can you please confirm this happens on 9.0.0-rc.4?

**Comment by lvhiep** [comment]
Hi @andresesfm , it work well on 9.0.0-rc.4. Thank you!
