### ISSUE TITLE
Get the list of subscribed plans for the user.

### ISSUE THREAD

**Issue by dooboolab** [dooboolab/react-native-iap#18]
`getPurchaseItemsAndroid(inapp : string)`

We are missing above method currently for IOS.
Also looking for the contributor!

**Comment by dooboolab** [comment]
@ankurToko 
Should sheck this out. So @JJMoonl, would you implement restoreIosNonConsumableProducts method? Or just leave it like this? What is a plan?

**Comment by JJMoon** [comment]
OK.  I will change and commit..

**Comment by alanlanglois** [comment]
What about this method?
I get a  RNIap.getPurchaseItemsAndroid is not a function error.
What are the params needed by this function?
