### ISSUE TITLE
Android: E_IAP_NOT_AVAILABLE due to promotedProductListener call

### ISSUE THREAD

**Issue by jgillick** [dooboolab/react-native-iap#1800]
Version: 8.6.0

Using `withIAPContext` on Android throws the `E_IAP_NOT_AVAILABLE` because it calls the iOS-only method `promotedProductListener`.

The source of the bug is this line:
https://github.com/dooboolab/react-native-iap/blob/d5adf25f2220a2a4a334aa10fb4bd378f039c2fb/src/hooks/withIAPContext.tsx#L138-L145

From PR: https://github.com/dooboolab/react-native-iap/pull/1786

**Comment by andresesfm** [comment]
Fix available in latest release
