### ISSUE TITLE
Error: Failed to load parser '@babel/eslint-parser'

### ISSUE THREAD

**Issue by andresesfm** [dooboolab/react-native-iap#1803]
@jeremybarbet . Are you seeing: 
Error: Failed to load parser '@babel/eslint-parser' declared in '.eslintrc.js': Cannot find module '@babel/eslint-parser'
I get that error on vscode
Looks like it's been marked as read-only here: https://github.com/babel/babel-eslint/issues/788. Do we still need it?

**Comment by jeremybarbet** [comment]
After pulling main from this [commit](https://github.com/dooboolab/react-native-iap/commit/d5adf25f2220a2a4a334aa10fb4bd378f039c2fb) did you:

```sh
rm -rf node_modules IapExample/node_modules
```

Go to `yarn.lock` and `IapExample/yarn.lock`, delete the content of both files and save.

Then you can run `yarn` at the root.

It's very likely you still have cache from yarn@1

**Comment by andresesfm** [comment]
Just tried the suggested steps but no luck 🤷 . It's strange because I see that `@babel/eslint-parser` is indeed in `devDepencencies`

**Comment by jeremybarbet** [comment]
Also tried myself and everything works fine in vscode or through the terminal. You can try to run `yarn lint`? Are you on `main` or `next`?

**Comment by andresesfm** [comment]
I'm on `next` but I just merged from main.  `yarn lint` works. This only happens when I open a `.ts` file

**Comment by andresesfm** [comment]
just had to restart vscode 🙃

**Comment by jeremybarbet** [comment]
Ahah nice! Switching between `main` and `next` might definitely break stuff along the way. Packages version/lock files are totally different, you might have to clean everything each time, until we can sync both branches
