### ISSUE TITLE
Github issues template is gone

### ISSUE THREAD

**Issue by andresesfm** [dooboolab/react-native-iap#1804]
@jeremybarbet I just realized that the github template for new issues is no longer appearing after your recent changes. Is it OK if we revert?

**Comment by jeremybarbet** [comment]
It has been moved in here https://github.com/dooboolab/react-native-iap/tree/main/.github/ISSUE_TEMPLATE. Probably because the name has to follow a convention. Let me check the Github documentation and open a PR to fix that

**Comment by jeremybarbet** [comment]
Fixed in here https://github.com/dooboolab/react-native-iap/pull/1805

**Comment by andresesfm** [comment]
That worked @jeremybarbet thank you
