### ISSUE TITLE
Dynamic Product Add  Over In-App-Purchase From App

### ISSUE THREAD

**Issue by atul8** [dooboolab/react-native-iap#1806]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

I need to add dynamic products on app store from mobile app for IAP feature.Just i go through on link then i got Generic in-app-purchase implementation required and subscription groups. How do i implement the generic in-app-purchase implementation.
I go through it with the help of SKProductsRequest we can get it.

**Expected Behavior**

Dynamic Add Products From App Over In-APP-Feature ProductsList.

**Screenshots**

**Environment:**

- react-native-iap:
- react-native:
- Platforms (iOS, Android, emulator, simulator, device):

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
This is not the library for you. We only read the products and allow purchase but not creation

**Comment by atul8** [comment]
Dear Team,

Thank you for your reply.

**Comment by atul8** [comment]
Dear Sir,

Hope you are doing well.
                                        Please recommend another library,
which can  full fill my requirement. Product Creation as well Product Read
And Product Purchase And Product History And Order Details. It would be
very helpful for me.

Thank You
Best Regards
Atul Kumar Ojha

**Comment by atul8** [comment]
Dear Sir,
                Please recommend it another library which can full fill my requirement. Help me!!!!
