### ISSUE TITLE
getReceiptIOS function is gone.

### ISSUE THREAD

**Issue by ifsnow** [dooboolab/react-native-iap#1808]
As of version 8.6.0, `getReceiptIOS` has been removed.

https://github.com/dooboolab/react-native-iap/blob/8.5.3/src/iap.ts#L665 : exists
https://github.com/dooboolab/react-native-iap/blob/8.6.0/src/iap.ts#L665 : removed

I wonder if this is a breaking change.

**Comment by andresesfm** [comment]
@jeremybarbet was this removed by mistake?

**Comment by jeremybarbet** [comment]
Yep definitely a mistake when I moved some code around

**Comment by andresesfm** [comment]
fix: https://github.com/dooboolab/react-native-iap/pull/1812/files

**Comment by jeremybarbet** [comment]
It's fixed in this release https://github.com/dooboolab/react-native-iap/releases/tag/8.6.4
