### ISSUE TITLE
The app hangs when buyProduct() has an error

### ISSUE THREAD

**Issue by wasedaigo** [dooboolab/react-native-iap#183]
Version 1.0.8

If I have a line like this, this will never get returned - it hangs.
In my case the error is *responseCode: 7(ITEM_ALREADY_OWNED)*
```
const purchase = await RNIap.buyProduct(productId);
```
I think this is an unwanted side effect caused by this commit.
You probably should at least resolve the promise if you do not want to reject it.
https://github.com/dooboolab/react-native-iap/commit/d74846c4e0e6bbf65e3a4a1749aa675a53bf1724#diff-b21dbc2d57e14bf6f1b5f81c3a3c3ba5R309

What do you think?

**Comment by dooboolab** [comment]
@wasedaigo I've get that code away because below code does that when purchaseListener is called.
![image](https://user-images.githubusercontent.com/27461460/41164177-7f9aab74-6b75-11e8-843b-e54d57904cfe.png).
However, I've revived this code again for you to see how it works. It is in `1.1.0`.

**Comment by wasedaigo** [comment]
Ok, this is not hanging anymore.
I needed to do a bit work as android errors were not documented.
Here is how I am handling the error. Does this look alright? You can close the issue now.

```
    try {
      await RNIap.prepare();
      await RNIap.getProducts([productId]);
      let purchase;
      try {
        purchase  = await RNIap.buyProduct(productId);
      } catch (e) {
        if (e.code !== 'E_ALREADY_OWNED') {
          throw e;
        }
      }
```

**Comment by dooboolab** [comment]
@wasedaigo Good idea. I understood that. I think I can manage this one but since I am really busy these days, I may not upgrade this feature for a while.. I am out of time with my work so these days I am just maintaining this module for those who needs help or fixing critical bugs. I maybe helpful maybe after 2~3 months from now. Sorry for that. However, I may have time to review the `PR`.

**Comment by dooboolab** [comment]
I've publshed your PR to `1.1.2`. I will close this for now.

**Comment by wasedaigo** [comment]
I can help with PR at some pint, but I need to know what you would like to do.
