### ISSUE TITLE
Handle IOS promocode and implement promoted subscriptions - RNIap/RNIap-Swift.h' file not found

### ISSUE THREAD

**Issue by atech-basemalnabulsi** [dooboolab/react-native-iap#1831]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

I am trying to use Promocode and promotion service form APPLE since it's required now to use it and not using our own promocode implementation.
While trying to define the Queue we faced import issue as "'RNIap/RNIap-Swift.h' file not found"
Based on RNIap documentation we should import it to define purchase queue, can you help to find the missing part.

Documentation URL is:
https://react-native-iap.dooboolab.com/docs/faq/#objc-version

When I comment the import I get error on 
[[SKPaymentQueue defaultQueue] addTransactionObserver:RNIapQueue.shared];
as "Property 'shared' not found on object of type 'RNIapQueue'"

**Expected Behavior**

We expect to accept the package or has a file called RNIap-Swift.h to import 
[[SKPaymentQueue defaultQueue] addTransactionObserver:RNIapQueue.shared];=

**Screenshots**

**Environment:**

- react-native-iap: ^8.6.5
- react-native: 0.63.4
- Platforms (iOS, Android, emulator, simulator, device): ios device

**To Reproduce**

1. Go to the URL https://react-native-iap.dooboolab.com/docs/faq/#objc-version
2. Continue with the steps
3. You will get the error in the second import step

---

[Optional] **Additional Context**

<img width="726" alt="Screen Shot 2022-08-10 at 5 07 56 AM" src="https://user-images.githubusercontent.com/109934170/183794742-7538fe47-60aa-41f7-8615-56544ce3040e.png">
<img width="721" alt="Screen Shot 2022-08-10 at 5 06 19 AM" src="https://user-images.githubusercontent.com/109934170/183794763-e993d5b4-4c3b-480a-8c39-211a0b3b3b90.png">

**Comment by andresesfm** [comment]
`RNIapQueue` has been recently removed as it is no longer necessary. Documentation needs to be updated

**Comment by andresesfm** [comment]
https://github.com/dooboolab/react-native-iap/pull/1836
