### ISSUE TITLE
Add offer or billingPeriod to Purchase objects on Android for 9.0.0

### ISSUE THREAD

**Issue by SimonDamberg** [dooboolab/react-native-iap#1833]
When processing subscriptions, there is no way of knowing what offer the user purchased. This makes it difficult in cases where it is important for the backend to know what the user purchased. Adding the `pricingPhase`, or just the `billingPeriod`, to the `Purchase` object would be great.

**Comment by SimonDamberg** [comment]
@andresesfm Yes, but the issue is when a purchase happens in the background, for example a renewal, or if something happens during the processing of the `Purchase` (crash, user closes, network disconnect etc.). In this case, the `Purchase` would be processed on the next application start, but there would be no state with the offer available to communicate to the backend in the listener. Because of this behaviour, I don't keep track of the productId in a state and instead access it from the `Purchase` object where it is available. This would be great if I could do for the offer as well. I want to be able to keep track of the offers users have bought, as well as show in the app which offer the user currently owns if they want to switch.

**Comment by andresesfm** [comment]
@SimonDamberg I think you are correct in the sense that 1) You should be able to track the offer information. and 2) That Google Billing Library doesn't support it.

Having said that, the suggestion would be to store the information in your backend when the purchase is initiated and then reconcile it when you verify the purchase on your backend.

**Comment by SimonDamberg** [comment]
Yes, that is my workaround as of now. I hope it gets added to the Google Billing Library since it would make sense to be able to access it there as well :)
