### ISSUE TITLE
iOS Build native error: applicationUsername is optional

### ISSUE THREAD

**Issue by yuri-lomashko-itechart** [dooboolab/react-native-iap#1837]
**Description**

iOS stopped building on the latest version. There is a error in `RNIapIos.swift` file

**Expected Behavior**

App builds successfully

**Screenshots**

<img width="671" alt="Screen Shot 2022-08-10 at 19 34 27" src="https://user-images.githubusercontent.com/54143988/183965037-5f6f1982-abcb-4c00-bb8e-af83a28a542c.png">

**Environment:**

- react-native-iap: 8.6.5
- react-native: 0.67.4
- Platforms: iOS

**To Reproduce**

Just make a build though Xcode or CLI

**Comment by andresesfm** [comment]
Thank you for reporting this @yuri-lomashko-itechart. Could this be related to using an older version of react native? (Our CI process is building correctly)

**Comment by yuri-lomashko-itechart** [comment]
Yeah, it could be. It's a native project with integrated React Native part. So there are a lot of old things :).
Unfortunately I know swift not well and don't know correct solution here, but I temporary fixed it with that patch
```diff
diff --git a/ios/RNIapIos.swift b/ios/RNIapIos.swift
index 6ea8857d218d8749556d1a9b7c09cea13dbd64ba..1396c011d1c668c8546c40c1beba96311ec19918 100644
--- a/ios/RNIapIos.swift
+++ b/ios/RNIapIos.swift
@@ -210,7 +210,7 @@ class RNIapIos: RCTEventEmitter, SKRequestDelegate, SKPaymentTransactionObserver
       let payment = SKMutablePayment(product: prod)
 
       if applicationUsername != nil {
-        payment.applicationUsername = applicationUsername
+        payment.applicationUsername = applicationUsername ?? ""
       }
       SKPaymentQueue.default().add(payment)
     } else {

```

**Comment by andresesfm** [comment]
@yuri-lomashko-itechart I think this is a better option: https://github.com/dooboolab/react-native-iap/pull/1839 (Closer to the original intent)
