### ISSUE TITLE
Unsync between `main` and `next`

### ISSUE THREAD

**Issue by jeremybarbet** [dooboolab/react-native-iap#1838]
Hey @andresesfm

When I try to open a PR to merge `next` into `main` the diff looks very off. Like some files are missing from `next` or `main` but they are present in both. That make my rebases for my branches off `next` insanely complicated.  

You can check it out there https://github.com/dooboolab/react-native-iap/compare/main...next 

Any chance something went wrong when merging between branches? Maybe we could cherry of the next commits into a clean new branch off main?

**Comment by andresesfm** [comment]
Can you give me some examples of such files?
It is definitely messy, there's been a lot of merging from main to next along with many other commits inside next. When we do the merge we'll have to pay attention to those but they'll be all squashed into a single commit so no need to worry about all the inbetween commits

**Comment by jeremybarbet** [comment]
If you open the link and click on the "files changed", for the first 5 files they are both present on main and next but appears as a diff which is weird. When you go the path for each of these files on main and next they are both same files

**Comment by andresesfm** [comment]
Closing in favor of: https://github.com/dooboolab/react-native-iap/discussions/1852
