### ISSUE TITLE
Android hangs on RNIap.prepare()

### ISSUE THREAD

**Issue by donjordano** [dooboolab/react-native-iap#184]
### Version of react-native-iap
1.0.8

### Version of React Native
0.55.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
prepare for a purchase or return an error

### Actual behavior
The app hangs and not returning nothing.
### Tested environment (Emulator? Real Device?) 
Real device

### Steps to reproduce the behavior
Here is the test code:
```javascript
async componentDidMount() {
    try {
      await RNIap.prepare(); // the app hangs here and nothing happnes on Android
      this.getItems(); // never get called
    }
    catch (err) {
      console.warn(err.code, err.message);
    }
  }
```

Hi, I'm experiencing a strange behavior of the app. On RNIap.prepare() nothing get called after that. No error is returned.

**Comment by dooboolab** [comment]
@donjordano Could you share what is printing after `RNIap.prepare()`? Do like below.
```
const result  = RNIap.prepare();
console.log('result', result);
```

**Comment by donjordano** [comment]
@dooboolab here is the result: 
```javascript
result Promise {_40: 0, _65: 0, _55: null, _72: null} - Android
result Promise {_40: 0, _65: 1, _55: undefined, _72: null} - iOS
```

**Comment by donjordano** [comment]
@dooboolab I manage to fix it. The issue was in **settings.gradle**  somehow these two lines:
```java
include ':react-native-iap'
project(':react-native-iap').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-iap/android')
```
appear 3 times. So I deleted dublicated lines and it work.

**Comment by dooboolab** [comment]
@donjordano Yes~ react-native link still has some bugs when linking. You should check the changes in your project files every time you use this command to link automatically.
