### ISSUE TITLE
iOS transactionId is different than the receipt's transactionID

### ISSUE THREAD

**Issue by angelos3lex** [dooboolab/react-native-iap#1844]
**Description**
We noticed some edge case where the `SubscriptionPurchase.transactionId` is different than the `transaction_id` that's included inside the `SubscriptionPurchase.transactionReceipt`.  We call `https://buy.itunes.apple.com/verifyReceipt` using the `SubscriptionPurchase.transactionReceipt` as body, and the returned response contains a different transactionId than the original that was returned from iap.

**Expected Behavior**
We expected that the `transactionId` is unique and the receipt response from apple would always contain the same transactionID.
(This is the case normally, we have not shown this malformed problem a lot)

**Environment:**
- react-native-iap: 7.5.0
- react-native: 0.67.4
- Platform: iOS

**Additional Context**
We request a subscription using: `IAP.requestSubscription(subscription.productId)`

Any Ideas? Is this a valid scenario we need to handle?

**Comment by professorkolik** [comment]
I think you should rely on `originalTransactionIdentifierIOS` which is originalTransactionId on Apple side
