### ISSUE TITLE
Subscription upgrade in Android

### ISSUE THREAD

**Issue by vshab** [dooboolab/react-native-iap#185]
### Version of react-native-iap
1.1.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Be able to upgrade subscription

### Actual behavior
There is no way to upgrade subscription in Android

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
See API

### Description

Hello!

In iOS upgrading is handled by the AppStore when buying **Yearly** while having **Monthly**. However as I mentioned in #171 there is a special way in Android to upgrade subscription:
>However, when upgrading or downgrading, you pass the product IDs for the current subscription and the future (upgraded or downgraded) subscription to the BillingFlowParams object using the addOldSku() method.

https://developer.android.com/google/play/billing/billing_subscriptions#Allow-upgrade

I think it's an important feature to have in IAP.

**Comment by dooboolab** [comment]
@vshab Since, I am really busy these days, hope you could give us some `PR` to this repo for new features or new features won't be applied for a while..

**Comment by evaleirasclapps** [comment]
What are the ProrationMode possible values for android?? The documentation mention {number}, but what numbers??

Thanks!

**Comment by hyochan** [comment]
@evaleirasclapps Please check the constant value [here](https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.ProrationMode).

**Comment by mehdichk** [comment]
Hi guys, thanks @hyochan for the great job, really.
Is the downgrade/upgrade wking now ? I saw that it's on the doc, but not working for me ^^
ie => when I try to upgrade from monthly to yearly : I find myself with 2 active subscription (good for my wallet, but my users will kill me ^^)
