### ISSUE TITLE
Documentation misleading and misunderstanding

### ISSUE THREAD

**Issue by YoFiq** [dooboolab/react-native-iap#1854]
Can somebody provide updated documentation about how to use that lib?

On website half of documentation describing old versions of the lib
Half of IAP hooks not works
Almost all info is written for Class-based components and no function-based

Also in advanced usage example lot of function was just removed in latest versions

**Comment by hyochan** [comment]
If you are looking for function component example, I hope our example code helps for now.

https://github.com/dooboolab/dooboolab.com/blob/main/src/components/pages/Sponsor.tsx


Hopefully we can update the doc soon

**Comment by jeremybarbet** [comment]
Wip for new documentation here https://github.com/dooboolab/react-native-iap/pull/1815

**Comment by Huseyinnurbaki** [comment]
Also please have a look at the external links/articles mentioned in the documentation.
Some of them are outdated and misleading.

For example: 
https://medium.com/dooboolab/announcing-react-native-iap-hooks-96c7ffd3f19a
4.Purchase Products
requestPurchase usage looks like outdated.

https://medium.com/dooboolab/react-native-in-app-purchase-121622d26b67
not misleading but a little old.

**Comment by Dallas62** [comment]
#1894

**Comment by andresesfm** [comment]
Happy to accept PRs to fix the documentation. Thank you for understanding

**Comment by andresesfm** [comment]
Merged @jeremybarbet 's PR with updated documentation. Please create a PR if you find any issues with the documentation that were not covered on his updates
