### ISSUE TITLE
Error when using Hooks - offerTokenArr

### ISSUE THREAD

**Issue by mikemangas** [dooboolab/react-native-iap#1856]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

I switched to  useIAP hooks. 

And whenever I call the requestPurchase function (purchase Button),  i get the error (see screenshot).
According the Screenshot, the "offerTokenArr" is missing, but i get this token, only when calling "getSubscriptions" and not "getProducts".

**Expected Behavior**

No error. Successfull purchase.

**Screenshots**

My Code:
<img width="868" alt="Screenshot 2022-08-14 at 23 17 39" src="https://user-images.githubusercontent.com/85886271/184555338-70a493f9-22c5-46f5-b13f-5f57d623570c.png">

<img width="382" alt="Screenshot 2022-08-14 at 23 23 21" src="https://user-images.githubusercontent.com/85886271/184555439-52b95a02-092d-4628-af43-2720f5ee6edb.png">

the Error: 
![Screenshot_1660511587](https://user-images.githubusercontent.com/85886271/184555192-ad23e7a6-a649-4f73-bfdd-67337564b2dd.png)

**Environment:**

- react-native-iap:
- react-native:
- Platforms (Android, Emulator, API 33):

**To Reproduce**

see code screenshot above.

---

[Optional] **Additional Context**

**Comment by SergiOnGit** [comment]
It isn't about hooks. I got this error too. Just upgraded to version 9 and now I have this error during requestPurchase. As I see latest stable version is 8.2.1. Others have bugs or am I doing something wrong? As I see docs are the same, nothing changed.

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1857

**Comment by andresesfm** [comment]
`9.0.1` has been released with the fix

**Comment by SergiOnGit** [comment]
@andresesfm Now there is another error
![Screenshot_1660599391](https://user-images.githubusercontent.com/13105977/184724264-73f69d51-51ca-4013-8025-8309235e3d96.png)
r

**Comment by andresesfm** [comment]
@SergiOnGit Can you please post here an example of your call to do the purchase?

**Comment by SergiOnGit** [comment]
Here you are @andresesfm 

```
requestRemoveAds = async (type = 0) => {
        try {
            const itemSkus = Platform.select({
                android: [
                    'premium_4',
                ],
                ios: [
                    'premium_4',
                ]
            });

            await RNIap.getProducts(itemSkus);
            await RNIap.requestPurchase(itemSkus[type]);
        } catch (error) {
            // toast.show(translate.purchase_error_msg[language], 4000);

            console.warn('requestRemoveAds', error);
        }
    }
```

**Comment by andresesfm** [comment]
I see. Please note that `requestPurchase` now takes an object as parameter instead of positional parameters. Please try `requestPurchase({sku:mySku}`

**Comment by SergiOnGit** [comment]
@andresesfm Hm right. Looks like I have to update the code.

**Comment by lincdh** [comment]
After upgrading to 9.0.1 then 9.0.3 I still get this error @andresesfm.

I have checked src/iap.ts buyItemByType there is nothing wrong([] exists instead of undefined)

**Comment by mikemangas** [comment]
works perfectly fine for me, since updated to 9.0.4
Thank you so much!
