### ISSUE TITLE
[Android] requestSubscription throws an error "Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by saadanii** [dooboolab/react-native-iap#1862]
<h3>Version of react-native-iap</h3>
8.6.7

<h3>Version of react-native</h3>
0.68.2

<h3>Platforms you faced the error (IOS or Android or both?)</h3>
Android

[<h3>Screenshot</h3>
![screenshot](https://user-images.githubusercontent.com/36452851/184930192-1f2b26d6-2ed4-485b-b2a0-dbb0e1095deb.png)

<h3>Expected behavior</h3>
requestSubscription should open the native store modal to purchase a subscription.

<h3>Actual behavior</h3>
requestSubscription throws an error.

<h3>Tested environment (Emulator? Real Device?)</h3>
Real Device
Emulator

<h3>Steps to reproduce the behavior</h3>
Call requestSubscription() within an app in staging.

Let me know if anything else can help.

**Comment by andresesfm** [comment]
@saadanii Can you please share how you are calling the method? The method recently changed to take an object instead of positional parameters. Please also consider moving to 9.0.2 or newer

**Comment by saadanii** [comment]
@andresesfm i'm calling it like this : 
`
await requestSubscription({
          sku: productId,
          obfuscatedAccountIdAndroid: currentUser?.uuid,
          obfuscatedProfileIdAndroid: eventUuid,
          applicationUsername: eventUuid,
});
`

**Comment by andresesfm** [comment]
@saadanii I found this issue. Seems to be related to a bug in the library: https://stackoverflow.com/q/65095426/570612. Can you please try in 9.0.2 and see if that fixes it?

**Comment by saadanii** [comment]
We're atm trying to stay away from version 9 as it uses billling v5 and we based all iap logic on billing v4

**Comment by andresesfm** [comment]
I see, in that case, I would suggest forcing your app to use a newer version of the library: https://developer.android.com/google/play/billing/release-notes#4-1
