### ISSUE TITLE
[Android] Duplicated pricing phase in subscriptionOfferDetails

### ISSUE THREAD

**Issue by mmajk55** [dooboolab/react-native-iap#1878]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

I've created a subscription and I've added an offer to the base plan and now I have two duplicated pricing phases in `subscriptionOfferDetails`. Is this an expected behavior? Shouldn't we have only one subscription offer detail in this case?  

**Expected Behavior**
Don't have duplicated `pricingPhase` in separate `subscriptionOfferDetails` element if discount offer is added

**Screenshots**
![Screen Shot 2022-08-22 at 12 26 25](https://user-images.githubusercontent.com/45169174/185899859-66ad5a3b-32c5-4d4a-a260-0e9a820016d1.png)

**Environment:**

- react-native-iap: 9.0.4
- react-native: 0.66.4
- Platforms (iOS, Android, emulator, simulator, device): Android

**To Reproduce**

1. Create a subscription and add an offer to the base plan

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
Hello @mmajk55 . I also get that duplication. My interpretation is that you might want to have the option to show the free trial or have your users purchase directly without trial. This is not a bug on our end since we are just passing down what the native library returns.

**Comment by mmajk55** [comment]
Hello, @andresesfm thanks for explaining!

**Comment by mmajk55** [comment]
@andresesfm I have one more question. In Google play we are setting the `basePlanId` for each base plan. There is no chance to receive it from API?

**Comment by andresesfm** [comment]
@mmajk55 I thought about the same but I don't see a way to get it from the native API. As an alternative I see that there's the concept of "tags". Accoding to the documentation: 
> Tags | A tag is an optional label of up to 20 characters that you can use to mark or group base plans and offers and identify them in the API. Tags can be used to determine which offer to show when the user is eligible for more than one. You can add up to 20 tags. Users cannot see tags.
-- | --

I haven't used them but if they do work for you, please let us know to add to the documentation

**Comment by mmajk55** [comment]
@andresesfm thanks for the answer. I will try it and let you know
