### ISSUE TITLE
Parameter specified as non-null is null: skuArr after updating to 10.0.0

### ISSUE THREAD

**Issue by Relax594** [dooboolab/react-native-iap#1883]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

App is crashing when running `getSubscriptions(['android.test.purchased', 'android.test.item_unavailable'])` after updating to v10.0.0. Working fine with v9.x

`Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter skuArr`
in `getItemsByType`

**Expected Behavior**

Don't crash

**Screenshots**

**Environment:**

- react-native-iap: 10.0.0
- react-native: 0.68.3
- Platforms (iOS, Android, emulator, simulator, device): Android (iOS not tested)

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by minosvasilias** [comment]
Was facing the same error earlier today. Check `src/iap.ts`:
https://github.com/dooboolab/react-native-iap/blob/dd3d6d04cc21f1f0971c1571fbf159505666f88d/src/iap.ts#L138-L142

Expected value is `getSubscriptions({skus: ['android.test.purchased', 'android.test.item_unavailable']})`
