### ISSUE TITLE
applicationUsername is not showing up in transaction received from apple when using requestSubscription

### ISSUE THREAD

**Issue by normtronics** [dooboolab/react-native-iap#1889]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

I am trying to pass a UUID to the applicationUsername field when requesting a subscription. Upon completing that subscription and looking at the transaction info from apple, the appAccountToken isn't present

**Expected Behavior**
I expect the appAccountToken to be present int the transaction info received from apple when setting applicationUsername in requestSubscription

**Screenshots**

**Environment:**
I am working in the Sandbox env

- react-native-iap: 9.0.4
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): IOS, real device 

**To Reproduce**

1. Set applicationUsername in requestSubscription
2. Complete a transaction 
3. Check the transaction on the server 

---

[Optional] **Additional Context**

**Comment by duchoang145** [comment]
+1

**Comment by quentinNpApnl** [comment]
@normtronics did you find a solution?
