### ISSUE TITLE
getProducts and getSubscriptions returns empty array  in ios working fine in android 

### ISSUE THREAD

**Issue by skjangid** [dooboolab/react-native-iap#1895]
"react": "17.0.2",
"react-native": "0.66.4",
"react-native-iap": "8.0.5",

getProducts and getSubscriptions returns empty array  in ios working fine in android.

**Comment by andresesfm** [comment]
Please try a newer version. If the problem persists, it would mean this is a configuration issue on the AppStore. (Skus not matching what you are passing)
