### ISSUE TITLE
requestPurchase showing an error

### ISSUE THREAD

**Issue by Kadir-prog** [dooboolab/react-native-iap#1899]
![screenshot-1661852813275](https://user-images.githubusercontent.com/80304501/187414624-93b7392d-2754-4adc-bb10-7e2adbd2241e.png)

version
"react-native-iap": "^9.0.0-rc.4",

when i pass product id every time i'm getting same error 

here is my code

const initilizeIAPConnection = async () => {

        await IAP.initConnection()

            .then(async (connection) => {

                console.log('IAP result', connection);

                getItems();

            })

            .catch((err) => {

                console.warn(`IAP ERROR ${err.code}`, err.message);

            });

        await IAP.flushFailedPurchasesCachedAsPendingAndroid()

            .then(async (consumed) => {

                console.log('consumed all items?', consumed);

            }).catch((err) => {

                console.warn(`flushFailedPurchasesCachedAsPendingAndroid ERROR ${err.code}`, err.message);

            });

    };

    const getItems = async () => {

        try {

            console.log("itemSubs ", items);

            const Products = await IAP.getProducts(items);

            console.log(' IAP Su', Products);

            if (Products.length !== 0) {

                if (Platform.OS === 'android') {

                    //Your logic here to save the products in states etc

                    setsubcription_plans(Products)

                } else if (Platform.OS === 'ios') {

                    // your logic here to save the products in states etc

                    // Make sure to check the response differently for android and ios as it is different for both

                }

            }

        } catch (err) {

            console.warn("IAP error", err.code, err.message, err);

            //   setError(err.message);

        }

    };

const requestSubscription = async (sku) => {

        console.log("IAP req", sku);

        try {

            await IAP.requestPurchase(sku)

                .then(async (result) => {

                    console.log('IAP req sub', result);

                    if (Platform.OS === 'android') {

                        // setPurchaseToken(result.purchaseToken);

                        // setPackageName(result.packageNameAndroid);

                        // setProductId(result.productId);

                        // can do your API call here to save the purchase details of particular user

                    } else if (Platform.OS === 'ios') {

                        console.log(result.transactionReceipt)

                        setProductId(result.productId);

                        setReceipt(result.transactionReceipt);

                        // can do your API call here to save the purchase details of particular user

                    }

                })

                .catch((err) => {

                    console.warn(`IAP req ERROR %%%%% ${err.code}`, err.message, isModalVisible);

                });

        } catch (err) {

            console.warn(`err ${err.code}`, err.message);

        }

    };

did any thing wrong here please help

**Comment by Kadir-prog** [comment]
this is new one

![screenshot-1661855773516](https://user-images.githubusercontent.com/80304501/187415987-ce68d61b-8325-4a24-bdc5-5f2fcaea0e19.png)

**Comment by andresesfm** [comment]
@Kadir-prog please try the 9.0.4 release instead of the beta, I think that issue was fixed. Reopen if it's still failing

**Comment by Kadir-prog** [comment]
![screenshot-1662009337539](https://user-images.githubusercontent.com/80304501/187836857-bf2b5bb7-753f-4419-a0b4-51808fdf760c.png)

hi @andresesfm this is new one

**Comment by andresesfm** [comment]
Use `requestPurchase({sku})`
