### ISSUE TITLE
validateReceiptIos always returns false

### ISSUE THREAD

**Issue by BenIrving** [dooboolab/react-native-iap#190]
### Version of react-native-iap
1.0.7
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
validateReceiptIos returns true for valid receipts
### Actual behavior
validateReceiptIos always returns false
### Tested environment (Emulator? Real Device?)
Real device, sandbox app store
### Steps to reproduce the behavior

I am able to make subscription purchases successfully, and receive a transaction receipt. When I try to validate this on iOS using validateReceiptIos(receiptBody, true, 55) I always get returned false.

Looking at the code in the package: 

```
 if (res) {
        if (RNVersion < 54) {
          const json = JSON.parse(res._bodyInit);
          return json;
        }
        const json = await res.text();
        res = JSON.parse(json);
      }

      return false;

```
Is this not always going to return false when RNVersion >= 54? the parsed result is never returned from the function. 

Also, if I return `res = JSON.parse(json);` I always get 
`status
:
21004`
Is this due to us not sending a shared secret with the request?

**Comment by dooboolab** [comment]
@BenIrving Oops, my mistake. Could you try `react-native-iap@1.1.5` and come back again?
