### ISSUE TITLE
A requestPurchase promise not resolves if endConnection called for Android

### ISSUE THREAD

**Issue by mtnt** [dooboolab/react-native-iap#1901]
**Description**

My app is configured to end connection when it fall into background state and init connection again when it returns into active state. So, when I call `requestPurchase` on android, the native payment modal cause the app goes into background state and the connection brakes and neither then or catch branch code executed.

I do not remember why I configured the app so, but I did it deliberately =)

**Expected Behavior**

The requestPurchase should return a purchase after reinit or at least it should emit an exception. Something =)

**Environment:**

- react-native-iap: 8.0.8
- react-native:0.68.1
- Platforms (iOS, Android, emulator, simulator, device): Android emulator Pixel_4_API_31

**To Reproduce**

1. configure a listener of state
```
AppState.addEventListener(
      'change',
      (() => {
        let prevState;
        return state => {
          if (state === 'active' && prevState === 'background') {
            RNIap.initConnection()
          } else if (state === 'background') {
            RNIap.endConnection()
          }
          prevState = state;
        };
      })()
    );
```
2. call `await RNIap.requestPurchase(productId, false);`

**Comment by andresesfm** [comment]
@mtnt Should you be using `await` before init and end connection?

**Comment by mtnt** [comment]
@andresesfm I use it in regular promise way:
```
RNIap.initConnection().then(() => {
      console.log('DBG: IAP connection inited by', source);

      if (Platform.OS === 'Android') {
        // we make sure that "ghost" pending payment are removed
        // (ghost = failed pending payment that are still marked as pending in Google's native Vending module cache)
        RNIap.flushFailedPurchasesCachedAsPendingAndroid()
          .catch(() => {
            // exception can happen here if:
            // - there are pending purchases that are still pending (we can't consume a pending purchase)
            // in any case, you might not want to do anything special with the error
          })
          .then(() => {
            console.log('DBG: subscribe to purchase');
            this._subscribeToPurchase();
          });
      } else {
        console.log('DBG: subscribe to purchase');
        this._subscribeToPurchase();
      }
    });
```
and
```
RNIap.endConnection().then(() => {
// some actions
});
```

this code is not coupled with `requestPurchase` call

**Comment by mtnt** [comment]
so, is it possible to restore listening after reinit and resolve existing promise?

**Comment by andresesfm** [comment]
I don't think so. For the new init it would be as if the request never existed

**Comment by mtnt** [comment]
@andresesfm why did you close it? There is still an unfinished promise, it leads to unreachable code branches and memory leak. You can at least reject the promise

**Comment by andresesfm** [comment]
@mtnt You bring up a good point. I have created a PR to address such memory leaks: https://github.com/dooboolab/react-native-iap/pull/1910. I'm not sure it'll help in your particular case since the request will still be cancelled as soon as your app goes to the background but I agree this is a good practice

**Comment by andresesfm** [comment]
Released 10.0.3

**Comment by mtnt** [comment]
@andresesfm nice, so will the promise be rejected?

**Comment by mtnt** [comment]
Great) it`s enough for me, I will get purchase from the `purchaseUpdatedListener`
