### ISSUE TITLE
NativeException thrown on requestPurchase on android device/emulator 

### ISSUE THREAD

**Issue by hkeithk** [dooboolab/react-native-iap#1913]
**Description**

When requestPurchase is called on an android device/emulator, the play console billing dialog comes up, but app crashes. Took a look at the change logs and updated the parameters. Code sample: 

```

if (Platform.OS === 'android') {
      await requestPurchase({ sku: productId, obfuscatedAccountIdAndroid: user_id });
    }

```

**Expected Behavior**

Expected behavior is when the play store dialog opens when a productId is passed. No crash occurs. Clicking on the confirmation or '1-tap buy' will successfully process the purchase, and the purchaseListener should receive the purchase receipt. 

**Screenshots**

When calling requestPurchase, the android play store dialog opens, with the correct productId and details, but the app crashes with the error logs: 

![image](https://user-images.githubusercontent.com/22736937/187805286-2db3d36f-44d8-4d1f-a34b-2a4c36b034c4.png)

In some instances, we get no error logs, just the play store dialog
![image](https://user-images.githubusercontent.com/22736937/187801874-f74bb297-ccd3-4acb-bb5b-1e3262bd02f8.png)

**Environment:**

- react-native-iap: 10.0.1
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): Android emulator/device only. IOS works as expected

**To Reproduce**

1. Call getProducts to get an array of products from the store
2. Pass the productId into requestPurchase in the format ( {sku: productId, ...other params})
3. App crash (sorry if this is not very descriptive, let me know if this can give more context)

---

[Optional] **Additional Context**

Not sure if these error logs will be helpful, but pulled these out of sentry. 

```

java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:92) at com.facebook.react.bridge.JavaMethodWrapper$2.extractArgument(JavaMethodWrapper.java:46) at com.facebook.react.bridge.JavaMethodWrapper$2.extractArgument(JavaMethodWrapper.java:42) at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:356) at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:313) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) at java.lang.Thread.run(Thread.java:920)

```

```

in-app (exception of system takes precedence)
exception (ignored because this variant does not have a contributing stacktrace, but the system variant does)
stack-trace
frame (non app frame)
modulejava.lang.Thread
filename (module takes precedence)thread.java
functionrun
frame (non app frame)
modulecom.facebook.react.bridge.queue.MessageQueueThreadImpl$4
filename (module takes precedence)messagequeuethreadimpl.java
functionrun
frame (non app frame)
moduleandroid.os.Looper
filename (module takes precedence)looper.java
functionloop
frame (non app frame)
moduleandroid.os.Looper
filename (module takes precedence)looper.java
functionloopOnce
frame (non app frame)
modulecom.facebook.react.bridge.queue.MessageQueueThreadHandler
filename (module takes precedence)messagequeuethreadhandler.java
functiondispatchMessage
frame (non app frame)
moduleandroid.os.Handler
filename (module takes precedence)handler.java
functiondispatchMessage
frame (non app frame)
moduleandroid.os.Handler
filename (module takes precedence)handler.java
functionhandleCallback
frame (non app frame)
modulecom.facebook.react.bridge.queue.NativeRunnable
filename (module takes precedence)nativerunnable.java
functionrun
frame (non app frame)
modulecom.facebook.react.bridge.JavaModuleWrapper
filename (module takes precedence)javamodulewrapper.java
functioninvoke
frame (non app frame)
modulecom.facebook.react.bridge.JavaMethodWrapper
filename (module takes precedence)javamethodwrapper.java
functioninvoke
frame (non app frame)
modulecom.facebook.react.bridge.JavaMethodWrapper$2
filename (module takes precedence)javamethodwrapper.java
functionextractArgument
frame (non app frame)
modulecom.facebook.react.bridge.JavaMethodWrapper$2
filename (module takes precedence)javamethodwrapper.java
functionextractArgument
frame (non app frame)
modulecom.facebook.react.bridge.ReadableNativeArray
filename (module takes precedence)readablenativearray.java
functiongetDouble

collapse 11 similar
typeNullPointerException
valueAttempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

```

**Comment by andresesfm** [comment]
@hkeithk does it happen if you don't pass `obfuscatedAccountIdAndroid`?

**Comment by hkeithk** [comment]
@andresesfm when I remove the  `obfuscatedAccountIdAndroid` the behavior i see is the second screenshot. Google play dialog comes up, no error message, but still an app crash

**Comment by andresesfm** [comment]
@hkeithk I'm having a hard time reproducing this. I think it might be something in your app other than this library. Can you please try to reproduce using `IapExample`. I looked at places where `getDouble()` could be called but nothing looks out of place

**Comment by hkeithk** [comment]
Hey @andresesfm, thanks for your help. You were right - after some more digging it was not caused by react-native-iap. Apologies and thanks for your help. Closing the ticket now

**Comment by RenatoSerra22** [comment]
Hey @hkeithk  what was causing it for you?
Im having the exact same exception on request purchase and not sure what im doing wrong now, it was working fine before my upgrade

**Comment by hsource** [comment]
@RenatoSerra22 Sorry about that! I introduced a bug in the latest version. #2046 should fix it.

If you're in a rush, you can temporarily install a version with the fix by doing `yarn add wanderlog/react-native-iap#12.1.1-wanderlog.1` or just wait for the new fix to be released on npm

**Comment by RenatoSerra22** [comment]
thank you @hsource do you have an ETA more or less of when this will be released to npm?
Like hours, days, weeks? just for me to know which approach to pick :)
Thank you

**Comment by hsource** [comment]
You alternatively could just use the current version, but pass in `prorationModeAndroid: ProrationMode. UNKNOWN_SUBSCRIPTION_UPGRADE_DOWNGRADE_POLICY`, which probably just does nothing

**Comment by RenatoSerra22** [comment]
For now i've just done a patch-package till its live.
Thank you for telling me whats up :)

**Comment by andresesfm** [comment]
Update has been released

**Comment by RenatoSerra22** [comment]
thank you @andresesfm
