### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference

### ISSUE THREAD

**Issue by Kadir-prog** [dooboolab/react-native-iap#1915]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
when calling request purchase getting this error

**Expected Behavior**
should be display payment model

**Screenshots**
![screenshot-1662012194103](https://user-images.githubusercontent.com/80304501/187843193-a2a64011-b173-428d-9d38-57144704b73d.png)

**Environment:**

- react-native-iap: ^9.0.0-rc.4
- react-native:0.67.4
- Platforms Android,device:

**Comment by andresesfm** [comment]
@Kadir-prog 9.0.0-rc.4 was a prerelease build. Please use `[9.0.4](https://github.com/dooboolab/react-native-iap/releases/tag/9.0.4) or even better, use the new 10.x.x version

**Comment by Kadir-prog** [comment]
> @Kadir-prog 9.0.0-rc.4 was a prerelease build. Please use `[9.0.4](https://github.com/dooboolab/react-native-iap/releases/tag/9.0.4) or even better, use the new 10.x.x version

thanks @andresesfm its working thanks for your time

**Comment by achuinard** [comment]
I'm still getting this on Android using the `requestSubscription` hook:

```
  const { connected, subscriptions, getSubscriptions, requestSubscription } =
        useIAP();

    const buyProduct = useCallback(
        sku => {
            const sub = subscriptions.find(sub => sub.productId === sku);
            if (sub) {
                const data = {
                    subscriptionOffers: sub.subscriptionOfferDetails,
                    andDangerouslyFinishTransactionAutomaticallyIOS: true,
                };
                requestSubscription(data);
            }
        },
        [subscriptions, requestSubscription],
    );
```

Am I doing something wrong by chance?

**Comment by achuinard** [comment]
I believe it's this `val productParamsList = ...` line in the RNIapModule.kt. I modified it to add logging:

```
            Log.i(TAG, offerTokenArr.size().toString())
            Log.i(TAG, skuArr.size().toString())
            val productParamsList =
                skuArr.toArrayList().map { it.toString() }.mapIndexed { index, sku ->
```

They both logged size 1, then it crashes immediately after on (I believe) the `map { it.toString() }`

**Comment by andresesfm** [comment]
@achuinard what are the values you are passing?

**Comment by andresesfm** [comment]
Also @achuinard ```subscriptionOffers is not the same as sub.subscriptionOfferDetails ```  the types are different

**Comment by achuinard** [comment]
@andresesfm Thanks for getting back to me, I was passing `subscriptionOffers` from the first call which as you pointed out was wrong. I managed to get it working off one of your other examples.

**Comment by leo0grau** [comment]
@achuinard could you say how you fix it ?

**Comment by AmitRathee729** [comment]
> subscriptionOffers

@leo0grau, please cross-check check requestSubscription payload.

- offterToken is in subscriptionOfferDetails

`requestSubscription({
                sku: productId,
                ...(offerToken && {
                  subscriptionOffers: [
                    {
                      sku: productId,
                      offerToken: offerToken,
                    },
                  ],
                }),
              })`
              
 This worked for me, hope will for you too ✅
