### ISSUE TITLE
Undefined is not an object (evaluating 'purchase.transactionId')

### ISSUE THREAD

**Issue by MaxJadav** [dooboolab/react-native-iap#1916]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

When I call await finishTransaction(purchase); throw error in try catch block.
[TypeError: undefined is not an object (evaluating 'purchase.transactionId')]

**Expected Behavior**
Shuld not throw undefined error.

**Screenshots**

**Environment:**
Sandbox
- react-native-iap:"^10.0.3"
- react-native:"0.67.2"
- Platforms (iOS,real device):

**To Reproduce**

---

[Optional] **Additional Context**
```
this.purchaseUpdateSubscription = purchaseUpdatedListener((purchase: SubscriptionPurchase | ProductPurchase) => {
				console.log("purchaseUpdatedListener=====>")
				const receipt = purchase.transactionReceipt;
				console.log('purchase status : ', purchase)
				if (receipt) {
					try {
						await finishTransaction(purchase);
					} catch (error) {
						console.log("error=>", error)
					}
				}
			});
```

purchase status=> Log proper with _{ transactionDate: '1662030229000.0',
  transactionId: '2000000144097…’,
  transactionReceipt: 'MIJY+wYJKoZIhvcNAQcCoIJY7DCCWOgCAQExCzAJBgUrD….
productId: blablabla }_

When I call finishTransaction that throw error in catch block 'error=>', [TypeError: undefined is not an object (evaluating 'purchase.transactionId')]

**Comment by andresesfm** [comment]
try `finishTransaction({purchase})`

**Comment by dprajapati1179** [comment]
Hi @andresesfm,

I am using the latest version but, still unable to finish transaction on iOS getting TypeError: undefined is not an object (evaluating 'purchase.transactionId' when not sending params into object and undefied when sending into an object.

**Comment by andresesfm** [comment]
What's the exact version @dprajapati1179 ?
