### ISSUE TITLE
Crashing on android 

### ISSUE THREAD

**Issue by cakesoft-shashank** [dooboolab/react-native-iap#1917]
**Description**
Crashing on android when calling `initConnection().then`

**Screenshots**![Screenshot_20220901-182016.jpg](https://user-images.githubusercontent.com/50690016/187918060-3408c7e2-02f4-436a-97a4-04129fdbedaf.jpg)

**Environment:** android

- react-native-iap:10.0.3
- react-native:0.68.2
- Platforms (iOS, Android, emulator, simulator, device): android phone

**Comment by andresesfm** [comment]
try `getProducts({skus:....}`
