### ISSUE TITLE
Parameter specified as non-null is null:  parameter token

### ISSUE THREAD

**Issue by phongit1995** [dooboolab/react-native-iap#1920]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
App is crashing when running  
await requestPurchase({
              sku: productId
  });

Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter token

**Expected Behavior**

**Screenshots**
![302394450_778185016849443_8950993567380914766_n](https://user-images.githubusercontent.com/40308146/188034392-80371f9b-d625-4c4c-b4d2-dea96dab0bc6.jpg)

**Environment:**

- react-native-iap: 10.0.3
- react-native:0.63.4
- Platforms (iOS, Android, emulator, simulator, device): Android 10 

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
The crash is not happening when calling `requestPurchase` but when calling `finishTransaction` Please change the parameters fo finishTransaction with an object

**Comment by leo0grau** [comment]
i am with this error, when calling requestSubscription, any sollution ?

**Comment by sbulmahn** [comment]
Hi -- I have this exact same issue. Has anyone else found a solution for this?

**Comment by andresesfm** [comment]
Same version of the library? have you tried updating to the latest?

**Comment by andresesfm** [comment]
Did you follow the migration guides in the docs?

**Comment by sbulmahn** [comment]
Hi Andres – Yes, we did follow the implementation details that we found on the Git site.

 

Question: would this issue happen if we don’t yet have our application hosted in the Google Play store? We’re still doing implementation testing and haven’t yet posted it.

 

Thanks again for your help, and please advise

 

Regards,

Scott

**Comment by andresesfm** [comment]
You can only test Android IAP if the app is in the Play Store

**Comment by quocbaovu15101996** [comment]
I have the same issues. Any Idea?

**Comment by quocbaovu15101996** [comment]
I used version 8.0.4 a few days ago everything is ok. But today when I run yarn or npm install this error appears.
Change RNIap.requestSubscription(sku) -> to RNIap.requestSubscription({sku}) is working for me. Is there any explanation?

**Comment by andresesfm** [comment]
You must have updated it to 10.x.x + where that change was made

**Comment by skjangid** [comment]
Thanks @quocbaovu15101996 , it's working for me.
