### ISSUE TITLE
Documentation getSubscriptions parameters

### ISSUE THREAD

**Issue by basemanabulsi** [dooboolab/react-native-iap#1925]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

In documentation its saying: `getSubscriptions(skuArr)`, also in example `https://github.com/dooboolab/dooboolab.com/blob/main/src/components/pages/Sponsor.tsx` its saying the same. 

If we write it in the same way we will get an arror:

**Parameter specefied as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter skuArr**

After investigating and looking in the code I found it should be called as 
`getSubscriptions({skus:skuArr })`

**Expected Behavior**

Return subscriptions not an error

**Screenshots**

rniap code:

<img width="575" alt="Screen Shot 2022-09-05 at 10 57 36 PM" src="https://user-images.githubusercontent.com/14277303/188507531-74843675-c366-4887-b7b4-86b092561644.png">

rniap example: 
<img width="571" alt="Screen Shot 2022-09-05 at 10 51 56 PM" src="https://user-images.githubusercontent.com/14277303/188507556-94207713-ce18-4082-b977-eb6142d0df1d.png">

**Environment:**

- react-native-iap: 10.0.3
- react-native: 0.69.5 or 0.64 we tried both - its not related to react-native-version
- Platforms (iOS, Android, emulator, simulator, device): android, ios

**To Reproduce**

1. Call initConnection()
2. call getSubscriptions(skuArr)
3. After getting an error try: getSubscriptions({skus: skuArr})
4. 

---

[Optional] **Additional Context**

**Comment by basemanabulsi** [comment]
@linaia 
I got the offerToken from getSubscriptions, its returned from SDK
Also, the object has alot of changes in the latest versions. I have upgraded from V7.4 to V10 I faced those issues.

The issue I am currently facing is that the payment box after clicking on requestSubscription is not shown, I tried to debug the SDK but I could find anything yet.

I put this thread to help anyone faced issues while upgrading to the new version

<img width="643" alt="Screen Shot 2022-09-07 at 8 15 46 PM" src="https://user-images.githubusercontent.com/14277303/188939598-bc6aa1a7-6d09-46f9-9cf4-d79e243dc27b.png">

**Comment by basemanabulsi** [comment]
After multiple tried with requestSubscriptions and digging into RNIAP package I found it.

the sku is optional in android, you only have to send subscriptionOffers which contains array of objects each object consists of sku and offerToken

I append the method in the screenshot, maybe someone will save time while requesting it.

<img width="442" alt="Screen Shot 2022-09-07 at 10 11 40 PM" src="https://user-images.githubusercontent.com/14277303/188958784-5011e3a0-fd3d-470b-8423-e026839d0998.png">

**Comment by vietMaiExe** [comment]
that's exactly what I found. The documentation looks incorrect with the getSubscriptions and getProducts method. Regarding to the declared types, these 2 methods are accepting an object with skus as a key instead of an array with skus. 
<img width="812" alt="Screen Shot 2022-09-08 at 21 39 01" src="https://user-images.githubusercontent.com/96100244/189151236-6b54a6e8-7201-403f-9428-0e3f7c0a5cec.png">

**Comment by andresesfm** [comment]
That is correct, thank you @basemanabulsi @vietMaiExe
