### ISSUE TITLE
10.0.x releases throwing IAP_NOT_AVAILABLE error in tests

### ISSUE THREAD

**Issue by huanvu** [dooboolab/react-native-iap#1930]
**Description**

10.0.x releases throwing IAP_NOT_AVAILABLE error in tests

**Expected Behavior**

You should be able to stub/mock library as normally.

**Environment:**

- react-native-iap: 10.0.5
- react-native: 0.64.2
- Platforms (iOS, Android, emulator, simulator, device): local (mac)

**To Reproduce**

1. Write test where react-native-iap is imported at any some point.
2. Run test
3. See IAP_NOT_AVAILABLE thrown.

Looks like since eventEmitter is instantiated right away with getNativeModule() upon import, it will always throw an error before any mocking/stubbing can be done.

**Comment by andresesfm** [comment]
Proposed fix: https://github.com/dooboolab/react-native-iap/pull/1932.

**Comment by andresesfm** [comment]
Released on 10.0.7

**Comment by huanvu** [comment]
Thank you @andresesfm for the super quick turnaround!
