### ISSUE TITLE
Help in Android subscription downgrade with DEFERRED mode

### ISSUE THREAD

**Issue by JameDodgers** [dooboolab/react-native-iap#1936]
Hello there,

Could you guys help me to understand what exactly should I do when trying to perform a subscription downgrade on Android? Currently when I call `requestSubscription()` with `ProrationModesAndroid.DEFERRED` my listener gives me the same purchase object that I'm downgrading from. If I try to call `finishTransaction()` upon that purchase it gives me the error _"purchase is not suitable to be purchased"_.

**Expected Behavior**

Based on the discussions in https://github.com/dooboolab/react-native-iap/issues/888, I believe that the value returned in `currentPurchase` would be null and I wouldn't need to handle it because the subscription change will be notified to my backend serve by the real-time developer notifications.

Thanks in advance.

**Environment:**

- react-native-iap: 9.0.4
- react-native: 0.66.4

**Comment by andresesfm** [comment]
Correct, you can't finish that transaction on the client. Your backend will get the update and you have to acknowledge it there

**Comment by JameDodgers** [comment]
But what should I do with the `currentPurchase`? Keep spamming my backend server with it? As my backend will receive the notification when the billing period ends, is there a way to know if a purchase is in this state to prevent sending it to my backend? Sorry if I was not clear
