### ISSUE TITLE
App title included in product title

### ISSUE THREAD

**Issue by dawidvdh** [dooboolab/react-native-iap#194]
### Platforms you faced the error (IOS or Android or both?)

Android, I have not yet tested iOS

### Expected behavior

`title` property in products returned from `RNIap.getProducts` should be the same as the title set in the store.

### Actual behavior

`title` property is set as the title in the store with the addition of the App name in parentheses, like so `Some Product Title (App Name)`.

### Tested environment (Emulator? Real Device?)

Test on real Android Device.

### Steps to reproduce the behavior

calling `RNIap.getProducts` will return `Some Product Title (App Name)`.

**Comment by mul1sh** [comment]
Getting this same behavior in android, any help or can I do a pr to fix this?

Thanks

**Comment by mradzinski** [comment]
@dooboolab This is totally the expected behavior and the same provided by Google's `BillingClient` if used natively, so nothing you can do about it.

**Comment by dooboolab** [comment]
@mradzinski Thank you for your update. Then, I will close this issue for now.

**Comment by AdamGerthel** [comment]
Is there no way to get just the title without the app name in parenthesis? Is everyone else manually removing that part of the string? Seems like an ugly workaround for something that could be included in rn-iap, no?
