### ISSUE TITLE
react-native-iap 10.1.0 doens't work with new React Native 0.70

### ISSUE THREAD

**Issue by joaotmachado** [dooboolab/react-native-iap#1940]
**Description**

iOS: Eternal loading when purchase is requested.
Android: Crash when opening the purchase screen.

**Expected Behavior**

The paywall to show after purchase is requested.

**Screenshots**

iOS:
<img width="425" alt="Screen Shot 2022-09-09 at 10 37 52" src="https://user-images.githubusercontent.com/65225461/189363026-a4a9379d-50ae-4c08-b64b-db73cd6ff6b3.png">

Android:
<img width="339" alt="Screen Shot 2022-09-09 at 10 29 06" src="https://user-images.githubusercontent.com/65225461/189362004-33cd6965-5457-4342-9ecc-71503ad33574.png">

**Environment:**

- react-native-iap: 10.1.0
- react-native: 0.70
- Platforms: iOS (device and simulator), Android (device and simulator)

**To Reproduce**

1. Upgrade React Native 0.69.5 to 0.70.
2. yarn add react-native-iap version 10.1.0
3. Go to the purchase screen.
4. Try to subscribe (iOS. Android crashes on step 3).

**Comment by andresesfm** [comment]
Hello, the request parameters have changed as of 10.0.0. Please pass an object with the parameters. Reopen if any other issues

**Comment by andresesfm** [comment]
Addeed: https://react-native-iap.dooboolab.com/docs/migrate_to_10.x.x for quick reference

**Comment by joaotmachado** [comment]
> Addeed: https://react-native-iap.dooboolab.com/docs/migrate_to_10.x.x for quick reference

it worked @andresesfm ! 

But on android im getting : Possible Unhandled Promise Rejection (id: 0):
"subscriptionOffers are required for Google Play Subscriptions"

do you have a clue?

**Comment by andresesfm** [comment]
Described in documentation
https://react-native-iap.dooboolab.com/docs/guides/purchases
