### ISSUE TITLE
Return an JSON parse error

### ISSUE THREAD

**Issue by wasedaigo** [dooboolab/react-native-iap#195]
I got a report from a customer that she does not seem to be able to restore her items correctly. I am suspecting something is failing during the JSON parse of BillingResponse. (for example, if orderID is missing, this would fail) I want to catch this error and throw it to Crashlytics.

Another approach is instead of returning an error, keep an empty field empty instead of relying on GetString() to raise an error. Basically, we should check each field to see whether it exists. This approach is safer and give more control to devs.

What do you think?

https://github.com/dooboolab/react-native-iap/pull/196

**Comment by dooboolab** [comment]
Merged just now.
