### ISSUE TITLE
getSubscriptions gives different results when developing locally versus Google Play Store build

### ISSUE THREAD

**Issue by TomNes94** [dooboolab/react-native-iap#1952]
**Description**

Using getSubscriptions on Android does not fetch old style introductory offers. The element that should contain both the normal price and the introductory offer is missing.  It does work for newly created introductory offers. This does however only occur when using the app from internal testing (have not tried production app for obvious reasons). Running the app locally (debug and release variants) does fetch all data.

**Expected Behavior**

When calling getSubscriptions on Android, the subscriptionOfferDetails contains two objects: for just the regular pricing, which has a pricingPhaseList that contains the regular pricing object. The second object contains a pricingPhaseList which contains information for both regular pricing as well as the introductory offer.
**Screenshots**

What is fetched in the internal testing build:
![Screenshot 2022-09-12 at 18 23 49](https://user-images.githubusercontent.com/31142262/189706148-8dc607a3-aa4b-4209-905d-46d3d6f9f712.png)

What is fetched locally:
![Screenshot 2022-09-12 at 18 23 59](https://user-images.githubusercontent.com/31142262/189706151-23199216-e3b3-44fa-999d-6ddbbf098f78.png)

**Environment:**

- react-native-iap: 10.1.0
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): Android, internal

**Comment by andresesfm** [comment]
@TomNes94 I don't think this is a bug in the library. Most likely you are using different skus for testing. Please reopen if otherwise

**Comment by TomNes94** [comment]
I did some more testing, and it is indeed not a bug in the library. The Google Play Billing Library v5 will not send subscriptionOfferDetails of introductory offers a user is not eligible for anymore, while the previous version did.

**Comment by andresesfm** [comment]
Thank you for the info @TomNes94

**Comment by BogdanDemeny** [comment]
I'm having this issue/case while using a testing account. Do you know if I can reset the purchase history so I can test introductory offers using the same account?

**Comment by andresesfm** [comment]
Not to my knowdlegde
