### ISSUE TITLE
v10: Inconsistencies in products/subscriptions returned from getProducts and getSubscriptions across iOS & Android

### ISSUE THREAD

**Issue by goguda** [dooboolab/react-native-iap#1953]
Trying to upgrade to v10 from 8.6.7. The documented API changes have been implemented, and the implementation continues to work just fine on iOS.

But, it appears that the structure of the products/subscriptions being returned on Android has _completely_ changed unexpectedly compared to what is returned on iOS and this does not appear to be documented.

For example, take the following product returned from getProducts() and its values, which returns like this on iOS (and used to return the same object structure on Android in v <= 8.6.7):

```
{
   "countryCode":"CAN",
   "currency":"CAD",
   "description":"Description for product X",
   "discounts":[
   ],
   "introductoryPrice":"",
   "introductoryPriceAsAmountIOS":"",
   "introductoryPriceNumberOfPeriodsIOS":"",
   "introductoryPricePaymentModeIOS":"",
   "introductoryPriceSubscriptionPeriodIOS":"",
   "localizedPrice":"$27.99",
   "price":"27.99",
   "productId":"com.product.productX",
   "subscriptionPeriodNumberIOS":"0",
   "subscriptionPeriodUnitIOS":"",
   "title":"Product X",
   "type":"iap"
}
```

Now, in the newer version the same product returned from getProducts() on Android is being returned as:

```
{
   "description":"Description for product X",
   "name":"Product X",
   "oneTimePurchaseOfferDetails":{
      "formattedPrice":"$25.99",
      "priceAmountMicros":"25990000",
      "priceCurrencyCode":"CAD"
   },
   "productId":"com.product.productX",
   "productType":"inapp",
   "title":"Product X"
}
```

but still the old version is returned on iOS.

A similar change has been made to the products returned from getSubscriptions() as well, with a lot of the properties of the subscription having been moved inside a key named _subscriptionOfferDetails_ on Android, but these values being present in the first level of the object on iOS.

While the prior (and familiar) format is still being returned on iOS, why the sudden inconsistencies in what is being returned on Android? Why have values such as _formattedPrice_ been moved inside of _oneTimePurchaseOfferDetails_ on Android, but not on iOS? Why is _localizedPrice_ suddenly _formattedPrice_ on Android? Why is this critical breaking change not documented anywhere?

This change should either be reversed, or implemented the same way across iOS and Android as it was before. Having the returned products structured differently across separate platforms like this is really unnecessary and just adds confusion/makes for spaghetti code with unnecessary if statements to handle different platforms.

**Comment by andresesfm** [comment]
@goguda Starting on version 9. Android was migrated to use the latest Billing v5 which provides a different API. In particular handles subscriptions very differently. I'm working on updating iOS in the new rn-iap version 11.0.0 (currently in beta). Once you've done the integration I'm open to see your concrete suggestions on how to unify both interfaces

**Comment by goguda** [comment]
> @goguda Starting on version 9. Android was migrated to use the latest Billing v5 which provides a different API. In particular handles subscriptions very differently. I'm working on updating iOS in the new rn-iap version 11.0.0 (currently in beta). Once you've done the integration I'm open to see your concrete suggestions on how to unify both interfaces

Makes sense, thanks for the quick reply. I'd be interested in playing around with v11 to see what changes get made for iOS. I think after those changes are made, from there we could look at which values are similar between iOS and Android and consolidate the API from there for v12.
