### ISSUE TITLE
Crash Android app – java.lang.NoSuchMethodError: No virtual method queryPurchase

### ISSUE THREAD

**Issue by whyamsx** [dooboolab/react-native-iap#1957]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

I followed all the steps to install the module, but when I try to open my application, it immediately closes with an error:
`java.lang.NoSuchMethodError: No virtual method queryPurchases(Ljava/lang/String;)Lcom/android/billingclient/api/Purchase$PurchasesResult; in class Lcom/android/billingclient/api/BillingClient; or its super classes (declaration of 'com.android.billingclient.api.BillingClient' appears in /data/app/~~FoR8L1AMXFFXmbdRD_fM2g==/com.myapp-xM5XOFzRKtJr5CCRKb25hA==/base.apk)`

I tried integration for AndroidX, also without it - all to no avail.

**Environment:**

- react-native-iap: 9.0.4 and 10+
- react-native: 0.63.3
- Platforms (iOS, Android, emulator, simulator, device): Android

**To Reproduce**

1. Just follow the entire installation process, which is described in the [documentation](https://react-native-iap.dooboolab.com/docs/get-started#installation) and run in Android.
2. Error is shown: `java.lang.NoSuchMethodError: No virtual method queryPurchases(Ljava/lang/String;)Lcom/android/billingclient/api/Purchase$PurchasesResult; in class Lcom/android/billingclient/api/BillingClient; or its super classes (declaration of 'com.android.billingclient.api.BillingClient' appears in /data/app/~~FoR8L1AMXFFXmbdRD_fM2g==/com.myapp-xM5XOFzRKtJr5CCRKb25hA==/base.apk)`

**Comment by iamkunall** [comment]
Hi @whyamsx please update your react native version according to the required react native version for IAP.

**Comment by whyamsx** [comment]
> Hi @whyamsx please update your react native version according to the required react native version for IAP.

Yes, I came to the conclusion that this was the problem
But I can't update the version because it will break my project, so I just rolled back the module version and it worked for me
