### ISSUE TITLE
Unable to auto-initialize connection

### ISSUE THREAD

**Issue by mujuappsile** [dooboolab/react-native-iap#1958]
![image](https://user-images.githubusercontent.com/113532312/190178469-8fbe2d61-41f9-43c6-b374-aac4765fe201.png)
There is issue init connection

**Comment by andresesfm** [comment]
Please use the issue template.

**Comment by mujuappsile** [comment]
@andresesfm did't found about it...

**Comment by andresesfm** [comment]
When you create a new issue, select Bug report and fill out all the required info

**Comment by SergiOnGit** [comment]
@mujuappsile How did you solve it?

**Comment by mujuappsile** [comment]
@SergiOnGit did you used endConnection method ? if you used this then removed it

**Comment by SergiOnGit** [comment]
@mujuappsile Yeah removing endConnection helped. Thank you.
