### ISSUE TITLE
getAvailablePurchases() does not resolve in iOS 16

### ISSUE THREAD

**Issue by tharwi** [dooboolab/react-native-iap#1961]
**Description**

getAvailablePurchases() does not resolve in iOS 16. Checked with both iOS 15.5, and 15.6 devices. The response is returning as expected. But on iOS 16 device it doesn't return anything.

**Expected Behavior**

getAvailablePurchases() should return a success or error response

**Environment:**

- react-native-iap: 7.2.1
- react-native: 0.63.4
- Platforms (iOS, Android, emulator, simulator, device): iPhone SE device

**Comment by andresesfm** [comment]
Please help us test the pre-release versions of 11.0.0. Its main purpose is to use Storekit 2 that focuses on iOS 15 environments

**Comment by andresesfm** [comment]
Please reopen if it still happens on 11.x.x

**Comment by TaylorPringleNZME** [comment]
@andresesfm Do you have any options for version 10? 

We are currently experiencing this issue in development and TestFlight builds but production is fine.

**Comment by andresesfm** [comment]
@TaylorPringleNZME Please create a new ticket with more detail. I think the latest 10.x fixed an issue related to this, but otherwise, I'll need more detail to understand your issue. Also, please consider contributing to the project

**Comment by kayro2222** [comment]
hey @andresesfm, i'm facing this problem with `11.0.5`. It's a very inconsistent error, due to I have the promise being resolved with my physical device (Iphone 13 iOS 16) with the version 10.0.1 with a Testflight build. When I upgrade to `11.0.5`, I also have being experience this error on simulators.

Here's my code:

```
if (Platform.OS === 'ios') {
        const connected = await initConnection()

        initConnection().then(async (connected) => {
         if(connected){
             const purchases = await getAvailablePurchases()
          console.log('purchases', purchases)
          const sortedPurchases = purchases.sort(
            (a, b) => b.transactionDate - a.transactionDate,
          )
          const latestReceipt = sortedPurchases?.[0]?.transactionReceipt

          if (latestReceipt) {
            const decodedReceipt = await validateReceiptIos({
              receiptBody: {
                'receipt-data': latestReceipt,
                password: process.env.ITUNES_CONNECT_SECRET,
              },
              isTest:
                process.env.IS_ITUNES_PRODUCTION === 'false' ? true : false,
            })

            const { latest_receipt_info } = decodedReceipt
            const isSubValid = !!latest_receipt_info?.find(
              (receipt: Record<string, unknown>) => {
                const nowInMilliseconds = Date.now()
                const expirationInMilliseconds = Number(receipt.expires_date_ms)

                return expirationInMilliseconds > nowInMilliseconds
              },
            )

            return isSubValid
          }
         }

          return false
}
      
useEffect(() => {
    const checkSubscribeActive = async () => {
      setIsSubscribe(await handleGetPurchaseHistory())
    }
    checkSubscribeActive()
}, [])
```

**Comment by andresesfm** [comment]
@kayro2222 please consider using Storekit 2. It's described in the migration guide to 11.0.0

**Comment by noumantahir** [comment]
Facing similar issue with `react-native-iap 12.4.2` , For me `getProducts({skus})` never resolves. 
Using StoreKit2 is perhaps not an option since `platform :ios` has to be set to `15.0` or above for that while we are stilling supporting prior versions as well.

**Comment by andresesfm** [comment]
@noumantahir try `12.4.4`. If the skus array was empty, Android crashed and iOS would not resolve. Now it validates and rejects if that's the case
