### ISSUE TITLE
iOS crash: RNIapIos.getPurchaseData takes up more than 1 GB of memory

### ISSUE THREAD

**Issue by YaoHuiJi** [dooboolab/react-native-iap#1969]
**Description**

After upgrading from 7.5.3 to 10.1.0, my app crashes everytime in half a minute after startup

> Failure Reason: Message from debugger: Terminated due to memory issue

In the Console log, I found the app crashed after hundreds of 

> "New transaction added to queue <SKPaymentTransaction: 0x280342fb0>"

and with hundreds of

> [react-native-iap] Purchase Successful
> [react-native-iap] requestReceiptDataWithBlock with force refresh: NO

in the xcode console

here is the Instruments screenshot

<img width="923" alt="截屏2022-09-18 17 38 11" src="https://user-images.githubusercontent.com/741543/190896171-1d818901-c515-4fa6-8fb7-1d276e2ac255.png">

As you can see in the screenshot, it take up too many memory, it looks suspicious, but sorry, I'm not familiar with swift and RNIap, so I can't tell the reason for it in a short time. I'll have a try, but I wonder if @andresesfm or @jeremybarbet can take a quick look and see if you can see the answer directly?

**To Reproduce**
you need an sandbox account with a lot of past purchases, I think it is the key, you can't reproduce this issue with a new account, but it's 100% chance for an account with a lot of past purchases.

**Environment:**

- react-native-iap: 10.1.0
- react-native: 0.66.0
- Platforms (iOS, Android, emulator, simulator, device): iOS real device

**Comment by YaoHuiJi** [comment]
take one of these tests, for example, in 8 seconds more than 9000 object(size 112kb~656kb) is created, and then app is killed by os, most of these object is about receipt data

after commenting out some code related to receipt Data, the app will still get a memory warning, but it will not be killed. Again, I am not familiar with both Swift and native development. I just wonder if receipt data is stored in several large collections at the same time, so if the sandbox account has too many historical transactions, with an influx of receipt data, so that these collections occupy a huge of memory in an instant, leading to the app being killed by the system?

I still don't know how to fix it😫, I am afraid to release a new version with this issue now, I think I may have to go back to 7.5.3 first

**Comment by YaoHuiJi** [comment]
There probably won't be hundreds of subscriptions in the actual account, so maybe it will probably only affect Test Flight users, whose sandbox accounts, as far as I know, can't clear its purchase history. I guess I can never use my own Apple Id to test my beta version app in Test Flight from now on.

Or, does anyone know how to clear the purchase history of their Test Flight sandbox account with their Apple Id?  I only know how to clear purchase history. of normal sandbox account

**Comment by andresesfm** [comment]
@YaoHuiJi this is a common complaint. As you have mentioned, this happens when you use the same account to test on sandbox. I've seen some SO posts where the suggestion is to use new accounts every time

**Comment by andresesfm** [comment]
For reference: https://stackoverflow.com/questions/7747457/clearing-purchases-from-ios-in-app-purchase-sandbox-for-a-test-user

**Comment by YaoHuiJi** [comment]
> For reference: https://stackoverflow.com/questions/7747457/clearing-purchases-from-ios-in-app-purchase-sandbox-for-a-test-user

thank you for your reply, maybe I didn't make it clear, I already know how to clear the purchase history of an ordinary sandbox account, I mean the sandbox account of Test Flight, this sandbox account is different from the sandbox account of development mode, you can't find it in Connect and clear its purchase history, it is the same real account as the Apple Store account.

**Comment by YaoHuiJi** [comment]
> @YaoHuiJi this is a common complaint. As you have mentioned, this happens when you use the same account to test on sandbox. I've seen some SO posts where the suggestion is to use new accounts every time

thank you, I'm not familiar with native development, I think a lot of React Native developers aren't, either. It would have been nice if there had been a hint in the document "Frequently Asked Questions."
