### ISSUE TITLE
Didn't get restore item in ios

### ISSUE THREAD

**Issue by Ashi90** [dooboolab/react-native-iap#197]
Hello All,
I'm using inApp Purchase in one of my App for both iOS  and Android, and I've successfully bought an item using this library. But when I go to restore purchase it returns me multiple items in the Array. So please let me know how can I found my product.

**Comment by JJMoon** [comment]
@Ashi90 Restore item recovers already bought items of non-consumable products.
Would you make a new sandbox tester and process with it again?
How many non-consumable products are there in your app?
