### ISSUE TITLE
getSubscriptions return empty array.

### ISSUE THREAD

**Issue by mdrazu24** [dooboolab/react-native-iap#1970]
getProduct api is working just fine but when I'm trying  getSubscription api it's returning empty array. I've tried several version of this package and currently I'm on 11.0.0-rc.2

    "react-native-iap": "11.0.0-rc.2",
    "react-native": "0.69.5",
    "react": "18.0.0",
    "expo": "~46.0.9",

here's the code :
 const items = Platform.select({
    ios: [],
    android: ["monthly_big_20"], //testing subscription item
  })
const subscribe = async (sku, offerToken) => {
    const results = await RNIap.getSubscriptions({ skus: items })
    console.log(results)
}

![image](https://user-images.githubusercontent.com/41054947/190926862-1aac9157-e3ea-4314-b216-c7b4e7dfe749.png)
this is the overview of my plans. Please let me know if I'm doing anything wrong here or what's the available fixes.

**Comment by andresesfm** [comment]
@mdrazu24  Can you please confirm if this is happening on 10.x.x? It could be a regression bug on 11 RC

**Comment by mdrazu24** [comment]
> @mdrazu24 Can you please confirm if this is happening on 10.x.x? It could be a regression bug on 11 RC

Yes I'm getting the same error with 10.x.x. I was gtting the product list succesfully but the subscription list did not work. I was suspicious of declaration of my subscription list. But It seems alright.

**Comment by nguyen95** [comment]
Same issue

**Comment by mdrazu24** [comment]
It's still the same. I'm waiting to hear from any of the collaborator

**Comment by nguyen95** [comment]
Oh sorry, in my case, getSubscriptions return data but data dont have "price" param (or empty). Show i must get price from subscriptionOfferDetails.

**Comment by nguyen95** [comment]
My code same with you. But i cannot open console right now. Waiting for tomorrow, i can get it for you.

**Comment by nguyen95** [comment]
<img width="497" alt="Screen Shot 2022-09-21 at 00 10 36" src="https://user-images.githubusercontent.com/36287542/191321728-370030e6-01f8-444f-89e4-ad06a2f93665.png">

**Comment by mdrazu24** [comment]
Thanks bro

**Comment by asRizvi888** [comment]
> <img alt="Screen Shot 2022-09-21 at 00 10 36" width="497" src="https://user-images.githubusercontent.com/36287542/191321728-370030e6-01f8-444f-89e4-ad06a2f93665.png">

is it working???

**Comment by furkanndemirr** [comment]
yapabilen varmı

**Comment by furkanndemirr** [comment]
> getProduct api is working just fine but when I'm trying getSubscription api it's returning empty array. I've tried several version of this package and currently I'm on 11.0.0-rc.2
> 
> ```
> "react-native-iap": "11.0.0-rc.2",
> "react-native": "0.69.5",
> "react": "18.0.0",
> "expo": "~46.0.9",
> ```
> 
> here's the code : const items = Platform.select({ ios: [], android: ["monthly_big_20"], //testing subscription item }) const subscribe = async (sku, offerToken) => { const results = await RNIap.getSubscriptions({ skus: items }) console.log(results) }
> 
> ![image](https://user-images.githubusercontent.com/41054947/190926862-1aac9157-e3ea-4314-b216-c7b4e7dfe749.png) this is the overview of my plans. Please let me know if I'm doing anything wrong here or what's the available fixes.

did you find the solution

**Comment by mayankVerma96** [comment]
you have to enter the ID's of you subscription, your plan and your offer in the SKU array

const items = await getSubscriptions({
        skus: [
          "com..subscription",
          "access-plan",
          "offer-3-days",
        ],
      });

**Comment by evegkm** [comment]
> you have to enter the ID's of you subscription, your plan and your offer in the SKU array
> 
> ```
> const items = await getSubscriptions({
>         skus: [
>           "com..subscription",
>           "access-plan",
>           "offer-3-days",
>         ],
>       });
> ```

I tried that, and by structuring it that way, it finally returned something, but the product ID and description. I have this in my constants:

import { Platform } from 'react-native';

export const subscriptionSkus = Platform.select({
ios: ['monthly-premium-plant1', 'annual-premium-plant1'],
android: ['premium_plan', 'monthly-premium-plant1','free-trialt1'],
default: [],
});
I have this in the code on my subscription extraction screen:
import {subscriptionSkus} from "../constants/constants";

import {
initConnection,
getSubscriptions,
endConnection,
} from "react-native-iap";

function SubscriptionStatusScreen({ navigation }) { 
const [subscriptions, setSubscriptions] = useState([]); 
const [loading, setLoading] = useState(true); 

useEffect(() => { 
const initIAP = async () => { 
try { 
const result = await initConnection(); 
console.log("IAP initialized:", result); 
console.log("Searching for SKUs:", subscriptionSkus); 
const subs = await getSubscriptions({ skus: subscriptionSkus }); 
console.log("Subs:", JSON.stringify(subs, null, 2)); 
setSubscriptions(subs); 
} catch (error) { 
console.warn("Error initializing IAP:", error); 
} finally { 
setLoading(false); 
} 
}; 

initIAP(); 

return () => { 
endConnection(); 
}; 
}, []);
my subscriptions are structured like this 

![Image](https://github.com/user-attachments/assets/86deae0e-0405-4390-9d24-5399a4e03bdc) , additional details 
"react-native-iap": "^12.16.2",
"react-native": "0.76.9",
"react": "18.3.1",
"expo": "~52.0.38", 
I want to get the data from monthly-premium-plan 1, can you help? It only returns the data from premium_plan itself.
