### ISSUE TITLE
[ANDROID] Price and currency params return empty value

### ISSUE THREAD

**Issue by nguyen95** [dooboolab/react-native-iap#1978]
**Description**

Price and currency params return empty value. So i must get these information from offerDetail

**Expected Behavior**

Price and currency params return string value

**Environment:**

- react-native-iap: 10.0.0
- Platforms (iOS, Android, emulator, simulator, device): Android

**Comment by andresesfm** [comment]
What is your proposal to handle onetime and subscription offers in that case @nguyen95 ?

**Comment by nguyen95** [comment]
I'm clear the response data in api 5.0. So I will close this issue. Thank you
