### ISSUE TITLE
[SOLVED] RNIap.getSubscriptions error :  [TypeError: undefined is not an object (evaluating 'RNIapIos.getItems')]

### ISSUE THREAD

**Issue by lc3t35** [dooboolab/react-native-iap#198]
### Version of react-native-iap
1.20

### Platforms you faced the error (IOS or Android or both?)
tested on iOS only

### Expected behavior
get list of subscriptions

### Actual behavior
RNIap.getSubscriptions error :  [TypeError: undefined is not an object (evaluating 'RNIapIos.getItems')]

### Tested environment (Emulator? Real Device?)
both

### Steps to reproduce the behavior

````
const itemSkus = Platform.select({
  ios: [
    'com.shares.sharesapp',                     // I also tried ['BASIC', 'CLASSIC', 'MAX', 'PLUS'] ..
  ],
  android: [
    'com.shares.sharesapp',
  ],
});

async componentDidMount() {
    try {
      await RNIap.prepare();
    }
    catch (err1) {
      console.log("RNIap.prepare error : ", err1);
    }
    finally {
      console.log("finally");
      try {
        const products = await RNIap.getSubscriptions(itemSkus);
        console.log('Subscriptions', products);
      }
      catch (err) {
        console.log("RNIap.getSubscriptions error : ", err);
      }
    }
  }
````
I not able to connect with sandbox account in simulator 
![capture d ecran 2018-06-20 a 15 37 42](https://user-images.githubusercontent.com/921372/41706853-1719016e-753d-11e8-9016-c82ec1bc1e2a.png)

and in real device, having these popup
![photo](https://user-images.githubusercontent.com/921372/41706885-2c3be17e-753d-11e8-8103-4f8339a8d25b.jpg)

Here is the list of subscriptions in App Store Connect
![capture d ecran 2018-06-20 a 12 42 30](https://user-images.githubusercontent.com/921372/41707383-467b8dd6-753e-11e8-8be9-5ded134d240b.png)

Can someone please help me to setup this in good shape ?

**Comment by lc3t35** [comment]
I had to manually install as described...
````
Manual installation
iOS

    In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
    Go to node_modules ➜ react-native-iap and add RNIap.xcodeproj
    In XCode, in the project navigator, select your project. Add libRNIap.a to your project's Build Phases ➜ Link Binary With Libraries
    Run your project (Cmd+R)
````

**Comment by lc3t35** [comment]
This time after it ask me to connect (disconnect on your real device first), I was able to grab the subscription detail 
````
itemSkus :  Array [
  "com.shares.sharesapp.basic",
 ]
 Subscriptions Array [
  Object {
     "currency": "EUR",
     "description": "***",
     "localizedPrice": "3,99 €",
     "price": "3.99",
     "productId": "com.shares.sharesapp.basic",
     "title": "Abonnement BASIQUE",
     "type": "Do not use this. It returned sub only before",
   },
 ]````

**Comment by lc3t35** [comment]
FYI, RNIap.getSubscriptions(itemSkus) works also in simulator.

**Comment by gurmanpsingh** [comment]
In 2022, the products fetch like:
// simple productIDs without bundle identifier.
let allSkus={
          skus:[
          'productID1',
          'productID2',
        ]
      }
      
      RNIap.getSubscriptions(allSkus); // to fetch the products
      RNIap.requestSubscription({sku:'productID1'}) // to request the subscription.
