### ISSUE TITLE
Access Free Trial Phase on Android Subscriptions

### ISSUE THREAD

**Issue by junedomingo** [dooboolab/react-native-iap#1981]
**Description**

In the previous version (8.0.8), we can access free trial period via `subscription.freeTrialPeriodAndroid`. 
Is there a way to access it on the new version (10.1.3)?

This is the result of the new version
```js
{
  "subscriptionOfferDetails": [{
    "pricingPhases": {
      "pricingPhaseList": [{
        "recurrenceMode": 1,
        "priceAmountMicros": "1234000000",
        "billingCycleCount": 0,
        "billingPeriod": "P1Y",
        "priceCurrencyCode": "PHP",
        "formattedPrice": "₱1,234.00"
      }]
    },
    "offerTags": [],
    "offerToken": "TOKEN_STRINGS"
  }],
  "name": "Sub Yearly",
  "productType": "subs",
  "description": "Yearly Subscription",
  "title": "Subs Yearly Title",
  "productId": "sub_yearly"
}
```

Or did I miss something?

**Expected Behavior**

Able to get free trial period on android

**Environment:**

- react-native-iap: 10.1.3
- react-native: 0.67.4
- Platforms (iOS, Android, emulator, simulator, device): Android

**Comment by andresesfm** [comment]
@junedomingo You only get it if the user is elegible.

**Comment by junedomingo** [comment]
Hi @andresesfm , thanks for all the hard work here! 

So I switched to another Google account (to be eligible), and there's a new `Free` pricingPhase obj.
Unlike in the old version, you can access the `freeTrialPeriodAndroid` value (to show it in the UI) even if your account is no longer eligible for a Free trial but it makes more sense now.
