### ISSUE TITLE
getAvailablePurchases returns correct data only once on iOS

### ISSUE THREAD

**Issue by vvodicka** [dooboolab/react-native-iap#1987]
**Description**

Docs for `getAvailablePurchases` says, it shall return "all purchases made by the user (either non-consumable, or haven't been consumed yet)". If I use it to get not-yet-consumed consumables, it returns correct data only once. Then it returns empty array till I make another purchase. `currentPurchase` is still set correctly during this behaviour. Above description applies also to `getPurchaseHistory`

Example:
```
import {getAvailablePurchases, requestPurchase, useIAP} from 'react-native-iap'

const {currentPurchase} = useIAP()

//purchase created with this call some time ago (currentPurchase exists) :
await requestPurchase({
          obfuscatedAccountIdAndroid: me?.userId,
          obfuscatedProfileIdAndroid: me?.userId,
          sku: selectedProductId,
          andDangerouslyFinishTransactionAutomaticallyIOS: false,
          applicationUsername: me?.userId,
        })

const logPurchases = async () => {
      const ap = await getAvailablePurchases()
      console.log('after 1st', ap)
      const ap2 = await getAvailablePurchases()
      console.log('after 2nd', ap2)
  }

<Button
        title={'logPurchases'}
        onPress={() => {
          logPurchases()
        }}
      />
```

**Actual Behavior**

console log after `logPurchases` button press:
`after 1st  [{"productId": "com...]`
`after 2nd  [ ]`

**Expected Behavior**

console log after `logPurchases` button press:
`after 1st  [{"productId": "com...]`
`after 2nd  [{"productId": "com...]`

**Environment:**

- react-native-iap: 10.1.3
- react-native: 0.67.4
- Platforms (iOS, Android, emulator, simulator, device): iOS device
- iOS: 16.0
- XCODE: 14.0

**To Reproduce**

See example

**Comment by andresesfm** [comment]
The reason for this is that the restore transactions are marked as finished as soon as `getAvaiableItems` gets called. It makes it convenient because other platforms (including Storekit2) handle it automatically. However, there are situations when you'd like to have the freedom to handle finishing the transaction manually. I have this on my list to fix as soon as 11.0.0 lands

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/2000

**Comment by andresesfm** [comment]
Released on `11.0.2` Please set `automaticallyFinishRestoredTransactions` to false when calling `getAvailableItems`. Like so: `getAvailableItems({automaticallyFinishRestoredTransactions:false})` Keep in mind that when this is set to false, you'll have to call `finishTransaction` when you are done restoring the purchase

**Comment by vvodicka** [comment]
Thanks! Really appreciate a prompt resolving!

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/2007
