### ISSUE TITLE
Promote IAPs from App Store?

### ISSUE THREAD

**Issue by ilyakar** [dooboolab/react-native-iap#199]
Does this plugin support SkPaymentTransactionObserver method so that the In-App Purchases can be promoted on the iOS App Store?
https://developer.apple.com/app-store/promoting-in-app-purchases/

**Comment by ilyakar** [comment]
Here’s the PR of react-native-in-app-utils and how they solved this:

https://github.com/chirag04/react-native-in-app-utils/pull/179

**Comment by JJMoon** [comment]
No. We didn't implement this yet. We will implement this sooner or later.

**Comment by xVanilla** [comment]
We need news please, I have no ideas how to fix this

**Comment by JJMoon** [comment]
OK. I will look over it.

**Comment by ilyakar** [comment]
Thanks!!! :)

**Comment by JJMoon** [comment]
I wonder if this method is already implemented regarding #307.
It is about unfinished transaction handling. And I guess Promoted Purchased Transactions can be handled in the same manner.
I committed a PR regarding this, and it is not deployed yet. I hope you to check this PR.
https://github.com/dooboolab/react-native-iap/pull/347 

Do you think this is the solution for this issue ?

**Comment by xVanilla** [comment]
@JJMoon I don't know for now. I will take a look at it when I got some times to work on it. Thanks!

**Comment by JJMoon** [comment]
@xVanilla Thank you for your reply. Currently, we need some test. In real App Store promotion.
If this can be done successfully, this issue can be resolved.

**Comment by EightPool** [comment]
Any news on this feature?

**Comment by L-Yeiser** [comment]
@neilco I am attempting to implement this feature but can not get the listener to fire using itms-service trigger (itms-services://?action=purchaseIntent&bundleId=[BUNDLE_ID]&productIdentifier=[PRODUCT_ID]). I am starting the observer in the appDelegate and add the listener when our app initializes. Any help.

**Comment by neilco** [comment]
@L-Yeiser Are you calling `[IAPPromotionObserver startObserving]` at the very beginning of `-[application:didFinishLaunchingWithOptions:]`?

**Comment by L-Yeiser** [comment]
@neilco ends up I was using the wrong productIdentifier. A coworker had updated the productId and I was unaware. Everything now works as expected. Thanks for the time.
