### ISSUE TITLE
Android Linking issue #Android

### ISSUE THREAD

**Issue by Hassan-Riaz** [dooboolab/react-native-iap#1991]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

I have integrated react-native-iap: 10.1.0
And facing this error not able to gradle sync or build
Recompile with -Xlant:deprecation for detalls
/Applications/.../MainActivity.java: 4: error: cannot find symbol
import com.dooboolad.RNlap.lapPackage:

Have also tried linking manually using the link below but its not working i am not able to build or run the project its keep saying gradle sync failed
https://react-native-iap.dooboolab.com/docs/get-started/

**Expected Behavior**

After installing package the gradle sync should integrate the package and then i should be able to run it.

**Screenshots**

![WhatsApp Image 2022-09-22 at 9 34 29 PM](https://user-images.githubusercontent.com/43652534/191896914-0428b75e-8c6b-4e72-9988-1064a7532acc.jpeg)

<img width="1331" alt="Screenshot 2022-09-23 at 10 33 33 AM" src="https://user-images.githubusercontent.com/43652534/191897656-806bca94-e115-48d9-bfcd-6b60ed6fbc05.png">

**Environment:**

- react-native-iap:
- react-native:
- Platforms (Android, device):

**To Reproduce**

1. install react-native-iap
2. sync/build gradle

**Comment by andresesfm** [comment]
Most likely: https://react-native-iap.dooboolab.com/docs/get-started/
`missingDimensionStrategy`
