### ISSUE TITLE
On cancel requestPurchase on android I have no catch error

### ISSUE THREAD

**Issue by MariusCatanoiu** [dooboolab/react-native-iap#1993]
On iOS we have this on cancel requestPurchase:

```
code:E_USER_CANCELLED
message:The operation couldn’t be completed. (SKErrorDomain error 2.)
```

which is ok.
But on android I have no error.

code:

```
 try {
      await requestPurchase({
        sku,
        andDangerouslyFinishTransactionAutomaticallyIOS: false,
      });
    } catch (err) {
      console.warn(err.code, err.message);
    }
```

**Environment:**

- react-native-iap: 10.1.3
- react-native: 0.69.5
- Platforms (iOS, Android, emulator, simulator, device): Android

**To Reproduce**

1. requestPurchase
2. cancel the flow

**Comment by andresesfm** [comment]
I just tested on version `11.0.2` and I cannot reproduce. I used the IapExample app. 
Launch the app, tap on "Products"
Tap on buy on any of the items
Tap outside the popup dialog.
 See the rejection error on the screen. 

Please let me know if I'm missing anything

**Comment by mvrty** [comment]
Have same issue on `12.1.2` - not getting any error when cancelling a payment on Android phone (tested Pixel 6 - Android 12 and Samsung S10 -Android 11) (everything else works as expected).

Using same code as @MariusCatanoiu above - did you get it working?

**Comment by mvrty** [comment]
@andresesfm Which device did you test on? I can't seem to get any rejection here.

Using the hooks approach, wrapping app in `withIAPContext` and getting `requestPurchase` from `useIAP` hook. So not calling `initConnection` anywhere. What's interesting is that even on Android simulator the `requestPurchase` doesn't throw any error (maybe this is expected? but calling `initConnection` throws saying billing not available, as expected). Am I missing something obvious here?

**Comment by mvrty** [comment]
@andresesfm Thank you!

However, the `requestPurchase` promise on Android real device directly resolves and hence no rejection is thrown when cancelling a purchase.

```
setPurchasing(true); // state to disable buy button
try {
      await requestPurchase({
        skus,
        andDangerouslyFinishTransactionAutomaticallyIOS: false,
      });
      console.log('after request');
    } catch (err) {
      console.warn(err.code, err.message);
    }
```
would print out 'after request' directly when pressed. It's still possible to buy but if cancelled - no error. Any ideas on this? I have 1-tap buy in Google Play store - not sure if that has anything to do with it?

**Comment by andresesfm** [comment]
When using hooks, the  purchase Error is saved in 

```
{currentPurchaseError...}  = userIAP()
```

Please take a look at the IapExample bundled with the app
