### ISSUE TITLE
STOREKIT_HYBRID_MODE will use Storekit 2 on iOS 13.7 Simulator

### ISSUE THREAD

**Issue by derRaab** [dooboolab/react-native-iap#1995]
**Description**

When using `STOREKIT_HYBRID_MODE`, the fallback to Storekit 1 seems to not work (at least on iOS Simulator 13.7).

Since calling `setup({ storekitMode: 'STOREKIT_HYBRID_MODE'  })` immediately logs `Using Storekit 2` I assume this is just a basic internal misconfiguration.

All calls to `initConnection()`, `getSubscriptions()` and `getProducts()` also fail with `[Error] Method only available on iOS 15 and up`

**Expected Behavior**

The app should fallback to Storekit 1.

**Screenshots**

**Environment:**

- react-native-iap: 11.0.0-rc.6
- react-native: 0.68.3
- Platforms iOS 13.7 Simulator (iPhone 11)

**To Reproduce**

1. Use `setup({ storekitMode: 'STOREKIT_HYBRID_MODE'  })` 
2. Run your app on iOS 13.7 Simulator
3. Error is shown

---

**Additional Context**

I did switch to STOREKIT1_MODE manually, which lead to this error: https://github.com/dooboolab/react-native-iap/issues/1992#issuecomment-1257005273

**Comment by andresesfm** [comment]
Fixed as part of `11.0.0-rc.7`
