### ISSUE TITLE
subscriptionIOS.subscriptionPeriodNumberIOS missing in 11.0.0-rc-7 in STOREKIT_HYBRID_MODE

### ISSUE THREAD

**Issue by derRaab** [dooboolab/react-native-iap#1997]
**Description**

After upgrading from 10.1.3 to 11.0.0-rc.7 `SubscriptionIOS` doesn't contain the value for `subscriptionPeriodNumberIOS` on iOS 16 anymore.

I've checked https://github.com/dooboolab/react-native-iap/blob/next/docs/docs/migrate_to_11.0.0.md again but it doesn't mention that changed and I did't find any other value that's representing the duration of the description.

iOS 13.7 does use Storekit 1 and the value exists but on iOS 16 with Storekit 2 it doesn't.

**Expected Behavior**

`subscriptionIOS.subscriptionPeriodNumberIOS` exists on iOS 16.

**Environment:**

- react-native-iap: 11.0.0-rc.7
- react-native: 0.68.3
- Platforms iOS 16 simulator

**To Reproduce**

1. Test on iOS 16.

**Comment by derRaab** [comment]
I tried using Storekit 1 again, but then on my iOS 16 Simulator `getAvailablePurchases()` will not resolve, like mentioned in this ticket: https://github.com/dooboolab/react-native-iap/issues/1984

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1999

**Comment by andresesfm** [comment]
Released on `11.0.1`
