### ISSUE TITLE
Android requestSubscription return true

### ISSUE THREAD

**Issue by hieuptit93** [dooboolab/react-native-iap#1998]
**Description**
I try requestSubscription on android and the result is always return true.
Not return
{
    "orderId":"GPA.2023-9153-0180-49403",
    "packageName":"com.package.name",
    "productId":"subscription.name.sku",
    "purchaseTime":1565763897962,
    "purchaseState":0,
    "purchaseToken":"kkoohioagkpieamagedjoiji.AO-J1Owj3YPtGxM9YOBSCywUo07BwcX79dAS24w7DvvxVi-gEzsXeRvkY5NGETBH8oDUaWc0oF4M8K3EiJ2v9JUfoGzxPazO51qpksIXGOkVPHI0DVJE3FzOdDd7bqbAIPVLFUo7u6SzdN1nRUlg9xoakvzqY8Kwow",
    "autoRenewing":true,
    "acknowledged":false
  }

**Expected Behavior**

**Screenshots**

**Environment:**

- react-native-iap: 10.0.7
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): Android

**Comment by andresesfm** [comment]
Hello @hieuptit93. The method returns a `Promise`

**Comment by Kadir-prog** [comment]
hi @hieuptit93 before you request any purchase, you should set purchaseUpdatedListener to get the updates as soon as the application is launched

**Comment by Kadir-prog** [comment]
hi @andresesfm so how can we get that response after purchase any subscription

**Comment by andresesfm** [comment]
follow the sample code in the documentation
