### ISSUE TITLE
[QUESTION][IOS] Renewing after cancellation.

### ISSUE THREAD

**Issue by noahhayes** [dooboolab/react-native-iap#200]
Scenario:
User purchases subscription.
User cancels subscription.
User is prompted to renew subscription.
User purchases (renews).

So my question: What will the renewed purchase receipt look like? Will it use the Original Transaction ID or will it have a totally new Transaction ID?

It seems to be impossible to test this in sandbox so I'm hoping somebody knows!

**Comment by JJMoon** [comment]
I think it can be tested in real device in sandbox mode. Subscription time passes faster during test. For example, 5 minutes instead of 1 day. 
The process looks like semi-abusing. And I don't this that works.
@noahhayes Can you test this ?
