### ISSUE TITLE
Product update listener trigger multiple times???

### ISSUE THREAD

**Issue by suupham2506** [dooboolab/react-native-iap#2002]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

When I successfully purchase an item, it triggers 21 times on purchaseUpdatedListener.

**Expected Behavior**
It should trigger once.

**Screenshots**

**Environment:**

- react-native-iap: 10.1.3
- react-native: 0.69.5
- Platforms (iOS, Android, emulator, simulator, device): IOS

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by exzos28** [comment]
You must provide a minimal code example, please.

**Comment by andresesfm** [comment]
Added to FAQ: https://github.com/dooboolab/react-native-iap/pull/2005
