### ISSUE TITLE
purchaseUpdatedListener call so many times

### ISSUE THREAD

**Issue by Kadir-prog** [dooboolab/react-native-iap#2013]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
when app is purchase is done purchaseUpdatedListener gets executed when go back from screen and call again still purchaseUpdatedListener called and resubmit previous data to api how to remove all listener 

**Expected Behavior**
need to remove listener after purchase

**Screenshots**

**Environment:**

- react-native-iap: 9.0.4
- react-native: 0.67.4
- Platforms (Android, device):
---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
read FAQ
