### ISSUE TITLE
Purchased successfully and deducted but no money transferred to google console

### ISSUE THREAD

**Issue by LamQuyet** [dooboolab/react-native-iap#2017]
**one of my customers made an in-app purchase and paid successfully but google console was not credited. Is there any way to catch this error?**

**Environment:**

- react-native-iap: 10.0.0
- react-native: 0.66.3
- Platforms (iOS, Android, emulator, simulator, device): Android devices
- Environment: production

---

**Comment by andresesfm** [comment]
Did you finish the transaction successfully? If so, it could be a problem you should bring up with the Google Play folks

**Comment by victoriaSh** [comment]
@LamQuyet Did you manage to figure out what went wrong? 
I haven't updated the app in about six months. There were some rare purchases until mid-January, but then there was a surge in user activity on the app. I can see successful purchases and purchase tokens in the database and in the user activity statistics, I can see that the paid content was successfully accessed by users. However, I don't see any purchases or refunds in the Play Console.

**Comment by useVlad** [comment]
@andresesfm 
I have the same problem, some users of my application make purchases, transactions from Google purchasing ID are saved in the database, these transactions are not displayed in the Google console...


any ideas or news on this issue?

**Comment by useVlad** [comment]
@LamQuyet any ideas or news on this issue?
