### ISSUE TITLE
clearTransactionIOS not working with StoreKit 2

### ISSUE THREAD

**Issue by myklosbotond** [dooboolab/react-native-iap#2018]
**Description**

Calling `clearTransactionIOS` returns a TypeError when using StoreKit 2.

**Expected Behavior**

The call either works, or the unavailability of this method is documented.

**Screenshots**

**Environment:**

- react-native-iap: 11.0.7 
- react-native: 0.66.4
- Platforms (iOS, Android, emulator, simulator, device): iOS 16

**To Reproduce**

1. Enable StoreKit 2 with `setup({ storekitMode: 'STOREKIT_HYBRID_MODE' })`.
2. Call `clearTransactionIOS()`.
3. TypeError is shown:
    ```text
    [TypeError: (0, _$$_REQUIRE(_dependencyMap[2], "../internal").getIosModule)().clearTransaction is not a function. (In '(0, _$$_REQUIRE(_dependencyMap[2], "../internal").getIosModule)().clearTransaction()', '(0, _$$_REQUIRE(_dependencyMap[2], "../internal").getIosModule)().clearTransaction' is undefined)]
    ```

---

[Optional] **Additional Context**

In [`src/modules/iosSk2.ts#L49`](https://github.com/dooboolab/react-native-iap/blob/11.0.7/src/modules/iosSk2.ts#L49) the `IosModulePropsSk2` interface includes this method, but on the native side no such method is provided in `ios/RNIapIosSk2.swift`.

```ts
export interface IosModulePropsSk2 extends NativeModuleProps {
  /* ... */
  buyProduct: BuyProduct;
  clearTransaction: clearTransaction;
  clearProducts: clearProducts;
  /* ... */
}
```

**Comment by andresesfm** [comment]
released on `12.0.1`
