### ISSUE TITLE
Android subscription does not have localizedPrice

### ISSUE THREAD

**Issue by myklosbotond** [dooboolab/react-native-iap#2022]
**Description**

`localizedPrice` is not present in an android subscription, yet the types say that it is.

**Expected Behavior**

`localizedPrice` is either not present in `SubscriptionAndroid` or is marked as optional.

**Screenshots**

**Environment:**

- react-native-iap: 12.0.1
- react-native: 0.66.4
- Platforms (iOS, Android, emulator, simulator, device): Android (or rather TypeScript)

**To Reproduce**

1. Get a subscription object from `getSubscriptions` and observe its structure.

---

[Optional] **Additional Context**

`SubscriptionAndroid` is extending `ProductCommon`, which in turn includes `localizedPrice: string`. However, the price-related info on android can be found only in `subscription.subscriptionOfferDetails[*].pricingPhases.pricingPhaseList[*].formattedPrice`.

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/2025

**Comment by andresesfm** [comment]
Released on `12.0.2` Thank you @myklosbotond

**Comment by asleepace** [comment]
> Released on `12.0.2` Thank you @myklosbotond

Why is it designed this way on Android?
