### ISSUE TITLE
Unable to get the history of purchases

### ISSUE THREAD

**Issue by kayro2222** [dooboolab/react-native-iap#2026]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

I'm trying to get the user's purchases with `getPurchaseHistory()` and `getAvailablePurchases()` to verify if the user has active subscription to send him to the main navigator of the app or to the subscription offers. The functions are returning an undefined value or an empty array.

**Expected behavior**

I need to get the history of purchases to validate if the date is expired or not. Using the version 10.0.6, I had successfully get the history using the methods described above.

**Screenshots**

**Environment:**

- react-native-iap: 12.0.1
- react-native: 0.66.4
- Platforms (iOS, Android, emulator, simulator, device): iOS 15+

**To Reproduce**

I'm requesting the purchase using the examples provided from the lib:

```
const handleRequestSubscription = async () => {
    setLoading(true)
    if (selectedSubscription) {
      if (Platform.OS === 'ios') {
        try {
          await requestSubscription({
            sku: selectedSubscription?.productId,
          })
        } catch (error) {
          setLoading(false)
          if (error instanceof PurchaseError) {
            Alert.alert(
              'Error',
              'A error has occurred. Please check your payment configuration.',
            )
            console.log({ message: `[${error.code}]: ${error.message}`, error })
          } else {
            console.log({ message: 'handleBuySubscription', error })
          }
        }
      }
    }
  }
  
  useEffect(() => {
    const checkCurrentPurchase = async () => {
      try {
        if (currentPurchase?.productId) {
          await finishTransaction({
            purchase: currentPurchase,
            isConsumable: true,
          })

          setIsSubscribe(true)
        }
      } catch (error) {
        if (error instanceof PurchaseError) {
          Alert.alert(
            'Error',
            `message: [${error.code}]: ${error.message}, error`,
          )
        } else {
          Alert.alert('Error', `message: 'handleBuyProduct', ${error}`)
        }
      }
    }

    checkCurrentPurchase()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentPurchase, finishTransaction])
```

But when I reload the app, I want to verify if this subscription is active using:

```
export const PurchaseHistory: React.FC = () => {
  const navigation = useNavigation()
  const { getAvailablePurchases, getPurchaseHistory } = useIAP()
  const { setIsSubscribe } = useSubscriptionContext()
  const [loading, setLoading] = useState(false)

  const handleGetPurchaseHistory = async () => {
    console.log('getPurchaseHistory', await getPurchaseHistory())
    console.log('getAvailablePurchases', await getAvailablePurchases())
  }

  useEffect(() => {
    const checkSubscribeActive = async () => {
      handleGetPurchaseHistory()
    }
    checkSubscribeActive()
  }, [])

  return <></>
}
```

My logs:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/15899265/194425673-2eea8898-1346-443d-b71c-a92f1f1bcb43.png">

---

[Optional] **Additional Context**

I'm using `setup({ storekitMode: 'STOREKIT2_MODE' })`
I do not save the purchase information at my server-side.

**Comment by andresesfm** [comment]
@kayro2222 it looks like a bug that would happen when using hooks. Can you please try passing the following parameter to the method:

```
getAvailablePurchases({
alsoPublishToEventListener:true})
```
That should fix it while I come up with an actual fix

**Comment by andresesfm** [comment]
Since you are using Storekit 2. You can try `await IapIosSk2.latestTransaction(sku)`

**Comment by kayro2222** [comment]
it worked @andresesfm! thanks for your time.

**Comment by kayro2222** [comment]
hey @andresesfm, I'm receiving `[Error: Can't find product for sku **my_sku**]` using `IapIosSk2.subscriptionStatus(skus.monthly)` when I reload my app. At fast refresh, I'm able to get the subscriptions.

**Comment by kayro2222** [comment]
it seems that I need to use the context hook at the history too
