### ISSUE TITLE
How to decode base64 result.latest_receipt returned by validateReceiptIos ?

### ISSUE THREAD

**Issue by lc3t35** [dooboolab/react-native-iap#203]
### Version of react-native-iap
1.2.1
### Platforms you faced the error (IOS or Android or both?)
iOS
I was digging into validateReceiptIos to get more information on subscriptions status, I did this
````
RNIap.validateReceiptIos({
        'receipt-data': purchase.transactionReceipt,
        'password': "****",
      }, false, 54).then(result => {
        console.log("DEBUG pending_renewal_info ", result.pending_renewal_info);
        console.log("DEBUG lastest_receipt ", result.latest_receipt)
      });
````
result.latest_receipt is a base64 encoded json, does someone know the best way to convert it to readable json ?

Ref links : 
https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html
https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW1

I've noticed an error in isTest param, if isTest is true, it should run as sandbox
````
export const validateReceiptIos = async (receiptBody, isTest, RNVersion) => {
  if (Platform.OS === 'ios') {
const URL = !isTest ? 'https://sandbox.itunes.apple.com/verifyReceipt' : 'https://buy.itunes.apple.com/verifyReceipt';
````
should be 
````
export const validateReceiptIos = async (receiptBody, isTest, RNVersion) => {
  if (Platform.OS === 'ios') {
const URL = isTest ? 'https://sandbox.itunes.apple.com/verifyReceipt' : 'https://buy.itunes.apple.com/verifyReceipt';
````

**Comment by dooboolab** [comment]
@lc3t35 Thank you for your correction. Could you give us a `PR` so that you can be the contributor? Or do you just want me to do this?

**Comment by dooboolab** [comment]
@lc3t35 I've just fixed it and publisehd to `1.2.3`.

**Comment by lc3t35** [comment]
Thank you @dooboolab , any idea for decoding base64 encoded json receipt ?

**Comment by dooboolab** [comment]
@lc3t35 Haven't had idea yet. I've just use this to verify that the purchase is not malformed. Could you share if you find any news?

**Comment by lc3t35** [comment]
@dooboolab  I think there is a problem with the receipt I get, I've tried with another receipt such this one shown here https://github.com/j3k0/cordova-plugin-purchase/issues/215 which decodes well.

**Comment by lc3t35** [comment]
It seems that I can get renewal.auto_renew_status ("0" or "1") from 
````
RNIap.validateReceiptIos({
        'receipt-data': purchase.transactionReceipt,
        'password': "*****",
      }, false, 54).then(result => {
        _.each(result.pending_renewal_info, function (renewal) {
          console.log("DEBUG pending_renewal_info ", renewal.auto_renew_product_id, renewal.auto_renew_status);
        });
        // console.log("DEBUG lastest_receipt ", result.latest_receipt);
      });
````
Is this enough to know if the user has not cancelled his subscription, in this case renewal.auto_renew_status is "0" (i.e. not automatically renewable) ?

**Comment by ramonsenadev** [comment]
@lc3t35 
For decode this base64 (from subscriptions), you will need to send it to apple server. Like described in https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html

I was trying to copy the base64 from console while I was debugging my app and trying to make the call to Apple end-point, but it looks like the chrome was truncating the receipt, since I was always getting "invalid receipt" from Apple server.

After I sent the base64 receipt data to my local server and made the call to apple, I finally decoded the receipt.

**Comment by dooboolab** [comment]
Related #237

**Comment by tmjordan** [comment]
you can use this lib  https://github.com/Wizcorp/node-iap

**Comment by lincdh** [comment]
After calling RNIap.validateReceiptIos I see the object with these keys: `['environment', 'latest_receipt', 'latest_receipt_info', 'pending_renewal_info', 'receipt', 'status']`. Then why does one need to decode `latest_receipt`?
