### ISSUE TITLE
In-App purchase in iOS.

### ISSUE THREAD

**Issue by sanilcgs** [dooboolab/react-native-iap#204]
@dooboolab Hi, I have a doubts regarding IAP. I have added three IAP products into app store connect. By mistake, I haven't added any screen shot and promotional images of two of my IAP products. But all the IAPs are getting approved by apple and shows a message **An in-app purchase has been returned and is highlighted in the table below.**. But one of my approved products have submitted with all required fields. So my question is can I test In-App purchase with the approved one having all the fields submitted???

**Comment by dooboolab** [comment]
@sanilcgs Haven't had that issue for me. Since I haven't experienced your case, it is hard to tell.  However, I may guess your status when you put some screenshot for me to read. Cheers.

**Comment by sanilcgs** [comment]
@dooboolab I have tested with my approved in-app product, but I got the error message **Invalid product ID**. Also when I call the **getProducts** method I got an empty array. In my case, two more in-apps are there with approved status. But I haven't submitted the required images for those products at the time of submission.

**Comment by dooboolab** [comment]
@sanilcgs Yes. You should submit the required images in in-app. I'll close this one since you've solved your issue.
