### ISSUE TITLE
RNIap.getSubsription(itemSubs) get empty Array but RNIap.getProduct(itemSku) get Products 

### ISSUE THREAD

**Issue by ardhendu12345** [dooboolab/react-native-iap#2040]
react-native -0.70.1
react-native-iap-8.2.1

here i can get the product after using RNIap.getProduct(itemSku) , but in the same app there is also an subscription Plan likewise 
product , though i can able to get the product but get empty Array for subscription by using RNIap.getSubscription(itemSubs)
please help me how to get the  the subscription details..Please help ..

**Comment by andresesfm** [comment]
read migration guides
