### ISSUE TITLE
getReceiptIos is not a function

### ISSUE THREAD

**Issue by FeTree** [dooboolab/react-native-iap#2042]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

Hi, im trying to fetch the transactionReceipt base 64 encoded string so I can send to our server to verify the IAP. When using getReceiptIOS() i am getting the error:
```
Possible Unhandled Promise Rejection (id: 15):
TypeError: (0, _$$_REQUIRE(_dependencyMap[2], "../internal").getIosModule)().requestReceipt is not a function. (In '(0, _$$_REQUIRE(_dependencyMap[2], "../internal").getIosModule)().requestReceipt(forceRefresh != null ? forceRefresh : false)', '(0, _$$_REQUIRE(_dependencyMap[2], "../internal").getIosModule)().requestReceipt' is undefined)
```

Code i am using:
```
const newReceipt = await getReceiptIOS({ forceRefresh: false });
console.log(newReceipt, 'newReceipt');
```

**Expected Behavior**

The string is printed to the console

**Screenshots**

N/A

**Environment:**

- react-native-iap: 12.0.3
- react-native: 0.69.3
- Platforms (iOS, Android, emulator, simulator, device):

**To Reproduce**

1. Paste code within the requestPurchase function
2. On device make an IAP

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
`requestReceipt` is only available on Sk1. Fix here: https://github.com/dooboolab/react-native-iap/pull/2045

**Comment by FeTree** [comment]
I see, thank you @andresesfm
