### ISSUE TITLE
react-native-iap V12.0.3 gives the error parameter specified as non-null is null: method kotlin .jvm.internal.Intrinsics.checkNotNullParameter,parameter skuArr 

### ISSUE THREAD

**Issue by ardhendu12345** [dooboolab/react-native-iap#2043]
when i use real device for 
React native - 0.70.1
react-native-iap- 12.0.3

it giges me error when i call RNIap.getSubscription(itemSubs) or RNIap.getProducts(itemSku) 
"parameter specified as non-null is null: method kotlin .jvm.internal.Intrinsics.checkNotNullParameter,parameter skuArr "

please help me to solve the issue

**Comment by andresesfm** [comment]
read migration guides

**Comment by arifhakanarslan** [comment]
I'm having the same problem too. Any progress?

**Comment by snwshivani** [comment]
hello 
I'm facing the same issue can anyone help me with this 
of any link to read the migration 
I'm using the latest version: 12.1.2 and using react native CLI

**Comment by arifhakanarslan** [comment]
Hello
It worked when I updated the package as below.
"react-native-iap": "^9.0.0",

**Comment by snwshivani** [comment]
but is it updated with google billing library version 4 or greater? 
bcoz it will not work after 1st November

**Comment by snwshivani** [comment]
ok I got the solution and it also works in the latest version
RNIap.getSubscriptions({skus: productSkus});

try this

**Comment by arifhakanarslan** [comment]
oh supper, I'm trying right away

**Comment by arifhakanarslan** [comment]
> oh supper, I'm trying right away

It worked, thanks a lot

**Comment by MahbbRah** [comment]
> ok I got the solution and it also works in the latest version RNIap.getSubscriptions({skus: productSkus});
> 
> try this

This worked for me as well, Ty!

**Comment by eliamgar10** [comment]
What did you guy do?
