### ISSUE TITLE
Provide Better Errors

### ISSUE THREAD

**Issue by swushi** [dooboolab/react-native-iap#2044]
**Description**
Right now, it appears that this library groups all errors together when using `requestPurchase`. It typically looks like: `[Error: The operation couldn’t be completed. (SKErrorDomain error 2.)]`

Unfortunately, this also includes the user cancelling the purchase entirely. So, there is currently no way to distinguish between the user cancelling the purchase-attempt, and an actual error, so it forces the developer to decide if they would rather swallow the error, or display an error when they are just cancelling. If you display an error when the user cancels, you are _surely_ scaring them, and they will probably not try to make another purchase.

**Code Snippet**
```ts
try {
  await requestPurchase({ sku: product.productId });
} catch (error) {
  // Ideally we'd like to show an error-toast here, however react-native-iap currently does not provide a way to
  // distinguish between the user clicking cancel, and an actual error occuring. So, in an effort to avoid showing the user
  // an error when they click cancel, we are swallowing the error entirely.
}
```

**Expected Behavior**
Provide `errorTypes` and allow the developer to decide how to handle each type.

**Environment:**

- "react-native-iap": "^10.0.0",
- "react-native": "0.69.5",
- Platforms (iOS):

**To Reproduce**

1. Attempt to make a purchase
2. Press `cancel` in the native iOS IAP sheet.

**Comment by andresesfm** [comment]
@swushi The error object has a `code` field that you can use for that effect

**Comment by swushi** [comment]
Wonderful, are the possible types defined anywhere?

**Comment by swushi** [comment]
Just found it: https://github.com/dooboolab/react-native-iap/blob/main/src/purchaseError.ts
