### ISSUE TITLE
Storekit 2 - missing discounts (Introductory and Promotional Offers) in getSubscriptions

### ISSUE THREAD

**Issue by timbrandin** [dooboolab/react-native-iap#2048]
When using Storekit 2 mode, there aren't any introductory or promotional offers mapped to the Product type in the subscriptionSk2Map.

These fields are set if available offers are set:
```
introductoryPriceNumberOfPeriodsIOS
introductoryPricePaymentModeIOS
introductoryPriceSubscriptionPeriodIOS
introductoryPrice
introductoryPriceAsAmountIOS
discounts
```

**Environment:**

- react-native-iap: 12.0.1
- react-native: 0.66.1
- Platforms (iOS, Android, emulator, simulator, device): iOS

**To Reproduce**

1. Create products in App Store with introductory and promotional offers
2. use getSubscriptions({ skus: [SKU] }) and fetch the data
3. The fields are missing.

---

**Comment by andresesfm** [comment]
@timbrandin. For Sk2 you can use product.subscriptionInfo. This could use some polishing

**Comment by timbrandin** [comment]
@andresesfm that is not passed through getSubscriptions:

https://github.com/dooboolab/react-native-iap/blob/main/src/iap.ts#L242-L244
![image](https://user-images.githubusercontent.com/1715834/195803109-36377933-6541-4703-801d-0957c85b467e.png)
https://github.com/dooboolab/react-native-iap/blob/main/src/types/appleSk2.ts#L66-L88
![image](https://user-images.githubusercontent.com/1715834/195803222-725202e6-f79f-4fe7-8da2-3e98cd94cc70.png)

Do you have an example with offers available?

**Comment by andresesfm** [comment]
For now the way to do it is to go directly to the Sk2 implementation directly like so:
```
import {IapIosSk2} from 'react-native-iap'
...
await IapIosSk2.getItems(...)

```
