### ISSUE TITLE
iOS StoreKit 1 getAvailablePurchases crash

### ISSUE THREAD

**Issue by Aximem** [dooboolab/react-native-iap#2055]
**Description**

I'm trying to migrate from  RN IAP version 7 (where everything is working) to version 12.  
I want to keep Storekit 1 since I have a receipt validation process.   
The subscription is working fine but I struggle with restore purchase feature with getAvailablePurchases.

**Expected Behavior**

getAvailablePurchases retrieve user available purchases like in previous versions

**Environment:**

- react-native-iap: 12.1.2
- react-native: 0.69.3
- Platforms (iOS, Android, emulator, simulator, device): iOS 16

**To Reproduce**

In App.tsx 

```
import {setup} from 'react-native-iap';

setup({storekitMode: 'STOREKIT1_MODE'});
```

In my component

``` 
import React, {useEffect} from 'react';
import {Text, TouchableOpacity} from 'react-native';
import {useIAP, withIAPContext} from 'react-native-iap';

const MyComponent = () => {
  const {availablePurchases, getAvailablePurchases} = useIAP();

  useEffect(() => {
    console.log('availablePurchases', availablePurchases);
  }, [availablePurchases]);

  return (
    <TouchableOpacity
      onPress={async () => {
        try {
          await getAvailablePurchases();
        } catch (e) {
          console.log('error', e);
        }
      }}>
      <Text>Restore purchases</Text>
    </TouchableOpacity>
  );
};

export default withIAPContext(MyComponent);
``` 

I'm getting a warning:  
> Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"2480":{"module":"RNIapIos","method":"getAvailableItems"},"2492":{"module":"NativeAnimatedModule","method":"startAnimatingNode"} ...

And, randomly, the app is crashing with memory issue

Also some logs from XCode: 
>[react-native-iap] Purchase Successful
[react-native-iap] requestReceiptDataWithBlock with force refresh: NO
[react-native-iap] restoreCompletedTransactionsFailedWithError
2022-10-18 17:27:07.732595+0200 GOWOD[18854:732509] [javascript] 'Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"2475":{"module":"RNIapIos","method":"getAvailableItems"}

**Comment by andresesfm** [comment]
I don't think this is an issue with the library but with the way `useEffect` is structured. Please see IapExample. It's working for me. If that fails please reopen
