### ISSUE TITLE
Android purchases refunded after 3 days

### ISSUE THREAD

**Issue by sarons** [dooboolab/react-native-iap#2059]
After user purchases a product, it gets refunded in exactly 3 days. He purchased it again and refunded again in 3 days.

```
useEffect(() => {
    try {
      const checkCurrentPurchase = async (purchase)=> {
        if (purchase) {
          const receipt = purchase.transactionReceipt;
          if (receipt)
            try {
              await finishTransaction(purchase)

            } catch (ackErr) {
              crashlytics().recordError(ackErr)
            }
        }
      }
      checkCurrentPurchase(currentPurchase)
    } catch (ackErr) {
      crashlytics().recordError(ackErr)
    }
  }, [currentPurchase, finishTransaction]);
```

I found this https://stackoverflow.com/a/56664532
Users must acknowledge the purchase within 3 days otherwise the subscription will be refunded:

https://developer.android.com/google/play/billing/billing_library_overview#acknowledge

It works fine on iOS, do I need to do something different for android?

**Expected Behavior**

Purchase is accepted and not refunded after 3 days

**Screenshots**
<img width="987" alt="Screenshot 2022-10-19 at 20 09 19" src="https://user-images.githubusercontent.com/833224/196789672-691fcf5a-9c97-47b4-900d-04aeabdcac6f.png">

**Environment:**

- react-native-iap: "12.0.1"
- react-native: "0.66.4"
- Platforms (Android, device):

**To Reproduce**

1. Buy Product in production app
2. Wait 3 days
3. Money refunded

---

**Comment by sarons** [comment]
I see that there is an acknowledgePurchaseAndroid method
https://react-native-iap.dooboolab.com/docs/api-reference/methods/android/acknowledge-purchase-android

Do I need to use that for android?

Didn't have this issue with previous versions of react-native-iap

**Comment by kayro2222** [comment]
same problem here @andresesfm

**Comment by andresesfm** [comment]
Calling `finishTransaction` is all that's needed. Make sure it's called and that it doesn't fail.

**Comment by kayro2222** [comment]
I'm getting an error: `An unknown or unexpected error has occurred. Please, try again later.`

This is my code to finish transaction:

```
const checkCurrentPurchase = async () => {
      try {
        if (currentPurchase?.productId) {
          await finishTransaction({
            purchase: currentPurchase,
            isConsumable: false,
          })
          setIsSubscribe(true)
        }
      } catch (error) {
        if (error instanceof PurchaseError) {
          //THE ERROR THAT ARE SHOWING TO ME
          Alert.alert(
            'Error',
            `message: [${error.code}]: ${error.message}, error`,
          )
        } else {
          Alert.alert('Error', `message: 'handleBuyProduct', ${error}`)
        }
      }
    }
```

**Comment by sarons** [comment]
> I'm getting an error when trying to finish a subscribe transaction: `An unknown or unexpected error has occurred. Please, try again later.`
> 
> This is my code to finish transaction:
> 
> ```
> const checkCurrentPurchase = async () => {
>       try {
>         if (currentPurchase?.productId) {
>           await finishTransaction({
>             purchase: currentPurchase,
>             isConsumable: false,
>           })
>           setIsSubscribe(true)
>         }
>       } catch (error) {
>         if (error instanceof PurchaseError) {
>           //THE ERROR THAT ARE SHOWING TO ME
>           Alert.alert(
>             'Error',
>             `message: [${error.code}]: ${error.message}, error`,
>           )
>         } else {
>           Alert.alert('Error', `message: 'handleBuyProduct', ${error}`)
>         }
>       }
>     }
> ```

@andresesfm I don't get this error. My transaction works fine on android dev, staging and iOS. The only issue is that it refunds the money after 3 days

**Comment by sarons** [comment]
So turns out there was a breaking change when I upgraded react-native-iap, 
changing
`await finishTransaction(purchase)`
to
`await finishTransaction({purchase})`
fixed it

**Comment by shivanitp** [comment]
I'm facing the same issue my subscription gets an auto refund after 3 days 

I'm using  12.3.2 versions of iap

var purchase = await RNIap.requestSubscription({ purchaseTokenAndroid: oldToken, prorationModeAndroid: ProrationModesAndroid.IMMEDIATE_AND_CHARGE_PRORATED_PRICE, subscriptionOffers });

var purchaseUpdateSubscription = await RNIap.purchaseUpdatedListener(async (purchasedUpdate) => {
    if(purchasedUpdate){
        var achnowalgeAndroid = await acknowledgePurchaseAndroid({ token: purchasedData.purchaseToken, developerPayload: 'developer-payload' })
        try {
            const ackResult = await finishTransaction({ purchase: purchasedData });
        } catch (ackErr) {
                console.log('ackErr', ackErr);
        }

    }
})

can anyone help me with this

**Comment by aj019** [comment]
> So turns out there was a breaking change when I upgraded react-native-iap, changing `await finishTransaction(purchase)` to `await finishTransaction({purchase})` fixed it

This solved it for me

**Comment by kivancagaogluu** [comment]
I am using exact same codes at example. Production or testing does not matter subscriptions cancelled automatically by Google and users got an email says "Your subscription requires action". 

```javascript
const checkCurrentPurchase = async () => {

      try {
        if (currentPurchase?.productId) {
          await finishTransaction({
            purchase: currentPurchase,
            isConsumable: true,
          });

          setOwnedSubscriptions((prev) => [
            ...prev,
            currentPurchase?.productId,
          ]);
        }
      } catch (error) {
        console.log("error", error);
        if (error instanceof PurchaseError) {
          errorLog({message: `[${error.code}]: ${error.message}`, error});
        } else {
          errorLog({message: 'handleBuyProduct', error});
        }
      }
```
      
Code below logs
```ERROR  An error happened handleBuyProduct [Error: Google is indicating that we have some issue connecting to payment.]```
      
Did anyone actually solved this?

**Comment by Neeraj-WebNeuron** [comment]
I am facing the same issue in "react-native-iap": "^12.15.7"

money is refunded just after 3 days in prod
