### ISSUE TITLE
Question: Can I change the subscription type at the app level?

### ISSUE THREAD

**Issue by daheeahn** [dooboolab/react-native-iap#2060]
(Not Bug Report)

I implemented in-app purchase with react native iap,
Can I change the subscription type in app?
For example, I'm on a monthly subscription, but I'm changing it to an annual subscription!

Currently, the user can cancel or switch directly from the app store or play store. 
I wonder if there is an API that can do this in the app.

**Comment by andresesfm** [comment]
Yes, you can, depending on the platform, basically, you pass the previous token to the new purchase request
