### ISSUE TITLE
v 12.0.3 - problem with requestPurchase -  skus is required for android purchase

### ISSUE THREAD

**Issue by mikemangas** [dooboolab/react-native-iap#2061]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

I have migrated from version 9 to 12.0.3
Subscription works perfectly.
But if i use requestPurchase function, i receive the error: "skus is required for android purchase". Nevertheless i am passing the productId as expected and stated in the examples you provide[ here](https://github.com/dooboolab/react-native-iap/blob/main/IapExample/src/screens/Products.tsx).

I am calling the getProducts function. I also receive all informations about my product and render them in my View. But as soon as i call this requestPurchase function, i receive the error.

I would like to know, if anyone receives  the same error, using the "requestPurchase" function. And if anyone has a potential solution for that.

/*****DOWNGRADING from 12.0.3 to 12.0.0 works fine then!!!***////

**Expected Behavior**
Providing the SKU to the function and initiate the Google Pay View.

**Screenshots**
<img width="487" alt="Screenshot 2022-10-20 at 11 10 29" src="https://user-images.githubusercontent.com/85886271/196907285-1788810e-1795-43ae-a425-af5bce21ff27.png">

<img width="607" alt="Screenshot 2022-10-20 at 10 57 50" src="https://user-images.githubusercontent.com/85886271/196905894-1b98d768-ff83-4358-ab12-b229d28f5ba9.png">

<img width="392" alt="Screenshot 2022-10-20 at 10 58 33" src="https://user-images.githubusercontent.com/85886271/196905725-131ce40e-3f85-4563-9bea-1fdf76214d47.png">

**Environment:**

- react-native-iap:
- react-native:
- Platforms (Android, emulator):

**To Reproduce**

1. Upgrade to the newest IAP version
2. Use: 
```
   const handleBuyProduct = async sku => {
    try {
      await requestPurchase({sku});
    } catch (error) {}
  };

// some blocks after
              <Button
                title="Buy"
                onPress={() => handleBuyProduct(product.productId)}
              />
```
4. When you click on Buy, the error comes: skus is required for android purchase

---

**Comment by sniperosx** [comment]
Hi @mikemangas,
I noticed the same thing today. Unfortunately, the solution of downgrading to 12.0.0 is no help for me (not even with clearing and native new builds). However, I work exclusively on subscriptions. There may be a more far-reaching problem there.

Would be nice if there is another workaround. I don't want to change the framework so late in the development process :)

**Comment by andresesfm** [comment]
Have you tried passing `skus` as the message indicates?

**Comment by sniperosx** [comment]
Hi @andresesfm, 
I was to dumb cause I used "requestPurchase" to purchase/book a subscription. 
There is another method called "requestSubscription" (without purchase) that needs to be used. 

Thanks for your fast reply :)

**Comment by hardikbhingradiya** [comment]
Please use below function for request purchase, its working fine for me, but please make sure use parameter name **skus** for android and pass **sku in array** same like mentioned as below

const handleBuyProduct = async (sku) => {
    try {
      await requestPurchase(Platform.select({
        ios: { sku },
        android: { skus: [sku] }
      }));
    } catch (error) {
      if (error instanceof PurchaseError) {
        console.log({ message: `[${error.code}]: ${error.message}`, error });
      } else {
        console.log({ message: 'handleBuyProduct', error });
      }
    }
  };

**Comment by noumantahir** [comment]
For iOS using just one sku and for android using skus array of selected product did the trick for me.

`IAP.requestPurchase(Platform.OS === 'ios' ? { sku } : { skus: [sku] });`

**Comment by OHHAKO** [comment]
I also have the same problem.

try code:
`IAP.requestPurchase(Platform.OS === 'ios' ? { sku } : { skus: [sku] });`

and down graded to 12.0.0
but It's not working. any solutions?

**Comment by neeraj-tangariya** [comment]
i solved using this
```js
    const handleBuyProduct = async (sku: Sku) => {
        console.log('sku is***********', sku)
        try {
            if (Platform.OS === 'ios') {
                const data = await requestPurchase({ sku });
                console.log('success product buy>>>>>>>>>>>>', data);
            } else if (Platform.OS === 'android') {
                const data1 = await requestPurchase({ skus: [sku] });
                console.log('success product buy>>>>>>>>>>>>', data1);
            }
        } catch (error) {
            if (error instanceof PurchaseError) {
                errorLog({ message: `[${error.code}]: ${error.message}`, error });
            } else {
                errorLog({ message: 'handleBuyProduct', error });
            }
        }
    }
```
