### ISSUE TITLE
Request purchase on Android returns boolean as opposed to specified type 

### ISSUE THREAD

**Issue by lukashaertel** [dooboolab/react-native-iap#2063]
**Description**

The `requestPurchase` method's signature specifies that the return type is `Promise<ProductPurchase | void>`, but the code for Android with targeting Play Store returns a boolean.

**Expected Behavior**

`requestPurchase` on Android should return the specified return type.

**Environment:**

- react-native-iap: 12.2.0
- react-native: 0.69.6
- Platforms (iOS, Android, emulator, simulator, device): Android device, Android emulator

**To Reproduce**

1. Request inapp purchase on Android
2. A successful purchase is returned as true instead of the product purchase.

---

**Additional Context**

Type specified here:
https://github.com/dooboolab/react-native-iap/blob/main/src/iap.ts#L560

Android implementation called and returned here:
https://github.com/dooboolab/react-native-iap/blob/main/src/iap.ts#L619

The promise is resolved with a boolean in the android play store module here:
https://github.com/dooboolab/react-native-iap/blob/main/android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt#L518

**Comment by andresesfm** [comment]
Thank you @lukashaertel. You are correct. Here is the fix: https://github.com/dooboolab/react-native-iap/pull/2064

**Comment by andresesfm** [comment]
This was related after all: https://github.com/dooboolab/react-native-iap/issues/1998

**Comment by andresesfm** [comment]
released as `12.3.1`
