### ISSUE TITLE
getPurchaseHistory but the result is an empty array

### ISSUE THREAD

**Issue by 19424056** [dooboolab/react-native-iap#2065]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
storekitMode: 'STOREKIT_HYBRID_MODE'
ios 13(StoreKit1) & ios 16(StoreKit2) is both use 1 account appleStore

ios 13(StoreKit1) 
successfully purchase, getPurchaseHistory then 1 item available (correct)

ios 16(StoreKit2)
getPurchaseHistory then result = []// i need 1 item available

Code i am using:

`const response = await getPurchaseHistory({`
`      alsoPublishToEventListener: false,`
`      automaticallyFinishRestoredTransactions: false,`
`    });`

`console.log(response) // result = []`
**Expected Behavior**
The string is printed to the console

**Screenshots**
N/A

**Environment:**

- react-native-iap: "12.3.0"
- react-native: "0.70.3"
- Platforms (iOS, Android, emulator, simulator, device): IOS

**To Reproduce**

Environment Sandbox
`ios 13 -> storeKit 1`
1. press button getPurchaseHistory
Code i am using:

`const response = await getPurchaseHistory({`
`      alsoPublishToEventListener: false,`
`      automaticallyFinishRestoredTransactions: false,`
`    });`
2. show alert login apple store, apple Store Account login is required
3. Result is [{objectExample1}, {objectExample2}, ......]

`ios 16 -> storeKit 2`
1. press button getPurchaseHistory
Code i am using:

`const response = await getPurchaseHistory({`
`      alsoPublishToEventListener: false,`
`      automaticallyFinishRestoredTransactions: false,`
`    });`
2. Result is [] :(
---

[Optional] **Additional Context**

**Comment by buidinhmanh14799** [comment]
Sample issue

**Comment by andresesfm** [comment]
Did you call `getProducts`/`getSubscriptions` before calling `getPurchaseHistory`?

**Comment by 19424056** [comment]
I did call getSubscriptions before calling getPurchaseHistory .
this only happens when I buy requestSubscription successfully on storeKit1 (Iphone 8, ios 13).
on Iphone 12, ios 16 getPurchaseHistory -> [] array empty
but getPurchaseHistory on (Iphone 8, ios 13) -> [{1itemHistoryAvailable}]

Environment Sandbox
ios 13(StoreKit1) & ios 16(StoreKit2) is both use 1 account appleStore

**Comment by andresesfm** [comment]
@19424056 I think the disconnect is that sk2 is doing a validation to see if the subscription is still valid. It checks the expiration date before adding it to the array.
https://github.com/dooboolab/react-native-iap/blob/12.3.3/ios/RNIapIosSk2.swift#L589
Do you think that's what's causing it to not show up in your case?

**Comment by andresesfm** [comment]
Merging with: https://github.com/dooboolab/react-native-iap/issues/2089

**Comment by 19424056** [comment]
tks ❤️ @andresesfm . really thankful
