### ISSUE TITLE
column originalTransactionIdentifierIOS in object Purchase of function purchaseUpdatedListener incorrect

### ISSUE THREAD

**Issue by 19424056** [dooboolab/react-native-iap#2066]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
storekitMode: 'STOREKIT_HYBRID_MODE'
ios 16 -> storeKit 2 

The first time I bought it, transactionId, originalTransactionIdentifierIOS = 2000000815290844 is indetical, 2000000815290844 is originalID, BE validate Ok, successfully purchase

The Second time I bought it, transactionId, originalTransactionIdentifierIOS = 2000000815267291 are the same again, but originalTransactionIdentifierIOS is incorrect, must be 2000000815290844, after BE validate with originalTransactionIdentifierIOS = 200000081526729 is not exist, purchase faild

Code i am using:
`const purchaseUpdateSubscription = purchaseUpdatedListener(async (purchase) => {`
`      console.log(`purchase : ${JSON.stringify(purchase)}`);`
`// Make API call to your server to validate transaction`
`validateBE({ originalTransactionId: purchase.originalTransactionIdentifierIOS }) //faild because originalTransactionIdentifierIOS is incorrect,`
`}`

I think the problem is here:
react-bative-iap/src/types/appleSk2.ts
![image](https://user-images.githubusercontent.com/60703498/197101124-2e462b73-1284-4adb-97e4-6833153509fe.png)

**Expected Behavior**
The string is printed to the console

**Screenshots**
N/A

**Environment:**

react-native-iap: "12.3.0"
react-native: "0.70.3"
Platforms (iOS, Android, emulator, simulator, device): IOS

**To Reproduce**

1. Paste code within the requestPurchase function
2. On device make an IAP
---

[Optional] **Additional Context**

**Comment by buidinhmanh14799** [comment]
Sample issue

**Comment by andresesfm** [comment]
Thank you @19424056 . Fix here: https://github.com/dooboolab/react-native-iap/pull/2072

**Comment by andresesfm** [comment]
Released as `12.3.2`

**Comment by 19424056** [comment]
Tks @andresesfm
