### ISSUE TITLE
requestSubscription sku=prod_A_1YEAR but not yet finishTransaction, error can't buy that package anymore with sku=prod_A_1YEAR

### ISSUE THREAD

**Issue by 19424056** [dooboolab/react-native-iap#2067]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
storekitMode: 'STOREKIT_HYBRID_MODE'
ios 16 -> storeKit 2

first, requestSubscription with sku=prod_A_1YEAR
next, login account apple Store is requied, show alert successfully purchases with purchase from purchaseUpdatedListener
{
    productid: "prod_A_1YEAR"
    transactionId: "2000000815290884",
    transactionDate: 1666316197000, //??
    transactionReceipt: '', 
    purchaseToken: '',
    quantityIOS: 1,
    originalTransactionDateIOS: 166626173200
   originalTransactionIdentifierIOS: "2000000815290884",
}
after that,   not yet finishTransaction for some reason //testing
end, requestSubscription again with sku=prod_A_1YEAR, login account apple Store is not required
purchase from purchaseUpdatedListener identical first time
{
    productid: "prod_A_1YEAR"
    transactionId: "2000000815290884",
    transactionDate: 1666316197000, //??
    transactionReceipt: '', 
    purchaseToken: '',
    quantityIOS: 1,
    originalTransactionDateIOS: 166626173200
   originalTransactionIdentifierIOS: "2000000815290884",
}

even though Receipt expires, Can't buy that package again

![image](https://user-images.githubusercontent.com/60703498/197117861-df3981da-1c4a-4226-aea9-28b4439e763e.png)

**Expected Behavior**
The string is printed to the console

**Screenshots**

**Environment:**

- react-native-iap:"12.3.0"
- react-native:"0.70.3"
- Platforms (iOS, Android, emulator, simulator, device):IOS

**To Reproduce**

1.Paste code within the requestPurchase function
2.On device make an IAP

---

[Optional] **Additional Context**

**Comment by buidinhmanh14799** [comment]
Sample issue

**Comment by 19424056** [comment]
this is not related to as https://github.com/dooboolab/react-native-iap/issues/2066

this only happens when i requestSubscription but not finishTransaction in event purchaseUpdatedListener . 
after that requestSubscription again then login account apple Store is not required, 
in event purchaseUpdatedListener i get purchase is  identical first time

{
productid: "prod_A_1YEAR"
transactionId: "2000000815290884",
transactionDate: 1666316197000, 
transactionReceipt: '',
purchaseToken: '',
quantityIOS: 1,
originalTransactionDateIOS: 166626173200
originalTransactionIdentifierIOS: "2000000815290884",
}

even though this purchase expired, Can't buy that package again

**Comment by 19424056** [comment]
@andresesfm 

Case transaction has not been finishTracsaction, will this transaction be canceled and refunded?

**Comment by andresesfm** [comment]
correct, if it's not finished, it'll get refunded by the store
