### ISSUE TITLE
 Undefined is not an object (evaluating 'skus.includes')

### ISSUE THREAD

**Issue by gauravjainn** [dooboolab/react-native-iap#2069]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
import * as RNIap from "react-native-iap";

  RNIap.initConnection().then(() => {
      RNIap.getSubscriptions(itemSkus)
        .then((res) => {
          console.log(itemSkus);
          // console.log("res---", res);
        })
        .catch((err) => {
          console.log("err--", err);
        });
    });

**Expected Behavior**

please help me to get list of subscription

**Screenshots**

**Environment:**

- react-native-iap:12.3.0
- react-native:0.68.2
- Platforms (iOS, Android, emulator, simulator, device): simulator

---

[Optional] **Additional Context**

**Comment by Skr1pt1k** [comment]
Use like this `await getSubscriptions({ skus: this.itemSkus });`
