### ISSUE TITLE
Invalid Product ID error on IOS

### ISSUE THREAD

**Issue by ilysorc** [dooboolab/react-native-iap#207]
### Version of react-native-iap
"react-native-iap": "^0.3.24",
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
buying a product
### Actual behavior
returns always invalid product Id error.
### Tested environment (Emulator? Real Device?)
Emulator.
### Steps to reproduce the behavior
I added my first in app purchase feature and i waited for a week but it always returns Invalid Product Id error. 

<img width="270" alt="screen shot 2018-07-16 at 20 41 58" src="https://user-images.githubusercontent.com/2563790/42775048-12aafcf0-893c-11e8-9d94-438195235e8b.png">
<img width="1007" alt="screen shot 2018-07-16 at 20 43 19" src="https://user-images.githubusercontent.com/2563790/42775055-183bc398-893c-11e8-9052-76277cded4e9.png">

**Comment by dooboolab** [comment]
@ilysorc That is expected behavior. You can't test the actual purchase in the simulator. Also refer to [medium](https://medium.com/@dooboolab/react-native-in-app-purchase-121622d26b67), your iap status should be `Ready to submit`.

**Comment by ilysorc** [comment]
@dooboolab thank for your reply. i checked medium now. first step says "You need to complete the Payments and Financial Reports" but i clicked this menu i only see reports. How can i configure these steps?
<img width="1298" alt="screen shot 2018-07-17 at 21 34 15" src="https://user-images.githubusercontent.com/2563790/42838484-9f7304fc-8a09-11e8-95a0-4f16450b3cc4.png">

**Comment by dooboolab** [comment]
Oops. I meant you need to complete the `Agreements, Tax and Banking`. Sorry for that.

**Comment by ilysorc** [comment]
@dooboolab thank you. that is fixed problem.

**Comment by JJMoon** [comment]
I guess the issue was resolved. I am closing this issue.

**Comment by blaues0cke** [comment]
I sill have this issue. Can receive consumable products and subscriptions without any problems. Even buying subscriptions is working pretty well. Only the `RNIap.buyProduct('any sku even the ones from .getProducts()');` result in:

```
IAP: Error Error: Invalid product ID.
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:400)
    at MessageQueue.js:139
    at MessageQueue.__guardSafe (MessageQueue.js:316)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:138)
    at t (RNDebuggerWorker.js:1)
```

Do you have any idea? Have no pending contracts, the in app purchases are "Ready to submit" and I am using a working sandbox account.
