### ISSUE TITLE
Android requestPurchase looking for skus instead of sku

### ISSUE THREAD

**Issue by cjbland** [dooboolab/react-native-iap#2074]
**Description**

The `requestPurchase` for Android appears to be looking for `skus` instead of `sku` when requesting a purchase.

**Expected Behavior**

The Android `requestPurchase` experience should be the same as iOS and Amazon.

**Screenshots**

https://github.com/dooboolab/react-native-iap/blob/50ff5aaeb3204e64b6a6e67011c836cbe3a27a80/src/iap.ts#L609

**Environment:**

- react-native-iap: 12.1.2
- react-native: 0.70.3
- Platforms (iOS, Android, emulator, simulator, device): Android, Google Pixel 6

**To Reproduce**

1. Run the IapExample on an Android device

**Comment by cjbland** [comment]
This appears to be a duplicate of https://github.com/dooboolab/react-native-iap/issues/2061 but it would be nice if the APIs were consistent across stores.

**Comment by andresesfm** [comment]
Google Play takes an array of skus, Apple's Appstore takes a single sku, how would you make them consistent?

**Comment by cjbland** [comment]
Thanks for that info, I was not aware of the differences between the two stores. Then it would be nice if the documentation pointed out that the method signature is different when requesting a purchase on iOS versus Android:

https://react-native-iap.dooboolab.com/docs/api/modules#usage-8

That example makes it seem like the same `requestPurchase({sku})` method signature is valid for all requests when it is not.

**Comment by andresesfm** [comment]
Good suggestion. We are open to all PRs if you'd like to contribute
