### ISSUE TITLE
Android - requestSubscription return Boolean instead of SubscriptionPurchase

### ISSUE THREAD

**Issue by thuongtv-vn** [dooboolab/react-native-iap#2076]
**Description**

Android: `requestSubscription` API return a boolean value when successful.

**Expected Behavior**

Return an object `SubscriptionPurchase `

**Screenshots**

**Environment:**

- react-native-iap: 12.3.0
- react-native: 0.63.4
- Platforms: Android Device 

**To Reproduce**

1. request subscription by using `requestSubscription`
2. log the request result.
3. result is a boolean value.

As documentation the result of this api request should be an `SubscriptionPurchase` object or `null`, `void`:
https://github.com/dooboolab/react-native-iap/blob/50ff5aaeb3204e64b6a6e67011c836cbe3a27a80/src/iap.ts#L711

**Comment by andresesfm** [comment]
fix available on `12.3.2`
