### ISSUE TITLE
ios - calling requestSubscription doesn't do nothing

### ISSUE THREAD

**Issue by kobishaked1** [dooboolab/react-native-iap#2077]
**Description**

Using the requestSubscription method in android works just fine and opens the popup to make the purchase. however, in ios, nothing happens. it doesn't return any value or error and also doesn't trigger the purchaseErrorListener

**Expected Behavior**

open apple subscription popup

**Screenshots:**

<img width="313" alt="image" src="https://user-images.githubusercontent.com/102145822/197488699-de1d34b8-216c-4075-a257-29f9259a30d5.png">

**Environment:**

- react-native-iap: 12.1.1
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): iPhone xr (version 16), physical device

**To Reproduce**

1. on ios device version 16 make a call to: await requestSubscription({sku: PRODUCT_ID});
2. you will notice that nothing happen

**Comment by andresesfm** [comment]
It's not my experience, It's working fine on the IapExample app

**Comment by kobishaked1** [comment]
it was fixed by adding the line:
`setup({storekitMode:'STOREKIT_HYBRID_MODE'})`
right before the initConection method
now the popup is coming up but I have another issue. the purchaseUpdateListener is not triggered after I get a popup that approves the payment. 
here is whole code of the listeners and the requestSubscription method:
```
useEffect(() => {
    if (!PRODUCT_ID) {
      return;
    }

    let purchaseUpdateSubscription: EmitterSubscription | undefined;
    let purchaseErrorSubscription: EmitterSubscription | undefined;

    getSubscriptions({skus: [PRODUCT_ID]})
      .then(prods => {
        if (!prods || prods.length === 0) {
          return;
        }

        if (Platform.OS === 'android') {
          offerTokenRef.current =
            prods[0].subscriptionOfferDetails[0]?.offerToken;
        }

        setGotProduct(true);

        purchaseUpdateSubscription = purchaseUpdatedListener(async purchase => {
          console.log(
            `the purchase we get from purchaseUpdatedListener: ${purchase}`,
          );
          await sendPayment({
            purchase,
            onSuccess: () => {
              setUser(userObj => ({
                ...userObj!,
                isFree: false,
                plan: 'Premium',
              }));
              navigation.dispatch(CommonActions.goBack());
            },
          });

          try {
            finishTransaction({purchase});
          } catch (error) {
            console.error(error);
          }
        });
        purchaseErrorSubscription = purchaseErrorListener(error => {
          console.error('purchaseErrorListener', error);
        });
      })
      .catch(e => console.error(e));

    return () => {
      purchaseUpdateSubscription?.remove();
      purchaseErrorSubscription?.remove();
    };
  }, [setUser, navigation]);

  const purchaseSubscription = async () => {
    if (!PRODUCT_ID || isPaymentOpen) {
      return;
    }
    setIsPaymentOpen(true);

    try {
      if (Platform.OS === 'ios') {
        await IapIos.clearTransactionIOS();
        await requestSubscription({sku: PRODUCT_ID});
      } else {
        await requestSubscription({
          subscriptionOffers: [
            {sku: PRODUCT_ID, offerToken: offerTokenRef.current},
          ],
        });
      }
    } catch (error) {
      console.error('from purchaseSubscription:', error);
    }

    setIsPaymentOpen(false);
  };
```

I really appreciate your help!

**Comment by andresesfm** [comment]
Do you get an error or anything on the logs? Do you get anything returned?

**Comment by amkiran** [comment]
> Do you get an error or anything on the logs? Do you get anything returned?

@andresesfm No errors are recorded in logs and the promise of `requestSubscription` never resolves.

I noticed the same issue on iOS 15 & 16 devices as well, but it's gone after upgrading to `react-native-iap: 12.1.0`.
So the issue now happens only on iOS 14.

**Comment by kobishaked1** [comment]
for me im using ios 16 and react-native-iap 12.1.1 and in some of the case the purchaseUpdatedListener fired and in other cases it doesnt

**Comment by ElicaInc** [comment]
@andresesfm: Thank you for sharing your great libraries!
> @andresesfm No errors are recorded in logs and the promise of `requestSubscription` never resolves.
I occasionally had the same issue (iOS15, react-native-iap 12.0.1) in TestFlight, but adding the line 'await clearTransactionIOS();' just before 'await requestSubscription({sku: productId})' works fine in my setting.

**Comment by andresesfm** [comment]
What `storeKitMode` are you using?

**Comment by ElicaInc** [comment]
> What `storeKitMode` are you using?

setup({storekitMode: 'STOREKIT2_MODE'});

**Comment by herbertvuijk** [comment]
Have this problem too. The problem is that there for some reason calling requestSubscription will first fire purchaseUpdatedListener if there are unfinished transactions. So let's say you have 5 unfinished purchases, trying to requestSubscription will not open the apple subscription popup, but instead cause an event trigger to purchaseUpdatedListener. This happens 4 more times, till everything is finished, only then it works.

My work around is this to call clearTransactionIOS before requestSubsription. Doesn't feel right to me though. 


>     if (Platform.OS === 'ios') {
>       await clearTransactionIOS();
>     }
>     await requestSubscription(obj);

Are there better solutions? I'm looking into using getPendingPurchasesIOS and finish all of them before attempting requestSubscription.

**Comment by andresesfm** [comment]
`getPendingTransactions` issue has been fixed
