### ISSUE TITLE
Type in Documentation Missing? "InAppPurchase"

### ISSUE THREAD

**Issue by princefishthrower** [dooboolab/react-native-iap#2078]
In the first code snippet on https://react-native-iap.dooboolab.com/docs/guides/purchases,

the `purchase` variable is denoted with the following types: `InAppPurchase | SubscriptionPurchase | ProductPurchase`

However, TypeScript can't find `InAppPurchase`:

```
Cannot find name 'InAppPurchase'.ts(2304)
```

Any ideas or pointers here? Happy to do a pull request on the docs as soon as I can figure out where `InAppPurchase` is coming from 😄

**Comment by andresesfm** [comment]
Hello @princefishthrower . You are correct, that documentation needs to be updated. That type has been removed. A PR would be nice 🙂 . Thank you

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/2087
