### ISSUE TITLE
Items is not defined

### ISSUE THREAD

**Issue by StuartMorris0** [dooboolab/react-native-iap#208]
### Version of react-native-iap
Latest

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
No Error

### Actual behavior
Error occurs: Items is not defnied

### Tested environment (Emulator? Real Device?)
Both Emulator and Real Device

### Steps to reproduce the behavior

We have a method setup as follows:
```
  async componentDidMount() {
    console.log('hello');
    const itemSkus = Platform.select({
      ios: [
        'correctcodes',
      ],
      android: [
        'correctcodes',
      ],
    });

    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      this.setState({ items });
      console.log('state');
      console.log(this.state);
    } catch(err) {
      console.log('error occurred');
      console.warn(err.message); // standardized err.code and err.message available
    }
  }
```

I am finding that the console.warn is getting called with Items is not defined. Is the above correct?

**Comment by dooboolab** [comment]
@StuartMorris0 If you are having a problem in just fetching the products, our module may not be properly linked to your project. Please try the manual installation either.

**Comment by dooboolab** [comment]
@StuartMorris0 It will just return an empty array if it fails to fetch the products. Not sure about your symptoms yet.
