### ISSUE TITLE
getAvailablePurchases() not response

### ISSUE THREAD

**Issue by datduong56** [dooboolab/react-native-iap#2081]
**Description**
When i logout sandbox account and call getAvailablePurchases method. It isn't response any thing. If i login sandbox account again it work. In ios 14 and ios 15 when i logout sandbox account and call getAvailablePurchases method it show from login sandbox account

**Expected Behavior**

Show from login sandbox account when user logout sandbox account and call getAvailablePurchases method in ios 16

**Environment:**

- react-native-iap: 12.0.3
- react-native: 0.69.5
- Platforms (iOS, Android, emulator, simulator, device): IOS 16

**To Reproduce**

1. Go to Setting -> App Store -> Log out sandbox account
2. Open app 
3. Call getAvailablePurchases method
4. getAvailablePurchases method is not responding

**Comment by andresesfm** [comment]
What `storekitMode` are you using @datduong56 ?

**Comment by andresesfm** [comment]
Merging with: https://github.com/dooboolab/react-native-iap/issues/2089

**Comment by datduong56** [comment]
Sorry for my late response. I use `STOREKIT1_MODE`
