### ISSUE TITLE
StoreKit2 getPendingPurchasesIOS not working -> wrong mapping in RNIapIosSk2.m and RNIapIosSk2.swift

### ISSUE THREAD

**Issue by herbertvuijk** [dooboolab/react-native-iap#2082]
I
**Description**

I was using getPendingPurchasesIOS. This gives the following error: 

[TypeError: (0, _internal.getIosModule)().getPendingTransactions is not a function. (In '(0, _internal.getIosModule)().getPendingTransactions()', '(0, _internal.getIosModule)().getPendingTransactions' is undefined)]

As you can see getPendingPurchasesIOS resolves to getPendingTransactions. But the function name in RNIapIosSk2.m and RNIapIosSk2.swift is pendingTransactions (no 'get'). 

**Expected Behavior**

I replaces all occurences of pendingTransactions with getPendingTransactions in the IOS module (RNIapIosSk2.m and RNIapIosSk2.swift) and then it worked. Alternatively I guess it can be changed on the RN side. 

**Environment:**

- react-native-iap: 12
- react-native:
- Platforms (iOS, Android, emulator, simulator, device): IOS SK2

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/2085 thank you @herbertvuijk

**Comment by andresesfm** [comment]
released on `12.3.3`
