### ISSUE TITLE
Best practice Idea, my feedback after implementing RN IAP 12 (PurchaseUpdateListener , getPendingTransactionsIOS )

### ISSUE THREAD

**Issue by herbertvuijk** [dooboolab/react-native-iap#2083]
So I found that relying on PurchaseUpdateListener is a bit tricky. It doesn't get called always, and sometimes if a user doesn't open the app for months it will get called a lot of times in case of monthly subscriptions with very old transactions. 

I created a RN side wrapper method called confirmAllPendingAndRefreshEntitlements. It does the following: 
-  getPendingTransactionsIOS (i implemented a similar kotlin method for Android) and finish them synchronous one by one. *
-  Only after they are all finished / confirmed I now proceed with retrieving currentEntitlements (SK2) and getPurchases (android). 

Whenever PurchaseUpdateListener is called I basically ignore the passed Purchase but instead I call my confirmAllPendingAndRefreshEntitlements. I also execute this method on app launch. I do this before adding my PurchaseUpdateListener (since on Android adding a the listener will cause all unfinished transactions to be pushed to the listener). 

This has increased the IAP stability within my app a lot, so I'm curious to hear feedback on this approach. For me it fixed:
- Not opening popups on IOS in case of requestSubscription
- Making sure I get all transactions, because I have seen situations where PurchaseUpdateListener never got called

Lastly: I also implemented an automatic Appstore.Sync in case retrieving currentEntitlements results in a unverified transaction. This is recommended by apple. It appears that in very rare occasions a Appstore.Sync is needed to get currentEntitlements up to date. I implemented an Alert.alert to indicated the user that a popup will open that will ask the Apple ID password. We had complaints coming in from users and the only solution to fix the currentEntitlement was to reinstall the app, with this new Appstore.Sync fallback we now resolved that as well. 

*getPendingTransactionsIOS  is currently broken in the last 12.x release I will submit a pull request for my fix of that.

**Comment by andresesfm** [comment]
Hey @herbertvuijk I'm curious to see the code you implemented, can you post it here?

**Comment by herbertvuijk** [comment]
Hi Andres,

Its pretty simple, it only works with SK2 though.

It fixes the issue of non responding subscription flows on IOS (I see quite some issues about that here).

It also only works on IOS since on Android there are no pending transactions for subscriptions as I found out later.

```

purchaseUpdatedSubscription = purchaseUpdatedListener(async (purchase) => {
  console.log("Updater is called!");
  if (Platform.OS !== "ios") {
    // dont finish the passed purchase here tjere might be more unfinished transactions than just this one, so get them all and finish them all
    await finishPendingIOSTrans();
    // now get current entitlements SK2, I implemented my own function for this that also acts on an unverified transaction with an Appstore.sync
    await getCurrentEntitlementsCustom();
  } else {
    // on android we will not receive any montlhy renewals, you only receive the first subscription.
    // we check serverside for latest status
    await finishTransaction(purchase);
  }
});

const finishPendingIOSTrans = async () => {
// note this function is currently not working in RN IAP #2082
  var purchasesOLD = await getPendingPurchasesIOS();
  if (purchasesOLD != undefined && purchasesOLD != null) {
    for (var i = 0; i < purchasesOLD.length; i++) {
      purchasesOLD[i].transactionId = purchasesOLD[i].id + "";

      await finishTransactions(purchasesOLD[i]);
    }
  }
};

```

**Comment by andresesfm** [comment]
@herbertvuijk I think what you are trying to fix/prevent would most likely only happen on a dev environment. Thank you for posting here. Hopefully, it helps someone.
