### ISSUE TITLE
App store rejection - 

### ISSUE THREAD

**Issue by MarkBlythe** [dooboolab/react-native-iap#209]
### Version of react-native-iap
1.2.5
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
prepare() method should return false with app store restrictions on
### Actual behavior
prepare() method returns true
### Tested environment (Emulator? Real Device?)
real device (iPhone 8)
### Steps to reproduce the behavior

- Set up in app purchases as described in the documentation.

- Turn on parental control by adding app store restrictions to the device.

App Store submission was rejected for the following reason:

> Guideline 1.3 - Safety - Kids Category
> 
> You have selected the Kids category for your app, but it includes access to external content or allows the user to engage in commerce without first obtaining parental permission. Specifically, we found the following in your app:
> 
> - Purchasing in-app purchase products
> 
> Next Steps
> 
> To resolve this issue, please update your app to incorporate a parental gate before the user can access external content or engage in commerce and ensure that the parental gate cannot be disabled.

Is there any way the prepare() method can return a little more data about whether restrictions are enabled on the device. Or at least return false instead of true when App Store has restrictions turned on.

**Comment by JJMoon** [comment]
@MarkBlythe I am afraid to say that this is not the issue of this module.
I didn't go through this document, but what I grasped is 
you should make some steps (obstacles ?) to purchase the products.

https://developer.apple.com/app-store/parental-gates/

**Comment by MarkBlythe** [comment]
@JJMoon Apologies, on further discussion with Apple I realised the rejection was 100% their end not the module. This module is great and I plan to use it again in future projects. It would be awesome if we could identify that restrictions on the device were in place however that would be a feature request and not an issue.
