### ISSUE TITLE
Not able to build the App in xcode 12.4

### ISSUE THREAD

**Issue by cisplRejjak** [dooboolab/react-native-iap#2090]
"react-native-iap": "^12.3.3"
xcode : 12.4

<img width="572" alt="image" src="https://user-images.githubusercontent.com/55873481/199220598-32536aea-1c7f-4da1-9172-cd2821b736cf.png">

<img width="917" alt="image" src="https://user-images.githubusercontent.com/55873481/199220674-342998fc-5dc4-4a99-846e-63a51df70976.png">

**Comment by andresesfm** [comment]
Any reason not to update to the latest XCode?

**Comment by Haider-Ali-7** [comment]
@andresesfm Hi, i'm getting this error after installing this package.

**versions:**
```
xcode: 13.1
react-native: 0.66.4
react-native-iap: ^12.4.6
```

`error: Abort trap: 6 (in target 'RNIap' from project 'Pods')`

Is it packages's related or swift related issue?

**Comment by andresesfm** [comment]
@Haider-Ali-7 not sure it is the same issue described on the ticket. It looks more like a runtime crash. If you have more context, please create a separate ticket

**Comment by Haider-Ali-7** [comment]
Thanks for quick response. Mine is little different. It's actually swift compiler issue and it throws `Abort trap: 6` error. It's a bug in swift. I have created ticket in apple/swift.
