### ISSUE TITLE
amazon getAvailablePurchases return empty array

### ISSUE THREAD

**Issue by andmau90** [dooboolab/react-native-iap#2095]
availableItemsType is always null, there aren't any called methods that set it

`
if (productTypeString == availableItemsType) {
    availableItems.pushMap(promiseItem)
}
`

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/2096

**Comment by andresesfm** [comment]
Released on `12.4.1`
