### ISSUE TITLE
getAvailableItems() is not a recognized Objective-C method error 

### ISSUE THREAD

**Issue by hamart** [dooboolab/react-native-iap#2097]
**Description**

Run example application from `IapExample` folder. 

**Expected Behavior**

List of available purchases is retrieved

**Screenshots**

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-04 at 17 13 43](https://user-images.githubusercontent.com/2163029/199997140-bba990ee-9307-4b54-b641-4dd567f245c6.png)

**Environment:**

- react-native-iap: 12.4.1
- react-native: 0.69.1
- Platforms (iOS, Android, emulator, simulator, device): iOS device (15), iOS simulator (iOS 16)

**To Reproduce**
 
1. Go to Available purchases.
2. Press Get the available purchases
3. Error `getAvailableItems() is not a recognized Objective-C method` is shown

**Comment by atkristin** [comment]
Experiencing same issue on `getAvailablePurchases` as well as `getPurchaseHistory`

react-native-iap: 12.4.0
react-native: 0.66.1
Platforms: iOS device (15), iOS simulator (iOS 16)

**Comment by andresesfm** [comment]
https://github.com/dooboolab/react-native-iap/pull/2098

**Comment by andresesfm** [comment]
Released on `12.4.2`
