### ISSUE TITLE
How to retreive Receipt in SK2 mode? 

### ISSUE THREAD

**Issue by herbertvuijk** [dooboolab/react-native-iap#2102]
I'm probably overlooking something, but I dont receive the transactionReceipt in my purchaseUpdateListener when using SK2. 

How do I get the receipts for the transation(s)?

**Comment by herbertvuijk** [comment]
The reason I need the receipt is to check on Apples backend if the subscription is still valid in case of auto renewing subs. At the moment we only receive the transactions in our backend when people activily use the app. But some people have a monthly sub and then never open the app. 

This makes our back-end unaware if the subscription is still active. And this is a problem because we have some reporting and affiliate payments to affiliate based on the actual status of active subscribers. For Google I already implemented it and it works fine with the receipt. 

So for me its not about any real verification, I just use currentEntitlements and trust that that is alright when it comes to valid subscriptions. 

I will have a look at your link to see if that would help. But there should be a way in SK2 how we can check serverside auto renewing subscription if they are still valid right?

**Comment by saadanii** [comment]
We're also doing a similar check from backend side, and we passed the purchase.transactionReceipt. But after moving to sk2 the transactionReceipt was removed according to documentation. So what I was wondering would be the alternative to that?

**Comment by lvothnrv** [comment]
I also have the same problem, I try to retrieve the receipt to send to my backend so that I can check and store the purchase in my database but so far I can't find a solution with SK2...

**Comment by herbertvuijk** [comment]
So the workaround that I'm using is a function I added myself. If you have any own native module you can add it there, or otherwise add it to RNIap module and create a patch.

Below the function to retrieve latest receipt on IOS. This one I post to my server and with that receipt I can always retrieve all related receipts, e.t.c. In this way I can check server side the actual status of subscriptions without being dependent on whether users open their app or not. 

@objc
    public func getReceiptIOS(
        _ resolve: @escaping RCTPromiseResolveBlock = { _ in},
        reject: @escaping RCTPromiseRejectBlock = {_, _, _ in}
    ) {
        
        if let appStoreReceiptURL = Bundle.main.appStoreReceiptURL,
            FileManager.default.fileExists(atPath: appStoreReceiptURL.path) {

            do {
                let receiptData = try Data(contentsOf: appStoreReceiptURL, options: .alwaysMapped)
                print(receiptData)

                let receiptString = receiptData.base64EncodedString(options: [])

                // Read receiptData.
                resolve(receiptString);
                return;
            }
            catch {
                
                reject("001", "Couldn't read receipt data with error: \(error.localizedDescription)", error)
                return;
            }
        }
        
        resolve("");
    }

**Comment by lvothnrv** [comment]
Alright my friend I will try that thank you very much.

**Comment by lvothnrv** [comment]
> So the workaround that I'm using is a function I added myself. If you have any own native module you can add it there, or otherwise add it to RNIap module and create a patch. To do that:
> 
> * Add function below to the file RNIapIosSk2.swift, for example around line 300 after the endConnection function (see bottom)
> * Add the function in RNIapIosSk2.m (this is the mapping between React Native and the .swift file) like so:
>   RCT_EXTERN_METHOD(getReceiptIOS: (RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject)
> * Now you should be able to call this function from React Native
> 
> This function getReceiptIOS should be in RNIap already according to the documentation, but it is not, I guess it isnt implemented yet.
> 
> Function to retrieve latest receipt, best to do after confirming transactions (finishTransaction)
> 
> ```
> 
> @objc
>     public func getReceiptIOS(
>         _ resolve: @escaping RCTPromiseResolveBlock = { _ in},
>         reject: @escaping RCTPromiseRejectBlock = {_, _, _ in}
>     ) {
>         
>         if let appStoreReceiptURL = Bundle.main.appStoreReceiptURL,
>             FileManager.default.fileExists(atPath: appStoreReceiptURL.path) {
> 
>             do {
>                 let receiptData = try Data(contentsOf: appStoreReceiptURL, options: .alwaysMapped)
>                 print(receiptData)
> 
>                 let receiptString = receiptData.base64EncodedString(options: [])
> 
>                 // Read receiptData.
>                 resolve(receiptString);
>                 return;
>             }
>             catch {
>                 
>                 reject("001", "Couldn't read receipt data with error: \(error.localizedDescription)", error)
>                 return;
>             }
>         }
>         
>         resolve("");
>     }
> ```

Any other changes needed? Just install react-native-iap and add the lines of code you told me and it works? Because it still doesn't work for me :/

**Comment by andresesfm** [comment]
For Sk2 there's no need for validation, the framework does it for you. If all you need is to know if a subscription is still valid, simply check if it's part of `getPurchaseHistory`'s response. It's a lot simpler now

**Comment by rajeshlousigam** [comment]
> To validate subscriptions on the backend when using SK2 I think you should be using the "App Store Server API" (https://developer.apple.com/documentation/appstoreserverapi/get_all_subscription_statuses) with the `originalTransactionId` instead of `https://buy.itunes.apple.com/verifyReceipt` with the `transactionReceipt`. This endpoint returns the same kind of data structure as `Transaction.currentEntitlements` does in app (and it also includes renewal info like `verifyReceipt` does).

Question here. How to get the originalTransactionId?

**Comment by Arttron** [comment]
For receipt for purchases using storekit v1
I used setup method for use v1
setup({ storekitMode: 'STOREKIT1_MODE' }); const historyPurchases = await getPurchaseHistory()

**Comment by kesha-antonov** [comment]
@herbertvuijk thanks for the code

Strangely it returns receipt for old purchase made few hours ago and not recent one

rn-iap also returns same old receipt since uses the same code: https://github.com/hyodotdev/openiap-apple/blob/551d86ad368675440889ea31e03978341eb68fb0/Sources/OpenIapModule.swift#L386

Looks like it is sandbox issue (maybe): https://chatgpt.com/c/68ee4ae3-f22c-8333-b308-9248369159a6

Also receipt used in openiapp-apple is deprecated https://developer.apple.com/documentation/foundation/bundle/appstorereceipturl

And Apple recommends to use this one: https://developer.apple.com/documentation/StoreKit/Transaction
