### ISSUE TITLE
requestPurchase promise doesn't return `Product` for storekit2

### ISSUE THREAD

**Issue by charleschen** [dooboolab/react-native-iap#2107]
**Description**
After a successful call for `requestPurchase` with storekitmode on `STOREKIT2_MODE`, the value returned to the success promise callback is not the interface for `Product`.  From looking at the swift code (https://github.com/dooboolab/react-native-iap/blob/main/ios/RNIapIosSk2.swift#L695) it looks like the code is serializing a transaction, where as storekit1 (https://github.com/discord/react-native-iap/blob/main/ios/RNIapIos.swift#L537) changes the transaction into Product interface.

**Expected Behavior**

`requestPurchase` promise should return the same interface for storekit1 and storekit2 mode.

**Screenshots**

**Environment:**

- react-native-iap: 12.4.4
- react-native:
- Platforms (iOS, Android, emulator, simulator, device):

**Comment by andresesfm** [comment]
Fix here: https://github.com/dooboolab/react-native-iap/pull/2141

**Comment by andresesfm** [comment]
Released on `12.4.8`

**Comment by charleschen** [comment]
thanks!
