### ISSUE TITLE
finishTransaction not working for consumable products on iOS

### ISSUE THREAD

**Issue by LiveXenon** [dooboolab/react-native-iap#2110]
**Description**

`let finishTransactionResult = await finishTransaction({ purchase: purchase, isConsumable: true });`

**finishTransaction** returns **undefined** when called for consumable products on **iOS**. The confirmation is in the [apple store receipt](https://developer.apple.com/documentation/appstorereceipts/) where in the **in_app** field there are all the old purchases (related to consumable products) which should have already been consumed.

<img width="683" alt="Screenshot 2022-11-12 alle 18 30 48" src="https://user-images.githubusercontent.com/34724827/201487038-ff240059-05c8-4233-bdbc-13d270f06053.png">

**Expected Behavior**

Apple documentation instead says:

Determine which products the user purchased. Purchases for non-consumable products, auto-renewable subscriptions, and non-renewing subscriptions remain in the receipt indefinitely. **For consumable products, the transaction is added to the receipt when the purchase is made, and remains until your app finishes that transaction. It no longer appears in updated receipts after you call [finishTransaction(_:)]**

https://developer.apple.com/documentation/appstorereceipts/responsebody/receipt/in_app

**Environment:**

- react-native-iap: 12.4.4
- react-native: 0.66.5
- Platforms: iOS

**Comment by Mahesh9765** [comment]
Facing same issue. Anyone find solution for this?

**Comment by andresesfm** [comment]
The iOS Native SDK doesn't return a result when calling finishTransaction: https://developer.apple.com/documentation/storekit/skpaymentqueue/1506003-finishtransaction
I have updated the code to always return `true` instead of undefined https://github.com/dooboolab/react-native-iap/pull/2139

**Comment by andresesfm** [comment]
Change released on `12.4.7`. Let me know/reopen if any other issues
