### ISSUE TITLE
Purchase dialog hangs in Amazon Fire devices on Live App Testing

### ISSUE THREAD

**Issue by dduranalba** [dooboolab/react-native-iap#2113]
**Description**
Everything works as expected while testing locally using Amazon's App Tester. However, after promoting the app to Amazon's Live App Testing, I'm experiencing a weird issue where the purchase dialog doesn't show up after calling requestSubscription method. It would just hang. 

This is what I get from looking at the logcat that seems related:

`D/Kiwi: ForegroundTaskPipeline: No UI visible to execute task: com.amazon.device.iap.internal.a.e.a$1@aa2220c, placing into pending queue until task is visible`

The only way I can get the dialog to show is by clicking on the Overview/Recents square button in Android's navigation(let's you access other apps that are open) that would eventually force the app to go the background. When the app comes back to the foreground, the dialog will show and will keep showing normally.

I wonder if this is happening to someone else in the community.

I have implemented IAP(Subscriptions)  for both Google and Apple Stores and they work just fine. This issue only happens on Amazon IAP.

**Expected Behavior**

Purchase dialog should pop up when calling requestSubscription method.

**Environment:**

- react-native-iap: 12.4.4
- react-native: 0.65.1
- Platforms (Android): Fire OS

**Comment by andresesfm** [comment]
Looks like some other people are also having this issue independent of this library: https://amazon.developer.forums.answerhub.com/questions/244933/iap-library-migration-iaps-work-fine-with-app-test.html

**Comment by dduranalba** [comment]
> Hello @dduranalba , are you able to reproduce this with the IapExample app?

Thank you for your reply. I will test the IAPExample in Amazon's App Live Testing environment and I will post my results. Unfortunately Amazon's support takes forever to reply. As you can see I also left a comment on the link you posted a while ago and still haven't got any response

**Comment by andresesfm** [comment]
I have found a solution. Created the following PR: https://github.com/dooboolab/react-native-iap/pull/2200 I hope it helps @dduranalba

**Comment by andresesfm** [comment]
Merged and released
