### ISSUE TITLE
Subscription upgraded and downgrade 

### ISSUE THREAD

**Issue by shivanitp** [dooboolab/react-native-iap#2115]
I'm using the 12.3.2 version of iap library 

after adding the subscriptionOffers in RNIap.requestSubscription upgraded and downgrading the subscription not working.
can anyone help me with this?

after updating or downgrading the plan it's not canceling the old subscription plan and the new subscription plan gets started 

hear is my code which I'm performing 
const subscriptionOffers = [{
                            sku,
                            offerToken, (new buying subscription offer token)
                        }]
                        purchase = await RNIap.requestSubscription({ subscriptionOffers } false, subId, oldPurchaseToken, ProrationModesAndroid.IMMEDIATE_AND_CHARGE_PRORATED_PRICE);

I'm stuck in this help me

**Comment by andresesfm** [comment]
Are the two subscriptions part of the same group @shivanitp ?

**Comment by ismail-sk** [comment]
> Are the two subscriptions part of the same group @shivanitp ?

My is have two offers for one subscription.
how can open billing window for one of offer?
example: i wanted pay for "formattedPrice": "₺123,89"

 edited answer of getSubscriptions():
```
[
    {
        "subscriptionOfferDetails": [
            {
                "pricingPhases": {
                    "pricingPhaseList": [  /** this is OFFERS (ONE is same of Base plan) **/
                        {
                            "recurrenceMode": 2,
                            "priceAmountMicros": "123890000",
                            "billingCycleCount": 1,
                            **"billingPeriod": "P1Y",** /** in play console ID: ark-gold-12m  **/
                            "priceCurrencyCode": "TRY",
                            **"formattedPrice": "₺123,89"**
                        },
                        {
                            "recurrenceMode": 1,
                            "priceAmountMicros": "14990000",
                            "billingCycleCount": 0,
                            **"billingPeriod": "P1M",**  /** in play console ID: ark-gold-base  **/
                            "priceCurrencyCode": "TRY",
                            **"formattedPrice": "₺14,99"**
                        }
                    ]
                },
                "offerTags": [
                    "ay",
                    "base",
                    "gold",
                    "teklif",
                    "year"
                ],
                "offerToken": "AUj/Yhhuh4KVCBPxg+cSA27zOTmcvhs3Upf1Q20KMZlU97RL0KaLPFvFSbCBVF/xZcHhFwk5nP191mwcXpNndsXZOfPR2AZyT8MADqe4gLZh4V6XUD0tyZVU6KHYddVqMUE54LunNEJ92Kdl9g=="
            },
            {
                "pricingPhases": {
                    "pricingPhaseList": [ /** this is BASE plan **/
                        {
                            "recurrenceMode": 1,
                            "priceAmountMicros": "14990000",
                            "billingCycleCount": 0,
                            "billingPeriod": "P1M", /** in play console ID: ark-gold-base  **/
                            "priceCurrencyCode": "TRY",
                            "formattedPrice": "₺14,99"
                        }
                    ]
                },
                "offerTags": [
                    "ay",
                    "base",
                    "gold"
                ],
                "offerToken": "AUj/YhhhwNlCfuI/DhD3qt0Qx+FUeyQ2miBoNkK6HgT25f8y3V0pAB4yZGQcPZ7KQgFMzftjJg2nTqs4ijklw50X9Dmsa93tLpNpWap7NA6NLu3o6GoyvkbVjNF3rA3qpXkNblaMSw=="
            }
        ],
        "name": "Ark Gold",
        "productType": "subs",
        "description": "",
        "title": "Ark Gold (ark)",
        "productId": "ark_gold_class",
        "platform": "android"
    }
]
```

**Comment by dhameliyadharmesh** [comment]
I'm using the 12.11.0 version of iap library

Using this code: 
await requestSubscription({
            sku: productId , \\ new product id
            purchaseTokenAndroid: oldPurchaseToken, // Purchased token
            prorationModeAndroid: ProrationModesAndroid.IMMEDIATE_AND_CHARGE_PRORATED_PRICE,
            ...(offerToken && {
              subscriptionOffers: [{ sku: productId, offerToken }],
            }),
          });

Let me know what's the wrong here,
i'm getting error "something wen wrong on our end, Please try again" in Android, Screenshot attached.

[
<img width="352" alt="Screenshot 2023-12-19 at 1 27 30 PM" src="https://github.com/dooboolab-community/react-native-iap/assets/50448775/ffb9257a-d472-4aed-a766-233bf103eb05">
](url)

**Comment by nl-danish** [comment]
Hi @dhameliyadharmesh,

Were you able to found any solution? 
Please, let us know, we're struggling with the same issue.

Here's my thread; https://github.com/dooboolab-community/react-native-iap/issues/2757

**Comment by dhameliyadharmesh** [comment]
Do not use this package. it is not working at all in iOS production properly.

**Comment by nl-danish** [comment]
Hi @dhameliyadharmesh,

Sorry I've been on leave, could you please tell us what package did you used instead?
Another thing i wanted to ask was, if not IOS, did it work for Android? If yes, was the bug that you encountered was fixed?

Please let us know,
Thanks.

**Comment by devteam-technolabs** [comment]
Encountered same issue on android

**Comment by Nikhil-MathBud** [comment]
purchaseTokenAndroid: oldPurchaseToken
or new Purchase Token

**Comment by Nikhil-MathBud** [comment]
Hi @devteam-technolabs did you found the solution.
Stuck at same issue..

**Comment by Nikhil-MathBud** [comment]
Hi @andresesfm can you please help us with the issue, were you able to find the solution??

**Comment by Nikhil-MathBud** [comment]
Hi @dhameliyadharmesh , Facing similar issue, 
can u help. Here's my thread:- https://github.com/hyochan/react-native-iap/issues/2940
