### ISSUE TITLE
IAP.requestPurchase() need to pass different params between two platform.

### ISSUE THREAD

**Issue by StevenChen0824** [dooboolab/react-native-iap#2120]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
In Document, it seems you just call requestPurchase({ sku: productId }) with any object with sku key. But in fact you if on android, 
the params you need to pass turn to { skus: [productId ]}. Is it expected behavior, but not mention in docs. Or a bug?

**Expected Behavior**
on both platform, the params pass into requestPurchase() should be the same { sku: productId }

**Screenshots**
<img width="340" alt="image" src="https://user-images.githubusercontent.com/47494983/203232664-241bec26-9918-4df5-bb81-a04830a698d7.png">

**Environment:**

- react-native-iap: "12.4.4"
- react-native:"0.65.3"
- Platforms (iOS, Android, emulator, simulator, device):

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
This is not possible as Playstore takes an array of skus where as ios only takes a single string
