### ISSUE TITLE
finishTransaction and getReceiptIOS don't work

### ISSUE THREAD

**Issue by lvothnrv** [dooboolab/react-native-iap#2121]
Hello, I have a bug with finishTransaction and getReceiptIOS for IOS, these modules are not working.., I'm on the latest version of react-native-iap.

- react-native-iap: 12.4.4
- react-native: "0.69.7
- Platforms (iOS, Android, emulator, simulator, device): iOS

**Comment by andresesfm** [comment]
https://github.com/dooboolab/react-native-iap/issues/2110
