### ISSUE TITLE
purchaseHistory transactionDate returning string instead of number

### ISSUE THREAD

**Issue by sasweb** [dooboolab/react-native-iap#2122]
**Description**

given `const { purchaseHistory } = useIAP()` the transaction date is returned in a weird format (at least on iOS).
For example `purchaseHistory[0].transactionDate` is returning `'1669123563000.0'` (string with decimal) instead of `1669123563000`. This is very critical because date based calculations may not work properly.

**Expected Behavior**

`transactionDate` should be an absolute number as defined in the types.

**Screenshots**

This screenshot is from production. Affecting multiple users.

![screenshot](https://user-images.githubusercontent.com/15066762/203349088-e08d699e-8b29-4796-bb60-35d5b0054ad7.png)

**Environment:**

- react-native-iap: 12.3.2
- react-native: 0.70.3
- Platforms (iOS, Android, emulator, simulator, device): iOS, Android untested

**To Reproduce**
Log purchaseHistory on iOS

**Comment by andresesfm** [comment]
Proposed fix: https://github.com/dooboolab/react-native-iap/pull/2133

**Comment by andresesfm** [comment]
Released in `12.4.5`

**Comment by jeroenptrs** [comment]
Could this be reopened? `getPendingTransactions` is still returning a string
https://github.com/dooboolab-community/react-native-iap/blob/d72ce491d3525f4cf5d8175ae0d76c9107988632/ios/RNIapIos.swift#L316
