### ISSUE TITLE
Error: Invalid product ID.

### ISSUE THREAD

**Issue by simranjeetsingh** [dooboolab/react-native-iap#2123]
We are integrating IOS In-App Purchase in react native app using this npm module

and keeps getting errors about invalid product ID

followed all these steps

1.  Completed an effective "Agreements, Tax, and Banking."
3. Setup sandbox testing account in "Users and Roles."
4. Signed into iOS device with sandbox account.
5. Set up three In-App Purchases with the following status:
6. i. Ready to Submit
7. ii. Missing Metadata
8. iii. Waiting for Review
9. Enable "In-App Purchase" in Xcode "Capabilities" and in Apple Developer -> "App ID" setting.
10. Delete app / Restart device / Quit "store" related processes in Activity Monitor / Xcode Development Provisioning Profile -> Clean -> Build
11. Attempt RNIap.buyProduct('com.app.product.id') for each product all throwing the same error.

but still getting the same error
Can anyone help me to find the real issue

- react-native-iap:12.4.4 (also tried lower versions)
- react: 17.0.2 
- react-native: 0.66.3
- Platforms (iOS, Android, emulator, simulator, device):

**Comment by andresesfm** [comment]
You have to call `getProducts([your id])` before calling `buyProduct(your id)`
