### ISSUE TITLE
Incomplete documentation for a beginner

### ISSUE THREAD

**Issue by finom** [dooboolab/react-native-iap#2129]
Thank you for your work!
I'm trying to figure out how IAP works and [I need to choose](https://react-native-iap.dooboolab.com/docs/get-started#android) between "With Android Support" and "With AndroidX". Since I'm a beginner (I came from web) I have no idea what to choose. Can you help me and update the docs with new information? Thank you!

**Comment by andresesfm** [comment]
@finom Those docs are designed to be copied and pasted on your android `build.gradle` files. You need both, not one or the other. I hope this helps. Let me know if you have any questions

**Comment by akuul** [comment]
I believe none of these are relevant for RN 0.72+, correct ? At least the example project doesn't use them anymore, hence making docs confusing for beginners.
