### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): Error: E_IAP_NOT_AVAILABLE in IOS 

### ISSUE THREAD

**Issue by iasreact1** [dooboolab/react-native-iap#2135]
My react-native -0.67.3
react-17.0.2
react-native-iap -8.0.5 
Some days before when i upload the project to the appstore  it was ok Everything , I can able to get the products as well the subscriptions .. But suddenly i am getting a warning message 
Possible Unhandled Promise Rejection (id: 0):
Error: E_IAP_NOT_AVAILABLE
and the prodcut and the subscription list are coming [] , an empty array ...Can some one help me to fix that issue or what to do that i can able to get the products ... i also trying changing the react-native-iap-8.0.8 but the same result happens here...please help...

**Comment by rakeshramaniskythread** [comment]
Getting same issue and not able to open the ios subscription.

**Comment by pashanhenlei** [comment]
in my case, I just re-run 'pod install' and make sure the output contains "Installing RNIap", and the error is gone.
