### ISSUE TITLE
"skus" is required

### ISSUE THREAD

**Issue by Muhammadmahadsaeed** [dooboolab/react-native-iap#2142]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
I have successfully uploaded app on play store with (billing) permission and created package at in app product section. when call getProduct function, it gives me a error "skus is required". I don't understand why 

**Expected Behavior**

**Screenshots**

**Environment:**

- react-native-iap:
- react-native:
- Platforms (iOS, Android, emulator, simulator, device):

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
Updated documentation: https://github.com/dooboolab/react-native-iap/pull/2143
