### ISSUE TITLE
getAvailablePurchases does not return the latest transaction receipt

### ISSUE THREAD

**Issue by iamrohitagg** [dooboolab/react-native-iap#2147]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
I am using getAvailablePurchases function to get the latest purchase for iOS. But it does not return the latest receipt.

**Expected Behavior**
The function must return the latest purchase made by the user.

**Environment:**
- react-native-iap:"^12.4.8"
- react-native:"0.67.3"
- Platforms (iOS, Android, emulator, simulator, device):

**Code**
```
const purchases = await getAvailablePurchases({
                onlyIncludeActiveItems: true,
              });
        const sortedAvailablePurchases = purchases.sort(
          (a, b) => b.transactionDate - a.transactionDate,
        );
        const latestAvailableReceipt =   sortedAvailablePurchases[0]

```
The variable latestAvailableReceipt depicts the latest receipt.

**Comment by c-info** [comment]
this.purchaseUpdateSubscription = purchaseUpdatedListener((purchase: SubscriptionPurchase | ProductPurchase) => {
				console.log("purchaseUpdatedListener=====>")
				const receipt = purchase.transactionReceipt;
				});
				
				
receipt returns empty in iOS sandbox account

**Comment by hristo0624** [comment]
@c-info 

I can see same result with the iOS sandbox account.

Then with that empty receipt, how can I test the receipt validation on the server?

**Comment by homiis** [comment]
@hristo0624 Did you ever figure this out? I am also getting empty `transactionReceipt` when testing.

**Comment by homiis** [comment]
@andresesfm can you advise on this? Should `transactionReceipt` be empty when testing in TestFlight?

**Comment by andresesfm** [comment]
That's correct
