### ISSUE TITLE
I can't execute command "./gradlew bundleRelease" in android

### ISSUE THREAD

**Issue by Yeonbin** [dooboolab/react-native-iap#2151]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
I want to make in app function using this library. So I install 'react-native-iap' module. And I follow every direction to use this library. But I didn't execute "./gradlew bundleRelease" command. 
I follow these things:
1. add "minSdkVersion = 24, supportLibVersion = "28.0.0", kotlinVersion = "1.5.0", androidXAnnotation = "1.1.0", androidXBrowser = "1.0.0" " in android/build.gradle file. 
2. add dependencies "classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"" in android/build.gradle file.
3. add "missingDimensionStrategy "store", "play"" line in android/app/build.gradle file.

**Expected Behavior**
I want to connect store (app store, play store) and I want to get products' information.
And I want to make .aab file using './gradlew bundleRelease' command.

**Screenshots**
<img width="606" alt="image" src="https://user-images.githubusercontent.com/10930647/205577472-aafa06e5-4a9b-4672-88c6-f9032b86faa7.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/10930647/205577725-9e3b3183-35e8-43d5-82e0-56788fdad1a2.png">
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/10930647/205578294-581396ab-657f-4e4d-a773-0e212ee54621.png">

**Environment:**

- react-native-iap: "^12.4.8"
- react-native: "0.68.2"
- Platforms (iOS, Android, emulator, simulator, device): android emulator

**Error Message**
> Task :react-native-iap:generatePlayReleaseRFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-iap:generatePlayReleaseRFile'.
> Could not resolve all files for configuration ':react-native-iap:playReleaseCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-release.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=release, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find react-native-0.71.0-rc.0-release.aar (com.facebook.react:react-native:0.71.0-rc.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.71.0-rc.0/react-native-0.71.0-rc.0-release.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 3 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
@Yeonbin the error states:
> Could not find react-native-0.71.0-rc.0-release.aar 
That's not related to this library

**Comment by Yeonbin** [comment]
> @Yeonbin the error states:
> 
> > Could not find react-native-0.71.0-rc.0-release.aar
> > That's not related to this library

I just think the main was "react-native-iap:generatePlayReleaseFile Failed".
But main error was that you mentioned. Thank you! I fixed it!

I have another question. Is my code correct? Or is there any error to fixed?

**Comment by andresesfm** [comment]
You should probably change your import to 
` import * as IAP from 'react-native-iap'` or import the methods directly
