### ISSUE TITLE
getProducts response payload has missing fields on android

### ISSUE THREAD

**Issue by fitimbyttyqi** [dooboolab/react-native-iap#2154]
**Description**
Hey guys, thanks for creating this awesome package and always thankful for the supporting you give.

I'm having a weird issue calling getProducts function. 
The response that comes from android has some missing fields (two of them which are price and currency) unlike response from IOS.

**Expected Behavior**
When calling getProducts, I expect the response to have the same fields from ProductCommon type which both ios and android extends from.

**Screenshots**
This is the response when calling from android.

<img width="547" alt="Screen Shot 2022-12-06 at 10 37 03" src="https://user-images.githubusercontent.com/61948517/205874695-6c2d2360-3de4-4ad7-b235-e78f662b42ac.png">

This is the response when calling from ios (same products).

<img width="647" alt="Screen Shot 2022-12-06 at 10 39 18" src="https://user-images.githubusercontent.com/61948517/205875222-f721be40-dffb-4446-8df5-121101a2821f.png">

As you can see price and currency are missing in android payload.

**Environment:**

- react-native-iap: 12.4.9
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): IOS, Android, Testing Device

**To Reproduce**

1. Call getProducts from useIAP hook.
2. Console.log(products);
3. Notice that the response is a bit different regarding some fields

---

**Additional Context**
I'm not sure if this is a package issue or the configuration on playstore/appstore but Im sure i've set the prices and currency for the iap products.

Also as you can notice the price is 9.99EUR but in the response payload is returning the price in dollar.
<img width="1100" alt="Screen Shot 2022-12-06 at 10 44 27" src="https://user-images.githubusercontent.com/61948517/205876518-fc5e1cce-3488-4636-a9f3-b74e7035c11a.png">

**Comment by fitimbyttyqi** [comment]
@andresesfm Thanks a lot for the information. 

One more question, about the price, I've set the currency to EUR but its returning $, any idea why is that happening?

**Comment by andresesfm** [comment]
Your screenshot of the price in EUR doesn't match the product Id of the json response

**Comment by fitimbyttyqi** [comment]
@andresesfm Yeah, but there is a product underneath with that Id and different price, I just didn't screenshot them all.

Do you think that has to do with PlayStore location ? the way the currency in response returns?

**Comment by andresesfm** [comment]
> @andresesfm Yeah, but there is a product underneath with that Id and different price, I just didn't screenshot them all.
> 
> Do you think that has to do with PlayStore location ? the way the currency in response returns?

It's based on the device location

**Comment by fitimbyttyqi** [comment]
@andresesfm Okay, thanks a lot once more for the explanation :)
