### ISSUE TITLE
Android: purchase Subscription error: "subscriptionOffers are required for Google Play Subscriptions"

### ISSUE THREAD

**Issue by alexkendall** [dooboolab/react-native-iap#2155]
**Description**

Calling `RNIap.requestSubscription({
            sku: productId,
            andDangerouslyFinishTransactionAutomaticallyIOS: false,
        })` results in an error being thrown: "subscriptionOffers are required for Google Play Subscriptions"

**Expected Behavior**

Subscription is able to validate.

**Environment:**

- react-native-iap: 11.0.0-rc.7
- react-native: ^0.70.1
- Platforms: Android device

**To Reproduce**
Try to subscribe to a valid subscription with sku specified. (Works on iOS)

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
The error message is correct. Works as expected

**Comment by axelmy318** [comment]
Hello, did you manage to get it working  ? I get the same error

**Comment by erkie** [comment]
@andresesfm what's the solution?

**Comment by andresesfm** [comment]
The solution is to pass subscriptionOffers

**Comment by andresesfm** [comment]
This is not a limitation important by this library. It's a newish requirement by the native SDK

**Comment by ton21** [comment]
> subscriptionOffers

how to to that?

**Comment by zkerkeb** [comment]
@andresesfm you must be the worst contributor i have ever encounter, what is the point of contributing in a community RN packages if you do not want to give answers to the community, what kind of response is 

> The error message is correct. Works as expected

are you missing the point of the question or are you deliberately disrespecting the community using this package ? and when I see how the documentation is made I really wonder if you want people to use this lib ? Thank you for the work done but do it well or let your position to someone who actually cares helping the community.

**Comment by zkerkeb** [comment]
For anyone wondering how to solve this error you need to pass the _offerToken_ (each subscription have one) in the subscription object sent by google play, _offerToken_  is in the  _subscriptionOfferDetails_  array, 

according to one exemple found in the repo  you need to pass the offerToken linked to the subscription in the _requestSubscription_ method, 

here is the exemple

```
  await requestSubscription({
        sku, // the product id
        ...(offerToken && {
          subscriptionOffers: [{sku: sku, offerToken}],
        }),
      });
```
the offerToken is not necessary for Ios that is why we conditionnaly add it if we send it to the function, hope this helps.

**Comment by tkapu** [comment]
Thank you @zkerkeb That works perfectly!

**Comment by anatooly** [comment]
subscriptionOffers: [{sku: **productId or basePlanId**, offerToken}] ?

**Comment by sparkison** [comment]
Thanks to @zkerkeb, the following worked for me! 

I wasn't sure where the `offerToken` was coming from in the examples, here's how I got it, hopefully help some others too 😉 

```JS
const sku = product.productId
const offerToken = Platform.OS === 'android'
    ? product.subscriptionOfferDetails[0]?.offerToken || null
    : null
await requestSubscription({
    sku,
    ...(offerToken && {
        subscriptionOffers: [{sku, offerToken}],
    }),
})
```

**Comment by Magotrox** [comment]
Thanks to @zkerkeb and @sparkison. Now it works!!!
