### ISSUE TITLE
Setup storekitMode blocks debugger

### ISSUE THREAD

**Issue by professorkolik** [dooboolab/react-native-iap#2156]
**Description**

When we execute 
`setup({ storekitMode:  <store_kit_mode> });`

We no longer able to use Debugger in debug mode.

**Expected Behavior**

When setting storekit mode, debug is not broken

**Screenshots**

<img width="868" alt="Screenshot 2022-12-11 at 22 49 56" src="https://user-images.githubusercontent.com/7031202/206930886-9b1fc12c-ed06-4c2b-aef7-e02fe0dba7a1.png">

**Environment:**

- react-native-iap: 12.4.8
- react-native: 0.69.7
- Platforms (iOS, Android, emulator, simulator, device): iOS 16.1 simulator
- React Native Debugger: 0.13.0

**To Reproduce**

1. Enable debug mode in simulator/emulator
2. Open React Native Debugger/Chrome DevTools
3. Error 'Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.' is shown

**Comment by andresesfm** [comment]
I'm thinking this is related to the method used to see if Storekit2 is available 🤔

**Comment by andresesfm** [comment]
@professorkolik Have you tried any of these proposed solutions: https://stackoverflow.com/questions/61067004/invariant-violation-calling-synchronous-methods-on-native-modules-is-not-suppor ?

**Comment by professorkolik** [comment]
@andresesfm sure we did, and it does the job, but it's a hack, which is not ok. On of the possible solutions I do see is setting storekitMode through env variables, wdyt?

**Comment by andresesfm** [comment]
I meant not as a permanent solution but to know if you had tried something that worked

**Comment by professorkolik** [comment]
@andresesfm ah, sorry, yeah the stackoverflow solution works, but it's smth would be nice to avoid.

**Comment by andresesfm** [comment]
It's strange that here: https://stackoverflow.com/a/69849801/570612 they mentioned it was fixed on rn 0.66

**Comment by professorkolik** [comment]
I will close this issue, since, nobody else experiences it. Will raise a PR if I find proper solution

**Comment by c-goettert** [comment]
I am facing this issue as well (using v 12.10.5 with RN 0.70.9). Did you find a proper solution for this @professorkolik ?

Also, I didn't even find the option to configure StoreKit-mode in the official docs, just stumbled across it in this migration guide. I think the docs could use a little upgrade in this regard..

**Comment by professorkolik** [comment]
@c-goettert 
My recommendation would be to drop ReactNativeDebugger and switch to Flipper 😄 

To configure store kit just call

```setup({ storekitMode: <store_kit_mode> });``` in your index file
