### ISSUE TITLE
Error when trying to switch base plan subscription

### ISSUE THREAD

**Issue by JameDodgers** [dooboolab/react-native-iap#2168]
**Description**

Hello! It's indeed possible to switch from a monthly base plan to an annual base plan under the same subscription on Android? The Google Play Billing's [official docs](https://developer.android.com/google/play/billing/subscriptions#proration-recommendations) describes a case for the proration mode where the user is changing the recurring period on the same tier, but when I tried to do so, I received __Error retrieving information from server [DF-DFERH-01]__. Am I missing something here?

Despite the docs, lurking around for an answer I found this [issue](https://issuetracker.google.com/issues/236001071) in Google's IssueTracker related to this scenario with no solution from support until now.

For this particular case, my __requestSubscription__ it's done this way:
```
requestSubscription({
  sku: productId,
  subscriptionOffers: [{ sku: productId, offerToken }], // offerToken of target base plan
  purchaseTokenAndroid: subscribedProduct.purchaseToken, // purchaseToken from current subscription
  prorationModeAndroid: ProrationModesAndroid.DEFERRED, // Recommended proration mode from official docs
});
```

**Environment:**

- react-native-iap: 12.4.9
- react-native: 0.70.5

**Comment by JameDodgers** [comment]
It worked using the __IMMEDIATE_AND_CHARGE_FULL_PRICE__ proration mode

**Comment by cervebar** [comment]
We had the same issue, it seems it's the problem of Android v5 itself (and their documentation) - see this [Billing V5: change between 2 renewable base plans of the same subscription](https://github.com/android/play-billing-samples/issues/549)

It seems there are 2 options how to solve that:
1. use only 
   - `IMMEDIATE_AND_CHARGE_FULL_PRICE`
   - `IMMEDIATE_WITHOUT_PRORATION` - we used this as we don't want user to pay twice for same subscription and only different period
   - see this answer [549#issuecomment-1183421918](https://github.com/android/play-billing-samples/issues/549#issuecomment-1183421918)
2. change your subscriptions in Google Play back to model 1 subscription - 1 plan
