### ISSUE TITLE
apk error processAmazonReleaseResources 

### ISSUE THREAD

**Issue by gern132** [dooboolab/react-native-iap#2172]
<img width="1056" alt="Screenshot 2022-12-26 at 13 40 47" src="https://user-images.githubusercontent.com/61838272/209539650-da5ac149-6edf-4e83-af8f-918feac04487.png">

<img width="401" alt="image" src="https://user-images.githubusercontent.com/61838272/209539735-08dea273-c2b7-4d77-a578-2ec10511d315.png">
 USING Android support

"react-native-iap": "^12.4.9"

have error when try to build(apk) project

**Comment by andresesfm** [comment]
https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found
