### ISSUE TITLE
Why treating ios and android differently?

### ISSUE THREAD

**Issue by mikemangas** [dooboolab/react-native-iap#2173]
**Screenshots**

![image](https://user-images.githubusercontent.com/85886271/209727425-9cdbbab0-162b-4791-b742-394c12365a1f.png)

In order to make both, android and ios work, i had to do this workaround. isnt there a way, to call this method, without this workaround?

it is quite confusing!

thank you.

**Comment by pierroo** [comment]
EXACTLY the issue I was going to raise, WHY?
This is so confusing.

It was so straight forward in earlier version, the latest ones have so many weird behavior, not only this one but also the localizedPrice that disappeared on android in getProducts... For sure there must be a good reason, but even the documentation don't mention it, and the documentation itself only mentions the requestPurchase "ios like" without even mentioning android is different (https://react-native-iap.dooboolab.com/docs/guides/purchases)

**Comment by andresesfm** [comment]
@mikemangas @pierroo Android now accepts an array of SKUs (before it was only a single SKU at the time). iOS still only takes only one SKU. I'm open to suggestions on how to address the difference

**Comment by pierroo** [comment]
that makes sense @andresesfm, thanks for clarifying.
Ideally I think it would be worth mentioning it in the docs, for there is no mention at all of those differences and it's obvious the doc was made mainly with iOS in mind (in order to avoid similar issues opened here)

**Comment by mikemangas** [comment]
@andresesfm  thank you so much for always replying and explaining! That makes totally sense!
But i can not find it anywhere in the documentation.
Maybe adding this to the documentation, would be also a good solution?

**Comment by jaysquared** [comment]
> @mikemangas @pierroo Android now accepts an array of SKUs (before it was only a single SKU at the time). iOS still only takes only one SKU. I'm open to suggestions on how to address the difference

On Android, when only the sku parameter is given, convert it into an array and use that as skus parameter automatically.
