### ISSUE TITLE
How can we get the active subscription list for both Android and iOS?

### ISSUE THREAD

**Issue by nabajyotiappstango** [dooboolab/react-native-iap#2175]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

After getting a subscription if a user want get his/her active subscriptions, how can we implement it? Can any one help me to figure out this issue? @hyochan please provide a solution. Is there any pre defined method which will return the active subscription list of that user?

**Expected Behavior**

**Screenshots**

**Environment:**

- react-native-iap:
- react-native:
- Platforms (iOS, Android, emulator, simulator, device):

**Comment by andresesfm** [comment]
seems better suited for a discussion than an issue
