### ISSUE TITLE
subscriptions array is empty when calling getSubscriptions with non-renewable skus on ios

### ISSUE THREAD

**Issue by SyedTayyabUlMazhar** [dooboolab/react-native-iap#2176]
**Description**

When retrieving non-renewable subscriptions on ios using **getSubscriptions** method, the **subscriptions** array is always empty. But if I were to call **requestSubscription** for that same sku, then I am able to purchase that subscription. 

**Expected Behavior**

**subscriptions** shouldn't be empty

**Environment:**

- react-native-iap: "^12.4.8"
- react-native: "0.69.5"
- Platforms: iOS simulator & device.

**To Reproduce**

1. call getSubscriptions({skus: ["some_non_renewable_sku"]});
2. Log subscriptions array.
3. Array is empty.

---

[Optional] **Additional Context**

Note that this issue does not occur on renewable subscriptions, I can call getSubscriptions with it, and subscriptions array will get updated with the data.

**Comment by andresesfm** [comment]
Fix: https://github.com/dooboolab/react-native-iap/pull/2180

**Comment by andresesfm** [comment]
Released in `12.4.10` please lt me know if any other issues

**Comment by SyedTayyabUlMazhar** [comment]
> Released in `12.4.10` please lt me know if any other issues

So it's being returned by the getProducts function, shouldn't it be returned from getSubscriptions(since it's a non-renewable subscription)?.

**Comment by andresesfm** [comment]
I haven't found a more reliable way to check if a product is a subscription. So I have removed the filter. The fix was released on `12.4.12`

**Comment by cynde** [comment]
so, should i use getSubscriptions or getProducts for non-renewable iap? @andresesfm . because i keep getting empty array using getProducts
