### ISSUE TITLE
Consuming in-app purchase in android.

### ISSUE THREAD

**Issue by sanilcgs** [dooboolab/react-native-iap#218]
I have successfully integrated react-native-iap into my app. Now I have a doubt regarding in-app products in android. I have added 3 managed products in my google play console.  The issue I am facing is when I try to purchase an item for the second time, no action happening. My doubt is, do I need to invoke the **consumePurchase()** method for consuming that item?

**Comment by dooboolab** [comment]
@sanilcgs If your product is not `consumable` you can't sue `consumePurchase` method. If your product is `consumable` you may use that to rebuy the item.
