### ISSUE TITLE
 Google is indicating that we have some issue connecting to payment

### ISSUE THREAD

**Issue by Abdulahaditsol** [dooboolab/react-native-iap#2184]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
I am getting error in RNIAP finishtransaction in android platform while testing subscription purchase purchase.
[Error: Google is indicating that we have some issue connecting to payment.]
it was working fine before when i was using "react-native-iap": "^4.4.0" but later after playstore warn regarding billing library I updated RNIAP to version 11 following this document https://react-native-iap.dooboolab.com/docs/get-started

**Environment:**

- react-native-iap:
- react-native: 0.63.3
- Platforms Android

---

[Optional] **Additional Context**
our users is effecting badly by this issue anyone have suggestion please share me.
Thanks

**Comment by andresesfm** [comment]
Please follow the migration guides

**Comment by Abdulahaditsol** [comment]
Hi andresesfm I followed the whole guide and our ios app is working well only affects the android app.

**Comment by andresesfm** [comment]
These are some possible causes: https://stackoverflow.com/questions/53858736/why-am-i-getting-developer-error-response-code-when-connecting-my-billingclient

**Comment by dimaischenko** [comment]
> Hi andresesfm I followed the whole guide and our ios app is working well only affects the android app.

@Abdulahaditsol I guess I figured it out. For Android subscriptions, you need to pass `isConsumable: true` 

```
finishTransaction({purchase: purchase, isConsumable: true})
```

And vice versa for iOS
```
finishTransaction({purchase: purchase, isConsumable: false})
```

I'll be checking things out more carefully and will be glad if someone else will check and write back, nowhere clearly it is not written in the manuals, there is only a mention that for iOS subscription are consumable products. 

@andresesfm And also in this example https://github.com/dooboolab/react-native-iap/blob/main/IapExample/src/screens/Subscriptions.tsx it is explicitly and platform-independent stated that the subscription is consumable , probably needs to be fixed

**Comment by dimaischenko** [comment]
It seems that for iOS subscriptions are **non-consumables** too, then you should pass `isConsumable: false` in `finishTransaction` for iOS too. I suspect it doesn't play a role in the case of iOS, which is why it worked in previous example. But we need to carefully review the manuals, for example at this page https://react-native-iap.dooboolab.com/docs/guides/purchases I found:

> Subscribable products can be purchased just like consumable products and users can cancel subscriptions by using the iOS System Settings.

Which is a bit misleading as for me

**Comment by SufianBabri** [comment]
@dimaischenko thanks for your comment. It helped me solve the issue.

I have added a bit more information about it in [this comment](https://github.com/dooboolab-community/react-native-iap/issues/2492#issuecomment-1802666370). Hopefully, it will clarify it further for others.
