### ISSUE TITLE
getPurchaseHistory and getAvailablePurchases returns a huge array with many duplicates on iOS

### ISSUE THREAD

**Issue by mikemangas** [dooboolab/react-native-iap#2186]
**Description**

Whenever i Call the method getPurchaseHistory or getAvailablePurchases, i receive a valid array on android, with a array length of 8 for the getAvailablePurchases for example.
On iOS the array length is 57... with many, many duplicates.
**Expected Behavior**

Array does not contain duplicates.
**Screenshots**

<img width="320" alt="image" src="https://user-images.githubusercontent.com/85886271/210891854-9128fc70-8af3-4c2b-a993-b252e758526c.png">

Length 8
<img width="123" alt="image" src="https://user-images.githubusercontent.com/85886271/210892041-dbc2c861-ba87-45a8-a2a3-c9e7fe18714b.png">

**Environment:**

- react-native-iap: newest
- react-native: newest
- Platforms (ios, 15 and 16  simulator and device):

**To Reproduce**

Import either the one or the other method.
Call one of the methods inside a async function. Make sure to call the method just once.
For example within a useEffect(() => {...}, [])

<img width="553" alt="image" src="https://user-images.githubusercontent.com/85886271/210898202-c402ea85-3d65-4c40-8a10-2472cafecd39.png">

By the way, it doesnt matter if i import the function or use the hook, the result stays the same!
const  { getPurchaseHistory,purchaseHistory} = useIAP();

**Comment by andresesfm** [comment]
This is expected, check the FAQ. Let me know if any other issues

**Comment by andresesfm** [comment]
Same reason as this: https://react-native-iap.dooboolab.com/docs/faq#update-listener-called-many-times-on-ios-storekit-1
