### ISSUE TITLE
Subscription does not have subscriptionOfferDetails

### ISSUE THREAD

**Issue by alexsandersarmento** [dooboolab/react-native-iap#2188]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**
Property `'subscriptionOfferDetails'` does not exist on type `'Subscription'`.
  Property `'subscriptionOfferDetails'` does not exist on type `'SubscriptionAmazon'.`

**Expected Behavior**
Access `subscriptionOfferDetails` from the return of the `getSubscriptions()` method

**Screenshots**
<img width="856" alt="Screenshot 2023-01-05 at 20 53 57" src="https://user-images.githubusercontent.com/60042662/210902060-3903af93-bc40-4fdd-b7d7-5b10234c36bb.png">
<img width="694" alt="Screenshot 2023-01-05 at 20 54 25" src="https://user-images.githubusercontent.com/60042662/210902097-6d2aefcf-0ad7-49ff-980b-98e0e0c4af88.png">
<img width="460" alt="Screenshot 2023-01-05 at 20 54 38" src="https://user-images.githubusercontent.com/60042662/210902127-e1844a8f-bbec-459c-8043-8196f0e38b0b.png">

**Environment:**

- react-native-iap:
- react-native:
- Platforms (iOS, Android, emulator, simulator, device):

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by moooss** [comment]
Subscriptions types are differents on each platform.
`subscriptionOfferDetails` is only available on `SubscriptionAndroid` type.
The ts linter is telling you that it does not exist on type `SubscriptionAmazon`, it is also true for `SubscriptionIos`.

You have to test the presence of the property before using it on android, and use something else on ios.
