### ISSUE TITLE
Finish transaction throwing error

### ISSUE THREAD

**Issue by emanu7478** [dooboolab/react-native-iap#2190]
**Description**

 When I try to finish the transaction it throws me the error _E_UNKNOWN An unknown or unexpected error has occurred. Please try again later._ I tried multiple times later but still finish transaction throwing an error. But when I went through the subscription list in the play store it showing subscribed but after some time it will not renew the subscription

`RNIap.finishTransaction(res, false).catch(err => {
          console.log('IAP finish transaction error', err.code, err.message);
        });`

Here res contains response from RNIAP.requestsubscriptions successful completion

**Environment:**

- react-native-iap: 7.5.0
- react-native: 0.64.0
- Platforms (iOS, Android, emulator, simulator, device): Android

**To Reproduce**

1. Request subscription by RNIAP.requestSubscription()
2. After successful response call RNIAP.finishTransaction(res, false)
3. Error 'E_UNKNOWN An unknown or unexpected error has occurred' is shown

---

**Comment by andresesfm** [comment]
Updated docs: https://github.com/dooboolab/react-native-iap/issues/2190. You need to pass arguments inside object
