### ISSUE TITLE
Andorid Proration DEFERRED causes DF-DFERH-01 error

### ISSUE THREAD

**Issue by jlafosse** [dooboolab/react-native-iap#2195]
**Description**

When attempting to use prorationMode **DEFERRED**, play store responds with: **Error retrieving information from server DF-DFERH-01**

**Expected Behavior**

Purchase new base plan subscription.

**Screenshots**

![Screenshot_20230110-115448](https://user-images.githubusercontent.com/1720055/211618648-a1c6d721-e973-4cdb-b1bf-6d99ea863d8e.png)

**Environment:**

- react-native-iap: 12.4.12
- react-native: 0.69.6
- Platforms (iOS, Android, emulator, simulator, device): Android
- Devices: Pixel 2, Pixel 6 Pro, Pixel 7, etc.

**To Reproduce**

1. Setup a Subscription in Google Play (i.e. Premium)
2. Create base plans under the Premium Subscription (i.e. premium-1m, premium-6m, premium-1y)
3. Subscribe to the 1 month premium, then attempt to subscribe to the 6 month premium using DEFERRED proration.

Attempting to subscribe with a new offer on an different base plan using DEFERRED will result with: **Error retrieving information from server DF-DFERH-01**.  

**Here are the results of the other proration types:**

```
DEFERRED - Fail
IMMEDIATE_AND_CHARGE_FULL_PRICE - Success
IMMEDIATE_AND_CHARGE_PRORATED_PRICE - Fail
IMMEDIATE_WITHOUT_PRORATION - Success
IMMEDIATE_WITH_TIME_PRORATION - Success
```

**Here is some example code below:**

```

const GP_SUB_PRODUCT_ID = 'premium';
const USER_SELECTED_SKU = 'premium-6m';

const subscriptions = await getSubscriptions({ skus: [GP_SUB_PRODUCT_ID] });

const purchases = await getAvailablePurchases();

const latest = purchases.length
    ? purchases[purchases.length - 1]
    : { transactionReceipt: null };

// Need to find the baseplan offer via tags??
// https://github.com/dooboolab/react-native-iap/issues/1878#issuecomment-1233417699
const offer = subscriptions.subscriptionOfferDetails.find(
    o => {
        return USER_SELECTED_SKU == o.offerTags[0];
    }
);

await requestSubscription({
    obfuscatedAccountIdAndroid: userId,
    subscriptionOffers: [
        {
            sku: GP_SUB_PRODUCT_ID,
            offerToken: offer.offerToken,
        },
    ],
    purchaseTokenAndroid: latest?.purchaseToken,
    prorationModeAndroid: ProrationModesAndroid.DEFERRED,
});


```

**Comment by andresesfm** [comment]
I don't think this error is related to this library but to google play: https://support.google.com/googleplay/thread/81842487/error-retrieving-information-from-server-df-dferh-01?hl=en

**Comment by jlafosse** [comment]
Thanks for the response. I have already seen that post and attempted those resolutions to no avail (restart, clear cache, etc). The strange thing is that this error occurs for 3 different developers on 3 different android phones. If this is indeed a Google Play Store issue, then that means that you cannot use DEFERRED proration which is their recommended method... unbelievable.

**Comment by andresesfm** [comment]
It's pretty well described here: https://www.namiml.com/blog/play-billing-deferred-proration-mode
