### ISSUE TITLE
TypeError: Cannot read property 'canMakePayments' of undefined in IOS

### ISSUE THREAD

**Issue by bigchamp** [dooboolab/react-native-iap#220]
### Version of react-native-iap
"react-native-iap": "1.3.0",

### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
Must be called on Android before any other purchase flow methods. In ios, it will simply call canMakePayments method and return value.
### Actual behavior
TypeError: Cannot read property 'canMakePayments' of undefined in IOS
### Tested environment (Emulator? Real Device?)
Real Device: Iphone 6, ios 10.3.3
### Steps to reproduce the behavior
```
import * as RNIap from 'react-native-iap';

then:
const itemSkus = Platform.select({
  ios: [
    'app.xxx.xxx.xxxPurchase'
  ],
  android: [
    'xxx
  ]
});

in component class: 
async componentDidMount() {
    try {
      await prepare();
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
  }
```
and once i get into this screen appears error that "TypeError: Cannot read property 'canMakePayments' of undefined in IOS"

Thank you!

**Comment by dooboolab** [comment]
@bigchamp Could you update our module (currently it's version in 1.3.5) and try to unlink and link again? It is because `react-native-iap` isn't linked properly to your project.

**Comment by louiskhenghao** [comment]
i am facing exact same issue, the version i've installed was 1.3.5 (tried on emulator)

**Comment by louiskhenghao** [comment]
reinstall the package and relinking solved my issue :D
