### ISSUE TITLE
Cannot requestSubscription

### ISSUE THREAD

**Issue by milesscherrer** [dooboolab/react-native-iap#2203]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

When calling requestSubscription with a productId of my subscription I get:

`Products error:  [TypeError: right operand of 'in' is not an object]`

Expecting checkout to appear

**Screenshots**

**Environment:**

- react-native-iap: 12.4.14
- react-native: 0.66.3
- Platforms (iOS, Android, emulator, simulator, device): iOS

**Comment by Munir-Hassan** [comment]
Did you find any solution on it? For me Nothing happens. Calling the function does nothing. @milesscherrer

**Comment by milesscherrer** [comment]
needed to call it with an object requestSubscription({ sku: productId }) and it worked, you probably just need to define subscriptionRequestIOS above the await
