### ISSUE TITLE
E_SERVICE_ERROR Billing is unavailable. This may be a problem with your device, or the Play Store may be down.

### ISSUE THREAD

**Issue by LuckyLuky** [dooboolab/react-native-iap#221]
### Version of react-native-iap 

1.3.5

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Working RNIapExample example. 

### Actual behavior

When I run RNIapExample, I immediately get this warning: 
`E_SERVICE_ERROR Billing is unavailable. This may be a problem with your device, or the Play Store may be down.` 
I get the same error when I press `Get available purchases` button. 

If I press `Get Products` button, I get this error: 
`E_NETWORK_ERROR The service is disconnected (check your internet connection.)` 

### Tested environment (Emulator? Real Device?)

Real Device (Samsung Galaxy S5)

### Steps to reproduce the behavior

1. Clone project. 
2. Run RNIapExample.

**Comment by dooboolab** [comment]
@LuckyLuky I think the play service is not installed in your device or you are not logged in to playstore. Could you check that?

**Comment by LuckyLuky** [comment]
@dooboolab Yes, that was it, I wasn't logged in to Playstore. Thank you.

**Comment by itsaberi** [comment]
I have the same problem but I have already logged to play store

**Comment by rusakovic** [comment]
@hyochan 
Hello. Thank you for your work!

I have the same error, if I signed in in Play Store, but I have >1 Google accounts in my phone.

If I leave only 1 google account - all is OK.

Could you, please, check it?

react-native-iap: 8.0.10
Xiaomi Redmi 10 Android 11
Play Store 30.6.16-21

**Comment by nkpatnis** [comment]
after calling initConnection getting this error
`Billing is unavailable. This may be a problem with your device, or the Play Store may be down.`

**Comment by DevHeauk** [comment]
it also can be related supporting paid service country of play store
refer this page. https://support.google.com/googleplay/answer/143779?sjid=6123458031532873966-AP
