### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by tonsnoei** [dooboolab/react-native-iap#2215]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

Using react-native-iap:12.5.1 with react 18.2.0 / react-native 0.71.1 results in an error when setting the Kotlin to the version adviced in the documentation
![image](https://user-images.githubusercontent.com/8810118/214568135-3d961070-9dff-4712-94be-48df53b674c7.png)

1. When compiling Android with the above setting, it results in the following error:
```shell
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
root project 'myproject' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.0
```
2. This suggests you should change the version of Kotlin to `1.5.20`. 
![image](https://user-images.githubusercontent.com/8810118/214569219-5facb5d2-c0e4-4554-9979-c05fab223efb.png)

But this results in the following error:
```
> Task :react-native-iap:compilePlayReleaseKotlin FAILED
e: /Users/me/.gradle/caches/transforms-3/a6aada49b843a4931062f30d3627d3df/transformed/jetified-billing-ktx-5.1.0-api.jar!/META-INF/java.com.google.android.libraries.play.billing.public.ktbilling_granule.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
```
3. Change the version to `1.6.0` will fix the issue. 
![image](https://user-images.githubusercontent.com/8810118/214570077-6e95c34a-7cc4-45a4-9375-9d554b12f9c7.png)

**Environment:**

- react-native-iap:12.5.1
- react-native:0.71.1
- Platforms: Android

**To Reproduce**

See above

**Comment by andresesfm** [comment]
Thank you @tonsnoei. Included your suggestion here: https://github.com/dooboolab/react-native-iap/pull/2217
