### ISSUE TITLE
Renewable subscription auto cancelled

### ISSUE THREAD

**Issue by jipEbizz** [dooboolab/react-native-iap#2219]
**Version of react-native-iap**
^7.4.1

**Version of react-native**
0.62.2

**Platforms you faced the error (IOS or Android or both?)**
Android Only

**Expected behaviour**
Renewable Subscription

**Actual behaviour**
My live users have subscribed to the product and after some time or days, the membership was auto cancelled and received an email from Google that "money was refunded and membership cancelled" even if the users did not unsubscribe.

Can anyone please look into this?

Thank you.

![Screen Shot 2023-01-27 at 12 41 07](https://user-images.githubusercontent.com/72867449/215029135-978e718b-7534-4d76-b057-354ffb09152f.png)

**Comment by professorkolik** [comment]
This happens when the purchase is not acknowledged, had similar issue.
We resolved it by acknowledging the purchase from server-side

**Comment by berk9595** [comment]
Hey, I think you need to finish the transaction after your clients purchased the thing
 ```
import {
  finishTransaction,
} from 'react-native-iap';

finishTransaction({
          purchase: purchase,
          isConsumable: true,
        });
```
