### ISSUE TITLE
The sku was not found. Please fetch products first by calling getItems

### ISSUE THREAD

**Issue by MariusCatanoiu** [dooboolab/react-native-iap#2225]
I have this error for some users. Looks like an edge case.
For 99% of the users works without an issue.
The items are Consumable and I don't use `getItems`

**Environment:**

- react-native-iap:  12.5.1,
- react-native: 0.70.6
- Platforms (iOS, Android, emulator, simulator, device): Android (Samsung S20, A13 and more)

**To Reproduce**

I use this code

```
try {
	const remoteProducts = await getProducts({ skus: skuIds });
        this.setState({ remoteProducts });
} catch (error) {
}

```

and 

```
try {
	await requestPurchase(Platform.OS === 'ios' ? { sku: skuId} : { skus: [skuId] });
} catch (error) {
}
```

I have the "skuIds" and "skuId" all the time, I check them first.

**Comment by andresesfm** [comment]
@MariusCatanoiu since you include two different blocks of code. could it be that there's a race condition in your code?

**Comment by MariusCatanoiu** [comment]
> @MariusCatanoiu since you include two different blocks of code. could it be that there's a race condition in your code?

I don't see this case. The second cod is running only if the `remoteProducts` flag is changing status in the state

**Comment by andresesfm** [comment]
Are you calling `endConnection` at some point?

**Comment by MariusCatanoiu** [comment]
> Are you calling `endConnection` at some point?

Of course. In `componentWillUnmount`, and `initConnection` in `componentDidMount`.
On app resume I call again `initConnection`. I have a method with a listener on AppState when you put the app in background and return. From time to time the connection is lost, and I have to call it again

**Comment by Pingou** [comment]
Same issue.

**Comment by davide-desio-eleva** [comment]
Hi all,
we are facing the same situation on Android, calling getProducts passing an array of skus will result in missing products.
I could explain it a little better, adding some screenshot.

**Calling `getProducts(skus:['test002','test003])` will result in adding only 'test002' in products, ignoring 'test003'**
Calling useIAP().products give us only 'test002'. See screenshot below.
![41f741e2-b14d-4b1f-a899-c38309c6e796](https://user-images.githubusercontent.com/20799924/216007509-9189b959-0a7c-49d1-a3af-f6b78105def3.jpg)

So **when calling `requestPurchase({skus: [_sku]})` where _sku is 'test003', we get the error 'The sku was not found. Please fetch products first by calling getItems'** because actually 'test003' is missing in products.

While on IOS everything seems to be fine, Calling `getProducts(skus:['test002','test003])` will result in adding both 'test002' and 'test003' in products and so, calling `requestPurchase({skus: [_sku]})` where _sku is 'test003', result in a successful request purchase (and we can also finish it by calling `finishTransaction({...})`
Calling useIAP().products give us 'test002' and 'test003'. See screenshot below.
![1c5c86dd-a6a8-48cc-ad9a-f7479636c12a](https://user-images.githubusercontent.com/20799924/216007575-51780711-9e77-4ecc-b239-16e7db7e42e1.jpg)

**Android: tested on Samsung Galaxy Tab S6
IOS: tested on Ipad Air 6th generation** 

Hope this help in debugging.
@andresesfm let me know if I can give you further details

**Comment by MariusCatanoiu** [comment]
@davide-desio-eleva  `getProducts(skus:['test002','test003])` has to be `getProducts({ skus:['test002','test003] })`.
I'm missing something?

**Comment by davide-desio-eleva** [comment]
> @davide-desio-eleva `getProducts(skus:['test002','test003])` has to be `getProducts({ skus:['test002','test003] })`. I'm missing something?

Hi @MariusCatanoiu, we are passing an object as you point out calling `getProducts({ skus:['test002','test003] })`.
Sorry for the mistake, I've edited my previous post.

**Comment by davide-desio-eleva** [comment]
Other info that might be helpful. 
Everything refers **only to Android**. 
We have iap updated to **12.7.2.**

- We've added a 'test004' product in google play console, and suddenly calling `getProducts({ skus:['test004'] })`, it returns the product 'test004'
**- We've then added a 'test005' product in google play console, but calling `getProducts({ skus:['test005'] })`, it has returned an empty array**
**- After a couple of hour we call again `getProducts({ skus:['test005'] })`, and the 'test005' appears magically into products**
- Then we add another product 'test006' in google play console, and calling `getProducts({ skus:['test006'] })`, it return instantly the product 'test006' 
**- Then we add another product 'test007' in google play console, but calling `getProducts({ skus:['test007'] })`, it has returned an empty array**

We are retrying calling `getProducts({ skus:['test007'] })` to see if it magically appears after a while. 

All products were always active, and consumables
<img width="1183" alt="Schermata 2023-02-01 alle 14 26 49" src="https://user-images.githubusercontent.com/20799924/216055817-e7ccde81-58eb-4eda-a267-adc70e4e9ba5.png">

It seems that there is a 'period' before the in-app-purchase is available even if it is signed as active in google play console.
@andresesfm could this be true in your expirience?
This probably explain why this is happening only on android platform while IOS is ok.

**Comment by andresesfm** [comment]
Thank you for the clarification @davide-desio-eleva . It seems to be a known issue (expected behavior?) on the Google Side: https://stackoverflow.com/questions/16320381/propagation-delay-when-changing-in-app-product-price-description-in-google-pla

**Comment by andresesfm** [comment]
> Same issue.
> 
> It seems to me that the problem is that I am caching the offerToken, and for some reasons they are different every time? What's the point of that? That is particularly annoying since getSubscriptions fails more than half the time for some reason, with init failing with the error message :"Billing is unavailable. This may be a problem with your device, or the Play Store may be down"

@Pingou I had no idea the offerToken is different every time. I'm curious as to why you need to cache it?

As for getSubscriptions failing it could be that the device's connection drops or that you are calling it too often

**Comment by andresesfm** [comment]
Too often per user

**Comment by andresesfm** [comment]
> > Are you calling `endConnection` at some point?
> 
> Of course. In `componentWillUnmount`, and `initConnection` in `componentDidMount`. On app resume I call again `initConnection`. I have a method with a listener on AppState when you put the app in background and return. From time to time the connection is lost, and I have to call it again

@MariusCatanoiu I think you might be doing this too often which causes race conditions. The recommendation is to init/end the connection at the top level of your app

**Comment by davide-desio-eleva** [comment]
> Thank you for the clarification @davide-desio-eleva . It seems to be a known issue (expected behavior?) on the Google Side: https://stackoverflow.com/questions/16320381/propagation-delay-when-changing-in-app-product-price-description-in-google-pla

Well, reference is about a propagation delay when changing in app product info (like price or description) and this could be based on cached information on google side.

But we are creating completely new products. 
Those should be available instantly on google side and thus calling the getProducts() method of react-native-iap.
Is this method getting them from the local play store cache or directly via an API?

**Comment by andresesfm** [comment]
@davide-desio-eleva 
We are not caching the response as described above. Also note that the reference is for an old version of Billing services. Here is another reference: https://stackoverflow.com/questions/11068686/this-version-of-the-application-is-not-configured-for-billing-through-google-pla

**Comment by andresesfm** [comment]
Thank you all for your comments. Please reopen if any other issues

**Comment by davide-desio-eleva** [comment]
Thank you for your clarification.
Good to know that nothing is cached as described above.

Still the reference has no clue with this issue: it says Google take a while to process applications, but those are totally other situation than this issue.

_We are adding an in-app-purchase on Google Play Console, and before seeing it with getProducts() sometimes we should wait seconds, sometime we should wait hours, sometimes it takes a day._

We could assume this is an intended behavior, still without any specific reference.
We'll test it in as much condition as possible, and update here for future reference is anyone is experiencing the same issue.

**Comment by robertstar10** [comment]
@davide-desio-eleva Would you have any clue for it. I got exactly same issue with.

**Comment by davide-desio-eleva** [comment]
You should wait until it appears: I can confirm that "We are adding an in-app-purchase on Google Play Console, and before seeing it with getProducts() sometimes we should wait seconds, sometime we should wait hours, sometimes it takes a day." and there is anything you can do but wait.
