### ISSUE TITLE
getSubscriptions doesn't return prices for Amazon

### ISSUE THREAD

**Issue by Pingou** [dooboolab/react-native-iap#2227]
getSubscriptions doesn't return prices for Amazon.
Here what is returned (sandbox with Amazon app tester).

`{"currency": "USD", "description": "Get my sub", "iconUrl": "http://", "localizedPrice": null, "originalJson": "{
    \"sku\": \"my_sub\",
    \"productType\": \"SUBSCRIPTION\",
    \"description\": \"Get my sub\",
    \"smallIconUrl\": \"http:\\/\\/\",
    \"title\": \"sub - yearly\",
    \"coinsRewardAmount\": 0
}", "originalPrice": null, "platform": "amazon", "price": "0.0", "productId": "my_sub", "title": "sub - yearly", "type": "subs"}`

However prices are returned for one time purchases.

- react-native-iap: 12.7.1
- react-native: 0.70.2
- Platforms (iOS, Android, emulator, simulator, device): Android device

**Comment by andresesfm** [comment]
@Pingou do you see the following message on the Android Logcat?

```
onProductDataResponse: Failed to parse price for product: 
```

**Comment by Pingou** [comment]
> @Pingou do you see the following message on the Android Logcat?
> 
> ```
> onProductDataResponse: Failed to parse price for product: 
> ```

@andresesfm  No I don't

**Comment by andresesfm** [comment]
I would suggest adding a breakpoint in `RNIapAmazonListener.kt:35` and verify that the priceString is what you expect. I'm not sure why it is being parsed as it is. Let me know how that goes

**Comment by andresesfm** [comment]
I just noticed that your `localizedPrice` is null which explains why `price` is "0.0". What are you setting the price to be in your tester?

**Comment by Pingou** [comment]
@andresesfm prices in productData are null. In the App Tester I see them at the correct price though. Any clue?
