### ISSUE TITLE
android finishTransaction `Google is indicating that we have some issue connecting to payment`

### ISSUE THREAD

**Issue by oajh04** [dooboolab/react-native-iap#2228]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

`Google is indicating that we have some issue connecting to payment.`
This error occurs when you make a subscription payment on Android and then finishTransaction.
What's the problem?

**Environment:**

- react-native-iap: 12.5.1
- react-native: 0.66.3
- Platforms (iOS, Android, emulator, simulator, device): android device

**Comment by oajh04** [comment]
In addition, we are currently implementing regular subscription payments with requestSubscription, and even though we succeeded in finishTransaction, the subscription payment history that we paid before when calling getAvailablePurchases is being responded, and I wonder if it works normally.

**Comment by dimaischenko** [comment]
May be the same as #2184 I seem to have figured it out, I posted in that thread
