### ISSUE TITLE
The callback getItemsByType() exists in module RNIapModule

### ISSUE THREAD

**Issue by saimemre** [dooboolab/react-native-iap#223]
I'm testing on the actual device on the android platform.
iap Version ^ 0.3. *.
Error: The callback getItemsByType() exists in module RNIapModule, but only one callback may be registered to a function in a native module.

**Comment by dooboolab** [comment]
@saimemre Could you share your code? Also, I prefer you to upgrade our module to recent version that fixed lots of potential bugs previously.

**Comment by saimemre** [comment]
@dooboolab thanks for answer. 

I updated my new account, Now, when the app is opened for the first time, the payment page is not opened and then it opens when it is entered.

`'use strict';

import React, {Component} from 'react';
import {connect} from 'react-redux';
import {Container, Content, List, ListItem, Right, Left, Radio, Text, Button, Header, Icon, Body, Title } from 'native-base';
import { Dimensions, View, Image, Platform, ScrollView} from 'react-native';
import * as RNIap from 'react-native-iap';
import { Actions, ActionConst } from 'react-native-router-flux';
import Modal from 'react-native-modalbox';


import styles from './style.js';
import purchaseService from '../../services/purchase';

var {height, width} = Dimensions.get('window');

// import dumb components
import Spinner from '../loaders/Spinner';

const itemSkus = Platform.select({
  android: [
    // 'android.test.purchased',
    // 'android.test.canceled',
    // 'diamonde300',
    'vip_test',
    'vip_1',
    'vip_100',
    'vip_6'
  ],
});

class Purchase extends Component {

  constructor(props) {
    super(props);
    this.state = {
      selected: 'threeMonth',
      productId: null,
      productList: [],
      receipt: '',
      availableItemsMessage: '',
      purchasedItems: []
    };

    this._handleClick = this._handleClick.bind(this);
    this.getItems = this.getItems.bind(this);

  }

  async componentWillMount() {
    
    try  {
      await RNIap.prepare();
      console.log("Im ready");
    }
    catch (err) {
      console.log(err.message)
    }
    //this._getProducts(this.props.token, 'vip');
    this.getHistory();
    
  }

  async componentDidMount() {

    //console.log(this.state.products);
    try {
      const products = await RNIap.getSubscriptions(itemSkus);
      console.log('Products', products);
      this.setState({ productList: products, productId: products[0].productId });
      this.getAvailablePurchases();
    } catch (err) {
      console.log(err);
      console.warn(err.code, err.message);
    }

  }


  _getProducts(token, type) {
    console.log("product çek");
    purchaseService.getProducts(token, type)
    .then((response) => response.json())
      .then((responseJson) => {
        if (responseJson.data) {
          console.log(responseJson.data);
          this.setState({
            products: responseJson.data.products,
            isFetchingProducts: false
          });
        } else {
          this.setState({
            products: [],
            isFetchingProducts: false
          });
        }
      })
      .catch((error) => {
        console.log(error);
      })
  }

  async getHistory() {
    try {
      const history = await RNIap.getPurchaseHistory();
      console.log("history");
      console.log(history);

    } catch (err) {
      console.warn(err.code, err.message);
    }
  }

  getItems(){
    
  }

  buySubscribeItem = async(sku) => {
    try {
      console.log('buySubscribeItem: ' + sku + '/');
      const purchase = await RNIap.buySubscription(sku);
      console.info(purchase);

      this._setProduct(this.props.token, purchase);
      
      this.setState({ receipt: purchase.transactionReceipt });
    } catch (err) {
      console.log(err.code, err.message);
      //Alert.alert(err.message);
    }
  }



  buyItem = async(sku) => {
    try {
      console.info('buyItem: ' + sku);
      // const purchase = await RNIap.buyProduct(sku);
      const purchase = await RNIap.buyProductWithoutFinishTransaction(sku);
      console.info(purchase);

      this._setProduct(this.props.token, data);

      this.setState({ receipt: purchase.transactionReceipt });
    } catch (err) {
      console.warn(err.code, err.message);
      //Alert.alert(err.message);
    }
  }

  _setProduct(token, data) {
    purchaseService.setProduct(token, data)
    .then((response) => response.json())
      .then((responseJson) => {
        if (responseJson.data) {

          console.log(responseJson.data);


          /*
          this.setState({
            likers: responseJson.data.likers,
            isFetchingLikers: false
          });
          */

        } else {
          /*
          this.setState({
            likers: [],
            isFetchingLikers: false
          });
          */
        }
      })
      .catch((error) => {
        console.log(error, '%%%%%%%%%%%here...error:chat:actions.js%%%%%%%%%');
      })
  }
  

  getAvailablePurchases = async() => {
    try {
      console.info('Get available purchases (non-consumable or unconsumed consumable)');
      const purchases = await RNIap.getAvailablePurchases();
      console.info('Available purchases :: ', purchases);
      if (purchases && purchases.length > 0) {
        this.setState({
          purchasedItems: purchases,
          availableItemsMessage: `Got ${purchases.length} items.`,
          receipt: purchases[0].transactionReceipt
        });
      }
    } catch(err) {
      console.warn(err.code, err.message);
      console.log(err.message);
    }
  }

  _buyNewItem = async(purchaseId) => {
    console.log(purchaseId);
    await this.buySubscribeItem(purchaseId).then(res => console.log(res));
  }

  _handleClick(index) {

    console.log(index);
    this.setState({
      productId: index
    });
  }

  render() {
    const { productList, receipt, availableItemsMessage } = this.state;
    if(this.state.productList.length > 0){
      return (
        <Container style={{...styles.container}}>
          <Header style={{backgroundColor: '#FFF'}}>
            <Left>
              <Button transparent onPress={() => Actions.pop()} style={{marginTop: -5, marginRight: 5}}>
                  <Icon name="arrow-back" style={styles.backButton}/>
              </Button>
            </Left>
            <Body>
              <Title style={{ fontFamily:'arial', color:'rgba(0,0,0,0.65)', fontSize:18, fontWeight:'600', paddingLeft: 2}}>
                  Vip Üye Ol
              </Title>
            </Body>
            <Right />
          </Header>
          <ScrollView>
            <View style={styles.purchaseContent}>
              <View style={{ flex: 1, alignItems: 'center' }}>
                <View style={{ flex: 2, alignItems: 'center' }}>
                  <Image source={require('../../../img/vip.png')} style={{ width: 100, height: 100 }} resizeMode="contain"/>
                  <Text style={{ textAlign: 'center', fontSize: 23, color: '#F5A623', fontWeight: '900' }}>Vip Üye Ol ve Sınırları {"\n"}Kaldır!</Text>
                </View>
                <View style={{ flex: 1, marginTop: 20, alignItems: 'flex-start' }}>
                  <Text style={styles.listText}>•	Sınırsız mesaj gönder</Text>
                  <Text style={styles.listText}>•	Profilini ziyaret edenleri gör</Text>
                  <Text style={styles.listText}>•	Fotoğrafını beğenenleri gör</Text>
                  <Text style={styles.listText}>•	Mesajların en üstte çıksın</Text>
                </View>
                
              </View>
          
            </View>

            <View style={{ flex: 1, padding: 20, marginTop: 20 }}>
              
                {
                  productList.map((product, i) => {
                    let bgColor = '#B2B2B2';
                    
                    if(this.state.productId === product.productId){
                      console.log("selected olduk bee");
                      bgColor = '#F5A623';
                    }
                    return(

                      <View>
                        <Button full style={{ marginLeft: 0, marginBottom: 10,  height: 50, borderRadius: 5, backgroundColor: bgColor, }}
                          onPress={ () => this._handleClick(product.productId) }>
                          <Left>
                            <Text style={styles.text}>{ product.description }</Text>
                          </Left>
                          <View style={{ alignItems: 'center', flexDirection: 'row', marginRight: 20, }}>
                            <View style={{ marginRight: 10 }}>
                              <Text style={styles.text}>{product.localizedPrice}</Text>
                            </View>
                            <View>
                              <Icon name="md-radio-button-off" style={styles.radioIcon} />
                            </View>
                          </View>
                        </Button>
                      </View>
                    )
                  })
                }
                
                <View style={{ marginLeft: width / 8,  flex: 1, alignItems: 'center', marginTop: 20 }}>
                  <Button onPress={() => this._buyNewItem(this.state.productId)} full rounded success style={{ backgroundColor: '#7ED321', width: '80%',  shadowColor: '#000000',
                    shadowOffset: { width: 0, height: 5 },
                    shadowOpacity: 0.4,
                    shadowRadius: 20,
                    elevation: 1, }}>
                    <Text style={{ textAlign: 'center' }}>SATIN AL</Text>
                  </Button>
                </View>

              

            </View>
          </ScrollView>
        </Container>
      );
    }else{
      return (
        <Spinner />
      );
    }
  }
}


function bindAction(dispatch) {
  return {
    
  };
}

function mapStateToProps(state) {
  return{
    token: state.auth.token,
  };
};

export default connect(mapStateToProps, bindAction)(Purchase);
`

**Comment by dooboolab** [comment]
@saimemre Could you put all your code in `componentWillMount` to `componentDidMount`? This may cause race condition in your code. Please try again then.
