### ISSUE TITLE
MIssing Documentation for a complete setup trying to use Amazon IAP

### ISSUE THREAD

**Issue by lbusz** [dooboolab/react-native-iap#2230]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

I am working with a project that alreay have this library installed. Thing is that i am getting getSuscriptions as empty array all the time. I think this is due to missing configurations (build.gradle, AndroidManifest, MainActivity, strings, so on) as those were not provided by previous developer. So i started looking into the documentation and was not able to find any references. 
The library that is installed is 9.0.4 which is rather old, so i went ahead and updated it to 12.7.2 but was unable to identify where should i be using the app_public_key (just to name one thing)
**Expected Behavior**

There should be some documentation stating the configuration (basic at least) that need to be put in place to be able to use this end to end
**Screenshots**

**Environment:**

- react-native-iap: 9.0.4, 10, 11, 12.7.2
- react-native: react-native-tvos@latest
- Platforms (iOS, Android, emulator, simulator, device): FireTV Stick 4k

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by anishamalde** [comment]
Hi, 
I have actually written an article on how to get started with Amazon IAP: https://dev.to/amazonappdev/react-native-iap-one-package-to-rule-them-all-4f0n
Hope this helps!

**Comment by codal-mpawar** [comment]
@anishamalde Amazon pays support only for android only not for iOS right?

**Comment by grigdodon** [comment]
@lbusz hey. did you manage to find how do you apply the app_public_key?
did you follow this https://developer.amazon.com/docs/appstore-sdk/integrate-appstore-sdk.html?
Thank you!
