### ISSUE TITLE
Getting Error: Error not specified. on getSubscriptions

### ISSUE THREAD

**Issue by lbusz** [dooboolab/react-native-iap#2231]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

using latest version, i get [Error: Error not specified.] when calling (key is the app_public_key)

```
useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      try {
        await initConnection(key);
        const subs = await getSubscriptions({ skus: ['our_sku'] });

        console.log({ subs });

        setSubscriptions(subs);
      } catch (e) {
        console.log({ e });
        setError(e);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);
```

**Expected Behavior**

I expect to get the sku details

**Screenshots**

**Environment:**

- react-native-iap: 12.7.2
- react-native: react-native-tvos@latest
- Platforms (iOS, Android, emulator, simulator, device): FireTV Stick 

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by Pingou** [comment]
@lbusz Did you manage to solve your issue? It was working for me and now for some unkown reason I have the same error as you.

**Comment by Pingou** [comment]
For reference, I typed "adb shell setprop debug.amazon.sandboxmode debug" and it started working.

**Comment by curiousdustin** [comment]
Perhaps the `adb shell setprop debug.amazon.sandboxmode debug` command belongs in the docs somewhere? Worked for me as well.

**Comment by vishalhyperspace** [comment]
Hello all @lbusz @Pingou  @curiousdustin  
For me, it was working fine when I am testing with sandbox (App tester) but when I will submit for live app testing and download from live app testing it gives me an error: Error not specified
My in-app product SKU is in live mode. 
Please help me to fix it. 
Thank you.
