### ISSUE TITLE
error: Abort trap: 6

### ISSUE THREAD

**Issue by subodhsavtiaQss** [dooboolab/react-native-iap#2239]
Hi All,

I am getting this error in my project.
I am using:
React native: 0.70.3
Xcode: 13.1

Here are the some error screenshots:
![217290331-a6f0d749-5c71-47b3-8fe6-4c15645d96b9](https://user-images.githubusercontent.com/69214293/217291899-e38283d5-eb88-4c0c-a276-c1bcc064f025.png)

![217289925-f0474e99-6e9b-43ec-b434-3ae327a7e0c5](https://user-images.githubusercontent.com/69214293/217291939-3c1c6151-ef91-4cf7-afb8-6250b5a5ae99.png)

**Comment by omar-bear** [comment]
me too i have the same problem !

**Comment by subodhsavtiaQss** [comment]
Hi All,

The error has been resolved by updating the Xcode version to **14.2**.

Working fine now.
