### ISSUE TITLE
Android purchaseUpdatedListener running twice.

### ISSUE THREAD

**Issue by TomNes94** [dooboolab/react-native-iap#2246]
**Description**

After upgrading from 12.4.9 to 12.4.14, it seems like `purchaseUpdatedListener` runs twice on Android.

**Expected Behavior**

When a user purchases a subscription, the `purchaseUpdatedListener` is executed once if you correctly use `finishTransaction`.

**Environment:**

- react-native-iap: 12.4.14
- react-native: 0.70.6
- Platforms (iOS, Android, emulator, simulator, device): Android, device.

[Optional] **Additional Context**

Does not happen on iOS.

Listener code is as follows:

```
  useEffect(() => {
    const purchaseUpdateSubscription = purchaseUpdatedListener(async purchase => {
      if (purchase.transactionReceipt) {
        try {
          const os = Platform.OS;
          if (os === 'android' || os === 'ios') {
            await api.user.addSubscription(purchase, os);
            const success = await finishInAppTransaction(purchase);
            if (success) {
              getLoggedInUser();
            }
          }
        } catch (error) {
          handleError(error, false);
        }
      }
    });

    const purchaseErrorSubscription = purchaseErrorListener(error => handleError(error, false));

    return () => {
      purchaseUpdateSubscription.remove();
      purchaseErrorSubscription.remove();
    };
  }, [getLoggedInUser]);
```

**Comment by andresesfm** [comment]
Are you calling the purchase with multiple skus? if so that's the reason

**Comment by andresesfm** [comment]
Another question: is it being called twice with the exact same data?

**Comment by TomNes94** [comment]
The purchase wasnt called with multiple sku's, and it was called in very quick succession with the exact same data. For reasons unknown (I haven't changed a thing), this doesn't occur anymore.
