### ISSUE TITLE
Subscriptions are not working with new Android API - offerToken CANNOT BE NULL

### ISSUE THREAD

**Issue by oarsoy** [dooboolab/react-native-iap#2247]
**Description**

We have been using this module for a very long time. Needed to update to support Google Play Billing v5. Successfully updated and working without issue on iOS. However, on Android we can't run it. We don't have any offers in Google Play console subscription package (no offer is provided). So, we provide "offerToken: null" for Android. However, when user clicks on Subscribe button, it gives "offerToken is required for constructing ProductDetailsParams" error. Why so? Do we have to set up Offer to use this module on Android? Why is the same code working as expected on iOS but not Android? Looking for some suggestions. (Note: We check the receipt on the server side and using component structure)

**Code**

```
async componentDidMount() {

const myProducts = [
      'XXX'
    ];
    	    	  
initConnection().then(() => {
      // we make sure that "ghost" pending payment are removed
      // (ghost = failed pending payment that are still marked as pending in Google's native Vending module cache)
      flushFailedPurchasesCachedAsPendingAndroid()
        .catch(() => {
          // exception can happen here if:
          // - there are pending purchases that are still pending (we can't consume a pending purchase)
          // in any case, you might not want to do anything special with the error
        })
        .then(() => {
	       
          this.purchaseUpdateSubscription = purchaseUpdatedListener(
            (purchase: SubscriptionPurchase | ProductPurchase) => {
              console.log('purchaseUpdatedListener', purchase);
              const receipt = purchase.transactionReceipt;
              if (receipt) {
    
     	AsyncStorage.getItem('keylog')
.then((value) => {

var superreceipt = encodeURIComponent(receipt);
// Do something here which you want to if all the Text Input is filled.
    fetch('XXX', {
  method: 'POST',
  headers: new Headers({
             'Content-Type': 'application/x-www-form-urlencoded', // <-- Specifying the Content-Type
    }),
 body: 'service=purchase&key='+value+'&receipt='+superreceipt})

.then((response) => response.json())
.then( async (response) => {	 
		if (response.status == "ok") {

                      await finishTransaction({purchase, isConsumable: false});

                    } else {
                      // Retry / conclude the purchase is fraudulent, etc...
                      
                    }
                  })
              }
            )}
            })
            })
            })
            
await getSubscriptions({skus: myProducts}) 

}


componentWillUnmount() {

  endConnection();
  
   if (this.purchaseUpdateSubscription) {
      this.purchaseUpdateSubscription.remove();
      this.purchaseUpdateSubscription = null;
    }

    if (this.purchaseErrorSubscription) {
      this.purchaseErrorSubscription.remove();
      this.purchaseErrorSubscription = null;
    }
    
}


async subscribeButton() {
    try {

await requestSubscription({
      sku: "XXX",
         subscriptionOffers: [
           {
             sku: "XXX",          // as a string
             offerToken: null,  // as a string
           },
         ],
    })
    .catch(err => {
       console.log('error buying product', err);
     })
       .then(async res => {
 
      // handle/store response
      
      var superreceipt = encodeURIComponent(res.transactionReceipt);

     	AsyncStorage.getItem('keylog')
.then((value) => {

    fetch('XXX', {
  method: 'POST',
  headers: new Headers({
             'Content-Type': 'application/x-www-form-urlencoded', // <-- Specifying the Content-Type
    }),
 body: 'service=purchase&key='+value+'&receipt='+superreceipt})

.then((response) => response.text())
.then((responseText) => {
	
		var myObjStr = JSON.parse(responseText);
		if (myObjStr.status==="ok") {
			
			this.props.navigation.navigate('Forwarder');			
			}

})

    })
    
    })
    } catch (err) {
      console.log(err.code, err.message);
    }
  }
```

**Environment:**

- react-native-iap: 12.7.2
- react-native: 0.66.1
- Platforms (iOS, Android, emulator, simulator, device):

**Comment by jgillick** [comment]
Even if you do not have any offers setup, Google will still provide an `offerToken` in the response to `getSubscriptions`. This is  how you'd get the first offer returned for the product you're trying to subscribe to:

```
const products = getSubscriptions({ skus: ['XXX'] });
const product = products.find((i) => i.productId === 'XXX');
const offers = product.subscriptionOfferDetails || [];

let offerToken = null;
if (offers.length) {
  offerToken = offers[0].offerToken;
}
```

**Comment by oarsoy** [comment]
> Even if you do not have any offers setup, Google will still provide an `offerToken` in the response to `getSubscriptions`. This is how you'd get the first offer returned for the product you're trying to subscribe to:
> 
> ```
> const products = await getSubscriptions({ skus: ['XXX'] });
> const product = products.find((i) => i.productId === 'XXX');
> const offers = product.subscriptionOfferDetails || [];
> 
> let offerToken = null;
> if (offers.length) {
>   offerToken = offers[0].offerToken;
> }
> ```

Thank you, after adding this it started to work!
Documentation are mess. Do you have any suggestions for implementing Restore mechanism? If the user reinstalls and try to subscribe again, Google Play doesn't allow them to subscribe again. And when this happens, the component doesn't trigger or send the receipt. Do we need to add another purchase condition on the following:

this.purchaseUpdateSubscription = purchaseUpdatedListener((purchase: SubscriptionPurchase | ProductPurchase) => {
