### ISSUE TITLE
How to check Payment Decline status in Android Google Play Store @question

### ISSUE THREAD

**Issue by charles85** [dooboolab/react-native-iap#225]
Hi,

Question:

Recently few of our customers payment has been declined in the Google Play store Transaction history. I don't any API or status reference where we can check Payment decline from Google Play store. Any Advice?

We are using RNIap.buyProductWithoutFinishTransaction(id);

Does validateReceiptAndroid help to validate transaction response from Google Play?

Response from Google Play
{"purchaseToken":"ndtslbfohescbfnvbiwkgkgf","signature":"lM2UG39Fotcsds6arm\/FzkqmZgNJuMpnC0Sl43+ZMx5GvKVqgS0HeXmHSixtxb7+g\/fr8NYTodLHuQ9FXLEbPrHFHkI2udQjtTUR3aEkDXo5WYBmhLd2KRQ4P3fWjfxaf1TnKof4NuysxmNf8Skex2Zlr8AmhXvbX6Fly5MIyLUYlRm90pO8kY6hZhadgURNBlD7nUKK7m+6K17UCfDd+C5qB8pm5h09bpe2M\/bFauKbo+wFlUIsEVyxfrkETn6\/MnE5sQjp3PTGuy464q3Tz6oNrQ==","autoRenewing":false,"data":"{\"orderId\":\"7702772427343288954.2384710893962521\",\"packageName\":\"com.xxxxxxxx\",\"productId\":\"30000_advancedpack\",\"purchaseTime\":1533983071450,\"purchaseState\":0,\"purchaseToken\":\"ndtslbfohescbfnvbiwkgkgf\"}","transactionReceipt":"ndtslbfohescbfnvbiwkgkgf","transactionDate":"1533983071450","transactionId":"7702772427343288954.2384710893962521","productId":"30000_advancedpack"}

**Comment by dooboolab** [comment]
@charles85 I am not sure about this one but validating receipt may help you find out the problem.

**Comment by charles85** [comment]
Ok. We will try with validating receipt on server side because we saw few transaction payment was cancelled after 30 mins user made the purchase. Do we have a callback on this part?

**Comment by charles85** [comment]
Yes.

**Comment by dooboolab** [comment]
@charles85 If user canceled the purchase, I think you can't manage it unless you check the receipt manually. Check `transactionReceipt` field in the readme. Maybe there could be better approach, but currently I think checking the `receipt` is the only way. Check [receipt-validation](https://github.com/dooboolab/react-native-iap#receipt-validation).
