### ISSUE TITLE
IOS Production Return Empty

### ISSUE THREAD

**Issue by RZulfikri** [dooboolab/react-native-iap#2251]
**Description**
Hi I had issue when the app published to the appstore, it work on testflight/debug mode.
When I `getSubscriptions` it return empty response, but in testflight/debut it return list of subscription that I set on the appstore. Anyone know what I was missing?

**Expected Behavior**
return list of subscription

**Environment:**

- react-native-iap: "^12.4.11"
- react-native:  "0.67.5"
- Platforms (iOS): Real Devices (Install from Appstore)

**To Reproduce**
- `initConnection`
- `getSubscriptions`
- return empty

---

**Comment by andresesfm** [comment]
try the latest.

**Comment by andresesfm** [comment]
https://stackoverflow.com/questions/21394359/reasons-for-skproductsrequest-returning-0-products

**Comment by andresesfm** [comment]
Possible fix released here: https://github.com/dooboolab/react-native-iap/releases/tag/12.8.4. Changing productId's Set from `anyhashable` to `string`.

Please reopen if any issues
