### ISSUE TITLE
Need clarifications regarding "Subscription reports version update" for In-App Purchase

### ISSUE THREAD

**Issue by MaxJadav** [dooboolab/react-native-iap#2255]
**Description**
Getting mail from Apple.
We’re reaching out to let you know that, starting March 1, 2023, subscription reports version 1.2 will no longer be available. If you automatically download subscription reports using the App Store Connect API or Reporter, please update your query parameter to version 1.3 if you haven’t already done so. 

Version 1.3 builds on version 1.2, and includes additional data to help you understand subscription offer code redemptions. With version 1.3, you’ll have access to the number of active subscribers using your offer codes and the number of offer code redemptions for your service. You can also find out if subscribers convert to paid renewal when the offer period ends.

**Environment:**

- "react-native-iap": "^10.1.0"
- "react-native": "0.67.2"
- Platforms (iOS):

Which subscription reports version is use here?

**Comment by andresesfm** [comment]
Thank you for the heads up. This library doesn't use the reports or the connect API
