### ISSUE TITLE
"Unable to auto-initialize connection" message on Android (and some suggestions)

### ISSUE THREAD

**Issue by cwhenderson20** [dooboolab/react-native-iap#2265]
**Description**

First, thank you all of the work you do on this module! It's immensely helpful! Unfortunately, I am seeing thousands of promise rejections from Android devices with the message `Unable to auto-initialize connection`. I noticed that others have reported this (#2183, #1958), but there's not enough information in there to help me figure out what's going on. For what it's worth, I believe this is mostly just a warning message. I haven't seen this interfering with purchasing rates on Android.

For context, I am using the `withIAPContext` HOC at the top level of my app, and then a hook that attaches an `onPurchaseUpdated` listener in order to act on changes to the latest purchase.

Simplified, that hook looks like this:

```ts
import { purchaseUpdatedListener } from 'react-native-iap'

function usePurchaseUpdatedListener() {
  const { connected } = useIAP();

  useEffect(() => {
    if (!connected) {
      return;
    }

    async function onPurchaseUpdated(purchase: Purchase) {
      // do some async things like fetching data here...
    }

    const purchaseUpdatedSubscription = purchaseUpdatedListener(onPurchaseUpdated);

    return () => {
      purchaseUpdatedSubscription.remove();
    }
  }, [connected])
}
```

And here's the stacktrace I see in Bugsnag:

```
Error Unable to auto-initialize connection 
    node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:105:50 promiseMethodWrapper
    node_modules/react-native-iap/src/eventEmitter.ts:62:4 purchaseUpdatedListener
    src/data/billing/hooks.ts:218:6 anonymous
    ...
```

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/5496110/222045085-0d0917d0-8fbb-4529-ac26-b72b9979dd6a.png">

So I looked into it a bit, and `purchaseUpdatedListener` comes from `eventEmitter.ts`. The relevant lines are:

```ts
if (isAndroid) {
  getAndroidModule().startListening();
}
```

…which then calls `startListening` from `RNIapModule.kt`. That calls `sendUnconsumedPurchases`, which calls `ensureConnection`, which is where this `Unable to auto-initialize connection` message originates. Ultimately, I don't understand how all of the native code works well enough to make a diagnosis to the root cause, but one thing that I find somewhat strange is that the `getAndroidModule.startListening()` method supposedly returns a Promise, but that I, on the consumer side, have no way to `catch` errors that may be thrown from that Promise. I suspect this is why the error goes uncaught. 

Maybe the code should be modified to either handle the potential rejection internally (if it really is innocuous):

```ts
if (isAndroid) {
  getAndroidModule().startListening().catch(e => console.warn(e));
}
```

You could also bubble it up to the user, but given the fact that the `purchaseUpdatedListener` function already returns an EventEmitter subscription, maybe an `errorCallback` as a second parameter that would be called in the case of an error would work:

```ts
export const purchaseUpdatedListener = (
  listener: (event: Purchase) => void,
  errorCallback?: (error: unknown) => void,
) => {
  //... 
  if (isAndroid) {
    getAndroidModule().startListening().catch(error => {
      if (errorCallback) {
        errorCallback(error);
      } else {
        throw error;
      }
    });
  }

  return emitterSubscription;
};

// ...

const purchaseUpdateSubscription =
      purchaseUpdatedListener(onPurchaseUpdated , (error) => console.warn(error));
```

Though this certainly has its drawbacks as well (mixing three separate async paradigms [events, promises, callback]).

Again, thank you for this module, it's been instrumental in offering subscriptions to users. I'm interested to hear your thoughts on the above.

**Environment:**

- react-native-iap: 12.02
- react-native: 0.70.6
- Platform: Android

**Comment by andresesfm** [comment]
It makes sense to have the option to catch the error or ignore it. This is a bug

**Comment by cwhenderson20** [comment]
Thanks for the reply! I'm most curious why it's happening in the first place, given that I seem to be following all of the guidelines around connection status, but having the option to silently ignore it would be nice.

**Comment by andresesfm** [comment]
How about something like 
```
export const purchaseUpdatedListener = (
  listener: (event: Purchase) => void,
  handleAndroidConnectionFailure: (reason: any) => any = () => {},
) => {
  //...
  if (isAndroid) {
    getAndroidModule().startListening().catch(handleAndroidConnectionFailure);
  }
//...
};
```

In that way, it has a default value so it's not a breaking change

**Comment by cwhenderson20** [comment]
Sure I that works. Though I think that re-throwing the error from inside the Promise _technically_ retains the previous behavior, which is that the error will go uncaught rather than swallowed.

**Comment by andresesfm** [comment]
Upon further research, I went with: https://github.com/dooboolab/react-native-iap/pull/2268.

**Comment by andresesfm** [comment]
Released as `12.8.0` Thank you @cwhenderson20. Please let us know if any other issues

**Comment by ramakula** [comment]
This issue is back again on version 12.13.0. We had to rollback because if impacted our android subscriptions, we had 100s instances of this error: we ended up rolling back to 12.10.8, this is the version .

There is no specific device or android version combination. 

Unable to auto-initialize connection:

<img width="1482" alt="Screenshot 2024-04-26 at 10 31 34" src="https://github.com/dooboolab-community/react-native-iap/assets/2745769/86419dcc-ba34-464b-bb20-8a3b1bde806d">

<img width="1490" alt="Screenshot 2024-04-26 at 10 36 36" src="https://github.com/dooboolab-community/react-native-iap/assets/2745769/0fe55482-7bba-4911-a5d5-99a8f804a572">
<img width="1479" alt="Screenshot 2024-04-26 at 10 36 22" src="https://github.com/dooboolab-community/react-native-iap/assets/2745769/2463a3fc-c1ea-4d1e-9d48-4f36d823f925">

**Comment by moritzkarliczek** [comment]
Same for us. We also experience this issue again with version 12.13.1.

**Comment by andreiciceu** [comment]
Happens aswell on
```
"react-native-iap": "^12.15.1",
```

Any insight into why this happens?

**Comment by GiyoMoon** [comment]
I'm facing the same bug :/ Version `12.15.1`

**Comment by oivoodoo** [comment]
reproduced in `12.15.2` as well. Does anyone could suggest any possible solution?

Thank you for supporting the library!

**Comment by LPDF** [comment]
bump !

**Comment by ramakula** [comment]
Same issue on latest version, we are losing a lot of customers because of this error :(

**Comment by ramakula** [comment]
@andresesfm It looks like the changes from your PR are reverted that's why it's been a problem:

https://github.com/dooboolab-community/react-native-iap/blob/main/src/eventEmitter.ts#L61

Perhaps it is reverted to address other changes?

 @cwhenderson20

**Comment by Aximem** [comment]
#2836 We can't revert lib version because of Android billing 7.0 requierements :/

**Comment by ramakula** [comment]
i've filed a PR based on @cwhenderson20 's suggestions:

https://github.com/dooboolab-community/react-native-iap/pull/2839

**Comment by tvriya** [comment]
I'm facing the same bug :/ Version `react-native-iap@12.15.5`

**Comment by thefavey** [comment]
I’m also facing the same issue. Does anyone have any working code that handles the error effectively? Or tips on how to use the errorHandler with `IAPContext` and `useIAP`?

**Comment by doduy291** [comment]
I'm experiencing the same message when calling `getAvailablePurchases()` and `getSubscriptions()` on version `12.15.1,` so I put them inside a `setTimeout()`, and it seems to work in my case.

**Comment by eyedroot** [comment]
This issue is still reproducible even in the latest version 12.16.2. Are there any updates or news regarding this?

**Comment by ganesht10** [comment]
This issue is still present in latest 12.16.2.
Any solution or fix?

**Comment by unaisdev** [comment]
Something about? We are on `13.0.2` and there is still the error
