### ISSUE TITLE
Got error message "This feature is not available on your device." when run getProducts(...) function on android device.

### ISSUE THREAD

**Issue by RohanSensei** [dooboolab/react-native-iap#2266]
**Description**

With old version like 8.2.*, "getProducts" runs ok on an real Android device.
This happens after updated, the version is ^12.7.4 now.
I use the new function params of course: getProducts({ skus: consumableSkus })

the related codes:
```
const consumableSkus = Platform.select({
  ios: [
    'guajin.iap',
    'middle.guajin.iap',
    'big.guajin.iap',
  ],
  android: ['guajin', 'guajin.middle', 'guajin.big'],
});

...

const {
    connected,
    products,
    // subscriptions,
    getProducts,
    // getSubscriptions,
    finishTransaction,
    currentPurchase,
    currentPurchaseError,
  } = useIAP();

...

const handleGetProducts = async ({skus}: {skus: string[]}) => {
    console.log(consumableSkus)
    await getProducts({ skus: consumableSkus! })
  };
```

**Expected Behavior**
get products data.

**Errors**
Error when handle get products:

```
Possible Unhandled Promise Rejection (id: 0):
Error: This feature is not available on your device.
Error: This feature is not available on your device.
    at promiseMethodWrapper (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=me.suhe.yi&modulesOnly=false&runModule=true:2044:45)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=me.suhe.yi&modulesOnly=false&runModule=true:118556:116)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=me.suhe.yi&modulesOnly=false&runModule=true:20671:26)
...
```

**Environment:**

- react-native-iap: ^12.7.4
- react-native:0.71.1
- Platforms (iOS, Android, emulator, simulator, device):Android device

**To Reproduce**

1. Just run getProducts on an Android device with latest version react-native-iap;
2. Downgrade to old version like 8.**, maybe everything ok.

**Comment by andresesfm** [comment]
That message comes from this Native Error Code: https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode#FEATURE_NOT_SUPPORTED . Maybe the Play Store on the device is outdated?

**Comment by RohanSensei** [comment]
The Play Store version is 25.8.20.20-21, which has just been updated, yet the same issue persists.

**Comment by andresesfm** [comment]
https://stackoverflow.com/questions/72317599/android-google-billing-integration-client-does-not-support-productdetails

**Comment by andresesfm** [comment]
Here are more things to try: https://github.com/android/play-billing-samples/issues/563. Let us know if any of the suggestions work

**Comment by andresesfm** [comment]
For reference, I found that since the migration I converted all the methods from `skuDetails` to `productDetails`. Not all Play Store versions support the `productDetails` native API. the solution would be to implement a method that checks if features are available on the device

**Comment by tomscheney** [comment]
I have a try  upgrade the play store  to 33 , But, it is not work for me.

info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1
    Memory: 219.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/eagle/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.5 => 0.67.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
