### ISSUE TITLE
StoreKit2: appAccountToken is always null on the JS side

### ISSUE THREAD

**Issue by zarv1k** [dooboolab/react-native-iap#2269]
**Description**

`TransactionSk2.appAccountToken` is always null

**Expected Behavior**

`TransactionSk2.appAccountToken` is UUID string when provided in `purchaseRequest`

**Environment:**

- react-native-iap: 12.7.3, 12.8.0
- react-native: 0.70.6
- Platforms (iOS): 15+

**To Reproduce**

```ts
setup({ storekitMode: 'STOREKIT2_MODE' });
// ...
const sku = 'com.example.product';
// ...
await requestPurchase({
  quantity: 1,
  appAccountToken: '73d7bd1d-0d44-4600-86b8-4222570a0931',
  sku,
  andDangerouslyFinishTransactionAutomaticallyIOS: false,
});
// ...
const transactionSk2 = await IapIosSk2.latestTransaction(sku);
console.log(transactionSk2.appAccountToken); // null but should be '73d7bd1d-0d44-4600-86b8-4222570a0931'
```
---

**Additional Context**

It seems like the native UUID (including optional UUID?) instance serialization is broken on the react-native-iap lib side or on the RN bridge side

**Comment by andresesfm** [comment]
Thank you @zarv1k . Released as `12.8.1`
