### ISSUE TITLE
getAvailablePurchases and Promo Codes

### ISSUE THREAD

**Issue by Hjord** [dooboolab/react-native-iap#227]
### Version of react-native-iap
0.3.23

### Platforms you faced the error (IOS or Android or both?)
iOS

### Actual behavior
I have 2 devices with the same Apple ID.
2 different items bought with promo code (Non-consumable)
When calling getAvailablePurchases only the purchase made from the other device is restored.
If I restore on a 3rd device, both items is restored.

In short: In app products 'bought' by promo codes, does not unlock on the device, it was redeemed on. But it unlocks on the user's other device(s).

### Expected  behavior
All purchases, promo code or not, restored on all devices.

### Tested environment (Emulator? Real Device?)
Real devices on App Store version

Maybe this is not a problem with this module.
But I find it hard to test and any help is appreciated.

**Update:**
I have added some logging for the production app.
And I can confirm that the only thing returned when restoring, is the  product unlocked on the other device.

**Comment by JJMoon** [comment]
I cannot understand what your question means.
I guess you are testing restoring non-consumable products. 
I suggest you to make a new sandbox tester and test from the scratch.
Your question looks irrelevant to this module itself.

**Comment by Hjord** [comment]
I have updated original post.
It may be irrelevant, I honestly don't know. It's a really weird behavior

**Comment by Hjord** [comment]
No one who know, what may cause this?

**Comment by Hjord** [comment]
After a bit more research I have found out Promo Codes does only work in production environment.
I cannot test it in sandbox.

**Comment by Hjord** [comment]
Update:
I have added some logging for the production app.
And I can confirm that the only thing returned when restoring, is the  product unlocked on the other device.

**Comment by JJMoon** [comment]
I found same symptom here.
https://github.com/bizz84/SwiftyStoreKit/issues/113
I hope when you test, erase the app, turn off the device.
@Hjord  Thank you for your post.

**Comment by Hjord** [comment]
I just tried uninstalling the app, restart the phone, install the app and restore.
Same thing happens.

I have tried with a newly create Apple ID. Here it works as expected.

**Comment by dooboolab** [comment]
@Hjord can you try this again with the new update which is `2.2.0`? We've made some fixes and want to know if it resolves your symptoms.
