### ISSUE TITLE
Questions about Subscribing promoted 

### ISSUE THREAD

**Issue by leechanghoon3024** [dooboolab/react-native-iap#2275]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

Hello, I'm having a hard time with subscription promotion in IOS.

Using the ```requestSubscription```  method, the process of printing the subscription list and paying for the subscription was completed.

However, I set up a subscription promotion (free tier for a week), but it is not displayed on the subscription payment sheet. 

When referring to other apps, I know that it is displayed as text after setting up promotions.

```withoffer``` parameter in the ```requestSubscription``` method also created a code, but it is not exposed.

In the original sandbox, subscription promotions are not exposed and charges are not paid. Does it only print text?
Or did I make a wrong key, or do I miss something?
When receiving subscription information, it was confirmed that the information of the promotion was received. in discount parameter 

```
[{"identifier": "XXXXX_PROMOTION", "localizedPrice": "₩0", "numberOfPeriods": "7", "paymentMode": "FREETRIAL", "price": "0", "subscriptionPeriod": "DAY", "type": "SUBSCRIPTION"}]
```

1. Subscription settings and promotion registration in the app store
2. Insert ```sku`` and ```withoffer``` in the ```requestSubscription``` method
3. However, information about the promotion is not exposed in the subscription sheet.
4. Is there anything I miss?

**Expected Behavior**

**Screenshots**
![스크린샷 2023-03-09 오후 4 57 00](https://user-images.githubusercontent.com/73262261/223957814-bcf996d5-b40e-465d-ae2f-f653caeb2451.png)

**Environment:**

- react-native-iap:   "12.8.2",
- react-native:   "0.68.1",
  
- Platforms (iOS, Android, emulator, simulator, device):
- IOS 14 device(16.2)

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
@leechanghoon3024 I would start by updating your version of `r-n-iap`. the r.c. builds are not meant for production

**Comment by leechanghoon3024** [comment]
@andresesfm Changed the version to 12.8.2 Yet my issue remains the same.

**Comment by andresesfm** [comment]
Could this be an expected behavior on the Sandbox?

**Comment by leechanghoon3024** [comment]
@andresesfm  Neither the sandbox nor the production shows any statement about the Promotion.

**Comment by andresesfm** [comment]
Can you include the code you are using?

**Comment by leechanghoon3024** [comment]
I modified it by adding the appropriate parameter to the withoffer.
```
 const withOffer =
 {
      identifier: identifier,
      keyIdentifier: keyIdentifier,
      nonce: nonce,
      signature: signature,
      timestamp: timestamp
};
```
thanks

**Comment by MissingCorner-HaoPhan** [comment]
> 

How can i get those parameters

**Comment by MissingCorner-HaoPhan** [comment]
> I modified it by adding the appropriate parameter to the withoffer.
> 
> ```
>  const withOffer =
>  {
>       identifier: identifier,
>       keyIdentifier: keyIdentifier,
>       nonce: nonce,
>       signature: signature,
>       timestamp: timestamp
> };
> ```
> 
> thanks

How can i get those parameters
