### ISSUE TITLE
RNIap.prepare : canMakePayments is not a function

### ISSUE THREAD

**Issue by lc3t35** [dooboolab/react-native-iap#228]
### Actual behavior

RNIap.prepare sometimes throws an error :
RNIap.prepare error :  TypeError: a.canMakePayments is not a function. (In 'a.canMakePayments()', 'a.canMakePayments' is undefined)

### Steps to reproduce the behavior
```
try {
    await RNIap.prepare();
}
catch (error) {
    console.log("RNIap.prepare error : ", error);
}
```
Link Library seems to be set accordindly to documentation :
![capture d ecran 2018-08-14 a 00 59 00](https://user-images.githubusercontent.com/921372/44062607-5b57eb98-9f5d-11e8-8467-9a49547decbf.png)

As it is something I track in Sentry, I don't have the full context of use on client side, it is possible it happens when the user hit the cancel button when asked for his AppStore credentials or when you are in a Sandbox mode .I need to dig more into this, to give more context and reproducible behavior.

**Comment by dooboolab** [comment]
@lc3t35 I am suspecting the mismatch version of `react-native-iap` with the native side. Did you use `react-native-code-push` to actually publish new version of your app? `canMakePayments` had been implemented in later version so currently, I am doubting about it.

**Comment by lc3t35** [comment]
@dooboolab  no, I don't use react-native-code-push but I've detached from expo, add manually as explained in Readme (I can see in Xcode the correct code with canMakePayment), and update code if needed with exp publish.

**Comment by cuiying408** [comment]
Same issue here

**Comment by dooboolab** [comment]
@lc3t35 @cuiying408 Are you both using expokit? Will this [link](https://github.com/dooboolab/react-native-iap/issues/14) help? Or [this](https://github.com/dooboolab/react-native-iap/issues/178) one.

**Comment by dooboolab** [comment]
@lc3t35 Also, if you `publish` from expo without releasing new native app, this might cause the problem. `publish` just works as same as that in `react-native-code-push`.

**Comment by lc3t35** [comment]
@dooboolab  please read Actual behaviour : "RNIap.prepare SOMETIMES throws an error :" ;)my app is working fine in sandbox mode as I test it before submitting to Apple (it was submitted yesterday for review).
I just noticed that **sometimes** I have this message, but I was not able to track why it happens.
I suppose it might happen when the user cancels the authentication process on appStore if the user was not defined (for the test I disconnect my personal appStore account so I can login with the sandbox account), I remember that I've tested that my app handle correctly the case "user cancels App store's authentication".

**Comment by lc3t35** [comment]
@dooboolab you mean that I have to submit a new app each time I publish ? so what is the interest of react-native if I can hot push RN modifications of the app without touching the app ...

**Comment by dooboolab** [comment]
@lc3t35 I've read the behavior and I was suspecting if you've upgraded our module and just published to `expo` where `canMakePayments` method is missing in native side. If you've upgraded our module, you must submit new app to apply the native side too.

**Comment by lc3t35** [comment]
@dooboolab ok I should have stated that the module was already published with the correct current version that has canMakePayments method. Even the previous build already had the last version of react-native-iap. Of course if there is an update in react-native modules such as react-native-iap, you have to resubmit a build of the app. The current build of the app has the current version of react-native-iap. The iOS app used for the test is this latest build (all this is tracked on Sentry so I'm 100% sure).

**Comment by dooboolab** [comment]
@lc3t35 That's ok. I just tried to share things that I know of. I think we need more information for this one to actually solve it. Please come back to us when you find something new.

**Comment by chiragpurohit71085** [comment]
I had similar issue, but that was resolved by unlinking and linking again

react-native unlink react-native-iap

react-native link react-native-iap
  
Scanning folders for symlinks in /InappTest/node_modules (14ms)
rnpm-install info Linking react-native-iap ios dependency
rnpm-install info Platform 'ios' module react-native-iap has been successfully linked
rnpm-install info Linking react-native-iap android dependency
rnpm-install info Platform 'android' module react-native-iap has been successfully linked

**Comment by dooboolab** [comment]
Closing this since it seems `linking` issue in `react-native`.
