### ISSUE TITLE
Android Static responses don't work

### ISSUE THREAD

**Issue by naldyn** [dooboolab/react-native-iap#229]
### Version of react-native-iap
1.4.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Use one on the following product IDs during a purchase operation:
android.test.purchased
android.test.canceled
android.test.refunded
android.test.item_unavailable

### Actual behavior
Error message: An error occurred when the server information was retrieved ([DF-BA-AH-01])

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
    RNIap.buySubscription(sku).then((purchase) => {
      //Process result
    }).catch((error) => {
      alert(error);
    });

**Comment by dooboolab** [comment]
@naldyn This is related to [play service issue](https://productforums.google.com/d/msg/play/3dV1K-yk9XY/B0iuvo4nCAAJ). Could you follow [this](https://productforums.google.com/d/msg/play/3dV1K-yk9XY/B0iuvo4nCAAJ)?

**Comment by haotangio** [comment]
Also having the same issue.
@dooboolab I did follow the guideline there but the issue is not solved.
Did someone overcome this problem?
