### ISSUE TITLE
Can you add introductory price?

### ISSUE THREAD

**Issue by gitbyzin** [dooboolab/react-native-iap#23]
Your awesome package is well used.
I need introductory price infomation.
Can you add introductory price?

getIntroductoryPrice()
getIntroductoryPriceCycles()
getIntroductoryPricePeriod()

**Comment by JJMoon** [comment]
OK. We will implement these methods. Thank you for your concern.

**Comment by dooboolab** [comment]
@gitbyzin 
Just wondering. Is this feature supported in Android too?

**Comment by JJMoon** [comment]
@gitbyzin Sorry for late reply. But, I found there would be nothing to implement in source code. It's some more setting in iTunesConnect product page. 
It looks like matter of parsing the product information.
