### ISSUE TITLE
Possibility to purchase more than 1 of the same consumable?

### ISSUE THREAD

**Issue by lefoy** [dooboolab/react-native-iap#231]
Do you think it would be possible to implement the quantity property for iOS? I need to be able to purchase the same product multiple time.

https://developer.apple.com/documentation/storekit/skmutablepayment/1506170-quantity

Thank you!

**Comment by dooboolab** [comment]
@lefoy If you find same funtionality in `android`, I'd consider this in next update.

**Comment by lefoy** [comment]
Unfortunately we didn't find the same functionality on Android :(

Maybe we could add a parameter to the buyProduct function and do nothing with it on Android? I know it's a bit counter intuitive but it would be a great addition for iOS.

The other plugin we were using for IAP is having some issues so we are thinking about switching to this plugin instead. The quantity parameter is very important for our app so we might have to add the functionality in our forked branch, but if we can find a way to implement it to this library, it would be best.

Here's the commit where we added the quantity parameter to the current plugin we are using. https://github.com/exposio/react-native-in-app-utils/commit/af5d860bc4e9aa87136e8e82c2a546b50ce559a6

As you can see it's not a big change so I wouldn't mind working on a PR, but given the fact that such functionality doesn't exist on Android, I'm not sure how to add it to this library. Currently we are using different products to achieve the same functionality on Android (com.xxxx.product1, com.xxxx.product2, com.xxxx.product3...)

Thank you for your quick replies, have a great day

**Comment by dooboolab** [comment]
@lefoy Thanks. If you desperately need this feature, I'd request you to implement `buyProductWithQuantityIOS` to make sure that it only works in `ios`. `PR` will be good.

**Comment by dooboolab** [comment]
[PR](https://github.com/dooboolab/react-native-iap/pull/240) merged.

**Comment by ningacoding** [comment]
on Andtroid it's posible but not implemented yet. any update?.
