### ISSUE TITLE
Error in 2.0.0-alpha3 release (Android)

### ISSUE THREAD

**Issue by kolyaVV** [dooboolab/react-native-iap#232]
### Version of react-native-iap
2.0.0-alpha3

### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Work properly
### Actual behavior
Error
### Tested environment (Emulator? Real Device?)
Both
### Steps to reproduce the behavior
Just clone 2.0.0-alpha3 and try to run the Android example.

### Solution is 
There are probably just typos in the latest release.

FILE: RNIapModule.java
line 306    purchase.isautoRenewingAndroid() must be purchase.isAutoRenewing()
line 404    purchase.isautoRenewingAndroid() must be purchase.isAutoRenewing()

**Comment by ernestcdc** [comment]
Hi, I am experiencing the same issue. How do you get around this?

**Comment by ernestcdc** [comment]
I can confirm this issue exists in 2.0.0-alpha3. Workaround is indicated above by @kolyaVV.

Reference: https://developer.android.com/reference/com/android/billingclient/api/Purchase

**Comment by dooboolab** [comment]
@kolyaVV Fixed in `2.0.0-alpha4`. Sorry I don't know why my editor changed that to lowercase. Please reopen when still causing problem.
