### ISSUE TITLE
getProducts() crashes on iOS < 11.2 because introductoryPrice is nil

### ISSUE THREAD

**Issue by swapkids** [dooboolab/react-native-iap#233]
### Version of react-native-iap
2.0.0-alpha3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
not crash

### Actual behavior
crashes:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[9]'

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
call getProducts() on < 11.2 device

### Fix

add this:
NSString* introductoryPrice = localizedPrice;
instead of
NSString* introductoryPrice;

in line 278 of RNIapIos.m

**Comment by dooboolab** [comment]
@swapkids Thanks. Will publish this to `2.0.0-alpha7`.
