### ISSUE TITLE
validateReceiptIos always returns false

### ISSUE THREAD

**Issue by fabianunger** [dooboolab/react-native-iap#237]
### Version of react-native-iap
2.0.0-alpha3
(I tried 1.1.5 as well, same issue)
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
validateReceiptIos returns 0/1/true for valid receipts
### Actual behavior
validateReceiptIos always returns false
### Tested environment (Emulator? Real Device?)
Real device, sandbox app store
### Steps to reproduce the behavior
I am able to make auto renewable subscription purchases successfully, and receive a transaction receipt. When I try to validate this on iOS using validateReceiptIos(receiptBody, true, 55) I always get returned false.

If I log JSON.stringify(res) I get:
{"status":21004, "environment":"Sandbox"}

There was a similar issue at [#190](https://github.com/dooboolab/react-native-iap/issues/190)

**Comment by LinusU** [comment]
At which line are you inserting the log at? 🤔

**Comment by dooboolab** [comment]
@fabianunger Strange. Should be fixed in #190. Could you share some codes?

**Comment by fabianunger** [comment]
```
 validate = async (product) => {
    try {
      console.log(product);

      const receiptBody = {
        'receipt-data': product.transactionReceipt,
      };
      console.log(receiptBody);

      const result = await RNIap.validateReceiptIos(receiptBody, true, 55).then(res=>{
        console.log(JSON.stringify(res));
      });
      console.log(result);

    } catch(err) {
      console.warn(err.code, err.message);
      Alert.alert(err.message);
    }

  };

```

**Comment by fabianunger** [comment]
"react": "^16.3.2",
    "react-native": "^0.55.3",

**Comment by fabianunger** [comment]
@dooboolab It does not need a shared secret somewhere, right?

**Comment by LinusU** [comment]
@fabianunger Could you try out [this version](https://github.com/dooboolab/react-native-iap/pull/239) and see if it gives you a more detailed error message?

```sh
npm install LinusU/react-native-iap#ios-validate
```

**Comment by fabianunger** [comment]
@LinusU @dooboolab 
I just added the shared secret in the receiptBody and now it seams to work out.
Maybe I just missed it somewhere in the docs? Or is that not the way it is supposed to happen?
```
  const receiptBody = {
        'receipt-data': product.transactionReceipt,
        'password': '*********'
      };
```

**Comment by fabianunger** [comment]
@LinusU 
I tested it also with your version: Same outcome. 
As a response I get {"status":21004, "environment":"Sandbox"}.

Works by adding the shared secret as the 'password' within the receiptBody. In general: Is this the regular way anyway?

**Comment by dooboolab** [comment]
@fabianunger You've done it right. For more information [ref](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html) here.

**Comment by venku122** [comment]
What is the `shared secret` and where can I find it?

**Comment by khorark** [comment]
> What is the `shared secret` and where can I find it?

https://www.appypie.com/faqs/how-can-i-get-shared-secret-key-for-in-app-purchase

**Comment by imanshu1** [comment]
Validate Reciept in Production Mode returning {status: 21007} , can anyone help mw with this.

Thanks in advance

**Comment by mrcwerfar** [comment]
Look here:

https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html

"21007:  This receipt is from the test environment, but it was sent to the production environment for verification. Send it to the test environment instead."

use this address for test environment verification: https://sandbox.itunes.apple.com/verifyReceipt

**Comment by Ajaymedicine608** [comment]
@fabianunger https://stackdev.space/questions/expanding-capabilities-with-cross-platform-integration
