### ISSUE TITLE
prepareAndroid

### ISSUE THREAD

**Issue by KjellConnelly** [dooboolab/react-native-iap#24]
To simplify things, prepareAndroid should be called and ignored, with and then run the promise for ios devices. Currently, on ios, prepareAndroid does nothing, and crashes on attempted promise.

```javascript
// crash on ios
RNIap.prepareAndroid().then(message=>{
    // call get items function
}).catch(error=>{
    // handle error
})
```

Instead, I had to write conditional code

```javascript
// works, but extra unneeded code
if (Platform.OS == 'ios') {
    // call get items function
    return
}

RNIap.prepareAndroid().then(message=>{
    // call get items function
}).catch(error=>{
    // handle error
})
```

Could you make it so ios still handles the promise?

**Comment by JJMoon** [comment]
I tested module in iOS, but never crashed at that part. 
I guess we used await instead of promise handling. 
Please refer to the line 43 in example. https://github.com/dooboolab/react-native-iap/blob/master/RNIapExample/src/components/pages/First.js

We will change that part, not to crash. 
Thank you for your help.

**Comment by JJMoon** [comment]
I guess you can use await everywhere in RN project.
But, you define the function which use await as async. Just like the above componentDidMount in  First.js. I hope this will help.

**Comment by dooboolab** [comment]
@KjellConnelly @JJMoon 
Is this solved?

**Comment by KjellConnelly** [comment]
@JJMoon Thanks for letting me know about adding ```async``` in front of the function. I didn't know, and just assumed it wasn't a feature that worked. After testing it, it works - sort of... But there is still a problem on ios:

```prepareAndroid()``` should either return a message, or an errorCode. Before, when we were using ```prepare()```, I would do it like this:

 ```javascript
RNIap.prepareAndroid().then(message=>{
  // Ready to call RNIap.getItems()
}).catch(errorCode=>{

})
```

The equivalent using ```await``` looks like:

```javascript
async function myFunction() {
   try {
      const message = await RNIap.prepareAndroid()
   } catch(errorCode) {
      
   }
}
```

Unfortunately, it looks like when using try/catch, it always runs the catch function. This is probably because for ios, the function doesn't return the promise properly. Of course, if I don't use try/catch, and just run ```const message = await RNIap.prepareAndroid()``` by itself, then ios basically ignores it.

**Comment by JJMoon** [comment]
@KjellConnelly I tested with the Example in our repository. It's fine on iOS simulator. And it didn't catch the error. The only difference in our codes are 
```
async function myFunction() // in your code
```
instead of member function. 
So, I suggest you to test with our example, edit the bundle ID, and product ids.
I hope you have fine result.

**Comment by KjellConnelly** [comment]
@JJMoon I believe the example code does not use a try/catch. It just awaits a response. If in componentDidMount, you add the try/catch statement, it’ll always catch on my iOS real device. 

Try/catch should be used since catch will catch android error codes

**Comment by dooboolab** [comment]
@KjellConnelly
Can you share what version you are using? Because this should not happen in later version of ‘0.2.*’

**Comment by KjellConnelly** [comment]
@dooboolab I just updated to the current github version, and it looks like it is working now :) Sorry about that. I didn't update since you made the fixes. Didn't realize that you made them.
