### ISSUE TITLE
'React/RCTLog.h' file not found RNIapIos

### ISSUE THREAD

**Issue by backmeupplz** [dooboolab/react-native-iap#241]
### Version of react-native-iap
`2.0.0-alpha8`

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
App builds

### Actual behavior
App doesn't build

### Tested environment (Emulator? Real Device?)
Emulator and real device

### Steps to reproduce the behavior
1. Add `react-native-iap` to the project `npm install react-native-iap --save`
2. Enable iaps in the Xcode capabilities
3. Link the framework `react-native link react-native-iap`
4. Try building the app

Getting error `'React/RCTLog.h' file not found RNIapIos`, not sure what to do now.

**Comment by backmeupplz** [comment]
Manual installation works

**Comment by dooboolab** [comment]
@backmeupplz The linking system itself isn't perfect. If something doesn't work you should first try open xcode and build from there and try the manual linking.
