### ISSUE TITLE
How to purchase same product again

### ISSUE THREAD

**Issue by muha-loop4** [dooboolab/react-native-iap#247]
"react-native-iap": "^2.0.0-alpha12"
"react": "16.3.1",
"react-native : 55

I want to know is it possible to buy the in app product again, after buying it, because when i try to buy it again, using 

 buyItem = async sku => {
    try {
      console.info("buyItem: " + sku);
      //const purchase = await RNIap.buyProduct(sku);
      const purchase = await RNIap.buyProductWithoutFinishTransaction(sku);
      
      console.info(purchase);
      this.setState({ receipt: purchase.transactionReceipt }, () =>
        this.goToNext()
      );
      RNIap.finishTransaction();
    } catch (err) {
      //console.warn(err.code, err.message);
      Alert.alert("Transaction canceled: " + err.message);
    }
  };

Alert appears that you already own this product.

 I want to buy it again, how can i do that. In android.

**Comment by Bang9** [comment]
consumePurchase(purchaseToken)

**Comment by pehagg** [comment]
Wait, what? Why on Earth do you need to consume a non-consumable IAP? Is this some kind of Android idiocy?

**Comment by Bang9** [comment]
@pehagg Android only supported two purchases that are product and subscription, only iOS has non-consumable purchase type

**Comment by pehagg** [comment]
@Bang9 , adding consumeProduct didn't help in our case. In the code we buy the product and consume it immediately after the purchase has been done. When I try to buy the same IAP the second time nothing happens, no error, nothing. Using 1.0.5, has there been any fixes to the functionality after that?

**Comment by dooboolab** [comment]
@pehagg Are you on android?

**Comment by pehagg** [comment]
Yes, I am. But I might've tested with an old build (one missing the consumePurchase call), internal test track is playing a trick on me. Let me get back to you once I've verified with the correct build. Sorry.

**Comment by pehagg** [comment]
Need to release the app to production to test this. Hope it works...

**Comment by pehagg** [comment]
Still seeing the same issue. Probably due to old purchases not being consumed.

**Comment by dooboolab** [comment]
@pehagg Yeah. For some situations like this, I've implemented `consumeAllItems` method. You can use this when you start your app. Then later when you feel confident that you don't lose anything, you may take this away in later release.

**Comment by pehagg** [comment]
This is what I ended up doing too. Now it works as it should. Should’ve read the API docs more closely when we started using the library on Android :)
