### ISSUE TITLE
initConnection is not a function

### ISSUE THREAD

**Issue by lgraubner** [dooboolab/react-native-iap#249]
### Version of react-native-iap

2.0.2

### Platforms you faced the error (IOS or Android or both?)

both

### Expected behavior

`initConnection` should be exported.

### Actual behavior

`initConnection` is not defined on the default export.

### Tested environment (Emulator? Real Device?)

Emulator

### Steps to reproduce the behavior

```JavaScript
import RNIap from 'react-native-iap';

RNIap.initConnection();
```

**Comment by jameslporter** [comment]
Can confirm. Happening to me too. It would be nice if the setup guide actually guided you through a simple purchase flow and it work as advertised.

**Comment by JJMoon** [comment]
I hope this work.
```
import * as RNIap from 'react-native-iap';
```

Please refer to the example. https://github.com/dooboolab/react-native-iap/blob/master/RNIapExample/src/components/pages/First.js

**Comment by lgraubner** [comment]
@JJMoon while this works it's inconsistent regarding the other methods. I created a PR.
