### ISSUE TITLE
In app product integration requirements.

### ISSUE THREAD

**Issue by muha-loop4** [dooboolab/react-native-iap#252]
Hi, i would like to know, my paid application agreement in app connect is pending, so that means i cant get the product list , and i cant buy it. Only bank details are pending. so should i need to first complete the agreement and then i will be able to get products or buy product.

And do i have to submit the build which contains in app purchase buying code. actually i have submitted the app, now it is in review status, so first build which is been submitted doesnot contains react-native-iap feature. after that i have created the in app products, and the status is ready to submit, but the paid agreement is pending due to bank details. so what should i need to do in order to use react-native-iap in IOS app.

<img width="718" alt="snap1" src="https://user-images.githubusercontent.com/40353747/45215969-be7dd400-b2a7-11e8-8459-cc6143bc5bc5.png">

<img width="729" alt="sanp2" src="https://user-images.githubusercontent.com/40353747/45215977-c2115b00-b2a7-11e8-8b0c-64612fcb9331.png">

android is in working condition no problem.

**Comment by JJMoon** [comment]
I guess it's a kind of country issue. I cannot completely understand your question.
If it's bank issue, I suggest you to take a time to wait the bank do their job.
And you can test your IAP products even if you don't summit the App Store review.
This is not an issue of this module, I close this.

**Comment by muha-loop4** [comment]
Hi, sorry about my confusing explanation, i have completed the integration of react-native-iap, but when i cant get products, and make payments in android. but in ios the RNIap.getProducts(itemSKus) return empty array. 

const itemSkus = Platform.select({
  ios: [
    '344'
  ],
  android: [
    '344'
  ],
});
const result = await RNIap.initConnection();
const products = await RNIap.getProducts(itemSkus);
console.log(products, result);
await RNIap.endConnection();

Now result is true
but products is empty array

Please Help.
