### ISSUE TITLE
getProducts() and getSubscriptions() show duplicates

### ISSUE THREAD

**Issue by petetastic** [dooboolab/react-native-iap#258]
### Version of react-native-iap
2.1.1

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
getProducts and getSubscriptions should return a singular list of products

### Actual behavior
Each successive call to either of these functions returns a cumulative list, instead of the same list.

### Tested environment (Emulator? Real Device?)
Both

### Steps to reproduce the behavior
Call getSubscriptions() twice in a row

This seems to be down to two problems in the getProducts() function in Objective-C:

Firstly this line:

`if (cur.productIdentifier == aProd.productIdentifier) {`

...fails to compare the strings correctly, but it works with:

`if ([cur.productIdentifier isEqualToString:aProd.productIdentifier]) {`

Secondly this line:
`if (delTar > 0) {`

...doesn't account for a duplicate at position 0, so it should instead be:
`if (delTar >= 0) {`

These fixed work for me.

Cheers

**Comment by dooboolab** [comment]
@petetastic Yeah looks bug in this [PR](https://github.com/dooboolab/react-native-iap/pull/253/files). Would you like to give us a [PR] to resolve this?

**Comment by petetastic** [comment]
eek! I'd love to, but I'm afraid I don't know how to do that! Happy to if you show me how, otherwise equally I can wait until you fix it, that's not a problem. Cheers.

**Comment by dooboolab** [comment]
You can see guide [here](https://help.github.com/articles/creating-a-pull-request/). Generally, you may fork our repo then update your fix and then create a `PR`.

**Comment by dooboolab** [comment]
@petetastic I've updated your fix in `2.1.2` please try again.
