### ISSUE TITLE
iOS: How to consume products

### ISSUE THREAD

**Issue by idlework** [dooboolab/react-native-iap#259]
When my users switch with their credit card or Paypal account, the product is bought but the function `buyProductWithoutFinishTransaction` is never resolved. When the users try to purchase this product again they get the an alert with the message `This in-app purchase has already been bought”` and again the function `buyProductWithoutFinishTransaction` does not resolves.

This same process happens when you use the sandbox user for iOS purchases

### Version of react-native-iap
2.1.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Function `buyProductWithoutFinishTransaction` should always resolve even when item is already bought.

### Actual behavior
Function `buyProductWithoutFinishTransaction` never resolves

### Tested environment (Emulator? Real Device?)
Real device (iPhone 5, 6, 8)

### Steps to reproduce the behavior
```
try {
      const transaction = await RNIap.buyProductWithoutFinishTransaction(productId)
      await addCreditsForPurchase({ receipt: transaction.transactionReceipt })
      await RNIap.finishTransaction()
    } catch (e) {
      console.log(e.message)
    }
```
The app never get past `buyProductWithoutFinishTransaction`, there for `addCreditsForPurchase` and `finishTransaction`fucntions are never called.

**Comment by JJMoon** [comment]
I guess the finishTransaction wasn't called properly or it just failed when user purchased previously.
And, the next purchase would not be resolved. 

If this is the case additional finishTransaction call might help.

But, our objective-C method checks if there is not resolved transaction as follows.
```
 if (currentTransaction) {
    [[SKPaymentQueue defaultQueue] finishTransaction:currentTransaction];
  }
  currentTransaction = nil;
```

I guess another method is worth testing with removing `if` clause.

**Comment by dooboolab** [comment]
Closing this since it is dupe in #257
