### ISSUE TITLE
Problem with introductoryPrice in subscriptions

### ISSUE THREAD

**Issue by zalempro** [dooboolab/react-native-iap#260]
### Version of react-native-iap

react-native-iap 2.1.1

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

When we get introductoryPrice of a subscription (getSubscriptions) we should see SKProductDiscount info as :

- introductoryPrice
- introductoryPricePaymentMode
- introductoryPriceNumberOfPeriods 
- introductoryPriceSubscriptionPeriod

### Actual behavior
Now we receive object reference:
"introductoryPrice": "<SKProductDiscount: 0x600002660240>",

### Tested environment (Emulator? Real Device?)

iOS Emulator

### Steps to reproduce the behavior

1 - Create subscription with introductory Price ( trial, ... )
2 - Get info of this subscription 

### Maybe a solution

[RNIapIos.m.zip](https://github.com/dooboolab/react-native-iap/files/2379886/RNIapIos.m.zip)

**Comment by dooboolab** [comment]
@zalempro Would you like the update with the source you've provided?

**Comment by dooboolab** [comment]
[Updated](https://github.com/dooboolab/react-native-iap/commit/d55a2d76ddb1573e5aa56d2d710a3547ad7ce074) should be fine.
