### ISSUE TITLE
getProducts Returns Empty [] on IOS

### ISSUE THREAD

**Issue by helbery** [dooboolab/react-native-iap#263]
### Version of react-native-iap
2.1.1
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Returning list of products
### Actual behavior
Our app is already approved and ready for sale on App Store and all products is approved but still when i call RNIap.getProducts it returns empty []
### Tested environment (Emulator? Real Device?)
Emulator and Real Device

**Comment by dooboolab** [comment]
@helbery Have you gone through #256?

**Comment by tmjordan** [comment]
Hi everyone, I have the same problem. I always get an empty array when calling getProducts
@hyochan @helbery

**Comment by kelrik** [comment]
@hyochan @helbery Hello! I also have same problem with getProducts.

**Comment by helbery** [comment]
@hyochan @tmjordan  yes it is fixed the issue with me that we didn't sign the tax contract and agreement with apple once signed all products returned

**Comment by tmjordan** [comment]
@helbery on android, i also have the same issue
