### ISSUE TITLE
Cross platform receipt validation 

### ISSUE THREAD

**Issue by ohpax** [dooboolab/react-native-iap#266]
while I was designing my app, I came up with a big problem. 
my app is for both Ios and Android and I have monthly subscription. 
I know that the only way I know the user has not canceled the purchase is by validation of his receipt.
but lets imagine this scenario. My user has two phones one Android and one Ios. And, he makes the purchase using the Ios, but he decides to use the android and he does not open my app in his Ios. Then, there is no way to know what is the next months receipt number or I can not even make sure he did not cancel his subscription. 
do you have any workaround for this scenario !?

**Comment by dooboolab** [comment]
@ohpax Basically, users have to pay for each ios and android for their subscriptions. I haven't seen any app syncing the subscription on each platform. If you have seen something like that please share.

**Comment by ohpax** [comment]
I think I found my answer. I need to have a webhook to handle change events => https://help.apple.com/app-store-connect/#/dev0067a330b
