### ISSUE TITLE
Cannot make connection by RNIap.initConnection() in real android device

### ISSUE THREAD

**Issue by pongponglau** [dooboolab/react-native-iap#268]
### Version of react-native-iap
2.2.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Expected to call const result = await RNIap.initConnection(); successfully

### Actual behavior
await RNIap.initConnection() always return false, sometimes i see the following error message:

"Already started. Call endConnection method if you want to start over. ".

However, i call RNIap.endConnection in the finally block.

### Tested environment (Emulator? Real Device?)

Real android device with the released version of apk

### Steps to reproduce the behavior
Just call const result = await RNIap.initConnection();

**Comment by ShooterArk** [comment]
Just add this code to your component with IAP and this error will handled,

`componentWillUnmount() {
        RNIap.endConnection();
    }`

**Comment by pongponglau** [comment]
Thanks for your suggestion. I have tried to end connection in componentWillUnmount, however, i still get the same issue. Do i need to configure anything in android phone before using in-app purchase? 

Currently, i will go through the whole cycle, i.e. initconnection, getproduct, buyproduct, endconnection every time the purchase button is clicked by user. I just develop a function to wrap the whole cycle together.

I dont know if this is a good practice or not.

Thanks for your advice

**Comment by dooboolab** [comment]
@pongponglau Try calling `initConnection` in `componentDidMount` then you won't call this in every lifecycle. Also, you can ignore the warning message and just go on. It just means you tried to start already running service, and it is prevented from `react-native-iap` code internally.

**Comment by EnginYilmaz** [comment]
Hello, for some reasons I have two different purchase screens one from chat screen for an offered service and one from the agenda page for a psychotherapy meeting that counsellor picks for own. If I init connection and register the listener from for example chat screen than the registered callback function triggers on agenda screen which made my backend API server call impossible to run( In this case first registered callback function runs).  On componentWillUnmount I run RNIap.endConnection(); but end connection function doesn't terminate the Listener properly.

**Comment by andresesfm** [comment]
I don't think the `endConnection` method makes any attempt to clean the listeners. You should create your own clean up code. See code examples
