### ISSUE TITLE
Example of Checking Existing Subscriptions

### ISSUE THREAD

**Issue by rapind** [dooboolab/react-native-iap#271]
Would love it if there was an example of checking to see if a user already has a valid subscription and then showing the option to purchase if they don't.

It's unclear to me if `getAvailablePurchases` will only include subscriptions that have been purchased and are still valid. E.g. a monthly or yearly subscription that hasn't been cancelled. Do we need to do date checking ourselves or will the subscription simply not be included in the `getAvailablePurchases` call if the user has cancelled and it has expired?

**Comment by JJMoon** [comment]
I guess this document has all answers.

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGui
de/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW8

There are expiration date and cancellation info in the receipt.

**Comment by rapind** [comment]
@JJMoon  Apple's example there is a little more complicated (and contrived) than I was expecting. The idea that content may stay locked during a lapse in their subscription seems like a more advanced edge case. While I'm sure it happen, most subscription I suspect will be simple unlock flags (everything is available), or tiered subscription flags (bronze, silver, gold). That would probably suffice as a useful example. Never mind determining lapsed periods to only unlock certain content .

I wonder how many publishers even do this lapsed period locking... Most would just grant access to their back catalogue without any lapsed period locking I think.

**Comment by dooboolab** [comment]
Closing this for dupe #275
