### ISSUE TITLE
Could not initConnection on version 2.2.2 

### ISSUE THREAD

**Issue by marcosmartinez7** [dooboolab/react-native-iap#273]
### Version of react-native-iap

2.2.2 (latest)
React native 57.0

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Could init connection

### Actual behavior

Init connection returns null

### Tested environment (Emulator? Real Device?)

Differents real devices

### Steps to reproduce the behavior

1. I have created a alpha testing app in the playstore with the package com.mycompany.myapp
2. I have created and activated products and subscriptions
3. The app is on "Published" state on the playstore
4. The merchant account is active

4. I have integrated the library, added and linked it. 
5. I have tried this:

```
import * as RNIap from 'react-native-iap';

 try {
            let cnn = await RNIap.initConnection();
            if(cnn){
                console.warn(cnn)
            }else{
                console.warn("Nope")
            }
            let products = await RNIap.getProducts(itemSkus);
                console.warn(products )

        } catch(err) {
            console.warn(err);
       }
 }


```

**cnn = null 
and 
getProducts = empty array**

The app.build.gradle has: 

`    compile project(':react-native-iap')`

The settings.gradle has:

```
include ':react-native-iap'
project(':react-native-iap').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-iap/android')

```
The Manifest has this permissions:

```
 <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.android.vending.BILLING" />
```
Im running the app using react-native run-android

Any ideas of how can i troubleshoot this? 

Also, how is this library working? the initConnection method checks if there is any app in the playstore with the app id = com.mycompany.myapp ?

Thanks

**Comment by dooboolab** [comment]
@marcosmartinez7 Try all the steps in #256. Lots of similar problems solved with issue here.

**Comment by marcosmartinez7** [comment]
Thats an ios issue with the purchase, i cant even get the connection.. any ideas?

**Comment by fmassey** [comment]
Same

**Comment by marcosmartinez7** [comment]
Tried using RN 55.3 and still the same issue

**Comment by dooboolab** [comment]
Try to unlink and link again. The `linking` script isn't perfect or try the manual installation.

**Comment by marcosmartinez7** [comment]
Ok, i will try, but is the 2.2.2 version tested with RN 57 ?

Thanks

**Comment by marcosmartinez7** [comment]
Same problem linking mannually. Connection is null.

Do you guys know wich are the possible causes that will result in a null connection?

**Comment by marcosmartinez7** [comment]
The code of initConnection is resolving a promise returning null, maybe thats the problem? 

see the method on https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java

**Comment by marcosmartinez7** [comment]
The thing is that the documentation saids that initConnection retunrs a promise of type void, but it returns null, and that is confusing a lot

I was thinking that was wrong and in fact seems to be ok, i can invoque .getSubscriptions and obtain them even when the initConnection returns null..

So.. my advice, change the documentation or the initConnection to return true and make it boolean

**Comment by fmassey** [comment]
Ok I don't received any products from .getProducts. @marcosmartinez7 
1- Did your apk is in production or beta/alpha? 
2- Did your itemSku is formatted like "com.myPackage.myItems"? 
3- Are you able to get subscription on emulator?

**Comment by marcosmartinez7** [comment]
3. No! It doesnt work in emulators, use a real device. 
2. Nop, just use the id that you assigned on the playstore. If the product id is "pepito", use "pepito".
1. Is on alpha. I **THINK** that you need to first generate a signed apk and add it to the alpha testing first.
