### ISSUE TITLE
Error RNIapModule.buyItemByType got 5 arguments, expected 6

### ISSUE THREAD

**Issue by tab** [dooboolab/react-native-iap#281]
I have an exception with latest version react-native-iap.

### Version of react-native-iap

2.3.0

package.json:
```
{
  ...
  },
  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.56",
    "react-native-iap": "^2.3.0",
    ...
  },
...
}
```

### Platforms you faced the error (IOS or Android or both?)

Only Android.
Version 4.4.4

### Actual behavior

Error `RNIapModule.buyItemByType got 5 arguments, expected 6`

### Tested environment (Emulator? Real Device?)

Device

### Steps to reproduce the behavior

On iOS everything work as usual, but on Android I have exception "RNIapModule.buyItemByType got 5 arguments, expected 6"

My purchase function:
```
_purchase = async(sku) => {
    RNIap.buyProduct(sku).then(purchase => {
       // send payment confirmation to backend API
     }).catch(error => {
       // send payment rejection to backend API 
     });
}
```

Thanks for your help or advice how to fix the problem.

**Comment by dooboolab** [comment]
Resolved in #280 .
