### ISSUE TITLE
RNIap.getProducts doesn't get updated products details on Android

### ISSUE THREAD

**Issue by raynor85** [dooboolab/react-native-iap#284]
### Version of react-native-iap
2.3.6
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
If I update a manageable product (ie changing title, description, and / or price), I should get the updated product when I call `RNIap.getProducts(productSkuList)`, and when I try to buy it, I should get a contextual menu with the updated fields

### Actual behavior
`RNIap.getProducts(productSkuList)` always give me back the old product, BUT when I try to buy it, I see the updated product in the contextual menu

![bug android](https://user-images.githubusercontent.com/5817333/46841848-2bfab400-cdc2-11e8-800b-0a3437559166.png)

### Tested environment (Emulator? Real Device?)
Real device, Samsung Galaxy S7

### Steps to reproduce the behavior
As described in "Expected behavior"

**Comment by dooboolab** [comment]
Related to #194 which is totally uncontrollable.

**Comment by raynor85** [comment]
No it is not related, I am talking about another problem here. The same issue raises if you change the price or the description, and it is not related to the fact that the title on android comes with the bundle ID. For that I just stripped it out from the client. This issue is way more serious.

**Comment by dooboolab** [comment]
@raynor85 I think `playstore` may take sometime updating product info. I think it is related in a notion that it is not manageable unless `Android` sdk provides some implementation that guarantee the updates.

**Comment by andruli** [comment]
Hey @raynor85 the same thing happened to me today. I changed the price of some subscriptions and the change didn’t reflected on Android, although if you pressed to purchase it, it was showing the up to date price. I didn’t want my users to view an outdated price so rolled back the change. But I’m interested, did it eventually show the right price for you ?

**Comment by andruli** [comment]
For anyone is reading this in the future it was a caching issue, it took around 2 hours to reflect the changes made to the iap item on the app.

**Comment by raynor85** [comment]
What I do to force the change is deleting the app and creating a new one,
and if it is not enough, I disable and re enable google service from the
phone settings.

**Comment by oleksiy-nesterov** [comment]
The same situation for me... Maybe somebody knows some trick to force a product's data update?

**Comment by didac-wh** [comment]
Changing the parameters seems to refresh the caché.

`productSkuList.push("any-random-string");
RNIap.getProducts(productSkuList)
...
`

Also take into account that Google Play takes some minutes to refresh details.
