### ISSUE TITLE
.getAvailablePurchases() not returning available products while in development.

### ISSUE THREAD

**Issue by mattsidjohn** [dooboolab/react-native-iap#286]
### Version of react-native-iap
Latest

### Platforms you faced the error (IOS or Android or both?)
No error just no result.

### Expected behavior

I have created 2 products in the ios features as non-consumable products and are Ready to Submit.

I can successfully "getProducts", and have successfully purchased 1 of them. If i try to purchase it again it tells me it has already been purchased. Now I need the getAvailablePurchases to iterate over the array to allow access to already purchased items. However my getAvailablePurchases() is resulting in an empty array when I should have 1 product available for purchase.

My question is does the getAvailablePurchases stay empty until its actually live? Or is this unexpected behavior.

### Tested environment (Emulator? Real Device?)
Real device after exp publish ran and build scheme set to release. And loaded onto actual device iPhone Xs Max

**Comment by mattsidjohn** [comment]
Both of the products are "non-consumable" I have successfully tested purchasing and it works great ( as expected) Where I'm having issues is that since i have purchased 1 of the 2 products when I call getAvailableProducts() nothing is being returned. I would expect based on the documentation I should get 1 result in the array, and it should be the product I have not purchased. I also tested just calling available products with a sandbox test account that has not made any purchases and my result array for getAvailableProducts() is still empty. I hope this helps!

**Comment by JJMoon** [comment]
Did you include 2 item ids when you call getAvailablePurchases ? I updated related functions, but this can hardly happen.

**Comment by dbhowell** [comment]
This may/may not be related, but I'm getting an error on `getAvailableProducts()` of:
```
{ [Error: No value for originalJson]
	framesToPop: 1,
	code: 'E_BILLING_RESPONSE_JSON_PARSE_ERROR',
	line: 20294,
	column: 31,
	sourceURL: 'http://localhost:8081/index.delta?platform=android&dev=true&minify=false'
}
```
This is after a subscription has been purchased and you attempt to `getAvailablePurchases()`

**Comment by mattsidjohn** [comment]
No I did not include the item ids - didn’t know it the function took parameters. I’ll try tomorrow first thing.

**Comment by mattsidjohn** [comment]
Looks like it doesn’t accept any parameters like I thought....

**Comment by JJMoon** [comment]
I mean this ids.. You have to include these items like this. I guess you did this.

https://github.com/dooboolab/react-native-iap/blob/8cb75740a3b4c4f5bd7153ed3a1faf6f44e2ec20/RNIapExample/src/components/pages/First.js#L18

**Comment by mattsidjohn** [comment]
If you read my first and second clarification of my issue it’s the
getAvailableProducts() function that it is not giving me a response. Will
this function work in sandbox mode?

**Comment by mattsidjohn** [comment]
Yes my purchasing and product receiving works fine. It’s the getAvailableProducts() that is not returning a result. Is that expected behavior while in development?

**Comment by JJMoon** [comment]
Yes. The method should return one item you already purchased with that account.
But, the Apple IAP server frequently malfunctions, I cannot tell a certain answer.
The method was tested in sandbox circumstances. I hope you make a new sandbox account and test again.

**Comment by mattsidjohn** [comment]
So is it impossible to fully test this until its live on the app store? I'm at a loss...

**Comment by mattsidjohn** [comment]
Figured it out, I wasn't calling the "finishTransaction()" so i was stuck in a loop on my sandbox test account "Purchase was successful" but didn't not fully process on Apple's side they called it a dead loop. This can be closed.
