### ISSUE TITLE
Why use custom error messages?

### ISSUE THREAD

**Issue by mars-lan** [dooboolab/react-native-iap#290]
What's the rationale for manually mapping error codes to custom descriptions here: 
https://github.com/dooboolab/react-native-iap/blob/98e9d230be99ce87f368e0446ed108656b0588b8/ios/RNIapIos.m#L311

Wouldn't it better to simply use whatever returned by https://developer.apple.com/documentation/foundation/nserror/1414418-localizeddescription?language=objc  ? This also has the benefit of localizing the error messages.

**Comment by dooboolab** [comment]
Yeah maybe you can give a `PR` for this one.
