### ISSUE TITLE
Check subscription is still active or not? (Both iOS and Android)

### ISSUE THREAD

**Issue by Buwaneka1993** [dooboolab/react-native-iap#292]
### Version of react-native-iap
2.3.10
### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
Simply check whether subscription is active or not (I'm using auto renewal option)
Can I use `getAvailablePurchases()` method for check whether user still subscribe or not?

* In my App , subscription cancel by user by their own or if there is some issue in their card(Payment is not success).

I have check it in by this way(Refer following code), And Its given the expected result in android Test Account, (but not tested in iOS yet) . Is this a correct way to check subscription is active or not?

```
getPurchases = async () => {
    try {
      const purchases = await RNIap.getAvailablePurchases();
      let active = false;
      purchases.forEach(purchase => {
        if (purchase.productId == 'MY_PRODUCT_ID') {
          active = true;
        }
      })

      if (active == false) {
        await this.buySubscribeItem("MY_PRODUCT_ID");
      } else {
        Alert.alert(`You are SUBSCRIBED!`);
      }
    } catch (err) {
      console.warn(err); // standardized err.code and err.message available
      Alert.alert(err.message);
    }
  }
```

**Comment by dooboolab** [comment]
`getAvailablePurchases` is to restore the `non-consumable purchase`. If you want to handle that you should check the `receipt` as explained in official Apple document.

**Comment by theoryweary** [comment]
I'm also not sure how to check if my subscription is valid on Android.   Using GetPurchaseHistory only returns the manual purchase that started the subscription, but I don't know what method to use to return the new subscription that was automatically purchased by the Play Store when the subscription renews.  Without the new subscription purchase, I don't have any receipt to validate. 

Please help - how can I check that the subscription has been renewed by the Play Store?

**Comment by CarterBland** [comment]
@theoryweary Is there a way to check cross devices? IOS would work because it's off the receipt ID, but seems like Android's tied to the device?

**Comment by dorin2006** [comment]
Hello Colleagues!

Please help me :) 

RNIap.getAvailablePurchases() returns array with values on Android,
while in google play -> subscribtions, there is no entry.

I'm testing with test account.

Did anyone face the same issue ?

p.s. react-native-iap is a great library guys, thank you for a great job!!!
