### ISSUE TITLE
Exactly identify already subscribed to specific item or not

### ISSUE THREAD

**Issue by Buwaneka1993** [dooboolab/react-native-iap#293]
### Version of react-native-iap
2.3.10
### Platforms you faced the error (IOS or Android or both?)
Both
### Verify is this the correct way to do it
Simply check whether subscription is active or not (I`m using auto renewal option)
Can I use `getAvailablePurchases()` method for check whether user still subscribe or not?

* In my App , subscription cancel by user by their own or if there is some issue in their card(Payment is not success).

I have check it in by this way(Refer following code), And Its given the expected result in android Test Account, (but not tested in iOS yet) . Is this a correct way to check subscription is active or not?

```
getPurchases = async () => {
    try {
      const purchases = await RNIap.getAvailablePurchases();
      let active = false;
      purchases.forEach(purchase => {
        if (purchase.productId == 'MY_PRODUCT_ID') {
          active = true;
        }
      })

      if (active == false) {
        await this.buySubscribeItem("MY_PRODUCT_ID");
      } else {
        Alert.alert(`You are SUBCRIBED!`);
      }
    } catch (err) {
      console.warn(err); // standardized err.code and err.message available
      Alert.alert(err.message);
    }
  }
```

**Comment by JJMoon** [comment]
@Buwaneka1993 I hope you to refer to the example project.  I hope you to take a time and study, code, test enough. Use === instead of ==.

**Comment by dooboolab** [comment]
@Buwaneka1993 Please refer to #300. I will close this as a dupe.
