### ISSUE TITLE
How to get client info? (subscriber info such as email,name etc.)

### ISSUE THREAD

**Issue by Buwaneka-Sumanasekara** [dooboolab/react-native-iap#294]
### Version of react-native-iap
2.3.10
### Platforms you faced the error (IOS or Android or both?)
both

**Comment by dooboolab** [comment]
I wasn't aware that we can get that from the purchase. Do you have any information that does this?

**Comment by Buwaneka1993** [comment]
For Google pay we can do this it in this way(According to the Android developer site)
https://developer.android.com/google/play/billing/billing_library_overview#java

- From you app, send the **purchase token** and **user account credential** to your secure backend server. The secure backend server should associate the purchase with the user after verification has succeeded.
- After you get the token from the app:
Use the Subscriptions and In-App Purchases portion of the Google Play Developer API to perform a GET request to retrieve the purchase details from Google Play (Purchases.products for a one-time product purchase or Purchases.subscriptions for a subscription). **The GET request includes the app package name, product ID, and a token (purchase token).**
Ex: `GET https://www.googleapis.com/androidpublisher/v3/applications/packageName/purchases/subscriptions/subscriptionId/tokens/token`

Google Play returns the purchase details.

The secure backend server verifies that the order ID is a unique value that doesn’t represent a previous purchase.

The secure backend server uses the user account credential received in step 1 to associate the purchase token with the user of the app instance where the purchase was made.

(optional) If you are validating a subscription and the subscription is being upgraded, downgraded, or the user has re-subscribed before the subscription has lapsed, check the linkedPurchaseToken field. The linkedPurchaseToken field in a Purchases.subscriptions resource contains the token of the previous, or “originating” purchase. For more about linkedPurchaseToken, refer to Purchases.subscriptions).
The in-app product is made available to the user.

```
{
  "kind": "androidpublisher#subscriptionPurchase",
  "startTimeMillis": long,
  "expiryTimeMillis": long,
  "autoRenewing": boolean,
  "priceCurrencyCode": string,
  "priceAmountMicros": long,
  "countryCode": string,
  "developerPayload": string,
  "paymentState": integer,
  "cancelReason": integer,
  "userCancellationTimeMillis": long,
  "cancelSurveyResult": {
    "cancelSurveyReason": integer,
    "userInputCancelReason": string
  },
  "orderId": string,
  "linkedPurchaseToken": string,
  "purchaseType": integer,
  "profileName": string,
  "emailAddress": string,
  "givenName": string,
  "familyName": string,
  "profileId": string
}
```

API : https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get
Response : https://developers.google.com/android-publisher/api-ref/purchases/subscriptions#resource

**Comment by dooboolab** [comment]
@Buwaneka1993 Could you also find us information on `ios` also? We need to think this as a new feature after some consideration.

**Comment by ZeroCool00** [comment]
Hello... any news on this great feature?

**Comment by nushydude** [comment]
Docs say that the Google Profile information is only available for purchases made with 'Subscribe with Google'. Don't really understand what they are.
https://newsinitiative.withgoogle.com/subscriptions

**Comment by meInteractive** [comment]
For iOS you need to use the property **applicationUsername**  in the object **SKPayment**, when you sending request from application. This is the right and recommended way how to link payment with user account in your database.

**Read more:**
https://developer.apple.com/documentation/storekit/skpayment
https://developer.apple.com/documentation/storekit/skpayment/1506116-applicationusername

**Code example:**
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/RequestPayment.html#//apple_ref/doc/uid/TP40008267-CH4-SW2


This feature is highly requested, because linking payment to user is a big pain.

**Comment by lossen** [comment]
Any updates here?
