### ISSUE TITLE
Linking in android studio requires RNIapExample?

### ISSUE THREAD

**Issue by jarvisluong** [dooboolab/react-native-iap#297]
### Actual behavior
Doing gradle syncing and I got this error: The specified project directory '<Project path>/node_modules/react-native-iap/RNIapExample/android' does not exist.

I did all the manual project link

**Comment by dooboolab** [comment]
I think you can remove some kind of dependency like that. The example doesn't exist in npm. I don't quite get how you achieve that. You could be more detail from me to reach your problem.

**Comment by jarvisluong** [comment]
Is changing from “compile” to “implementation” the cause of this? That was the only change I made when linking the module.

**Comment by dooboolab** [comment]
@jarvisluong No that isn't a problem. Can you delete `react-native-iap.iml` file in side our module and try that?

**Comment by jarvisluong** [comment]
@dooboolab yes it solved the problem, but I need to delete both ```react-native-iap.iml``` and ```android.iml``` inside the module too
