### ISSUE TITLE
README API Reference doesn't match implementation

### ISSUE THREAD

**Issue by pehagg** [dooboolab/react-native-iap#298]
### Version of react-native-iap

2.3.12

### Platforms you faced the error (IOS or Android or both?)

both

### Expected behavior

README and code docs should match. Affects at least `initConnection`, haven't checked the rest of the functions, but it'd be appreciated if the API Reference in README would match the code. Now I don't know which one to trust and need to start skimming through the implementation, which I don't have time for.

### Actual behavior

For example, `initConnection` in README is documented as returning the result of `canMakePurchase` on iOS, but with a return value of `Promise<void>`. With VSCode's code completion it says it returns `Promise<string>` and is a no-op on iOS. 

### Tested environment (Emulator? Real Device?)

N/A

### Steps to reproduce the behavior

See Actual behavior.

**Comment by dooboolab** [comment]
@pehagg Sorry that we couldn't fully manage the outdated docs. I'll fix this with your help for creating issue. If you read the [ChangeLogs](https://github.com/dooboolab/react-native-iap/blob/master/CHANGELOG.md), you can see I've been supporting `canMakePayment` from `1.2.4`. It had no-ops in ios before.
