### ISSUE TITLE
iOS in-app purchase failure when no payment method added

### ISSUE THREAD

**Issue by anandwahed** [dooboolab/react-native-iap#299]
### Version of react-native-iap

`react-native-iap": "^2.2.2`

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

- User selects the in-app purchase but no payment methods have been added in the Apple account
- User is taken to the Apple account settings page to add payment method
- User adds the card details and selects `Done`
- User's card is charged for the in-app purchase amount and default iOS modal shows up with transaction successful
- User should be taken to the mobile application and valid transaction receipt should be generated

### Actual behavior

- User selects the in-app purchase but no payment methods have been added in the Apple account
- User is taken to the Apple account settings page to add payment method
- User adds the card details and selects `Done`
- User's card is charged for the in-app purchase amount and default iOS modal shows up with transaction successful
- Transaction receipt for the in-app purchase is not received

### Tested environment (Emulator? Real Device?)

Real Device - iPhone 6s

### Steps to reproduce the behavior

- Check to ensure the Apple account in the device the payments method is set to `none` or some invalid payment details
- Make the in-app purchase through the app
- User is taken to the Account settings page to add a valid payment method
- Payment method is charged but the transaction receipt is not received in the below mentioned code

```
await RNIap.clearTransaction();

RNIap.buyProductWithoutFinishTransaction(sku)
  .then(purchase => {
    // not reached
    if(calltoserverisSuccess){
      RNIap.finishTransaction();
    }
  })
  .catch(error => {
    // code enters catch case if ever
  }
```

**Comment by dooboolab** [comment]
@anandwahed Hi. Thank you for the issue. Feels like #279 is related to this one which is recently resolved. Could you try `2.3.14` and come back?

**Comment by anandwahed** [comment]
@dooboolab Since you have edited the comment after closing the ticket we didn't get notification about the change. We used the version `2.3.14` as per the last comment and still have the issue. Now we are trying to use the latest version `2.3.17`
