### ISSUE TITLE
getAvailablePurchases RETURN array empty [] despite I have completed successfully purchase both IOS and Android platform 

### ISSUE THREAD

**Issue by longleTDT** [dooboolab/react-native-iap#300]
### Version of react-native-iap
"react-native-iap": "^2.3.12",

### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
array not empty
### Actual behavior
[]
### Tested environment (Emulator? Real Device?)
Iphone 6s and Samsung galaxy S6
### Steps to reproduce the behavior
I have purchased completed one subscription on android and one non-renewable subscription on ios , then I use method getAvailablePurchases() to get information purchase but they return a array empty.

_getAvailablePurchases = async () => {
    try {
      const purchases = await RNIap.getAvailablePurchases();
      console.info('Available purchases :: ', purchases);
    } catch (err) {
      console.log(err)
    }

I am using account sandbox on IOS and Android

**Comment by dooboolab** [comment]
One of most question asked in issue. I think I should write this up in `Q&A` soon. I'll help you understand the process of in-app purchase better if you read the official docs provided in each platform (android & ios).

`getAvailablePurcahses` is used only when you purchase a non-consumable product. This can be restored only. If you want to find out if a user subscribes the product, you should check the receipt which you should store in your own database. Apple suggests you handle this in your own backend to do things like what you are trying to achieve.

I'll close this issue soon.
