### ISSUE TITLE
IAP not prepared.Was prepare method called successfully?

### ISSUE THREAD

**Issue by antbaobao** [dooboolab/react-native-iap#301]
### Version of react-native-iap
2.0.3
### Platforms you faced the error (IOS or Android or both?)
Android
### Tested environment (Emulator? Real Device?)
Real Device

**Comment by dooboolab** [comment]
@antbaobao Please use `initConnection` instaed since that was deprecated in `2.0`. Also try our recent version and come back. I will close this.
