### ISSUE TITLE
Android - await RNIap.buySubscription is returning undefined

### ISSUE THREAD

**Issue by evaleirasclapps** [dooboolab/react-native-iap#302]
### Version of react-native-iap
**2.3.15**

### Platforms you faced the error (IOS or Android or both?)
**Android**

### Expected behavior
Get purchase when subscription was completed successfully.
### Actual behavior
The promise resolves immediately (without the purchase is complete)

### Tested environment (Emulator? Real Device?)
Emulator

**Comment by evaleirasclapps** [comment]
Resolved on PR #303

**Comment by dooboolab** [comment]
Could you try `2.3.16` ?

**Comment by evaleirasclapps** [comment]
Was fixed?

**Comment by evaleirasclapps** [comment]
Works

**Comment by dooboolab** [comment]
Thanks. I'll close this.

**Comment by mehdichk** [comment]
Hi guys, it doesn't work for me ("purchase is undefined)
But only when I use the "upgrade/downgrade" format (ie "buySubscription(product, old_product)")
Otherwise, it works perfectly.
Any idea ?
