### ISSUE TITLE
Invalid product Id on iOS

### ISSUE THREAD

**Issue by BakytzhanAkzhol** [dooboolab/react-native-iap#304]
**Version of react-native-iap**
2.3.17

**Main Library**
expo: "30.0.0"
react: "16.3.1"
react-native: 30.0.0 from expo server

**Platforms you faced the error (IOS or Android or both?)**
iOS

**Expected behavior**
Returning list of subscription
Buy subscription

**Actual behavior**
Our app is already approved and ready for sale on App Store and all products is "Ready for Submit" but still when i call RNIap.getSubscriptions it returns empty [] and I call buySubscription(ProductId) it returns "Product Id Invalid"

**Tested environment (Emulator? Real Device?)**
Emulator and real device

**Steps to reproduce the behavior**
I make all steps in the tutorial.
Make sandbox user in Role & Users and connect to real device.
Make two items form subscription.
RNIap.initConnection always return true.

**Question:**
Q1: I need some backend for working with RNIap? 
Q2: Can i get  list of subscription in emulator or real device without publish to Testflight?

My code:

```
const itemSubs = Platform.select({
  ios:[
   'neupusti.1month',
    'neupusti.subs.6month'
  ],
  android: [],
});
...
  async componentDidMount() {
    try {
      const result = await RNIap.initConnection();
      console.log('result', result);

       Alert.alert("RNIAP is connected: "+result);
    } catch (err) {
      console.warn(err.code, err.message);
    }
  }
...
 getSubscriptions = async() => {
    try {
      const products = await RNIap.getSubscriptions(itemSubs);
      console.log('Products', products);
      this.setState({ productList: products });
    } catch (err) {
      console.warn(err.code, err.message);
    }
  }
...
buyItem = async(sku) => {
    try {
      console.info('buyItem: ' + sku);
      // const purchase = await RNIap.buyProduct(sku);
      const products = await RNIap.buySubscription(sku);
      // const purchase = await RNIap.buyProductWithoutFinishTransaction(sku);
      console.info(products);
       Alert.alert(JSON.stringify(products));

      this.setState({ receipt: purchase.transactionReceipt }, () => this.goToNext());
    } catch (err) {
      console.log(err);
      console.warn(err.code, err.message);
      Alert.alert(err.message);
    }
  }
```

p.s. I spent 3+ days searching for a solution and nothing helped me.

**Comment by dooboolab** [comment]
Q1: no
Q2: Have you gone through medium I've posted? It says you don't need to upload the app the testflight for testing this feature. You just need to do the step in the medium.
![image](https://user-images.githubusercontent.com/27461460/47666218-5502ad80-dbe6-11e8-8468-66d5675ad154.png)

Make sure your product is in `Ready To Submit` status.

**Comment by BakytzhanAkzhol** [comment]
Hi, I read your article and made this step.But, I still can't get list subscriptions.
Right now, I have one item for subscription in purchase.

**Comment by dooboolab** [comment]
I can't read your language so are you sure it is in `Ready to Submit` state?

**Comment by dooboolab** [comment]
Also please refer to #256 who've explained the config step in detail.

**Comment by BakytzhanAkzhol** [comment]
> I can't read your language so are you sure it is in `Ready to Submit` state?

Yes, It says **Ready to Submit**. I forgot to translate for you. Sorry.

**Comment by dooboolab** [comment]
Please refer to #256 and try again

**Comment by hyperh** [comment]
Hmm having similar issues with invalid productId

**Comment by dooboolab** [comment]
Did you go over above issue I’ve mentioned?

**Comment by hyperh** [comment]
@dooboolab Thanks for the link. Followed it and it worked.

**Comment by JJMoon** [comment]
Nice to hear the issue was resolved. I'm closing this issue.

**Comment by BakytzhanAkzhol** [comment]
Problem solved.. My mistake was incorrectly filled out a tax form on the site of Apple.com. Thank you)
