### ISSUE TITLE
iOS: Error while trying to call buySubcription function: 'restoreCompletedTransactionsFailedWithError' 

### ISSUE THREAD

**Issue by Buwaneka1993** [dooboolab/react-native-iap#305]
### Version of react-native-iap
2.3.10
### Platforms you faced the error (IOS or Android or both?)
IOS
While tring to call buySubcription function i`m getting error 'restoreCompletedTransactionsFailedWithError ' . and not showing any screen. I used sandbox testing account for this

### Tested environment (Emulator? Real Device?)
Tested in Both

**Comment by Buwaneka1993** [comment]
I have updated this package version to 2.3.17 and specified the error: its 'Cannot connect to iTunes Store' I have just tested it in Emulator. any idea for resolve it?

**Comment by dooboolab** [comment]
For connection issue you should check your ios setup like the bundle id.

**Comment by Buwaneka1993** [comment]
I have checked the bundle id , there is no difference

**Comment by JJMoon** [comment]
@Buwaneka1993 I hope you test with the example of this module.

**Comment by JJMoon** [comment]
I hope this issue is resolved. Closing..
