### ISSUE TITLE
BuySubscription not works in IOS

### ISSUE THREAD

**Issue by wesleymonaro** [dooboolab/react-native-iap#306]
### Version of react-native-iap
2.3.13
"react": "16.2.0",
"react-native": "0.53.0",

### Platforms you faced the error (IOS or Android or both?)
IOS only

### Expected behavior
Call a window to confirm the subscription

### Actual behavior
Not firing any windows or message

### Tested environment (Emulator? Real Device?)
Both, iOS 11.4

### Steps to reproduce the behavior
Hi!
I need to call a buySubscription method, but only in IOS not firing any message or error. I tried to change the react-native-iap version, since 1.4.0, but have the same

![image](https://user-images.githubusercontent.com/10585736/47728992-29131680-dc3e-11e8-8c8c-55497a883be3.png)

Is the first product in this app. Android works fine.

**Comment by wesleymonaro** [comment]
Information, I included a catch, to see any error message, but nothing happens :/

**Comment by dooboolab** [comment]
@wesleymonaro Please try `2.3.17` and comeback.

**Comment by wesleymonaro** [comment]
@dooboolab Nothing :/
react-native-iap reinstaled, with link comand line, and i tried manually too. Same problem. Nothing is fired

**Comment by wesleymonaro** [comment]
Question: Even though Apple has not yet approved the new version of the app with IAP, something should come up, right?

**Comment by dooboolab** [comment]
@JJMoon can you test this out for him?

**Comment by JJMoon** [comment]
Did you make sandbox tester and test with that account in real device ?

**Comment by wesleymonaro** [comment]
@JJMoon Yes. I created a sandbox account, and the test was maked in a real device

**Comment by alorr10** [comment]
Having this same problem too. Version 2.3.17. I call buyProduct(itemSKU) and no prompt comes up, the promise never gets resolved.

**Comment by JJMoon** [comment]
@wesleymonaro Did you try buyProduct or buySubscription? I hope you test at least twice. In sandbox mode, the first try doesn't work most of time.
@alorr10 If you tried buyProduct, this is another issue. I ask you to try with new sandbox tester and in real device.

**Comment by wesleymonaro** [comment]
@JJMoon Both methods. The same problem

**Comment by JJMoon** [comment]
@wesleymonaro Would you test with the example of this module? It's tested.
Just change product names, bundle id, you are ready to test.

**Comment by voidstarfire** [comment]
Also Facing the same problem. IAP not working with ```RNIap.buySubscription('sub')```

I can see the subscriptions with ```RNIap.getSubscriptions(itemSkus)```

I get an unknown error which is very unhelpful
```
Error buying subscription Error: Cannot connect to iTunes Store
    at createErrorFromErrorData (dd63c188-0127-4d7b-bb0d-25aec5491f8a:2435)
    at dd63c188-0127-4d7b-bb0d-25aec5491f8a:2387
    at MessageQueue.__invokeCallback (dd63c188-0127-4d7b-bb0d-25aec5491f8a:2827)
    at dd63c188-0127-4d7b-bb0d-25aec5491f8a:2574
    at MessageQueue.__guard (dd63c188-0127-4d7b-bb0d-25aec5491f8a:2731)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (dd63c188-0127-4d7b-bb0d-25aec5491f8a:2573)
    at t (RNDebuggerWorker.js:1)
```

Completely stuck for now.

**Comment by dooboolab** [comment]
`getSubscriptions` should be called first before actually `buySubscription` in `ios`. Also make sure you've done this.

**Comment by JulianKingman** [comment]
I'm getting this error when trying to change a subscription (`buySubscription` a second time with a different ID).

**Comment by hyochan** [comment]
@JulianKingman This wasn't in my test case so it is hard for me to test out. Could you provide some example that I may look closer?

**Comment by JJMoon** [comment]
I tested yesterday, RNIap.buyProductWithoutFinishTransaction works. Can you share the source code?

**Comment by edo1493** [comment]
I see this when trying to switch plans. For example I buy a subscription via buyProductWithoutFinishTransaction and then try to buy a different plan. I get the error on the second try.

**Comment by JulianKingman** [comment]
@hyochan I don't think there's a solution for this. As an example if you have 2 subscriptions in the same subscription group with different prices, purchase one, then upgrade to the other, then you get the error.

**Comment by hyochan** [comment]
@JulianKingman Since your issue has different personality compared to the previous one, I hope you to open a new issue. Also, since we are working on some other solutions, I hope you can try `PRing` too. Thanks.

**Comment by hyochan** [comment]
@JulianKingman Your issue may be followed up in #274.
