### ISSUE TITLE
iOS in-app purchase failure when payment method added live when there is not payment method already present

### ISSUE THREAD

**Issue by anandwahed** [dooboolab/react-native-iap#307]
### Version of react-native-iap

`react-native-iap": "^2.3.17`

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Payment should go through only when `finishTransaction` is being called

### Actual behavior

The amount is being detected after a payment method like credit card is added.
But the `RNIap.buyProductWithoutFinishTransaction(sku)` method reached.

### Tested environment (Emulator? Real Device?)

Real Device - iPhone 6s

### Steps to reproduce the behavior

- Check to ensure the Apple account in the device the payments method is set to none or some invalid payment details
- Make the in-app purchase through the app
- User is taken to the Account settings page to add a valid payment method
- Payment method is charged but the transaction receipt is not received in the below mentioned code

```
ComponentDidMount(){
     await RNIap.initConnection();
     await RNIap.consumeAllItems();
     const prod = await RNIap.getProducts(product);

} 

  async componentWillUnmount() {
       RNIap.endConnection()
}

buyProduct(sku){
await RNIap.clearTransaction();

RNIap.buyProductWithoutFinishTransaction(sku)
.then(purchase => {
  // not reached
 if(calltoserverisSuccess){
    RNIap.finishTransaction();
 }
})
.catch(error => {
 // code enters catch case if ever
}}
```

**Comment by dooboolab** [comment]
Sorry to say this but your code seem to have many syntax error. Please refer to our example project in our repo and compare with your code first.

**Comment by zohaibahmed-22** [comment]
@dooboolab 
Thanks for the reply, the code that is posted over here is just for an example, this is not the exact that is being used in the real application.
i will try to explain what is the issue
1.  componentDidMount 
     - connection in initiated by calling `RNIap.initConnection();`
     - then products are fetched and store in state by calling `RNIap.getProducts(product)`

2. when user click on purchase button
    -  `RNIap.clearTransaction();` is called just to make sure no pending transactions left.
    -   `RNIap.buyProductWithoutFinishTransaction(sku)` is called in success case a call to application server is triggered if server gives success case true then `RNIap.finishTransaction();` is called to complete the payment.

3. componentWillUnmount()
   -  `RNIap.endConnection()` to end connection.

This process works fine if user have already payment method added. When user don't have a payment method added it takes to adding payment method page and amount is charged before reaching the `RNIap.finishTransaction(); `

**Comment by dooboolab** [comment]
Thanks for the detail. Your issue looks clear  now. @cc JJMoon

**Comment by anandwahed** [comment]
@JJMoon

**Comment by JJMoon** [comment]
@zohaibahmed-22 Is this sandbox test case ?

**Comment by zohaibahmed-22** [comment]
@JJMoon No, its a real environment case.

**Comment by zohaibahmed-22** [comment]
@dooboolab @JJMoon have a look at this one
https://forums.developer.apple.com/thread/6431

**Comment by dooboolab** [comment]
I agree. cc @JJMoon

**Comment by JJMoon** [comment]
@anandwahed I agree on you. It's my fault. Sorry for that. 
I will look over the Apple's thread and take care of the issue.

**Comment by JJMoon** [comment]
@anandwahed I guess it's right way to `finish transaction` when it's failed. Please look up this thread. https://stackoverflow.com/questions/11008636/inapp-purchase-skpaymentqueue-finish-transaction-doesnt-work
When it fails, there will be no receipt, so you don't apply the purchase product. And the finishing transaction doesn't always mean 'purchasing'. 
Meanwhile, I will investigate thread 6431.

**Comment by JJMoon** [comment]
I just read the thread 6431 (https://forums.developer.apple.com/thread/6431#14562) 
The bottom line. Problem not solved since 2015. Wow..
There are two different ways to handle this 'store kit flow' effect.
1. Do not show any user alert.
2. Show the result.

And I learned two things.
A. We have to `finishTransaction` when it failed. (I guess with or without option, always)
B. Storekit flow makes failed and success with receipt both. (it's bad)

I suggest you all to read this thread, and return to this issue.

I guess, which way you choose (1 or 2), it's on your own.
We might need a call back for failure response.

**Comment by maxs15** [comment]
@JJMoon does it mean we shouldn't use buyProductWithoutFinishTransaction ?

**Comment by JJMoon** [comment]
@maxs15 I didn't mean that. Sorry for confusing. 
The StoreKit flow can happen at any purchasing. It's iOS issue, not this module.
For now, I don't have any clue, either. This thing happens in any native iOS apps. Right?
We will dig more in our free time.

**Comment by JJMoon** [comment]
@hyochan If you connect the real server (yours), whether you are in debug mode or release mode doesn't matter. I guess you have 2 options.
1. You run on the real device in debug mode in Xcode. Use JS console log.
2. You run on the real device in release mode in Xcode. Use NSLog in objective-c code.
Both methods should work.

**Comment by hyochan** [comment]
@JJMoon Yeah, I've figured that out already but still that I couldn't make live purchase testing in ios. Is this [stackoverflow](https://stackoverflow.com/questions/6294865/how-to-test-in-app-purchase-without-sandbox) true? Then how can I solve this problem? We have to test the live purchase.

**Comment by hyochan** [comment]
Anyone who is facing this problem, I am sure all of them do, please give us an idea of how to encounter this problem. `in-app purchase fail when payment method added live` as described in issue title. How could I debug this?

**Comment by anandwahed** [comment]
@hyochan No we didn't contact Apple support.

**Comment by hyochan** [comment]
I think we need to contact `apple` for this and this looks really terrible that there is a different test case which is not reproducible in `sandbox` environment (this really makes my heart sick). For those who want to understand the problem, I've recorded the screen and you can see the [clip here](https://firebasestorage.googleapis.com/v0/b/cooni-ebee8.appspot.com/o/Github_iOS_iap_COONI_2018-12-17.mp4?alt=media&token=43ff6f97-d0e5-40c6-8e71-cdc914a8b1fc). @anandwahed Could you also contact apple for this? Because I know they aren't that supportive so it is better for more people to have contact with them. Let's gather up to solve this issue.

**Comment by hyochan** [comment]
Today we received [answer](https://forums.developer.apple.com/thread/112099) from apple. There may be callback returned again after `failure`. We are working on workaround solution but I am afraid this could be very nasty. We are working on workaround solution in #343.

**Comment by hyochan** [comment]
I've released to `2.4.0-beta1`, trying to make a workaround for this problem. The `PR` #348 has been added to this version and you can also see the readme in `PR` talking about `advanced purchase 3`.

**Comment by Edgpaez** [comment]
Guys, thank you for investing time in this problem! 🙏 

I think the current documentation needs to be clearer around the usage of `addAdditionalSuccessPurchaseListenerIOS`. That's something I tried to address at #414.

But I also think this leaves room from improvement to the API. Would you guys be open to discussing a change in the API that can better accommodate the so called 'store kit flow'? Something maybe using RxJS, for example:

```javascript
const observable = RNIap.buyProduct('com.example.coins100')
						.subscribe(
							purchase => console.log(purchase), // successful payment
							err => console.log(err) // err.code and err.message are available
						)
						
```

Or something different that better hides the additional subscription for iOS?

**Comment by hyochan** [comment]
@Edgpaez That's great but that will change the behavior of the purchase being done in `android`. I hope I can investigate `version 3` of this module in `2019`.

**Comment by Edgpaez** [comment]
hi @hyochan, AFAICT, we don't need to change the internal behavior of the package, only the public facing interface. We can keep the [buyItemByType](https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L362) method resolving promises and simply add a bit of Rx on top of that on [index.js](https://github.com/dooboolab/react-native-iap/blob/master/index.js).

for example, we'd have this in index.js:

```javascript
export const buyProduct = (sku) => Platform.select({
  android: () => Observable.of(RNIapModule.buyItemByType(ANDROID_ITEM_TYPE_IAP, sku, null, 0)), // returns an observable that emits when the RNIapModule.buyItemByType promise resolves
  ios: ... // ios would do the same but taking into account the usage of addAdditionalSuccessPurchaseListenerIOS
})();
```

My goal is not this specific implementation but to hide details specific to the 'store kit flow'.
Do you think this is a good idea?
Would you be interested in a PR?

**Comment by hyochan** [comment]
@Edgpaez Ok. I understand the detail now. However, I feel adding `RxJS` is bit too much with implementing the `feature` since I think this can be covered without it.

Also, I feel the below would be something different.
```
RNIap.buyProduct('com.example.coins100')
						.subscribe(
							purchase => console.log(purchase), // successful payment
							err => console.log(err) // err.code and err.message are available
						)
```

If you call `buyProduct` for two items like below,
```
RNIap.buyProduct('com.example.coins100');
RNIap.buyProduct('com.example.coins200');
```
 We can't guarantee which one would finish first so I think we should handle this in native to `sendEvent` out to `JS`.

I feel like implementation should look like
```
RNIap.buyProduct('com.example.coins100');
RNIap.buyProduct('com.example.coins200');

// receiving events
const subs =  RNIap.purchaseUpdateListener(purchase => {
  ...
});
```

Please tell me if there is something I've missed.
