### ISSUE TITLE
After a successful subscription and clicking on OK from the success dialog, I am asked to verify iTunes, how can I prevent this?

### ISSUE THREAD

**Issue by ianataffinity** [dooboolab/react-native-iap#308]
### Version of react-native-iap
2.3.16

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
No dialog

### Actual behavior
Verification dialog after a successful purcahse

### Tested environment (Emulator? Real Device?)
Real Device through Test Flight

### Steps to reproduce the behavior
* Successfully purchase a subscription
* Enter in Apple id to complete purchase 
* Click on OK from success dialog

### Issue

The library works excellent. The subscription to a product ID is successful and I get back a successful transaction and purchase item. 

However, after clicking on OK, another dialog appears immediatly after asking to verify iTunes account. Which isn't needed as everything is done!

Whats this for? And how can I prevent it from happening? Missing a step?

Here is the code for purchasing, bit scrappy as we are still testing:

    try {
        RNIap.buySubscription(this.state.selectedProductId).then((purchase) => {
            let receipt = purchase.transactionReceipt
            RNIap.endConnection()
            this.props.navigation.goBack()
        }).catch(e => {
          error(e)
        })
    } catch (e) {
      error(e)
    }

### Screen shots 

![image](https://user-images.githubusercontent.com/29443467/47973654-adabdc00-e0f9-11e8-89b7-32ac100c3202.png)

![image](https://user-images.githubusercontent.com/29443467/47973677-d16f2200-e0f9-11e8-8429-0c93d8ed9707.png)

**Comment by ianataffinity** [comment]
Oh and just a quick note. I do call `RNIap.getSubscriptions(this.subscriptionIds)` to get a list of subscription product ID's to use. I don't hardcode the ID's

**Comment by alorr10** [comment]
That's just a weird testflight thing. [This blog post](http://davidbarnard.com/post/164337147440/testing-auto-renewable-subscriptions-on-ios) explains testing subscriptions really well

**Comment by ianataffinity** [comment]
@alorr10 thanks for pointing me in the right direction.
