### ISSUE TITLE
RNIap.clearTransaction throwing error

### ISSUE THREAD

**Issue by alorr10** [dooboolab/react-native-iap#309]
### Steps to reproduce the behavior call await RNIap.clearTransaction();

I can tell my app and/or itunes account is in bad shape because calling buyProducts() isnt even showing a pop up anymore, I think because I've purchased too many subscriptions and my account got into a corrupted state. I am trying to call clearTransaction to get my account/app back to a normal state so I can test iap's, but it is throwing this exception and I cannot purchase products at all. 

![img_2084](https://user-images.githubusercontent.com/4950657/47976476-6bd25580-e067-11e8-8215-555eea9219be.png)

**Comment by alorr10** [comment]
Signed out and in of icloud, restarted the phone, and it started working again

**Comment by superandrew213** [comment]
Isn't the purpose of `RNIap.clearTransaction()` to clear the queue?

**Comment by turcottedanny** [comment]
@superandrew213 You can't finish a transaction in purchasing state. 
From Apple:
https://developer.apple.com/documentation/storekit/skpaymentqueue/1506003-finishtransaction?language=objc
> Calling finishTransaction: on a transaction that is in the SKPaymentTransactionStatePurchasing state throws an exception.

But I managed to get out of this situation, by calling `clearTransaction` one time for each of the pending transactions in my account (it raised an error each time)

@alorr10 Are you able to reproduce this state ? I'm trying to understand why I get into this situation ( it happens rarely)

**Comment by edo1493** [comment]
We are seeing this in production too, not sure if this is due the fact the user has to change payment details and then is brought back into the app.

**Comment by ilyakar** [comment]
I don't understand. What's the solution to this?

The doc states:
```
await RNIap.clearTransaction(); // add this method at the start of purchase.
const purchase = await RNIap.buyProduct(...)
```

Not having the .clearTransaction causes "Already bought this product" for consumables, having the .clearTransaction causes the app to crash sometimes.

**Comment by leotm** [comment]
I'm upgrading from v2 to v3-5 (likely 4.5.2+ to resolve the iOS 14 issue) and found this helpful, for what it's worth

https://github.com/dooboolab/react-native-iap/blob/de0fc084966fc4d36a9c45f4e27cb166243d4319/README_DEPRECATED.md

**Comment by codal-mpawar** [comment]
https://github.com/dooboolab/react-native-iap/issues/309#issuecomment-493706077
this is actually currently happening with my project @leotm @ilyakar Can you please me how I can handle it.
IN screen
We have a flat list and flat list have items and items that have a purchase option and that all are consumable. and on item button do below operations.

await RNIap.clearTransactionIOS();
RNIap.requestPurchase(
							this.state.tipProductId,
							false,
							userDetail['cognito:username'],
							userDetail['cognito:username']
						).then(async (purchase) => {
						// api call
						await RNIap.finishTransaction(purchase, true);
			await RNIap.clearTransactionIOS();
						}).catch(() => {
						   await RNIap.clearTransactionIOS();
})

don't know what i missing can any one please help me on this i am getting crash and attach firebase log screen shot 
<img width="1122" alt="Screen Shot 2021-12-15 at 6 29 06 PM" src="https://user-images.githubusercontent.com/46340921/146190812-a0d50bf4-9e5b-41b9-92b3-92fd8f039c91.png">

**Comment by BogdanRad** [comment]
@codal-mpawar, Did you find a solution to this problem? I have same problem..
