### ISSUE TITLE
Signature missing from Android purchase.

### ISSUE THREAD

**Issue by Froelund** [dooboolab/react-native-iap#31]
Hi!

I need to validate purchases from the backend, but I'm missing signature on the purchase.

The Purchase class `com.android.billingclient.api.Purchase` already contains the signature, but it needs to be passed in the response.

**Comment by JJMoon** [comment]
I am not Android specialist, but it looks like 'buyItem' method returns Purchase object, and send back to RN side as it is. ( RNIapModule.java line 419 )
I found signature on getPurchasedItemsAndroid. Can you use that instead?
