### ISSUE TITLE
getAvailablePurchases returns empty array (non-consumable)

### ISSUE THREAD

**Issue by jordan-jarolim** [dooboolab/react-native-iap#316]
### Version of react-native-iap
2.3.18
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
getAvailablePurchases() should return array of previously purchased items
### Actual behavior
getAvailablePurchases() returns an empty array
### Tested environment (Emulator? Real Device?)
TestFlight
### Steps to reproduce the behavior
I am signed with my real apple id, I buy a non-consumable product on ios and call getAvailablePurchases() later. The method returns an empty array instead of the array of purchased items. Although when I try to buy the same item for the second time, I get a warning saying that I have already bought that item and I can get it for free. So its definitely somehow saved in iTunes connect. Unfortunately, I am not able restore those purchases with getAvailablePurchases method (even if it is called after initConnection()). Any help appreciated.

**Comment by jordan-jarolim** [comment]
Update: works correctly when running on connected physical device. So it seems theres some problem with TestFlight Accounts.

**Comment by JJMoon** [comment]
@jordan-jarolim Thank you for your work. Testflight is for closed (and open) beta test tool for production. It's real Apple ID. I suggest not to use real ID for IAP testing. There is Sandbox tester for this purpose. I am closing this issue..

**Comment by jordan-jarolim** [comment]
According to this article: http://help.testlio.com/testing-mobile-applications/testing-in-app-purchases-on-ios sandbox account is automatically created. So it should work the same way as the sandbox account created in itunes connect. Just help me understand why this shouldnt work please.

**Comment by wasedaigo** [comment]
I might be getting this issue in production(2.2.0). Some users report me that purchases items won't appear.
