### ISSUE TITLE
Supporting RN versions <54

### ISSUE THREAD

**Issue by schumannd** [dooboolab/react-native-iap#318]
I want to use this package in a RN v51 project. Are there specific reasons why RN 54 is a requirement for this project or are lower versions just not supported?

**Comment by dooboolab** [comment]
You still can use this but you won't be able to use a validating receipt feature in the repository. That's all.

**Comment by schumannd** [comment]
Do you know how far back this package supports older RN versions? Maybe this number should be mentioned in the README, as it would encourage more users / contributors to use this package. Validating a reciept on the client side seems to be unsafe anyway, so I would think many could do without that feature.

I moved away from the [current iOS iap package](https://github.com/chirag04/react-native-in-app-utils) as it as not really maintained anymore, and I would suspect many might do the same.
