### ISSUE TITLE
Property `description` missing from Product type description on README

### ISSUE THREAD

**Issue by schumannd** [dooboolab/react-native-iap#321]
I have added it in PR #320 

Also, title is described as `Returns the title Android and localizedTitle on iOS`. AFAIK title and description are also localized on android. Is this a reference to the property names of the native objects? If yes I would remove it as it can be confusing.

I think a complete documentation of types and functions somewhere could be helpful. Maybe simply introducing something like flow or typescript would be a possibility?

Edit:
The description of the `price` property of the Product object also seems to be wrong: `Will return localizedPrice on Android (default)`

On Android it does not return a localized string.

**Comment by dooboolab** [comment]
merged.
