### ISSUE TITLE
Purchase product for specific users

### ISSUE THREAD

**Issue by schumannd** [dooboolab/react-native-iap#322]
I think it's currently an iOS-only feature, but I think it should be implemented in this package.

It makes it possible to use multiple accounts with a single appstore/playstore account without sharing the purchases.

**Comment by dooboolab** [comment]
Are you saying you want to show different purchases to users in your app? If then, you may implement logic by yourself differentiating the type of users.

**Comment by JJMoon** [comment]
@schumannd Thank you for your opinion. I am not fully aware of this issue, but it looks like.
This functionality (purchase a product with several Apple ID) might be prohibited by Apple. If it is necessary you just have to log out and sign in with other ID.
And another issue is.
IMHO, some functionality available in Android may (or should) not be included in iOS and vice versa.
Those platforms are different in nature, and compete each other. I guess this module just supplies each platform's functionality.

**Comment by schumannd** [comment]
@JJMoon 

I may have been wrong about the reason [applicationUsername](https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername) and [restoreCompletedTransactionsWithApplicationUsername](https://developer.apple.com/documentation/storekit/skpaymentqueue/1505992-restorecompletedtransactionswith?language=objc) were introduced in iOS 7. Maybe you cannot do multiple purchases with it anyway.

But it offers a way to attach some sort of string to a purchase. And this functionality is also available for Android as the `developerPayload` described [here](https://developer.android.com/google/play/billing/billing_reference#getBuyIntent)

So as this functionality is present in both android and iOS I think it should be implemented in this package as well.

[Here](https://github.com/chirag04/react-native-in-app-utils/pull/119/files) is an example PR where it was implemented in a different package. Is this wanted? If yes, I might get around to implementing and opening a PR for it.

**Comment by JJMoon** [comment]
@schumannd Thank you for your suggestion. I think it makes sense. I will implement it.
Anyway, we are borrowing some methods from this rn-in-app-util library.

**Comment by meInteractive** [comment]
@schumannd it woul be greate! We have the same problem

**Comment by hyochan** [comment]
Would this be handled together with #294? I've not yet dig into this. I am currently organizing some duplicate issues to be solved.

**Comment by schumannd** [comment]
I think it should stay open

**Comment by hyochan** [comment]
@schumannd Thanks for the interest. Let's keep it opened.

**Comment by lucianojsjr** [comment]
Any news about this feature request? I think it should stay open too.

**Comment by yasodha-r** [comment]
I also need this feature. @hyochan any update on this?
