### ISSUE TITLE
RNIap.clearProducts is not a function

### ISSUE THREAD

**Issue by raynor85** [dooboolab/react-native-iap#323]
### Version of react-native-iap
2.3.19
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
RNIap.clearProducts() should work
### Actual behavior
RNIap.clearProducts() raises this error: ` _reactNativeIap.default.clearProducts is not a function`
### Tested environment (Emulator? Real Device?)
Both
### Steps to reproduce the behavior
Simply run that code. I have found a workaround, but the documentation should be updated or the bug fixed.

```
import { clearProducts } from 'react-native-iap';

clearProducts();
```

**Comment by hyochan** [comment]
@raynor85 Are you still facing this? Have you tried `unlinking` and `linking` again?

**Comment by hyochan** [comment]
Seems like this is an linking issue. Please reopen when you face this.
