### ISSUE TITLE
transactionReceipt equal to dataAndroid

### ISSUE THREAD

**Issue by schumannd** [dooboolab/react-native-iap#324]
I would think that transactionReceipt should be equal to signatureAndroid. At least that's how I have seen it used in another package. Is there another reason for this design decision?

Also it is confusing that `transactionReceipt` contains a dict on android, but the actual receipt on iOS. Is this intended?

**Comment by dooboolab** [comment]
You need to validate purchase in android with the returned `json` referred to google doc. Also [this](https://medium.com/@infinitesimal_/doing-android-purchase-validation-api-v3-in-java-5c46fc837368) may help. We've stored `transactionReceipt` that will be used to validate the purchases.

Please share something more if you have any other opinion or better solution.

**Comment by schumannd** [comment]
Thanks, that explains it.
