### ISSUE TITLE
RNIAP.getSubscriptions(itemSkus) returns undefined

### ISSUE THREAD

**Issue by Ollie-Saer-WBS** [dooboolab/react-native-iap#327]
### Version of react-native-iap
2.3.19
### Platforms you faced the error (IOS or Android or both?)
iOS (Have not tried on Android as not required)
### Expected behavior
`console.log( products );` returning the array of my product.  This constant is the value returned by `RNIap.getSubscriptions(itemSkus);`
### Actual behavior
`console.log( products );` returns `undefined`.
### Tested environment (Emulator? Real Device?)
Both.
### Steps to reproduce the behavior
```
import * as RNIap from 'react-native-iap';
 
const itemSkus = Platform.select({
  ios: [
    'iview_learning_individual_5yr'
  ],
});

async componentDidMount() {
	try {
		const result = await RNIap.initConnection();
		//console.log('result', result);
	} catch (err) {
		console.warn(err.code, err.message);
	}

	try {
		 const products = await RNIap.getSubscriptions(itemSkus);
		 this.setState({ products });
		 console.log( products );
	} catch(err) {
		 console.warn(err); // standardized err.code and err.message available
	}
}
```
![App Store Connect In-App Purchase record](https://user-images.githubusercontent.com/42766020/48903307-0cd85300-ee53-11e8-9e68-6a846dd08b62.png)

**Comment by dooboolab** [comment]
Have you gone through `Q&A` session in the readme? This is one of most asked issue.

**Comment by Ollie-Saer-WBS** [comment]
I've had a look at the Q&A briefly, but I'm unsure which one applies to me?  As the function does not return an error message or an empty array, just `undefined`.  Thanks very much for your help.

![Q&A Excerpt](https://user-images.githubusercontent.com/42766020/48934218-0b626580-eefb-11e8-8e1f-6c6065d6f8d2.png)

**Comment by dooboolab** [comment]
The middle one. Unlinking and linking or manual linking would help.

**Comment by Ollie-Saer-WBS** [comment]
Unfortunately, running `react-native unlink react-native-iap` and then running `react-native link react-native-iap` produces the same result.  I'll be having a look at manual linking over the weekend.  Thanks very much for your help thus far.

**Comment by dooboolab** [comment]
Any news?

**Comment by Ollie-Saer-WBS** [comment]
Unfortunately, I wasn't able to complete the manual linking.  This is because while I am ejected to ExpoKit, I remove the ejection parameters from my `app.json` file.  This allows me to install most React Native community libraries in my project (which CRNA does not), but also allows me to use Expo to build my project.  This, unfortunately, has the knock-on effect of Expo ignoring Native Code during the build process.

I don't suppose you have any suggestions as to how I can get the automated linking working?  Also, is the status of my In-App Purchase (Waiting for Review) valid for it be picked up by the `RNIap.getSubscriptions(itemSkus);` method?

**Comment by dooboolab** [comment]
Your items can be fetched correctly when the status is in `Ready to submit`. Then you can later request the review to reviewer selecting the purchases.

Also, you need to detach to expokit to correctly use our module. Now I see why you won't able to use our module. Since this doesn't seem to be an issue, I will close for now.
