### ISSUE TITLE
How to consume/cancel a subscription? Not working with consumePurchase

### ISSUE THREAD

**Issue by CodeHunterDhi** [dooboolab/react-native-iap#330]
###Version of react-native-iap
 2.0
"react-native": "0.53",
### Platforms you faced the error (IOS or Android or both?)
android

### Expected behavior
Consumption of a subscription before subscription period is over

### Actual behavior
Not working with  "await RNIap.consumePurchase(purchase.purchaseToken);"

### Tested environment (Emulator? Real Device?)
 In Real Device

### Steps to reproduce the behavior
 Please Subscribe and then try to consume  using 
"await RNIap.consumePurchase(purchase.purchaseToken)"

 #### Error Message :" Google is indicating that we have an error in our code. Sorry about that."

Note: consumePurchase is working well in the case of purchased products.

How to consume the Subscriptions?

Thanks

**Comment by dooboolab** [comment]
You aren't understanding the iap correctly. You can't consume the subscription.
