### ISSUE TITLE
Error when logged out off Play Store

### ISSUE THREAD

**Issue by pyankoff** [dooboolab/react-native-iap#331]
### Version of react-native-iap
2.3.19

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Graceful fail

### Actual behavior
Native error

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
If you log out from Play Store accounts on the device, this line throws an error `Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference`:

https://github.com/dooboolab/react-native-iap/blob/e961483d1ee73803cf2449fbbeec94d720e63294/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L279

**Comment by dooboolab** [comment]
Yeah. Good catch. We should fix this. Would you mind giving a `PR` for this?

**Comment by safciplak** [comment]
i get still version 2.4.0-beta13 how can we redirect to log in google account ? 
help help me 
cheers
