### ISSUE TITLE
Cannot restore/consume a failed purchase on Android

### ISSUE THREAD

**Issue by lefoy** [dooboolab/react-native-iap#332]
### Version of react-native-iap
2.3.17

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
I should be able to restore/consume a consumable product after a payment has failed.

### Actual behavior
I am not able to retrieve the failed payment.

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
We are testing our payment process to make sure it fails gracefully under different circumstances. When there's a change of network during the purchase process, we get an error `An unknown or unexpected error has occurred. Please try again later.` and the displayed message in the Google popup says that there's no connection available. So far so good.

The problem happens when we are trying to restore/consume that purchase. When we try the purchase process again, we get a message saying "Your already own this item" and the purchase fails.

Our understanding is that we have a pending transaction that we need to complete, but we don't see any way to retrieve the token from that purchase to complete the transaction. We tried `getAvailablePurchases` but it doesn't seem to work because our product is a consumable. We also tried `consumeAllItems` but we still get the already owned message.

Is there any way to retrieve and complete the pending transaction?
Thanks!

**Comment by dooboolab** [comment]
This sounds pretty promising. Currently, this is a new issue for me. I think I need to search on google for this weird experience. Also, `consumeAllItems` should work fine, and hard to tell why it isn't working in your case.

**Comment by dooboolab** [comment]
@lefoy I just found wrong `npe` in `android` during `getAvailablePurchases` and fixed it in `2.3.20`. Would you mind trying this out?

**Comment by lefoy** [comment]
Thank you for the reply. I tried the update but I get the same results, `getAvailablePurchases` returns an empty array and `consumeAllItems` returns `"All items have been consumed"` but I still get the message "Your already own this item" from Google when I tried the purchase again.

I am able to reproduce the issue when I turn off my wifi right after I click on the confirm transaction button in the Google popup during the payment process.

Here's the code I'm using to restore purchases, maybe I'm doing something wrong.

```
[...]
.catch(error => { // <- This is the catch for the `RNIap.buyProduct` function
  console.log(error, error.code);
  if (error.code === "E_ALREADY_OWNED") {
    console.log(flags.PAYMENT, "Item is already bought");
    return RNIap.getAvailablePurchases().then(purchases => {
      console.log(flags.DEBUG, "availablePurchases", purchases);
      let purchase = purchases.find(purchase => purchase.productId === product);
      if (purchase) {
        console.log(flags.PAYMENT, "Restoring transaction", purchase);
        let { transactionReceipt, transactionId } = purchase;
        return RNIap.consumePurchase(purchase.purchaseToken).then(() => {
          return Promise.resolve({ ...transaction, transactionReceipt, transactionId });
        });
      } else {
        console.log(flags.PAYMENT, "Consuming all items");
        return RNIap.consumeAllItems().then(result => {
          console.log(flags.DEBUG, "consumedItems result", result);
        });
      }
    });
  } else {
    throw error;
  }
});
```

**Comment by lefoy** [comment]
@hyochan I'm using 2.3.21, which I think is the latest release

**Comment by hyochan** [comment]
Ok. I am currently unaware of this issue. Let's see who's coming next.

**Comment by lefoy** [comment]
I'm not sure I understand your answer, you're saying there's no way to fix this issue? @hyochan

**Comment by hyochan** [comment]
@lefoy Yes, because `consumeAlltems` should do that job correctly but you are still seeing this. I think we need to hold on for some solution in your case.

Also could you try `await consumeAllItems` serveral times and comback again?

**Comment by hyochan** [comment]
@lefoy I've just updated the code for you to move forward. Try `2.3.24` and do `await consumeAllItems` and please tell me what's comming.
