### ISSUE TITLE
RNIap.getProducts not working

### ISSUE THREAD

**Issue by Nits7029** [dooboolab/react-native-iap#333]
### Tested environment (Emulator? Real Device?) : Real Device

check attached screenshot

![screenshot_2018-12-05-18-23-40-563_com josuq](https://user-images.githubusercontent.com/9457796/49515172-31551600-f8bc-11e8-9670-bb3eca1b9eae.png)

**Comment by dooboolab** [comment]
Did you check [issue](https://github.com/facebook/react-native/issues/21754) in `react-native`? Check if your version of react-native may cause this problem. This error message doesn't belong to this module.

**Comment by Nits7029** [comment]
`async componentDidMount() {
  try {
    const result = await RNIap.initConnection();
     console.log('result', result); // getting true
    const products = await RNIap.getProducts('com.josuq'); // in this line i am getting an error
  } catch(err) {
    console.warn(err); // standardized err.code and err.message available
  }
}`

**Comment by Nits7029** [comment]
check my inline comment in above code, thanks

**Comment by dooboolab** [comment]
Have you gone through the issue link I've posted earlier?

**Comment by Nits7029** [comment]
yes, it works now. but i am getting blank array now though i have added 2 products in google play console. so what else i need to check?

![screen shot 2018-12-07 at 4 41 54 pm](https://user-images.githubusercontent.com/9457796/49644658-152db200-fa3f-11e8-8403-d5ac04468151.png)

**Comment by Nits7029** [comment]
@dooboolab could you please tell me, thanks

**Comment by dooboolab** [comment]
You need to wait for few hours if you created new products in playstore.

**Comment by Nits7029** [comment]
ok, can i get products in debug mode or it will work only in release mode?

**Comment by Nits7029** [comment]
ok, thanks.

**Comment by Nits7029** [comment]
i have checked, its still returning a blank array. so what i should do now? for in app purchase, merchant account setup, payment method setup needed in google play console or its not mandatory?

**Comment by dakiesse** [comment]
@Nits7029 have your solved the problem? I have the same now and I can't understand how to get products
