### ISSUE TITLE
 Where should I write "RSA public key"?

### ISSUE THREAD

**Issue by oper1782** [dooboolab/react-native-iap#334]
### Version of react-native-iap
Install the latest version yesterday
### Version of react-native
0.57.1
### Platforms you faced the error (IOS or Android or both?)
android
### Expected behavior
I did not write it but it run
### Tested environment (Emulator? Real Device?)
Emulator. Signed App distribute "Alpha Version"
### Steps to reproduce the behavior
const itemSkus = Platform.select({
    ios: [
      'test1',
      'test2',
      'test3'
    ],
    android: [
      'test1',
      'test2',
      'test3',
    ],
  });
    
  async componentDidMount() {
        try {
        console.log("itemSkus",itemSkus)
          const products = await RNIap.getProducts(itemSkus);
          this.setState({ products : products });
          console.log("point componentDidMount",products)
        } catch(err) {
          console.log("point componentDidMount Error ",err); // standardized err.code and err.message available
        }
    }

**Comment by dooboolab** [comment]
You don't need to write it down in recent iap module.
