### ISSUE TITLE
[Android] cannot buy two time on same product id

### ISSUE THREAD

**Issue by king804** [dooboolab/react-native-iap#335]
Version of react-native-iap
0.3.23

Version of React Native
react-native : 0.57

Platforms you faced the error (IOS or Android or both?)
Android

Tested environment (Emulator? Real Device?)
Real Device

The client only able to buy once, after that they can't buy again, keep no response on same item.

async componentDidMount() {
         await RNIap.prepare();
         const products = await RNIap.getProducts(itemSkus);
}

async buyProduct(){
         await RNIap.buyProduct('com.xxxxxxxxxxxx.xxxxxx').then(purchase => {

         });
}

**Comment by dooboolab** [comment]
You need to `consumePurchase` to able to re-purchase. If your product isn't `consumable` you can't re-purchase.

**Comment by king804** [comment]
Is that every-time access the purchase page require consumer item?

i draft the code like this...correct?

getPurchases = async() => {
  try {
    const purchases = await RNIap.getAvailablePurchases();
    purchases.forEach(purchase => {
        await RNIap.consumePurchase(purchase.purchaseToken);
    })
  } catch(err) {
    console.warn(err); // standardized err.code and err.message available
    Alert.alert(err.message);
  }
}

**Comment by king804** [comment]
I just saw the documents, i already have 10~30 purchase and don't consumer, is that call consumeAllItems() is better?
