### ISSUE TITLE
doboolab-welcome

### ISSUE THREAD

**Issue by Thomazella** [dooboolab/react-native-iap#336]
why?

**Comment by dooboolab** [comment]
Why not?
This is nothing but to inform that this package belongs to `dooboolab`. This is what other great libraries are doing such as `react-native-elements` or `firebase`. I've just seperated package to `dooboolab-welcome` to reuse this in other module that's created by `dooboolab's forks`. If you've installed many modules that belongs to `dooboolab` it will just print once.

Thanks.

**Comment by lxcid** [comment]
Thanks for the explanation. I recommend adding this explanation to README.md under FAQ. When reviewing libraries, it can be scary at times to see dependencies that seems a little bit out of place. Also, as the package is not open sourced (though you can review the source if you have install it), it make it a little suspicious. (Thus, I'm also recommending opening sourcing the small package)

I have no problem with the dependencies and respect the owner/maintainer decisions. Thanks for the hard work!

**Comment by hyochan** [comment]
@lxcid Oh! I understand your concern now. Yeah, there was a serious attack with `npm packages` and sure many people will be curious about this. Also, I'll just make [dooboolab-welcome](https://github.com/dooboolab/dooboolab-welcome) public for now (I didn't know it wasn't).

**Comment by Thomazella** [comment]
@hyochan That's what I was trying to say. I was just having a bad day that day. Please excuse me for that. Also, last time I checked, the welcome package itself depends on `chalk`...

**Comment by hyochan** [comment]
@Thomazella Yes. `dooboolab-welcome` uses chalk to color the letters. Is there any vulnerability inside?
