### ISSUE TITLE
Android: check if introductory period is still active

### ISSUE THREAD

**Issue by VLanc** [dooboolab/react-native-iap#338]
### Version of react-native-iap
2.3.17
### Version of react-native
0.50.4
### Platforms you faced the error (IOS or Android or both?)
Android
### Tested environment (Emulator? Real Device?)
Real Device

I try to implement subscription with the introductory price. I want to change the text on my subscription screen depending on whether the introductory period is still active but there isn't a necessary field in the object after calling `RNIap.getSubscriptions()` and `RNIap.buySubscription()` on the Android (for example, after calling `RNIap.buySubscription()` on the iOS I receive an object with field `is_in_intro_offer_period` and I use it to check whether the introductory period is still active). Is it possible to check whether the introductory period is still active using these methods on the Android?

**Comment by hyochans** [comment]
I haven't tested this feature yet. It would help me figure out your experiment like what you've done and what you are getting.

**Comment by VLanc** [comment]
@hyochan 
This is what I do on my subscription screen:
```
componentDidMount() {
  await RNIap.initConnection();
  const subscriptions = await RNIap.getSubscriptions(subItemSkus);
  ...
}
```

After it, I get the array with an object of subscriptions in subscriptions constant.
iOS (there isn't a necessary field to check whether the introductory period is still active):
![image](https://user-images.githubusercontent.com/29314707/50162157-abd75a00-02ee-11e9-9273-cc7c906facf1.png)

Android (there isn't a necessary field too): 
![image](https://user-images.githubusercontent.com/29314707/50162245-e8a35100-02ee-11e9-9bf0-b323a2d7b1a2.png)
```
handleBuySubscriptionButton() {
  const purchase = await RNIap.buySubscription(subItemSkus);
  ...
}
```
After it I get the object in purchase constant with `is_in_intro_offer_period` field which I can use for my purpose (iOS):
![image](https://user-images.githubusercontent.com/29314707/50159027-b42b9700-02e6-11e9-867a-4a4cea1aa3c5.png)

But I don't get a similar field on the Android:
![image](https://user-images.githubusercontent.com/29314707/50172903-244a1500-0307-11e9-81c8-c0c9ae7a5ac2.png)

How to check whether the introductory period is still active using these methods on the Android?
