### ISSUE TITLE
cleanup transactionReceipt / purchaseToken / dataAndroid for android

### ISSUE THREAD

**Issue by schumannd** [dooboolab/react-native-iap#339]
In the docs `purchaseToken` is labeled a ios/android key. But for iOS it seems to be always None.

On android `transactionReceipt` returns a stringified JSON containing duplicate data already available a level above in the data structure.

I propose the following:
- remove the `purchaseToken` key and instead save its value in `transactionReceipt` for android

**Comment by hyochans** [comment]
I am quite confused about what you are on to reading it. Could you explain what exactly you want to achieve from here? What was your test case?

**Comment by schumannd** [comment]
My goal is to make the package more easily accessible to new users by making the data structures more consistent and improving documentation.

I was confused by `receipt` containing a stringified json containing data already available. `additionalData` also confuses me as it is not documented and terribly named.

I opened this issue to find out whether it is in the interest of the maintainers to improve this.

**Comment by schumannd** [comment]
Oh, I haven't even considered googles own API to send data like that... If that is the case, maybe we shouldn't change it.

> If you provide your format of returned json here, I will look for it.

What do you mean by that?

**Comment by hyochan** [comment]
@schumannd I just wanted to look at the returned `json` you're looking at.

**Comment by schumannd** [comment]
Ok, first of all I got confused with the naming in my code when explaining my issue the first time. I have edited it and it should now be clearer.

When calling `buySubscription` I get something like the following json:

```
{
  autoRenewingAndroid: true, 
  dataAndroid: "{"orderId":"GPA.3300-5851-3283-12345","packageName":"my.package.name","productId":"my.product.id","purchaseTime":1545052439166,"purchaseState":0,"purchaseToken":"oiqCHh08o7rknK170ALyjuhZkLy94e1Zrp1ObKB0zlvTLjVkpMgNmTpUeY5KdN-yKT6y4jP-.hsvrzGh5O8ADmh_5sbj4KmQJ.nAfTOa5nER-4hmL06.GFyBKx.7tv1htGQDN0roK2VO7pjoN7wTF8mM08vWXjMjzSl3v-eqgfGMKXXcbu65du4xUWdw","autoRenewing":true}", 
  productId: "my.product.id", 
  purchaseToken: "kocdpadgbejnakeieikocidb.AO-J1OyXDtSqUX4C0tlj9noJMNLmnJpwtUKa8qtA7G-1ZMaZKwHqjIM7wmNBLAdiwvoC_V5uKpg7dKpWlHVa8KSMSKpUA2mPnk-_77SUkCa8FwJOTgPIAkrUVykKZP8Y3Mn3H_FINgDPXJk8ylQo2CMGeZ9Gi_9yzg", 
  signatureAndroid: "Ut6oQ3p0Hc2QY85KoSBUGILMMB8EUMkIefd4zpCuAb7G44oCU83s3DDZKK7hf1Zqmy7WyYJmPXLRXJmvHxyER5E8e0M8KgSpemddBG5p9ZV5QGVzzXYLZ5dPeExr46hIDLaH0hHjmSJ3o7eyMva6UJjZeHX4VLzBH3TwBSuguRXadT98T1JmLni2V04PTLrZd0PFPJQ47DbuKhvtV8n0Wx3UImcOXoGZZDPlkulL0vzxKE6lfVVV0q5M866D6NvWE9s7hKd8ZPOdLx72cLUgB7JOtZl61jb76y8ZLYZJrQCPU4CGVM8nOK3Wz1VwPLSxk6jt4VMSKV5LbeDGUje6qt==", 
  transactionDate: "1545052439166", 
  transactionId: "GPA.3300-5851-3283-45143", 
  transactionReceipt: "{"orderId":"GPA.3300-5851-3283-12345","packageName":"my.package.name","productId":"my.product.id","purchaseTime":1545052439166,"purchaseState":0,"purchaseToken":"oiqCHh08o7rknK170ALyjuhZkLy94e1Zrp1ObKB0zlvTLjVkpMgNmTpUeY5KdN-yKT6y4jP-.hsvrzGh5O8ADmh_5sbj4KmQJ.nAfTOa5nER-4hmL06.GFyBKx.7tv1htGQDN0roK2VO7pjoN7wTF8mM08vWXjMjzSl3v-eqgfGMKXXcbu65du4xUWdw","autoRenewing":true}
}
```
Similar for `buyProduct` and `getPurchaseHistory`. As you can see, there is quite a bit of duplicate information. But maybe it is sent like that from google.

So my problems are:

1. `purchaseToken` is labeled as both android and iOS key. It is always None for me on iOS. Does it have some relevancy in iOS that I have not found out about yet? Or is it an error in the docs.

2. `dataAndroid` and `transactionReceipt` contain a lot of duplicate data. Or am I missing some edge case here where some data in these keys is of practical use?

What do you think, should this be improved?

**Comment by hyochan** [comment]
@schumannd 
1. `purchaseToken` is labeled as both android and iOS key. It is always None for me on iOS. Does it have some relevancy in iOS that I have not found out about yet? Or is it an error in the docs.
- Is your product consumable in `ios`?

2. dataAndroid and `transactionReceipt` contain a lot of duplicate data. Or am I missing some edge case here where some data in these keys is of practical use? 
- We you see the [code](https://github.com/dooboolab/react-native-iap/blob/7437c962528c956f98f5f23de0acaa695280fd9a/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L271-L305), yes you are right there are some duplicate data. If you don't need that you can just ignore that. Reason for putting that in api was that we weren't sure which `extra` data received in a certain situation when it is `subscription`, `auto renewable` and etcs. We've just provided the possibility to handle some information we aren't aware of.

**Comment by schumannd** [comment]
@hyochan 
No they are not consumable. I assume then a purchaseToken would be set for iOS?

**Comment by hyochan** [comment]
@schumannd Actually, I think the readme was wrong. I will update it. `purchaseToken` is only for android.

**Comment by hyochan** [comment]
@schumannd Sorry, I was confused. I think the purchaseToken should be returned. Were you testing this in `sandbox`?

**Comment by hyochan** [comment]
@schumannd I've just looked in the code and realized missing `purchaseToken` field in ios today. Actually, this was the `cp` of `transactionReceipt` previously. So I think I need to change this is doc that `ios` is not returning this anymore.

**Comment by hyochan** [comment]
`purchaseToken` is needed for `android` to consume the actual purchase which `ios` doesn't have that functionality. I think we can close this for now.

**Comment by schumannd** [comment]
Well, the `purchaseToken` would still be available. I don't think this issue has been resolved. Or is the answer "Won't fix"?

**Comment by hyochan** [comment]
I don't quite get your problem here. How would you like the changes to be?

**Comment by schumannd** [comment]
I proposed:

instead of:

```
{
  autoRenewingAndroid: true, 
  dataAndroid: "{"orderId":"GPA.3300-5851-3283-12345","packageName":"my.package.name","productId":"my.product.id","purchaseTime":1545052439166,"purchaseState":0,"purchaseToken":"oiqCHh08o7rknK170ALyjuhZkLy94e1Zrp1ObKB0zlvTLjVkpMgNmTpUeY5KdN-yKT6y4jP-.hsvrzGh5O8ADmh_5sbj4KmQJ.nAfTOa5nER-4hmL06.GFyBKx.7tv1htGQDN0roK2VO7pjoN7wTF8mM08vWXjMjzSl3v-eqgfGMKXXcbu65du4xUWdw","autoRenewing":true}", 
  productId: "my.product.id", 
  purchaseToken: "oiqCHh08o7rknK170ALyjuhZkLy94e1Zrp1ObKB0zlvTLjVkpMgNmTpUeY5KdN-yKT6y4jP-.hsvrzGh5O8ADmh_5sbj4KmQJ.nAfTOa5nER-4hmL06.GFyBKx.7tv1htGQDN0roK2VO7pjoN7wTF8mM08vWXjMjzSl3v-eqgfGMKXXcbu65du4xUWdw", 
  signatureAndroid: "Ut6oQ3p0Hc2QY85KoSBUGILMMB8EUMkIefd4zpCuAb7G44oCU83s3DDZKK7hf1Zqmy7WyYJmPXLRXJmvHxyER5E8e0M8KgSpemddBG5p9ZV5QGVzzXYLZ5dPeExr46hIDLaH0hHjmSJ3o7eyMva6UJjZeHX4VLzBH3TwBSuguRXadT98T1JmLni2V04PTLrZd0PFPJQ47DbuKhvtV8n0Wx3UImcOXoGZZDPlkulL0vzxKE6lfVVV0q5M866D6NvWE9s7hKd8ZPOdLx72cLUgB7JOtZl61jb76y8ZLYZJrQCPU4CGVM8nOK3Wz1VwPLSxk6jt4VMSKV5LbeDGUje6qt==", 
  transactionDate: "1545052439166", 
  transactionId: "GPA.3300-5851-3283-45143", 
  transactionReceipt: "{"orderId":"GPA.3300-5851-3283-12345","packageName":"my.package.name","productId":"my.product.id","purchaseTime":1545052439166,"purchaseState":0,"purchaseToken":"oiqCHh08o7rknK170ALyjuhZkLy94e1Zrp1ObKB0zlvTLjVkpMgNmTpUeY5KdN-yKT6y4jP-.hsvrzGh5O8ADmh_5sbj4KmQJ.nAfTOa5nER-4hmL06.GFyBKx.7tv1htGQDN0roK2VO7pjoN7wTF8mM08vWXjMjzSl3v-eqgfGMKXXcbu65du4xUWdw","autoRenewing":true}"
}
```

to return 

```

{
  autoRenewingAndroid: true, 
  productId: "my.product.id", 
  signatureAndroid: "Ut6oQ3p0Hc2QY85KoSBUGILMMB8EUMkIefd4zpCuAb7G44oCU83s3DDZKK7hf1Zqmy7WyYJmPXLRXJmvHxyER5E8e0M8KgSpemddBG5p9ZV5QGVzzXYLZ5dPeExr46hIDLaH0hHjmSJ3o7eyMva6UJjZeHX4VLzBH3TwBSuguRXadT98T1JmLni2V04PTLrZd0PFPJQ47DbuKhvtV8n0Wx3UImcOXoGZZDPlkulL0vzxKE6lfVVV0q5M866D6NvWE9s7hKd8ZPOdLx72cLUgB7JOtZl61jb76y8ZLYZJrQCPU4CGVM8nOK3Wz1VwPLSxk6jt4VMSKV5LbeDGUje6qt==", 
  transactionDate: "1545052439166", 
  transactionId: "GPA.3300-5851-3283-45143", 
  transactionReceipt: "oiqCHh08o7rknK170ALyjuhZkLy94e1Zrp1ObKB0zlvTLjVkpMgNmTpUeY5KdN-yKT6y4jP-.hsvrzGh5O8ADmh_5sbj4KmQJ.nAfTOa5nER-4hmL06.GFyBKx.7tv1htGQDN0roK2VO7pjoN7wTF8mM08vWXjMjzSl3v-eqgfGMKXXcbu65du4xUWdw"
}

```

The second format contains all data contained in the first one. And it is much easier to understand. If we want to capture additional data, we can add the `dataAndroid` key again.
