### ISSUE TITLE
getProducts : Empty Array

### ISSUE THREAD

**Issue by Nishit-Chauhan** [dooboolab/react-native-iap#340]
### Version of react-native-iap
2.3.19
### Version of react-native
0.56.0
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Array with products and subscription
### Actual behavior
Empty Array in both  products and subscription
### Tested environment (Emulator? Real Device?)
simulator
### Steps to reproduce the behavior
i have followed all the steps,
also done manual installation for IOS.
products and subscription both were fetched before some days,
![screen shot 2018-12-17 at 6 14 36 pm](https://user-images.githubusercontent.com/45855322/50087971-ae22b100-0227-11e9-99bc-ec0a3237912a.png)
but for now i m getting empty array for both.
i have configured in both, in Android it is working fine.

-------------------------
const coins = Platform.select({
    ios: [
        'coins250', 'coins600', 'coins2000'
    ],
    android: [
        'coins250', 'coins600', 'coins2000'
    ]
});

 async componentDidMount() {
        try {
            const products = await RNIap.getProducts(coins);
            console.log('Products', products)
            products.map((item, index) => {
                if (coins.includes(item.productId)) {
                    this.setState(state => (this.state.products.push(item), state))
                }})
        } catch (err) {
            console.warn(err); // standardized err.code and err.message available
        }
    }

**Comment by hyochan** [comment]
@Nishit-Chauhan Did you followed the [readme](https://github.com/dooboolab/react-native-iap#invalid-productid-in-ios)?

**Comment by sagarguhe** [comment]
@hyochan I am facing this issue on Android as well

**Comment by Nishit-Chauhan** [comment]
i have already configured manually on ios and it was working fine before few days,
but now the getProducts function returns blank array

**Comment by jimbol** [comment]
I had this problem, but I just had the wrong SKU. For ios I found the right one here.

<img width="1397" alt="Screen Shot 2019-05-01 at 11 17 36 PM" src="https://user-images.githubusercontent.com/1278367/57055166-7f055d00-6c67-11e9-9552-8340ec6ae993.png">
