### ISSUE TITLE
Expose priceLocale for iOS

### ISSUE THREAD

**Issue by m-sanders** [dooboolab/react-native-iap#342]
**Use case** 

We're offering a monthly and annual auto-renewing subscriptions on our iOS app. We want to display a comparable monthly equivalent price for the annual subscription formatted for the specific App Store locale. As a device can have a different locale from App Store, we cannot rely on the device locale to format the currency price. We also cannot rely on the currency code, for example, the euro formatting varies based on your country.

**Proposed solution for iOS** 

Expose `SKProduct.priceLocale` string value as part of the `getProducts` response as `product.priceLocaleIOS`.

https://github.com/dooboolab/react-native-iap/blob/10af7093f6f26c7473b20c232a4040e70ee5e620/ios/RNIapIos.m#L311-L314

**Android**

From my brief look into how to solve this for Android, there does not appear to be the equivalent locale information on the Play Store product. We're currently not targeting Android, but happy to make the change generic if anyone can point me in the right direction.

Would you like me to submit a PR?

---

### Version of react-native-iap

2.3.19

### Version of react-native

0.57.0

### Platforms you faced the error (IOS or Android or both?)

iOS only.

### Expected behavior

Able to further localise pricing information based

### Tested environment (Emulator? Real Device?)

Real device. iPad Air 2.

**Comment by hyochan** [comment]
This has been reverted in #345.

**Comment by hyochan** [comment]
@m-sanders Hi. I am organizing issues right now to maintain this further since I have bit free time these days. Do you still need this issue to be opened?

**Comment by m-sanders** [comment]
Apologies @hyochan for not getting back to you. I have not managed to find the time to look into this again. Feel free to close.

**Comment by hyochan** [comment]
Ok, I'll close this for now. Feel free to reopen whenever you need this.

**Comment by DataGreed** [comment]
@hyochan so is there any way to get `priceLocale` now?

**Comment by adorum** [comment]
any news on this?
