### ISSUE TITLE
Error when buying subscriptions: E_DEVELOPER_ERROR

### ISSUE THREAD

**Issue by fabricioasap** [dooboolab/react-native-iap#349]
Happy holidays!

### Version of react-native-iap
2.3.23

### Version of react-native
0.57.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Be able to buy the subscription and get the purchase info

### Actual behavior
I'm seeing a message saying "This version of the application is not configured for billing through Google Play."

### Tested environment (Emulator? Real Device?)
Real device with Android 7.1.1

### Steps to reproduce the behavior
A few minutes ago everything was working as expected, I was able to buy subscriptions with a test user but suddenly it stopped to work. I didn't change anything in the code or the Google play settings.

I'm getting the subscriptions correctly: 
```
async componentDidMount() {
    try {
      const result = await RNIap.initConnection();
      if (result) {
        const subscriptions = await RNIap.getSubscriptions(itemSubscriptions);
      }
    } catch (err) {
      console.warn(err);
    }
  }
```

But when I try to buy it, I get the error
`const purchase = await RNIap.buySubscription(sku);`

Does anyone know what is happening?
Thanks.
Best,

**Comment by fabricioasap** [comment]
I'm getting the same error with versions `2.23.26` and `2.4.0-betal`

**Comment by hyochan** [comment]
This error doesn't belong to our module and really in android `iap` itself. Please read [stackoverflow](https://stackoverflow.com/questions/11068686/this-version-of-the-application-is-not-configured-for-billing-through-google-pla).
