### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by JongGyuChoi** [dooboolab/react-native-iap#350]
### Version of react-native-iap
^2.4.0-beta2
### Version of react-native
0.56.0
### Platforms you faced the error (IOS or Android or both?)
 android

Build failed with below message

node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:26: error: RNIapModule(ReactApplicationContext) has private access in RNIapModule
    modules.add(new RNIapModule(reactContext));
                ^
Note: /Users/my/Documents/test_app/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

plz help me~

**Comment by hyochan** [comment]
Oops. There was a regression issue in ‘2.4.0-beta2’. I will update to beta3 soon. Please try ‘2.4.0-beta1’ for now.
