### ISSUE TITLE
 'E_NETWORK_ERROR', 'The service is disconnected (check your internet connection.)'

### ISSUE THREAD

**Issue by zdf01082413** [dooboolab/react-native-iap#352]

**Comment by zdf01082413** [comment]
'E_NETWORK_ERROR', 'The service is disconnected (check your internet connection.)'

**Comment by zdf01082413** [comment]
'E_NETWORK_ERROR', 'The service is disconnected (check your internet connection.)'

**Comment by thodwris** [comment]
Any solution on that?
