### ISSUE TITLE
What is the correct way to purchase a subscription on ios?

### ISSUE THREAD

**Issue by scottmcpherson** [dooboolab/react-native-iap#354]
Trying to figure out what the correct way to purchases a subscription. The documentation seems to suggest different approaches. 

My current approach completely stoped working. The purchase confirmation no longer appears on a physical device:

```
 async componentDidMount() {
      const itemSkus = Platform.select({
        ios: ['Yearly_Auto_Renew_Premium', 'Monthly_Auto_Renew_Premium']
      })
      try {
        await RNIap.initConnection()
        const products = await RNIap.getSubscriptions(itemSkus)
        this.setState({ products })
      } catch (err) {
        console.log(err)
      }
  }
  makePurchase = async ({ productId }) => {
    try {
      const { currentUser } = firebase.auth()
      const userId = currentUser && currentUser.uid

      const purchase = await RNIap.buyProductWithoutFinishTransaction(productId)
      const { transactionReceipt } = purchase

      // Call the server
      checkIsValidReceipt({ transactionReceipt }).then(result => {
        if (isValid) {
            // Update to subscribed here
        }
      })
    } catch (err) {
      console.log('err: ', err)
    }
  }
```
`checkIsValidReceipt` never gets called because `buyProductWithoutFinishTransaction` never resolves and the confirm purchase modal never shows.

Is this the recommended approach for purchasing a subscription? If so, I can continue to trouble shoot

`"react-native-iap": "^2.4.0-beta5",`

Update:
After reading this [article](https://kemenaran.winosx.com/posts/ios-developer-what-to-do-if-in-app-purchases-stop-working/), I was created a new test user. Now, when I open the app, it keeps asking me to confirm purchases. I click cancel and the dialog keeps popping back open.

**Update 2:**
I had to erase all content and settings from my phone to get it working again.
I would still like to know if the above approach uses the correct functions to purchase a subscription?

**Comment by JJMoon** [comment]
@scottmcpherson I think your code is OK. First of all, did you log the `products` in componentDidMount ?
The transaction you started with `buyProductWithoutFinishTransaction` won't not disappear unless you explicitly call `finishTransaction` method.
And you should log out your Apple ID, when you test IAP in sandbox mode.
You can log out sandbox in the Setting App.

**Comment by scottmcpherson** [comment]
Yeah, products are good. There was some really weird stuff going on with with my sandbox user. So I ended up deleting and creating a new one. And then, an endless flood of confirm to purchase popups started showing up. So I had to erase all my content and settings on my phone. 

Anyways, all is good now. Closing this issue.
