### ISSUE TITLE
Improving error messages / documentation regarding error messages

### ISSUE THREAD

**Issue by robertherber** [dooboolab/react-native-iap#358]
### Version of react-native-iap
2.3.26

### Version of react-native
0.57 (Expo 31)

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
I'd like to be able to discern between potentially critical errors and errors that are just because users canceled the purchase. This could be both a matter of improving documentation and maybe improving the error messages exposed by react-native-iap.

### Actual behavior
On both platforms I essentially get one single message no matter what seems to "fail" during the payment. I get:
"Canceled." (Android)
"Kan inte ansluta till iTunes Store" (iOS, Swedish for "Could not connect to iTunes Store")

### Tested environment (Emulator? Real Device?)
In production on real devices.

### Steps to reproduce the behavior
Seems to be triggered for example when initiating a purchase that the user cancels.

**Comment by hyochan** [comment]
Hi. Thank you for the issue! Are you aware that linking native modules are not yet supported by `expo`?

**Comment by robertherber** [comment]
@hyochan Of course. As I mentioned I'm using this library in production. It's a detached Expo project.

**Comment by noahhayes** [comment]
I'm seeing a similar issue. I am selling a subscription and I was able to test it successfully on my own device with my real account and with sandbox users. However, I'm noticing that a large number of my international users are failing to complete the transaction. All I see is a CANCELLED error message. Strangely, I see the error message multiple times. For instance, some users will press purchase 4 times in a row and are not able to complete the transaction. I can't figure out if they are just confused or if it's breaking.

**Comment by hyochan** [comment]
@noahhayes Thanks for the re-issue. I'll reference your issue #412 since this is related.

**Comment by hyochan** [comment]
Let's handle this continuously in #412.
