### ISSUE TITLE
localizedPrice returns wrong value on iOS

### ISSUE THREAD

**Issue by gaykov** [dooboolab/react-native-iap#360]
Hello,

We're facing a weird issue on iOS. The price for our in-app item is `$4.99` and we're trying to display it in user's currency using `localizedPrice`. On Android, everything works fine, and the price is converted and the currency is displayed correctly.

But on iOS, our customers from Russia, that should see `RUB 349` see `$349`, which is pretty funny for them, but not so funny for us  😕.

Here's how we display the text on the purchase button:
```
`${i18n.t('screens.pricing.purchase')} ${_.get(props.products, '0.localizedPrice', '4.99')}`
```

And we load products from the store by using
```
const products = await RNIap.getProducts([itemSkus]);
```

### Version of react-native-iap
2.3.21

### Version of react-native
0.57.5

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
`localizedPrice` on iOS should return a correct string with the currency symbol, just like on Android.

### Actual behavior
`localizedPrice` adds the dollar sign to the price in different currency.

### Tested environment (Emulator? Real Device?)
Real devices.

### Steps to reproduce the behavior
1. Add in-app purchase
2. Try to use `product.localizedPrice` on devices in non-dollar country.

**Comment by JJMoon** [comment]
I am not using `i18n.t `, but it seems like you must not include '4.99' in the list.
The localizedPrice has its currency units and price like "$ 3.44".
If you change location, the string will be "RUB 344" automatically.
I guess the price is Tier 4. ($ 4.99 ?). So, there is no way this module make that issue.

**Comment by JJMoon** [comment]
@gaykov OK. Then one thing I want to ask you to test.
Use '$ 4.99' or 'USD 4.99' instead of just '4.99'. Then you can see the difference.
