### ISSUE TITLE
Calling getSubscriptions second time returns an error

### ISSUE THREAD

**Issue by ljuborados** [dooboolab/react-native-iap#365]
### Version of react-native-iap
2.3.26
### Version of react-native
0.57
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
When calling getSubscriptions for the second time (without killing the app), even if RNIap.endConnection has been callled, I'd expect it to return the available subscriptions as in the first call.
### Actual behavior
It returns:
```javascript
[Error: Purchase failed with code: 0(OK)]
```
### Tested environment (Emulator? Real Device?)
Real device - Android 8.1.1
### Steps to reproduce the behavior

Add this code to any component:

```javascript
componentDidMount() {
        this.getAvailableSubscriptions();
    }

    componentWillUnmount() {
        RNIap.endConnection();
    }

    getAvailableSubscriptions = async () => {
        try {
            const res = await RNIap.initConnection();
            console.log(res);
            const products = await RNIap.getSubscriptions(itemSkus);
            console.log(products);
            this.setState({
                availableSubscriptions: products,
                subscriptionsFetched: true
            })
        } catch (error) {
            console.warn(error);
        }
    };
```
Navigate to the component, it should return all the available subscriptions.  
Go back. Navigate to the component again.  
It returns:
```javascript
[Error: Purchase failed with code: 0(OK)]
```

**Comment by hyochan** [comment]
I think you are not showing codes where the problem actually occurs because I see `Purchase failed` message not `getSubscriptions` message.
