### ISSUE TITLE
IAP does not prompt user to sign in to PlayStore if they are signed out.

### ISSUE THREAD

**Issue by theoryweary** [dooboolab/react-native-iap#367]
### Version of react-native-iap
"react-native-iap": "2.3.23",

### Version of react-native
    "react-native": "0.57.1",

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
When buySubscription is called and the user is not signed in to the Play Store, the device should present a popup to ask the user to sign in.  On iOS this works, but on Android I don't know how to trigger the sign-in popup. 

### Actual behavior
On android there is no pop-up asking the user to sign in to the Play Store.  Instead BuySubscription returns this Error:
Error: The service is disconnected (check your internet connection.)
    at createErrorFromErrorData (NativeModules.js:146)

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
Install app on device that is not signed in to Google Play.
Try to run BuySubscription (getSubscriptions also has the same behavior).  The promise fails without asking the user to log in. 

I understand that in practice most users would be logged in to the PlayStore already on their device, but I'd really like to be able to prompt the user if they get signed out for some reason.

**Comment by hyochan** [comment]
If what you've generated is normal behavior in android (unlike ios), currently I think you should `Alert.alert` something based on the `rejected error`.
