### ISSUE TITLE
Need help for non-renewable subscription in iOS

### ISSUE THREAD

**Issue by tranhiepqna** [dooboolab/react-native-iap#368]
Hi all,I want to implement in-app purchase in my app and I am new on this. In my app users have to pay for each new their post. Currently my in-app purchase product is set type Consumable but Apple rejected my app. Apple said

> Since the service offered by your app requires the user to make an advance payment to access the content or receive the service, please use non-renewable subscription in-app purchase product type.

I change my in-app purchase product to non-renewable. When I pay my first post, its ok. But when I try to pay the next post, it shows a message "You have already purchase this, tap to renew or extend it". I do not want to show this message when I pay new post. How can I resolve this issue?Any buddy have idea for this. Help will be appreciated. Thanks in advance.

### Version of react-native-iap
 react-native-iap: "^2.3.19"
### Version of react-native
 react-native: "0.48.1",
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Don't show a message "You have already purchase this, tap to renew or extend it", when I try to pay the next post
### Tested environment (Emulator? Real Device?)
Real Device

**Comment by hyochan** [comment]
I think this kind of question is more likely to be asked to `apple`. We are just supporting the bridging. Your question is more related to the `iap` feature of Apple which you should firstly understand before using this module. I don't know actually why Apple rejected your `consumable` products but it should be `consumable` if you want to purchase the item again.
