### ISSUE TITLE
buyProductWithoutFinishTransaction for subscriptions

### ISSUE THREAD

**Issue by robertherber** [dooboolab/react-native-iap#373]
I can't understand from the documentation if buyProductWithoutFinishTransaction is meant for use with subscriptions as well?

**Comment by hyochan** [comment]
@robertherber I think it is enough to just use `buySubscription`. The actual story of implementing `buyProductWithoutFinishTransaction` (if I remember correctly) was to solve an issue like #307 which I think didn't work quite well. Correct me if I am wrong (cc @JJMoon). So just use `buySubscription` will be fine.

**Comment by robertherber** [comment]
But wouldn’t this mean the same behavior would be true for subscriptions? #307 is probably as relevant for subscriptions, am I not right?
