### ISSUE TITLE
App Crashed when buy product

### ISSUE THREAD

**Issue by anhdvz** [dooboolab/react-native-iap#374]
### Version of react-native-iap
2.4.0-beta6
### Version of react-native
0.57.5
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Buy success
### Actual behavior
app crashed
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior
1. Buy product from google
2. Press home button to close app
3. Launch app from icon on screen
4. Buying modal disappear, buy product again
Error log:
Fatal Exception: com.facebook.react.bridge.ObjectAlreadyConsumedException
Map already consumed
com.facebook.react.bridge.WritableNativeArray.pushNativeMap (WritableNativeArray.java)
com.facebook.react.bridge.WritableNativeArray.pushMap (WritableNativeArray.java:53)
com.facebook.react.bridge.Arguments.fromJavaArgs (Arguments.java:187)
com.facebook.react.bridge.CallbackImpl.invoke (CallbackImpl.java:32)
com.facebook.react.bridge.PromiseImpl.resolve (PromiseImpl.java:30)
com.dooboolab.RNIap.RNIapModule.resolvePromisesForKey (RNIapModule.java:526)
com.dooboolab.RNIap.RNIapModule.access$800 (RNIapModule.java:46)
com.dooboolab.RNIap.RNIapModule$11.onPurchasesUpdated (RNIapModule.java:443)

**Comment by hyochan** [comment]
I think this issue is also related to #315.

**Comment by hyochan** [comment]
Please try `beta8` then come back again.

**Comment by anhdvz** [comment]
i tried beta11 and this issue still happen

**Comment by jimji1005** [comment]
Issue is `Map already consumed`, meaning you are purchasing the same item again. Google docs states you need to `consume` your purchase before buying it again.

**Comment by anhdvz** [comment]
@hyochan Did you close app (move to background) and launch app again from app's launch icon? When I did that, the processing of google iap is stop, and when i buy again, app crashed.
@jimji1005 How to do it? because I am in the middle of processing iap and I close it, so purchase did not happened and i can not consume it.

**Comment by anhdvz** [comment]
in my component:
 async componentDidMount() {
    try {
      await RNIap.initConnection();
      RNIap.consumeAllItems();
    } catch (err) {}
  }

  async componentWillUnmount() {
    await RNIap.endConnection();
  }

**Comment by hyochan** [comment]
@anhdvz The PR #379 by @dajaffe attempt to fix an issue as you've described lastly. However, you are saying no luck. I think we need this to supported from `react-native` to provide guide of handling background services especially in `android`.
