### ISSUE TITLE
Convert consumable to non-consumable please for me

### ISSUE THREAD

**Issue by Coinizy1** [dooboolab/react-native-iap#381]
### Version of react-native-iap
latest
### Version of react-native
latest
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Want to add non-consumable purchase
### Actual behavior
it is consumable
### Tested environment (Emulator? Real Device?)
Real
### Steps to reproduce the behavior
I want to add restore purchase to my app and non-consumable purchase.
I dont understand one thing i have a login/signup system so when user signup and he pays then i am doing payment to yes in database. what i dont understand is if i add non-consumable purchase how i am going to delete his old account if he restore purcase on new email and new device. because once he pay and change phones what i can do to.

//////////////  Code please convert it to non consumable    /////////////////

import React, { Component } from 'react';
import * as firebase from 'firebase';
var styles = require('../../assets/files/Styles');
import { Alert, Dimensions, Image, TouchableOpacity, ScrollView, Linking, Platform } from 'react-native';
import { Container, Body, Header, Input, Item, Left, Text, Title, Right, View, Button, Toast, Thumbnail, Grid, Row } from 'native-base';
import Strings from '../utils/Strings';
import { Constants, Location, Permissions, ImagePicker } from 'expo';
import * as RNIap from 'react-native-iap';

const itemSkus = Platform.select({
    ios: [
        'Get_Plans'
    ],
    android: [
        'Get_Plans'
    ]
});

var { width, height } = Dimensions.get('window');

export default class Register extends Component {
    static navigationOptions = {
        title: `${Strings.ST125}`,
    };
    constructor() {
        super();

        this.state = {
            receipt: null,
            Date: null,
            Payment: "14.99$",
            premium: null,
        };
    }
    async componentDidMount() {
        var userId = firebase.auth().currentUser.uid;
        var pay;
        var date;
        var Receipt;
        await firebase.database().ref('users').child(userId).once('value').then(function (snapshot) {
            pay = (snapshot.val() && snapshot.val().payment);
            date = (snapshot.val() && snapshot.val().PaymentDate);
            Receipt = (snapshot.val() && snapshot.val().Receipt);
        });
        this.setState({ receipt: Receipt });
        this.setState({ Date: date });
        this.setState({ premium: pay });
        try {
            await RNIap.initConnection();
            const products = await RNIap.getProducts(itemSkus);

        } catch (err) {
            console.warn(">>>>>>>>>>>>>>>>>>>>>  " + err.message);
            Alert.alert(err.message);
        }
    }

    Payment = async () => {
        var userId = firebase.auth().currentUser.uid;

        RNIap.buyProduct('Get_Plans').then(purchase => {
            this.setState({
                receipt: purchase.transactionReceipt
            });
            firebase.database().ref('users/' + userId).update({
                payment: "yes",
                Receipt: this.state.receipt,
                PaymentDate: new Date().toDateString(),
            });
            Alert.alert("Congratulation, Now you are Premimum user of app.");
            // handle success of purchase product
        }).catch((error) => {
            Alert.alert(error.message);
        })

    }

    componentWillUnmount() {
        RNIap.endConnection();
    }

    render() {

        return (
            <Container style={{ backgroundColor: '#fff' }}>
                <ScrollView>
                    <Grid>

                        <Row style={{ flexDirection: 'column', justifyContent: 'center', alignItems: 'center', backgroundColor: '#FFF', padding: 30, paddingBottom: 0 }}>
                            <Image
                                source={require('../../assets/images/logo_dark.png')}
                                style={{ width: 130, height: 130 }}
                                resizeMode='contain' />

                            {this.state.premium == 'yes' ? (
                                <View>
                                    <View style={{ flexDirection: 'row' }}>
                                        <Text style={{ margin: 10, marginBottom: 5, fontSize: 12, fontWeight: 'bold', textAlign: 'center', color: '#888888' }}>
                                            {this.state.Payment}
                                        </Text>
                                        <Text style={{ margin: 10, marginBottom: 5, fontSize: 12, fontWeight: 'bold', textAlign: 'center', color: '#888888' }}>
                                            {this.state.Date}
                                        </Text>
                                        <Text style={{ margin: 10, marginBottom: 5, fontSize: 12, fontWeight: 'bold', textAlign: 'center', color: '#888888' }}>
                                            Premium User
                                </Text>
                                    </View>

                                    <Text style={{ paddingLeft: 0, paddingBottom: 10, marginBottom: 5, marginTop: 15, fontSize: 18, fontWeight: 'bold' }}>
                                        Premium User
                            </Text>

                                    <Text style={{ color: '#888888', fontSize: 14, marginBottom: 20 }}>
                                        Congratulations, You are a premium user now. You can see the Workout Tab Now to Access latest videos and fitness tips.
                                    </Text>

                                    <Text style={{ paddingLeft: 0, paddingBottom: 10, marginBottom: 5, marginTop: 15, fontSize: 18, fontWeight: 'bold' }}>
                                        Receipt
                            </Text>

                                    <Text style={{ color: '#888888', fontSize: 14, marginBottom: 20 }}>
                                        {this.state.receipt}
                                    </Text>
                                </View>
                            ) : (
                                    null
                                )}
                        </Row>

                    </Grid>
                    {this.state.premium != 'yes' ? (
                        <Button block info
                            onPress={this.Payment}
                        >
                            <Text>{Strings.ST125}</Text>
                        </Button>
                    ) : (
                            null
                        )}
                </ScrollView>
            </Container>
        )
    }

}

**Comment by hyochan** [comment]
I think this kind of question is more likely to be asked to `stackoverflow`.
