### ISSUE TITLE
Document purchase transaction format mistake. 2.4.0-beta6

### ISSUE THREAD

**Issue by MikePodgorniy** [dooboolab/react-native-iap#382]
### Version of react-native-iap
2.4.0-beta6

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
transactionReceipt receipt will return purchaseToken for android.
https://github.com/dooboolab/react-native-iap#consumption-and-restoring-purchases

### Actual behavior
It returned the same as dataAndroid

### Tested environment (Emulator? Real Device?)
Real device & google play sandbox account

### Steps to reproduce the behavior
Just purchase something 

<img width="1264" alt="screen shot 2019-01-25 at 10 29 25" src="https://user-images.githubusercontent.com/5052136/51734433-35680d80-208d-11e9-9a58-d1fa74f1330a.png">

**Comment by hyochan** [comment]
You might want to see #339.
