### ISSUE TITLE
Return value of validateReceiptAndroid

### ISSUE THREAD

**Issue by LeomarAmiel** [dooboolab/react-native-iap#384]
Just a question, does `validateReceiptAndroid`return the value from this [resource representation](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions)?

**Comment by hyochan** [comment]
@LeomarAmiel I referred to [in-app-purchase](https://github.com/voltrue2/in-app-purchase) node.js module when building this.

**Comment by vishaldhanotiya** [comment]
I have faced the same issue. I write down the solution [here](https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880) please check this [link](https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880) it may help you to solve your problem 

https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880
