### ISSUE TITLE
getPurchaseHistory gets empty array in production

### ISSUE THREAD

**Issue by ming436534** [dooboolab/react-native-iap#385]
### Version of react-native-iap
2.4.0-beta6

### Version of react-native
0.55.4

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
getPurchaseHistory result is not empty.

### Actual behavior
The library generally works perfectly, but there is one case that confused me a lot. A user claimed that he subscribed a renewable product, for some reason the first purchase was not recorded so that we need the getPurchaseHistory to recover his purchase, but the problem is that the getPurchaseHistory function returned an empty array. When he tried to purchase again (by calling buySubscription), an alert with 'purchased message' pops up which showed that he has already purchased the product. I also confirmed his purchase by checking the purchase history from the itunes developer website.
Is there anyway to solve this problem? Thank you.
### Tested environment (Emulator? Real Device?)
Production

### Steps to reproduce the behavior
Unknown...

**Comment by vberegovoy** [comment]
Getting same issues.
Please help.

**Comment by andersmandersen** [comment]
We had a simular issue, and created the following bug report, which has been closed: 
https://github.com/dooboolab/react-native-iap/issues/227

**Comment by Cnordbo** [comment]
Same issue here! This is critical! 

Locally and in Testflight, everything is correct.

**Comment by hyochan** [comment]
@Cnordbo I don't think you are on the same issue because to re-purchase the item, you should make it as `consumable`.

**Comment by hyochan** [comment]
@Cnordbo Oh, I see. Yes, then you are on right track. Unfortunately, since I may not dig this problem for a while, I think you need someone else's help or dig yourself with this issue.

**Comment by hyochan** [comment]
Have you guys tried ‘getAvailablePurchases’?

**Comment by ming436534** [comment]
I almost forget I still keep this issue open. I can share how I 'solved' the problem. As I really didn't know how to fix this issue and only one of our user has this problem, I told the user to refund. The user refunded successfully and magically calling getPurchaseHistory from his phone was not returning empty array anymore but an array with one result(which showed that the order was refunded). Therefore this maybe a problem of apple iap server.

**Comment by Cnordbo** [comment]
@hyochan Your right, i am on another issue. But it could be the same... As im using getAvailablePurchases.. Heres my code for restoring: 

```js 
const restorePurchases = () => {
  return new Promise((resolve, reject) => {
    RNIap.getAvailablePurchases()
      .then(purchases => {
        let result = purchases.some(purchase => {
          return purchase.productId === itemSkus.premium;
        });
        if (result) {
          setPremium().then(resolve);
        } else {
          unsetPremium().then(() => {
            reject({ message: `No previous purchases (${purchases.length})` });
          });
        }
      })
      .catch(err => {
        return unsetPremium().then(() => reject(err));
      });
  });
};
```

**Comment by hyochan** [comment]
@Cnordbo This one looks quite weird even in finding out the actual symptoms. I think it would be nice if we can get some answers out of `Apple` like what we've done in #307.

**Comment by Cnordbo** [comment]
That would be nice, yes. Im too unfamiliar with the iOS purchase process myself to write such a request on the forum. Might be quicker if someone whos familiar with the code and process takes a look.

**Comment by Andy10Levels** [comment]
I'am sorry, but my English is bad(

I think, you don't close transaction,  if you have "This is already bought inside the app, it will be restored for free".

> Same issue here! This is critical as it makes eveyrone unable to restore purchases unless the app i tied up to a user account.
> 
> Locally and in Testflight, everything is correct.
> 
> Array has a length of 0, and if you try to buy the product again, it fails to do so and Apple throws an error because its already been purchased.
> 
> `(0)` indicates the length of the purchase array.
> ![image](https://user-images.githubusercontent.com/385693/53103555-252d3c00-352e-11e9-84c6-8e4ae12e3e6f.png)
> 
> When trying to buy the product again:
> (Translation: This is already bought inside the app, it will be restored for free)
> ![image](https://user-images.githubusercontent.com/385693/53103671-5279ea00-352e-11e9-8be8-b207868d177d.png)

**Comment by Cnordbo** [comment]
"ghosts" account is deleted, so cant get any further with that info.

**Comment by ming436534** [comment]
This problem still happens occasionally, is there any updates? Thanks.

**Comment by ming436534** [comment]
It seems that I solved the problem by calling clearTransaction before every call of buySubscription, users who had the problem can now re-purchase again without costing any extra money because apple won't charge them again.
