### ISSUE TITLE
validateReceiptAndroid always returns undefined

### ISSUE THREAD

**Issue by ramondelmondo** [dooboolab/react-native-iap#393]
### Version of react-native-iap
2.4.0-beta6

### Version of react-native
0.57.8

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
When I try to use validateReceiptAndroid, I expected an object like this:
{
  "kind": "androidpublisher#subscriptionPurchase",
  "startTimeMillis": long,
  "expiryTimeMillis": long,
  "autoRenewing": boolean
}

### Actual behavior
validateReceiptAndroid always returns undefined

### Tested environment (Emulator? Real Device?)
Real Device (Moto G5 Plus)

### Steps to reproduce the behavior
let accessToken = "460530446560-9ueadkhvjrh1rh93roaso56fnu49ir78.apps.googleusercontent.com"; (clientId OAuth 2.0 from google api)
const purchase = await RNIap.buySubscription(itemSubs[sku]);
let decodedReceipt = await RNIap.validateReceiptAndroid('com.ourPackage', purchase.productId, purchase.purchaseToken, accessToken, true);

**Comment by hyochan** [comment]
Have you gone through [readme](https://github.com/dooboolab/react-native-iap#receipt-validation)?

**Comment by ramondelmondo** [comment]
Yes, I followed the steps of this [post](https://stackoverflow.com/questions/35127086/android-inapp-purchase-receipt-validation-google-play?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by hyochan** [comment]
There is nice [post](http://blog.naver.com/PostView.nhn?blogId=gusrn1423&logNo=221352943668&categoryNo=50&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=search&userTopListOpen=true&userTopListCount=5&userTopListManageOpen=false&userTopListCurrentPage=1) written in Korean about this. I'll try to translate this after the confirm made by the author. Hope you could use the google translation for this beforehand.

**Comment by hyochan** [comment]
Closing this for now since this isn't actually a bug or anything.
