### ISSUE TITLE
'IAPPromotionObserver.h' file not found

### ISSUE THREAD

**Issue by TylerIlunga** [dooboolab/react-native-iap#395]
### Version of react-native-iap
2.4.0-beta12

### Version of react-native
^0.55.4

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
"Build succeeded"

### Actual behavior
"Build failed"
'IAPPromotionObserver.h' file not found

### Tested environment (Emulator? Real Device?)
Never gets to this stage due to the build failing

### Steps to reproduce the behavior
- Manual Installation
- CMD+B

**Comment by hyochan** [comment]
@neilco Could you help this one out?

**Comment by neilco** [comment]
@TylerIlunga Does the **Header Search Paths** build setting in Xcode contain `$(SRCROOT)/../node_modules/react-native-iap/ios`? If not, add it and then rebuild.

**Comment by hyochan** [comment]
#417 Will this help you? I'll close this for now because this doesn't seem to relate to our module.
