### ISSUE TITLE
react-native-iap:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by KDVL** [dooboolab/react-native-iap#396]
I want to update my application but i can't. Compliation failed 

### Version of react-native-iap
2.3.26

### Version of react-native
0.56.1"

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
./gradlew assembleRelease

### Actual behavior

> Task :react-native-iap:compileReleaseJavaWithJavac FAILED
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:15: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.Arguments;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:16: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.LifecycleEventListener;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:17: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactApplicationContext;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:18: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactContext;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:19: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactContextBaseJavaModule;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:20: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactMethod;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:21: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.Promise;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:41: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReadableArray;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:42: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.WritableArray;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:43: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.WritableMap;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:45: error: cannot find symbol
public class RNIapModule extends ReactContextBaseJavaModule {
                                 ^
  symbol: class ReactContextBaseJavaModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:63: error: cannot find symbol
  private HashMap<String, ArrayList<Promise>> promises = new HashMap<>();
                                    ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:65: error: cannot find symbol
  private ReactContext reactContext;
          ^
  symbol:   class ReactContext
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:79: error: cannot find symbol
  LifecycleEventListener lifecycleEventListener = new LifecycleEventListener() {
  ^
  symbol:   class LifecycleEventListener
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:103: error: cannot find symbol
  public RNIapModule(ReactApplicationContext reactContext) {
                     ^
  symbol:   class ReactApplicationContext
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:109: error: cannot find symbol
  private void ensureConnection (final Promise promise, final Runnable callback) {
                                       ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:151: error: cannot find symbol
  public void initConnection(final Promise promise) {
                                   ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:161: error: cannot find symbol
  public void endConnection(final Promise promise) {
                                  ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:176: error: cannot find symbol
  public void refreshItems(final Promise promise) {
                                 ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:206: error: cannot find symbol
  public void getItemsByType(final String type, final ReadableArray skus, final Promise promise) {
                                                      ^
  symbol:   class ReadableArray
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:206: error: cannot find symbol
  public void getItemsByType(final String type, final ReadableArray skus, final Promise promise) {
                                                                                ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:254: error: cannot find symbol
  public void getAvailableItemsByType(final String type, final Promise promise) {
                                                               ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:316: error: cannot find symbol
  public void getPurchaseHistoryByType(final String type, final Promise promise) {
                                                                ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:358: error: cannot find symbol
  public void buyItemByType(final String type, final String sku, final String oldSku, final Integer prorationMode, final Promise promise) {
                                                                                                                         ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:400: error: cannot find symbol
  public void consumeProduct(final String token, final Promise promise) {
                                                       ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:448: error: cannot find symbol
  private void rejectPromiseWithBillingError(final Promise promise, final int responseCode) {
                                                   ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:510: error: cannot find symbol
  private void addPromiseForKey(final String key, final Promise promise) {
                                                        ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:8: error: package com.facebook.react does not exist
import com.facebook.react.ReactPackage;
                         ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:9: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.NativeModule;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:10: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactApplicationContext;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:11: error: package com.facebook.react.uimanager does not exist
import com.facebook.react.uimanager.ViewManager;
                                   ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:12: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.JavaScriptModule;
                                ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:13: error: cannot find symbol
public class RNIapPackage implements ReactPackage {
                                     ^
  symbol: class ReactPackage
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:14: error: cannot find symbol
  public List<Class<? extends JavaScriptModule>> createJSModules() {
                              ^
  symbol:   class JavaScriptModule
  location: class RNIapPackage
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:19: error: cannot find symbol
  public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
                                              ^
  symbol:   class ReactApplicationContext
  location: class RNIapPackage
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:19: error: cannot find symbol
  public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
              ^
  symbol:   class ViewManager
  location: class RNIapPackage
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:24: error: cannot find symbol
  public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
                                                ^
  symbol:   class ReactApplicationContext
  location: class RNIapPackage
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:24: error: cannot find symbol
  public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
              ^
  symbol:   class NativeModule
  location: class RNIapPackage
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:150: error: cannot find symbol
  @ReactMethod
   ^
  symbol:   class ReactMethod
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:160: error: cannot find symbol
  @ReactMethod
   ^
  symbol:   class ReactMethod
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:175: error: cannot find symbol
  @ReactMethod
   ^
  symbol:   class ReactMethod
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:205: error: cannot find symbol
  @ReactMethod
   ^
  symbol:   class ReactMethod
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:253: error: cannot find symbol
  @ReactMethod
   ^
  symbol:   class ReactMethod
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:315: error: cannot find symbol
  @ReactMethod
   ^
  symbol:   class ReactMethod
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:357: error: cannot find symbol
  @ReactMethod
   ^
  symbol:   class ReactMethod
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:399: error: cannot find symbol
  @ReactMethod
   ^
  symbol:   class ReactMethod
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:79: error: cannot find symbol
  LifecycleEventListener lifecycleEventListener = new LifecycleEventListener() {
                                                      ^
  symbol:   class LifecycleEventListener
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:145: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:227: error: cannot find symbol
            WritableArray items = Arguments.createArray();
            ^
  symbol: class WritableArray
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:227: error: cannot find symbol
            WritableArray items = Arguments.createArray();
                                  ^
  symbol: variable Arguments
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:230: error: cannot find symbol
              WritableMap item = Arguments.createMap();
              ^
  symbol: class WritableMap
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:230: error: cannot find symbol
              WritableMap item = Arguments.createMap();
                                 ^
  symbol: variable Arguments
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:271: error: cannot find symbol
        WritableArray items = Arguments.createArray();
        ^
  symbol: class WritableArray
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:271: error: cannot find symbol
        WritableArray items = Arguments.createArray();
                              ^
  symbol: variable Arguments
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:288: error: cannot find symbol
            WritableMap item = Arguments.createMap();
            ^
  symbol: class WritableMap
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:288: error: cannot find symbol
            WritableMap item = Arguments.createMap();
                               ^
  symbol: variable Arguments
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:331: error: cannot find symbol
            WritableArray items = Arguments.createArray();
            ^
  symbol: class WritableArray
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:331: error: cannot find symbol
            WritableArray items = Arguments.createArray();
                                  ^
  symbol: variable Arguments
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:334: error: cannot find symbol
              WritableMap item = Arguments.createMap();
              ^
  symbol: class WritableMap
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:334: error: cannot find symbol
              WritableMap item = Arguments.createMap();
                                 ^
  symbol: variable Arguments
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:359: error: cannot find symbol
    final Activity activity = getCurrentActivity();
                              ^
  symbol:   method getCurrentActivity()
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:434: error: cannot find symbol
      WritableMap item = Arguments.createMap();
      ^
  symbol: class WritableMap
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:434: error: cannot find symbol
      WritableMap item = Arguments.createMap();
                         ^
  symbol: variable Arguments
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:511: error: cannot find symbol
    ArrayList<Promise> list;
              ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:516: error: cannot find symbol
      list = new ArrayList<Promise>();
                           ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:525: error: cannot find symbol
      ArrayList<Promise> list = promises.get(key);
                ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:526: error: cannot find symbol
      for (Promise promise : list) {
           ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:535: error: cannot find symbol
      ArrayList<Promise> list = promises.get(key);
                ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:536: error: cannot find symbol
      for (Promise promise : list) {
           ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:545: error: cannot find symbol
      ArrayList<Promise> list = promises.get(key);
                ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:546: error: cannot find symbol
      for (Promise promise : list) {
           ^
  symbol:   class Promise
  location: class RNIapModule
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:18: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:23: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapPackage.java:25: error: cannot find symbol
    List<NativeModule> modules = new ArrayList<>();
         ^
  symbol:   class NativeModule
  location: class RNIapPackage
Note: /Users/kevin/Documents/ReactNative/GameQuestion/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
74 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-iap:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by hyochan** [comment]
We need more information to help you out. Please try other native modules and see if this actually is a problem from our module. There are several issues that aren't related to this which actually comes from `react-native` bridge.

**Comment by KDVL** [comment]
@hyochan thank's for your response.
Yes, the bridge package isn't find, do you know why ?

**Comment by hyochan** [comment]
I think you should better ask this kind of question in `stackoverflow` because there are more people watching to answer to your question. Also, I'd like to know your specific environment like are you using `expo`? What other native modules you using? and etc.. <== (better post in addition to reducing writing thread when you also post a new question.)
