### ISSUE TITLE
How to get response from IAP if payment made by Redeem Code.

### ISSUE THREAD

**Issue by ganeshzehntech** [dooboolab/react-native-iap#400]
I used the react-native-iap and works when buy my non consumable product with debit or credit card in iOS and Android for my application.
But I want to buy with Reedem Code option on IAP popup for buy product .
I didn't find anything that how can we set this , either we need to use another methods or packages to get the success response or in the same method we can get the response after Reedem Code.
I want to implement this coupon code functionlaity for both Android and iOS.
We have Coupon Code available and since this can be test in live mode as well.
How can we do this in React Native IAP, please help me into this.

Reference Native Android Link here : 
[https://developer.android.com/google/play/billing/billing_onetime#Implement-promo](url)

Regards
Ganesh

**Comment by hyochan** [comment]
I think this isn't covered yet in our module.

**Comment by ganeshzehntech** [comment]
Okay, but I found something in current version:
Image was taken from the section from https://www.npmjs.com/package/react-native-iap
What is this related it's not related to buying a product with redeem code 

![image](https://user-images.githubusercontent.com/40742110/53154339-8ca3c400-35e0-11e9-91cd-9efaa2ca0d7b.png)

Please let me know on this, I hope you understand what I am saying...
One more reference link https://bitwaretechnologies.com/app-purchase-android/
We need to do the same in React Native for both iOS and Android.

Thanks

**Comment by hyochan** [comment]
Yeah, this currently only supports ios.

**Comment by ganeshzehntech** [comment]
> Yeah, this currently only supports ios.

So if user Redeem(will generate from apple ) Code in iOS, we can buy the product in free, if user Redeem Code for my App and get the response after successfully buy...
I'll get the response into the following listener :

> IAPEmitter.addListener('iap-promoted-product', async () => {
  // Check if there's a persisted promoted product
  const productID = await RNIap.getPromotedProduct();
  if (productID !== null) { // You may want to validate the product ID against your own SKUs
    try {
      await RNIap.buyPromotedProduct(); // This will trigger the App Store purchase process
    } catch(e) {
      console.warn(e);
    }
  }
});

Please let me know on this.
Many thanks for the reply :)

**Comment by EightPool** [comment]
As far as I understand, RNIap.getPromotedProduct() allows users to buy your promoted products directly from the App Store. They click on a promo banner you created, it opens your app and fires the IAP. It is not used for "Redeem code". See more here:https://developer.apple.com/app-store/promoting-in-app-purchases

Actually, you don't need any listener. When a user redeem a code from the App Store or Play Store it will go to their purchase inventory. Just launch RNIap.getAvailablePurchases() on app opening to get products they redeemed.

**Comment by ganeshzehntech** [comment]
Hello @EightPool 
I am using RNIap.buyProduct() an then IAP popups open in Android and iOS now after that user enter Redeem Code either on Android and iOS(need to know on popup if option appears) , and then after done, we will not get any response in the same method ?
Because for this RNIap.getPromotedProduct() I need to develop functionality that how user want to go with payment before IAP.
So the method I am using , we can't get transaction response ?

Thank you :)

**Comment by EightPool** [comment]
> user choose the option of redeem payment method on IAP popup and enter Redeem Code either on Android and iOS(need to know on popup if option appears) , and then after done, we will not get any response in the same method ?

If a user uses a code in the IAP popup instead of credit card, it will be handled the same way and unlock your IAP. You don't get any response?

**Comment by ganeshzehntech** [comment]
I don't know the response yet, but when we try to buy them from live App and use Code the functionality not worked as expected, I'll try to get respond in an alert box, I'll live app again and check the response. I'll keep you posted here on the same.
Thank you :)

**Comment by lc3t35** [comment]
This is the error we have when we use a redeem code ...
![CEC53314-7472-4535-9BBD-5A5AC781694A](https://user-images.githubusercontent.com/921372/54499918-b1593600-4917-11e9-9a30-1ec070b88d51.jpg)

**Comment by rizzomichaelg** [comment]
Fixed in #490.
Promo codes trigger the purchase but don't complete it, so their transaction state is "SKPaymentTransactionStatePurchased". 

This pull just checks for the transaction state being SKPaymentTransactionStatePurchased.

**Comment by LectricAvenue** [comment]
Hey guys,

Forgive me if this is the wrong place, but this is the only place that I have found discussion about using promo codes redeemed through the app store. It might be helpful to add some information promo codes to the documentation (not promoted products)

What method has #490 changed? My IAPs are working, but the promo codes are not. All of my IAPs are subscriptions, and the promo code is - of course - for a subscription as well. 

Is the promo code treated as a consumable even if it is for a subscription?

**Comment by Metroxe** [comment]
Is there any further update on this, I am still also having an issue getting promo codes that were redeemed through the app store.

**Comment by lucidlive** [comment]
Would also like some information on this...

**Comment by v-khast** [comment]
maybe I got something wrong, but why the issue is closed? I think it hasn't been resolved.
is there any further update on this?

**Comment by jkz27** [comment]
Any update on this?

**Comment by chetan-sharma-newput** [comment]
Why is there no support for redeeming promo codes in the app on android till now? Is there a technical reason?

**Comment by mikgross** [comment]
Dear IAP Hub, as a paying customer, we would like to have you add this feature. 2 years already without moving on the matter?

**Comment by iaphub** [comment]
Hi @mikgross, if you're using the iaphub library you can post an issue [here](https://github.com/iaphub/react-native-iaphub/issues) or contact our support (support@iaphub.com).
We're having this feature on the roadmap, redeeming android promo codes should work but we currently do not have an event that you could listen to on the client to detect when it happens, it'll come in a future release.

**Comment by bperlman** [comment]
This appears to still be an issue - did anyone find a solution for this?

**Comment by andresesfm** [comment]
On android the promo code is handled by the native UI, not related to this library: 
https://developer.android.com/google/play/billing/promo
