### ISSUE TITLE
App/Bundle ID mismatch results in empty response for getProducts/getSubscriptions

### ISSUE THREAD

**Issue by mrozilla** [dooboolab/react-native-iap#401]
### Version of react-native-iap
`2.4.0`

### Version of react-native
`0.58.3`

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
I'm torn between an error saying none of the requested `itemSkus` could be found and the current behaviour.

### Actual behavior
An empty array is returned

### Tested environment (Emulator? Real Device?)
Both

### Steps to reproduce the behavior
In general, calling for a `productId` that cannot be found in the store, further explanation below

### Further context
I've just spent a considerable amount of time banging my head trying to figure out why is my app returning only an empty array from the store. Let's say I wanted to load a productID `com.example.app.premium.1month` for an app/bundle ID `com.example.app`.

I completely forgot that my dev app is using a different app/bundle ID (to allow for the prod and the dev version to be installed on the same phone) and when calling getSubscriptions from the app/bundle ID `com.example.dev`, the `com.example.app.premium.1month` is (understandably) not returned.

I wanted to get your opinion if it makes sense to add an error message, otherwise I'd just make a PR making a note about this in the docs.

And cheers for the package and the time you're investing in it 🙌

**Comment by tmjordan** [comment]
@mrozilla I have the same problem, i always receive an empty array, and i don't understand why.

**Comment by hyochan** [comment]
@mrozilla If the package name is different from what has been created in `store`, of course, you won't get products correctly. If you want any additional doc to improve, it is always welcomed.

**Comment by hyochan** [comment]
Same issue in #407
