### ISSUE TITLE
Should Podspec point to master or to the release tag?

### ISSUE THREAD

**Issue by abdielou** [dooboolab/react-native-iap#404]
I'm not sure if this is a problem or not. The Podspec points to master and not to the release tag. Isn't this problematic when building with older versions? When you install/update the pods, it will grab whatever is the latest, right? But, what if I'm running an older version?

https://github.com/dooboolab/react-native-iap/blob/b3cac16377c9ea4b66cbde701a65e7cc08efb36f/RNIap.podspec#L13

**Comment by hyochan** [comment]
We've not yet configured `release` branch. I will handle this.

**Comment by abdielou** [comment]
@hyochan Quick question on this. Why set this to `stable` branch instead of the actual version tag?

**Comment by hyochan** [comment]
@abdielou Oh you are right. So you want this to be something like below.
```
s.source         = { :git => 'https://github.com/dooboolab/react-native-iap', :tag => "v#{s.version}" }
```

**Comment by hyochan** [comment]
@abdielou Do you mind giving us a `PR` as above if this fits your needs?

**Comment by abdielou** [comment]
@hyochan thanks. Let me test out your suggestion and I'll push the PR
