### ISSUE TITLE
Results in empty response for getProducts!

### ISSUE THREAD

**Issue by 13ArturBruno** [dooboolab/react-native-iap#407]
### Version of react-native-iap
 "react-native-iap": "^2.4.1",

### Version of react-native 
RN 0.53+

### Platforms you faced the error (IOS or Android or both?)
 IOS

### Expected behavior
I need to implement and test this functionality in an app that I'll need to upload to apple connect

### Actual behavior
results in empty response for getProducts

### Tested environment (Emulator? Real Device?)
both

### Steps to reproduce the behavior

my app information:
![captura de tela 2019-02-21 as 10 59 31](https://user-images.githubusercontent.com/32041225/53176393-bf43c180-35cc-11e9-90d4-cf3a4401c8a8.png)

my product information:
![captura de tela 2019-02-21 as 10 59 46](https://user-images.githubusercontent.com/32041225/53176416-c965c000-35cc-11e9-8e84-1389c40ed876.png)

 i try with this code :
```lang-js
const itemSkus = Platform.select({
  ios: [
    'br.com.ousesaber.innap.usuariopremium'
  ],
  android: [
    'br.com.ousesaber.innap.usuariopremium'
  ]
});
```

```lang-js
getItems = async() => {
    try {
      const products = await RNIap.getProducts(itemSkus);
      // const products = await RNIap.getSubscriptions(itemSkus);
      console.log('Products', products);
      this.setState({ productList: products });
    } catch (err) {
      console.warn(err.code, err.message);
    }
  }
```
output:
```lang-js
Products Array []
```

I've been having enough problems with this, can anyone help me?

**Comment by hyochan** [comment]
@13ArturBruno Please check the [readme](https://github.com/dooboolab/react-native-iap#invalid-productid-in-ios)? If not, please try the steps then come back.

**Comment by marcusrall** [comment]
Did you find out what could be happening?

**Comment by 13ArturBruno** [comment]
My error has been solved! Just had pended on the agreements and tax.

**Comment by tmjordan** [comment]
Hi everyone, I have the same problem. I always get an empty array when calling getProducts

**Comment by tmjordan** [comment]
@hyochan @13ArturBruno

**Comment by hyochan** [comment]
Please check the `readme` I've referred above and `agreements and tax`.

**Comment by tmjordan** [comment]
@hyochan i have to put my bank account information, and have an active state on paid applications contracts? If yes i will do it later.
But even on android i also receive an empty array.

**Comment by hyochan** [comment]
@tmjordan Android takes max 24hours to make it work if you've just uploaded purchase items.

**Comment by tmjordan** [comment]
Ok thank you very much man, i will wait and i will let you know :)

**Comment by tmjordan** [comment]
Hi @hyochan, i have succeed to make it work on iOS, but still nothing on android, still getting an empty array.  To test I'm using an android emulator with google play. Not sur if it is related.

**Comment by dhamnesh** [comment]
I am facing the same issue, getting an empty array from the getProducts() method. 

react-native-iap - 2.4.8 & react native version - 0.56.0.

How to resolve it?

**Comment by dani-z** [comment]
@hyochan I was using `InAppUtils` module and the products were coming just fine, so I guess all the setup in Apple connect is OK. 
But when I use `getProducts` I'm getting an empty array.

Using latest RN (0.60) and latest RNIap.

**Comment by emrecanozkok** [comment]
@dani-z did you fix this problem.me too getting empty array 
this is my simplest code

`const itemSkus = Platform.select({
  ios: [],
  android: ['1_number_weekly', 'one_number_weekly', 'two_number_weekly'],
});

async componentDidMount() {
    try {
      await RNIap.initConnection();
      console.log(itemSkus);
      const products = await RNIap.getSubscriptions(itemSkus);
      this.setState({products});
      console.log('products', products);
    } catch (err) {
      console.warn(err); // standardized err.code and err.message available
    }
  }`

console log is 

`["1_number_weekly", "one_number_weekly", "two_number_weekly"]
[Wed Aug 12 2020 13:45:29.765]  LOG      products []`
