### ISSUE TITLE
Clarify InitConnection's return value in ReadMe

### ISSUE THREAD

**Issue by wasedaigo** [dooboolab/react-native-iap#408]
ReadMe says InitConnection returns ```string```
Could you please clarify this? I assume it returns "true"/"false" as string. Why don't we return bool?

**Comment by hyochan** [comment]
`initConnection` will only have `resolved` state or `rejected` state which means it doesn't matter whether the value is boolean or string. If it is `resolved` then it returns successfully. It currently returns `string` in case if enhancement (there could be more states we could handle in the future).

**Comment by wasedaigo** [comment]
@hyochan I do not think that is correct. InitConnection is calling CanPayment internally, right? The result is either "true" or "false". I do not see any rejection here.
https://github.com/dooboolab/react-native-iap/blob/master/ios/RNIapIos.m#L113
