### ISSUE TITLE
From TransactReceipt in IOS return a giant Hash ?

### ISSUE THREAD

**Issue by 13ArturBruno** [dooboolab/react-native-iap#410]
### Version of react-native-iap
"^2.4.1"
### Version of react-native
0.55+
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
I was expecting the receipt to really
### Actual behavior
From TransactReceipt in IOS return a giant Hash
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior

![captura de tela 2019-02-25 as 10 45 03](https://user-images.githubusercontent.com/32041225/53344382-55d7f180-38f1-11e9-9d2d-b498147edce7.png)

this return its correct ?

**Comment by hyochan** [comment]
Yes looks expected.
