### ISSUE TITLE
introductoryPriceNumberOfPeriodsIOS is wrong

### ISSUE THREAD

**Issue by gerbus** [dooboolab/react-native-iap#411]
### Version of react-native-iap
`^2.4.1`

### Version of react-native
`https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz`

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
`introductoryPriceNumberOfPeriodsIOS` in the subscription array is right (shows 2 as I have specified in App Store Connect).

### Actual behavior
`introductoryPriceNumberOfPeriodsIOS` in the subscription array is wrong (shows 1, not 2 as specified in App Store Connect).

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
1. Set up a subscription in App Store Connect
2. Add an introductory price
3. Select free
4. Specify 2 months
5. Run `RNIap.getSubscriptions(...)` from app and look at `introductoryPriceNumberOfPeriodsIOS` key/value.

**Comment by sck-v** [comment]
Created pull request with fix #454
