### ISSUE TITLE
buySubscription on iOS failing multiple times for users

### ISSUE THREAD

**Issue by noahhayes** [dooboolab/react-native-iap#412]
### Version of react-native-iap
2.2.2

### Version of react-native
0.57

### Expected behavior
Error message should distinguish between user cancelling purchase and user experiencing an error. 

### Actual behavior
I'm noticing that a large number of my users are getting an error when attempting to purchase a subscription. In my error logs, I'm seeing the CANCELLED error message when they try to buy.  Of course, many of these users could actually be cancelling their transaction. However, I'm curious to dig into this further because there are many users that attempt to make the purchase multiple times. For example, some users will press purchase 4 times in a row and are not able to complete the transaction--they all show the CANCELLED error message. I can't figure out if they are just confused and cancelling the purchase or if it's breaking due to an unknown error.

Attached is roughly the code I'm using.

[RegisterActivate2.txt](https://github.com/dooboolab/react-native-iap/files/2908675/RegisterActivate2.txt)

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
I can't reproduce it myself. I'm only seeing the activity through logging.

**Comment by domhadfield** [comment]
OK, I can add more information as we are having the same issue.

Users are all on iOS 12.4.1.

The error is being returned from the store after calling: `RNIap.buySubscription(productId)`

The error that is returned is: `Invalid product ID.`

**Comment by hyochan** [comment]
Actually, this `PR` was updated in #291. Apple doesn't seem to provide the correct `error` message natively (if I am correct). But then if we revert the `PR` it will provide only `Enligsh` error message. @mars-lan Hope you can look at this if you are available.

**Comment by noahhayes** [comment]
Thanks @hyochan

Is there anything I’m doing obviously wrong in the attached code?

I saw someone commented that it may be caused by an Invalid Product ID. Are there any gotchas that I may be missing regarding Product ID? 

It’s strange to me because it works fine for me in the US but breaks for users in Vietnam, Cambodia and other countries.

**Comment by hyochan** [comment]
@noahhayes I've briefly saw your code and seems to look ok. I'd suggest you to use `componentDidMount` instead `componentWillMount` tough.

I hope you to check some tax agreement for `Vietnam, Cambodia or other countries` if you are facing issue in ios.

**Comment by mars-lan** [comment]
> Actually, this `PR` was updated in #291. Apple doesn't seem to provide the correct `error` message natively (if I am correct). But then if we revert the `PR` it will provide only `Enligsh` error message. @mars-lan Hope you can look at this if you are available.

I believe the original question has nothing to do with the localized description, but the actual error code ([SKErrorPaymentCancelled](https://developer.apple.com/documentation/storekit/skerrorcode?language=objc) that got mapped to the standardized "E_USER_CANCELLED" [here](https://github.com/dooboolab/react-native-iap/pull/291/files#diff-5879a701decbc95a12d5125526d5b411R292)).  #291 didn't touch that part of the code so reverting it won't address the issue.

**Comment by hyochan** [comment]
@mars-lan Thanks for confirming. I did not had time to look through that. I'll come back when I'll be available.

**Comment by edo1493** [comment]
I have something similar where they go through the flow, have to change payment method (for example) and then the component doesn't return anything after the transaction is completed.

In this case, we make them restore the purchases and everything is fine.

**Comment by hyochan** [comment]
@edo1493 Could you provide some codes? Do you mean you've just called `getAvailablePurchases` to solve this issue?
