### ISSUE TITLE
Get Expire date for both android & ios subscription

### ISSUE THREAD

**Issue by Friis1978** [dooboolab/react-native-iap#419]
Hello everyone, 

I had a hard time figuring out how to get the expiration dates for the subscriptions, I have search many different places, tried also to use the Googlesignin repo, but nothing seems to work. When signing in on my Service accont, connected to my application, I expected to get access to the data, but gets a Error 401, after this I thought I could use the rest api for googleplay, but found no documentation to React Native ? 

I found this method RNIap.validateRecieptAndroid, but I dont know where to get accessToken to the method, something I missed ?

Can someone perhaps give me a full example to get the data I need ? 

Please, please Help me....

**Comment by hyochan** [comment]
I've not used local validation for `android`. I recommend you to you can validate from the `server-side`  and [this](https://github.com/voltrue2/in-app-purchase) might help.

**Comment by Friis1978** [comment]
Wow, many thanks hyochan, I will try to give that a try.

Are you saying that you will do something simular in your repository ? 
and document it also ? In the case, what version is that ?

**Comment by hyochan** [comment]
@Friis1978 [in-app-purchase](https://github.com/voltrue2/in-app-purchase/issues) library will not be included, this is different spec.

**Comment by hyochan** [comment]
@Friis1978 I've found useful link for your `question` which is written in Korean. See [Link](http://blog.naver.com/PostView.nhn?blogId=gusrn1423&logNo=221352943668&categoryNo=50&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=search&userTopListOpen=true&userTopListCount=5&userTopListManageOpen=false&userTopListCurrentPage=1) and see if this can help you with `google translation`.

**Comment by Friis1978** [comment]
Hei @hyochan I really appreciate your help, 

I found a link myself, where the author was also looking for a solution, and the answer was also to use a firebase function, which was also what your example sugested. 

For any interested people, I copy pasted the code, which is working perfect. 
`const functions = require('firebase-functions');
const jwt = require('jsonwebtoken');
const keyData = require('./key.json');         // Path to your JSON key file
const request = require('request-promise');

/** 
 * Exchanges the private key file for a temporary access token,
 * which is valid for 1 hour and can be reused for multiple requests
 */
function getAccessToken(keyData) {
  // Create a JSON Web Token for the Service Account linked to Play Store
  const token = jwt.sign(
    { scope: 'https://www.googleapis.com/auth/androidpublisher' },
    keyData.private_key,
    {
      algorithm: 'RS256',
      expiresIn: '1h',
      issuer: keyData.client_email,
      subject: keyData.client_email,
      audience: 'https://www.googleapis.com/oauth2/v4/token'
    }
  );

  // Make a request to Google APIs OAuth backend to exchange it for an access token
  // Returns a promise
  return request.post({
    uri: 'https://www.googleapis.com/oauth2/v4/token',
    form: {
      'grant_type': 'urn:ietf:params:oauth:grant-type:jwt-bearer',
      'assertion': token
    },
    transform: body => JSON.parse(body).access_token
  });
}

/**
 * Makes a GET request to given URL with the access token
 */
function makeApiRequest(url, accessToken) {
  return request.get({
    url: url,
    auth: {
      bearer: accessToken
    },
    transform: body => JSON.parse(body)
  });
}

// Our test function
exports.testApi = functions.https.onRequest((req, res) => {
  // TODO: process the request, extract parameters, authenticate the user etc

  // The API url to call - edit this
  const url = `https://www.googleapis.com/androidpublisher/v2/applications/${packageName}/purchases/subscriptions/${subscriptionId}/tokens/${token}`;

  getAccessToken(keyData)
    .then(token => {
      return makeApiRequest(url, token);
    })
    .then(response => {
      // TODO: process the response, e.g. validate the purchase, set access claims to the user etc.
      res.send(response);
      return;
    })
    .catch(err => {
      res.status(500).send(err);
    });
});`

The code was taken from this question: [https://stackoverflow.com/questions/49836166/call-google-play-developer-api-from-firebase-functions](url)

From google, here is some documentation also: [https://developers.google.com/identity/protocols/OAuth2ServiceAccount](url)

**Comment by thodwris** [comment]
You put this code on your backend or on your react native code?

**Comment by Friis1978** [comment]
@thodwris I use this as a firebase function that will run, when a new subscription is saved from the user.

**Comment by thodwris** [comment]
@Friis1978  
Where does the firebase function live? It's not on react native code?

**Comment by tomerdev** [comment]
I would recommend using [iaphub](https://www.iaphub.com) if you do not want to develop a complex system to validate receipts on the server side.
