### ISSUE TITLE
Refreshing the receipt from apple when lost?

### ISSUE THREAD

**Issue by HARISMEHMOOD** [dooboolab/react-native-iap#420]
I want to know if there's a way to check weather the subscription is already purchased against apple id even if its not available against a different user for my app.

**Comment by hyochan** [comment]
I'm not sure if this is possible. I think you should better search for support through `stackoverflow`. Currently, you can check the `receipt` and find out about it.

**Comment by EricCarrGH** [comment]
If you've lost or don't have the receipt to check,  you need to refresh the receipt from apple (receive them again) and then check it to know.

https://developer.apple.com/documentation/storekit/skreceiptrefreshrequest

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html#//apple_ref/doc/uid/TP40008267-CH8-SW9

I don't think that's available in this lib, but you could add it and do a PR :) .. I see a link to the second link above in the source code ( https://github.com/dooboolab/react-native-iap/blob/master/ios/RNIapIos.h ), perhaps it's on the list of to-dos.

**Comment by hyochan** [comment]
I've removed `question` label and renamed issue `title` since the `question` has been answered and `feature request` has been provided.

**Comment by HARISMEHMOOD** [comment]
May be I wasn't clear with my question. Apologies for that. 

What I want to do is to make sure that there's only one **Active** subscription against one Apple Id. 

Receipts are not lost or anything for us. I want to know if there's a way using react-native-iap to check weather there's already an active subscription available.

**Comment by hyochan** [comment]
@HARISMEHMOOD I think you should check out #275 for that support.
