### ISSUE TITLE
Rewarded products

### ISSUE THREAD

**Issue by uzeuze** [dooboolab/react-native-iap#421]
Google has launched a new monetization option called “Rewarded Products”. Is it easy to add it to this library?

**Read more:**
https://developer.android.com/google/play/billing/billing_rewarded_products
https://support.google.com/googleplay/android-developer/answer/9155268#enroll

**Comment by hyochan** [comment]
@uzeuze Adding new feature shouldn't matter much. However, making the test environment is quite a burden. I've just read the document and my question is how do you give rewarded products to the user? I can only see how to get it.

**Comment by SMKH-PRO** [comment]
I vote for this feature!
