### ISSUE TITLE
transactionId always "" from getPurchaseHistory

### ISSUE THREAD

**Issue by gerbus** [dooboolab/react-native-iap#424]
### Version of react-native-iap
`^2.4.1`

### Version of react-native
`https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz`

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
transactionId is not empty.

### Actual behavior
transactionId is an empty string in result:
`[{`
`  autoRenewingAndroid: false,`
`  signatureAndroid: 'LELlDZtkLgaDNLowuK9yphjvB9z8Dtlw+zM0TgcTgcztnMmPTLsrkPGDO1X30r3xtIO6exjujuKmUSJiGBX3vTzPzXdrmn5q0gqkQg6TCL2ZSC94/aIJE2zvws2GPGI02ICUCAotty2dbGiduAoE3Kf+SImcZPjoWjdh3l/mgYCzu7K+MrZmHU7F27NWPVv+RMg5q6Hzv2s7GuxYeD41BiBYHfbnTidD1EM5fu6cSivGswdFaSU8qlVNXkUNH1cKFARDE15iUrgeQQVh8KEN/dvvrcNIWNb8ICwvv9Y+wYGiC/zA/WkYCHyk/Xao0c7MRA==',`
`  purchaseToken: 'mgbaflglpllamdhkjacb.AO-J1OyLsiyKIcSz2cNQeVTlo8ghi1MKn6BmfhdAMT04ZaWE5zWtCrTlCifgGfBJKx1IaqHMOA2N_iC9PHfFPFhxa67vQP9LAnvYDzMfQXRMzv7YT5Q',`
`  dataAndroid: '{"productId":"app_000","purchaseToken":"mgbaflglpllamdhkjacb.AO-J1OyLsiyKIcSz2cNQeVTlo8ghi1MKn6BmfhdAMT04ZaWE5zWtCrTlCifgGfBJKx1IaqHMOA2N_iC9PHfFPFhxa67vQP9LAnvYDzMfQXRMzv7YT5Q","purchaseTime":1550610049162,"developerPayload":null}',`
`  transactionReceipt: '{"productId":"app_000","purchaseToken":"mgbaflglpllamdhkjacb.AO-J1OyLsiyKIcSz2cNQeVTlo8ghi1MKn6BmfhdAMT04ZaWE5zWtCrTlCifgGfBJKx1IaqHMOA2N_iC9PHfFPFhxa67vQP9LAnvYDzMfQXRMzv7YT5Q","purchaseTime":1550610049162,"developerPayload":null}',`
`  transactionDate: '1550610049162',`
`  transactionId: '',`
`  productId: 'app_000'`
`}];`

### Tested environment (Emulator? Real Device?)
Android device

### Steps to reproduce the behavior
1. Set up a subscription in App Store Connect
2. Purchase the subscription from app using RNIap.buySubscription()
3. Run RNIap.getPurchaseHistory() and look at the transactionId property of the result

**Comment by hyochan** [comment]
`getPurchaseHistory` is used only in `non-consumable` product.

**Comment by gerbus** [comment]
Thanks @hyochan. I was confused when initially reading the README about those.

**Comment by gerbus** [comment]
@hyochan actually the result of `getAvailablePurchases()` is an empty array. Is a subscription a `consumable` purchase? I thought it was `non-consumable`.

**Comment by gerbus** [comment]
I've updated Actual Behavior in case it's not clear what I'm seeing.

**Comment by hyochan** [comment]
@gerbus Sorry friend. I was confused. You are right. However, this is duplicate in #385.

**Comment by gerbus** [comment]
Hmm. Looks like the issue in #385 is a fully empty array, no? Just wanting to make sure this is in fact a duplicate of that, because for me the array is full *except* for the transactionId property.

Appreciate the prompt responses @hyochan!

**Comment by hyochan** [comment]
@gerbus Then this might not be an issue and I think this is expected since `transactionId` only appears when there is no finished transaction (which means the transaction is not done yet). [Helpful Read](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html).
