### ISSUE TITLE
Crash when I try to run/build it from Android

### ISSUE THREAD

**Issue by raynor85** [dooboolab/react-native-iap#437]
### Version of react-native-iap
2.4.4
### Version of react-native
0.57.0
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
react-native run-android should build
### Actual behavior
It fails with the error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-iap'.
> Could not resolve all files for configuration ':react-native-iap:classpath'.
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.0.0).
```

**Comment by hyochan** [comment]
I think this issue isn't related to current repo and rather you should see `react-native` build config. Please try this [one](https://github.com/react-native-community/react-native-camera/issues/2027#issuecomment-449950270).
