### ISSUE TITLE
Receipt Validation for fake purchases

### ISSUE THREAD

**Issue by losheredos** [dooboolab/react-native-iap#438]
I had big issue about fake purchases in my recent project(which I used out libraries for purchasing), people were buying premium stuff with programs like luckypatcher without paying real money. I was able to see them but needed to ban/warn them manually.

I am curious how effective is validateReceiptIos method for stopping fake purchases. I know that I can clearly check the reality of the purchase via google API but in case can I use validateReceiptIos method to stop fake purchases in some level? 

Can you please explain details about it? Thank you.

**Comment by hyochan** [comment]
This issue should be further invested to those who need this in advance. Since I've not had worked on this issue yet. Hope you can find some improvement for us (maybe through stackoverflow) and guide us.

**Comment by hyochan** [comment]
I thought you can validate receipt in ios to prevent the fake purchase. Check [this repo](https://github.com/voltrue2/in-app-purchase) and see if you can do additional problem solving. I will close this for now since I think there aren't further job currently but please feel free to reopen when you think this should be invested.

**Comment by losheredos** [comment]
Ok yeah you are right, thanks for the answers. But maybe dont close it, let it stay open so people may be more willing to write about it. I guess if we can solve this issue somehow in front end part, this may be much better because we will not need to validate purchases via google api.

**Comment by Stafox** [comment]
@losheredos If you wan't to prevent fake purchases, the only way to do that it is **server validation**. All other solutions on frontend part are not so effective.
