### ISSUE TITLE
transactionDate typing conflict with doc

### ISSUE THREAD

**Issue by jpolo** [dooboolab/react-native-iap#440]
### Version of react-native-iap
2.4.4
### Version of react-native
0.59.2 (it does not matter)
### Platforms you faced the error (IOS or Android or both?)
Both platform
### Expected behavior

In the README the documentation says :
```
transactionDate : The time the product was purchased, in milliseconds since the epoch (Jan 1, 1970).
-- | -- | -- | --
```

### Actual behavior

But in `index.d.ts` and `index.js.flow`, `transactionDate` is typed as `string` when it should be `number`.

### Steps to reproduce the behavior
Run flow, wrong errors are returned when using transactionDate

**Comment by hyochan** [comment]
Yes you are right. Do you mind give us a fix `PR` for this?

**Comment by phil-flyclops** [comment]
I believe there is a bug compounded on top of this.  On Android the transactionDate value comes back as a string, on iOS is comes back as a number.  We should change the native code to align with one another as well as the type defs

**Comment by phil-flyclops** [comment]
References

Android: 
https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L295
https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L341
https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L441

iOS:
https://github.com/dooboolab/react-native-iap/blob/master/ios/RNIapIos.m#L483

I'm down to put in a fix if folks agree that the android code should also return a number

**Comment by hyochan** [comment]
@phil-flyclops agree

**Comment by phil-flyclops** [comment]
I looked into this and it turns out that underlying react bridge code we're using only has a way to return strings and ints, but no longs
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableMap.java

Does somebody who is familiar with the underlying React Native Java code have any guidance on how to handle a case like this?

**Comment by Loopiezlol** [comment]
Hmm one potential solution can include parsing the responses on the JS side of things (like [here](https://github.com/dooboolab/react-native-iap/blob/master/index.js#L223) or [here](https://github.com/dooboolab/react-native-iap/blob/master/index.js#L192))

Not the ideal solution, but can work as to circumvent this limitation @phil-flyclops
