### ISSUE TITLE
UI translations

### ISSUE THREAD

**Issue by kavolorn** [dooboolab/react-native-iap#444]
### Version of react-native-iap

2.4.0-beta12

### Version of react-native

0.57.7

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

I expect confirmation of payment to be translated to my local language.

### Actual behavior

I see that "Cancel" button is translated and everything else is in English.

### Tested environment (Emulator? Real Device?)

iPhone 7

### Steps to reproduce the behavior

Try to change application language and launch payments for consumable product.

**Comment by hyochan** [comment]
I am not sure about this since I've not seen this in my `env`. Could you give us more information that might help to improve this repo?

**Comment by kavolorn** [comment]
@hyochan Let's try :)

Here I attach the screen which is partly translated and I'm figuring out why.

![IMG_3553 2](https://user-images.githubusercontent.com/2448274/55474160-2c5d6480-5619-11e9-8a48-729e36ed15cc.jpg)

**Comment by kavolorn** [comment]
On the screen you can see that 1) price was translated properly (75 р.) and 2) Cancel button was translated properly. Wondering why everything else is in English.

**Comment by Lucas-Geitner** [comment]
Hello, is it still an issue ?

**Comment by kavolorn** [comment]
Hi, actually we've passed Apple's validation. So I assume all is good in the production. We can close the issues.
