### ISSUE TITLE
getAvailablePurchases() does not repond on iOS.

### ISSUE THREAD

**Issue by bhs324** [dooboolab/react-native-iap#446]
### Version of react-native-iap
2.4.5

### Version of react-native
0.59.3

### Platforms you faced the error (IOS or Android or both?)
iOS, Xcode 10.2

### Expected behavior
getAvailablePurchases() should return any result.

### Actual behavior
Does not respond.

### Tested environment (Emulator? Real Device?)
Simulator and Real Device(sandbox)

### Steps to reproduce the behavior
const subscriptions = await RNIap.getSubscriptions(['sub.id1']);
console.log('subscriptions: ', subscriptions); // It's OK. subscriptions: [ { productId: 'sub.id1', ...
const purchases = await RNIap.getAvailablePurchases();
console.log('Purchases: ', purchases); // Does not respond.

This happens after update Xcode 10.2

**Comment by wasedaigo** [comment]
I might be having the same problem in production... So this issue is intersting.

Is that possible for you to add break points and see what exactly is happening? 
Is either ```paymentQueueRestoreCompletedTransactionsFinished``` or ```restoreCompletedTransactionsFailedWithError``` called?

**Comment by andersmandersen** [comment]
We're having the same problem. At first we thought the issue where only related to restoring after entering promo codes. But in the last couple of days, we're seeing this affecting other users also. 

Our original issue: https://github.com/dooboolab/react-native-iap/issues/227

We havn't been able to locate the bug, since the issue is only happening in production.

The issue is seen on a couple of diffrent iOS version. The last time it happen was on a iPhone 8 running 12.1.4

A few weeks ago we implemented sentry and updated our code to the following. But the purchases array are just empty. 
``
```javascript
let purchases = await RNIap.getAvailablePurchases();
Sentry.captureMessage("All purchases:");
Sentry.captureMessage(purchases); // Returns []
```

**Comment by wasedaigo** [comment]
@andersmandersen in your case, it seems you are getting an empty response at least. In my case it stuck at that line

@bhs324  Can you clarify what "doesn't respond" means? Does it return an empty array or it does not reach that line?

**Comment by bhs324** [comment]
@wasedaigo iOS 12.2, does not reach that line.

**Comment by bhs324** [comment]
@wasedaigo iOS 12.2. It does not reach that line.

**Comment by wasedaigo** [comment]
did you set the break point..?

**Comment by wasedaigo** [comment]
@bhs324 did you set breakpoints..?

**Comment by bhs324** [comment]
@wasedaigo paymentQueueRestoreCompletedTransactionsFinished is called and it works now!
But it works only in development mode.

In production mode, getAvailablePurchases still not working.

I runned application with this command, 'react-native run-ios --configuration Release'.

And alert not displaying with this code.
```
Alert.alert(null, 'Hello!'); // It does not reach! I called BEFORE getAvaliablePurchases.
const purchases = await RNIap.getAvailablePurchases();
```

After comment out getAvailablePurchases, alert displaying.
```
Alert.alert(null, 'Hello!');
// const purchases = await RNIap.getAvailablePurchases();
```

**Comment by wasedaigo** [comment]
I think you should use Break Point or console log instead of Alert. It is possible this is a bug of Alert itself.

**Comment by bhs324** [comment]
I tested on simulator with these steps.

1. Set break points on 'paymentQueueRestoreCompletedTransactionsFinished' and 'restoreCompletedTransactionsFailedWithError'.
2. Calls getAvaiablePurchases like this.
```
// App.js
  async componentDidMount() {
    await RNIap.getAvailablePurchases();
    // ...
```
3. Launch my app and cancel iTunes sign in.
4. restoreCompletedTransactionsFailedWithError is called.
5. App freezes.

Here is my workaround to avoid freezing.
```
// App.js
  async componentDidMount() {
    setTimeout(async() => {
      await RNIap.getAvailablePurchases();
    }, 5000); // set enough delay.
    // ...
```

**Comment by wasedaigo** [comment]
I don't think simulator is a good way to test IAP.

**Comment by EduardoASAP** [comment]
Same issue happening to me. getAvailablePurchases() get stuck.
The error occurs on last version react-native-iap@2.4.8 on iOS version 12.2
It's working for older iOS versions and on Android.

**Comment by baddboy-obn** [comment]
getAvailablePurchases()
Dosn't work for me
"react-native": "0.59.8"
"react-native-iap": "^2.5.5"
then run on device, show login appleid window, then i input apple id and password, response itunes connect error.

**Comment by Metroxe** [comment]
This seems to be the same issue at #981 .

**Comment by StefanoCremona** [comment]
I got it to work adding initConnection() and endConnection() as by @Metroxe suggested

**Comment by bhujoshi** [comment]
For me, it's not working even after using initConnection().
```
useEffect(()=>{
    (async()=>{
      try {
        const connection = await RNIap.initConnection();
        if(connection){
          const products = await RNIap.getProducts(productIds);
          console.log({products}, getAvailablePurchases)
          const details = await getPurchaseHistory(); 
          console.log({details}, '***********')
        }
      } catch(err) {
        console.warn(err); // standardized err.code and err.message available
      }
    })()

    return ()=>{ RNIap.endConnection(); }
  }, []);
```
The code stop working after ```getPurchaseHistory```. Same is happening with getAvailablePurchases

**Comment by umerhayat54** [comment]
any luck anyone Please? still facing same issue

**Comment by Accoladecreative** [comment]
Still having this same issue
