### ISSUE TITLE
Subscription period number and unit typing are inverted

### ISSUE THREAD

**Issue by jpolo** [dooboolab/react-native-iap#448]
### Version of react-native-iap
2.4.6
### Version of react-native
0.59.2
### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
```javascript
subscriptionPeriodNumberIOS?: string,
subscriptionPeriodUnitIOS?: number,
```

### Actual behavior
```javascript
subscriptionPeriodNumberIOS?: number,
subscriptionPeriodUnitIOS?: string,
```

### Steps to reproduce the behavior
`yarn flow`

I'll submit a pull request to help you out.

**Comment by hyochan** [comment]
Closed via #449. Thanks for `PR`.
