### ISSUE TITLE
In app purchase ios with promotion code

### ISSUE THREAD

**Issue by truckhiem** [dooboolab/react-native-iap#450]
### Expected behavior:
1. Redeem promotion code in store
2. Back to app and restore purchase
3. Get receipt purchase

### Actual behavior
1. Redeem promotion code in store --> success
2. Back to app and nothing happen
3. Get availablePurchase --> null
4. Get purchaseHistory --> null
5. GetPromotedProduct --> null

### Steps to reproduce the behavior
I implemented these codes follow instruction:
<img width="905" alt="Screen Shot 2019-04-07 at 11 12 14 AM" src="https://user-images.githubusercontent.com/6792318/55678548-1952d900-5926-11e9-9b8b-4c0e9d173e56.png">

I add these codes at restoreButton to get promotedProduct:
<img width="814" alt="Screen Shot 2019-04-07 at 11 20 10 AM" src="https://user-images.githubusercontent.com/6792318/55678648-78651d80-5927-11e9-8c82-8419a2f770e8.png">

Any help? Thank you.

**Comment by StefanoCremona** [comment]
@truckhiem did you solve this problem? I'm having the same issue.
I redeem the code on the app store and there's no way from the app to know anything about it.
Cheers
