### ISSUE TITLE
getProducts returns empty array in newest version RN

### ISSUE THREAD

**Issue by augustbjornberg** [dooboolab/react-native-iap#451]
### Version of react-native-iap

^2.4.7

### Version of react-native

0.59.4

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

I expect **getProducts** to return an array of available purchases.

### Actual behavior

The returned device is empty.

### Tested environment (Emulator? Real Device?)

Both.

### Steps to reproduce the behavior

```
yield RNIap.prepare()
const products = yield RNIap.getProducts(iapBundleIds(content))

console.log(iapBundleIds(content))
// ["org.truthordrink.TruthOrDrink.pack1", "org.truthordrink.TruthOrDrink.pack2", "org.truthordrink.TruthOrDrink.pack3"]
console.log(products)
// []
```

The above code in the same xcode project works correctly using:
"react-native": "0.56.0",
"react-native-iap": "^2.4.0-beta6"

**Comment by hyochan** [comment]
There are several issues related to this which are already closed. Please follow that and this should be working.

**Comment by augustbjornberg** [comment]
Only one i could find that remotely matched mine was #340, but you closed that one instantly too without any answer.

For me, everything is working great in react-native 0.56.0, but not react-native 0.59.4, can't find anything related to that. Could you point me to one of the several ones related to my ticket?

**Comment by cesarve77** [comment]
Same problem here

**Comment by andrewdazs** [comment]
Same here

**Comment by npedrini** [comment]
I'm seeing the same. Are there any plans to address what seems like a confirmed issue with 0.59.4?

**Comment by Polelo-Monareng** [comment]
Why is this issue even closed? getProducts returns empty array in react-native 0.59.8 as well.

**Comment by npedrini** [comment]
@hyochan: per your above comment that presumably resulted in this issue being closed, please kindly let us know what issues this one duplicates. 

This is the only library of its kind that I know of, AND it is not working in current versions of RN. It would be great to get a better sense of what the issue is so the community can work towards getting it resolved. We need this library!

**Comment by hyochan** [comment]
Related #407

**Comment by ManalLiaquat** [comment]
I solved it! I am using these versions,

`react-native-iap: ^4.3.0`
`react-native: 0.60.5`

just do it like this
```
const itemSkus = Platform.select({
    ios: [
        '100coins' // just remove bundle id from product id
    ],
    android: [
        '100coins' // just remove bundle id from product id
    ]
});
```
