### ISSUE TITLE
Convert existing iOS paid app to freemium model with in-app purchase

### ISSUE THREAD

**Issue by craig1123** [dooboolab/react-native-iap#453]
Hi,

I'm going from a paid app to free and am going to use this library.

Is there a method in react-native-iap that lets me know if they've already bought the app?
Thank you!

**Comment by hyochan** [comment]
Actually, I've not had time to find information about this. Hope you can post some link in this thread that may help investing this issue.

**Comment by Stafox** [comment]
@craig1123 seems you need to attach some info to user account to handle that.

**Comment by Stafox** [comment]
@craig1123 you able to detect the date when app was installed. It is an `original_purchase_date` or ` receipt_creation_date` field in the decoded receipt root.
