### ISSUE TITLE
validateReceiptAndroid returns Error

### ISSUE THREAD

**Issue by bethshook** [dooboolab/react-native-iap#458]
### Version of react-native-iap
2.4.6

### Version of react-native
0.57.1

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
validateReceiptAndroid() should return a response

### Actual behavior
Error returned that simply reads "Error"

### Tested environment (Emulator? Real Device?)
Real device. Other iap methods work on the device.

### Steps to reproduce the behavior
const purchase = await RNIap.buySubscription('my_product_code')
      if (Platform.OS === 'android') {
        const productToken = purchase.purchaseToken
        const productId = purchase.productId
        const packageName = 'my.package.name'
        API.getToken(userToken).then(response => {
          const accessToken = response.data.access_token
          const validationData = {
            packageName,
            productId,
            productToken,
            accessToken,
            isSubscription: true
          }
          // I've also tried entering params without the object
          RNIap.validateReceiptAndroid(validationData).then(response => {
            console.log(JSON.stringify(response))
          }).catch(e => console.log(e))
        }).catch(e => console.log(e))
      }

**Comment by bethshook** [comment]
I've determined that it is likely an access token issue. Would be great if this returned more detailed error messages.

**Comment by hyochan** [comment]
@bethshook Is this solved? I hope you can post some great article or link like [here written in Korean](https://github.com/dooboolab/react-native-iap/issues/393#issuecomment-472821973) to share the working example with others.

**Comment by bethshook** [comment]
@hyochan Still not solved unfortunately. For now I've removed Android receipt validation.

**Comment by thanh90** [comment]
i checked an error by rectotron and it said 'Login required' from the error response

**Comment by ChrisEelmaa** [comment]
Do not do any kind of receipt validation on client side. It's not safe and recommended. All receipt validation should be done on backend.

You do not need this library to do any kind of validation. In fact, it would be good idea to remove receipt validation from this library, as validation is not that trivial and deserves to be in a separate lib. 

Use this for backend: http://github.com/voltrue2/in-app-purchase

**Comment by thanh90** [comment]
> Do not do any kind of receipt validation on client side. It's not safe and recommended. All receipt validation should be done on backend.
> 
> You do not need this library to do any kind of validation. In fact, it would be good idea to remove receipt validation from this library, as validation is not that trivial and deserves to be in a separate lib.
> 
> Use this for backend: [http://github.com/voltrue2/in-app-purchase](https://github.com/voltrue2/in-app-purchase)

agree

**Comment by thodwris** [comment]
@bethshook 

I am stuck on this code

```
API.getToken(userToken).then(response => {
const accessToken = response.data.access_token
```

I want to get somehow the accessToken from the frontend and not occupy with the backend at all.

**Comment by hyochan** [comment]
@thodwris [This](https://github.com/voltrue2/in-app-purchase) may help you.

**Comment by vishaldhanotiya** [comment]
I have faced the same issue. I write down the solution here please check this link it may help you to solve your problem

#1217 (comment)
