### ISSUE TITLE
buySubscriptions() not responding ( iOS 12.2 )

### ISSUE THREAD

**Issue by EduardoASAP** [dooboolab/react-native-iap#461]
### Version of react-native-iap
2.4.8
### Version of react-native
0.57.4
### Platforms you faced the error (IOS or Android or both?)
iOS 12.2
### Expected behavior
We are calling buySubscription() and then it should call apple store and buy a subscription item. This was working fine in older versions.
### Actual behavior
It get stuck as we call buySubscription(). This behavior started when we updated our iOS to 12.2. Before it was working fine in both platforms iOS and Android.
### Tested environment (Emulator? Real Device?)
iOS 12.2 Real Device. On older iOS version devices is working fine.
### Steps to reproduce the behavior
```
      const subscriptions = await RNIap.getSubscriptions(itemSubscriptions);
      const sku = subscriptions[0].productId;
      let purchase = null;
      try {
        purchase = await RNIap.buySubscription(sku);
        console.log('This line is never reached!!!');
        //More code
      } catch (err) {
      }
```

**Comment by cbfranca** [comment]
Did you get some error code? I've got many E_USER_CANCELLED errors, most of in IOS 12.2.

**Comment by EduardoASAP** [comment]
> Did you get some error code? I've got many E_USER_CANCELLED errors, most of in IOS 12.2.

We were getting anything, just being stuck on line.

We are now able to pass up buySubscription line. It's working on iOS 12.2 and iOS 12.3 beta on device. Don't know what changed.

**Comment by mikedream89** [comment]
@EduardoASAP  how to fix？
