### ISSUE TITLE
Empty array of getProducts(itemSkus) in android

### ISSUE THREAD

**Issue by thodwris** [dooboolab/react-native-iap#464]
### Version of react-native-iap
2.4.9
### Version of react-native
0.57.8
### Platforms you faced the error (IOS or Android or both?)
android
### Expected behavior
To be able to retrieve the products
### Actual behavior
I get an empty array
### Tested environment (Emulator? Real Device?)
Both emulator and real device
### Steps to reproduce the behavior

I've already created an alpha version on play console and debug the app on real device.
I've created subscriptions and not managed products.
<img width="1511" alt="Screenshot 2019-04-25 at 13 38 19" src="https://user-images.githubusercontent.com/297024/56733103-78568180-675f-11e9-86cd-796195d1e02d.png">

Code 

```
const itemSkus = Platform.select({
  android: [
    'com.synesthesiameditation.yearly',
    'com.synesthesiameditation.monthly'
  ]
});
```

```
async componentDidMount() {

    try {
      await RNIap.initConnection()
      const products = await RNIap.getProducts(itemSkus);
      console.log(products)
      this.setState({ products });
    } catch (err) {
      console.warn(err); // standardized err.code and err.message available
    }

  }

  componentWillUnmount() {
    RNIap.endConnection();
  }
```

**Comment by bumjoo** [comment]
I'm also facing this problem.
[initConnection()] returns 'true' but [getProducts or getSubscriptions] returns empty array..
What/Where should I check for solving this issue?

**Comment by tmjordan** [comment]
@hyochan same problem here

**Comment by hyochan** [comment]
This will take max 24hours for your products to be available if you've just uploaded the `iap` products. If this is the case, please close the issue. @thodwris for `android`, fetching product won't even work in `emulator` (just fyi).

**Comment by thodwris** [comment]
@hyochan 
Thank you for your answer.
I've created the products over 24 hours ago.

`@thodwris for android, fetching product won't even work in emulator (just fyi).`

What does it mean? And how I will be able to retrieve them and what's the purpose of 
`RNIap.getProducts(itemSkus)`
Maybe I don't get something here.

**Comment by hyochan** [comment]
@thodwris I meant in `ios` emulator the `fetching` works but not in `android` emulator. You shouldn't test anything in `android` emulator. Also this issue feels unrelated to our module. It would help you better to look for other information related to `anrdoid` `iap` and I hope you could comeback when you have some traction.

**Comment by thodwris** [comment]
@hyochan 
To be honest I don't understand you well.

What is the purpose of this RNIap.getProducts(itemSkus) eventually, if I don't get the products? :/
Very poor documentation..

**Comment by hyochan** [comment]
@thodwris Hey, your issue haven't been identified yet. I am just trying to help you out here. `Poor documentation` when nothing has been identified is quite non-sense.

I am begging you to provide some traction after you've identified something in native side. Looking at issue at stackoverflow with different keyword would definitely help. Here is [example link](https://stackoverflow.com/questions/23586388/in-app-billing-product-not-found).

**Comment by tmjordan** [comment]
@hyochan le's say i try IAP in a native android project. Does it still won't work on emulator or is it a react native issue?
I must find an android device

**Comment by hyochan** [comment]
@tmjordan It is same in real android. IAP feature only works in real device.

**Comment by tmjordan** [comment]
@hyochan ok thank you very much for your help and support. I will try to find a real device. 👍

**Comment by thodwris** [comment]
@tmjordan 

I had to use the getSubscriptions function and not getProducts. I know it's a silly mistake but you could mention that since I attached an image with subscriptions.

Thank you for this library though :)

**Comment by Purnimalamba** [comment]
hey,
I am facing the same issue.Empty array on android.I have tried everthing.need help.

React-native:0.59.9
react-native-iap: "4.1.1",

**Comment by ManalLiaquat** [comment]
I solved it! I am using these versions,

`react-native-iap: ^4.3.0`
`react-native: 0.60.5`

just do it like this
```
const itemSkus = Platform.select({
    ios: [
        '100coins' // just remove bundle id from product id
    ],
    android: [
        '100coins' // just remove bundle id from product id
    ]
});
```
