### ISSUE TITLE
Can't run on iOS due to 'unknown type name 'SKPaymentDiscount'

### ISSUE THREAD

**Issue by ndejesus1227** [dooboolab/react-native-iap#465]
### Version of react-native-iap
2.4.9
### Version of react-native

0.59.5

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
App builds
### Actual behavior
App doesn't build
### Tested environment (Emulator? Real Device?)

Emulator

### Steps to reproduce the behavior
Just react-native run-ios with the above versions of react-native-iap and React native

This is the exact error I get:

```/node_modules/react-native-iap/ios/RNIapIos.m:167:5: unknown type name 'SKPaymentDiscount'; did you mean 'SKProductDiscount'?```

I tried renaming SKPaymentDiscount to SKProductDiscount just to see and I was getting different errors. 

Let me know if you have any questions.

**Comment by hyochan** [comment]
I've not yet tested this in recent `ios` version. I feel like there has been changes in newer version. Could you give us a `PR` if possible?

**Comment by ndejesus1227** [comment]
@hyochan I'd be happy to, but I'm not 100% sure how I'd do it. Can you walk me through setting up a PR for y'all? I don't know what the fix would be

**Comment by hyochan** [comment]
@ndejesus1227 Do you think you've found the solution to this issue?

**Comment by ndejesus1227** [comment]
@hyochan no, I haven't. I've made attempts at fixing it but I only know JavaScript. I'd have to find someone to help who knows Native iOS much better than I do

**Comment by hyochan** [comment]
@ndejesus1227 Actually, this feature has been implemented by @renatoalencar in #455. I can't help this out further currently.

**Comment by ndejesus1227** [comment]
Thanks, @hyochan. 

@renatoalencar what version of react native are you running on? I'm not sure if I should be downgrading react-native-iap or RN for now

**Comment by renatoalencar** [comment]
Hello @ndejesus1227, that's on me, sorry. What is actually happening is that your iOS version is below 12.2. As the [Apple documentation](https://developer.apple.com/documentation/storekit/skpaymentdiscount?language=objc) describes, the `SKPaymentDiscount` is available only for iOS 12.2+.

I was suppose to verify the actual iOS version, but ended up forgetting.

**Comment by ndejesus1227** [comment]
@renatoalencar ah, okay. That makes sense. Do you have any idea on when you can make a fix for this? You can take your time, just curious

**Comment by ndejesus1227** [comment]
I'll be downgrading to a version before this update until this is addressed @hyochan @renatoalencar

**Comment by ggdegreat** [comment]
i having this issue too on version` 2.4.11`. The only version that worked before @hyochan made a changes is `2.4.8`

**Comment by Lucas-Geitner** [comment]
Thanks for the explanation @ggdegreat, so i'm going to 2.4.8 !

**Comment by nolanrbrady** [comment]
I was having the same issue, and can confirm that 2.4.8 fixes the issue. Thanks for the help!

**Comment by hyochan** [comment]
So the package won't be compatible with `ios` below 12 from `2.4.9`. I've updated [readme for migration](https://github.com/dooboolab/react-native-iap#migration-guide).

**Comment by Lucas-Geitner** [comment]
Is the payment with apple Pay (and no popup) going to work ? 

We need to keep both version sync if we want to use in production library. 

We cannot choose between version > 12 or version < 12 for business !

There are probably something i don't get ! Thanks for your work @hyochan !

**Comment by aniltirola** [comment]
I had the same problem - now solved. For over a year I did not open Xcode. Now I took my iphone 6s and upgraded to firmware 12.3.1; my mac was still on 'Sierra', so my Xcode installation was not compatible with the latest ios.
- I upgraded my Mac-OS to 10.14.5
- I upgrade Xcode to 10.2.1
- I use react-native-iap 2.5.5
- Iphone 6S with iOS 12.3.1
- ejected expo-project with sdk 32.0.0, that means expo-modified-react-native based on 0.57

---> now everything works

**Comment by DataGreed** [comment]
So, the app using this library won't work when running on iOS <12.2 ?

**Comment by hyochan** [comment]
It will from 3.0.0

**Comment by DataGreed** [comment]
Thanks, will stay on 2.4.8 till 3.0.0 will be released

**Comment by hyochan** [comment]
@DataGreed Just released `3.0.0` now.

**Comment by danidfm** [comment]
@hyochan we can still see the problem with SKPaymentDiscount on v3.0.0.

Is there something we are missing? we just updated the version on package.json, did the install and clean/build the app in xcode. The error still appear.

**Comment by hyochan** [comment]
@danidfm What is your build target in `ios`?

**Comment by danidfm** [comment]
build target is 11.0 and we removed enterely the node_modules folder.

**Comment by DataGreed** [comment]
same problem with me – tried 3.0.0, but rolled back to 2.4.8

**Comment by DataGreed** [comment]
(by the way, prior to that I tried 3.0.0 RC versions and still got the same error)

**Comment by hyochan** [comment]
Could you all kindly test `IamExample` project and see the difference with your project? I want to be clear on looking at the same codes.

**Comment by ndejesus1227** [comment]
> Hello @ndejesus1227, that's on me, sorry. What is actually happening is that your iOS version is below 12.2. As the [Apple documentation](https://developer.apple.com/documentation/storekit/skpaymentdiscount?language=objc) describes, the `SKPaymentDiscount` is available only for iOS 12.2+.
> 
> I was suppose to verify the actual iOS version, but ended up forgetting.

I just want to say that he literally send he was supposed to verify the version and avoid this issue, but he forgot. His pull request should have never been merged into master

**Comment by iLyxa3D** [comment]
Trying to Run project in Xcode for my iPhone with iOS v12.3.1
Same error, using react-native-iap v3.2.2. 
Going to 2.4.8 (build successful)

I think the reason is iOS version installed on the device

**Comment by hyochan** [comment]
This is very odd, because some of them already confirmed the build is ok (so do I). If you are having problem upgrading please try to remove `ios/build` then try again.

**Comment by francbelak** [comment]
@hyochan thank you for your great support!

I just tried all the hints mentioned in this issue (completely removed node_modules before npm install, clean app, removed ios/build). Unfortunately I am still getting this issue in combination with build target 11.2 and react-native-iap v3.2.2. I also tried downgrading to v2.4.8, which leads to a successful build. Moreover I tried to setup IapExample but end up in this react-native issue (https://github.com/facebook/react-native/issues)

**Comment by murilobast** [comment]
I'm having the same issue on an iMac with macOS 10.13. My macbook running 10.15 is building fine,

Maybe older mac version is not working? 🤔

**Comment by DataGreed** [comment]
@murilobast different xCode versions?

**Comment by rizvanrzayev** [comment]
Check os version `#if __IPHONE_12_2` error code block and rebuild

**Comment by NickAVolpe** [comment]
I was running into this issue. Updating my xcode from 10.1 to 10.2.1 fixed my issue. I am able to build my project now.

**Comment by lc3t35** [comment]
Same problem with Xcode 10.1, I can't update XCode to 10.2 because it needs OSX 10.14.3, not suppported by my old iMac stuck at 10.13.6.

**Comment by liudmyla-schastlyvets** [comment]
@lc3t35 , how did you build iOS project with Xcode 10.1?

**Comment by lc3t35** [comment]
@liudmyla-schastlyvets I can't build with 10.1, I had to use another computer with Xcode lastest version :(

**Comment by ismetsezer** [comment]
react-native: 0.59.0
react-native-iap:2.4.8
Xcode: 10.1
Successfully Built Project. Thanks

**Comment by lc3t35** [comment]
Yes, me too ! excellent work from the maintainers !
