### ISSUE TITLE
validateReceiptIos is returning a reciept with 21007 when testing from test flight.

### ISSUE THREAD

**Issue by HamzaIkram2727** [dooboolab/react-native-iap#467]

**Comment by NarekChang** [comment]
@HamzaIkram2727 How did you decide that?

**Comment by tmjordan** [comment]
@NarekChang Testflight must be used with the sandbox store

**Comment by NarekChang** [comment]
@HamzaIkram2727 
Will this work in TestFlight and Production?
```const valid = await RNIap.validateReceiptIos({ 'receipt-data': receipt, 'password': iosKey }, false);```
