### ISSUE TITLE
Wanted to know that on testflight the receipt is sent to the test server or the production server to be validated?

### ISSUE THREAD

**Issue by HamzaIkram2727** [dooboolab/react-native-iap#468]
### Version of react-native
0.58.2

**Comment by HamzaIkram2727** [comment]
So i am using Rniap for in-app purchases. The thing is everything works well when i am testing on my machine but when I upload the app on testflight and log in as a sandbox tester and invoke receipt validationios I always get status 27001. Any ideas?

**Comment by bethshook** [comment]
@HamzaIkram2727 The way I handle this is that when I validate the iOS receipt, I first assume it's going to the production environment. Then I check the response and if it's 21007, I validate again by sending to sandbox environment.

**Comment by martinezguillaume** [comment]
@bethshook simple and do the job, thanks !
