### ISSUE TITLE
Implicit conversion of 'BOOL' (aka 'bool') to 'id' is disallowed with ARC.

### ISSUE THREAD

**Issue by siderakis** [dooboolab/react-native-iap#470]
### Version of react-native-iap
Latest
### Version of react-native
Latest
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior

Build error: Implicit conversion of 'BOOL' (aka 'bool') to 'id' is disallowed with ARC.

RCT_EXPORT_METHOD(canMakePayments:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject) {
    BOOL canMakePayments = [SKPaymentQueue canMakePayments];
    resolve(canMakePayments);  <---error is here
}

**Comment by andrewzey** [comment]
Also getting this.

**Comment by andrewzey** [comment]
https://github.com/dooboolab/react-native-iap/compare/f5d5cef2d22196d222959456f510390c4a81b4d1...78517b37f1a5675a552d74f9e8613f503cfae73f#commitcomment-33334285

**Comment by hyochan** [comment]
Resolved in #471
