### ISSUE TITLE
buyProductWithOfferIOS isn't applying discount

### ISSUE THREAD

**Issue by StewPlayside** [dooboolab/react-native-iap#480]
### Version of react-native-iap
2.4.11

### Version of react-native
0.59.6

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Calling RNIap.buyProductWithOfferIOS should initiate an iOS purchase with supplied discount applied.

### Actual behavior
iOS purchase  popup appears, but at full price, without discount applied.

### Tested environment (Emulator? Real Device?)
Tested on real device in sandbox mode.

### Steps to reproduce the behavior
- Set up subscription offer on App Store Connect.
- Create signature-generation endpoint on your server to create the required ECDSA signature.
- Create a subscription offer complete with signature, and call RNIap.buyProductWithOfferIOS.

**Comment by StewPlayside** [comment]
I've checked to ensure the offer is making it to the 'discounts' NSArray, and can confirm it's there. I'm confident it's correctly assigned to SKMutablePayment.paymentDiscount when the payment is added to the SKPaymentQueue.

**Comment by hyochan** [comment]
Hi @renatoalencar.  Could you help @StewPlayside out here?

**Comment by renatoalencar** [comment]
Could you provide any code? Are you that the discount identifier is being passed to the `identifier` field?

**Comment by StewPlayside** [comment]
@renatoalencar Sure thing. I forgot to specify that this is an auto-renewable subscription. Here's where I create the offer object and make the request. The 'eligibleOfferData' object contains the response from my server. I've checked that these values are correct and they appear so. Is there any way to determine if the signature does not meet Apple's requirements in some way?

`const offer = {
	identifier: eligibleOfferData.offerIdentifier,
	keyIdentifier: eligibleOfferData.keyIdentifier,
	nonce: eligibleOfferData.nonce,
	signature: eligibleOfferData.signature,
	timestamp: eligibleOfferData.timestamp
};
			
RNIap.buyProductWithOfferIOS(productId, uid, offer)
.then((response) => {
	console.log('RNIap.buyProductWithOfferIOS success', response);
})
.catch((err) => {
	console.log('RNIap.buyProductWithOfferIOS error', err);
})`

**Comment by renatoalencar** [comment]
You can follow [this guide](https://developer.apple.com/documentation/storekit/in-app_purchase/generating_a_signature_for_subscription_offers?language=objc) for server implementation.

One tip I can give is to check if the timestamp you used is in milliseconds (not in seconds), my teammate had an issue with that.

**Comment by cl2205** [comment]
@StewPlayside did you ever find the culprit for this? I'm also running in the same issue.

**Comment by StewPlayside** [comment]
Sorry for the late response; I was able to get this working. The issue was something in my signature generation being the incorrect format - the trouble is it fails silently so it's difficult to tell if your signature is at fault.

**Comment by ravi2007147** [comment]
anybody can help me to provide a php code to generate signature. I am facing same issue. Applying  promo code, doesn't giving any error but performing regular payment process.

i am using following react native version

react-native-cli: 2.0.1
react-native: 0.55.4

**Comment by markuscosinus** [comment]
For anyone else struggling with this: Make sure the iOS version of your testing device is at least iOS 12, since earlier versions are not compatible with subscription offers.
