### ISSUE TITLE
Supported iOS versions

### ISSUE THREAD

**Issue by cumom** [dooboolab/react-native-iap#481]
I'd like to assume that version 2.4.9 supports iOS 10/11 in addition to iOS 12+. However, the wording in the README makes it sound like I have to pick a version of react-native-iap earlier than 2.4.9 in order to support iOS 11.
In summary, does version 2.4.9 support iOS 10 and/or 11?

**Comment by hyochan** [comment]
@cumom Sorry for the confusion. Actually, I think the `build` won't fail if you are using `ios` 12+ but there were some issues in compiling unknown method below `ios` 12 provided in #455. If anyone can debug this feature and support the lower version of `react-native-iap`, it would be really appreciated. Currently, I don't have much time debugging this issue so I just warned the problem in `migration guide`.

**Comment by cumom** [comment]
Actually, I am more interested in whether the newer version of
react-native-iap works with older versions of iOS.

**Comment by hyochan** [comment]
@cumom It will be compatible as long as it builds up. However, the new feature should be tested and see if it works properly.

**Comment by paolospag** [comment]
@hyochan I'm a little bit confused...
The documentation says: 
> For ios under version 12, it is compatible until react-nativep-iap version 2.4.8. From 2.4.9, it will support ios >= 12.

But I don't understand if `react-nativep-iap@2.5.5` (the latest version) supports iOS <= 12.
Can you kindly clarify this point?

**Comment by hyochan** [comment]
This is defined in the readme. I know this can be more supportive in `ios` by distinguishing the `ios` version. However, I'll leave this for now and please give us a `PR` if you think this is necessary.

**Comment by paolospag** [comment]
@hyochan it would be helpful if in the `react-nativep-iap >= 3` readme there was reference to the minimum versions for both iOS and Android.
For example, v3 supports iOS <= 12?

**Comment by jarredt** [comment]
+1 to this. Could it be clarified in the current v3+ README if there is a minimum version of iOS that the library supports? We would not want to upgrade to v3+ if the library would no longer work for our users on iOS <12.

**Comment by hyochan** [comment]
v3 will support ios below 12
