### ISSUE TITLE
Issue with IOS implementation

### ISSUE THREAD

**Issue by mdfateh** [dooboolab/react-native-iap#483]
### I followed the manual instruction to add RNIap Library files in IOS Project, But as I attached the file,
![Screenshot 2019-05-10 at 10 05 18 AM 1](https://user-images.githubusercontent.com/46807685/57503114-728a9f80-730c-11e9-9869-f57512b51456.png)
 it's showing semantic issues in RNIapIos.m File and other files as well.

**Comment by ChrisEelmaa** [comment]
downgrade the package or update to latest xcode https://github.com/dooboolab/react-native-iap/issues/465

**Comment by mdfateh** [comment]
> downgrade the package or update to latest xcode #465

I tried your solution. I downgraded the package, this time XCode Error resolved, but now I am getting an exception "can't read 'buyProduct' property", while I am calling the method 'buySubscription'. The same method in Android is working fine, But in iOS it is giving the above error!!

**Comment by hyochan** [comment]
@mdfateh I think you are suffering from linking `react-native` native modules. Since this isn't a primary issue on our module I'll close it for now.
