### ISSUE TITLE
App does not start after installation of react-native-iap

### ISSUE THREAD

**Issue by pandanr1** [dooboolab/react-native-iap#487]
### Version of react-native-iap
2.5.1
### Version of react-native
0.59.3
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
App should start
### Actual behavior
App does not start
### Tested environment (Emulator? Real Device?)
real device iPhone SE iOS 12.2
### Steps to reproduce the behavior

After installing and linking react-native-iap the app just freezes on start. This happens only when xCode -> Product -> Scheme -> Build Configuration is set to DEBUG. If i set Build Configuration to Release it just works. Is this a known bug/feature? Cant find something about it in docs. It would be great if we could use DEBUG Build Configuration with this plugin.

**Comment by hyochan** [comment]
Thanks for reporting this. Since this was unknown issue on our side, I hope you can post some error codes for more detail.

**Comment by pandanr1** [comment]
Sry, magically it works now after restarting xcode. I think it was not a problem with react-native-iap.
