### ISSUE TITLE
Android: Incorrect RNIapPackage import with react-native link 

### ISSUE THREAD

**Issue by henkkasoft** [dooboolab/react-native-iap#49]
### Version of react-native-iap
0.2.15
react-native: 0.53.3
### Expected behavior
react-native link react-native-iap should update MainApplication.java and android/app/build.gradle correctly
### Actual behavior
link adds MainApplication.java
import com.dooboolab.RNIap.RNIapPackage;
it should be: com.reactlibrary.RNIapPackage

Also:
compile project(':react-native-iap') is not updated to android/app/build.gradle, it have to be done by hand.

Thank you very much for the component, not yet fully in use but seems very useful.

**Comment by dooboolab** [comment]
@henkkasoft 
I've just tried `react-native link react-native-iap` with clean project from `react-native init` and worked fine.
```
➜  LinkTest npm install      
➜  LinkTest react-native link react-native-iap
Scanning folders for symlinks in /Users/hyochan/Documents/SourceCode/TestProjects/LinkTest/node_modules (27ms)
rnpm-install info Linking react-native-iap android dependency 
rnpm-install info Android module react-native-iap has been successfully linked 
rnpm-install info Linking react-native-iap ios dependency 
rnpm-install info iOS module react-native-iap has been successfully linked 
```

I've checked into android project and everything linked properly. Also compile project has been done successfully with out manually installing it.

```
include ':react-native-iap'
project(':react-native-iap').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-iap/android')
```

I've heard react-native link system is not that perfect so we've written manually installing guide. However more than 90% I am sure it would be fine. Did you also tried with clean install from react-native project?

**Comment by brentjanderson** [comment]
I have seen the same issue on the project I'm working on, FWIW. Linking uses `import com.dooboolab.RNIap.RNIapPackage;` instead of `com.reactlibrary.RNIapPackage;`. I have had to use the manual linking steps accordingly.
(refs #46)

**Comment by dooboolab** [comment]
@henkkasoft @brentjanderson 
Thank you for the bug report. I've just updated npm to `0.2.16` with breaking changes readme. Now the package name will be fixed to `com.dooboolab.RNIap.RNIapPackage`. This will be updated when you install `npm install --save react-native-iap@0.2.16` and just open up the android studio with `android` dir of your react-native project. Then it will warn you with no module found for `react-native-iap` so remove it. Then it will automatically find your module and link it for you if it was already installed.

Thank you. Tell me if there is another problem after `0.2.16` with the package name.

**Comment by henkkasoft** [comment]
Just another comment on instructions.

iOS manual instructions step 2 is missing "ios" folder:
Go to node_modules ➜ react-native-iap and add RNIap.xcodeproj
should be:
Go to node_modules ➜ react-native-iap ➜ ios and add RNIap.xcodeproj

Didn't want to create a new issue for so obvious small thing.

**Comment by Ruchita-uninow** [comment]
in android i am getting automatically imported with import com.dooboolab.RNIap.RNIapPackage; and need latest version with latest react-native update could you fix this issue as soon as possible ?

**Comment by hyochan** [comment]
@Ruchita-uninow Sounds like an npm cache problem
