### ISSUE TITLE
.clearTransaction() throwing "Cannot finish a purchasing transaction"

### ISSUE THREAD

**Issue by ilyakar** [dooboolab/react-native-iap#491]
### Version of react-native-iap
2.4.8

### Version of react-native
0.57.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Purchase to go through

### Actual behavior
Crashes sometimes when .clearTransaction() above .buyProduct()

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
The doc states:
```
await RNIap.clearTransaction(); // add this method at the start of purchase.
const purchase = await RNIap.buyProduct(...)
...
```

Not having the .clearTransaction causes "Already bought this product" for consumables, having the .clearTransaction throws "Cannot finish a purchasing transaction" (sometimes).

What's the solution?

**Comment by hyochan** [comment]
@ilyakar Can you try `clearProducts`?

**Comment by javascripter** [comment]
We observed the same error in our production app too. In our case however, this happened for `.clearTransaction()` above `.buySubscription()`.
I'm not too sure whether `.clearTransaction()` is really required for auto-renewable subscriptions, but we have similar code for consumables too.

If this should be a separate issue, please tell me so.

### Version of react-native-iap
2.4.8

### Version of react-native
0.59.8

### Platforms you faced the error (IOS or Android or both?)
iOS

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
```
let subscription = null

async function subscribe() {
  let purchase = null

  try {
    if (subscription) {
      subscription.remove()
      subscription = null
    }
    await RNIap.clearTransaction()

    purchase = await RNIap.buySubscription(SUBSCRIPTION_SKU)
  } catch (ex) {
    purchase = await new Promise((resolve, reject) => {
      subscription = RNIap.addAdditionalSuccessPurchaseListenerIOS(
        purchase => {
          // ... (code for checking item sku)
          resolve(purchase)
          subscription.remove()
          subscription = null
        }
      )
    })
  }

  if (!purchase) {
    return
  }
  // purchased 
}

```
The error is thrown only sometimes. We suspect calling `subscribe` again while `subscribe` is running may be causing errors

**Comment by WJimmyCook** [comment]
@javascripter I'm having the same error occasionally and I think you are right about calling subscribe again while subscribe is running. For me, I believe it happens because the user is quickly tapping the purchase button two or more times before the purchase confirmation screen from apple pops up.

**Comment by curiousdustin** [comment]
I am getting this error, and associated crash.

I am using react-native-iap 2.4.4, and I don't necessarily want to upgrade to 3.x yet.

I am calling `clearTransaction()` before `buySubscription()`. 

It is only crashing occasionally.

I am only using subscription IAP. 

Like @javascripter , it is unclear to me if `clearTransaction()` is needed for subscriptions.

Is there anything I can do to avoid this issue and crash?

**Comment by hyochan** [comment]
Might be related to #581. We are looking forward to digging it.
