### ISSUE TITLE
How to properly test purchasing on iOS?

### ISSUE THREAD

**Issue by ndejesus1227** [dooboolab/react-native-iap#492]
### Version of react-native-iap
2.3.21
### Version of react-native
0.59.7

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Connect to iTunes account
### Actual behavior
Asking to connect to iTunes on real device, not being able to connect with right credentials
### Tested environment (Emulator? Real Device?)
Emulator and Real device
### Steps to reproduce the behavior
Simply setting up on iOS

I get a smooth experience for Android but I'm not able to connect to any iTunes account on a real device.

**Comment by hyochan** [comment]
You shoulud make your `testflight` account.

**Comment by pandanr1** [comment]
... and sandbox user...

**Comment by hyochan** [comment]
Oh, I meant adding `sandbox` user! @pandanr1 thanks. I'll close this issue since this isn't related to our module.
