### ISSUE TITLE
Error when repurchasing items once purchased

### ISSUE THREAD

**Issue by StudyTae** [dooboolab/react-native-iap#494]
###_ Version of react-native-iap

 "react-native-iap": "^2.5.3",
### Version of react-native

react-native: `expo` sdk 30 version

### Platforms you faced the error (IOS or Android or both?)

Andoroid

### Expected behavior

Payment screen will be available.

### Actual behavior

> E_ALREADY_OWNED, You already own this item.

### Tested environment (Emulator? Real Device?)

Android studio and Real Device

### Steps to reproduce the behavior

If '`**getItems()**`' is executed, '`**buyItem()**`' is completed, and '`**buyItem()**`' is executed again, the 

> E_ALREADY_OWNED, you are already aware of this item

 error code will be generated.

**Comment by hyochan** [comment]
You should `consume` item if this is `consumable`. Hope you can study more on `android` `iap` feature since this is just the bridge that makes your life easier.

**Comment by StudyTae** [comment]
> You should `consume` item if this is `consumable`. Hope you can study more on `android` `iap` feature since this is just the bridge that makes your life easier.

I'm already using that function.
~~~js
  try {
      const result = await RNIap.initConnection();
      await RNIap.consumeAllItems();
      console.log("result", result);
    } catch (err) {
      console.warn(err.code, err.message);
    }
~~~

**Comment by gaykov** [comment]
For anyone struggling with the similar issue:

For me `consumeAllItemsAndroid` wasn't working for `android.test.purchased`, it was throwing an error (something like "No purchased items").

So it's possible to consume only `android.test.purchased` using `consumePurchaseAndroid` with the following code:
```
await RNIap.consumePurchaseAndroid(
  'inapp:your_bundle_id:android.test.purchased',
);
```

Then it's possible to purchase `android.test.purchased` again.

**Comment by K12AZ** [comment]
@haikov , when do we need to call this?
