### ISSUE TITLE
getProducts: fails on iOS depending on location

### ISSUE THREAD

**Issue by gaspop** [dooboolab/react-native-iap#495]
### Version of react-native-iap
2.4.9

### Version of react-native
0.59.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Should be able to contact AppStore and get product regardless of location.

### Actual behavior
The whole flow of getting the product info from AppStore and completing the purchase has worked fine when we've tried it in TestFlight on several different devices, but Apple's review team keep failing to even retrieve the product, not that it doesn't find any products, but getProducts seems to fail for some reason. They report the error on an iPad running on iOS 12.2, but that has worked fine for us.

The only difference I can think of is that we've done all our testing in Sweden, yet the in-app purchase is configured to be available everywhere so it shouldn't matter.

### Tested environment (Emulator? Real Device?)
Real devices using TestFlight

### Steps to reproduce the behavior
The thing is, we've haven't been able to reproduce the error ourselves so we're not sure how to move forward, but this is where it seems to fail on the review team's end.
```
try {
  const products = await IAP.getProducts(['our.product.id])
} catch (error) {
  this.setState({ error: 'Failed to get products' })  
}
```

**Comment by hyochan** [comment]
Doesn't sound like it depends on our module. I think you should search more on the native side. Please come back when you find any news.

**Comment by gaspop** [comment]
@hyochan you're probably right, was hoping someone might have encountered the same problem

**Comment by gaspop** [comment]
Closing this as it seems it was an error on Apple's end.

For anyone interested I asked the Apple review team if the problem occurred on iPhone as well, after which they suddenly approved the app without any further feedback.
