### ISSUE TITLE
> You should `consume` item if this is `consumable`. Hope you can study more on `android` `iap` feature since this is just the bridge that makes your life easier.

### ISSUE THREAD

**Issue by StudyTae** [dooboolab/react-native-iap#496]
> You should `consume` item if this is `consumable`. Hope you can study more on `android` `iap` feature since this is just the bridge that makes your life easier.

I'm already using that function.
~~~js
  try {
      const result = await RNIap.initConnection();
      await RNIap.consumeAllItems();
      console.log("result", result);
    } catch (err) {
      console.warn(err.code, err.message);
    }
~~~

_Originally posted by @StudyTae in https://github.com/dooboolab/react-native-iap/issues/494#issuecomment-494280794_

**Comment by hyochan** [comment]
So is this `consumable`?

**Comment by StudyTae** [comment]
> So is this `consumable`?

this is not `RNIap.consumeAllItems();`?

**Comment by hyochan** [comment]
I believe #510 fill fix this issue.
