### ISSUE TITLE
consumeAllItems doesn't work with android.test.purchased

### ISSUE THREAD

**Issue by fokoz** [dooboolab/react-native-iap#497]
### Version of react-native-iap
2.5.4
### Version of react-native
0.55.4
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
`consumeAllItems` should be consume all items, also `android.test.purchased` test product id
### Actual behavior
`consumeAllItems` doesn't consume `'android.test.purchased'` 
So I have to use `RNIap.consumePurchase("inapp:com.learnary:android.test.purchased")` to consume the test product.
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
```
const result = await RNIap.initConnection()
console.log('initiated connection?', result)
await RNIap.consumeAllItems();
const purchase = await RNIap.buyProduct('android.test.purchased');
```
Then error occurs "Already own this"

**Comment by hyochan** [comment]
Try `consumeProduct`

**Comment by fokoz** [comment]
@hyochan Yes. `consumPurchase` is working and I already stated it in Actual behavior.
 However, I'm afraid that someone will be wasting time to figure it out because `consumeAllItems` should work, so it looks like a bug.

**Comment by hyochan** [comment]
@fokoz Thanks for coming back. Currently, I think I need more detail to get into this behavior.
What do you suspect this might be caused from the [link](https://github.com/dooboolab/react-native-iap/blob/6a3310c4b594a28280d72b754a1d12d74a97af1c/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L180-L207).

**Comment by StudyTae** [comment]
> @fokoz 다시와 주셔서 감사합니다. 현재, 나는이 행동에 들어가기 위해서 더 자세하게 생각해야한다고 생각합니다. 
> 당신이 의심 않는 것은으로부터 발생할 수 있습니다 [링크](https://github.com/dooboolab/react-native-iap/blob/6a3310c4b594a28280d72b754a1d12d74a97af1c/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L180-L207) .

i'm same problem.
~~~js
async componentDidMount() {
  try {
      const result = await RNIap.initConnection();
      await RNIap.consumeAllItems();
      console.log("result", result);
} catch (error) {
      alert(error);
    }
...
//결제테스트
  getItems = async itemSkus => {
    try {
      const products = await RNIap.getProducts(itemSkus);
      // const products = await RNIap.getSubscriptions(itemSkus);
      console.log("Products", products);
      this.setState({ productlist: products });
    } catch (err) {
      console.warn(err.code, err.message);
    }
  };

  buyItem = async sku => {
    console.info("buyItem: " + sku);
    try {
      const purchase = await RNIap.consumePurchase(sku);
      this.setState({ receipt: purchase.transactionReceipt }, () =>
      );
    } catch (err) {
      if (err.code === "E_USER_CANCELLED") {
        console.log("##################################");
        console.log(err.message);
        console.log(err.code);
        // code = { resultCode: "S900" };
        // this.webview.postMessage(JSON.stringify(code));
        console.log("-----------------------------------------------");
      }
      const subscription = RNIap.addAdditionalSuccessPurchaseListenerIOS(
        async purchase => {
          this.setState({ receipt: purchase.transactionReceipt }, () =>
            console.log("ios sucess")
          );
          subscription.remove();
        }
      );
    }
  };

}

~~~

this is did not work.
`await RNIap.consumePurchase(sku);`

**Comment by hyochan** [comment]
There seems to be an issue with `getPurchases` method in `android`. See [here](https://stackoverflow.com/questions/49772079/iab-not-returning-un-consumed-purchase/49918684) if it helps.

**Comment by hyochan** [comment]
I believe #510 will fix this.
