### ISSUE TITLE
Issue with fetching Subscription details in IOS

### ISSUE THREAD

**Issue by mdfateh** [dooboolab/react-native-iap#498]
### Steps to reproduce the behavior

I used this library for Subscription. I tried two methods in ios getSubscription and buySubscription. it works fine in android. But when I use it in Ios, it fetches data in console.log, But unable to open the Subscription page after click on the button.
It returns all data in alert but failed to display the Subscription page!!
Error is "Cannot connect to iTunes Store"

**Comment by hyochan** [comment]
Did you put any alert in between that disturbs the native ui to open?

**Comment by mdfateh** [comment]
Ya, It's working fine now.
But some another bug is there. It's from my side or from Apple side,  can't figured out.
The bug is that When I SignIn once and provides credentials for "Confirm In-App purchase", It's showing the "SignIn Required" popup again and again.

**Comment by baddboy-obn** [comment]
i have same problem, then i try getSubscription open window login/pass iTunes, then i input it, display me "Cannot connect to iTunes Store". In Real device, 0.59.9, 2.5.5
![oAJ-M6RbY6U](https://user-images.githubusercontent.com/49719025/59118961-3aea3400-895a-11e9-940f-514d1d03d18e.jpg)
![isnVs5lZS5M](https://user-images.githubusercontent.com/49719025/59118962-3aea3400-895a-11e9-902f-ad8e1cfb5cd4.jpg)

**Comment by hyochan** [comment]
Please check your wifi and other issues related to `itunesconnect`. I believe this isn't issue in our side. I am clsoing this for now but please feel free to reopen when you think this is a problem in our module.

**Comment by baddboy-obn** [comment]
> Please check your wifi and other issues related to `itunesconnect`. I believe this isn't issue in our side. I am closing this for now but please feel free to reopen when you think this is a problem in our module.

Sorry its my fault, i updated xcode and iphone sdk and that do fine!
