### ISSUE TITLE
Add support for tvOS on ios

### ISSUE THREAD

**Issue by aakashsigdel** [dooboolab/react-native-iap#499]
### Version of react-native-iap
2.5.4
### Version of react-native
0.59.8
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
tvOS target should be supported
### Actual behavior
tvOS target is not supported
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
add the binary  to linked libraries of tvOS target, it will produce a build error

**Comment by aakashsigdel** [comment]
I have submitted a PR for this

**Comment by hyochan** [comment]
@aakashsigdel Thanks I'll look over it during the weekend.
