### ISSUE TITLE
Google Play Developer API version 3 support

### ISSUE THREAD

**Issue by nenjamin2405** [dooboolab/react-native-iap#501]
Hi guys, first of all, thank you guys for developing this awesome library,

I had a question related to the new Google Play Developer API. Do I need to beware about the phrase 

> Starting December 1, 2019, versions 1 and 2 of the Google Play Developer API will no longer be available so you need to update to version 3 ahead of this date

mentioned in this article https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html. 

Does this library use the old version (1 or 2) of Google Play Developer API as a dependency for purchasing and subscription?

Thank you guys a lot!

**Comment by hyochan** [comment]
We are already using v3.
