### ISSUE TITLE
Make purchase with fingerprint / Face ID

### ISSUE THREAD

**Issue by stanleycyang** [dooboolab/react-native-iap#502]
### Version of react-native-iap
2.5.4

### Version of react-native
59.2

### Platform
iOS

### FEATURE REQUEST

Making a purchase on iOS with Face ID / Fingerprint instead of purchasing with iTunes password

**Comment by hyochan** [comment]
Just a question. I thought this will be supported automatically in `production`. Could someone tell about this feature with more detail?

**Comment by stanleycyang** [comment]
I'm not quite sure if this is already supported in production for this library. I tried this library in develop and it seems that it makes the user input their Apple password still.

**Comment by jvandenaardweg** [comment]
> I tried this library in develop and it seems that it makes the user input their Apple password still.

That's expected when using the Sandbox environment. 

When your app runs in production, it will automatically use Touch ID or Face ID if the user has that setup on their phone. If they did not set that up, it will ask for their iTunes password, like back in the days :-)

**Comment by stanleycyang** [comment]
That's great to hear -- I will try moving it out to production and see if it works!

**Comment by stanleycyang** [comment]
In testflight it does not work either -- I'm assuming we need to move it to full production to see if it works?

**Comment by jvandenaardweg** [comment]
Testflight Apps use the same Sandbox environment. 

Touch/Face ID will only work from Apps within the App Store.

It’s not clearly documented, but that’s how it works.

Touch/Face ID should “just work” when your App is downloaden from the App Store, if users have set it up.

**Comment by stanleycyang** [comment]
Yeah, I agree about adding that to the README @jvandenaardweg . I can submit a PR for that to help out future users. I'll test first by moving this build into production to ensure that the Touch / Face ID works

**Comment by stanleycyang** [comment]
Great, looks like it's working in production. I'll add it to the README now

**Comment by hyochan** [comment]
closed for merged!

**Comment by sintylapse** [comment]
Hey @jvandenaardweg why documentation says `set your deployment target to iOS 12`, is Face and Touch ID won't work without it? So basically in order to enable this features on new devices I should get rid of older devices? Sounds not very logical to me considering that payment is built in devices, not application
