### ISSUE TITLE
Question: How to associate apple payment notification with my custom payment records?

### ISSUE THREAD

**Issue by dengue8830** [dooboolab/react-native-iap#503]
Sorry, this is not an issue, just searching some help, i have searched in every blog/discord channel and no one have an answer.

Is there some param when i'm making the purchase that allows me to associate the payment with my custom bill?

https://stackoverflow.com/questions/56304803/how-to-associate-apple-payment-notification-with-my-custom-payment-records

thanks

**Comment by hyochan** [comment]
Sorry. I have no idea on this one either.

**Comment by dengue8830** [comment]
[here](https://stackoverflow.com/a/56429198/3744400) is the solution
