### ISSUE TITLE
Currency is different from googleplay

### ISSUE THREAD

**Issue by gufengpiaoyi** [dooboolab/react-native-iap#504]
### Version of react-native-iap
2.4.8
### Version of react-native
0.59.1
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
The currency that is expected to be displayed is JP.
### Actual behavior
The currency shown now is HK
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
VPN set to Japan.GooglePlay clear cache and restart.The currency display in googleplay is JP.

**Comment by putuyoga** [comment]
Have you tried to change your google account/play region also?

**Comment by gufengpiaoyi** [comment]
> Have you tried to change your google account/play region also?

not yet.I guess this should be related to my account, but I don't know what to do.I can try your way.Thanks a lot.
