### ISSUE TITLE
RNIap.buyProduct not resolving and it's not storing the receipt state after completed transaction

### ISSUE THREAD

**Issue by DannyRox23** [dooboolab/react-native-iap#506]
### Version of react-native-iap
Latest

### Version of react-native
Latest

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
After purchase was successful, Alert "Congrats you have purchased" and fire function that hides the purchase button and unlocks consumable.

### Actual behavior
After the purchase was successful, nothing happens but the purchase did work. I need to fire a function or logic after the purchase was successful because currently the user has to restart the app to "unlock" the products because I need to do the getAvailablePurchases bit all over again to verify purchased items.

### Tested environment (Emulator? Real Device?)
Real Device and Bluestacks

### Steps to reproduce the behavior
The Alert doesn't "alert" after the purchase window disappears or after any purchase is done for the matter. Why?
```
async PurchasePack(){
        try {
            const purchases = await RNIap.buyProduct( packID );

            Alert.alert('THANK YOU', 'Your purchase was successful!')

        } catch( err )  {
            // standardized err.code and err.message available
            console.warn( err.code, err.message );

            this.setState({ purchased: 'false' });
        }
    }
```

**Comment by hyochan** [comment]
Try using `InteractionManager.createInteractionHandle();`. `Android` may have blocked your UI interaction.

**Comment by fokoz** [comment]
I have a problem which mays relate to this issue and it is so hard to test.

 Occasionally(10-20%) my user purchased product successfully but the code never reach requesting to api on the next line, so the coin is lost.

**Comment by hyochan** [comment]
@fokoz Have you also used `Alert`? This may block some thread in some devices if it has native ui coming up together. Please consider this one in mind.

**Comment by fokoz** [comment]
@hyochan I don't use alert and I don’t know which line doesn't resolve( buyProduct or consumePurchase) because when I test by myself everything goes fine but some user(10%) purchased the product and I receive order email from google but the next code is to send purchase token to api, I have no idea if it run or not.

I hope it is not about internet connection problem after purchasing or consuming

**Comment by hyochan** [comment]
@fokoz I am planning to release new releases with some migrations in #510. I hope you to try `3.0.0-rc.0' when merged.

**Comment by fokoz** [comment]
@hyochan could you explain how can you fix this issue? What cause the problem? Why do just some user experience this but not all of them ?Thank you.

**Comment by hyochan** [comment]
If you follow issue in #307, you will see the idea. Andorid `iap` works similar to `ios` so you may face the same problem. New purchase flow in #510 will describe how you can resolve this. Please try new purchase flow in `3.0.+`.
