### ISSUE TITLE
RNiap build fail

### ISSUE THREAD

**Issue by baddboy-obn** [dooboolab/react-native-iap#508]
### Version of react-native-iap
0.59.9
### Version of react-native
2.5.5
### Platforms you faced the error (IOS or Android or both?)
ios
### Expected behavior
Normal building test project
### Actual behavior
Build fail
### Tested environment (Emulator? Real Device?)
real/emul
### Steps to reproduce the behavior
1) Create test RN project
2) Install last RNiap
3) Linked 
4) xcode run build real device  = build fail
5) console react-native run-ios = build fail

**Comment by baddboy-obn** [comment]
![Снимок экрана 2019-06-06 в 20 04 41](https://user-images.githubusercontent.com/49719025/59051799-60156e80-8896-11e9-9652-5f0f8a41f07d.png)

**Comment by hyochan** [comment]
Related #465
