### ISSUE TITLE
How to get the accessToken in order to send it to validateReceiptAndroid

### ISSUE THREAD

**Issue by thodwris** [dooboolab/react-native-iap#509]
Hi @hyochan 

Can you clarify more this sentence from the documentation?

> Select your app > Services & APIs > "YOUR LICENSE KEY FOR THIS APPLICATION Base64-encoded RSA public key to include in your binary". reference.

**Comment by hyochan** [comment]
Could you follow other thread such as #458? See if it helps you.

**Comment by hyochan** [comment]
Please feel free to reopen when you still need improvements.

**Comment by thodwris** [comment]
My question is how to validate receipt on frontend? I don't want to do it from backend side.

**Comment by hyochan** [comment]
@thodwris I've not found the additional post in `English` but here is a nice one written in `Korean`. Could this help? Also, local validation is not `recommended` for production.

**Comment by thodwris** [comment]
Where is the link? I know it's not recommended but I need a fast way to do so.

**Comment by hyochan** [comment]
Its in #458

[Post again](https://m.blog.naver.com/PostView.nhn?blogId=gusrn1423&logNo=221352943668&categoryNo=50&proxyReferer=&proxyReferer=http%3A%2F%2Fblog.naver.com%2FPostView.nhn%3FblogId%3Dgusrn1423%26logNo%3D221352943668%26categoryNo%3D50%26parentCategoryNo%3D0%26viewDate%3D%26currentPage%3D1%26postListTopCurrentPage%3D1%26from%3Dsearch%26userTopListOpen%3Dtrue%26userTopListCount%3D5%26userTopListManageOpen%3Dfalse%26userTopListCurrentPage%3D1)

**Comment by vishaldhanotiya** [comment]
I have faced the same issue. I write down the solution [here](https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880) please check this [link](https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880) it may help you to solve your problem 

https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880
