### ISSUE TITLE
purchaseUpdatedListener - on Error?

### ISSUE THREAD

**Issue by Cnordbo** [dooboolab/react-native-iap#511]
### Version of react-native-iap
3.0.0-rc0
### Version of react-native
0.59.9
### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
unknown
### Actual behavior
unknown

According to your flow diagram for 3.0.0-rc0, theres an purchase response returned to the app both on success and failure. 

It seems that theres only the "happy-path" described in the docs for `purchaseUpdatedListener` - what happens if the user cancels / theres a failure? Are we assuming that the OS handles the response to the user, and only react to actual purchases made? Theres no response to the payment initiater?

Could you please describe this, it seems like theres a promise rejection in the code, but we are event based now, so might just be kept for backwards compatibility atm?

**Comment by hyochan** [comment]
@Cnordbo You can still receive promise messages from `requestPurchase`, whether it is failed or not. All the successful purchases will be received from `purchaseUpdatedListener` whether it was refused by `Apple` or successful.

Your idea of handling this in `onError` is quite reasonable though. We will have to think for our roadmap may be in the future.

**Comment by hyochan** [comment]
@Cnordbo Working on #517.

**Comment by Cnordbo** [comment]
Very nice @hyochan ! Thank you for that! Love the idea around this new event system! Thanks for you work!
