### ISSUE TITLE
How to check subscription auto renewed or not on iOS ? 

### ISSUE THREAD

**Issue by infaz** [dooboolab/react-native-iap#513]

**Comment by hyochan** [comment]
We need community support for this since I've not yet tested this feature

**Comment by jvandenaardweg** [comment]
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW6

A few ways that i'm currently aware of:

1. When validating a receipt with the Apple Servers, and the receipt validates, check if there's a new transaction after the last known `expirationDate`. If there is, its renewed.

2. Subscribe to status update notifications on your own server to receive `RENEWAL` notification types: https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW13

**Comment by Stafox** [comment]
@hyochan what about add possibility to decode `transactionReceipt` like it was done there: https://github.com/robotmedia/RMStore/blob/master/RMStore/Optional/RMAppReceipt.m

It allows also to resolve current issue. I know that I able to verify receipt using Apple Server, but I don't like the way to call Apple server twice (when make a purchase, and to verify).

What you think about that?

**Comment by hyochan** [comment]
@Stafox Thanks for providing this information. As you said, `apple` and `google` recommend us to use your own backend but for some ease of use or some other `MVP` apps, I've also provided offline `receipt validation`. I might have to look on your link someday for supporting this in `offline`.

**Comment by hyochan** [comment]
Similar to #532 could #275 help this?

**Comment by hyochan** [comment]
I'll close this for now since this is already solved issue.

**Comment by infaz** [comment]
@hyochan Thanks for pointed out the issue, and @Stafox Thanks for the information you provided. I think that the best way to handle it.
