### ISSUE TITLE
buyProductWithOfferIOS fails with E_UNKNOWN error

### ISSUE THREAD

**Issue by cl2205** [dooboolab/react-native-iap#516]
### Version of react-native-iap
2.5.5

### Version of react-native
0.59.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
A purchase with an Apple Subscription Offer discount applied should succeed with some feedback, ie. 'Purchase was successful' modal from StoreKit. The discount transaction should also be reflected in the ios receipt thereafter.

### Actual behavior
I'm able to get up to getting the StoreKit modals for seeing the correct discount price from the subscription offer and confirming the subscription, but it fails at the end w/ this Alert modal: `Unable to Purchase` `Contact the developer for more information.`

Can also confirm that the transaction is also missing from the iOS receipt.

On the other hand, I can confirm that a regular purchase transaction without any subscription offer succeeds in the current sandbox environment and am able to connect to the iTunes Store.

Here's the error stack: 
```
{
    framesToPop: 1,
    code: 'E_UNKNOWN',
    nativeStackIOS: [
      '0   shine                               0x00000001050b9524 RCTJSErrorFromCodeMessageAndNSError + 156',
      '1   shine                               0x0000000105060dfc __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 176',
      '2   shine                               0x0000000104fb9e18 -[RNIapIos rejectPromisesForKey:code:message:error:] + 512',
      '3   shine                               0x0000000104fbd124 __45-[RNIapIos paymentQueue:updatedTransactions:]_block_invoke + 312',
      '4   libdispatch.dylib                   0x000000018ce01884 <redacted> + 20',
      '5   libdispatch.dylib                   0x000000018ce0e404 <redacted> + 60',
      '6   shine                               0x0000000104fbced0 -[RNIapIos paymentQueue:updatedTransactions:] + 908',
      '7   libdispatch.dylib                   0x000000018ce00304 <redacted> + 32',
      '8   libdispatch.dylib                   0x000000018ce01884 <redacted> + 20',
      '9   libdispatch.dylib                   0x000000018ce0d73c _dispatch_main_queue_callback_4CF + 1012',
      '10  CoreFoundation                      0x000000018d382024 <redacted> + 16',
      '11  CoreFoundation                      0x000000018d37ccd4 <redacted> + 1888',
      '12  CoreFoundation                      0x000000018d37c254 CFRunLoopRunSpecific + 452',
      '13  GraphicsServices                    0x000000018f5bbd8c GSEventRunModal + 108',
      '14  UIKitCore                           0x00000001ba6c44c0 UIApplicationMain + 216',
      '15  shine                               0x0000000104cda748 main + 124',
      '16  libdyld.dylib                       0x000000018ce38fd8 <redacted> + 4'
    ],
    domain: 'SKErrorDomain',
    userInfo: {
      NSLocalizedDescription: 'Cannot connect to iTunes Store'
    }
```

### Tested environment (Emulator? Real Device?)
On a real device using a Sandbox account

### Steps to reproduce the behavior
- Set up a subscription offer on App Store Connect
- Make a signature request to your server and get a returned offer containing the required signature string, `nonce`, `timestamp`, and `keyIdentifier`
- Create a subscription offer complete with signature, and call RNIap.buyProductWithOfferIO with `productId`, `uid`, and `offer`

**Comment by hyochan** [comment]
@cl2205 I've not had test this feature throughly done in #455. @sck-v Could you assist this?

**Comment by cl2205** [comment]
Thanks @hyochan. I'm able to consistently connect to the iTunes store and make a regular purchase transaction (via `buySubscription()`) using the sandbox account -- just not with `buyProductWithOffer()`

**Comment by hyochan** [comment]
@cl2205 That's bit strange since the error message is `NSLocalizedDescription: 'Cannot connect to iTunes Store'`. Could you kindly provide your codes here?

**Comment by cl2205** [comment]
@hyochan here you go: 

```javascript 
// Purchase with Subscription Offer

const offer = {
    identifier: 'TESTOFFER', // from iTunes products discounts array
    keyIdentifier: 'MYK3Y1D' // from server,
    nonce: <nonce>, // from server
    signature: <base64-encoded-string>, // from server
    timestamp: 1560290457029 // from server
    };

  const sku = 'com.myteam.myapp.iap.monthly';
  const uid = ""; // this is an option string value for `applicationUsername` that can be an empty str as noted in the server signature docs: https://developer.apple.com/documentation/storekit/in-app_purchase/generating_a_signature_for_subscription_offers?language=objc
  
  const products = await loadProducts();   // this is successful
  const response = await RNIap.buyProductWithOfferIOS(sku, uid, offer); // StoreKit shows discount is applied but when confirming the purchase, transaction fails w/ above error
     

---------
// Regular Purchase

const sku = 'com.myteam.myapp.iap.monthly';
const response = await RNIap.buySubscription(sku);  // this is successful

```

**Comment by hyochan** [comment]
@cl2205 Have you solved the issue? I've looked through [here](https://forums.developer.apple.com/thread/114638) and seems below will help.
![image](https://user-images.githubusercontent.com/27461460/59699189-1d577d00-922c-11e9-91c4-7d33003a4856.png)

**Comment by cl2205** [comment]
@hyochan thanks for sharing that thread! 

I do seem to have resolved the issue of getting that particular alert of `Unable to Purchase - Contact the developer for more information`. and it does seem to have been related to the `applicationUsername` length. Thank you much for your help on that.

Unfortunately another issue I'm running into now is that the transaction still fails. Now I'm getting the system success modal of '`You're all set. The purchase was successful`' even though the transaction fails with an SKError code of 0 -- basically the issue described in this thread except it's happening even with an expired subscription for me: https://forums.developer.apple.com/thread/118286

**Comment by caoyongfeng0214** [comment]
> @hyochan thanks for sharing that thread!
> 
> I do seem to have resolved the issue of getting that particular alert of `Unable to Purchase - Contact the developer for more information`. and it does seem to have been related to the `applicationUsername` length. Thank you much for your help on that.
> 
> Unfortunately another issue I'm running into now is that the transaction still fails. Now I'm getting the system success modal of '`You're all set. The purchase was successful`' even though the transaction fails with an SKError code of 0 -- basically the issue described in this thread except it's happening even with an expired subscription for me: https://forums.developer.apple.com/thread/118286

How did you fix `Unable to Purchase - Contact the developer for more information`?
Please help me. [https://github.com/dooboolab-community/react-native-iap/discussions/2629](https://github.com/dooboolab-community/react-native-iap/discussions/2629)
