### ISSUE TITLE
Android getAvailablePurchase method hang on Android 9.0

### ISSUE THREAD

**Issue by fmassey** [dooboolab/react-native-iap#518]
### Version of react-native-iap
3.0.0-rc.2
### Version of react-native
0.58.2
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
const purchases = getAvailablePurchases(); should return.

Also, when I comment getAvailablePurchases() and I'm trying to buy a Product I got that Error: Error retrieving information from server. DF-DFERH-01
### Actual behavior
The app hang after calling getAvailablePurchases
### Tested environment (Emulator? Real Device?)
Real Device. This is only occurring with Android 9.0.
### Steps to reproduce the behavior
Put const purchases = getAvailablePurchases(); in you launching method.

**Comment by fmassey** [comment]
Hey I tested it with another Android 9.0 device (Samsung Galaxy 10e) and it works. The only difference with the LG G8 thinQ that doesn't work is the Android security patch level. 

LG G8 thinQ 
Android security patch level : April 1, 2019
Kernel Version 4.14.83

Samsung Galaxy 10e 
Android security patch level : May 1, 2019
Kernel Version 4.14.78

**Comment by raugustinas** [comment]
Same here!

Samsung Galaxy S8
Android security patch level: May 1, 2019
Kernel Version 4.4.111

**Comment by hyochan** [comment]
Could you try `3.0.0-rc.11` and comeback?

**Comment by fmassey** [comment]
I try in production with "react-native-iap": "^3.2.3" and it work with 

LG G8 thinQ
Android security patch level : April 1, 2019
Kernel Version 4.14.83

**Comment by calinpastean** [comment]
Happened to me on 4.3.0, Android 9.0; both production and debug
