### ISSUE TITLE
Android: 'The item you requested is not available for purchase' error.

### ISSUE THREAD

**Issue by s-aleinik** [dooboolab/react-native-iap#519]
### Version of react-native-iap

2.3.23

### Version of react-native

0.57.8

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

With the help of RNIap.buySubscription('subscription.id') method I will subscribe to any application subscription.

### Actual behavior

Frankly speaking, that is caused by android project configuration, I think. After moving from one project id (com.project.id) to another one (new.project.id) this method is always returning error "The item you requested is not available for purchase." After some hours of googling I've found out that this is the common issue with lots of info about it. But after 3 days!!! of debugging I'm still getting this error. The funniest part is that RNIap.getSubscriptions(SUBSCRIPTIONS) is always returning the full list of project subscriptions. And one more thing - after returning back to previous project id (com.project.id), everything works fine. Maybe someone there also faced it and could help.

### Tested environment (Emulator? Real Device?)

Real device. Android version 6.0.1

### Steps to reproduce the behavior

Try to use RNIap.buySubscription('subscription.id') method.

**Comment by rayashi** [comment]
I'm also facing this error

**Comment by s-aleinik** [comment]
@rayashi have you found the way to fix it?

**Comment by rayashi** [comment]
@s-aleinik unfortunately not, have you ?

**Comment by s-aleinik** [comment]
@rayashi same. Have wrote to the support and for now they're "investigating my issue".

**Comment by rayashi** [comment]
@s-aleinik let me know the news

**Comment by s-aleinik** [comment]
nothing useful from google so far

**Comment by s-aleinik** [comment]
@rayashi Hi. I have update on it. After long discussions with Google, we tried to rollout app into production. App is published now, and only after that subscriptions have started working. But fore some reason, they're all "Test subscriptions" - free for users to use

**Comment by chetan-plrch** [comment]
I don't think this can be a solution that requires to publish, facing the same problem have added my email address to License testers as well, still the error pop's up. Help needed

**Comment by s-aleinik** [comment]
@chetan-plrch if I’m not mistaken, we have rolled it out to closed Alfa track, so only beta testers had access to it. And after this app have started working fine

**Comment by Najaf-Rai** [comment]
facing same issue any body can help?

**Comment by srivatsan-asahi** [comment]
Hi i for me works for some devices , but not working for new license testers that am adding
