### ISSUE TITLE
Billing is unavailable.  android

### ISSUE THREAD

**Issue by maxto024** [dooboolab/react-native-iap#520]
### Version of react-native-iap
      `"react-native-iap": "2.5.5",`
### Version of react-native
`      "react-native": "0.59.3",`
### Platforms you faced the error (IOS or Android or both?)
Android 
### Expected behavior
to return true or false 
### Actual behavior
getting billing is unavailable
### Tested environment (Emulator? Real Device?)
Tested on the emulator and real device both even push it on play store  internal test and install Samsung j8 and still, I am getting billing is unavailable 

I am logged in the play store as well 
### Steps to reproduce the behavior

I am always getting this error 

Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.

```
 _checkStore= async () => {
     try {
 
       const result = await RNIap.initConnection();

       if(result) {
         this.getSubscriptions();
       }
       console.log('premium1', result);
     } catch(err) {
       console.warn('premium1', err); // standardized err.code and err.message available
     }
   }
```

**Comment by hyochan** [comment]
So I am confused with your code. Which line are you receiving message `Error: Billing is unavailable.`?

Also, I think

**Comment by maxto024** [comment]
thanks, @hyochan, yes I am getting this  `const result = await RNIap.initConnection();`

will check my env thanks

**Comment by hyochan** [comment]
Have you connected to internet?

**Comment by rborn** [comment]
@maxto024 you need a device that has google play installed in it. Some devices don't have it. Maybe is this the case?

**Comment by hyochan** [comment]
@maxto024 How are you going?

**Comment by b3hz4d** [comment]
I have this problem too
I test using two same device in one of them it works correctly but in other one i had this problem

**Comment by sogangCSmaster** [comment]
저도 아무문제 없이 잘 쓰다가 최근에 프로젝트를 다른 컴퓨터로 옮기면서 이와 비슷한 현상을 겪었습니다.

정확히는 google play in-app billing api version is less than 3 이것때문에 생기는 오류였고

virtual device를 새로 다시 깔면서 google play store에 로그인을 하지 않아 생기는 현상이였습니다.

에뮬레이터내에 google play store에 로그인하면 바로 해결됩니다.
