### ISSUE TITLE
ObjectAlreadyConsumedException missing in latest version?

### ISSUE THREAD

**Issue by lucienbl** [dooboolab/react-native-iap#523]
### Version of react-native-iap
3.0.0-rc5
### Version of react-native
59.9
### Platforms you faced the error (IOS or Android or both?)
Android bundleRelease
### Expected behavior
Build success
### Actual behavior
Build failed
### Tested environment (Emulator? Real Device?)
Bundle release phase
### Steps to reproduce the behavior
Build project

After checking, I noticed that
```java
import com.facebook.react.bridge.ObjectAlreadyConsumedException;
```
was missing in `RNIapModule.java`, which makes the build fail, but in the master branch this import is there, has this been fixed in a further release?

**Comment by hyochan** [comment]
Fixed in `3.0.0-rc.6`
