### ISSUE TITLE
[android] getSubscriptions not working

### ISSUE THREAD

**Issue by rborn** [dooboolab/react-native-iap#526]
### Version of react-native-iap

3.0.0.rc-6

### Version of react-native

0.59.8
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
`const subscription = await RNIap.getSubscriptions(subscriptionIds);` should return the subscriptions
### Actual behavior
`Error: Google is indicating that we have some issue connecting to payment.`
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior
Hi, thanks for this amazing module ❤️

Use the above code with valid ids for subscriptions.
It was working before 3.0.0-rc5

**Comment by hyochan** [comment]
@rborn This is pretty odd. I've had several issues related to this which happened when they upgraded the module. I am not quite sure why this is happening but most of them resolved this my unlinking and linking again.

**Comment by rborn** [comment]
I'll try tonite ir tomorrow and let you know 🤗

**Comment by rborn** [comment]
So I tried unlink/link and no luck.  Looking at the logcat erorrs google returns code 5.

This seem to happen when you test with a different app version than the one in the store and I did change the version of the app.
However I initially downgraded my test app and then I uploaded a new version to store (in alpha and beta (beta not published)  but still the same happens.

Before I only had it in internal and the testing was working :(
Any idea?

**Comment by hyochan** [comment]
Could [this](https://github.com/dooboolab/react-native-iap/issues/124#issuecomment-386593185) help ya?

**Comment by rborn** [comment]
Maybe is this: `4)wait for 6-12 hour for update item's on store.`
Thank you, I'll keep you posted 🤗

**Comment by rborn** [comment]
Ok, some updates (not entirely fixed though)
 - I had to build the app in Release mode (I actually think is just a matter of the key used to sign the apk but didn't have yet time to see how to sign the debug app with a different key while in test)
- Now the `getSubscriptions` seems to work ok, but I get a `DF-DFERH-01` from google in the inapp billing popup 🥺

**Comment by rborn** [comment]
I'm having the same issues now as in here: https://github.com/dooboolab/react-native-iap/issues/530

**Comment by rborn** [comment]
Closing, it was because I was testing with a different version number of the app and not signed with the release key

**Comment by hyochan** [comment]
@rborn Sounds good that it is finally working! 🎉
