### ISSUE TITLE
consumePurchaseAndroid not working

### ISSUE THREAD

**Issue by StudyTae** [dooboolab/react-native-iap#531]
I bought a test payment ID and wanted to pay again.

 So I was looking for that feature, and I found a `consumePurchaseAndroid`. So I used it, but it didn't work.

**I want to use the functions of below.**

> Note: To make multiple test purchases for the same in-app product, mark the item as consumed after each purchase. To do so, call 'consumeAsync().

~~~js
componentDidmount {
  try {
    const purchases = await RNIap.getAvailablePurchases();
    purchases.forEach(purchase => {
        await RNIap.consumePurchaseAndroid(purchase.purchaseToken);
      }
    })
  } catch(err) {
    console.warn(err); // standardized err.code and err.message available
    Alert.alert(err.message);
  }
}
~~~

**Comment by hyochan** [comment]
@StudyTae Could you test the `example` project? I've already tested that it was working.

**Comment by StudyTae** [comment]
@hyochan   Project behavior: Start the app => pay for it => turn it off and restart it => And try to pay again. => But there is no reaction.

example.js
~~~js
async componentDidMount() {
    try {
      const result = await RNIap.initConnection();
      await RNIap.consumeAllItems();
      const purchases = await RNIap.getAvailablePurchases();
      console.log(purchases);        //This array value is empty.
 purchases.forEach(purchase => {
        await RNIap.consumePurchaseAndroid(purchase.purchaseToken);
    });
      this.setState({
        loading: true,
      });
    } catch (error) {
      Alert.alert(
        "Info",
        "Network Error",
        [
          {
            text: "ok",
            onPress: () => {
              errorCodeSend("webviewlogin", JSON.stringify(error));
            }
          }
        ],
        { cancelable: false }
      );
    }
  }
...

  getItems = async itemSkus => {
    try {
      const products = await RNIap.getProducts(itemSkus);
      this.setState({ productlist: products });
    } catch (err) {
      errorCodeSend("webViewGetItemsFuc", err);
    }
  };


  buyItem = async sku => {
    try {
      const purchase = await RNIap.buyProduct(sku);
      this.setState({ receipt: purchase.transactionReceipt }, () =>
        this.webview.postMessage(JSON.stringify(code));
      );
    } catch (err) {
      if (err.code === "E_USER_CANCELLED") {
        this.webview.postMessage(JSON.stringify(code));
      }
      const subscription = RNIap.addAdditionalSuccessPurchaseListenerIOS(
        async purchase => {
          this.setState({ receipt: purchase.transactionReceipt }, () =>
            console.log("ios sucess")
          );
          subscription.remove();
        }
      );
    }
  };
...
async handleMessage(e) {
  const data = e.nativeEvent.data;
    pasedata = JSON.parse(data);
if (pasedata.apiType === "in_app") {
      array = [pasedata.productid];
      await this.getItems(array);
      await this.buyItem(this.state.productlist[0].productId);
    }
...
    <WebView
          ref={webview => (this.webview = webview)}
          source={{ uri: this.state.uri }}
          mixedContentMode="compatibility"
          allowFileAccess={true}
          onMessage={mssage => this.handleMessage(mssage)}
          onNavigationStateChange={this.onNavigationStateChange}
        />
}
~~~

**Comment by StudyTae** [comment]
@hyochan 
[related issue #126](https://github.com/dooboolab/react-native-iap/issues/126#issuecomment-439084872) 
The solution to this issue is that`**RNIap.consumeAllItems(**)`, when used, is the solution that makes products that have already been purchased available again.

But I already use that function, as you can see from the comments above. But it didn't work properly. So I tried to use `**getAvailablePurchases**` and `**consumePurchaseAndroid**` but this doesn't work right either. Is this the function difference based on the version? My version is **2.5.3.**

So I read the **readme** again and looked for the functions of `RNIap`. And I found `RNIap.consumePurchase`, and I tried to apply it. The function worked successfully on me.  
~~~js
 buyItem = async sku => {
    try {
      const purchase = await RNIap.buyProduct(sku);
      this.setState({ receipt: purchase.transactionReceipt });
      let parsedata = JSON.parse(this.state.receipt);
      let comsume = await RNIap.consumePurchase(parsedata.purchaseToken);
      if (comsume === true) {
         this.webview.postMessage(JSON.stringify(code));
      }
    } catch (err) {
      if (err.code === "E_USER_CANCELLED") {
        this.webview.postMessage(JSON.stringify(code));
      }
      const subscription = RNIap.addAdditionalSuccessPurchaseListenerIOS(
        async purchase => {
          this.setState({ receipt: purchase.transactionReceipt }, () =>
            console.log("ios sucess")
          );
          subscription.remove();
        }
      );
    }
  };
~~~

**Is my method the right way?**

Is there the right way to recommend me? Why doesn't the other solution work on me?

**Comment by hyochan** [comment]
@StudyTae This is resolved in `3.0.0-rc.+`. Please try using our `3.0.0` for now on. Currently `3.0.0-rc.12`.

**Comment by ashutosh-s** [comment]
I am using similar code and getting following error 

Error: Google is indicating that we have some issue connecting to payment.
Error: Google is indicating that we have some issue connecting to payment.
    at createErrorFromErrorData (blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:15917:17)
    at blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:15869:27
    at MessageQueue.__invokeCallback (blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:16746:18)
    at blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:16477:18
    at MessageQueue.__guard (blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:16650:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:16476:14)
    at e (file:///usr/lib/react-native-debugger/resources/app.asar/js/RNDebuggerWorker.js:1:136705)

**Comment by khorark** [comment]
> @hyochan
> [related issue #126](https://github.com/dooboolab/react-native-iap/issues/126#issuecomment-439084872)
> The solution to this issue is that **`RNIap.consumeAllItems()`**, when used, is the solution that makes products that have already been purchased available again.
> 
> But I already use that function, as you can see from the comments above. But it didn't work properly. So I tried to use **`getAvailablePurchases`** and **`consumePurchaseAndroid`** but this doesn't work right either. Is this the function difference based on the version? My version is **2.5.3.**
> 
> So I read the **readme** again and looked for the functions of `RNIap`. And I found `RNIap.consumePurchase`, and I tried to apply it. The function worked successfully on me.
> 
> ```js
>  buyItem = async sku => {
>     try {
>       const purchase = await RNIap.buyProduct(sku);
>       this.setState({ receipt: purchase.transactionReceipt });
>       let parsedata = JSON.parse(this.state.receipt);
>       let comsume = await RNIap.consumePurchase(parsedata.purchaseToken);
>       if (comsume === true) {
>          this.webview.postMessage(JSON.stringify(code));
>       }
>     } catch (err) {
>       if (err.code === "E_USER_CANCELLED") {
>         this.webview.postMessage(JSON.stringify(code));
>       }
>       const subscription = RNIap.addAdditionalSuccessPurchaseListenerIOS(
>         async purchase => {
>           this.setState({ receipt: purchase.transactionReceipt }, () =>
>             console.log("ios sucess")
>           );
>           subscription.remove();
>         }
>       );
>     }
>   };
> ```
> 
> **Is my method the right way?**
> 
> Is there the right way to recommend me? Why doesn't the other solution work on me?

I have this problem and my solution be that I'm revert call method consumePurchaseAndroid and acknowledgePurchaseAndroid.

```js
export const acceptPurchase = async (purchase: Purchase) => {
    try {
        if (isAndroid) {
            // If not consumable
            purchase.purchaseToken && (await acknowledgePurchaseAndroid(purchase.purchaseToken));
            // If consumable (can be purchased again)
            purchase.purchaseToken && (await consumePurchaseAndroid(purchase.purchaseToken));
        } else if (isIos) {
            purchase.transactionId && (await finishTransactionIOS(purchase.transactionId));
        }
        return true;
    } catch (e) {
        console.warn('confirmPurchase error =>', e);
        return false;
    }
};
```
