### ISSUE TITLE
What is the correct way of restoring Auto-Renewable Subscriptions?

### ISSUE THREAD

**Issue by Myerden** [dooboolab/react-native-iap#532]
### Version of react-native-iap
2.4.1
### Version of react-native
0.59.3
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Restore available auto-renewable subscriptions
### Actual behavior
Restore auto-renewable subscriptions in different devices.
### Tested environment (Emulator? Real Device?)
iPhone 6s Plus
### Steps to reproduce the behavior
call and priny the results of `await RNIap.getAvailablePurchases()` and `await RNIap.getPurchaseHistory()` methods orderly

---
After purchasing auto-renewable subscriptions I want to restore purchased subscriptions in different devices. As mentioned in Deprecated Readme (**iOS Purchasing process right way**)

> Non-consumable products can be restored via getPurchaseHistory function

but in documentation **getAvailablePurchases()** is used to restore purchases. In my tests, the result of *RNIap.getAvailablePurchases()* and *RNIap.getPurchaseHistory()* has different items and sizes.  

I am very confused which one is the restored items. Which method should be used? Which one is the latest valid restored subscription?

Thank you.

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/59614327-81f6d700-915b-11e9-92cf-2e6d1532b1e3.png)

Have you went through this?

**Comment by Myerden** [comment]
Yes, when I call *getAvailablePurchases()* 9 elements returns but when I call *getPurchaseHistory()* 2 elements returns. But the bottom images shows that restoring should be done with **getAvailablePurchases()**. As you can see non-consumable products mentioned in either with *getAvailablePurchases()* and *getPurchaseHistory()*. Which one is correct?

![Screen Shot 2019-06-17 at 18 07 06](https://user-images.githubusercontent.com/15304742/59615376-0e3cd600-912b-11e9-9d20-0f72fa7f23a5.png)
--
![Screen Shot 2019-06-17 at 18 11 40](https://user-images.githubusercontent.com/15304742/59615565-6542ab00-912b-11e9-8255-72f7f4ca4383.png)
--
![Screen Shot 2019-06-17 at 18 12 53](https://user-images.githubusercontent.com/15304742/59615659-90c59580-912b-11e9-8514-9424c1ab7636.png)
--

**Comment by Myerden** [comment]
Also I can not understand how these methods returns different items while calling the same action?

[index.js](https://github.com/dooboolab/react-native-iap/blob/cc553d116500ac3362ba9b2a0a057c8a02386fc0/index.js#L111)
```
/**
 * Gets an invetory of purchases made by the user regardless of consumption status
 * @returns {Promise<Purchase[]>}
 */
export const getPurchaseHistory = () => Platform.select({
  ios: async() => {
    checkNativeiOSAvailable();
    return RNIapIos.getAvailableItems();
  },
  //...
})();

/**
 * Get all purchases made by the user (either non-consumable, or haven't been consumed yet)
 * @returns {Promise<Purchase[]>}
 */
export const getAvailablePurchases = () => Platform.select({
  ios: async() => {
    checkNativeiOSAvailable();
    return RNIapIos.getAvailableItems();
  },
  //...
})();
```

as you can see two methods returns **RNIapIos.getAvailableItems();**

[RNIapIos.m](https://github.com/dooboolab/react-native-iap/blob/cc553d116500ac3362ba9b2a0a057c8a02386fc0/ios/RNIapIos.m#L125)
```
RCT_EXPORT_METHOD(getAvailableItems:(RCTPromiseResolveBlock)resolve
reject:(RCTPromiseRejectBlock)reject) {
    [self addPromiseForKey:@"availableItems" resolve:resolve reject:reject];
    [[SKPaymentQueue defaultQueue] restoreCompletedTransactions];
}
```

As I know **restoreCompletedTransactions** restores the purchases. So these two methods restoring the purchases. Where am I wrong?

**Comment by hyochan** [comment]
Did you follow #275?

**Comment by Myerden** [comment]
Yes. I did my restoring process as @andrewzey [solution](https://github.com/dooboolab/react-native-iap/issues/275#issuecomment-433582389).

```
const availablePurchases = await RNIap.getAvailablePurchases();
    const sortedAvailablePurchases = availablePurchases.sort(
      (a, b) => b.transactionDate - a.transactionDate
    );
    const latestAvailableReceipt = sortedAvailablePurchases[0].transactionReceipt;
```
I think now it is working correctly.

Thank you

**Comment by hyochan** [comment]
Thanks for coming back. I'll close this for now.
