### ISSUE TITLE
android build fails - cannot find symbol variable length

### ISSUE THREAD

**Issue by varinliali** [dooboolab/react-native-iap#536]
### Version of react-native-iap
^3.0.0-rc.14
### Version of react-native
0.57
### Platforms you faced the error (IOS or Android or both?)
Android

### Steps to reproduce the behavior
When I try to build the app on android studio Java Compiler throws an error with the error message 'cannot find symbol variable length'.
The error links to RNIapModule.java line 182 // purchase.length

**Comment by hyochan** [comment]
Fixed in `3.0.0-rc.15`. Sorry I was rushing at late night.
