### ISSUE TITLE
How can I know whether a user cancels payment?

### ISSUE THREAD

**Issue by StudyTae** [dooboolab/react-native-iap#538]
### Version of react-native-iap
"react-native-iap": "^2.5.3",

### Version of react-native

"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

It is understood that users can cancel payment within 72 hours if they make payment through the app. Therefore, when canceling the payment, you must reclaim the points that you gave the user. Can you tell me how the user canceled the payment?

**Comment by hyochan** [comment]
You can cancel the subscription and receive the result. If user cancelled the subscription in somewhere else, you can check this via `getAvailablePurchases`.

**Comment by StudyTae** [comment]
> 구독을 취소하고 결과를받을 수 있습니다. 사용자가 다른 곳에서 구독을 취소 한 경우이를 통해 확인할 수 있습니다 `getAvailablePurchases`.

https://github.com/dooboolab/react-native-iap/issues/531#issuecomment-502900967  

As you can see from this link, I've already used this function, but I've returned an empty array.

**Comment by Speedy1991** [comment]
Care: If you are using a backend - make sure you validate the purchases in your backend - never trust user input
E.g. For playstore you can do this as described in the [docs](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions)
