### ISSUE TITLE
Help with documentation and crash after purchrase

### ISSUE THREAD

**Issue by obsidianart** [dooboolab/react-native-iap#54]
### Version of react-native-iap
0.2.16

I'm not an Android or IOs developer and I'm starting now with the purchase system. Among all libraries for react native yours seems the only one with cross platform support and subscription. Thanks for your amazing job.

My questions following:

1) Is there anything bad in checking the subscription status every time the app loads?

2) What's the difference between "refreshAllItems" and "getSubscribeItems"? It seems (from the description) they do the same but in the description is unclear

3) What's the difference between buyItem and buySubscriptionItem?

4) I'm currently testing by releasing alpha version, I tried in many ways to deploy with android a dev version but seems impossible (by design), there's very little on react native, a guide would be amazing (but I understand you already have done a great job)

5) The app crash after purchase (the subscription is there after), I don't see anything wrong and the catch should prevent the app from crashing (but I notice in a few scenario it doesn't). I'm on Android
```
  async subscribe() {
    this.log("subscribe called")
    try {
      const isOS = Platform.OS === 'ios'
      const subscriptionName = isOS ? 'com.cooni.monthly' : 'monthly'
      this.log("attempting to subscribe")
      const receipt = await RNIap.buyItem(subscriptionName)
      this.log("receipt")
      this.log(receipt)
    } catch(e) {
      this.log("bought")
      this.log(e)
    }
  }
```

**Comment by dooboolab** [comment]
Hi! Thanks for sharing your problem. So I will quickly answer your questions as much as possible.

1. Is there anything bad in checking the subscription status every time the app loads?
    - As you need this feature to be called, it surely is not a big deal since it will do the job in another thread. However, if you need to wait for its callback to continue your app, I'd recommend you to do this job inside specific component somewhere like `componentDidMount`.

2. What's the difference between "refreshAllItems" and "getSubscribeItems"? It seems (from the description) they do the same but in the description is unclear
    - Generally, in-app-purchase items are non-consumable for default. Therefore, you need to restore the purchases to make them purchasable again. `RefreshAllItems` checks all your in-app items and make them purchasable again. Also `getSubscribeItems` is purchasing subscription item which is different from in-app item.

3.  What's the difference between buyItem and buySubscriptionItem?
    - `buyItem` is buying in-app item. `buySubscriptionItem` is buying subscription item.

4. I'm currently testing by releasing alpha version, I tried in many ways to deploy with android a dev version but seems impossible (by design), there's very little on react native, a guide would be amazing (but I understand you already have done a great job).
   - This is quite ambiguous to answer. Using our module is as simple as a guide in the readme.
<img width="746" alt="1" src="https://user-images.githubusercontent.com/27461460/36960105-dc6626f4-2088-11e8-93ec-943566a8ec50.png">
First prepare!
<img width="738" alt="2" src="https://user-images.githubusercontent.com/27461460/36960122-eba25a34-2088-11e8-8461-d7dcfea2f864.png">
Then purchase.

5. The app crash after purchase (the subscription is there after), I don't see anything wrong and the catch should prevent the app from crashing (but I notice in a few scenario it doesn't). I'm on Android.
   - I need to debug your logs in order to fix your issue. Could you do adb  logcat and see where the crash occurs? Also please check if your in-app-purchase items have been created in your playstore and linked to your app. Also seeing, your code, if you did not call `prepareAndroid()` in android platform, methods won't be called as expected.

Thank you.

**Comment by obsidianart** [comment]
That's an amazing and fast answer.

My understanding is that a subscription item is something like "billed every month", which is my case. I created a monthly recurrent item on google play and it works with the standard buyItem. In your guide the "Subscription" section use "buyItem", that's why I'm confused, since the name "buySubscriptionItem" seems for the section "Subscription". Also, you say "Subscribable products can be included in item object and purchased just like consumable product."

Logs: I have no idea how, I have 12 years experience with ecma languages but android is really new to me.. The item is created since I can subscribe to it (and yes I call prepare android). I'm trying to understand if there's a part of code called only on successful subscription. I will do more searching.

**Comment by obsidianart** [comment]
I finally got the android logs from google play
```
java.lang.NullPointerException: 
  at com.dooboolab.RNIap.RNIapModule$8.onPurchasesUpdated (RNIapModule.java:411)
  at com.android.billingclient.api.BillingClientImpl$1.onReceive (BillingClientImpl.java:136)
  at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts (LocalBroadcastManager.java:303)
  at com.android.billingclient.api.LocalBroadcastManager.access$000 (LocalBroadcastManager.java:44)
  at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage (LocalBroadcastManager.java:114)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)
```

**Comment by dooboolab** [comment]
@obsidianart Sorry for the readme. I've just udpated the readme to avoid confusion like you've experienced.
Also, having NullPointerException in your code,  did you add your account as a tester in play store console? Also, try with sku id `android.test.purchased`. If this won't work you should check if your account has been added to a tester.
Also, if `buyItem` works fine, you'd better check if you created your item with `SUBSCRIPTION` and not `INAPP` in playstore console.

Please tell me again if you are still having problem!

**Comment by obsidianart** [comment]
I'm afraid I have hard time understanding the difference. it's an "in app subscription" (attached how it looks like). The id I use is "monthly" and not "something.something.monthly". Please notice that the item is actually bought correctly. Since is an actual beta release trough the store is it relevant if it's a tester or not?

![screen shot 2018-03-05 at 12 28 27](https://user-images.githubusercontent.com/272280/36975066-c946b10a-2070-11e8-9d57-5ae201ae2776.png)

The user is added to the tester to receive the alpha version, is there a "tester" for the paid features?

That's the visual flow
<img width="471" alt="screen shot 2018-03-05 at 12 31 27" src="https://user-images.githubusercontent.com/272280/36975174-368cf8b4-2071-11e8-8824-67af46c7aa7d.png">

<img width="560" alt="screen shot 2018-03-05 at 12 31 41" src="https://user-images.githubusercontent.com/272280/36975180-3925d550-2071-11e8-894c-9e9dd670aa96.png">


<img width="557" alt="screen shot 2018-03-05 at 12 32 39" src="https://user-images.githubusercontent.com/272280/36975217-544e75b2-2071-11e8-8bdf-46bd69e8538e.png">


<img width="573" alt="screen shot 2018-03-05 at 12 32 45" src="https://user-images.githubusercontent.com/272280/36975221-56bd39d2-2071-11e8-9959-2eca07252ac7.png">


At the moment if I click again it says "already subscribed" but I can't retrieve it with the library methods.
Thanks a lot for your help

**Comment by dooboolab** [comment]
@obsidianart 
To retrieve your purchase you might want to use module `0.2.17` and use `fetchHistory` method.
By the way, I need to look into your codes why it crashes at last.

**Comment by obsidianart** [comment]
That's my full code. I didn't try to clean up as often this kind of crash is a typo. I'm aware there are still things from your example but I don't expect them to crash, only to be skipped. I didn't look into the IOs yet.

```
import React, { Component } from 'react'
import { Platform, ToastAndroid, Clipboard, SafeAreaView, ScrollView, Text, TextInput, Image, View, Modal, TouchableOpacity, RefreshControl, Button } from 'react-native'
import Navbar from './Navbar'

import Icon from 'react-native-vector-icons/Entypo'
import I18n from '../i18n'
import * as RNIap from 'react-native-iap';

// Styles
import styles from './Styles/LaunchScreenStyles'

const itemSkus = {
  ios: [
    'com.cooni.monthly',
  ],
  android: [
    'monthly',
  ],
};

async function prepareAndroid() {
  try {
    this.log("1 prepare android")
    const message = await RNIap.prepareAndroid()
    this.log("2 prepare android")
    // Ready to call RNIap.getItems()
  } catch (code) {
    this.log(code)
    // Depending on the situation, Android will have a different error code. Handle accordingly. Visit the link below for current info
    // https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponse.html
    // This catch will never be called on ios
    /*
      -2: FEATURE_NOT_SUPPORTED
      -1: SERVICE_DISCONNECTED
      0: SUCCESS (should never be successful since only errors are caught)
      1: USER_CANCELED
      2: SERVICE_UNAVAILABLE
      3: BILLING_UNAVAILABLE
      4: ITEM_UNAVAILABLE
      5: DEVELOPER_ERROR
      6: ERROR
      7: ITEM_ALREADY_OWNED
      8: ITEM_NOT_OWNED
    */
  }
}

export default class PremiumModal extends Component {
  // copyToClipboard = (text) => {
  //   Clipboard.setString(text)
  //   const isOS = Platform.OS === 'ios'

  //   if (isOS) {
  //     // TODO: https://stackoverflow.com/questions/24893788/android-toast-equivalent-in-ios
  //     alert(I18n.t('donate.copiedToClipboard'))
  //   } else {
  //     ToastAndroid.show(I18n.t('donate.copiedToClipboard'), ToastAndroid.SHORT)
  //   }
  // }

  state = {
    messages: []
  }

  log(msg) {
    this.setState({ messages: [msg, ...this.state.messages] })
  }

  async componentDidMount() {
    this.log("component mount")
    
    try {
      const message = await RNIap.prepareAndroid()
      this.log("messages")
      this.log(messages)
      const items = await RNIap.getItems(itemSkus)
      this.log("items")
      this.log(JSON.stringify(items))
      this.setState({ items })

      this.restorePreProducts()
    } catch (errorCode) {
      this.log("error")
      console.tron.log(errorCode)
    }
  }

  async restorePreProducts() {
    try {
      const subscribed = await RNIap.fetchHistory() // cross platform case
      this.log("subscribed")
      if (subscribed) this.log(JSON.stringify(subscribed))
      else this.log(" no subscriptions to restore")


      const results = await RNIap.refreshAllItems() // cross platform case
      let restoredTitles = ""
      this.log("restore pre products")
      if (results) this.log(JSON.stringify(results))
      else this.log(" no products to restore")

      results.forEach(result => {
        this.log(JSON.stringify(result))
        if (result.productIdentifier == "com.mywebsite.MyAppPremiumVersion") {
          this.setState({ premium: true })
          restoredTitles += "Premium Version"
        } else if (result.productIdentifier == "com.mywebsite.MyAppRemoveAds") {
          this.setState({ ads: false })
          restoredTitles += restoredTitles.length > 0 ? "No Ads" : ", No Ads"
        }
      })
      // alert("Restore Successful", "You successfully restored the following purchases: " + restoredTitles)
    } catch (err) {
      this.log(err)
      console.tron.log(err);
      alert(`${err}`);
    }
  }

  async subscribe() {
    this.log("subscribe called")
    try {
      const isOS = Platform.OS === 'ios'
      const subscriptionName = isOS ? 'com.cooni.monthly' : 'monthly'
      this.log("attempting to subscribe")
      const receipt = await RNIap.buyItem(subscriptionName)
      this.log("receipt")
      this.log(receipt)
    } catch(e) {
      this.log("bought")
      this.log(e)
    }
  }

  render() {
    return (
      <Modal
        visible={this.props.show}
        onRequestClose={this.props.toggle}
        animationType='fade'
        transparent={false}
      >
        <SafeAreaView style={{ flex: 1, backgroundColor: '#0B3954' }}>
          <View style={styles.mainContainer}>
            <View style={{ backgroundColor: '#0B3954', flex: 1 }}>
              <Navbar
                title={I18n.t('menu.premium')}
                rightAction={this.props.toggle}
                rightIcon='cross'
              />

              <ScrollView style={{ flex: 1 }}>
                <View style={{ paddingLeft: 20, paddingRight: 20 }}>
                  <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                    {I18n.t('premium.l1')}
                  </Text>
                  <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                    {I18n.t('premium.l2')}
                  </Text>
                  <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                    {I18n.t('premium.l3')}
                  </Text>

                  <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                    {I18n.t('premium.l4')}
                  </Text>

                  {this.state.messages.map(el => (
                    <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                      {JSON.stringify(el)}
                    </Text>
                  ))}

                  <Button
                    onPress={() => this.subscribe()}
                    title={I18n.t('premium.subscribe')}
                    color='#00E500'
                  />

                </View>
              </ScrollView>
            </View>
          </View>
        </SafeAreaView>
      </Modal>
    )
  }
}
```

**Comment by dooboolab** [comment]
In your code,

could you change 
```
const receipt = await RNIap.buyItem(subscriptionName)
```
to
```
const receipt = await RNIap.buySubscribeItem(subscriptionName)
```

**Comment by obsidianart** [comment]
I'm trying to keep the code as cross-platform as possible, I'll give it a go with fetchHistory first :D

**Comment by dooboolab** [comment]
@obsidianart yes. But `refreshPurchaseItemsAndroid` kind of method is not in `ios` as I know currently. Everything is handled by `ios` side unlike the `android`. However, if you need to restore this purchase in android, it would help you you that method and it won't affect the ios code. Just FYI.

**Comment by obsidianart** [comment]
so, ```buySubscribeItem``` fixed the crash, which is great, and ```fetchHistory``` returns the receipt. I still don't know what "refreshPurchaseItemsAndroid" is for, it's after the user deleted and reinstalled the app?

**Comment by dooboolab** [comment]
@obsidianart great that your problem is solved. `refreshPurchaseItemsAndroid` is to refresh either consumable & non-consumable product in android. If you refresh the consumable product, it will consume all your items in your app which I won't recommend. However, some developers uses this way if they are not sensitive about information tracked by the playstore. In this case most developers work with their backend and store information there. Also, `android` can restore the non-consumable product unlike `ios`. In `ios`, the non-consumable product won't get restored forever. As far as I know, this is my information so far. Could be updated.

**Comment by obsidianart** [comment]
My bad, fetchHistory returns an empty array (I had the original receipt in state).
That's my updated code, the purchase works but ```fetchHistory``` returns an empty array.
I'm not 100% sure I understand the meaning of "refreshing" products, but my understanding is that I should not call it.
Thanks for your help

```
import React, { Component } from 'react'
import { Platform, ToastAndroid, Clipboard, SafeAreaView, ScrollView, Text, TextInput, Image, View, Modal, TouchableOpacity, RefreshControl, Button } from 'react-native'
import Navbar from './Navbar'

import Icon from 'react-native-vector-icons/Entypo'
import I18n from '../i18n'
import * as RNIap from 'react-native-iap';

// Styles
import styles from './Styles/LaunchScreenStyles'

const itemSkus = {
  ios: [
    'com.cooni.monthly',
  ],
  android: [
    'monthly',
  ],
};

async function prepareAndroid() {
  try {
    this.log("1 prepare android")
    const message = await RNIap.prepareAndroid()
    this.log("2 prepare android")
    // Ready to call RNIap.getItems()
  } catch (code) {
    this.log(code)
    // Depending on the situation, Android will have a different error code. Handle accordingly. Visit the link below for current info
    // https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponse.html
    // This catch will never be called on ios
    /*
      -2: FEATURE_NOT_SUPPORTED
      -1: SERVICE_DISCONNECTED
      0: SUCCESS (should never be successful since only errors are caught)
      1: USER_CANCELED
      2: SERVICE_UNAVAILABLE
      3: BILLING_UNAVAILABLE
      4: ITEM_UNAVAILABLE
      5: DEVELOPER_ERROR
      6: ERROR
      7: ITEM_ALREADY_OWNED
      8: ITEM_NOT_OWNED
    */
  }
}

export default class PremiumModal extends Component {
  // copyToClipboard = (text) => {
  //   Clipboard.setString(text)
  //   const isOS = Platform.OS === 'ios'

  //   if (isOS) {
  //     // TODO: https://stackoverflow.com/questions/24893788/android-toast-equivalent-in-ios
  //     alert(I18n.t('donate.copiedToClipboard'))
  //   } else {
  //     ToastAndroid.show(I18n.t('donate.copiedToClipboard'), ToastAndroid.SHORT)
  //   }
  // }

  state = {
    messages: []
  }

  log(msg) {
    this.setState({ messages: [msg, ...this.state.messages] })
  }

  async componentDidMount() {
    this.log("component mount")
    
    try {
      const message = await RNIap.prepareAndroid()
      this.log("messages")
      this.log(message)

      this.log("restore")
      this.restorePreProducts()

      
      const items = await RNIap.getItems(itemSkus)
      this.log("items")
      this.log(JSON.stringify(items))
      this.setState({ items })

      
    } catch (errorCode) {
      this.log("error")
      console.tron.log(errorCode)
    }
  }

  async restorePreProducts() {
    try {
      this.log("restorePreProducts")
      this.log("fetchHistory")
      const subscribed = await RNIap.fetchHistory() // cross platform case
      this.log("subscribed 1")
      if (subscribed) this.log(JSON.stringify(subscribed))
      else this.log(" no subscriptions to restore")
      this.log("subscribed 2")

      // const results = await RNIap.refreshAllItems() // cross platform case
      // let restoredTitles = ""
      // this.log("restore pre products")
      // if (results) this.log(JSON.stringify(results))
      // else this.log(" no products to restore")

      // results.forEach(result => {
      //   this.log(JSON.stringify(result))
      //   if (result.productIdentifier == "com.mywebsite.MyAppPremiumVersion") {
      //     this.setState({ premium: true })
      //     restoredTitles += "Premium Version"
      //   } else if (result.productIdentifier == "com.mywebsite.MyAppRemoveAds") {
      //     this.setState({ ads: false })
      //     restoredTitles += restoredTitles.length > 0 ? "No Ads" : ", No Ads"
      //   }
      // })
      // alert("Restore Successful", "You successfully restored the following purchases: " + restoredTitles)
    } catch (err) {
      this.log(err)
      console.tron.log(err);
      alert(`${err}`);
    }
  }

  async subscribe() {
    this.log("subscribe called")
    try {
      const isOS = Platform.OS === 'ios'
      const subscriptionName = isOS ? 'com.cooni.monthly' : 'monthly'
      this.log("attempting to subscribe")
      const receipt = await RNIap.buySubscribeItem(subscriptionName)
      this.log("receipt")
      this.log(receipt)
    } catch(e) {
      this.log("subscribe error")
      this.log(e)
    }
  }

  render() {
    return (
      <Modal
        visible={this.props.show}
        onRequestClose={this.props.toggle}
        animationType='fade'
        transparent={false}
      >
        <SafeAreaView style={{ flex: 1, backgroundColor: '#0B3954' }}>
          <View style={styles.mainContainer}>
            <View style={{ backgroundColor: '#0B3954', flex: 1 }}>
              <Navbar
                title={I18n.t('menu.premium')}
                rightAction={this.props.toggle}
                rightIcon='cross'
              />

              <ScrollView style={{ flex: 1 }}>
                <View style={{ paddingLeft: 20, paddingRight: 20 }}>
                  <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                    {I18n.t('premium.l1')}
                  </Text>
                  <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                    {I18n.t('premium.l2')}
                  </Text>
                  <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                    {I18n.t('premium.l3')}
                  </Text>

                  <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                    {I18n.t('premium.l4')}
                  </Text>

                  {this.state.messages.map(el => (
                    <Text style={{ color: '#FFF', fontSize: 16, paddingTop: 10 }}>
                      {JSON.stringify(el)}
                    </Text>
                  ))}

                  <Button
                    onPress={() => this.subscribe()}
                    title={I18n.t('premium.subscribe')}
                    color='#00E500'
                  />

                </View>
              </ScrollView>
            </View>
          </View>
        </SafeAreaView>
      </Modal>
    )
  }
}
```
