### ISSUE TITLE
getSkuDetails() error code 5 on v3.0.0

### ISSUE THREAD

**Issue by gpatarin** [dooboolab/react-native-iap#542]
Hi, i've upgraded from v2.5.5 to v3.0.0 but the getProducts() function is not working (awaiting it for ever), no errors are raised, but only android logcat says :  
`06-20 13:32:00.152  3852  3990 W BillingClient: getSkuDetails() failed. Response code: 5`

Here's the code : 
```javascript
async componentDidMount() {
    try {
      await RNIap.initConnection();
      const products = await RNIap.getProducts(itemSkus);
      const buttons = products.map((product, key) => {
        return (
          <PurchaseCard
            key={key}
            price={product.localizedPrice}
            title={parseInt(product.title) + 'PTS'}
            productId={product.productId}
            handler={this._purchaseHandler}
          />
        );
      });
      await this.setState({
        productsList: products,
        buttons: buttons,
        loading: false,
      });
    } catch (e) {
      // Some things to do here ? i think its all about iOS eg CARD EXPIRED
    }
  }
```

### Version of react-native-iap
3.0.0
### Version of react-native
0.59.9
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Like in 2.5.5 getting the purchasable items
### Actual behavior
`Android logcat : 06-20 13:32:00.152  3852  3990 W BillingClient: getSkuDetails() failed. Response code: 5`
According to the documentation of android : 
`Invalid arguments provided to the API. This error can also  indicate that the application was not correctly signed or properly set  up for In-app Billing in Google Play, or does not have the necessary  permissions in its manifest`

But if i downgrade to v2.5.5 its working like charm !
 
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Use react-native-iap 3.0.0

**Comment by hyochan** [comment]
Anyone else having same issue?

**Comment by gpatarin** [comment]
Using fastlane to build and push to the playstore :)

**Comment by gpatarin** [comment]
Built and uploaded an updated APK having both Permissions and v3.0.0, but still getting the same logcat error... I'll be waiting until tomorrow to let the PlayStore review the app and update...

**Comment by hyochan** [comment]
I think [here](https://stackoverflow.com/questions/17128537/in-app-billing-v3-billing-response-result-developer-error) is answer for you.

**Comment by gpatarin** [comment]
Okay, sorry but i'm not using my developper's account (since its the account of the company) i use my own personnal account that i added to licensing list and Alpha channel access on the play console. Another thing to notice is that even android.test.purchased is not working...  
By the way everything is fine on 2.5.5 i can get the products list and use the fake credit card to pay, but the buyProduct() function is not awaiting the purchase (obv request, thats why i decided to upgrade to 3.0.0, but getProducts() makes it wait forerver. 
Maybe its this obscure billing package update to 2.0.1 that breaks things, so i'm just going to look at what has changed in this...
It seems like i'm missing something but don't know what it is...

**Comment by hyochan** [comment]
Sorry but I can't be more helpful because I can't generate that and also I can't see any message coming from your `env`. Please try to come back when you see any traction and let's wait for more coming.

**Comment by gpatarin** [comment]
Some news here, after i've find out that if forgot to console.warn the catch 🙃
Here is what i got 
`Error: Google is indicating that we have some issue connecting to payment.`

**Comment by hyochan** [comment]
So [this](https://support.google.com/pay/answer/7644087?hl=en) can help you?

**Comment by gpatarin** [comment]
Think its related to #526

**Comment by gpatarin** [comment]
Some news! It appears its device related error, getting it working on one phone but not the other ...

**Comment by MeisterTea** [comment]
Same problem for me ! https://github.com/dooboolab/react-native-iap/issues/591

**Comment by kumarutsav111** [comment]
same problem for me too

**Comment by kumarutsav111** [comment]
why there is no solution available for it?
