### ISSUE TITLE
Question: Does this project supports Google Play Billing Library 2.0 ?

### ISSUE THREAD

**Issue by keima** [dooboolab/react-native-iap#544]
In Google I/O 2019, Google released Google Play Billing Library 2.0 contains Pending Transaction( such as support iOS Promoting purchase ), Developer Payload support, and API changes.
Most important things is purchases must be acknowledged within three days.
(BTW, Google explained Billing Library 2.0 EoL comes 2021, same as this project currently uses 1.x)

- https://developer.android.com/google/play/billing/billing_library_releases_notes#release-2_0

Does this project supports Google Play Billing Library 2.0 ?

### Version of react-native-iap
N/A

### Version of react-native
N/A

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
N/A

### Actual behavior
N/A

### Tested environment (Emulator? Real Device?)
N/A

### Steps to reproduce the behavior
N/A

**Comment by hyochan** [comment]
@keima This is built with `2.0.1` see [Link](https://github.com/dooboolab/react-native-iap/blob/3dd4c7fb2444936285167b456dbbb81fbbe6f6c9/android/build.gradle#L49). However, `feature` like `acknowledging purchases` are not yet supported. We need community help. Maybe you can have a change 😃

**Comment by mifi** [comment]
Acknowledging purchases is very important, or else they will be cancelled automatically after 3 days (or 5 minutes in license test environment). I think this is something we should at least write about in the readme, and maybe also implement. I implemented acknowledge in backend using this library:
https://github.com/googleapis/google-api-nodejs-client/
androidpublisher.purchases.subscriptions.acknowledge

**Comment by hyochan** [comment]
@mifi Thanks for issue! I've just realized that this is very important after you've pointed out. I knew that `acknowledgePurchase` feature as rises in `android` but missed out that this will be cancelled automatically.. I am planning to release this is 3.2.0 in #557.

**Comment by hyochan** [comment]
@mifi Could you do me a favor? When 3.2.0 is merged, I hope you can provide us a way to `acknowledgePurchase` in backend for user below < 3.2.0 and above > 2

**Comment by mifi** [comment]
Awesome work man! Do you mean an example for how to do it in backend? It will depend on what kind of backend technology, but I have code in Node.js, I could share some of that

**Comment by hyochan** [comment]
@mifi It would be nice if you provide your sample code in `acknowledging purchase in backend` before readme on [#acknowledge-purchase-in-android](https://github.com/dooboolab/react-native-iap#acknowledge-purchase-in-android)

It would look like (below is just an example)
### Acknowledging purchase in the backend
Since `acknowledgePurchase` has been implemented in `3.2.0`, you should `acknowledgePurchase` in your backend when you are using below version `3.2.0`.
```
(your code)
```

Hope you can give us a `PR` to help others.

**Comment by tobiaseisenschenk** [comment]
Do we still need an example for validating a purchase in node?

**Comment by hyochan** [comment]
It's preferred to validate `receipt` on your backend.

**Comment by tobiaseisenschenk** [comment]
> It's preferred to validate `receipt` on your backend.

yes :)
But above you asked for a PR to update docs with the required backend code. I could not find it so I was wondering if I should do it.

**Comment by hyochan** [comment]
@tobiaseisenschenk That will be highly appreciated!!

**Comment by mifi** [comment]
I pulled out the gist of subscription validation handling in Node.js from my working production code. It's a bit long to put inside readme, so I put it in a github repo:
https://github.com/mifi/in-app-subscription-example

**Comment by hyochan** [comment]
@mifi Really cool~ Thanks for this! Well, I think you can still put that in our `readme` to for user to direct to that repo.
