### ISSUE TITLE
App rejected after review because in app purchases don't work on an emulator

### ISSUE THREAD

**Issue by NickyYo** [dooboolab/react-native-iap#547]
### Version of react-native-iap
3.0.0
### Version of react-native
0.59.9
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
App store approval of app
### Actual behavior
App store rejecting app because in app payments don't work on an emulator, receiving error message "cannot connect to iTunes Store"
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
Run on Emulator
<img width="264" alt="Screenshot 2019-06-21 at 23 26 34" src="https://user-images.githubusercontent.com/1761980/59954697-f1cbd100-947d-11e9-8ed1-a1bc5a9cdd46.png">

**Comment by hyochan** [comment]
Your information is not clear. You can't try buying purchases in emulator.
Also, this isn't a problem with your approval for app review. You may be missing something else.

**Comment by NickyYo** [comment]
Hi @hyochan , I followed the instructions exactly, tested the in app purchase on a real device and worked brilliantly but then when I submitted it the app got rejected. Apple responded with this and provided that screenshot above.
![Screenshot 2019-06-22 at 09 13 27](https://user-images.githubusercontent.com/1761980/59961329-1780c680-94ce-11e9-85ce-67710a9b163e.png)

**Comment by hyochan** [comment]
@NickyYo So I can't see anything about emulator

**Comment by defualt** [comment]
@NickyYo did you ever resolve this.  Same thing happened to me with Apple rejection because of the "Cannot connect to iTunes store" error. I can't reproduce the error.

**Comment by jagribble** [comment]
@defualt @NickyYo did you ever resolve this? The Apple app reviewers have pasted the same message to me 4 times now with no logs or screenshots. Any ideas would be helpful. Working fine for me on a real device both running from Xcode and test flight

**Comment by NickyYo** [comment]
> @defualt @NickyYo did you ever resolve this? The Apple app reviewers have pasted the same message to me 4 times now with no logs or screenshots. Any ideas would be helpful. Working fine for me on a real device both running from Xcode and test flight

Hey sorry for delay. The Apple App reviewers are hit and miss. I submitted the app again and explained in my testing description that in app payments don't work in a simulator and only work on a real device then the app was approved.
