### ISSUE TITLE
Build Failed With Logic Error (Yoga)

### ISSUE THREAD

**Issue by brkrtp** [dooboolab/react-native-iap#548]
### Tested environment (Emulator? Real Device?) EMULATOR

Build failed with no errors, but when remove the this library then build success. I dont understand whats the problem and what happening. Look the image for details...

<img width="276" alt="Screen Shot 2019-06-22 at 05 26 46" src="https://user-images.githubusercontent.com/18514716/59958394-bac1e380-94ae-11e9-835a-da9c9d0ca976.png">
<img width="1086" alt="Screen Shot 2019-06-22 at 05 26 51" src="https://user-images.githubusercontent.com/18514716/59958395-bb5a7a00-94ae-11e9-84a8-5833d186eb7a.png">

> The left expression of the compound assignment is an uninitialized value. The computed value will a

**Comment by hyochan** [comment]
I think this isn't related. I can't help you out without any further information.

**Comment by brkrtp** [comment]
> I think this isn't related. I can't help you out without any further information.

But without install this library everythink is going ok

**Comment by brkrtp** [comment]
Value stored to 'index' is never read

**Comment by Gaever** [comment]
@brkrtp I met this problem with react@16.9.0 (the latest at moment) and react-native@0.60.5.
Clean react-native init project contain react@16.8.6 in package.json. I downgraded react version in my project to 16.8.6 and build was complete successfully.
