### ISSUE TITLE
Android: Crashes when providing Old Subscription ID and Proration Mode = DEFERRED

### ISSUE THREAD

**Issue by mifi** [dooboolab/react-native-iap#555]
### Version of react-native-iap
3.0.0

### Version of react-native
0.59.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
App should not crash

### Actual behavior
App crashes after completing android purchase dialog

### Tested environment (Emulator? Real Device?)
Huawei P Smart 2018

### Steps to reproduce the behavior
- Create 2 subscriptions in Google Play, one monthly and one yearly
- Subscribe to monthly subscription. Works perfectly
- Subscribe to yearly subscription, with `Old Subscription ID` and `Proration Mode = DEFERRED` (4) sent to `RNIap.requestSubscription`
- App crashes without any java stack trace in react-native log-android
- NOTE! It works perfectly when not specifying any Proration Mode, so it is related to DEFERRED

By the way awesome job on this module! I'm happy that someone abstracted these crazy complex APIs a bit. This issue is not a dealbreaker because I can use other Proration Mode than DEFERRED but I thought I'd report it, and maybe someone can understand why this happens.

**Comment by hyochan** [comment]
Thanks for the detailed issue. Let's wait for those who can help us.

**Comment by iaphub** [comment]
See [this comment](https://github.com/dooboolab/react-native-iap/issues/888#issuecomment-660519819) regarding your issue with deferred subscriptions.

**Comment by andresesfm** [comment]
Documentation: https://github.com/dooboolab/react-native-iap/pull/1387
