### ISSUE TITLE
You can cancel the subscription and receive the result. If user cancelled the subscription in somewhere else, you can check this via `getAvailablePurchases`.

### ISSUE THREAD

**Issue by StudyTae** [dooboolab/react-native-iap#561]
You can cancel the subscription and receive the result. If user cancelled the subscription in somewhere else, you can check this via `getAvailablePurchases`.

_Originally posted by @hyochan in https://github.com/dooboolab/react-native-iap/issues/538#issuecomment-503390087_

**Comment by StudyTae** [comment]
https://github.com/dooboolab/react-native-iap/issues/531#issuecomment-502900967  

As you can see from this link, I've already used this function, but I've returned an empty array.

**Comment by hyochan** [comment]
I've had quite busy days in `2.+` version of `react-native-iap` and I've lately realized `getAvailablePurchases` didn't work as expected for some reason (quite not sure yet). I've managed to fix this in `3.0.0` and later version.
