### ISSUE TITLE
Migration to android x fails other app dependencies

### ISSUE THREAD

**Issue by varungupta85** [dooboolab/react-native-iap#562]
### Version of react-native-iap
3.2.2
### Version of react-native
0.59.9
### Platforms you faced the error (IOS or Android or both?)
Android
### Steps to reproduce the behavior
After moving to the latest package, I am not able to build my app project because it is not able to find some android compat libraries because `react-native-iap` has started using `Android X`. Is there a specific reason, this package has been moved to `Andorid X`.

**Comment by hyochan** [comment]
@varungupta85 We've managed to move forward to support `react-native@0.60+` which will be coming soon.
