### ISSUE TITLE
Flow types broken (expoert type PurchaseError)

### ISSUE THREAD

**Issue by jpolo** [dooboolab/react-native-iap#563]
### Version of react-native-iap
3.2.2

### Version of react-native
Does not matter

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
```
export type PurchaseResult = {
  responseCode: number,
  debugMessage: string,
}

export type PurchaseError = {
  responseCode: number,
  debugMessage: string,
}
```

### Actual behavior
```
expoert type PurchaseResult = {
  responseCode: number,
  debugMessage: string,
}

expoert type PurchaseError = {
  responseCode: number,
  debugMessage: string,
}
```

### Steps to reproduce the behavior

This is the third typing problem that I report, it is time to address the root problem : any contributor can break the typing without knowing it. The solution : tests !

Here is what I suggest : create a "npm run validate" script that would run every check possible : lint && typescript test && flow test && unit tests .

This scripts can be used for the CI or a git hook (using husky) to prevent any contributor to break the version.

**Comment by hyochan** [comment]
@jpolo Great idea on `validation`. Would you kindly give us a `PR` on this idea? It would be wonderful if you just create `npm run validate` script for us and I'll manage this in `ci`.
