### ISSUE TITLE
Am getting error : The sku was not found. Please fetch products first by calling getItems

### ISSUE THREAD

**Issue by binil1931** [dooboolab/react-native-iap#566]
### Expected behavior
 After successful subscribe get the receipt

### Actual behavior
Subscription getting error 
"The sku was not found. Please fetch products first by calling getItems"
### Steps to reproduce the behavior

const itemSkus = Platform.select({
  ios: [
   ''
  ],
  android: [
   'sub_1'
  ]
 });

Step 1:
    async componentDidMount() {
      const msg = await RNIap.initConnection();
      const items = await RNIap.getProducts(itemSkus);
      RNIap.getProducts(items).then((products) => {
      }).catch((error) => {
       console.log("inApp getProducts error ",error.message);
      })
    }

Step 2: Call subscribe
    _subscribe(){
 
      RNIap.buySubscription('sub_1').then(purchase => {
        console.log("inApp Subscription transactionReceipt ",purchase.transactionReceipt);
       }).catch((error) => {
        console.log("inApp Subscription error",error.message);
       })
    }

it throws error "The sku was not found. Please fetch products first by calling getItems"

**Comment by carlosqsilva** [comment]
Same here

**Comment by hyochan** [comment]
You are buying subscription but using `getProducts`. Try using `getSubscription` instead.

**Comment by chetan-plrch** [comment]
I am facing the same problem even when I use getSubscriptions. Why is there a issue with this ?

**Comment by amitkamble60** [comment]
await RNIap.initConnection();
            const products = await RNIap.getSubscriptions(itemSkus);
            const subs = await RNIap.getAvailablePurchases();


i use the above code its working fine.
but when i go to subscribe item its shows error that item not available. check below code for subscribe item

RNIap.requestSubscription(itemSkus[0]).then((result) => {
                console.log('result request', result);
            }).catch((e) => {
                console.log('error request', e);
            });

i also cross verified the itemSkus i am using

**Comment by Benzer1406** [comment]
Facing the same issue with `getsubscriptions` but only on Android. Seems as if the function does not get invoked sometimes.

**Comment by Madhavan86** [comment]
Me too facing the same issue in android. Am getting 'The sku was not found. Please fetch products first by calling getItems'.
Can someone help me what is the problem in Android.
