### ISSUE TITLE
Purchase confirmation dialog alert style instead of IOS IAP dialog.

### ISSUE THREAD

**Issue by nohaapav** [dooboolab/react-native-iap#568]
### Version of react-native-iap

2.4.8

### Version of react-native

0.55.4

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

Purchase confirmation should be scrolled from bottom (iOS style)

### Actual behavior

Purchase confirmation is alert style dialog

### Tested environment (Emulator? Real Device?)

Real device -> TestFlight

### Steps to reproduce the behavior

Just call RNiap.buyProduct or RNiap.buySubscription for Non-Consumable item

See:

![image](https://user-images.githubusercontent.com/4179104/60106569-b96e1080-9765-11e9-87a4-580b1b5e4580.png)

Should looks like this i guess:

![image](https://user-images.githubusercontent.com/4179104/60107068-8c6e2d80-9766-11e9-8ce9-19978d78ea79.png)

Am i missing something ?

**Comment by hyochan** [comment]
This is expected in `sendbox` mode. It wil automatically change when you publish your app to `production`. Also related #222.
