### ISSUE TITLE
Getting issue after calling : RNIap.consumePurchaseAndroid(purchase.purchaseToken);

### ISSUE THREAD

**Issue by binil1931** [dooboolab/react-native-iap#569]
3.1.0 of react-native-iap

59 Version of react-native

### Expected behavior
RNIap.consumePurchaseAndroid(purchase.purchaseToken);
getting success response

### Actual behavior
getting error: The callback cosumeProduct() exists in module RNIapModule, but only one callback may be registered to a function in a native module

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

after getting purchase token just call
await RNIap.consumePurchaseAndroid(purchase.purchaseToken);

getting above error

**Comment by hyochan** [comment]
This happens when try to `invoke` native method when which hasn't been resolved yet. Could you please provide more codes which can help to solve the problem?
