### ISSUE TITLE
buySubscription/requestSubscription type mismatch

### ISSUE THREAD

**Issue by benoitdion** [dooboolab/react-native-iap#572]
### Version of react-native-iap
3.0.1

### Description
The return type for `buySubscritpion` and `requestSubscription` do not match. The old, deprecated api `buySubscription` returns a `Promise<SubscriptionPurchase>`. The new `requestSubscription` return a `Promise<string>`. It looks like they both use the same implementation, what should be the correct type?

**Comment by hyochan** [comment]
It should be `Promise<string | SubscriptionPurchase>` currently. However, if `buySubscription` is removed in the future, it will be `Promise<string`. Should be improved though! Hope you can give us a `PR`.

**Comment by benoitdion** [comment]
what do you think about returning a `Promise<void>` since we should now rely on `purchaseUpdatedListener`/`purchaseErrorListener `? It might also be better to remove `buySubscritpion` from 3.x.x instead of deprecating since the old flow doesn't work anymore without the listeners and purchase acknowledgment.

**Comment by hyochan** [comment]
@benoitdion Yes~! Thanks for sharing, I will keep this in mind for future updates.
