### ISSUE TITLE
buySubscription not works in Android

### ISSUE THREAD

**Issue by itsaberi** [dooboolab/react-native-iap#573]
### Version of react-native-iap
2.5.5
### Version of react-native
^0.59.9
### Platforms you faced the error (IOS or Android or both?)
Android

When I use buySubscription(SKU) it never backs any values and stuck there. My SKU for the test is 'android.test.purchased'

**Comment by hyochan** [comment]
How did you used it? 
`await buySubscription`?

**Comment by itsaberi** [comment]
I used it like this
const purchase = await RNIap.buySubscription(sku);

**Comment by hyochan** [comment]
Wrap that with `try` and `catch` statement please to see the error message.

**Comment by itsaberi** [comment]
I try it and catch the error "That item is unavailable."

**Comment by hyochan** [comment]
@itsaberi Well then this is expected. You can't use `android.test.purchased` for android `subscription`. Please follow [stackoverflow](https://stackoverflow.com/questions/16189461/test-subscription-feature-of-in-app-billing) and [android doc](https://developer.android.com/google/play/billing/billing_subscriptions#testing-subscriptions).
