### ISSUE TITLE
Error retrieving information from server [DF-DFERH-01] when calling requestPurchase

### ISSUE THREAD

**Issue by emilioicai** [dooboolab/react-native-iap#576]
### Version of react-native-iap

3.2.3

### Version of react-native

0.59.9

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

`RNIap.requestPurchase('valid.sku');` should allow users to buy products in production

### Actual behavior

A popup showing `Error retrieving information from server [DF-DFERH-01]` keeps appearing after clicking on the `Buy now` button

### Tested environment (Emulator? Real Device?)

Real Devices (Samsung Galaxy J7 and Pocophone)

### Steps to reproduce the behavior

call `RNIap.requestPurchase` after proper initialisation:

```
await RNIap.initConnection();
const purchases = await RNIap.getAvailablePurchases();
```

**Comment by emilioicai** [comment]
I guess my products, store and test users are fine as everything was working before moving to `react-native-iap` 3.2.3

**Comment by hyochan** [comment]
@emilioicai I think you should upload new `apk` if you had the previous version.

**Comment by emilioicai** [comment]
@hyochan I did, I was trying from an alpha track with a test user. Anyway, suddenly it started working on its own. For anyone having this issue: I think google play takes a while to process apps switching from billing 1.X to billing 2.X, if you are seeing the DF-DFERH-01 error just wait some hours (8 in my case) and try again.

thanks @hyochan !
