### ISSUE TITLE
Unable to build iOS project using v3

### ISSUE THREAD

**Issue by varungupta85** [dooboolab/react-native-iap#577]
### Version of react-native-iap
3.2.2
### Version of react-native
0.59.9
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Build project successfully
### Actual behavior
Failing with build errors in RNIap
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
Add RNIap v3 to a project, perform the linking and observe the errors shown in below screenshot

![Screenshot 2019-07-02 at 5 24 01 PM](https://user-images.githubusercontent.com/7475133/60511016-935ce900-9cee-11e9-9a6e-6ec743e47060.png)

**Comment by hyochan** [comment]
Please try `3.2.4`.

**Comment by hyochan** [comment]
@varungupta85 Please try `3.2.4`.

**Comment by paolospag** [comment]
@hyochan `react-native-iap@3.2.4` doesn't seem to resolve the problem, I'm using `react-native@0.60.0-rc.3`.

I think it's related to the iOS version (presumably under 12.2). I'm trying to update Xcode from 10.1 to 10.2.1 as suggested [here](https://github.com/dooboolab/react-native-iap/issues/465#issuecomment-506897256) and I'll let you know if the problem is over.

Meanwhile, here are the details of the error:

```
info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:173:13: error: unknown type name 'SKPaymentDiscount'; did you mean 'SKProductDiscount'?

info             SKPaymentDiscount *discount = [[SKPaymentDiscount alloc]
            ^~~~~~~~~~~~~~~~~

info             SKProductDiscount

info In module 'StoreKit' imported from /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.h

info :3:

info /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKProductDiscount.h:21:53: note
: 'SKProductDiscount' declared here

info SK_EXTERN_CLASS_AVAILABLE(10_13_2, 11_2) @interface SKProductDiscount : NSObject {

                                                    ^

info 

info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:173:45: error: unknown receiver 'SKPaymentDiscount'; did you mean 'SKProductDiscount'?

info 
            SKPaymentDiscount *discount = [[SKPaymentDiscount alloc]
                                            ^~~~~~~~~~~~~~~~~

info 
                                            SKProductDiscount

info In module '
StoreKit

info ' imported from 

info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.h

info :

info 3

info :

info /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKProductDiscount.h:21:53
:

info  

info note

info : 

info 'SKProductDiscount' declared here


info SK_EXTERN_CLASS_AVAILABLE(10_13_2, 11_2) @interface SKProductDiscount : NSObject {
                                                    ^

info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:174:44:

info  error: 
no visible @interface for 'SKProductDiscount' declares the selector 'initWithIdentifier:keyIdentifier:nonce:signature:timestamp:'
                                           initWithIdentifier:discountOffer[@"identifier"]

                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m

info :

info 180
:

info 21
:
 

info error

info : 
property 'paymentDiscount' not found on object of type 'SKMutablePayment *'

info 
            payment.paymentDiscount = discount;

info 

info                     ^

info 

info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:211

info :
26
:

info  warning: incompatible pointer to integer conversion assigning to 'NSInteger' (aka 'long') from 'NSInteger *' (aka 'long *'); dereference with * [-Wint-conversion]
        payment.quantity = quantity;
                         ^ ~~~~~~~~
                           *(      )

info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:370:25

info : warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                    if (hasListeners) {
                        ^

                        self->

info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:
419:13: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]

info         if (hasListeners) {

            ^


info             self->

info 

info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:535:52

info : error
: property 'discounts' not found on object of type 'SKProduct *'


info         discounts = [self getDiscountData:[product.discounts copy]];
                                                   ^


info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:613:47:

info  error: 
property 'identifier' not found on object of type 'SKProductDiscount *'

info                 discountIdentifier = discount.identifier;

info                                               ^

info /Users/apple/Desktop/Eatviting/node_modules/react-native-iap/ios/RNIapIos.m:614:
34: error: property 'type' not found on object of type 'SKProductDiscount *'

info 

info                 switch (discount.type) {

info 

info                                  ^
```

**Comment by hyochan** [comment]
Ok let's invest this problem furture!

**Comment by maulikdhameliya** [comment]
![image](https://user-images.githubusercontent.com/12501230/60722540-d6b59280-9f4e-11e9-91ae-1b9fa83f68f5.png)

Guys I am also facing this build problem with Xcode Version 10.1 (10B61)

**Comment by varungupta85** [comment]
@hyochan Like other people have reported, I also updated to `3.2.4` and still observing the same problem.

**Comment by vuitv** [comment]
I have same problem

**Comment by maulikdhameliya** [comment]
@hyochan @varungupta85 @vuitv does anyone able to fix this problem?

**Comment by maulikdhameliya** [comment]
@hyochan can we maintain compatibility with Xcode Version 10.1 (10B61).
Is it possible to fix this issue with lower react-native-iap version?

**Comment by maulikdhameliya** [comment]
I have to downgrade to `"react-native-iap": "2.4.0"`  to fix build error

**Comment by sshallow** [comment]
I also encountered this problem, I saw that others solved it by downgrading, but the author suggested using version 3.2.0. I should downgrade or wait to fix this bug.

**Comment by sshallow** [comment]
> 我必须降级`"react-native-iap": "2.4.0"` 以修复构建错误

I am downgraded and still not working.

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/61436660-3ad84d80-a976-11e9-87e1-39dde874ffae.png)

I can't reproduce this in my `env`. So please generate minimal reproduction maybe sharing some codes.

**Comment by paolospag** [comment]
For me, the problem is Xcode: updating from 10.1 to 10.2.1 'm able to build correctly, but honestly I don't know if it works with iOS versions <= 12.1

**Comment by lc3t35** [comment]
Any news about that issue ?

**Comment by quyen91** [comment]
I am using Xcode 10.1 and same error occur. Then I update Xcode to 10.3. Xcode built successfully.

**Comment by ironworkshop** [comment]
Running into the same issue, on Xcode 10.1, going to get Xcode 10.3 dmg and run side by side to see if it solves it.

**Comment by maulikdhameliya** [comment]
@hyochan this issue seems to be compatible with Xcode > 10.2
Can we make it compatible with 10.1 please since many users can't upgrade their Xcode due to the limitation of upgrading OS ?

**Comment by lc3t35** [comment]
Thank you very much @doomsower, works fine on my side with XCode Version 10.1 (10B61) and rn-iap 3.4.0.
