### ISSUE TITLE
acknowledgePurchaseAndroid is not a function

### ISSUE THREAD

**Issue by eetlaa** [dooboolab/react-native-iap#579]
### Version of react-native-iap
3.2.3

### Version of react-native
v0.57.1 via Expo 32

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Acknowledge purchase with RNIap.acknowledgePurchaseAndroid as described in example

### Actual behavior
acknowledgePurchaseAndroid is not function

![Screenshot_20190703-173645](https://user-images.githubusercontent.com/38593869/60601156-4d6d5700-9dba-11e9-9344-95db19cfed75.png)

### Tested environment (Emulator? Real Device?)
Real device ONEPLUSA3003, LEX720, through Android Studio.

### Steps to reproduce the behavior
Eject expo project, add RNIap library and link manually and follow IapExample

**Comment by hyochan** [comment]
So does other methods works correctly?

**Comment by eetlaa** [comment]
Yes they do, also migrated to AndroidX with instructions on readme.

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/60632098-7b947a80-9e3e-11e9-9ee9-185719f47d4a.png)
I've just tested my own and it looks good to me.

**Comment by hyochan** [comment]
Please feel free to reopen `issue` if you still face the problem.

**Comment by Craigtut** [comment]
I've hit this issue as well, but for different reasons. I don't want to migrate to AndroidX yet so I'm trying to get away with using 3.0.1. 

acknowledgePurchaseAndroid simply doesn't exist in the codebase on 3.0.1. Was there another way to acknowledge purchase on android on 3.0.1? Or was this step not needed?

Or should I just not be trying to use 3.0.1 as it was incomplete?

**Comment by hyochan** [comment]
@Craigtut Ok. I understood your problem. I'll try to support `3.0.2` and include `acknowledgePurchaseAndroid` this weekend!

**Comment by Craigtut** [comment]
@hyochan - That would be amazing! Thank you so much

**Comment by hyochan** [comment]
Closed via #590. This is released to 3.0.2.
