### ISSUE TITLE
Finish transaction is called too quickly

### ISSUE THREAD

**Issue by solidfox** [dooboolab/react-native-iap#581]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2430%20Funded-%2300A156.svg" />](https://issuehunt.io/r/dooboolab/react-native-iap/issues/581)

### Version of react-native-iap
3.2.4

### Version of react-native
0.59.9

### Platforms you faced the error (IOS or Android or both?)
iOS (Android not yet confirmed)

### Expected behavior
1. A purchase goes through at the StoreKit side.
1. The receipt is sent to the react-native-iap subscription.
1. Something goes wrong and sending the receipt to the server fails.
1. User restarts the app.
1. StoreKit re-emits the SKPaymentTransactionStatePurchased event.
1. The receipt is sent to the react-native-iap subscription.
1. Receipt is sent to the app's server for validation and processing.
1. The purchased content is assigned to the user on the server.
1. The server acknowledges the delivery to the client.
1. The client finishes the StoreKit transaction through react-native-iap.

### Actual behavior
1. A purchase goes through at the StoreKit side.
1. **react-native-iap finishes the StoreKit transaction automatically.** 😱
1. The receipt is sent to the react-native-iap subscription.
1. Something goes wrong and sending the receipt to the server fails.
1. User has paid for content that was never delivered.
1. End of the world.

### Tested environment (Emulator? Real Device?)
This can be determined directly from this line of code: https://github.com/dooboolab/react-native-iap/blob/df1483db059cddeb6fd1244d583288e5e7f6b20e/ios/RNIapIos.m#L414

### Steps to reproduce the behavior

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $30.00)

- [<img src='https://avatars0.githubusercontent.com/u/27461460?v=4' alt='hyochan' width=24 height=24> hyochan](https://issuehunt.io/u/hyochan) ($30.00)
### Submitted pull Requests
- [#589 Fix #581 finishTransaction called automatically](https://issuehunt.io/r/dooboolab/react-native-iap/pull/589)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/dooboolab/react-native-iap/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by solidfox** [comment]
I'll go ahead and try to solve this on the iOS side but I'd be very happy if someone could tell me if this is handled on the Android side?

**Comment by solidfox** [comment]
This seems to serve the same purpose as [acknowledging a purchase](https://developer.android.com/google/play/billing/billing_library_overview#acknowledge) on Android so it should fit well into that existing api.

**Comment by hyochan** [comment]
Could you kindly support us with `PR` or any docs that we can go over?

**Comment by solidfox** [comment]
Absolutely, I'll try to make time to do a PR next week. In the meantime here is the apple documentation that explains that one should deliver the purchased material before calling finishTransaction and that SK will persist and keep providing the transaction to the observer until finish has been called.

The Provide Content and Finish the Transaction section in [this document](https://developer.apple.com/documentation/storekit/in-app_purchase/offering_completing_and_restoring_in-app_purchases#3195104)

**Comment by solidfox** [comment]
I believe the correct way to handle this would be to simply expose the finishTransaction method in the react-native-iap library. To avoid breaking changes I'd suggest adding a parameter `dangerouslyFinishTransactionAutomatically` to the requestPurchase function and default that too true. Then do console warnings for anyone not explicitly setting that parameter that they should update their flow. The parameter can then be removed or defaulted to false in v4.0.0.

**Comment by hyochan** [comment]
@solidfox Sounds great!! Looking forward for your `PR`!

**Comment by hyochan** [comment]
@solidfox How are you going with this? Would you prefer better performance if we can reward on the update? I will charge extra $30 for this for your help.

**Comment by solidfox** [comment]
@hyochan I started working on it today but got a bit caught up in getting the example running only to realize that the example isn't able to make purchases anyway so I guess I'll test it in my own use case.

I also noticed the remains of this commit that seems to be trying to achieve what I'm doing: https://github.com/dooboolab/react-native-iap/commit/edfbd12e46aed90ea0a36a6afe63e844fa96dd05

Only seems to be cruft left though so I guess it was removed at some point?

**Comment by solidfox** [comment]
Would it be possible to get access to the flow in the documentation to add in registering the purchase with the apps server and acknowledging / finishing the transaction?

**Comment by hyochan** [comment]
@solidfox Hey great request! If you tell me your email address, I'll invite you to that diagram in [draw.io](draw.io)

**Comment by solidfox** [comment]
@hyochan Thanks! You can send the invite to daniel.schlaug at gmail.

**Comment by hyochan** [comment]
@solidfox I've just shared the diagram to your `email`. Thanks!
