### ISSUE TITLE
Payment modal is not showing in several countries

### ISSUE THREAD

**Issue by mevanso01** [dooboolab/react-native-iap#585]
### Version of react-native-iap
^3.2.3
### Version of react-native
0.59.9
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
I hope it to show payment modal.
### Actual behavior
It works fine on android 9 in China. First time it didn't work, but soon after I installed 'Google Pay' app, it started working.
But it doesn't work in Turkey. Doesn't show payment modal even though the phone was already used to subscribe in other apps.
### Tested environment (Emulator? Real Device?)
I tested it in Real Device and Emulator.
### Steps to reproduce the behavior
This what I implemented.
```
const result = await RNIap.initConnection();
  if (!result) {
    return;
  }

  try {
    await RNIap.getSubscriptions(itemSubs);
    await RNIap.requestSubscription('blabla');
  } catch (err) {
    console.warn(err.code, err.message);
  }
```

I found that RNIap.getSubscriptions returns empty array in Real Device(android Pie) in Turkey, but not in China.

**Comment by hyochan** [comment]
@mevanso01 Thanks for the issue! If you face the different behavior in regions, I think it is the matter on google itself since `react-native-iap` only works as a `bridge` on integrating both `ios` and `android` `iap` module.

**Comment by mevanso01** [comment]
@hyochan Thanks for your kind reply. Then would you please help on fixing that issue?
Why it returns empty array in RNIap.getSubscriptions(itemSubs) funciton in android 9. In Turkey, the in-app purchase features works perfect on android 4 or 5 versions, but only android 9.
What can I do to fix this issue?

**Comment by hyochan** [comment]
@mevanso01 Honestly speaking, I'm not quite sure. Let's try to invest this with more people coming to the issue.

**Comment by gfpacheco** [comment]
I'm facing a similar issue here in Brazil: the `getSubscriptions` promise never resolves/rejects.

That only happens on alpha/beta/production tracks though.

In development/internal track it works just fine.

Any idea why/how to fix it?

**Comment by mevanso01** [comment]
The issue is fixed somehow. I think the tester in Turkey didn't test it with the latest internal test app.

**Comment by gfpacheco** [comment]
My problem was fixed when I migrated to Android bundle instead of APKs. I guess it had something to do with the signature. Now I'm facing another problem: the app crashes when I `requestSubscription`, but it's not relevant to this issue

**Comment by mevanso01** [comment]
You must invoke _initConnection_ and _getSubscriptions_ before _requestSubscription_.

```
  const result = await RNIap.initConnection();
  if (!result) {
  	// do something
    return;
  }

  try {
    await RNIap.getSubscriptions(itemSubs);
    await RNIap.requestSubscription('monthly1');
  } catch (err) {
    console.warn(err.code, err.message);
  }
```
