### ISSUE TITLE
Cannot connect to App Store - Production App

### ISSUE THREAD

**Issue by sturrock** [dooboolab/react-native-iap#587]
### Version of react-native-iap
^3.2.4

### Version of react-native
0.59.8

### Platforms you faced the error (IOS or Android or both?)
iOS - (Don't have android app yet)

### Expected behavior
User clicks to purchase a subscription and it should work 100% of the time.

### Actual behavior
User clicks to purchase subscription and it will work sometimes but most times they're getting "Cannot connect to the App Store"

### Tested environment (Emulator? Real Device?)
Real Devices - Production 

### Steps to reproduce the behavior
Not sure how to make it happen, but I thought it was all working fine, then Apple rejected my app and said the IAP's weren't working, so I tested it again and they were. 

One random time I tried to purchase and I got that "Cannot Connect to App Store" error, I closed and reopened the app and it was the same, then i turned the wifi off and it magically started working. I turned the wifi back on and it was still working, so must be something to do with the connection to the Apple servers. 

Any help would be good, Thanks

**Comment by jvandenaardweg** [comment]
I've had a similar experience once. App got rejected for the same reason, then I requested for a review without any changes and then it worked. It seems the Sandbox service the reviewers use might have hiccups every now and then. I can't really confirm if that's really the case...

**Comment by emilioicai** [comment]
I'm having this issue every now and then and always assumed this was an issue on Apple's side. I guess our best option is to handle these issues gracefully.

**Comment by garfiaslopez** [comment]
Happening right now :(

**Comment by jvandenaardweg** [comment]
I’m now also receiving this on production apps. Really random looking

**Comment by bjacog** [comment]
> Note: the reviewers do not use production, they still use the Sandbox environment. Only apps downloaded from the App Store use the Production environment.

Would be great to add this to the docs. If I have time I will submit a PR for this.

**Comment by mgreci** [comment]
This may or may not be known already but I never had success connecting to the App Store (errorCode = 0, unknown) in the iOS simulator but it worked every time when testing on a real device.
