### ISSUE TITLE
[android] Migration from 2.55 to 3.3.0 =>  Error: Google is indicating that we have some issue connecting to payment.

### ISSUE THREAD

**Issue by MeisterTea** [dooboolab/react-native-iap#591]
### Version of react-native-iap
3.3.0

### Version of react-native
0.58.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
     ```RNIap.getProducts(['android.test.purchased'])``` should work

### Actual behavior
Error: Google is indicating that we have some issue connecting to payment.

### Tested environment (Emulator? Real Device?)
Both

I had no issue with 2.55, any idea ?

**Comment by hyochan** [comment]
This looks related to #526. You need to upload new apk when migrating to `3.x` and then wait for few hours. Please feel free to reopen when this doesn't resolve your problem.

**Comment by MeisterTea** [comment]
i don't get it, in the linked issue has been resolved by signing the app with release key : why does it matter? It worked fine on < 3.x

Why would a new apk work? Again why do I have to wait a few hours? 

Also, I am working with android.test.purchased, so it's not a matter of hours as the fake product is already existing

Anyway, I will try unlinking and linking

**Comment by devagul93** [comment]
Hi @MeisterTea  did you resolve your issue?
I am also facing the same error.

**Comment by MeisterTea** [comment]
> Hi @MeisterTea did you resolve your issue?
> I am also facing the same error.

No, it is still broken

**Comment by elliotmoose** [comment]
+1

**Comment by elliotmoose** [comment]
> > Hi @MeisterTea did you resolve your issue?
> > I am also facing the same error.
> 
> No, it is still broken

Hi sorry, if it is still broken could you reopen the issue as I am facing a similar problem.

**Comment by MeisterTea** [comment]
I don't use the fake android purchases anymore. We switched to simply buying the actual products with the sandbox and it's working fine
