### ISSUE TITLE
_reactNativeIap.default.finishTransactionIOS in not a function

### ISSUE THREAD

**Issue by keeross** [dooboolab/react-native-iap#597]
### Version of react-native-iap
3.3.1

### Version of react-native
0.60.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Should finish transaction

### Actual behavior
Sends error `_reactNativeIap.default.finishTransactionIOS in not a function`

### Tested environment (Emulator? Real Device?)
Real device, iPhone XR

### Steps to reproduce the behavior
Hard to tell, I cleared the cache, build cache, yarn cache, nothing helps.

**Comment by keeross** [comment]
Okay, I guess it happens because there is no `finishTransactionIOS` in `index.d.ts`, overall all the index files are not in sync, this gives a mess while linking. I removed `.ts` and `.flow` files and had to import everything as `import * as RNIap from 'react-native-iap'` after what it worked.

**Comment by keeross** [comment]
Plus no `finishTransactionIOS` in `default` export object [here](https://github.com/dooboolab/react-native-iap/blob/064b1385b83a20515f7c63c42509bf407d437663/index.js#L517)

**Comment by tybq93** [comment]
In current document said iOS will auto finish transactions. So we do not need to call `finishTransactionIOS`, right? And i still cannot call `finishTransactionIOS` because the library said it's not exists.

**Comment by hyochan** [comment]
Please try `3.3.2`. There were missing `types` in `3.3.0` updates.

**Comment by hyochan** [comment]
@

> In current document said iOS will auto finish transactions. So we do not need to call `finishTransactionIOS`, right? And i still cannot call `finishTransactionIOS` because the library said it's not exists. so weird

If you pass `andDangerouslyFinishTransactionAutomatically` param to false, you will have to call `finishTransactionIOS`.
