### ISSUE TITLE
finishTransactionIOS is not a function

### ISSUE THREAD

**Issue by thekevinbrown** [dooboolab/react-native-iap#603]
### Version of react-native-iap
3.3.2

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Expected to be able to call finishTransactionIOS

### Actual behavior
```
Error occurred while submitting order TypeError: _reactNativeIap.default.finishTransactionIOS is not a function
    at SubmitOrderScene.componentDidMount$ (component.tsx:38)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:298
```

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

Implement payment flow setting `andDangerouslyFinishTransactionAutomatically` to `false`, then try to call `finishTransactionIOS` as per docs.

### Additional Notes

I saw #597, but this is not happening during my Typescript build, it's happening at runtime. Types are happy, but the function isn't actually there at runtime.

**Comment by matthewdschulman** [comment]
+1 same here

**Comment by karltaylor** [comment]
I'm currently getting this `"react-native-iap": "3.3.2",` and `"react-native": "0.61.5",`

What version did this get released?
