### ISSUE TITLE
consumePurchaseAndroid Not working in version 3.3.5

### ISSUE THREAD

**Issue by ashutosh-s** [dooboolab/react-native-iap#605]
### Version of react-native-iap
3.3.5

### Version of react-native
0.59.9

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
calling RNIap.consumePurchaseAndroid() should remove consumed packages from getAvailablePurchases()
### Actual behavior
Items still returning from getAvailablePurchases() and when we try to consume them it throws bellow error for every RNIap.consumePurchaseAndroid(purchase.purchaseToken) call
### Steps to reproduce the behavior

```
const availablePurchases = await RNIap.getAvailablePurchases();
availablePurchases.forEach((purchase)=>{
       // Each of this call is throwing below mentioned error
       RNIap.consumePurchaseAndroid(purchase.purchaseToken);
});

```

If there are 3 packages i get bellow error thrice and packages are still available in getAvailablePurchase()

Error: Google is indicating that we have some issue connecting to payment.
Error: Google is indicating that we have some issue connecting to payment.
    at createErrorFromErrorData (blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:15917:17)
    at blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:15869:27
    at MessageQueue.__invokeCallback (blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:16746:18)
    at blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:16477:18
    at MessageQueue.__guard (blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:16650:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:file:///5763777c-30bd-4220-b6d5-6644ff59a553:16476:14)
    at e (file:///usr/lib/react-native-debugger/resources/app.asar/js/RNDebuggerWorker.js:1:136705)

**Comment by hyochan** [comment]
It looks like the `connection` issue with google payment backend.

**Comment by ashutosh-s** [comment]
Hey @hyochan All other functionalities like make purchase, get packages are working, except RNIap.consumePurchaseAndroid(purchase.purchaseToken); otherwise RNIap.getAvailablePurchases() should not be working

**Comment by hyochan** [comment]
Are you sure you are trying to consume purchase that is consumable?

**Comment by ashutosh-s** [comment]
yes I am doing this

```
if (Platform.OS === 'android') {
            // If consumable (can be purchased again)
            RNIap.consumePurchaseAndroid(purchase.purchaseToken);
            // If not consumable
            RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken);
}
```
For non consumable I am sending acknoledgement and for  consumable I am  consuming

**Comment by hyochan** [comment]
I can't actually tell why this is happening right now. Could you also try `consumeAllItemsAndroid`?

**Comment by ashutosh-s** [comment]
Yes, I Just tried , It gives following error : 

```
YellowBox.js:67 Possible Unhandled Promise Rejection (id: 0):
Error: No purchases found
Error: No purchases found
    at createErrorFromErrorData (blob:file:///aba788d7-09e6-4f01-82e6-1ea46d6b8368:15917:17)
    at blob:file:///aba788d7-09e6-4f01-82e6-1ea46d6b8368:15869:27
    at MessageQueue.__invokeCallback (blob:file:///aba788d7-09e6-4f01-82e6-1ea46d6b8368:16746:18)
    at blob:file:///aba788d7-09e6-4f01-82e6-1ea46d6b8368:16477:18
    at MessageQueue.__guard (blob:file:///aba788d7-09e6-4f01-82e6-1ea46d6b8368:16650:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:file:///aba788d7-09e6-4f01-82e6-1ea46d6b8368:16476:14)
    at e (file:///usr/lib/react-native-debugger/resources/app.asar/js/RNDebuggerWorker.js:1:136705)
```

I am using this in sandbox enviroment

**Comment by hyochan** [comment]
@ashutosh-s Try using `await` using `consumePurchaseAndroid` and see the results.

**Comment by ashutosh-s** [comment]
I am getting this 

```
 Error: Google is indicating that we have some issue connecting to payment.
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at e (RNDebuggerWorker.js:1)
```

**Comment by hyochan** [comment]
I am not sure yet. Hope this can help https://support.google.com/googleplay/answer/1050566?hl=en-GB.

Also try to put developerPayload

**Comment by ashutosh-s** [comment]
I tried putting developer payload erlier . stuck from some time :-) appreciate all the help you have done so far

**Comment by tmjordan** [comment]
@hyochan @ashutosh-s Hi men, i have the same problem. It was working few times, then it stopped working and i receive the following error:
`The service is disconnected (check your internet connection.)`
I checked the connection and it's not the problem.
When using consumeAllItems, every items are consumed as expected but if we have non-consummables products, it is definitely a problem.
Hope guys will help me to have a solution to that problem.
Thanks

**Comment by tmjordan** [comment]
And please where can i find the developperPayload ?

**Comment by tmjordan** [comment]
I'm using `react-native-iap: 3.3.6  && react-native: 0.59.8`

**Comment by tmjordan** [comment]
I had to put await when calling acknowledgePurchaseAndroid or consumePurchaseAndroid. Looks like 'then statement' is not working. not sure why.
```
if (Platform.OS === 'android') {
            // If consumable (can be purchased again)
            await RNIap.consumePurchaseAndroid(purchase.purchaseToken);
            // If not consumable
            await RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken);
}
```
