### ISSUE TITLE
purchaseErrorListener

### ISSUE THREAD

**Issue by sshallow** [dooboolab/react-native-iap#609]
### Version of react-native-iap
^3.3.6
### Version of react-native
^0.59.10
### Error 
iOS，always call 7 times purchaseUpdatedListener

### Expected behavior
I have already purchased a subscription.Should the purchaseUpdatedListener method be called several times?
### Actual behavior
always call 7 times purchaseUpdatedListener
### Tested environment (Emulator? Real Device?)
iOS 12.3.1  iphone 7   real Device
### Steps to reproduce the behavior

my code:
```
async componentDidMount() {
    const value = await AsyncStorage.getItem('transactionReceipt');
    if (value !== null) {
      // We have data!!
    }
    this.purchaseUpdateSubscription = purchaseUpdatedListener((purchase: ProductPurchase) => {
      console.log('purchaseUpdatedListener', purchase);
      const receipt = purchase.transactionReceipt;
      if (receipt) {
        AsyncStorage.setItem("transactionReceipt",receipt);
      }
    });
    this.purchaseErrorSubscription = purchaseErrorListener((error: PurchaseError) => {
      console.log('purchaseErrorListener', error);
    });
    //.....
}
```

```
<TouchableOpacity  onPress={() => this._requestPurchase('com.******128')} >
```

```
async _requestPurchase(sku: string) {
    try {
      await RNIap.requestPurchase(sku, false);
    } catch (err) {
      console.warn(err.code, err.message);
    }
 }
```
![piaoju](https://user-images.githubusercontent.com/21257340/61780486-2e9c3680-ae35-11e9-8168-4a771acf9576.png)

**Comment by leethree** [comment]
have you called `finishTransactionIOS` to complete the transaction?

**Comment by sshallow** [comment]
> 你打电话`finishTransactionIOS`来完成交易吗？

No, I didn't call

**Comment by hyochan** [comment]
Anyone else experiencing same issue?

**Comment by hyochan** [comment]
It is all because you've called `await RNIap.requestPurchase(sku, false);` and didn't call `finishTransaction`. Closed for now.
