### ISSUE TITLE
for fast, how about use the api "SKPayment.paymentWithProductIdentifier(product_ID)" instead of "SKPayment.paymentWithProduct(theProd)" ?

### ISSUE THREAD

**Issue by 12343954** [dooboolab/react-native-iap#61]
### Version of react-native-iap
:^0.2.14

### Expected behavior
the purchase is very very slow ! i want to make it faster !

why don't you use the api "SKPayment.paymentWithProductIdentifier(product_ID)" ? 

i don't want to check the product_id in the validProducts (without `fetchProducts`).

`
```
for (int k = 0; k < validProducts.count; k++) {
        SKProduct *theProd = [validProducts objectAtIndex:k];
        if ([productID isEqualToString:theProd.productIdentifier]) {
            NSLog(@"\n\n\n Obj c >> InAppPurchase  :: purchaseItem :: Product Found  \n\n\n.");
            SKPayment *payment = [SKPayment paymentWithProduct:theProd];       **//it's too slow !**
            [[SKPaymentQueue defaultQueue] addPayment:payment];
            return;
        }
}
```

**Comment by 12343954** [comment]
![image](https://user-images.githubusercontent.com/1804003/37291854-8b0657b2-264a-11e8-8a81-906f18503969.png)

RNIap.buyItem().catch() // catch lots of codes < 0 ,what's means ?

**Comment by JJMoon** [comment]
OK.  According to document below, paymentWithProductIdentifier is deprecated.
https://developer.apple.com/documentation/storekit/skpayment/1623907-paymentwithproductidentifier 
But, I don't this this api slow down the purchasing process. The purchasing process in iOS takes times more than we usually expect. But, we will change that in the next deployment.

**Comment by 12343954** [comment]
thank you for reply! i know it !

but another question :
RNIap.buyItem(item) can receive the receipt , but in `VerifyReceipt` returns lots of code < 0 some times .
i see the inner exception, it shows "Unable to connect to the iTunes Store. " 
is it means i lost the purchase order, even the user paid the money ?!

thank you !

**Comment by 12343954** [comment]
![image](https://user-images.githubusercontent.com/1804003/37329463-dd4a07e2-26d8-11e8-9a18-04f081541f8f.png)

**Comment by JJMoon** [comment]
OK. If you got the receipt, your purchase transaction was successful.
The case of crash ? (the image above) looks like normal failure process.
Would you describe the steps more detail ?

**Comment by JJMoon** [comment]
@12343954 Any progress on this issue? We made some more protective code to iOS side. Would you try again? I will close this issue in the near future.
