### ISSUE TITLE
How to pass Apple Receipt to API call

### ISSUE THREAD

**Issue by byang8** [dooboolab/react-native-iap#611]
I'm having the issue of trying to pass the receipt value of RNIap.requestReceiptIOS() as a JSON to 
`
var data = {
  apple_request: [
    {
      subscription_number: "A-S00000004",
      // Apple Receipt 
      receipt_id: RNIap.requestReceiptIOS()  //This is supposed to be the Apple receipt:"MIIT5gYJ..." 
    }
  ]
};
`
Output - 

> Reponse: Promise {_40: 0, _65: 0, _55: null, _72: null}

_55 is where the Apple Receipt base64 is at. I need to pass the value to receipt_id.

I also tried following the usual script of running `.then` after a promise call
`var getPromise = Promise.resolve(getLastReceipt);
    getPromise.then(function(value){
      return value;
    });`

Which also returns as 

> Promise {_40: 0, _65: 0, _55: null, _72: null}

**Question is How do I turn a Promise into a JSON?**

**Comment by hyochan** [comment]
Can I see what `getLastReceipt` is doing in detail?

**Comment by byang8** [comment]
> Can I see what `getLastReceipt` is doing in detail?

getLastReceipt was an old method that I tried out and I have since removed it. 
But it essentially was just a `RNIap.requestReceiptIOS();` call where I tried to `.then` to read the promise.

**Comment by hyochan** [comment]
@byang8 Do you mean you've solved the problem? Please provide minimal reproduction if you still need help. Closed for now.

**Comment by byang8** [comment]
No I've yet to solve the problem. So far only hardcoding the receipt from the console works.
Here is the flow: 
```
getLastReceipt = async () => {
  var recentReceipt = await RNIap.requestReceiptIOS();
  var data = {
    apple_request : [
      {
        subscription_number: "A-S0000004",
        receipt_id: recentReceipt
      }
    ],
  }
  try { 
  const response = await fetch(appstore_url, { 
    method: 'POST',
    data,
    headers:{
      'API-TOKEN': 'secret_token'
    }
  });
  } catch(err) {
    throw Error(JSON.stringify(err));
  }
};
```
The issue in hand is that it cannot convert the RNIap.requestReceiptIOS() response to a JSON object because its a Promise<String>.

**Comment by byang8** [comment]
The solution to this issue was that the API call and and function that contained the JSON body needed to both be asynchronous calls. 
Wrapping:
```
async function getReceipt() {
    const latestReceipt = await RNIap.requestReceiptIOS();
    api.post(
      url,
      {
        apple_request: [
          {
            subscription: ${subscription_number},
            // Apple Receipt
            receipt_data: latestReceipt
          }
        ]
      },
      {
        headers: {
          "API-Token": ${api_token}
        }
      }
    );
  }
```

Api async/await call:
```
 const receiptCall = async () => await getReceipt(); 
```
