### ISSUE TITLE
I can't purchase real items which I created from Google Play Console

### ISSUE THREAD

**Issue by Ti-amo** [dooboolab/react-native-iap#612]
### Version of react-native-iap
^3.3.6

### Version of react-native
^0.60.0

### Platforms you faced the error (IOS or Android or both?)
Android
### Tested environment (Emulator? Real Device?)
Real Device

**Comment by hyochan** [comment]
You've posted wrong `react-native` version.
Also, please try [my guide](https://github.com/dooboolab/react-native-iap/issues/124#issuecomment-386593185) to resolve your issue.
