### ISSUE TITLE
How to test/debug? "This version of the application is not applicable for billing" in all situations unless when installed from Play Store

### ISSUE THREAD

**Issue by dancherb** [dooboolab/react-native-iap#617]
It's not possible to package an APK, upload to the Play console with a new version code, and then install on a physical device from the Play Store every time one line of code needs to be changed to see if things work (currently trying to debug error DF-DFERH-01, which seems to have hundreds of potential solutions). This is the case even when using "android.test.purchased". 

Is this to do with having app signing managed by Google - how are people handling this?

**Comment by dancherb** [comment]
Well things have randomly started working (on both the "not applicable for billing" error and "DF-DFERH-01"). Here are the fairly unhelpful notes I made for myself when debugging future projects, in case they help anyone:

```
install test app on a device from the Play store; then, uninstall it and run "react-native run-android --variant=release" - this seems to avoid "not configured for billing"

to solve error DF-DFERH-01, use buyProduct instead of buySubscription (even for a subscription)

buyProduct crashes on success if using this instead of buySubscription. however, after testing and it worked with buyProduct, I changed back to buySubscription and buySubscription now worked again.

in between this time, I also uploaded a new version to the Play console (1.3 build 2 instead of 1.3 build 1). this may have had some effect on both errors (if in doubt, upload a new binary?)
```

**Comment by Raymond-Cox** [comment]
I'm currently facing random errors as well. It makes it extremely difficult to debug when you have to submit it to the store before you can even test your changes.  I tried @dancherb suggestions on how to get passed "not configured for billing" but they didn't work for me.

**Comment by mathews-p** [comment]
If all the settings are ok and still you are getting **Error- "_This version of the application is not configured for billing through Google Play. Check the help center for more information."**

Please edit your In-App Products pricing in Play store or Deactivate and Activate the In-App products. This will solve the issue.
