### ISSUE TITLE
Error: That item is unavailable.

### ISSUE THREAD

**Issue by Proxy08** [dooboolab/react-native-iap#618]
### Version of react-native-iap
    "react-native-iap": "3.0.2"
### Version of react-native
      "react-native": "0.59.2"
### Platforms you faced the error (IOS or Android or both?)
       Android
### Expected behavior
popup Google play buy
### Actual behavior
Error: That item is unavailable.
### Tested environment (Emulator? Real Device?)
Real device 
### Steps to reproduce the behavior
         import RNIap, {
          Product,
          ProductPurchase,
          acknowledgePurchaseAndroid,
           purchaseUpdatedListener,
           purchaseErrorListener,
              PurchaseError,
             } from 'react-native-iap';
             const itemSkus = Platform.select({
                 android: [
                  'xxx',
                   'xxx',
                   'android.test.purchased',
                    ]
              });

        const result = await RNIap.initConnection();
          RNIap.getProducts(itemSkus).then((products) => {
              this.setState({
                  products
              });

          requestSubscription = async (sku) => {
            try {
              RNIap.requestSubscription(sku);
           } catch (err) {
            console.log(err.message);
              }
          }
              
When I try to buy my product I got that error,  but when I use android.test.purchased it works

**Comment by hyochan** [comment]
Please go over [my guide](https://github.com/dooboolab/react-native-iap/issues/124#issuecomment-386593185) to resolve your issue.

Please feel free to reopen when you still have a problem.

**Comment by Proxy08** [comment]
I followed your guide, but this not working, I used a signed apk on a real device, but I'm still getting that error

**Comment by NarekChang** [comment]
Try it. Work for me:

"You need additionally add your testing account to another special list of accounts "Gmail accounts with testing access", you can find that on play account setting(not project!). On the page where you can see a list of your projects go to settings, and then on "Account details" page (scroll down, it's almost in the bottom of page) you will find the "Gmail accounts with testing access" list."

**Set up application licensing**
To set up application licensing, start by adding your list of tester's Gmail addresses in the Play Console. 

1. Go to your Play Console.
2. Select Settings Settings > Account details.
3. Under "License Testing," add your testers' Gmail addresses.
4. At the top of the screen, select Save.

**Comment by DevrealmEOOD** [comment]
What worked for me (after all of the above points) was to set a version of the app to Alpha phase in the Google Play Console and then open the alpha testing link on the device that I test with. There I accepted the testing invitation and only after that I could actually buy the products in my app.

**Comment by aravi365** [comment]
I tried all those workarounds mentioned here but still i get that weird error : ' The item that you were attempting to purchase could not be found'.

**Comment by yemd** [comment]
I have the exact same issue, my signed bundle is on the alpha channel (unreviewed), I tried both Release builds, Debug builds, Simulator, Real device, I can fetch the subscriptions correctly but impossible to make a purchase.

Should I wait for Apple to review the alpha release first?

**Comment by aleena-adnan1** [comment]
any solution to this @menloai  ?

**Comment by radiosilence** [comment]
@wemow did releasing to Alpha resolve this?

**Comment by Fevziyildizhan** [comment]
> @wemowAlpha'ya yayınlamak bunu çözmek mü? Aynı sorun bende de var - ürünleri getirebiliyorum ancak satın alma çabamda `E_ITEM_UNAVAILABLE`. . Şu anda sadece yerel hata ayrıntılarını kullanarak IAP'leri test etmek istiyorum ancak yardımcı olması durumunda alpha'ya bir AAB göndereceğim.

ben teste filan yüklemedim satın almaya çalıştığım zaman satın almaya çalıştığınız öğe bulunamadı diyor debug ta çalışıyorum

**Comment by leaguefun** [comment]
react-native-iap : 12.15.2
react-native : 0.75.2

I created a new app in google play console, created a new subscription, published as alpha release, but still got the "Item is unavaiable" error

By the way, On IOS, there is able to bring up the in-app purchase popup at least .... 

I am still finding any way to figure it out, anyone got the same issues ?

> purchaseErrorListener {"code": "E_ITEM_UNAVAILABLE", "debugMessage": "", "message": "That item is unavailable.", "responseCode": 4}

**Comment by leaguefun** [comment]
react-native-iap : 12.15.2
react-native : 0.75.2

@radiosilence Did you solve your issue yet ? I got this issues too. 
Whatever I tried below, there is still got the same error ....
- Create new app and new subscription on the same developer account
- Create new app and new subscription on another developer account
- Use different android device and license test account
- Whatever is closed testing, open testing 

I think there are many developer using this library, is there anyone got this fixed before ? please kindly give me some hints, I would be so appreciate, many thanks.

**Comment by shaquibimdad** [comment]
> react-native-iap : 12.15.2 react-native : 0.75.2
> 
> @radiosilence Did you solve your issue yet ? I got this issues too. Whatever I tried below, there is still got the same error ....
> 
> * Create new app and new subscription on the same developer account
> * Create new app and new subscription on another developer account
> * Use different android device and license test account
> * Whatever is closed testing, open testing
> 
> I think there are many developer using this library, is there anyone got this fixed before ? please kindly give me some hints, I would be so appreciate, many thanks.

Steps i fixed on latest  IAP checked out at [22ac0875](https://github.com/hyochan/react-native-iap/commit/22ac087568762c5921b112b1147d509b9f962a4b)

Do a release build and sign bundle with release keys (important)
upload the bundle and release to the internal testing or any track 
 
create email list and add the email for testing as pointed below

![image](https://github.com/user-attachments/assets/037859f7-f07a-4ef0-9d1a-5402a83eef54)

now download app from play store as shown from below pointed link of internal testing track

![image](https://github.com/user-attachments/assets/91b12478-0045-4e56-8ebf-ddb4d87d40cd)

now the iap will work fine


and if you sign your debug builds with release keys it might work in dev builds too (not sure about this)

**Comment by syedtehrimabbas** [comment]
> > react-native-iap : 12.15.2 react-native : 0.75.2
> > [@radiosilence](https://github.com/radiosilence) Did you solve your issue yet ? I got this issues too. Whatever I tried below, there is still got the same error ....
> > 
> > * Create new app and new subscription on the same developer account
> > * Create new app and new subscription on another developer account
> > * Use different android device and license test account
> > * Whatever is closed testing, open testing
> > 
> > I think there are many developer using this library, is there anyone got this fixed before ? please kindly give me some hints, I would be so appreciate, many thanks.
> 
> Steps I followed to fix on latest IAP checked out at [22ac0875](https://github.com/hyochan/react-native-iap/commit/22ac087568762c5921b112b1147d509b9f962a4b)
> 
> Do a release build and sign bundle with release keys (important) upload the bundle and release to the internal testing or any track
> 
> create email list and add the email for testing as pointed below
> 
> ![image](https://github.com/user-attachments/assets/037859f7-f07a-4ef0-9d1a-5402a83eef54)
> 
> now download app from play store as shown from below pointed link of internal testing track
> 
> ![image](https://github.com/user-attachments/assets/91b12478-0045-4e56-8ebf-ddb4d87d40cd)
> 
> now the iap will work fine
> 
> and if you sign your debug builds with release keys it might work in dev builds too (not sure about this)

You saved my day, Man.
