### ISSUE TITLE
undifined "Cannot read porperty 'buyProduct' of undefined "

### ISSUE THREAD

**Issue by sshallow** [dooboolab/react-native-iap#621]
### Version of react-native-iap
    "react-native-iap": "^3.3.7"
### Version of react-native
    "react-native": "^0.59.10",
### Platforms you faced the error (IOS or Android or both?)
iOS,RNIap.requestSubscription(sku), undifined "Cannot read porperty 'buyProduct' of undefined "

### Tested environment (Emulator? Real Device?)
Real Device,ip7,ios 12,sandbox

### my code 
```
async _requestSubscription() {
    let index = this.refs["premiumOverlay"].getIndex();
    if (index > 0 && index < 10) {
      this.setState({premiumVisible:false})
      action.showLoading();
      let sku = this.state.iosSkus[index-1];
        try {
        await RNIap.requestSubscription(sku);
        action.dismissLoading();
      } catch (err) {
        console.warn(err.code, err.message);
        action.dismissLoading();
      }
    }
  }
```
### Steps to reproduce the behavior
![IMG_7A51C1618025-1](https://user-images.githubusercontent.com/21257340/62350345-0ac3a980-b535-11e9-993b-16fb5beb531d.jpeg)

**Comment by pouya92** [comment]
Hi, I'm getting same error, how did you manage to solve that?

**Comment by pouya92** [comment]
I found out, it needed to connect library manually.
