### ISSUE TITLE
I can't understand 'yourAPI.deliverOrDownloadFancyInAppPurchase'

### ISSUE THREAD

**Issue by magic990619** [dooboolab/react-native-iap#622]
I have read your new iap workflow and follow guide.
But 'yourAPI.deliverOrDownloadFancyInAppPurchase(purchase.transactionReceipt)'
Here what is 'yourAPI'?
please help me to understand.
Thanks.

**Comment by magic990619** [comment]
yourAPI means my backend API. :)
When user purchases in app products, I have to call backend api that gives some coins etc...

**Comment by Keurdange** [comment]
Can you please share an example of your backend API?

**Comment by alordiel** [comment]
> Can you please share an example of your backend API?

From a [youtube tutorial](https://www.youtube.com/watch?v=9kXF-IrJ_SI) there is an node.js backend [example](https://github.com/EuanMorgan/AndroidRNIAPTutorial/blob/main/backend-code.js) covering the android part.
