### ISSUE TITLE
When purchasing a subscription, the Promise resolves prior to the final confirmation modal closing

### ISSUE THREAD

**Issue by dphaener** [dooboolab/react-native-iap#626]
### Version of react-native-iap
3.3.7

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
iOS only

### Expected behavior
When requesting a subscription purchase, the promise should not resolve until the purchase is completely finished and the confirmation modal has closed.

### Actual behavior
The promise resolves when the purchase is completed, but there is still a success confirmation modal open. This allows more code to execute before it should in some cases.

Sample use case:
* A user purchases a subscription via IAP
* We attempt to tell our servers about this purchase and deliver the content
* There is a bad network connection and this fails
* We attempt to tell the user about this via a react native modal
* User never sees it because the confirmation modal is still open

### Tested environment (Emulator? Real Device?)

Tested on both a simulator and an iOS device, same behavior. This is in Sandbox mode only, have not tested this behavior yet in production.

### Steps to reproduce the behavior

See above.

**Comment by dphaener** [comment]
Side note here. As I have not yet tested this in production, this may be a moot point if that modal doesn't pop up. I know that the sandbox and production environments are vastly different for IAP. I will check back once we have tested in TestFlight.

**Comment by jvandenaardweg** [comment]
Those modals also appear when using TestFlight, even for Apple reviewers.

 Only “live” apps from the App Store do not have the modals/alerts.

Just show your modal when you want to, you should be fine when users download your app from the App Store

**Comment by dphaener** [comment]
@jvandenaardweg Thanks for the follow up and confirmation! I'll go ahead and close this since it's only an issue in sandbox mode.
