### ISSUE TITLE
'purchase-updated' is not supported event type for RNIapIos

### ISSUE THREAD

**Issue by Bang9** [dooboolab/react-native-iap#627]
### Version of react-native-iap
3.3.8

### Version of react-native
0.60.4

### Platforms you faced the error (IOS or Android or both?)
iOS only
### Expected behavior
add purchaseUpdatedListener

### Actual behavior
exception 'purchase-updated' is not supported event

### Tested environment (Emulator? Real Device?)
real device

I checked 'purchase-updated'  is already listed on supportedEvents

![image](https://user-images.githubusercontent.com/26326015/62595571-d6c3fc00-b919-11e9-8360-9778e6f0e199.png)

So I tried below, but not working
```
remove ios/Pods and ios/Podfile.lock
pod install
xcode clean and build
yarn start --reset-cache
```

### Steps to reproduce the behavior
Run this code on iOS
```
let purchaseUpdateSubscription = null;
purchaseUpdateSubscription = RNIap.purchaseUpdatedListener(async (purchase) => { ... });
```

![image](https://user-images.githubusercontent.com/26326015/62592478-3e744a00-b90e-11e9-8887-b518e59f8c1c.png)

**Comment by hyochan** [comment]
It feels like you’ve not properly linked the updated module

**Comment by Bang9** [comment]
> It feels like you’ve not properly linked the updated module
@hyochan Sorry I feel same, I checked now current example project working properly
WIP migrated from 2.5.5, I'll share the solution when I resolved this issue
thanks

**Comment by Bang9** [comment]
I tried to resolve this issue like below

```
1. remove node_modules, remove pods, clear all cache, reinstall all dependencies
-> not linked properly

2. remove react-native-iap, step1, install app, checking remove dependencies properly,
remove app, install react-native-iap, clear build, install pods
-> not linked properly

3. step 1, added 'react-native-iap' to react-native.configs.js with null option and linking manually
-> not linked properly

4. remove repo, clone repo
-> working ¯\_(ツ)_/¯
```
