### ISSUE TITLE
Subscription can't be purchased again

### ISSUE THREAD

**Issue by abdallaemadeldin** [dooboolab/react-native-iap#629]
### Version of react-native-iap
3.3.7
### Version of react-native
0.59.4
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
after purchase end i can purchase new subscription
### Actual behavior
always said we are unable to change your subscription plan. manage subscriptions.
### Tested environment (Emulator? Real Device?)
Real Devices
### Steps to reproduce the behavior
1- init connection
2- set listeners
3- get subscriptions
4- request subscription
5- on success save receipt and use RNIap.consumePurchaseAndroid(purchase.purchaseToken);
6- continue in app lifecycle
7- when i go to google play and unsubscribe and wait for free trial time to end and try to buy new subscription the error occurred

`
if (Platform.OS === 'ios') {
                                RNIap.finishTransactionIOS(purchase.transactionId);
                            } else if (Platform.OS === 'android') {
                                RNIap.consumePurchaseAndroid(purchase.purchaseToken);
                            }
`

**Comment by hyochan** [comment]
The `subscription` should be `acknowledge` not `consume`

**Comment by jvandenaardweg** [comment]
That’s how it suppose to work. A subscription is a one time thing once its active

**Comment by abdallaemadeldin** [comment]
you mean that when i buy subscription and it end i can't purchase it again?

**Comment by smsmdida** [comment]
@abdallaemadeldin exactly, subscription can be purchased only once
