### ISSUE TITLE
Force Close after Buy Item android.item.canceled

### ISSUE THREAD

**Issue by juragansandhy** [dooboolab/react-native-iap#63]
### Version of react-native-iap
^0.2.17

After i testing to buy item android.item.canceled. My Apps is force close.
Would you like to fixing them?

This is log when apps force close

`03-14 10:12:44.340  1497 13372 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
03-14 10:12:44.341  3353  3353 W BillingHelper: Couldn't find purchase lists, trying to find single data.
03-14 10:12:44.341  3353  3353 W BillingHelper: Received a bad purchase data.
03-14 10:12:44.342  3353  3353 W BillingHelper: Couldn't find single purchase data as well.
03-14 10:12:44.342  3353  3353 D RNIapModule: Purchase Updated Listener
03-14 10:12:44.342  3353  3353 D RNIapModule: responseCode: 0
03-14 10:12:44.343  3353  3353 D AndroidRuntime: Shutting down VM
03-14 10:12:44.343  3353  3353 E AndroidRuntime: FATAL EXCEPTION: main
03-14 10:12:44.343  3353  3353 E AndroidRuntime: Process: com.lelangapps, PID: 3353
03-14 10:12:44.343  3353  3353 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule$8.onPurchasesUpdated(RNIapModule.java:422)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6321)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
03-14 10:12:44.343  3353  3353 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
03-14 10:12:44.344  1810  1810 V PhoneStatusBarPolicy: updateManagedProfile mManagedProfileFocused: false mManagedProfileInQuietMode: false mKeyguardVisible: false mCurrentUserId:0 mCurrentProfileId:0 mSecondSpaceStatusIconVisible: true showIcon:false
03-14 10:12:44.344  1810  1810 D EventBus: [1810, u0] send(AppTransitionFinishedEvent)
03-14 10:12:44.344  1810  1810 D EventBus: [1810, u0]  -> ForcedResizableInfoActivityController [0x3c261e4, P1] onBusEvent(AppTransitionFinishedEvent)
03-14 10:12:44.344  1810  1810 D EventBus: [1810, u0] onBusEvent(AppTransitionFinishedEvent) duration: 21 microseconds, avg: 1131
`

**Comment by dooboolab** [comment]
@juragansandhy Thank you for the bug report. We are now working on the major update in the module which will come as `0.3.0`. We are trying hard to release it in this month. Hope you can try that version!

**Comment by juragansandhy** [comment]
@dooboolab okay i will try that version when that version is available

**Comment by dooboolab** [comment]
@juragansandhy `0.3.0-alpha` has been released. Please try it out.
