### ISSUE TITLE
Can't upgrade existing subscription

### ISSUE THREAD

**Issue by Chehow** [dooboolab/react-native-iap#631]
### Version of react-native-iap
3.39

### Version of react-native
message

### Platforms you faced the error (IOS or Android or both?)
IOS only (android works fine)

### Expected behavior
Can be able to change current subscription with requestSubscription method

### Actual behavior
E_UNKNOWN error in purchaseErrorListener (But before this I get success alert )

### Tested environment (Emulator? Real Device?)
Real Device + Sandbox

### Steps to reproduce the behavior
1. requestSubscription('monthly')
2. Success
3. Current subscription is active
3. requestSubscription('yearly')
4. Error

**Comment by hyochan** [comment]
Closed since its related to #525
