### ISSUE TITLE
Promise returned by requestSubscription never resolved

### ISSUE THREAD

**Issue by Chehow** [dooboolab/react-native-iap#632]
### Version of react-native-iap
3.3.9

### Version of react-native
0.60.3

### Platforms you faced the error (IOS or Android or both?)'
Android only (IOS works fine)

### Expected behavior
Promise returned by requestSubscription should be resolved

### Actual behavior
Promise returned by requestSubscription never resolved

### Tested environment (Emulator? Real Device?)
Real Device + Sandbox

### Steps to reproduce the behavior
await iap.requestSubscription();
console.log('This string does not print')

**Comment by hyochan** [comment]
Could you also test if the `result` is returned in `purchaseUpdatedListener`? The promises will be deprecated in the future maybe in `4.0.0+`

**Comment by Chehow** [comment]
Yes, It works fine in purchaseUpdatedListener (and I use it save subscription). I wanted to use promise because there is a delay between user click 'Buy' and payment modal appears on IOS (to show spinner). And It works fine currently on IOS. But for android it never resolved (so I will need to have special case in source code to handle it). 
Thx for the answer and good job on this module.

**Comment by TStupariu** [comment]
I can confirm this use case happens to me as well with the latest version of react-native-iap and React Native 0.60.3

**Comment by pliashkou** [comment]
Faced it with the latest version of react-native-iap & React Native 0.60.4

**Comment by pierregoutheraud** [comment]
Same problem with react-native@0.61 and react-native-iap@3.5.2 on Android.

**Comment by hyochan** [comment]
Please try `3.5.3` and comeback. There was one missing promises return in `android` when the `purchases` is null.

**Comment by pierregoutheraud** [comment]
@hyochan Still not working on `3.5.6`.

**Comment by hyochan** [comment]
@pierregoutheraud Could you try `3.5.7`? If you still help the problem please try to post some related `logcat` that can give more hint.

**Comment by pierregoutheraud** [comment]
@hyochan I tried installing `3.5.8` and I am now getting an unrelated new error `Cannot read property 'getAvailableItemsByType' of undefined` when using `getAvailablePurchases`.
