### ISSUE TITLE
Expokit installation instructions?

### ISSUE THREAD

**Issue by EdmundMai** [dooboolab/react-native-iap#639]
### Version of react-native-iap
    "react-native-iap": "^3.3.9",

### Version of react-native
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
I should see a Libraries folder in Xcode

### Actual behavior
I can't find the "Libraries" folder. Same problem as this guy: https://github.com/dooboolab/react-native-iap/issues/174#issuecomment-450506090

Would you happen to have steps on how to install this on iOS? I just ejected my expo app, and chose Expokit. I ran `npm install`, `react-native link react-native-iap`, and now I'm stuck on the manual installation part because I can't find the Libraries folder.

**Comment by hyochan** [comment]
Can you try [my suggestion[(https://github.com/dooboolab/react-native-iap/issues/14#issuecomment-360330732) in linking?

**Comment by lc3t35** [comment]
After updating from 3.3.7 to 3.3.9 with sdk34, I have the same problem rn-iap disappear from Podfile
