### ISSUE TITLE
InAppPurchase response always is "invalid items"

### ISSUE THREAD

**Issue by vadermemo** [dooboolab/react-native-iap#64]
Hi guys,

  I have a big problem, when a test on my iphone with my variable itemSkus initialized, always get the next message:

"InAppPurchase   ###  didReceiveResponse :: Valid Product Count ::  0"

Never get a "valid items", even with a double checking list:

1. Check the "Id Pack" from Itunes Connect is the same from Xcode's bundle identifier.
2. Check the list of "Products ID" from Itunes Connect is the same from variable itemSkus = {
  ios: [ ....]}

### Version of react-native-iap
0.2.17
### Expected behavior
A list of valid items from itemSkus array, with the correct format JSON, by example  : {price: ? , productId: ?}

### Actual behavior
A list empty and a next log 
"InAppPurchase   ###  didReceiveResponse :: Valid Product Count ::  0"

### Steps to reprodue the behabior
1. import * as RNIap from 'react-native-iap';
2. initialized a const itemSkus = {
  ios: ['id1', 'id2' ,'id3']};

3. Put the next snippet on componentDidMount() 
   items =  RNIap.getItems(itemSkus)
3.a. Put the next snippet on custom method onPress:
 items =  RNIap.getItems(itemSkus)

**Comment by JJMoon** [comment]
The 'Valid Product Count :: n' is from productRequest method in iOS, which is several times tested.
I guess the definition of products in iTunesConnect is not completed. Would you share the settings of them?
Another issue is.
You have to wait some time to test after setting this products in iTunesConnect. 
It took sometimes several hours or a day.
Implementation and test in IAP of iOS takes time.

**Comment by JJMoon** [comment]
Issue too old. Closing
