### ISSUE TITLE
[iOS] getSubscriptions isn't the same on emulator and in phone

### ISSUE THREAD

**Issue by rewieer** [dooboolab/react-native-iap#640]
### Version of react-native-iap
3.3.9

### Version of react-native
0.59.8

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
I expect receiving the exact same products in my phone and in my emulator

### Actual behavior
This is an object I get on my **phone**
```
{
  "subscriptionPeriodUnitIOS": "",
  "introductoryPrice": "€9,99",
  "title": "Abonnement 1 Mois",
  "type": "Do not use this. It returned sub only before",
  "introductoryPricePaymentModeIOS": "",
  "introductoryPriceNumberOfPeriodsIOS": "",
  "description": "Débloque tout Belib pendant 1 mois",
  "currency": "EUR",
  "price": "9.99",
  "localizedPrice": "€9,99",
  "subscriptionPeriodNumberIOS": "0",
  "introductoryPriceSubscriptionPeriodIOS": "",
  "productId": "premiumOne"
}
```

This is the object I can in my **emulator**
```
{
  "productId": "premiumOne",
  "description": "Débloque tout Belib pendant 1 mois",
  "introductoryPriceSubscriptionPeriodIOS": "",
  "subscriptionPeriodNumberIOS": "1",
  "introductoryPriceNumberOfPeriodsIOS": "",
  "discounts": [],
  "type": "Do not use this. It returned sub only before",
  "title": "Abonnement 1 Mois",
  "localizedPrice": "€9,99",
  "price": "9.99",
  "introductoryPricePaymentModeIOS": "",
  "subscriptionPeriodUnitIOS": "MONTH",
  "introductoryPrice": "",
  "currency": "EUR"
}
```
As you can see, in my phone I get **subscriptionPeriodNumberIOS** equal to 0, while in emulator it's equal to 1. 

### Tested environment (Emulator? Real Device?)
Both

### Steps to reproduce the behavior
Fetch subscriptions from the AppStore, compare the result in emulator and in phone.

**Comment by hyochan** [comment]
It looks like it's because your `ios` version is below `11.2` for your phone. The `SKProductPeriodUnit` is not supported in below version hence you will see different result.
