### ISSUE TITLE
docs and API refinement

### ISSUE THREAD

**Issue by voxspox** [dooboolab/react-native-iap#642]
I'm currently diving into IAPs and was wondering about some topics I explain in the following. My config is:

- react-native-iap: 3.3.9
- react-native: 0.60.4
- platform: Android

##### typeof Product
- [ ] The docs say that each field is of type `string`. Contrary to that I get type `Number` for `price` and `originalPrice`
- [ ] Contrary to the docs I get a number for `price` and not `localizedPrice`
- [ ] For `title` I get a concatenated string of a) the title I entered in the Play Console item setup and b) the title of the app itself. I expected to get only a).
- [ ] `introductoryPrice` includes the currency chars and thus maybe should be renamed to `introductoryLocalizedPrice`
- [ ] maybe unify naming for: there is `getSubscriptions` and `requestSubscription` for subscriptions but `getProducts` and `requestPurchase`

##### deprecated
- [ ] update deprecated function names in the docs by their successors p.ex.:
> Once you have called getProducts(), and you have a valid response, you can call buyProduct()

##### Finishing a Purchase
- [ ] The docs say that I have to call `acknowledgePurchaseAndroid` or (should call) `finishTransactionIOS`. I think it would be a good idea for a future release to provide a single  `acknowledgePurchase` to unify both platforms.

##### Q&A
- [ ] First question mentions `fetchProducts`. Is the hole answer for version 2 or should `get Products` be used instead?

**Comment by hyochan** [comment]
@voxspox Looks like you have a great insight on improving `react-native-iap`. Would you like to give us a `PR` for some of those you've listed?
I think I can design the `Finishing a Purchase` section and answer to `Q&A`. 
` First question mentions fetchProducts. Is the hole answer for version 2 or should get Products be used instead?`
- The answer is currently, they do the same thing but I'd liked to ensure that it won't work as a `promises`.

**Comment by voxspox** [comment]
maybe this issue should be split into separate issues

**Comment by voxspox** [comment]
any updates on this?
