### ISSUE TITLE
Add custom data to product purchase in global listener

### ISSUE THREAD

**Issue by kraken22** [dooboolab/react-native-iap#645]
### Version of react-native-iap
3.3.9
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
Both
### Expected behavior

My app allows the purchasing of _tokens_ (10, 20, 30, 50, or 100) through an in app purchase.
In the play console / app-store-connect i have made 5 different product "SKU's"
However, these _tokens_ are applied to specific user created "containers" by the backend API.

Previously with the promise based API, The user could be inside a specific "container" and click BUY. The app would then charge the user `const purchase = await RNIap.buyProduct(itemSKU /*either 10, 20 etc*/)` and immediately `consumePurchase(purchase.purchaseToken)` Upon a successful purchase (not cancelled by user / card failed etc...) the app would then send the `container_id` of the currently open "container" with the `purchase.transactionReceipt` to the server which validates the purchase using the `transactionReceipt` and applies the amount of _tokens_ (got from the purchase sku) directly to the container. I hope this makes sense.

### Actual behavior

After upgrading to the new event based purchase flow I cannot see a way of making this work. If I `requestPurchase(itemSKU)` inside the container "screen" then the 'callback' for the purchase will be given to the root component with no reference to this particular "container". 

My Questions:
- Is there a simple way of solving this problem that i cannot see yet????
- Can `await requestPurchase(itemSKU)` return a transactionId,
- Can I attach a simple bit of custom data to a purchaseRequest that will show up in the `purchaseUpdatedListener`

Thank You.

PS: Please let me know if anything does not make sense? Or if this is the wrong place to ask this type of question. (and if so where i can ask it hehe)

**Comment by jvandenaardweg** [comment]
> If I requestPurchase(itemSKU) inside the container "screen" then the 'callback' for the purchase will be given to the root component with no reference to this particular "container".

In `purchaseUpdatedListener` you'll receive  the complete `purchase`. there you have access to the  `productId` and `transactionReceipt`, which should be enough to validate it on your server.

**Comment by kraken22** [comment]
Yes. I now validate my purchase in the `purchaseUpdatedListener`.  However, in this function I don't know which container component initiated the purchase. This was the problem.
I have since changed the purchase structure of the app to not need this information anymore. Thanks a lot for your help.
