### ISSUE TITLE
renewable subscription suddenly cancelled

### ISSUE THREAD

**Issue by ming436534** [dooboolab/react-native-iap#647]
### Version of react-native-iap
3.3.6
### Version of react-native
0.60.0
### Platforms you faced the error (IOS or Android or both?)
Android Only
### Expected behavior
Renewable Subscription
### Actual behavior
We have user experiencing some strange issue. The issue is that we have a monthly renewable subscription plan, and during this two months some users who were in the middle of the subscription suddenly received an email which said that their subscription was cancelled automatically, and we also received refund report. May I know am I missing anything which may cause this issue? Thank you.
### Tested environment (Emulator? Real Device?)
Customer Problem
### Steps to reproduce the behavior
Unknown

**Comment by ming436534** [comment]
The reason of the above problem is that I did not call acknowledgePurchaseAndroid after purchasing, thank you.

**Comment by ming436534** [comment]
I also want to leave a comment here to help anyone who forget to call the acknowledgePurchaseAndroid function in app. If you have the purchase record with the purchase token in server, you can use [googleapi](https://github.com/googleapis/googleapis) to acknowledge the receipt from server.

**Comment by jipEbizz** [comment]
![Screen Shot 2023-01-27 at 11 41 20](https://user-images.githubusercontent.com/72867449/215021161-d4884ebc-6729-4e0e-bbf5-abb80022d5e5.png)

I didn't forget to add the `acknowledgePurchaseAndroid` method, even though I got the same issue. My live users have subscribed to the product and after some time or days, the membership was auto cancelled and received an email from Google that "money was refunded and membership cancelled" even if the users did not unsubscribe. 

Can anyone please look into this? 

Thank you.

**Comment by andresesfm** [comment]
If this still happens on the latest version, please create a ticket with all the details and I'll take a look. in the latest library, calling`finishTransactions` takes care of the acknowledgment depending on the type of product
