### ISSUE TITLE
No valid Product returned !!

### ISSUE THREAD

**Issue by gregoireLem** [dooboolab/react-native-iap#65]
I have the error "No valid Product returned !!" after getItems. Any idea of what could be the causes ? 

Thanks a lot for the lib

**Comment by dooboolab** [comment]
@gregoireLem Which platform did you tried? Please check if you created your IAP products in app store or android playstore first.

**Comment by gregoireLem** [comment]
For know I just tried on iOS. And yes I have to products that are in App Store.

**Comment by dooboolab** [comment]
@gregoireLem So is this solved?

**Comment by gregoireLem** [comment]
Nop still have no valid products ...

**Comment by dooboolab** [comment]
@gregoireLem Sorry. I've closed this because you've not given us reply for long time, so I felt you are fine with this. Could you please upgrade to 0.3.10 and try again following the [Blog](https://medium.com/@dooboolab/react-native-in-app-purchase-121622d26b67) I've posted here? I think there might be a configuration problem which someone asked earlier.

**Comment by gregoireLem** [comment]
Ok I did the upgrade to 0.3.10, now I don't have any errors but my products are empty.

`  
const itemIAP = Platform.select({
  ios: [
    'gregoire.test.TipsyDrinkingGame.allMode',
    'gregoire.test.game.shortMode',
  ],
  android: [
  ],
});

async componentDidMount() {
      try {
        await RNIap.prepare()
        const products = await RNIap.getProducts(itemIAP);
        Alert.alert("products :" + products)

      } catch(err) {
        Alert.alert(errorCode)
        console.log(errorCode);
      }
  }`

The state of my products in app store are "ready to submit"

If you have any clues 🤔
Thx for the help

**Comment by axelkennedal** [comment]
This issue should be closed @dooboolab
