### ISSUE TITLE
Cannot get array of products / subscriptions

### ISSUE THREAD

**Issue by mtakac** [dooboolab/react-native-iap#651]
### Version of react-native-iap
3.3.9

### Version of react-native
0.59.9

### Platforms you faced the error (IOS or Android or both?)
iOS and Android

### Expected behavior
I expect to be able to get an array of products and subscriptions created in Play console and Appstore.

### Actual behavior
Functions `RNIap.getProducts` and `RNIap.getSubscriptions` always return empty arrays.

### Tested environment (Emulator? Real Device?)
iOS simulator, Android emulator and Android real device

### Steps to reproduce the behavior
1. Add products in Google Play Console and Apple Appstore Connect
2. I used the code from example folder
3. I changed products / subscriptions ids

I did wait for more than 24 hours. I also created Internal and Alpha release in Google Play Console, but I still get only empty arrays back.

I guess I am a bit unclear on when exactly should I expect it to start working. For example when my Alpha testing Roll out is still Pending publication in Google Play Console, does that mean that `react-native-iap` won't work? Do I have to wait until the app is published to try it out?

Also I know that I won't be able to make even test purchases on simulator / emulator, but should `getProducts` / `getSubscriptions` work on emulators or do I need real device to test it?

```
const itemSkus = Platform.select({
    ios: ['product_1'],
    android: ['1', '2']
});

const itemSubs = Platform.select({
    ios: ['subscription_1'],
    android: ['subscription_1', 'subscription_2']
});

let purchaseUpdateSubscription;
let purchaseErrorSubscription;

class App extends Component {
    constructor(props) {
        super(props);

        this.state = {
            productList: [],
            receipt: '',
            availableItemsMessage: ''
        };
    }

    async componentDidMount() {
        SplashScreen.hide();
        try {
            const result = await RNIap.initConnection();
            await RNIap.consumeAllItemsAndroid();
            console.log('result', result);
        } catch (err) {
            console.warn(err.code, err.message);
        }

        purchaseUpdateSubscription = purchaseUpdatedListener(async purchase => {
            console.log('purchaseUpdatedListener', purchase);
            if (purchase.purchaseStateAndroid === 1 && !purchase.isAcknowledgedAndroid) {
                try {
                    const ackResult = await acknowledgePurchaseAndroid(purchase.purchaseToken);
                    console.log('ackResult', ackResult);
                } catch (ackErr) {
                    console.warn('ackErr', ackErr);
                }
            }
            this.setState({ receipt: purchase.transactionReceipt }, () => this.goNext());
        });

        purchaseErrorSubscription = purchaseErrorListener(error => {
            console.log('purchaseErrorListener', error);
            Alert.alert('purchase error', JSON.stringify(error));
        });
    }

    componentWillMount() {
        if (purchaseUpdateSubscription) {
            purchaseUpdateSubscription.remove();
            purchaseUpdateSubscription = null;
        }
        if (purchaseErrorSubscription) {
            purchaseErrorSubscription.remove();
            purchaseErrorSubscription = null;
        }
    }

    goNext = () => {
        Alert.alert('Receipt', this.state.receipt);
    };

    getItems = async () => {
        try {
            const products = await RNIap.getProducts(itemSkus);            
            console.log('Products', products);
            this.setState({ productList: products });
        } catch (err) {
            console.warn(err.code, err.message);
        }
    };

    getSubscriptions = async () => {
        try {
            const products = await RNIap.getSubscriptions(itemSubs);
            console.log('Products', products);
            this.setState({ productList: products });
        } catch (err) {
            console.warn(err.code, err.message);
        }
    };

    getAvailablePurchases = async () => {
        try {
            console.info('Get available purchases (non-consumable or unconsumed consumable)');
            const purchases = await RNIap.getAvailablePurchases();
            console.info('Available purchases :: ', purchases);
            if (purchases && purchases.length > 0) {
                this.setState({
                    availableItemsMessage: `Got ${purchases.length} items.`,
                    receipt: purchases[0].transactionReceipt
                });
            }
        } catch (err) {
            console.warn(err.code, err.message);
            Alert.alert(err.message);
        }
    };

    requestPurchase = async sku => {
        try {
            RNIap.requestPurchase(sku);
        } catch (err) {
            console.warn(err.code, err.message);
        }
    };

    requestSubscription = async sku => {
        try {
            RNIap.requestSubscription(sku);
        } catch (err) {
            Alert.alert(err.message);
        }
    };

    render() {
        const { productList, receipt, availableItemsMessage } = this.state;
        const receipt100 = receipt.substring(0, 100);

        return (
            <View style={styles.container}>
                <View style={styles.header}>
                    <Text style={styles.headerTxt}>react-native-iap V3</Text>
                </View>
                <View style={styles.content}>
                    <ScrollView style={{ alignSelf: 'stretch' }}>
                        <View style={{ height: 50 }} />
                        <NativeButton
                            onPress={this.getAvailablePurchases}
                            activeOpacity={0.5}
                            style={styles.btn}
                            textStyle={styles.txt}
                        >
                            Get available purchases
                        </NativeButton>

                        <Text style={{ margin: 5, fontSize: 15, alignSelf: 'center' }}>
                            {availableItemsMessage}
                        </Text>

                        <Text style={{ margin: 5, fontSize: 9, alignSelf: 'center' }}>
                            {receipt100}
                        </Text>

                        <NativeButton
                            onPress={() => this.getItems()}
                            activeOpacity={0.5}
                            style={styles.btn}
                            textStyle={styles.txt}
                        >
                            Get Products ({productList.length})
                        </NativeButton>
                        {productList.map((product, i) => {
                            return (
                                <View
                                    key={i}
                                    style={{
                                        flexDirection: 'column'
                                    }}
                                >
                                    <Text
                                        style={{
                                            marginTop: 20,
                                            fontSize: 12,
                                            color: 'black',
                                            minHeight: 100,
                                            alignSelf: 'center',
                                            paddingHorizontal: 20
                                        }}
                                    >
                                        {JSON.stringify(product)}
                                    </Text>
                                    <NativeButton
                                        // onPress={() => this.requestPurchase(product.productId)}
                                        onPress={() => this.requestSubscription(product.productId)}
                                        // onPress={() => this.buyItem(product.productId)}
                                        // onPress={() => this.buySubscribeItem(product.productId)}
                                        activeOpacity={0.5}
                                        style={styles.btn}
                                        textStyle={styles.txt}
                                    >
                                        Request purchase for above product
                                    </NativeButton>
                                </View>
                            );
                        })}
                    </ScrollView>
                </View>
            </View>
        );
    }
}
```

**Comment by hyochan** [comment]
You don't need `real device` to test in `ios` for `getProducts`/`getSubscription` but not in `android`. For `android` you'd need to have real device to purchase.

For google, please go over [my guide](https://github.com/dooboolab/react-native-iap/issues/124#issuecomment-386593185) to resolve your issue.
You do not actually have to publish the app to playstore for testing.

**Comment by nateblog** [comment]
I also have this issue, I already created a product in apple and I can not seem to access it.

```
const itemSkus = Platform.select({
  ios: [
    'product1'
  ],
  android: []
});

RNIap.getProducts(itemSkus).then((products) => {
      console.log(products);  //<< returns empty array
}).catch((error) => console.log(error))
```

Does it takes time for the product to reflect in your experience?

**Comment by jvandenaardweg** [comment]
@nateblog what kind of product did you create? A subscription or something else?

**Comment by nateblog** [comment]
@jvandenaardweg - yes I already added the localization since the in-app status will not be set to "Ready to Submit" if I skip the localization. I set the localization to "English (U.S.)" and yes the product is subscription.

**Comment by nateblog** [comment]
Sorry, it is sorted out now, the issue was the bundle Id in my xcode, i am using the wrong bundle id, it all works now

**Comment by Kuhne1** [comment]
I had a similar, and I just needed to do the linking process of the library manually. (ios)

**Comment by paulbargaoanu** [comment]
> Sorry, it is sorted out now, the issue was the bundle Id in my xcode, i am using the wrong bundle id, it all works now

Hey, @nateblog! I am facing a similar issue: I get empty arrays for products and subscriptions and I have created 2 subscription items within App Store Connect. Could you please elaborate on what was wrong with your bundle id? I don't think that I am submitting the correct item SKUs because I couldn't find any reference as to how they are constructed or what they are - are they [Bundle Identifier].[ProductId of the purchase item] or just [ProductId of the purchase item]? 

Any advice would be greatly appreciated.

**Comment by darren-junda-chen** [comment]
> I had a similar, and I just needed to do the linking process of the library manually. (ios)

You saved my day!

**Comment by ShridharCodewave** [comment]
I have integrated the react-native-iap and uploaded my signed apk to beta release on play store and also added one subscription plan. I am trying to get the list of subscription by subscription ID in debug mode which is always returning an empty array. Can I actually test the subscription in debug mode?

**Comment by kesepara** [comment]
@ShridharCodewave i'm facing the same issue. please let me know if you can solve the problem :(

**Comment by ismetsezer** [comment]
I am facing same problem on Android Emulator.  I uploaded apk to Google Play Store to Beta Channel and added products. 

![image](https://user-images.githubusercontent.com/14247947/65507089-ca99fb00-ded5-11e9-8f10-35bb26f12313.png)



First , connection init then I am trying to fetch products but nothing shows on console.warn
No results in here
No Errors   in  here

**Comment by jvandenaardweg** [comment]
@ismetsezer the whole In App billing for Android won't work in the emulator:
> You cannot use the emulator to test Google Play Billing; you must install your application on a device to test Google Play Billing.
> https://developer.android.com/google/play/billing/billing_testing

You need a real device for that. 

In iOS you can fetch subscription data in the simulator. But you cannot buy it, for that you also need a real device.

For the other comments above: Make sure the `versionName` and `versionCode` in `android/app/build.gradle` is the same or higher as the one in the non-production tracks in Google Play Console. Also, to my understanding, you need an active/reviewed app in one of the non-production tracks in order to get the billing to work locally.

I don't know the exact steps I did, but for me it's working locally with an Android device.  So it's probably not a react-native-iap package issue, but more a configuration thing.

**Comment by ismetsezer** [comment]
Thanks @jvandenaardweg   when I  switched to real device , Yes It works but as you said  and according to link, I have to wait for test app to published on Beta Channel because products array comes empty

**Comment by jvandenaardweg** [comment]
Good to hear @ismetsezer . Can you confirm if it starts working for you with a reviewed/published test app? Because then we can update the readme with that new information :-)

**Comment by ismetsezer** [comment]
Of course.After published by google play store , I will confirm here

**Comment by ShridharCodewave** [comment]
@kesepara  I had to wait for few hours after adding the new subscription plan on play store for it to appear on the device.

**Comment by beeremy** [comment]
Hi @ismetsezer and @kesepara ,
I would really appreciate your input about your development flow as something is still not clear to me.
I've set up RN IAP for iOS and it is working fine now.
I'm now starting to do the Android part, and I've found [here](https://github.com/dooboolab/react-native-iap/issues/124#issuecomment-386593185) that we have to use signed APK uploaded on Closed track (at least) to be able to test payment features.
But in your comments you're saying that you've been able to test it on Android emulator, is that correct?
Furthermore, if we have to use signed APK on the store, how can we debug?
Your help would be very much appreciated.

**Comment by ismetsezer** [comment]
Hi @beeremy.Thanks for your good opinions . You have to test iap on real device or emulator that has google play support to fetch products.  IAP has worked  after I published app on Google Play Store , this could be change but at least you have to upload or give a draft on the store  to test this feature. But it takes 2 - 3 hours to work.

**Comment by beeremy** [comment]
Hi @ismetsezer , thanks for your feedback. 

For whoever it can be useful, I've been able to make a debug config running after following this recommendation: https://stackoverflow.com/questions/36113347/is-it-possible-to-debug-locally-google-plays-in-app-billing-in-android-studio

**Comment by pepesrz91** [comment]
I can confirm as @ismetsezer that subscriptions and products will work after app is published in google play console. Trying to get subscriptions / products when app is not yet published will not work.

**Comment by edgaralienfoe** [comment]
RN 0.59.1 on Android dev here and I'm using iap version 4.4.1

My build is currently on the Alpha track. **Afterwards**, I rebuilt as usual on my machine in debug mode, within the Platform.select({}) I specified the subscription ID as it is on the Play Console, and I called getSubscriptions() but I'm receiving an empty array. Is this because it's in Alpha? Any ideas?

**Comment by acostalima** [comment]
@edgaralienfoe did you active your subscription in Google Play Console?

**Comment by edgaralienfoe** [comment]
@acostalima it should be activated. I assumed maybe it takes a few days for it to do so, but still no luck.

**Comment by acostalima** [comment]
@edgaralienfoe I'm asking because I recall there is an option to explicitly active a subscription on Google Play Console and if it is not active, then the subscription will not show up in your app. But, if you say so, there might be some other issue then.

**Comment by thecao-nucleusstudio** [comment]
@edgaralienfoe Did you find the solution? Maybe your app version needs to be higher than the one in Alpha track

**Comment by acostalima** [comment]
> @edgaralienfoe Did you find the solution? Maybe your app version needs to be higher than the one in Alpha track

Alpha track works just fine. I've been testing IAPs for quite some time now with builds deployed to Alpha without issues.

**Comment by patreu22** [comment]
For everybody who might run into trouble here, what did the trick on iOS for me was linking the project manually as suggested by @Kuhne1 - it worked after cleaning the build folder and installing Pods manually as well, hope it's useful to anybody!

**Comment by rusakovic** [comment]
> Of course.After published by google play store , I will confirm here
> 
> UPDATE
> 
> > After my app has published on Google Play Store, purchases came up and worked. It takes 3 days to approve. Thanks to @jvandenaardweg
> 
> UPDATE 2
> 
> > react-native-iap can work on android emulator , if emulator has google play store support.

Thank you.
1. Am I right, that 'In review' status doesn't allow to 'getProducts' on real device?
![image](https://user-images.githubusercontent.com/17801144/123077906-c2f4e680-d41a-11eb-9cee-1950323e178a.png)

2. Could I use react native debugger to console.log products?

**Comment by Mihai-github** [comment]
Same issue here.  The code is never executed.

Platform: IOS
Code: 
```
try {
            RNIap.initConnection().then(resp => {
                RNIap.getProducts(items)
                    .then(re => console.log(re))
                    .catch(e => console.log([e]));
            });
            //  this.setState({products});
        } catch (err) {
            console.log(err);
        }
```
