### ISSUE TITLE
Cannot read property 'fetchProducts' of undefined

### ISSUE THREAD

**Issue by ilyakar** [dooboolab/react-native-iap#66]
### Version of react-native-iap
0.2.17

### Expected behavior
Should fetch the products

### Actual behavior
```
Some error: TypeError: Cannot read property 'fetchProducts' of undefined
    at blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:63153:15
    at tryCallTwo (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:1975:5)
    at doResolve (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:2114:13)
    at new Promise (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:1996:3)
    at Object.getItems (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:63147:12)
    at getItems$ (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:63078:51)
    at tryCatch (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:36741:40)
    at Generator.invoke [as _invoke] (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:36929:22)
    at Generator.prototype.(anonymous function) [as next] (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:36766:21)
    at tryCatch (blob:file:///4d72f48f-05d3-412d-8e2f-5d0908f04e54:36741:40)
```

### Steps to reproduce the behavior
1. Run `yarn install react-native-iap`
2. Run `yarn link react-native-iap`. (I have a cocoapods projects so it adds the following line: `pod 'RNIap', :path => '../node_modules/react-native-iap'` to my Podfile
3. Run `cd ios`, Run `pod install`
4. Launch the app

**Comment by ilyakar** [comment]
Here is my Pods screenshot from XCode:

![screen shot 2018-03-23 at 18 21 29](https://user-images.githubusercontent.com/1760709/37844135-16381b3e-2ec7-11e8-939d-ca255c0228b5.png)

**Comment by dooboolab** [comment]
@ilyakar  did you fetch the correct product ids that you have set in your iTunes connect? 
![image](https://user-images.githubusercontent.com/27461460/37859374-f7bd31d2-2f55-11e8-99e7-03755d0faf96.png)
Check if you set up your products correctly.

**Comment by ilyakar** [comment]
Hi. Yes. When I remove the podfile from the ios folder the plugin installs correctly and everything works. But I am using a podfile for other plugins so this isn’t a permanent solution.


Kind regards,
Ilya

**Comment by dooboolab** [comment]
@ilyakar Are you still having trouble? This module shouuld work even if you are in cocoapods project.

**Comment by ilyakar** [comment]
Hi @dooboolab Yes, I still cannot get it to work with cocoapods. Am I missing something? Should I install plugins using cocoapods differently than the following?
1. Run `yarn install react-native-iap`
2. Run `yarn link react-native-iap`. (I have a cocoapods projects so it adds the following line: pod 'RNIap', :path => '../node_modules/react-native-iap' to my Podfile
3. Run `cd ios`, Run `pod install`
4. Launch the app

**Comment by alanlanglois** [comment]
@ilyakar  did you tried this: 
https://github.com/dooboolab/react-native-iap/issues/14

**Comment by dooboolab** [comment]
@ilyakar can you delete `pod 'RNIap', :path => '../node_modules/react-native-iap'` from your Podfile? It should not be there. I will update this one.

**Comment by dooboolab** [comment]
@ilyakar any update?

**Comment by ilyakar** [comment]
Thanks for the responses guys! I still didn't get to trying this out as we're focused on the marketing aspects now, but I will and let you know!

**Comment by ilyakar** [comment]
0.3.10 seems to work fine for me. I currently deal with plugins by removing my podfile and then installing them, then adding the podfile back. I haven't tested if the newer version solve the podfile problems.
