### ISSUE TITLE
developerPayload for subscriptions?

### ISSUE THREAD

**Issue by 2joocy** [dooboolab/react-native-iap#661]
I noticed that normal purchases have the ability to pass in the developerPayload, although subscriptions do not. Is there a way to currently do this?

Use case would be server to server authentication

**Comment by hyochan** [comment]
Currently, `developerPayload` is affected on `consumePurchase` and `acknowledgePurchase`. Could you describe more specifically?

**Comment by 2joocy** [comment]
The issue that I am having currently, is that I am trying to implement server side authentication, without having to make a handshake with the client to confirm the purchase. The issue I have currently, is that my real time notification sent from pub sub is being sent before the developerpayload is set in `const test = await RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken, tokenHeader);`. 

Either I would have to do setTimeout on the server, for like 10 seconds, or somehow get the developerpayload as the purchase is being sent out
