### ISSUE TITLE
Not getting any response on calling requestPurchase and updatedPurcahseListener

### ISSUE THREAD

**Issue by MobileCoderzTechnologies** [dooboolab/react-native-iap#665]
@hyochan 
### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
requestPurchase function should return a response on successful purchase.

### Actual behavior
Didn't get any response on successful purchase and same behavior happening with updatedPurchaseListener function.

### Tested environment (Emulator? Real Device?)
Real Android Device

**Comment by hyochan** [comment]
I think this is related to #651 and hance [my reply](https://github.com/dooboolab/react-native-iap/issues/651#issuecomment-523386226).

**Comment by skoob13** [comment]
I have a similar issue. `requestPurchase` doesn't resolve, however, `getProducts()` works as expected. In logs I have found the next lines:
```
09-05 17:02:08.544 3009-3009/app W/BillingHelper: Couldn't find purchase lists, trying to find single data.
09-05 17:02:08.551 3009-3009/app E/DoobooUtils: Map already consumed
```
Is this also connected with #651?
