### ISSUE TITLE
_reactNativeIap.default.acknowledgePurchaseAndroid is not a function

### ISSUE THREAD

**Issue by rafaelsorto** [dooboolab/react-native-iap#666]
### Version of react-native-iap
3.0.2

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Should be able to acknowledgePurchaseAndroid for a subscription

### Actual behavior
App closes and the debugger shows the following error: _reactNativeIap.default.acknowledgePurchaseAndroid is not a function

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Try to acknowledge a purchase on Android for a subscription. 

```
if (Platform.OS === "android") {
            // If not consumable
            await RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken);
          }
```

Hi guys, thank you for the time taken to invest in this awesome project. 

I am using the latest release before 3.1.0 because my project has some dependencies that are not compatible with AndroidX so I am using the latest relase I could find before having to migrate to AndroidX which seems to be 3.0.2.

I also found in the reported issues that to close #579 the function acknowledgePurchaseAndroid was being added to 3.0.2 but there must be something missing because I am already using 3.0.2. My vscode editor does not complain anymore about the function missing, but when I actually execute it in the code my app closes immediately and all I could see in the debugger is that it complains the function does not exist. *_reactNativeIap.default.acknowledgePurchaseAndroid is not a function*

I am facing the issue where the Android subscription in Sandbox mode is being auto cancelled and the flag autoRenewingAndroid is never set to true. I suspect it is due to the acknowledge missing to Android thus the subscription being auto cancelled.

Thanks in advance for your support :D

**Comment by hsparihar-systango** [comment]
@raeesbhatti 
I have imported 
`import * as RNIap from 'react-native-iap';`
still getting error for android 
`[TypeError: RNIap.acknowledgedataAndroid is not a function. (In 'RNIap.acknowledgedataAndroid(data.purchaseToken)', 'RNIap.acknowledgedataAndroid' is undefined)]`

please suggest what else you have fixed

**Comment by hyochan** [comment]
acknowledgePurchaseAndroid
