### ISSUE TITLE
how to capture payment card details - subscription flow

### ISSUE THREAD

**Issue by jeevankumarkanuganti** [dooboolab/react-native-iap#668]
I want to do a subscription purchase using a test card from apple pay wallet in the iphone.

I had followed the documentation as given , and able to see the products(monthly/yearly) displaying . when I click on the button i created, I used "requestSubscription" method and seeing the popup to buy the product and on click Buy i am getting a popup with successfully .

1)I need to see the card details used for the payment
2)even if i remove the card from my wallet, I am able to buy the subscription always showing successful message.
3) I need to know , how to test this iap subscription with real and test cards.

**Comment by hyochan** [comment]
1) I ain't sure about this one but I think you can't get the card details using `iap` StoreKit. Update me if I am wrong.
2) Are you a sandbox user? Then that may happen.
3) Have you gone through sandbox testing? Please go over the resources I provide below.
    - [official link](https://developer.apple.com/in-app-purchase) might help you.
    - [how to test in app purchases in your app](https://support.magplus.com/hc/en-us/articles/203809008-iOS-How-to-Test-In-App-Purchases-in-Your-App)
    - [medium blog for iap](https://medium.com/dooboolab/react-native-in-app-purchase-121622d26b67)

**Comment by jeevankumarkanuganti** [comment]
hi @hyochan ,

Thanks for the response.

Yes, I am using sandbox tester and I followed the same [medium blog for iap](https://support.magplus.com/hc/en-us/articles/203809008-iOS-How-to-Test-In-App-Purchases-in-Your-App) steps given.
In the 4th point, it says, "You will be prompted to sign in. Use the e-mail and password of the test user you created earlier and you will be allowed to make a purchase without incurring a charge"

 * do I again need to SignIn with sandbox tester or any user who has iTunes account?
* Once the purchase is made successfully, where can I find the payment details in the iTunes merchant account.
