### ISSUE TITLE
autoRenewingAndroid missing in release 3.0.2

### ISSUE THREAD

**Issue by rafaelsorto** [dooboolab/react-native-iap#669]
### Version of react-native-iap
3.0.2

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
autoRenewingAndroid should be true if the user has not cancelled the subscription

### Actual behavior
autoRenewingAndroid missing from Purchase item

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
- Create a subscription in the Google Play Console
- Request the subscription to be added for a user
- Get the available purchases for a user
- The purchase is in the list but the autoRenewingAndroid key is missing

### Description

Hey guys I am trying to check if a User has a valid subscription in Android. I noticed in one of the Issues in there that it is mentioned that to verify a subscription is valid for Android one has to verify that the autoRenewingAndroid is set to true, which means the subscription is still valid?

It turns out that for 3.0.2 the key autoRenewingAndroid is missing and it looks as if it is a missing item.putBoolean in the RNIapModule.java (I am sending a PR soon as a proposed fix)  

What concerns me is that I noticed in the Google Play documentation that a user can cancel the subscription that they have but the App should continue to provide the subscription until it reaches its end. Like if the user cancels a monthly subscription on the middle of the month, the app should still provide the premium services until the end of the month or previously agreed period. 

I also fixed the missing autoRenewingAndroid here locally, but when I cancel a subscription in the app Subscriptions, I do not see this key changing to false, it is always set to true, is there something else that I am missing to validate Android Subscriptions?

**Comment by hyochan** [comment]
I think your question is related to #275 #532. By using this solution, you may check if the user is subscribed.
I am not sure about your next question. `autoRenewingAndroid` always returning `true` should be some `env` problem in play store server.

**Comment by hyochan** [comment]
I feel like releasing this in 3.0.3 though. I'll close this when this is ready.

**Comment by hyochan** [comment]
Released 3.0.3 in #673
