### ISSUE TITLE
When can I get the subscription receipt to store it?

### ISSUE THREAD

**Issue by booboothefool** [dooboolab/react-native-iap#674]
### Version of react-native-iap
2.3.26
### Version of react-native
0.55.4
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Get receipt after purchase
### Actual behavior
Error with no receipt
### Tested environment (Emulator? Real Device?)
Real device in dev mode

### Steps to reproduce the behavior
1. Have subscription group, already subscribed one.
2. Try switch subscription
```
try {
  const receipt = await RNIap.buySubscription(productId);
  console.log({ receipt });
} catch (err) {
  console.log(err);
}

```
3. Get error
```
Error: An unknown or unexpected error has occured. Please try again later.
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:398)
    at MessageQueue.js:137
    at MessageQueue.__guardSafe (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:70
```

And no receipt is shown. 

I also see:
```
export interface ProductPurchase {
  productId: string;
  transactionId: string;
  transactionDate: string;
  transactionReceipt: string;
  signatureAndroid?: string;
  dataAndroid?: string;
  purchaseToken?: string;
}

export interface SubscriptionPurchase extends ProductPurchase {
  autoRenewingAndroid: boolean;
  originalTransactionDateIOS: string;
  originalTransactionIdentifierIOS: string;
}
```

For consumable I am able to get `transactionReceipt`. For subscription it errors, but it supposed to show `originalTransactionIdentifierIOS`? Can I use `originalTransactionIdentifierIOS` to fetch the receipt somehow?

Does receipt only show when subscribe for first time, not changing subscription in group?
It is hard to test because I am not sure how to get rid of subscription to test properly. Is receipt supposed to show up in`buySubscription()` result?

I am just trying to store the user's subscription receipt on my backend so I can validate later.

**Comment by nateblog** [comment]
You can try this way:

```
import * as RNIap from 'react-native-iap';

RNIap. getPurchaseHistory().then((purchaseHistory) => {
     if(purchaseHistory.length > 0) {
         const getLastPurchase = purchaseHistory[purchaseHistory.length -1];
         const getReceipt = getLastPurchase.transactionReceipt;

         // DO RECEIPT RELATED TASK
     }
});
```

this is how I get my latest subscription receipt

**Comment by booboothefool** [comment]
Thanks that works when getting the receipt sometime after, but I would wanted to store with the purchase for my backend. 

I was able to get the receipt eventually, but think there might be strange behavior with Environment: Sandbox depending on whether subscription has already been made (in which no receipt will come back).

```
const receipt = await RNIap.buySubscription(productId);
console.log({ receipt });
                    // receipt
                    //     originalTransactionDateIOS: 1556516266000
                    //     originalTransactionIdentifierIOS: "1000000523549123"
                    //     productId: "myproductid"
                    //     transactionDate: 1567055668000
                    //     transactionId: "1000000562522123"
                    //     transactionReceipt: "MIIm/gyJKo..."
```

So I think best thing to do might be to:
1. Try to get receipt and store after `buySubscription()`
2. If not, fallback and check with `getPurchaseHistory()`
3. Check with `getPurchaseHistory()` pretty regularly, like once a day
