### ISSUE TITLE
Cancel subscription on iOS and Android

### ISSUE THREAD

**Issue by iutin** [dooboolab/react-native-iap#679]
How to implement cancel subscription on iOS and Android? Does it possible make by this library? Thank you

**Comment by hyochan** [comment]
User can do this in their `setting` on each os. I'm not sure yet if you can achieve this in your app. Hope you can give me an update.

**Comment by jvandenaardweg** [comment]
> I'm not sure yet if you can achieve this in your app. Hope you can give me an update.

On iOS you can only cancel through iTunes/App Store. There is no way for the user to do this in your app.

**Comment by jvandenaardweg** [comment]
Might be good to add this to the readme. As this is typically something you want to know when you start developing on in app purchases.

**Comment by julioxavierr** [comment]
I don't know if this is something that changed recently, but I've just tested and this redirects to install iTunes app. After some research I got to this new solution:

```
Linking.openURL('https://apps.apple.com/account/subscriptions');
```

**Comment by lukewlms** [comment]
If you're landing on this page and want the current solution, here's the readme section:

https://github.com/dooboolab/react-native-iap#how-can-a-user-cancel-a-subscription-in-my-app

**Comment by jaaywags** [comment]
@lukewlms I think that link is dead. [I did find this though.](https://github.com/dooboolab/react-native-iap/blob/c0481d3344057ff54c9da2aa70f34dea412a9460/docs/docs/faq.md#how-can-a-user-cancel-a-subscription-in-my-app).

**Comment by mohit23x** [comment]
You can also do this directly, without opening a browser, using:
```
 Linking.openURL('App-prefs:APPLE_ACCOUNT&path=SUBSCRIPTIONS');
```

**Comment by yernandus** [comment]
> ```js
> https://play.google.com/store/account/subscriptions
> ```

and for android?
