### ISSUE TITLE
Add correct types for new method: requestPendingPurchasesIOS

### ISSUE THREAD

**Issue by jvandenaardweg** [dooboolab/react-native-iap#690]
### Version of react-native-iap
3.4.2

### Version of react-native
0.60.4

### Platforms you faced the error (IOS or Android or both?)
both

### Expected behavior
Typescript/Flow should get the correct types for `requestPendingPurchasesIOS`, introduced here: https://github.com/dooboolab/react-native-iap/pull/663

### Actual behavior
No types

### Tested environment (Emulator? Real Device?)
IDE

### Steps to reproduce the behavior
Use TS :-)

**Comment by hyochan** [comment]
@jvandenaardweg Thanks for the `issue`. However, `requestPendingPurchasesIOS` has been renamed to `getPendingPurchasesIOS` and there is actually type definition for `typescript` but not `flow`. I've updated `flow` in #693.
