### ISSUE TITLE
Types: normalize price type between iOS and Android

### ISSUE THREAD

**Issue by jvandenaardweg** [dooboolab/react-native-iap#694]
### Version of react-native-iap
3.4.4

### Version of react-native
0.60.0

### Platforms you faced the error (IOS or Android or both?)
Android and IOS

### Expected behavior
type of `price` should be the same on iOS and Android: a `string` OR a `number`. Preferably a `number`, because it is a number.

### Actual behavior
Android: The type of `price` is a `number` (see screenshot)
iOS: The type of `price` is a `string` (see screenshot)

https://github.com/dooboolab/react-native-iap/blob/master/index.d.ts#L10

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
Run `RNIap.getSubscriptions()`

Android:
<img width="495" alt="Screenshot 2019-09-04 at 14 29 30" src="https://user-images.githubusercontent.com/5155373/64254860-7fb54500-cf20-11e9-95a8-b103dbea2445.png">

iOS:
<img width="577" alt="Screenshot 2019-09-04 at 14 45 10" src="https://user-images.githubusercontent.com/5155373/64255943-b0967980-cf22-11e9-8702-654af2f95cb2.png">

To help prevent this in the future, maybe it's a good idea to add mocks to this project. So types are validated against mocks when you run `tsc` before releasing a new version of this package. Also makes it easier to write unit tests, which this project does not have but which i would recommend to be created

I found out about this when creating mocks myself:

```typescript
const test: RNIap.Subscription<string>[] = [
  {
    currency: 'EUR',
    description: 'Monthly plus subscription',
    freeTrialPeriodAndroid: 'P3D',
    iconUrl: '',
    introductoryPrice: '',
    introductoryPriceCyclesAndroid: '',
    introductoryPricePeriodAndroid: '',
    localizedPrice: '€9.99',
    originalJson: '[REDACTED]',
    originalPrice: 9.989999771118164,
    price: 9.989999771118164,
    productId: '[REDACTED]',
    subscriptionPeriodAndroid: 'P1M',
    title: '[REDACTED]',
    type: 'subs',
  }
```

`price` gives an error on my mock.

**Comment by voxspox** [comment]
+1

Additionally `introductoryPrice` should be a `Number`. Currently on Android and iOS it is a localized price p.ex. "0,99 €". Following the scheme of `price` and `localizedPrice` a new value `localizedIntroductoryPrice` should be added.

**Comment by voxspox** [comment]
For Discussion

**Comment by voxspox** [comment]
is this fixed by https://github.com/dooboolab/react-native-iap/pull/885 ?

**Comment by jvandenaardweg** [comment]
@voxspox I have not tried the latest updates, but according to that PR the `price` is now also a `string` on Android?

That seems to fix the differences yes.

Preferably you want that to be a `number` to be honest. But this will do, as it fixes the inconsistency.
