### ISSUE TITLE
Checking whether a subscription is active

### ISSUE THREAD

**Issue by Tsiniloiv** [dooboolab/react-native-iap#697]
Is there a method to check whether a given subscription that the user has purchased is still active?

I'm implementing a subscription flow for my application using this wonderful library, and I've noticed that there doesn't seem to be any way to check if a subscription is currently active.

I can set up a subscription easily enough, and canceling it is no big problem, but making the application react to the current state of the subscription doesn't seem to have an obvious solution, unless I'm missing something.

How do you check the status of a current subscription?

**Comment by hyochan** [comment]
This [answer](https://github.com/dooboolab/react-native-iap/issues/275#issuecomment-425185861) might help.

**Comment by Stafox** [comment]
@Tsiniloiv there are three ways what I know how to do that:
- Using server validation (You send request with receiptData and your backend comunicates with Apple server and return response about purchased products validity)
- Using local validation (issue #700 , not ready yet). You refresh your receipt on device, and decode it.
- Call apple's verifyReceipt from device. But Apple strongly not recommends to do that.

**Comment by hanishcodebrew** [comment]
I am looking for the same approach, please help. 

Thanks
