### ISSUE TITLE
Do we really need SDK version 26?

### ISSUE THREAD

**Issue by KjellConnelly** [dooboolab/react-native-iap#7]
Looks like I can't build my app on Android without SDK version 26 (Oreo) using this repo. Is it really needed to be that high? According to a recent blog post I read, only 0.5% of Android users have Oreo or above. And since IAPs have been out since... idk a long time, it doesn't seem like we would need v26.

Nevertheless, I am pretty much a noob when it comes to Android, so maybe someone could answer this question better than I can guess at and make the fix (if plausible). 

Not sure if it just needs a number tweak in ```android/build.gradle``` or not...

```gradle
android {
  compileSdkVersion 26
  buildToolsVersion "26.0.2"
  ...
}
```

**Comment by dooboolab** [comment]
@KjellConnelly
Hi KjellConnelly~ You can change your buildToolsVersion as your taste. You can set it to sdk 23 when you prefer it.
