### ISSUE TITLE
Offline receipt validation support for iOS

### ISSUE THREAD

**Issue by Stafox** [dooboolab/react-native-iap#700]
It would be very useful to have possibility to validate iOS receipt in offline.

This feature was already mentioned [here](https://github.com/dooboolab/react-native-iap/issues/513#issuecomment-500605956).

There is an example [how it has implemented](https://github.com/robotmedia/RMStore/blob/master/RMStore/Optional/RMAppReceipt.m) in RMStore lib

I guess there are many people who desire this feature.

**Comment by hyochan** [comment]
I hope someone can give us a `PR` on current feature.
