### ISSUE TITLE
React Native 0.59.10 version

### ISSUE THREAD

**Issue by LukePenkava** [dooboolab/react-native-iap#701]
Hi, 

 is it possible to update the docs with what version of react-native-iap is suitable for react native versions before 0.60 ? I have to stay for production reasons on 0.59.10 and would like to use iap module, but i am not sure which version is the right to use. Perhaps i missed some specification on that, but i could not find it.

 I am guessing that i should use 3.0, since 3.1 requires migration to AndroidX ( which i cant do right now ). Let me please know if that is the case and as i mentioned, i think it could be useful for people to know which version to use for what RN version, at least pre 0.60.

Thanks
Luke

**Comment by hyochan** [comment]
Work done in #701 and `react-native-iap@3.4.5`.

**Comment by LukePenkava** [comment]
@hyochan Thank you. The documentation is now much more clear.

**Comment by kesepara** [comment]
@LukePenkava did you manage to find any solution?

**Comment by LukePenkava** [comment]
@kesepara I am not sure what is specifically your issue, but i just followed the docs for <0.60. I am on iap version 3.4.6 with RN version 0.59.10. Also i am using pods for ios and did manual installation for Android. Everything works fine now.

**Comment by kesepara** [comment]
@LukePenkava I am on RN version 0.56.1 and also tried iap version 3.4.6, still get the same error which is "RNIapModule.java:5: error: package androidx.annotation does not exist". How did you manage to use this package without androidx?

**Comment by LukePenkava** [comment]
@kesepara I dont know how you fix that error, if you get it. When i had androidx issue i rolled back to git version of the project without iap and installed it again with the new instructions in the docs. I suggest trying brand new RN 0.56.1 project and install it there based on the docs. If that does not work, try to start new RN project with 0.59.10 and see if that works. That should give you idea if that is something on your side or has something to do with the installation.

**Comment by kesepara** [comment]
@LukePenkava okay, i will try in the morning. thanks a lot.

**Comment by tarouboy** [comment]
Awesome! I am in similar situation and I thought I have to migrate to 0.60 ( which takes a long time ). Knowing that I can use 3.4.5 with 0.59.10 saved my life! <3

**Comment by tobiaseisenschenk** [comment]
unfortunately im on rn version 0.58.0, and installing any of the newer releases of this lib made my build fail. I decided to use release 3.0.2 (one before androidx support)
