### ISSUE TITLE
I don't see my subscriptions in iphone subscriptions menu, although when I buy subscription again it says you have already bought it

### ISSUE THREAD

**Issue by Karlen92** [dooboolab/react-native-iap#706]
### react-native 0.60.4
Os
###  Ios
Expected behavior
### I expect to see my subscriptions be in the phones respective menu 
Actual behavior
### The list of my subscriptions is empty in Iphones subscriptions
Tested environment
### Iphone 7 with Ios sandbox tester
Steps to reproduce the behavior

**Comment by Stafox** [comment]
@Karlen92 what do you mean by "_phones respective menu_"?

**Comment by Karlen92** [comment]
@Stafox If you open Iphone Settings then 
Click Name Of Apple Id -> Itunes & App Store -> Apple Id -> View Apple Id - > Subscriptions 
this is where it should the subscriptions you bought, but it's not there in our case, plus it allows to proceed payment without payment method and still it says All successful.

**Comment by Stafox** [comment]
@Karlen92 please, read the Apple docs and how sandbox environment works. There is some different between sandbox and production behavior.

So, it is not an issue. To see what you have bought use verifyReceipt method.
