### ISSUE TITLE
requestSubscription and finishTransactionIOS  doesn't seem to work...

### ISSUE THREAD

**Issue by SuperDuperMartin** [dooboolab/react-native-iap#708]
Thanks for an awesome bridge for IAP! I have one issue tho...

### Version of react-native-iap
3.4.1
### Version of react-native
0.60
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
When i try to buy a subscription without billing added to iOS account, purchaseUpdatedListener should catch the purchase after billing added.
### Actual behavior
After added billing and staring app purchase is gone thru and i cant attach sub to user.
### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior

requestSubscription(selectedProduct.productId)

purchaseUpdatedListener((purchase: ProductPurchase) => {
      const receipt = purchase.transactionReceipt
      if (receipt) return validateReciept(purchase, kid) // our server validation
        .then((deliveryResult) => {
          if (isIOS()) finishTransactionIOS(purchase.transactionId)
          if (isAndroid()) acknowledgePurchaseAndroid(purchase.purchaseToken)
          return receipt
        })
})

has anyone got this to work?

**Comment by SuperDuperMartin** [comment]
@hyochan okay! but the IAP is purchased from appStore, but not attached to my user. So i was hoping for this method to catch the payment?

**Comment by hyochan** [comment]
All the `error` should be returned to `purchaseErrorListener`.

**Comment by SuperDuperMartin** [comment]
@hyochan thats what i was hoping for, but does not seem to be the case... shouldnt purchaseUpdatedListener listen for this purchase until i run finishTransactionIOS?
Or do i assume wrong?
