### ISSUE TITLE
IllegalStateException: Too many receivers

### ISSUE THREAD

**Issue by varungupta85** [dooboolab/react-native-iap#710]
### Version of react-native-iap 
3.4.6

### Version of react-native 
0.60.4

### Platforms you faced the error (IOS or Android or both?) 
Android

### Expected behavior 
No error

### Actual behavior
I got the following error on Sentry which is stemming from the `initConnection` call in the module.

<img width="837" alt="Screenshot 2019-09-12 at 5 39 02 PM" src="https://user-images.githubusercontent.com/7475133/64783255-02737b00-d585-11e9-8fe3-6a63f7a750ee.png">

I believe the fix for this could be to check if we have a valid and a ready `billingClient` before making a connection to make the call idempotent.

### Tested environment (Emulator? Real Device?) 
Real device

### Steps to reproduce the behavior: 
Error reported by production app on some user's phone

**Comment by UsamaWalayat** [comment]
i got the same error.....anyone knows the solution?

**Comment by chetan-plrch** [comment]
Even I have got the same error, any solution or information ?

**Comment by JameelNazir** [comment]
Same error

**Comment by Birat77** [comment]
Same here

**Comment by andresesfm** [comment]
Before version `7.0.0` there was a bug that would create a new connection every time some method in the native module was called. That bug has been solved in the latest build. Please update
