### ISSUE TITLE
getSubscriptions returning an empty array only in production env [iOS].

### ISSUE THREAD

**Issue by cuttlas** [dooboolab/react-native-iap#712]
### Version of react-native-iap

3.4.0

### Version of react-native

0.59.1

### Platforms you faced the error (IOS or Android or both?)

IOS

### Expected behavior

getSubscriptions method to fetch the subscription info from the AppStore.

### Actual behavior

We are experiencing something weird: The getSubscriptions method is returning an empty array ONLY in the production environment in a iOS device. It works perfectly in local development (both on a real device and a simulator), also works perfectly in Testflight (with the exact same version running in production and using the same device) and also works well in Android (both development and production). Any ideas?
It's worth pointing out that the Apple Id associated with the device I'm testing it has already an active subscription for the app. It's an old subscription with different id, not the subscriptions the app offers right now. Can this have some effect?

This is the code:

```
  try {
    return RNIap.getSubscriptions(["..."]);
  } catch (e) {
    sentry.captureException(new Error(e));
  }
```

It doesn't throw any exception. Just returns an empty array.

**Comment by hyochan** [comment]
Have you published your app with `iap products` selected?

**Comment by cuttlas** [comment]
Problem solved, and it had nothing to do with this awesome library.  If someone encounters a similar problem just be sure that Apple has reviewed and approved your products/subscriptions... be aware that they don't need to be approved to be accessible on TestFlight, but they will not work on production.
