### ISSUE TITLE
react-native-iap says success before I validate receipt. Even in cases when there is error it says success  

### ISSUE THREAD

**Issue by Karlen92** [dooboolab/react-native-iap#715]
### Version of react-native-iap
react-native-iap 3.4.0
### Version of react-native
react-native 0.60.4
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
I want to see dialog after I validate receipt and finish transaction
### Actual behavior
It alerts success before I validate and finish transaction
### Tested environment (Emulator? Real Device?)
Iphone 7 device
For appleID I use IOS sandbox tester account
### Steps to reproduce the behavior
`await RNIap.requestSubscription('WhoSwipedOnYou');` _this alerts the success popup regardless the result._
_It even does not wait for this_ `RNIap.finishTransactionIOS();`

**Comment by hyochan** [comment]
This looks expected as a native `ios` behavior. What you want should be done on your side.

**Comment by TiagoGouvea** [comment]
@Karlen92 you should use the `purchaseUpdatedListener` method to receive that result. The `requestSubscription` return could never come.
