### ISSUE TITLE
react-native-iap 4.0.0 discussion & proposal

### ISSUE THREAD

**Issue by hyochan** [dooboolab/react-native-iap#717]
I am currently working on new major release comming from `4.0.0` in #716.

You can get it beforehand by
`yarn add react-native-iap@next` or `npm install react-native-iap@next`.

Please give me any other opinions on the updates being given.

**Comment by Stafox** [comment]
Look at this fork, please  https://github.com/vovkasm/react-native-iap/commits/develop
He made some warnings fixes and type fixes.

**Comment by hyochan** [comment]
@Stafox Wow. It'd be better for him to push `PR` to the `next` branch. Do you know him?

**Comment by Stafox** [comment]
@hyochan I have asked him to do a PR already.

**Comment by hyochan** [comment]
@Stafox `next` branch is merged to `master`. Please tell him to push `PR` to `master` when ready.
