### ISSUE TITLE
Google Play In-app Billing API version is less than 3 

### ISSUE THREAD

**Issue by b3hz4d** [dooboolab/react-native-iap#720]
### Version of react-native-iap
3.4.6
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
Android

I have problem with using RNIap giving me this error and it want to initial and getavailable purchase

**Comment by hyochan** [comment]
It isn not correct. We are using In-app Biling API version 3 for android.

**Comment by b3hz4d** [comment]
I have this problem just with some android devices.
For example using two Samsung S8 in one of them i have no problem in other i have this error

**Comment by hyochan** [comment]
I think we need more information to dig into this `issue`.

**Comment by mistikk** [comment]
I have same problem, what information do you need @hyochan 
![image](https://user-images.githubusercontent.com/8211075/65959743-7b1a7880-e45b-11e9-80ad-00eb622cda9b.png)

**Comment by b3hz4d** [comment]
I found the problem
It was because of country and region of where device connecting to google

**Comment by jimbol** [comment]
> It was because of country and region of where device connecting to google
@b3hz4d could you go into a little more detail?

**Comment by msfstef** [comment]
has anyone figured out what exactly causes this and what we can do to help the user resolve the issue?
