### ISSUE TITLE
[Android] acknowledgePurchaseAndroid() Google is indicating that we have some issue connecting to payment.

### ISSUE THREAD

**Issue by MeisterTea** [dooboolab/react-native-iap#721]
### Actual behavior
I have got a 
```Google is indicating that we have some issue connecting to payment.``` error
In logcat I get a ```E/DoobooUtils: Error Code : 5```

I was using version 2.5.5 previously, it was working fine.
The only thing not working there is the acknowledgePurchaseAndroid call

### Tested environment > Real Device

Here is my code : 
```js
  handleServerSubscribe = async purchase => {
    const {
      productId,
      transactionReceipt,
    } = purchase
    if (transactionReceipt) {
      try {
          // FIXME it fails right here
          await acknowledgePurchaseAndroid(purchase.purchaseToken)

      } catch (e) {
        console.log('subscription error ', e)
      }
    }
  }


componentDidMount() {
    this.purchaseUpdateSubscription = purchaseUpdatedListener(purchase => {
      this.handleServerSubscribe(purchase)
    })
  }
```

**Comment by hyochan** [comment]
If `acknowledgePurchase` isn't working, it feels like you've not correctly updated `billingClient` in android to `2.0.3`. Could you check your `build.gradle`?

**Comment by MeisterTea** [comment]
@hyochan uh, it looks like it but I have no clue where I can get the correct syntax :/
Is it supposed to be in the README ?

**Comment by hyochan** [comment]
Try to find the line `com.android.billingclient:billing` by searching.

**Comment by MeisterTea** [comment]
Well, I didn't have it, I only had 
```gradle
 implementation project(':react-native-iap')
```

Do I need both implementations ?

```gradle
 implementation 'com.android.billingclient:billing:2.0.3'
 implementation project(':react-native-iap')
```

I stil have the same error

**Comment by hyochan** [comment]
@MeisterTea I wanted you to check the version of the `billingclient` in your installed `react-native-iap` project. Check inside `node_modules/react-native-iap/android/build.gradle`

**Comment by MeisterTea** [comment]
oh, my bad... Yes, it does have the right version

```gradle
  implementation 'com.android.billingclient:billing:2.0.3'
```

Any idea ?

**Comment by hyochan** [comment]
@MeisterTea I think I found useful [LINK](https://stackoverflow.com/questions/15322165/getting-response-code-as-5-in-inapp-billing-consumption-android) for you.

**Comment by hyochan** [comment]
@MeisterTea Was this helpful?

**Comment by MeisterTea** [comment]
Well, I still have the error

**Comment by MeisterTea** [comment]
Well, I still have the error : 
js bridge: ```Google is indicating that we have some issue connecting to payment.```
logcat: ```E/DoobooUtils: Error Code : 5```
```
await acknowledgePurchaseAndroid(purchase.purchaseToken)
```
, I have some questions:

- Do you have any other idea how I could fix the issue ?
- How can I debug and use my release key ? react-native run-android seems to always install a generic debug key even after copying my release keystore as debug.keystore and pointing to it inside the build.gradle

**Comment by MeisterTea** [comment]
Well, I still have the error : 
js bridge: ```Google is indicating that we have some issue connecting to payment.```
logcat: ```E/DoobooUtils: Error Code : 5```
```
await acknowledgePurchaseAndroid(purchase.purchaseToken)
```
, I have some questions:

- Do you have any other idea how I could fix the issue ?
- How can I debug and use my release key ? react-native run-android seems to always install a generic debug key even after copying my release keystore as debug.keystore and pointing to it inside the build.gradle 

EDIT: It's all the same with the sample project of react-native-iap.
I change the versionCode to the latest I uploaded on the beta track, gave it the release key, added my subscription id, changed the code to load subscriptions, done a react-native run-android variant=release

I can buy the subscription but I am still getting the error 5

**Comment by ivpusic** [comment]
having the same issue. any solution for this?

**Comment by MeisterTea** [comment]
Yes, it's to due to acknowledging a PENDING payment.
IMO, licence testers shouldn't have a PENDING state anyway so maybe Google is at fault there.

**Comment by ivpusic** [comment]
I get the same issue also for payments which have the state `purchaseStateAndroid` 1 (PURCHASED)

**Comment by maximedupre** [comment]
> Yes, it's to due to acknowledging a PENDING payment.

I confirm this

**Comment by matamicen** [comment]
I had the same problem and I realized that problem was that the PurchaseToken was already confirmed. So I fix the problem controlling the call to` await acknowledgePurchaseAndroid(purchase.purchaseToken).`  @hyochan 

Hope it helps.

**Comment by illiteratewriter** [comment]
> I get the same issue also for payments which have the state `purchaseStateAndroid` 1 (PURCHASED)

have you found the solution?

**Comment by schumannd** [comment]
I have had the same error message recently. So I'd say this should stay active.

**Comment by creativemind1** [comment]
I'm getting the same error with `RNIap.finishTransaction`

**Comment by hyochan** [comment]
@creativemind1 What version are you using? `finishTransaction` should work on both `iOS` and `android`.

**Comment by creativemind1** [comment]
I'm using `"react-native-iap": "^4.4.1"` and when I'm calling finishTransaction in Android, I'm getting error from Google `Google is indicating that we have some issue connecting to payment`. So after getting successful response from my server I'm calling `RNIap.acknowledgePurchaseAndroid` which is working but not `finishTransaction`

**Comment by dmitrybolt** [comment]
Same error, but I on getProducts

**Comment by rafaeelrf** [comment]
Same error, but in consumeProduct:
`Error: Google is indicating that we have some issue connecting to payment.
    at Object.fn [as consumeProduct] (VM4 index.bundle:2143)`

**Comment by creativemind1** [comment]
I think if you add the email address in the test users of.google play
settings you will nit see tgat issue

**Comment by rafaeelrf** [comment]
I already added, but the problem was not solved

**Comment by MeisterTea** [comment]
If I remember right, you can't do it client side when you are on test servers because there is a slight delay between issuing the payment and server validation.
We had to move this logic server side

**Comment by Rashi-jain21** [comment]
Hi I am getting the same error while  RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken); API. Can someone please help

**Comment by faris-mohamed10** [comment]
> I'm getting the same error with `RNIap.finishTransaction`

me too having this issue using the latest version and test card is used

**Comment by compelling** [comment]
Same problem here, calling RNIap.finishTransaction(purchase, true) from my purchaseUpdatedListener that gets called as it should just after my RNIap.requestSubscription. This leads to the error. After 5 min I get the cancellation mail "This test purchase was canceled because it was not confirmed" from Google. Of course, I am using a test account, but that ought to be ok.
The same code works like a charm on iOS.

**Comment by compelling** [comment]
@MeisterTea what did you do backend, did you find out what the equivalent google request of RNIap.finishTransaction(purchase, true) was? Can you share some more info, so the rest of us can use that solution until the plugin works again?

**Comment by faris-mohamed10** [comment]
my issue was, I was calling finishtransaction 2 times. when I removed it, worked fine

**Comment by compelling** [comment]
I got it working: I just made these specific lines for Android, but the need to do so was not very apparent from the documentation. Now it works both on Android and iOS:
`        // on Android we need to acknowledge purchase or finishTransaction fails
                            // if we do not acknowledge, purchase will roll back in 5 min
                            RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken).then(() => {
                                RNIap.finishTransaction(purchase, true).catch(err => {
                                    console.log(err.code, err.message);
                                });
                            });
`

**Comment by odanicola** [comment]
i dont know if this working or not for you (this code for consumeProduct):

`await RNIap.finishTransaction(purchase).then(async () => {
                        await RNIap.consumePurchaseAndroid(purchase.purchaseToken).then(async () => {
                            console.log('purchase :', purchase)
                        }).catch(err => {
                            console.log('consume error: ', err.code, err.message)
                            Alert.alert('consume finish error: ', err.message)
                        });
                    }).catch(err => {
                        console.log('finish error: ', err.code, err.message)
                        Alert.alert('purchase finish error: ', err.message)
                    })`

I need to finish the transaction at first then revoke the purchase by hitting the consumePurchaseAndroid() as the code above. Hope it helps.

**Comment by ssg-luke** [comment]
> I got it working: I just made these specific lines for Android, but the need to do so was not very apparent from the documentation. Now it works both on Android and iOS:
> ` // on Android we need to acknowledge purchase or finishTransaction fails`
> ` // if we do not acknowledge, purchase will roll back in 5 min`
> ` RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken).then(() => {`
> ` RNIap.finishTransaction(purchase, true).catch(err => {`
> ` console.log(err.code, err.message);`
> ` });`
> ` });`

That seems to work for me too, i'm using v5.0.0

**Comment by ksielyov** [comment]
Getting same when:

**Comment by ksielyov** [comment]
purchase error Error: Google is indicating that we have some issue connecting to payment.
    at Object.promiseMethodWrapper [as buyItemByType] (VM4 index.bundle:2242)
    at VM4 index.bundle:142829
    at step (VM4 index.bundle:142328)
    at Object.next (VM4 index.bundle:142258)
    at fulfilled (VM4 index.bundle:142212)
    at tryCallOne (VM4 index.bundle:27056)
    at VM4 index.bundle:27157
    at VM4 index.bundle:30708
    at _callTimer (VM4 index.bundle:30596)
    at _callImmediatesPass (VM4 index.bundle:30635)

**Comment by diegogurgel** [comment]
I was getting this error and I added `implementation 'com.android.billingclient:billing:4.0.0'`  to my `/app/build.gradle`. I didn't test in release mode yet but it seems to solve the issue.

**Comment by pasindu-codimite** [comment]
I used hooks given in react-native-iap library, Then I had to use above solution like below,

          if (Platform.OS == 'android' && currentPurchase.purchaseToken) {
            acknowledgePurchaseAndroid({
              token: currentPurchase.purchaseToken,
              developerPayload: currentPurchase.developerPayloadAndroid,
            })
              .then(() => {
                finishTransaction({
                  purchase: currentPurchase,
                  isConsumable: true,
                  developerPayloadAndroid:
                    currentPurchase.developerPayloadAndroid,
                }).catch(err => {
                  console.error(err.code+" finish", err.message);
                });
              })
              .catch(err => {
                console.error(err.code+ " acknowledge", err.message);
              });
          } else {
            await finishTransaction({
              purchase: currentPurchase,
              isConsumable: true,
            });
          }

**Comment by jiemar** [comment]
> I used hooks given in react-native-iap library, Then I had to use above solution like below,
> 
> ```
>       if (Platform.OS == 'android' && currentPurchase.purchaseToken) {
>         acknowledgePurchaseAndroid({
>           token: currentPurchase.purchaseToken,
>           developerPayload: currentPurchase.developerPayloadAndroid,
>         })
>           .then(() => {
>             finishTransaction({
>               purchase: currentPurchase,
>               isConsumable: true,
>               developerPayloadAndroid:
>                 currentPurchase.developerPayloadAndroid,
>             }).catch(err => {
>               console.error(err.code+" finish", err.message);
>             });
>           })
>           .catch(err => {
>             console.error(err.code+ " acknowledge", err.message);
>           });
>       } else {
>         await finishTransaction({
>           purchase: currentPurchase,
>           isConsumable: true,
>         });
>       }
> ```

It doesn't work.
After changing code like this, err remain
'E_DEVELOPER_ERROR finish', 'Google is indicating that we have some issue connecting to payment.'

**Comment by cetfu** [comment]
Getting same error. Is there any solution?

[Error: Google is indicating that we have some issue connecting to payment.]

Tested on real device. in debug-release modes

**Comment by cetfu** [comment]
https://github.com/dooboolab-community/react-native-iap/blob/aab948226fd075c759022503af45286262e8ff97/IapExample/src/screens/Subscriptions.tsx#L68C12-L68C32
i guess it was a wrong usage. 

https://github.com/dooboolab-community/react-native-iap/issues/2578#issuecomment-1802669630
This usage solved my problem
