### ISSUE TITLE
getProducts and getSubscriptions returns empty array

### ISSUE THREAD

**Issue by alexpchin** [dooboolab/react-native-iap#723]
### Version of react-native-iap
3.4.11

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
Currently, I'm only working on iOS.

### Expected behavior
Should see auto-renewable subscriptions

### Actual behavior
Receiving an empty array:

<img width="192" alt="Screenshot 2019-09-20 at 08 08 52" src="https://user-images.githubusercontent.com/40461/65306701-f0de3480-db7d-11e9-9130-432581b22788.png">

### Tested environment (Emulator? Real Device?)
Mainly tested in the Simulator (Although, I tried on a real device yesterday and it was still empty)

### Steps to reproduce the behavior
So to clarify, I originally believed it to be because I had not finalised a tax form in the Agreements, Tax and Banking section of iTunes connect:

<img width="992" alt="Screenshot 2019-09-19 at 17 26 47" src="https://user-images.githubusercontent.com/40461/65306765-179c6b00-db7e-11e9-804b-d699b54b3915.png">

However, this has now been completed:

<img width="989" alt="Screenshot 2019-09-20 at 08 11 33" src="https://user-images.githubusercontent.com/40461/65306840-4ca8bd80-db7e-11e9-834d-c2fa1055d8c2.png">

I have created two products with the product ids `artistsannual` and `artistmonthly`. My bundle id is `com.iynk.iynk`.

<img width="946" alt="Screenshot 2019-09-20 at 08 12 50" src="https://user-images.githubusercontent.com/40461/65306925-782ba800-db7e-11e9-8613-38718fc79b1e.png">

They are both "Ready to Submit".

My code:

```
const subscriptionSKUs = Platform.select({
  ios: ['artistmonthly', 'artistannual'],
  android: [''],
});

class Upsell extends React.Component {
  .
  .
  .
    async componentDidMount() {
    try {
      const result = await RNIap.initConnection();
      console.log('result', result);

      const subscriptions = await RNIap.getSubscriptions(subscriptionSKUs);
      console.log('subscriptions', subscriptions);

      const products = await RNIap.getProducts(subscriptionSKUs);
      console.log('products', products);
    .
    .
    .
    } catch (e) {
      console.log('Error handling in Upsell componentDidMount', e);
    }
  }
  .
  .
  .
}
```

The response is:

- result: `true`
- subscriptions: `[]`
- products: `[]`

I have run `react-native link react-native-iap`.

I have also tried to implement `revenuecat`: https://github.com/RevenueCat/react-native-purchases Which is getting the Entitlements but not the products?

Do I need to "Submit the App" before Subscriptions and Products show up? How do you work on development products if this is the case?

I'm very stuck... Thanks in advance everyone!

**Comment by hyochan** [comment]
Have you checked `In App Purchase` in the xcode setting?

**Comment by alexpchin** [comment]
Yes, I have toggled on ‘In App Purchase’ in Xcode. Any other suggestions? I am still getting an empty array.

**Comment by alexpchin** [comment]
Ok, I have resolved the problem with the use of this StackOverflow post: https://stackoverflow.com/questions/7947805/ios-in-app-purchase-no-products-received/11707704#11707704

The issue was that my bundleID was auto-created by react-native:  `org.reactjs.native.example.xxx`. I had to change to be the correct one in all relevant files.

**Comment by hyochan** [comment]
@alexpchin Good job!

**Comment by wmonecke** [comment]
> Ok, I have resolved the problem with the use of this StackOverflow post: https://stackoverflow.com/questions/7947805/ios-in-app-purchase-no-products-received/11707704#11707704
> 
> The issue was that my bundleID was auto-created by react-native: `org.reactjs.native.example.xxx`. I had to change to be the correct one in all relevant files.

Hi, @alexpchin I am having this same issue for 4 hours now and don't know what to do. My bundleID was also created by RN. What exactly did you change to make it work??

**Comment by ManalLiaquat** [comment]
I solved it! I am using these versions,

`react-native-iap: ^4.3.0`
`react-native: 0.60.5`

just do it like this
```
const itemSkus = Platform.select({
    ios: [
        '100coins' // just remove bundle id from product id
    ],
    android: [
        '100coins' // just remove bundle id from product id
    ]
});
```

**Comment by roots-ai** [comment]
[iOS] Is it possible to get the product in `getProducts` without the product being submitted for review at apple store?
If yes, then I am still getting `getProducts` as an empty array.

**Comment by youssefatti** [comment]
@roots-ai Hello did you get it work?

**Comment by Akshay-Chhikara** [comment]
@roots-a - Did manual linking and also made sure that the agreement, tax, and banking were completed in case of iOS.

**Comment by youssefatti** [comment]
@Akshay-Chhikara Thank you for your reply. it works i just have to wait between the moment of its ready to submit and to getProducts.

For all just try to wait at least 24h

**Comment by selimmidikoglu** [comment]
> Ok, I have resolved the problem with the use of this StackOverflow post: https://stackoverflow.com/questions/7947805/ios-in-app-purchase-no-products-received/11707704#11707704
> 
> The issue was that my bundleID was auto-created by react-native: `org.reactjs.native.example.xxx`. I had to change to be the correct one in all relevant files.

How did you achieve that with which files?

**Comment by bulby97** [comment]
> > Ok, I have resolved the problem with the use of this StackOverflow post: https://stackoverflow.com/questions/7947805/ios-in-app-purchase-no-products-received/11707704#11707704
> > The issue was that my bundleID was auto-created by react-native: `org.reactjs.native.example.xxx`. I had to change to be the correct one in all relevant files.
> 
> How did you achieve that with which files?

@alexpchin Trying to solve this to. I'm using schemes to change my bundle id for dev / staging / prod.

Is there something else I need to do ?

**Comment by selimmidikoglu** [comment]
@bulby97 There were tons of 

-   First thing was to check if all subscriptions were on stage 'Ready to Submit'.
-   Second thing was to fill all the required things on itunnesconnect **Agreement, Tax, Banking** part. This part was kinda difficult because address field can not be filled with coorect address. You just need to submit 5 times. Apple is really interesting company.

-  I changed bundle ids in both xcode and itunnes connect. Than I tried to run app on real device. 
-  Than boom my in app purchases was there. 

As I see the problem genrally lie beneath by missing one step in configuration state. There is nothing related with code.

**Comment by bulby97** [comment]
@selimmidikoglu Sweet ! Changing my bundle id did the trick ! Awesome !

So basically there is no way to test in app purchases by having dev / staging / release environments.

It should be written somewhere it's not obvious at all I spent 3 days on this issue.

**Comment by selimmidikoglu** [comment]
@bulby97 
Actually since I am creating small apps. I never went development and production stages. I only add my account to TestFLight for in app purchase test. I wrote a function which deletes current paid subscriptions  in app purchases. So I am testing all posssibilities by deleting my subscription. While I make payment on my phone it already says [Sandbox account]. So it makes it testible easily. It is harder in Android for sure.

**Comment by AlexanderZaytsev** [comment]
@selimmidikoglu 
Did products/subscriptions appear only on your real device or on a simulator as well?

**Comment by AlexanderZaytsev** [comment]
**Update**
Got subscriptions appearing on the simulator after erasing the device&content and signing into iCloud again.

**Comment by selimmidikoglu** [comment]
@AlexanderZaytsev I could not make subscriptions/products appearing on my simulator. But I think it is possible but I do not know how.

**Comment by Mindbowser** [comment]
Hi Guys,

It seems that we are getting the array empty even after following all the steps, any idea or pointers to loog for?

**Comment by KhimGurung** [comment]
I had same issue, In my case both catch and then section were executing, dont know why. I was testing in simulator. Testing in real devices works as intended

**Comment by Mindbowser** [comment]
For me, On simulator it worked after adding store-kit configuration under schema. Only thing it will not work on simulator is receipt validation as simulator not giving proper receipt, but it worked on actual device for me

**Comment by BogdanRad** [comment]
hey guys, i have a interesting problem.. on ios emulator i have received the products and on real ios in testflight i haven't received.. Where is the problem?..

**Comment by MutableLoss** [comment]
I know most fixes have been mentioned here, but it seems like I ran into every possible issue to cause an empty product response. Since there were so many possibilities, here is a collective checklist:

**What to Check Locally:**
- Be sure you are calling getProducts in the initConnection callback
- If your app changed names at one point, verify that the bundleId is correct in all files
- Verify that you are passing the product sku array to getProducts (passing undefined will cause an empty response*)
**iOS Only:**
- in Xcode: Enable the IAP Capability in Main App Target (Target > Signing & Capabilities)
- For testing in the iOS Emulator, setup products in a local [Storekit configuration](https://developer.apple.com/documentation/xcode/setting_up_storekit_testing_in_xcode) 

**What to Check for Production with iOS (App Store Connect):**
- Verify the bundleId matches in the Project and in the App Store Connect provisioning profile
- Double check that all policies are accepted, that there are no issues with the bank account used, and that all contacts fields are filled out. You should show an "active" status for the Paid Apps Agreement
- Be sure you are have IAP Capability enabled in the App's Identifier (Apple Developer > Certificates > Identifiers)
- If you have multiple provisioning profiles with the same bundle ID, select the provisioning profile manually. Automatic management does not choose the latest profile
- If any of your IAP products show a "Missing Metadata" status, be sure to fill out the Review Information section (requires screenshot)

There are so many possible issues, I really hope this helps someone else.

*_I was really surprised you could pass **undefined** to getProducts. Is there any reason this method needs to fail silently when the param is undefined? The fact I had it setup incorrectly after a transition from the old RNIAP setup, makes me wonder if it could be a possible common issue._

**Comment by Pooj797** [comment]
Hi Guys,

 Getting the array empty even after following all the steps, any idea to look for it?

**Comment by MutableLoss** [comment]
@Pooj797 maybe try setting your getProducts to a specific product, and that way you can rule out an issue in the code. For example, but replace *myProductName* with one of your product skus you have setup:

```
RNIap.initConnection().then(output =>
     RNIap.getProducts('myProductName').then(products =>
         console.log(`Products: ${JSON.stringify}`)))
```

If setting it to a specific product allows you to get a products response, it means there is an issue with the code. Note: It will return an empty array if you pass '' to getProducts. If you still get an empty array, you know it is an issue with the product or product name. 

Hope that helps.

**Comment by Pooj797** [comment]
> @Pooj797 maybe try setting your getProducts to a specific product, and that way you can rule out an issue in the code. For example, but replace _myProductName_ with one of your product skus you have setup:
> 
> ```
> RNIap.initConnection().then(output =>
>      RNIap.getProducts('myProductName').then(products =>
>          console.log(`Products: ${JSON.stringify}`)))
> ```
> 
> If setting it to a specific product allows you to get a products response, it means there is an issue with the code. Note: It will return an empty array if you pass '' to getProducts. If you still get an empty array, you know it is an issue with the product or product name.
> 
> Hope that helps.

@MutableLoss thanks for reply
Issue is fixed i am using store kit configuration file so response is not coming of app store connect product Id's

**Comment by guptavishesh143** [comment]
This helped me in getting products from Appstore

`
  useEffect(() => {
    const checkCurrentPurchase = async () => {
      const connection = await RNIap.initConnection();

      if (connection === true) {
        const clearProducts = await RNIap.clearProductsIOS();
        console.log("clear Products", clearProducts);
        const subscriptions = await RNIap.getSubscriptions({
          skus: Platform.select({
            ios: ["product_id"],
            android: ["product_id"],
          }),
        });

        console.log("subscriptions", subscriptions);
      }

      
    };

    checkCurrentPurchase();
  }, []);
`

**Comment by aramvr** [comment]
In my case, it just needed to accept the agreement for paid apps here https://appstoreconnect.apple.com/agreements/#/
It took me like 5 hours to figure it out!

**Comment by spookyuser** [comment]
> I know most fixes have been mentioned here, but it seems like I ran into every possible issue to cause an empty product response. Since there were so many possibilities, here is a collective checklist:
> 
> **What to Check Locally:**
> 
> * Be sure you are calling getProducts in the initConnection callback
> * If your app changed names at one point, verify that the bundleId is correct in all files
> * Verify that you are passing the product sku array to getProducts (passing undefined will cause an empty response*)
>   **iOS Only:**
> * in Xcode: Enable the IAP Capability in Main App Target (Target > Signing & Capabilities)
> * For testing in the iOS Emulator, setup products in a local [Storekit configuration](https://developer.apple.com/documentation/xcode/setting_up_storekit_testing_in_xcode)
> 
> **What to Check for Production with iOS (App Store Connect):**
> 
> * Verify the bundleId matches in the Project and in the App Store Connect provisioning profile
> * Double check that all policies are accepted, that there are no issues with the bank account used, and that all contacts fields are filled out. You should show an "active" status for the Paid Apps Agreement
> * Be sure you are have IAP Capability enabled in the App's Identifier (Apple Developer > Certificates > Identifiers)
> * If you have multiple provisioning profiles with the same bundle ID, select the provisioning profile manually. Automatic management does not choose the latest profile
> * If any of your IAP products show a "Missing Metadata" status, be sure to fill out the Review Information section (requires screenshot)
> 
> There are so many possible issues, I really hope this helps someone else.
> 
> *_I was really surprised you could pass **undefined** to getProducts. Is there any reason this method needs to fail silently when the param is undefined? The fact I had it setup incorrectly after a transition from the old RNIAP setup, makes me wonder if it could be a possible common issue._

This was so helpful thank you!

**Comment by mathysFor** [comment]
Follow these steps one by one; they worked for me. The one that made the difference was 'Enable StoreKit Testing in Xcode'.
https://developer.apple.com/documentation/xcode/setting-up-storekit-testing-in-xcode#Enable-StoreKit-Testing-in-Xcode

**Comment by KaulSalil** [comment]
@mathysFor the solution that you mentioned did it help for testing on real device as well ?

**Comment by KaulSalil** [comment]
@mathysFor Just to clarify you enabled StoreKit to test without using apple connect right ?
