### ISSUE TITLE
Possible issue with requestPurchase promise

### ISSUE THREAD

**Issue by doomsower** [dooboolab/react-native-iap#725]
This is not a confirmed bug, since I'm rewriting my app to v3/v4 and haven't tested it manually yet. These are just some observations and a feature request.

Firstly, I've examined iOS and Android `requestPurchase`promises and found inconsistency. On iOS, promises are resolved on [per-purchase basis](https://github.com/dooboolab/react-native-iap/blob/67d3720024b6c0464dd47550562e3da2b26b67b0/ios/RNIapIos.m#L445): 

```objc
[self resolvePromisesForKey:RCTKeyForInstance(transaction.payment.productIdentifier) value:purchase];
```

On Android it seems that there's [one promise](https://github.com/dooboolab/react-native-iap/blob/9bcc75ce2774644b32fdcd6d845e64e0a223741d/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L516) for all `requestPurchase` calls:

```java
DoobooUtils.getInstance().resolvePromisesForKey(PROMISE_BUY_ITEM, item);
```

I'm not deeply familiar with IAP flows, but it seems that if user tries to buy 2 products in quick succession, then one of the `requestPurchase` calls might never reject or resolve. Or maybe it'll throw because of resolving same promise twice. Why not use product identifier as promise key as on iOS?

Secondly, a related issue. When `requestPurchase` rejects, it's possible to know which purchase has failed, because `requestPurchase` arguments are in the same scope. However, `purchaseErrorListener` receives only the error code and message, so there's no way to know which purchase failed. So I think `productId` field should be added to `PurchaseError`.

### Version of react-native-iap

`next` branch

**Comment by AustP** [comment]
I am using version 3.4.12 and am having an issue with `requestPurchase`'s promise on Android.

The problem I am having with it is that it never resolves after going through the purchase process. Interestingly, it rejects if I cancel the process halfway, but if I finish the process, it never resolves.

**Comment by hyochan** [comment]
I've reviewed #724. `requestPurchase` should not resolve `promises` in the next major release which you can use by `yarn install react-native-iap@next`.

**Comment by doomsower** [comment]
What about the second part of this issue?

> However, purchaseErrorListener receives only the error code and message, so there's no way to know which purchase failed. So I think productId field should be added to PurchaseError.

Without this `purchaseErrorListener` is useless and I have to use promises.

**Comment by hyochan** [comment]
> What about the second part of this issue?
> 
> > However, purchaseErrorListener receives only the error code and message, so there's no way to know which purchase failed. So I think productId field should be added to PurchaseError.
> 
> Without this `purchaseErrorListener` is useless and I have to use promises.

Thanks for your thought. I'll consider this for the next release.
