### ISSUE TITLE
How to check which plan is user subscribed to

### ISSUE THREAD

**Issue by sidpauhal** [dooboolab/react-native-iap#727]
### Version of react-native-iap
"react-native-iap": "^3.4.4",

### Version of react-native
"react-native": "0.60.5",

### Platforms you faced the error (IOS or Android or both?)
both

I have added monthly autorenewal subscription plans in Google play dashboard
Silver, Gold, Platinum

I am subscribing users like this
const products = await RNIap.requestSubscription('gold_membership');

I want to check which plan is user subscribed to and display in app that he is a Gold or silver member.

As mentioned in docs RNIap.getAvailablePurchases(); returns all purchases

but I want to check which subscription plan is user currently subscribed to.

Any help, guidance ?

**Comment by kevinetore** [comment]
@sidpauhal [This](https://github.com/chirag04/react-native-in-app-utils/issues/73) could be interesting.

**Comment by sidpauhal** [comment]
In android I am doing like this

```
const itemSkus = Platform.select({
	ios: [
		'silver_membership', 'gold_membership', 'platinum_membership'
	],
	android: [
		'silver_membership', 'gold_membership', 'platinum_membership'
	]
});

const purchases = await RNIap.getAvailablePurchases();
if(purchases !== null && purchases.length > 0){
	let current_plan = 'free';
	for (var i = 0; i < itemSkus.length; i++) {
		for (var j = 0; j < purchases.length; j++) {
			if(purchases[j].productId == itemSkus[i] && purchases[j].autoRenewingAndroid == true){
				current_plan = purchases[j].productId;
				break;
			}
		}
		if(current_plan != 'free'){
			break;
		}
	}
	this.update_subscription(current_plan);
}
```

I think this is not possible in IOS
Any help?
If it is not possible in IOS I will try another lib
react-native-in-app-utils

**Comment by kevinetore** [comment]
@sidpauhal Why wouldn't it be possible in iOS? If I'm correct I think you'd only need to figure out something for `autoRenewingAndroid` on iOS. Other than that you should be fine. I don't have much experience with `react-native-iap` yet, currently doing some research on how to implement IAP.

**Comment by sidpauhal** [comment]
@kevinetore @hyochan can we get product id from ios receipt 
I have to check which plan is user susbcribed to?

something like this
const renewalHistory = receipt.latest_receipt_info
const expiration = renewalHistory[renewalHistory.length - 1].expires_date_ms
if(expiration > Date.now()){
current_active_plan = receipt.product_id
}

**Comment by hyochan** [comment]
@sidpauhal I am not sure about this. However, I've been saving `receipt` and `productId` together in my backend database so I didn't have any situation like this.

**Comment by hanishcodebrew** [comment]
I am looking for the same answer in Android. Please help.

**Comment by daba-faith** [comment]
> @sidpauhal I am not sure about this. However, I've been saving `receipt` and `productId` together in my backend database so I didn't have any situation like this.

Receipt is always different everytime a user tries to purchase, even when the user is already subscribed to the product, a new receipt is generated 🥲, how do we go about that?
