### ISSUE TITLE
Seems like missing declaration and export of getPromotedProductIOS() and buyPromotedProductIOS()

### ISSUE THREAD

**Issue by su1736** [dooboolab/react-native-iap#729]
### Version of react-native-iap
3.4.12
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
normal working: return productId and open AppStore purchase process
### Actual behavior
javascript error in debugger like "getPromotedProductIOS is not a function"
### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior
Try to use these functions.

<br><br>
After I added declaration and export in index.d.ts and index.js all works well.

index.d.ts
```
  ...
  export function getPromotedProductIOS(): Promise<Product<string>>;
  export function buyPromotedProductIOS(): Promise<ProductPurchase>;
```

index.js
```
export default {
  ...,
  getPromotedProductIOS,
  buyPromotedProductIOS,
};
```

**Comment by hyochan** [comment]
You are right. I've just release `3.4.13` with update. Consider giving `PR` next time! Thank you.
