### ISSUE TITLE
I got an Error "null is not an object(evaluating 'o.refreshItems'....."

### ISSUE THREAD

**Issue by openmaya** [dooboolab/react-native-iap#732]
### Version of react-native-iap
"react-native-iap": "^3.4.4",

### Version of react-native
0.59.8

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
get Available Subscription Items

### Actual behavior
get Error

"null is not an object(evaluating 'o.refreshItems'....."

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
run app

In ComponentDidMount
RNIap.initConnection()
await RNIap.consumeAllItemsAndroid();

#### code

  async componentDidMount() {
    // Doooooooo Lib
    try {
      const result = await RNIap.initConnection();
      await RNIap.consumeAllItemsAndroid();
      console.log('result', result);
    } catch (err) {
      console.log(err.code, err.message);
      this.screenLog(err.message);
    }

    purchaseUpdateSubscription = purchaseUpdatedListener(async (purchase: ProductPurchase) => {
      console.log('purchaseUpdatedListener', purchase);
      if (purchase.purchaseStateAndroid === 1 && !purchase.isAcknowledgedAndroid) {
        try {
          const ackResult = await acknowledgePurchaseAndroid(purchase.purchaseToken);
          console.log('ackResult', ackResult);
        } catch (ackErr) {
          console.warn('ackErr', ackErr);
        }
      }
      this.setState({ receipt: purchase.transactionReceipt }, () => this.goNext());
    });

    purchaseErrorSubscription = purchaseErrorListener((error: PurchaseError) => {
      console.log('purchaseErrorListener', error);
      Alert.alert('purchase error', JSON.stringify(error));
    });

  }

**Comment by hyochan** [comment]
Could you please try our recent version and come back? If I remember correctly this is resolved.

**Comment by openmaya** [comment]
OK, I will be back

**Comment by openmaya** [comment]
I updated library but has Same Issue

**Comment by hyochan** [comment]
Well this looks expected when I've checkout again. So it seems you've received the message from the `error` handler which `purchases` are actually null that means there is nothing to consume at the moment.

**Comment by openmaya** [comment]
I change my code to step by step like below 

> try {
      const result = await RNIap.initConnection();
      this.screenLog(`initConnection:${result}`);
    } catch (err) {
      console.log(err.code, err.message);
      this.screenLog(err.message);
    }

but I got the result value 'undefined'

**Comment by hyochan** [comment]
@openmaya Where did you find this message coming from? Inside the `try` or `catch`?

**Comment by openmaya** [comment]
@hyochan 
I found it in try section, I made it by using expo.

**Comment by openmaya** [comment]
"null is not an object(evaluating 'o.refreshItems " message is from 

> try {
      await RNIap.consumeAllItemsAndroid();
    } catch (err) {
      console.log(err.code, err.message);
      this.screenLog(`consumeAllItemsAndroid:${err.message}`);
      this.screenLog(err.message);
    }

**Comment by hyochan** [comment]
Have you `ejected` your `expo` app? If not, our module won't work as expected.

**Comment by openmaya** [comment]
I ejected my project and upload on play store, but still have same 
initConnection -> result => undefined in try
getSubsscription -> null is not an object (evaluating 'c.getItemsByType')

**Comment by openmaya** [comment]
After link this module, I got other issue.
You can close this issue because it is from not bare project

**Comment by smalbois-panoptio** [comment]
Getting the same issue as above on Android - any idea please?
