### ISSUE TITLE
null is not an object (evaluating 'RNIapModule.startListening')

### ISSUE THREAD

**Issue by voxspox** [dooboolab/react-native-iap#734]
### Version of react-native-iap
3.4.12

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Actual behavior
Exception when calling iap.initConnection()

    null is not an object (evaluating 'RNIapModule.startListening')

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
can not reproduce, because it is on a user device.

### Misc

maybe related to #600

**Comment by voxspox** [comment]
appears on device with Android API level 25

**Comment by hyochan** [comment]
@emilioicai Do you have any idea on this issue?

**Comment by hoboman313** [comment]
I've been running into this exact issue on an android 10 device and emulator. Switching back to "3.4.15" fixed the issue for me.

**Comment by TheTimeWalker** [comment]
Same issue with mine. Reverting to 3.4.15 fixed it for me also. I have everything set up for AndroidX if that helps.

React Native: 0.61.1
RN IAP: 3.5.8
Android: 9.0

**Comment by drbarto** [comment]
I encountered the same error today. Reverting to version 3.4.15, as described above, did _not_ fix the issue for me.

Anybody on this issue got any new insights? I assume even if the revert fix works for you, that's not a viable permanent solution.

**Comment by TheTimeWalker** [comment]
I never encountered this issue again. The last time I was able to "fix" this by just cleaning cache, node_modules, etc. and rebuilding.
