### ISSUE TITLE
How to transfer/gift consumables purchased for an iOS app?

### ISSUE THREAD

**Issue by skizzo** [dooboolab/react-native-iap#735]
Hi! 

First of all, thanks for this amazing library. I use it in one of my apps and it works like a charm. I apologize for this being a bit of a generic question, but I figure that this might be a good place to ask this question.

According to [a couple][1] of [articles][2] I found, it's possible to transfer/gift In-App Purchases to other users. For example, a consumable in a game. Thing is, I can find zero instructions/tutorials about how to actually do this, neither on a user- nor a development level.

So, does anybody know a thing or two about this?

Thanks!

  [1]: https://www.geek.com/tech/apple-will-now-let-you-gift-in-app-purchases-1766974/
  [2]: https://www.theverge.com/2018/12/19/18149219/apple-app-store-ios-iphone-in-app-purchases-gifting-holidays

**Comment by hyochan** [comment]
Well I've not yet seen feature like this. However, I think you can still implement this using `consumable` products. Since `consumable` purchases will be handled in your own backend.
