### ISSUE TITLE
Types wrong in 3.5.1

### ISSUE THREAD

**Issue by jvandenaardweg** [dooboolab/react-native-iap#740]
### Version of react-native-iap
3.5.1

### Version of react-native
0.61.0

### Platforms you faced the error (IOS or Android or both?)
both

### Expected behavior
no type errors

### Actual behavior
type errors on `acknowledgePurchaseAndroid` and `requestSubscription`. But maybe more.

### Tested environment (Emulator? Real Device?)
emulator

### Steps to reproduce the behavior
running the latest version and then do your type checking

# Solution

```typescript
requestSubscription = (sku: string, oldSku: string, prorationMode: number)
```

Should be:

```typescript
requestSubscription = (sku: string, oldSku?: string, prorationMode?: number)
```

and...

```typescript
acknowledgePurchaseAndroid = (token: string, developerPayload: string)
```

Should be:
```typescript
acknowledgePurchaseAndroid = (token: string, developerPayload?: string)
```

I guess there are more of these little things now since the `index.d.ts` is gone and `index.ts` does not yet reflect those types. Don't have the time to go through them all at this moment. Just letting you know the types should be looked at :-)

**Comment by nenjamin2405** [comment]
I'm facing the same problem, the fields `oldSku ` and `prorationMode` of `requestSubscription` should be optional

**Comment by hyochan** [comment]
You guys are right. Sorry that I've missed this out. Today, I've just migrated our project to `typescript` since there are so many issues related to typings. Now we only need to concentrate on `ts` file and `flow` and `js` will be auto generated.

**Comment by nenjamin2405** [comment]
Thanks a lot @hyochan

**Comment by jvandenaardweg** [comment]
Thanks @hyochan for the fast response. Will try it out soon!
