### ISSUE TITLE
getAvailablePurchases on iOS let appear a dialog "Sign in to iTunes Store"

### ISSUE THREAD

**Issue by voxspox** [dooboolab/react-native-iap#747]
### Version of react-native-iap
3.4.13

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
getAvailablePurchases has no side effects

### Actual behavior
Calling `getAvailablePurchases` on iOS let appear a dialog "Sign in to iTunes Store".

This does not happen on Android.

![IMG_0020](https://user-images.githubusercontent.com/1503565/65967536-0860cb80-e462-11e9-855d-5181b6a2df0a.PNG)

I'm calling `getAvailablePurchases` during app start to restore the purchased items. According to the documentation I understood that this is the common way, right?

To restore the purchased items I'm calling `getAvailablePurchases` based on changes of [AppState](https://facebook.github.io/react-native/docs/appstate). Unfortunately the AppState is not only triggered on app start but also p.ex. after returning to the app from a dialog (caused by the app) p.ex. Sign In to iTunes... :(

For the user this is bothering. Especially if the user is not intending to buy something he would not want to enter his credentials to get rid of this dialog.

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
call getAvailablePurchases

**Comment by alexpchin** [comment]
When in development, this shows so that you can login with your sandbox account. I don’t believe the docs are very clear on this.

**Comment by mifi** [comment]
I think for production it may also show a prompt whenever calling this function, right? The way I implemented this is I call this when the user presses "restore purchase" and after purchaseUpdatedListener is called

**Comment by hyochan** [comment]
Hey @voxspox @alexpchin is right. @alexpchin Since we are working on the bridge, we assume that people might know little bit about `IAP` in native. Putting all things which already exist in each platform is quite a burden for maintainers. If there are some works on document that you think might be helpful, please feel free to add anything and push a `PR`.

**Comment by voxspox** [comment]
@mifi I've never seen an app with a "restore my purchases" button. From a UX perspective such a button is a burden and also unnecessary, because the app should know what I have bought ;)

@hyochan I get the prompt also after distributing the app via TestFlight (I assume this is production mode?!)

**Comment by mifi** [comment]
I've seen a few apps with that function. I don't quite remember now but I think it is needed (or required by apple) in some cases. Also in Apple's app store guideline examples they have this button:
https://developer.apple.com/app-store/subscriptions/

Also I thought it would be bad UX if the user ever has to enter their apple ID when opening my app, i think that would be confusing. (i've seen this happen before if session is expired or something happens with SSL MITM)

**Comment by voxspox** [comment]
Is there maybe a way to know before calling `getAvailablePurchases` that the prompt will appear? Or in other words, how can I detect if the user is connected to iTunes or not?

**Comment by cemocanon** [comment]
1+ same

**Comment by Zontex** [comment]
Hi guys, any answer on this? as I understand this is a debugging functionality but I'm testing with testflight and I want to prevent this from happening, is is it possible to somehow leave the sandbox mode?

**Comment by voxspox** [comment]
Meanwhile, I have found solution for me. I introduced a new variable `isRestorePurchasesEnabled` which is permanently stored by my app.

Init:

    isRestorePurchasesEnabled = false

On app start:

    if (Android || isRestorePurchasesEnabled) {
      call getAvailablePurchases
      on error.code === 'E_USER_CANCELLED' -> isRestorePurchasesEnabled= false
    }

On purchase:

    isRestorePurchasesEnabled = true
    requestSubscription ...

Settings:

    Button "restore purchases" -> isRestorePurchasesEnabled = true

The user will never see the connect-iTunes-prompt again. The restoring only happens after a purchases was done and thus the credentials have been already typed in + stored and the prompt will not be shown.
The only case where the prompt will be shown, but only once, is if the user logs out in Settings / iTunes / Sandbox Account. Don't know if this is there in production mode.

**Comment by ahmetfarukekinci** [comment]
Hello, 
I am really confused about one topic, can somebody help me ? 
I want to construct a controller that checks whether user still own the product or not ? 
How can I detect user cancellation with using this library for both apple and google play store ? 
I do not even know if its related with this getAvailablePurchase method. 
Thanks.

**Comment by VitaliKaniushok** [comment]
+ same

**Comment by nathsimpson** [comment]
I'd like to work out if this would also happen in production, rather than just TestFlight.
We're currently using this function as the app loads, rather than on a button press.

**Comment by mifi** [comment]
Apple still advices us *not* to automatically call this function on app automatically or startup

> Don't automatically restore purchases, especially when your app is launched. Restoring purchases prompts for the user’s App Store credentials, which interrupts the flow of your app.

https://developer.apple.com/documentation/storekit/in-app_purchase/restoring_purchased_products#:~:text=Restore%20Completed%20Transactions,of%20your%20app's%20completed%20transactions.

The way I implemented it is to send the receipt to the backend when the user presses purchase or restore purchase. Then the backend can provide the app with the subscription status in the future.

**Comment by yemd** [comment]
> 

Long time I know, but what if it's never needed and your subscriptions information are stored in backend or retrieved at startup, why such a button would need to exist? Is it still true and definitive?
