### ISSUE TITLE
Android: isAcknowledgedAndroid should be available for subscriptions

### ISSUE THREAD

**Issue by zs-doron** [dooboolab/react-native-iap#748]
### Version of react-native-iap
3.4.12
### Version of react-native
0.60
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
isAcknowledgedAndroid should be set for both SKU types to allow for cleanly checking whether a purchase should be acknowledged.
### Actual behavior
isAcknowledgedAndroid is only set for SKU types "IAP", not for subscriptions. However, subscriptions need to be acknowledged, too (see [Billing library documentation](https://developer.android.com/google/play/billing/billing_library_overview#acknowledge)). Currently, you have to check the purchase's transactionReceipt to see if the purchase has been acknowledged, or always acknowledge the purchase.

            if (type.equals(BillingClient.SkuType.INAPP)) {
              item.putBoolean("isAcknowledgedAndroid", purchase.isAcknowledged());
            } else if (type.equals(BillingClient.SkuType.SUBS)) {
              item.putBoolean("autoRenewingAndroid", purchase.isAutoRenewing());
            }

**Comment by hyochan** [comment]
Thanks for the issue! Fixed in `3.5.6`. Consider giving `PR` for the next time 😀

**Comment by zs-doron** [comment]
Thanks, I wanted to discuss it first before fixing it, next time I will add a PR. See PR #752 to fix the typings related to this issue.
