### ISSUE TITLE
purchaseUpdatedListener return twice transaction?

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [dooboolab/react-native-iap#753]
log listener
![Screen Shot 2019-10-03 at 5 21 52 PM](https://user-images.githubusercontent.com/33291479/66119419-d044be80-e602-11e9-8a65-a42b40f14989.png)

**Comment by nochkin** [comment]
You better provide the whole object as it may be different in other fields.

**Comment by mingxin-yang** [comment]
+1

**Comment by tarasvakulka** [comment]
I solved it, by refactor my code, I had two registered listener

**Comment by mingxin-yang** [comment]
I registered listener at the component, the component is a model, when I call the ***requestSubscription*** method, the listener will be called many times

**Comment by ssg-luke** [comment]
Not sure why this is closed. It definitely still occurs. I call the RNIap.purchaseUpdatedListener func only once on componentDidMount() (older app that uses class components) and I make sure to destroy the listener in componentWillUnmount(). After calling requestSubscription(), onPurchaseUpdated() is called twice on Android.

**Comment by heyoppa-admin** [comment]
this bug is still happening !
