### ISSUE TITLE
Auto linking is not working on 3.5.8

### ISSUE THREAD

**Issue by ospfranco** [dooboolab/react-native-iap#755]
### Version of react-native-iap
3.5.8

### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Autolinking is working
### Actual behavior
Dependency does not get autolinked
### Tested environment (Emulator? Real Device?)
emulator
### Steps to reproduce the behavior
I started a brand new project, added 'react-native-iap' dependency via yarn, tried to run android but it was not being autolinked, after fumbling around for a couple of hours and even trying manual linking, I downgraded to 3.5.2 because it was mentioned in a different issue, rebuild android and it then got autolinked correctly

**Comment by zabkwak** [comment]
I had similar issue and for some reason there was no java code in the 3.5.8. So after manual linking I got error about packageName in the react-native-iap manifest file. 

I installed 3.5.7 and updated the module file from this commit https://github.com/dooboolab/react-native-iap/commit/a165e54c9226c2cec8e9093f3a162577b4eb38d0#diff-b21dbc2d57e14bf6f1b5f81c3a3c3ba5.

It seems to be working now..

**Comment by hyochan** [comment]
To help maintenance with your issue, I hope you also try the `example` project which works fine with the latest release.

**Comment by ospfranco** [comment]
The example project seems to be manually linked, so it doesn't show this issue

**Comment by hyochan** [comment]
Fixed in `3.5.9`. Thanks for the issue!
