### ISSUE TITLE
RNIap.getSubscriptions(SUBSCRIPTIONS) throws "E_IAP_NOT_AVAILABLE" error

### ISSUE THREAD

**Issue by s-aleinik** [dooboolab/react-native-iap#757]
Version of react-native-iap
3.5.8

Version of react-native
0.60.5

Platforms you faced the error (IOS or Android or both?)
Android

Expected behavior
RNIap.getSubscriptions(SUBSCRIPTIONS) will return the list of subscriptions.

Actual behavior
throws an error: "TypeError: Cannot read property 'getItemsByType' of undefined", after that there is one more error as Unhandled Promise Rejection with text: "E_IAP_NOT_AVAILABLE"

Tested environment (Emulator? Real Device?)
Real device. Android version 6.0.1

Steps to reproduce the behavior
Try to use RNIap.getSubscriptions(SUBSCRIPTIONS) method.

**Comment by hyochan** [comment]
Did you call `initConnection` before `getSubscriptions`? Also that will be deprecated so it'd be better to use `requestSubscriptions`.

**Comment by Bang9** [comment]
> Did you call `initConnection` before `getSubscriptions`? Also that will be deprecated so it'd be better to use `requestSubscriptions`.

@hyochan not included `android/src folder` on 3.5.8

**Comment by hyochan** [comment]
@Bang9 Wow thanks for this. I'll fix this now.

**Comment by hyochan** [comment]
@s-aleinik Fxied in `3.5.9`.

**Comment by s-aleinik** [comment]
@hyochan @Bang9  thank you for the fast response :)

**Comment by s-aleinik** [comment]
@hyochan here is new error: `[TypeError: null is not an object (evaluating 'RNIapModule.getItemsByType')]```

**Comment by s-aleinik** [comment]
latest working version is 3.5.6 for me
