### ISSUE TITLE
getting error when trying to buy a subscription

### ISSUE THREAD

**Issue by anuragdwivedi29** [dooboolab/react-native-iap#758]
### Version of react-native-iap
3.5.8

### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
android
### Expected behavior
should open the dialog to make the payment and display the subscribed item
### Actual behavior
got an error the item you were attempting to purchase could not be found
### Tested environment (Emulator? Real Device?)
real device also
### Steps to reproduce the behavior
 made subscriptions in the google play  console
able to fetch the subscriptions 
but when trying to buy the subscription getting error
PS uploaded the app to google play console in closed track for testing

**Comment by hyochan** [comment]
Did you provide the `testing access`?

**Comment by anuragdwivedi29** [comment]
yes i provided it but there was a problem with my google account due to which it was not working ,i resolved it and now it is working .
I just wanted to ask you one more question how can we get hold of the the google play action sheet

**Comment by hyochan** [comment]
@anuragdwivedi29 Sounds great that it is working! Could you explain more about your second question? I don't quite get it.

**Comment by ydv0121** [comment]
hello.
also getting same issue while purchase

![Screenshot_20191015-095358](https://user-images.githubusercontent.com/37238045/66800202-fa1ab100-ef31-11e9-83b4-2287bb9f8e1e.png)

is there any solution??

**Comment by hyochan** [comment]
@ydv0121 This is very common question related to the setup for your `IAP` on play store. Please search for related issues. I'll close this for now!
