### ISSUE TITLE
Undefined Variable Promise In RNIapModule.java

### ISSUE THREAD

**Issue by PosSoolutions** [dooboolab/react-native-iap#760]
### Version of react-native-iap
 "react-native-iap": "^4.0.0-rc9",
### Version of react-native
60
### Platforms you faced the error (IOS or Android or both?)
Android 
### Expected behavior
Promise is defined and library compiles 
### Actual behavior
error: cannot find symbol variable promise
### Tested environment (Emulator? Real Device?)
Real device and Emulator
### Steps to reproduce the behavior
npm install "react-native-iap": "^4.0.0-rc9", build project

![image](https://user-images.githubusercontent.com/31963164/66272605-c7c9cf00-e820-11e9-80ef-0718b6a4e69b.png)

app fails to build

I comment out line 506 and I can then get the app to build.

**Comment by hyochan** [comment]
Same here as #761.
