### ISSUE TITLE
Purchase Module expecting more variables

### ISSUE THREAD

**Issue by PosSoolutions** [dooboolab/react-native-iap#761]
### Version of react-native-iap
"react-native-iap": "^4.0.0-rc9",
### Version of react-native
60
### Platforms you faced the error (IOS or Android or both?)
Android and Ios
### Expected behavior
Purchase module opens and confirms purchase
### Actual behavior
app crashes expecting more variables
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior
npm install "react-native-iap": "^4.0.0-rc9", build project

refer to issue
[https://github.com/dooboolab/react-native-iap/issues/760](url)
and take steps.

While invoking the function 

![image](https://user-images.githubusercontent.com/31963164/66272777-cef1dc80-e822-11e9-803e-17ebf6731981.png)

It throws this error 

![image](https://user-images.githubusercontent.com/31963164/66272799-fb0d5d80-e822-11e9-9e6f-8c54a8f2f051.png)

Please give me steps to pass the bug.

**Comment by hyochan** [comment]
`rc9` ~ `rc11` aren't recommended to use since there were some bugs during deploying. Please try other versions.
