### ISSUE TITLE
finishTransaction is missing from npm package

### ISSUE THREAD

**Issue by doomsower** [dooboolab/react-native-iap#762]
### Version of react-native-iap

4.0.0-rc10

### Version of react-native
0.61.2

### Platforms you faced the error (IOS or Android or both?)

both

### Expected behavior

`finishTransaction` should work

### Actual behavior

`finishTransaction` is in index.ts here on next branch, but for some reason it's missing from index.js and index.d.ts of installed package.

**Comment by hyochan** [comment]
Hey sorry! I think I’ve forgot the build. I’ll release to rc11 soon.

**Comment by hyochan** [comment]
Released `rc11`. Please try this.

**Comment by hyochan** [comment]
Actually I'll publish to `4.0.0` soon.

**Comment by hyochan** [comment]
Please try `4.0.1`.
