### ISSUE TITLE
purchaseUpdatedListener assignment crashes the app

### ISSUE THREAD

**Issue by andrespi** [dooboolab/react-native-iap#763]
### Version of react-native-iap
3.5.9

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
start listening to updates

### Actual behavior
crashes the app

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
add update listener as the example shows
but as soon as purchaseUpdateSubscription is assigned the app craches

![Screenshot_20191007-014525](https://user-images.githubusercontent.com/3899732/66286079-27b68900-e8a6-11e9-8d17-3d1e5eff8ddc.png)

**Comment by hyochan** [comment]
Please try `4.0.1`.
