### ISSUE TITLE
Task :react-native-iap:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by mertbuldur** [dooboolab/react-native-iap#765]
I have some error help me 
` Task :react-native-iap:compileReleaseJavaWithJavac FAILED
/Users/mertbuldur/Desktop/YAZILIM/React Native/ChatApp/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:506: error: cannot find symbol
      DoobooUtils.getInstance().rejectPromiseWithBillingError(promise, billingResult.getResponseCode());
                                                              ^
  symbol:   variable promise
  location: class RNIapModule
Note: /Users/mertbuldur/Desktop/YAZILIM/React Native/ChatApp/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java uses or overrides a deprecated API.
`

**Comment by hyochan** [comment]
Please try `4.0.1`.
