### ISSUE TITLE
3.5.9 throws error on start

### ISSUE THREAD

**Issue by ospfranco** [dooboolab/react-native-iap#766]
### Version of react-native-iap
3.5.9
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
Android
### Actual behavior
Crash on app start
### Tested environment (Emulator? Real Device?)
emulator
### Steps to reproduce the behavior
Updated to 3.5.9, on application start I'm getting the following error:

<img width="589" alt="Screenshot 2019-10-07 at 12 40 49" src="https://user-images.githubusercontent.com/1634213/66305494-b3a8cf00-e8ff-11e9-82ad-b67a222768eb.png">

**Comment by hyochan** [comment]
Please try on real device since `iap` won't do anything in `emulator`
