### ISSUE TITLE
4.0.0 won't compile

### ISSUE THREAD

**Issue by ospfranco** [dooboolab/react-native-iap#767]
### Version of react-native-iap
4.0.0
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
android
### Expected behavior
App compiles
### Actual behavior
App is throwing compilation error
### Tested environment (Emulator? Real Device?)
emulator, but fails on compilation step
### Steps to reproduce the behavior
Just added updated the dependency to 4.0.0, tried to run the app on emulator, android compilation fails:

<img width="1228" alt="Screenshot 2019-10-07 at 12 42 42" src="https://user-images.githubusercontent.com/1634213/66305613-ff5b7880-e8ff-11e9-9d26-e674f34d7201.png">

**Comment by hyochan** [comment]
Related #764

**Comment by hyochan** [comment]
Please try `4.0.1`.
