### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by PosSoolutions** [dooboolab/react-native-iap#769]
### Version of react-native-iap
 "react-native-iap": "^4.0.1",
### Version of react-native
60
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Android studios project at least builds
### Actual behavior
Crash on compile
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Install library sync gradle build app → Crash

![image](https://user-images.githubusercontent.com/31963164/66318983-2d759400-e8d1-11e9-9ca3-04208f95207a.png)

![image](https://user-images.githubusercontent.com/31963164/66319091-585fe800-e8d1-11e9-90df-031d67caa1b0.png)

![image](https://user-images.githubusercontent.com/31963164/66319116-64e44080-e8d1-11e9-9126-059127d42cf3.png)

**Comment by PosSoolutions** [comment]
Line 113 has a problem with the promise

![image](https://user-images.githubusercontent.com/31963164/66321059-d1ad0a00-e8d4-11e9-9fa1-c7eeffc592bb.png)

**Comment by hyochan** [comment]
Could you try `4.0.2` and come back?

**Comment by PosSoolutions** [comment]
4.0.2 seems like its going to work I am going to publish app now and see if it works in a live environment. Locally it is running fine. Thanks!

**Comment by PosSoolutions** [comment]
Quick Question:

![Screenshot_20191007-090945](https://user-images.githubusercontent.com/31963164/66328950-73872380-e8e2-11e9-9fd0-63d8fc530b45.png)

wIll this resolve itself once app is published?

If not what do i need to do before I initiate a purchase?

**Comment by meanking** [comment]
I got same error
![Screenshot_20191011-072309_DazzledDate](https://user-images.githubusercontent.com/49337840/66617221-6ded4e80-ebfe-11e9-90b9-c4cad968ef60.jpg)

**Comment by meanking** [comment]
When I load the page with react-native-iap. 

At first I got this error


![Screenshot_20191011-064505_DazzledDate](https://user-images.githubusercontent.com/49337840/66662609-569c7880-ec73-11e9-93a8-1f6f34e7628d.jpg)


How can I fix it?

**Comment by PosSoolutions** [comment]
Upgrade your library to the latest version 4.0.3 maybe higher  by now → is working for me.. In your componentDidMount or before you click buy initiate items

Like so
const itemSkus = Platform.select({
    ios: [
  "propducts_sku"
    ],
    android: [
     "propducts_sku"
    ]
  });
RNIap.getProducts(itemSkus).then((result) =>
                console.log('IAPInitialize', result)
            );

everything should be fine after that.
