### ISSUE TITLE
Android getItems returns empty array

### ISSUE THREAD

**Issue by ilyakar** [dooboolab/react-native-iap#77]
### Version of react-native-iap
0.2.17

### Expected behaviour
To return the array populated with four in-app purchases with are active on Google Play (my app is published in alpha release)

### Actual behaviour
returns: `[]`

### Steps to reproduce the behaviour

This is a snippet from my code:
```
let platformProducts = {
  ios: products,
  android: products
}

export function getInAppPurchases(){
  return (dispatch, getState) => {
    if(Platform.OS == 'ios'){
      getItems(dispatch)
    }
    else if(Platform.OS == 'android'){
      RNIap.prepareAndroid().then(() => {
        console.log('prepared, continue')
        getItems(dispatch)
      }).catch((error) => {
        console.log('Prepare error:', error)
      })
    }
  }
  async function getItems(dispatch){
    try {
      console.log('start getItems:', platformProducts)
      const items = await RNIap.getItems(platformProducts)
      console.log('got items:', items)
      dispatch({ type: 'GOT_PRODUCTS', products: items })
    }
    catch(error) {
      console.log('Some error:', error)
    }
  }
}
```

Here's the log output:
![screen shot 2018-03-26 at 18 34 52](https://user-images.githubusercontent.com/1760709/37919659-cda180da-3124-11e8-9d0c-70dea05a188d.png)

Here are the in-app purchases on Google Play:
![screen shot 2018-03-26 at 18 38 41](https://user-images.githubusercontent.com/1760709/37919707-fdff8740-3124-11e8-9f39-a8bc50c3f591.png)

**Comment by dooboolab** [comment]
@ilyakar Hi. This is really strange. Have you tested in ios platform too? Also could you check with `'android.test.purchased` with this if you are receiving anything?

**Comment by ilyakar** [comment]
False alarm. Thank you for getting back though. It seems I needed to wait a few more hours to see the in-app purchases from Google Play (recently published app).
