### ISSUE TITLE
java.lang.IndexOutOfBoundsException ArrayList.java:437

### ISSUE THREAD

**Issue by mifi** [dooboolab/react-native-iap#770]
### Version of react-native-iap
3.5.9

### Version of react-native
0.61.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
No error

### Actual behavior

In bugsnag this error got reported
```
java.lang.IndexOutOfBoundsException

ArrayList.java:437 java.util.ArrayList.get	
RNIapModule.java:517 com.dooboolab.RNIap.RNIapModule.onPurchasesUpdated	
RNIapModule.java:544 com.dooboolab.RNIap.RNIapModule$11.run	
RNIapModule.java:103 com.dooboolab.RNIap.RNIapModule$2.onBillingSetupFinished	
BillingClientImpl.java:1521 com.android.billingclient.api.BillingClientImpl$BillingServiceConnection$1.run	
Handler.java:907 android.os.Handler.handleCallback	
Handler.java:105 android.os.Handler.dispatchMessage	
Looper.java:216 android.os.Looper.loop	
ActivityThread.java:7593 android.app.ActivityThread.main	
Method.java:-2 java.lang.reflect.Method.invoke	
RuntimeInit.java:524 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run	
ZygoteInit.java:987 com.android.internal.os.ZygoteInit.main
```

### Tested environment (Emulator? Real Device?)
Real device (Huawei P Smart)

### Steps to reproduce the behavior
Have not managed to do reproduce yet

Looks like it's coming from here:

https://github.com/dooboolab/react-native-iap/blob/1ab8be027af680f21d69a692f34d4d7bf15f958e/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L517

Maybe need to add a check if purchases is not empty along with `purchases != null` check and reject if it is empty?

**Comment by mifi** [comment]
I'm now able to reproduce it. It happens when app is started, but only some times. Other times it succeeds, so it's 50/50. Even if I comment out all calls to RNIap it crashes

**Comment by hyochan** [comment]
@mifi Thank you for the issue. Can you try our recent version which is `4.0.3`? I've bumped up the version however, this isn't breaking updates. I've had removed `deprecated` methods and organize a code base. If I remember correctly, I've also fixed code on `onBillingSetupFinished` which resolve wrong `promises`. I hope you can test if updating can fix your problem.

**Comment by mifi** [comment]
Sorry for the horribly slow reploy. I was never able to reproduce the problem so I cannot test if your fix is working. But I'm glad you looked into this.
