### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by doomsower** [dooboolab/react-native-iap#771]
### Version of react-native-iap
4.0.2
### Version of react-native
0.61.2
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
purchase should work
### Actual behavior
I'm getting android crash with this error:
```
Cannot convert argument of type class com.android.billingclient.api.Purchase
```

This is the cause:

```java
DoobooUtils.getInstance().resolvePromisesForKey(PROMISE_BUY_ITEM, purchases.get(0));
```

react promise should be resolved with `WritableMap` and not with `Purchase`.

Btw, I noticed two very similar pieces of code, when Purchase is converted into WritableMap, [here](https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L298-L308) and [here](https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L512-L522). They're different all but in a couple of fields. Maybe this can be extracted into utility function?

**Comment by kabucey** [comment]
FWIW I'm getting this same error but on React Native version 0.60.6.

**Comment by hyochan** [comment]
Can you please try `4.0.3`? I've just fixed the code as @doomsower has pointed out. Please feel free to reopen when it still cause a problem.
