### ISSUE TITLE
Crash After Purchase

### ISSUE THREAD

**Issue by PosSoolutions** [dooboolab/react-native-iap#779]
### Version of react-native-iap
"react-native-iap": "^4.0.2",

### Version of react-native
60

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
App makes purchase successfully and returns to executing code

### Actual behavior
App makes successful purchase and crashes. Everytime I navigate back to the view or call 
 RNIap.getProducts(itemSkus).then((result) =>
  );
The app crashes again

### Tested environment (Emulator? Real Device?)
Live testing in both stores

### Steps to reproduce the behavior

Download library install publish app for testing make purchase.

Initialization code

import React from 'react'
import RNIap, {
    purchaseErrorListener,
    purchaseUpdatedListener,
} from 'react-native-iap';
import {Platform} from 'react-native'

const itemSkus = Platform.select({
    ios: [
        "baron58_features",
    ],
    android: [
        "baron58_features",
    ]
  });

class IAPmodule extends React.Component {
    purchaseUpdateSubscription = null
    purchaseErrorSubscription = null

    componentDidMount() {
        try {
          // It looks like the code is failing around here
            RNIap.getProducts(itemSkus).then((result) =>
                console.log('IAPInitialize', result)
            );
        } catch (err) {
            console.warn(err.code, err.message);
        }

        this.props.purchaseProduct(async (productId) => {
            await this.requestPurchase(productId)
        })
        ------→ It looks like the code is failing around here
        this.purchaseUpdateSubscription = purchaseUpdatedListener((purchase) => {
            console.log('purchaseUpdatedListener', purchase);
            const receipt = purchase.transactionReceipt;
            if (receipt) {
                yourAPI.deliverOrDownloadFancyInAppPurchase(purchase.transactionReceipt)
                    .then((deliveryResult) => {
                        if (isSuccess(deliveryResult)) {
                            if (Platform.OS === 'ios') {
                                RNIap.finishTransactionIOS(purchase.transactionId);
                            } else if (Platform.OS === 'android') {
                                // If consumable (can be purchased again)
                                RNIap.consumePurchaseAndroid(purchase.purchaseToken);
                                // If not consumable
                                RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken);
                            }
                        } else {
                            // Retry / conclude the purchase is fraudulent, etc...
                        }
                    });
            }
        });

        this.purchaseErrorSubscription = purchaseErrorListener((error) => {
            console.warn('purchaseErrorListener', error);
        });
    }

    componentWillUnmount() {
        if (this.purchaseUpdateSubscription) {
            this.purchaseUpdateSubscription.remove();
            this.purchaseUpdateSubscription = null;
        }
        if (this.purchaseErrorSubscription) {
            this.purchaseErrorSubscription.remove();
            this.purchaseErrorSubscription = null;
        }
    }
    requestPurchase = async (sku) => {

        //await RNIap.prepare();
        await RNIap.requestPurchase(sku, false);
    }

    requestSubscription = async (sku) => {
        try {
            await RNIap.requestSubscription(sku);
        } catch (err) {
            console.warn(err.code, err.message);
        }
    }

    render() {
        return null
    }
}
export default IAPmodule

**Comment by hyochan** [comment]
Please try 4.0.3.
It wasnt stable until 4.0.2
