### ISSUE TITLE
finishTransaction ambiguous argument name

### ISSUE THREAD

**Issue by doomsower** [dooboolab/react-native-iap#783]
### Version of react-native-iap
4.0.4
### Version of react-native
0.61.2

### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior

Ts signature of `finishTransaction` is:

```ts
export const finishTransaction = (
  transactionId: string,
  isConsumable?: string,
  developerPayloadAndroid?: string,
): Promise<string | void> => {
```

It's not documented (yet?), so expected the following code to work on Android:

```ts
const safeAcknowledgePurchase = async (purchase: ProductPurchase) => {
  try {
    await finishTransaction(purchase.transactionId!);
    return {
      error: undefined,
      acknowledged: true,
    };
  } catch (e) {
```

### Actual behavior

Instead it failed with E_DEVELOPER_ERROR
I had to use Platform selector:

```ts
async (purchase: ProductPurchase) => {
  try {
    await finishTransaction(
      Platform.OS === 'ios' ? purchase.transactionId! : purchase.purchaseToken!,
    );
    return {
      error: undefined,
      acknowledged: true,
    };
  } catch (e) {
```

Maybe `finishTransaction` should receive Purchase as a first argument?

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/66532249-a97a1100-eb49-11e9-8746-119acbe0d1d2.png)

I think the clear description inside our code would be enough. I think it'd be better to update the doc & code comments.

Thank you for the issue.
