### ISSUE TITLE
RNIapModule.buyItemByType got 6 arguments, expected 8 when trying to request subscription

### ISSUE THREAD

**Issue by TheTimeWalker** [dooboolab/react-native-iap#784]
### Version of react-native-iap
4.0.4

### Version of react-native
0.61.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior 
Google Pay pops up to buy subscription

### Actual behavior
Receiving error `RNIapModule.buyItemByType got 6 arguments, expected 8`

### Tested environment (Emulator? Real Device?)
Real Device: Samsung Note 10+ 5G

### Steps to reproduce the behavior
Use the simple README snippet
```javascript
  requestSubscription = async (sku: string) => {
    try {
      await RNIap.requestSubscription(sku);
    } catch (err) {
      console.warn(err.code, err.message);
    }
  }

  render() {
    ...
      onPress={() => this.requestPurchase(product.productId)}
    ...
  }
```
and try to buy an subscription with the productId passed over. The module fails to initiate subscription as it seems to demand more arguments than it's used for requestSubscription.

**Comment by hyochan** [comment]
I'm not sure why this is occurring in your side since `IapExample` code doesn't throw that error when tested (even in our recent version `4.0.4`). Have you tried to remove `node_modules` and try again (suspecting any caches so correct code haven't)?

**Comment by TheTimeWalker** [comment]
You're right, seems like my installation was cranky yesterday evening. It was from clean state so that what made it strange for me. Now today after removing node_modules and trying again it seems to work out again.
