### ISSUE TITLE
RNIapModule.buyItemByType got 8 arguments, expected 6 when trying to requestPurchase

### ISSUE THREAD

**Issue by jaapHou** [dooboolab/react-native-iap#785]
### Version of react-native-iap
3.4.12
### Version of react-native
0.6.0.3
### Platforms you faced the error (IOS or Android or both?)
android
### Steps to reproduce the behavior
  requestPurchase = async (sku) => {
    await this.getAvailablePurchases();
    var that = this;
    try {
      await RNIap.requestPurchase(sku, false)
    } catch (err) {
      console.warn(err.code, err.message);
    }
  };

**Comment by AliRehman7141** [comment]
I am facing the same issue on 

React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 150.48 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      npm: 6.10.3 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

"react-native-iap": "4.4.0",
