### ISSUE TITLE
Failure in requestPurchase

### ISSUE THREAD

**Issue by meanking** [dooboolab/react-native-iap#788]
#769  I got error.
I am using react-native-iap 4.0.4

And I updated according to modified version of it.
By the way I got this error.
How can I fix this problem?

![Screenshot_20191011-072309_DazzledDate](https://user-images.githubusercontent.com/49337840/66617404-30d58c00-ebff-11e9-9bab-d7dbd848d2a6.jpg)

**Comment by hyochan** [comment]
Have you seen #784?

**Comment by meanking** [comment]
Yes, 

By the way, I got this error when I load the page with react-native-iap.


![Screenshot_20191011-064505_DazzledDate](https://user-images.githubusercontent.com/49337840/66662728-91061580-ec73-11e9-93c7-26ec3c13cc4a.jpg)


How can I fix this?

**Comment by hyochan** [comment]
Please try `4.0.5` and come back.

**Comment by meanking** [comment]
What should I do for using 4.0.6?

Should I change some code including above code?

**Comment by meanking** [comment]
Would you explain for me why the "Index: 0, Size: 0" error occur?

**Comment by hyochan** [comment]
Could you try out the example project?

**Comment by meanking** [comment]
Yes, I tried to do it same as your sample code.

**Comment by meanking** [comment]
What is the cause of this error?

**Comment by meanking** [comment]
Now I got this error

how can I fix this?


`message: Google is indicating that we have some issue connecting to payment
code: E_DEVELOPER_ERROR
debugMessage: responseCode 5`

![Screenshot_20191011-121124_DazzledDate](https://user-images.githubusercontent.com/49337840/66679051-7e9dd300-ec97-11e9-862f-59e445ca8b42.jpg)

**Comment by hyochan** [comment]
Is there anyone facing the same issue?

**Comment by AlifElahi** [comment]
I am facing the same problem, have you found any solve for this @meanking

**Comment by diegogurpegui** [comment]
Still happening to me with 4.3.3 (and RN 0.59.10)
The Java file seems to be expecting 6 params (plus the result promise), and the JS code seems to be sending 6. So I don't know where the "expected 8" comes from.
I tried cleaning every compile/build file I found.

Any luck anyone?

**Comment by diegogurpegui** [comment]
Fixed it!

I tried to reset the cache to Metro Bundler with no luck.

But after that I changed the JS code of the library (file node_modules\react-native-iap\index.js) to add a log. That changed made some cache (which I'm unaware of) to refresh. And after that everything worked fine.
Needless to say I removed the log line and everything kept working.

Hope it helps.
