### ISSUE TITLE
Can we get product id from ios receipt

### ISSUE THREAD

**Issue by sidpauhal** [dooboolab/react-native-iap#790]
Can we get product id from ios receipt 
I have to check which plan is user susbcribed to?

I have plans like this
'silver_membership', 'gold_membership', 'platinum_membership'

something like this
RNIap.validateReceiptIos (receipt_data)
current_active_plan = 'free';
const renewalHistory = receipt.latest_receipt_info
const expiration = renewalHistory[renewalHistory.length - 1].expires_date_ms
if(expiration > Date.now()){
current_active_plan = receipt.product_id
}

return current_active_plan;

_Originally posted by @sidpauhal in https://github.com/dooboolab/react-native-iap/issues/727#issuecomment-539493454_

**Comment by hyochan** [comment]
I think you need collect `product id` with the `receipt` so that you can compare them if you need to. If there is any other updates please feel free to update me in this thread.

**Comment by sidpauhal** [comment]
@hyochan latest_receipt_info contains array of receipts I think each receipt contains product_id along with expires_date_ms and other transaction related information

so code can be like this for now (not tested)

```
RNIap.validateReceiptIos (receipt_data)
current_active_plan = 'free';
const renewalHistory = receipt.latest_receipt_info
const expiration = renewalHistory[renewalHistory.length - 1].expires_date_ms
if(expiration > Date.now()){
const current_plan = renewalHistory[renewalHistory.length - 1].product_id
current_active_plan = current_plan
}
return current_active_plan
```

I dont have any latest receipt data for now to post here 
If you have any please share so we can be sure that it contains product_id

**Comment by hyochan** [comment]
Thanks for sharing. I'll close this for now since you've resolved it.
