### ISSUE TITLE
discounted custom amount when request purchase

### ISSUE THREAD

**Issue by affanhashone** [dooboolab/react-native-iap#792]
### Steps to reproduce the behavior

Hi,

Is there any way to add Discounted offer price when requestPurchase

**Comment by hyochan** [comment]
Have you tried `requestPurchaseWithOfferIOS`?

**Comment by affanhashone** [comment]
@hyochan i want for android

**Comment by hyochan** [comment]
@affanhashone Could you kindly give the idea or any related implementation doc that might be helpful? Then we can support you if it is a feature request.

**Comment by affanhashone** [comment]
@hyochan i tried searching for documentation, but could not found.

i mean to say coupon code system, when user apply some coupon code, they may get some discounts like 20% off on purchase, for that reason i need to pass custom calculated value.

i think this is not possible from apple pay or google pay

**Comment by hyochan** [comment]
@affanhashone Thanks for the research. `feature request` is recommended when it is sure that it works in `native`.
