### ISSUE TITLE
I am not getting bottom sheet when i am implementing in app purchase for subscriptions in ios

### ISSUE THREAD

**Issue by anuragdwivedi29** [dooboolab/react-native-iap#794]
### Version of react-native-iap
4.0.7
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
![Webp net-resizeimage (9)](https://user-images.githubusercontent.com/53597970/66820647-bbe7b680-ef5e-11e9-9343-ca9750f15630.png)

### Actual behavior
![Webp net-resizeimage (8)](https://user-images.githubusercontent.com/53597970/66820666-c73ae200-ef5e-11e9-97ea-e1e7ed62d9ba.png)

### Tested environment (Emulator? Real Device?)
Real device and  app is distributed to testers via testflight

**Comment by lklepner** [comment]
Hi @anuragdwivedi29. The bottom sheet only appears in apple's production env. In the sandbox env a series of alerts, like the one you've shown, are used instead. I believe this is an iOS quirk, not a react-native-iap quirk..

**Comment by anuragdwivedi29** [comment]
Ok so before releasing it to prod how can we actually test its behaviour.Also i have one more question if after successful payment of subscription i want to navigate a user to a different screen then how it can be achieved cause i have tried but i am not able to redirect the user after successful subscription.Any pointers will be highly appreciated.

**Comment by hyochan** [comment]
@anuragdwivedi29 You should try the live purchase to actually test bottom sheet since Apple doesn't support this. Also your second question doesn't look like it is related to `IAP`. May be `react-navigation`. Closing this issue for now.

**Comment by HappyCodingLover** [comment]
@anuragdwivedi29 
How did you edit this price section in the payment sheet?
![image](https://user-images.githubusercontent.com/71419620/119507660-9a3ceb00-bda1-11eb-9ae6-e1cb8fa59a7b.png)
