### ISSUE TITLE
finishTransaction should take purchase instead of transaction ID

### ISSUE THREAD

**Issue by mars-lan** [dooboolab/react-native-iap#797]
The newly added `finishTransaction` takes "transaction ID" as its first argument (https://github.com/dooboolab/react-native-iap/blob/master/index.ts#L401), whereas in reality, the user should pass in "purchase token" in the case Android non-consumable (https://github.com/dooboolab/react-native-iap/blob/master/index.ts#L418). I'd recommend refactoring the method to take purchase object instead to make it truly platform-neutral.

**Comment by hyochan** [comment]
Thanks! Sounds very reasonable. We'll refactor@
