### ISSUE TITLE
Auto-Renewable Subscriptions need to Finish the Purchase ? 

### ISSUE THREAD

**Issue by matamicen** [dooboolab/react-native-iap#799]
Hi, everybody and first of all thanks for this brilliant library :)  @hyochan 

Is it not so clear to me, Do I have to finish the purchase with acknowledgePurchaseAndroid() and finishTransactionIOS() in an auto Auto-Renewable Subscription ? 

The doc of this library says for Consumables and Non-consumables and don't say anything about Subcriptions. 

Thanks!

Matt.

**Comment by hyochan** [comment]
You need this now in every `purchases`. Subscription should be `acknowledged`!
