### ISSUE TITLE
Google Play In-app Billing API version is less than 3 - E_SERVICE_ERROR

### ISSUE THREAD

**Issue by TiagoGouvea** [dooboolab/react-native-iap#800]
### Version of react-native-iap
4.0.7

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Connection init should start the connection, to get products, and after that be able to purchase.

### Actual behavior
On `initConnection` catch I got: 
```
error.code: E_SERVICE_ERROR
error.debugMessage: Google Play In-app Billing API version is less than 3
error.message: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.
```

It's happend on production app with this device:
```
Galaxy S8 (dreamlte)
Samsung
armeabi-v7a, armeabi, arm64-v8a
SO Android 9
```

I was wondering how could it be related to **"Google Play In-app Billing API version is less than 3"**, since the native link was done by the RNIAP.

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
The user want to purchase, but on `initConnection` it fails.

**Comment by TiagoGouvea** [comment]
I chated with the user, and checked that he has the Google Play Store updated, with version 17.1.16, and the [Google Play Services](https://play.google.com/store/apps/details?id=com.google.android.gms) has no update on his phone.

Another relevant question is [that](https://stackoverflow.com/questions/21091353/what-are-the-possibilities-to-get-this-error-code-3-in-inapp-purchase/21275043).

What could be?

**Comment by hannojg** [comment]
Hey! Google announced that they will quit support for the AIDL/Billing Library Version 1 and 2 and that one needs to upgrade to Version 3 until the beginning of December. Not sure if this is related, as I also don't know which version of the AIDL/Billing Library this library uses internally.

**Comment by hyochan** [comment]
> Another relevant question is [that](https://stackoverflow.com/questions/21091353/what-are-the-possibilities-to-get-this-error-code-3-in-inapp-purchase/21275043).
> 
> I talked with the user, and checked that he has the Google Play Store updated, with `version 17.1.16`, and the [Google Play Services](https://play.google.com/store/apps/details?id=com.google.android.gms) has no update on his phone, with version `19.4.20` from October 1st, 2019.
> 
> The user has two accounts on his phone, both identified as Brazilian accounts (country available to buy the products).
> 
> What could be?

A user could be using an old `android` phone. Could you check the user's Android version?

**Comment by TiagoGouvea** [comment]
```
Galaxy S8 (dreamlte)
SO Android 9
```

**Comment by jimbol** [comment]
Any more info on this?

**Comment by hyochan** [comment]
Have you guys re-uploaded `apk` in playstore after upgrading `react-native-iap`?

**Comment by jimbol** [comment]
Thanks for responding! I'm running `react-native-iap@4.3.0` on production right now. Has there been a change that fixes this issue?

**Comment by hyochan** [comment]
version 3 api `Requires Google Play client version 3.9.16 or higher.`. I've gone through the [doc](https://stuff.mit.edu/afs/sipb/project/android/docs/google/play/billing/versions.html), and currently, don't have idea to make this downward compatible.

**Comment by jimbol** [comment]
Ok, I will add a message to the user to upgrade their Google Play app.

**Comment by TiagoGouvea** [comment]
The error still happening sometimes with some users.. but I decided to ignore it and display "Connection error, try again later".
