### ISSUE TITLE
purchaseUpdateListener is getting called multiple times in IOS

### ISSUE THREAD

**Issue by anuragdwivedi29** [dooboolab/react-native-iap#801]
### Version of react-native-iap
4.0.4
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
should be called when requestSubscription(subscriptionID) is called
### Actual behavior
is getting called when the app loads for the very first time.Also when a subscription is bought it is getting called multiple times
### Tested environment (Emulator? Real Device?)
Real Device (sandbox environment)

**Comment by anuragdwivedi29** [comment]
are there any pointers for the above mentioned issue?

**Comment by Bang9** [comment]
maybe it would help you `clearTransactionIOS()`, but i'm not sure :p
[reference](https://developer.apple.com/library/archive/technotes/tn2387/_index.html)

**Comment by anuragdwivedi29** [comment]
ok i will try that but i am  testing the in app purchase in sandbox environment .So when i am launching the app and before making any purchase it is calling the clearTransactionIOS() and is making the purchase which should not be the behaviour. Ideally only when the user makes the purchase the it should ask for the payment and make the purchase.So therefore i am not able to understand  as to what i am doing wrong here.
Any pointers would be highly appreciated.Thanks

**Comment by franj0** [comment]
@anuragdwivedi29 if you did not finish transaction on app relaunch update listener will try automatically execute code inside.

Also do not forgot this.yourListener.remove() on unmount...

Maybe something of this you need. gl

**Comment by mingxin-yang** [comment]
+1

**Comment by nicolaswilliman** [comment]
This is happeening to me too. The difference is that I'm using the 3.2.3 version of RNIap.
I'm also removing the listener when unmounting, but the purchaseUpdateListener is getting called multiple times with differents transaction ids. Just happens in iOS.

Any ideas?

**Comment by Bang9** [comment]
@nicolaswilliman @anuragdwivedi29 @mingxin-yang @franj0 
I found the reason, refer this link(https://help.apple.com/app-store-connect/#/dev7e89e149d)

one auto-renewable subscription makes 6 transactions
If you turn the app back on 20 minutes **_after subscribe a 1week_**
**_6 transactions that occurred every 3 minutes_** will enter the purchaseUpdatedListener at once

**Comment by alexpchin** [comment]
@Bang9 Do you have a solution for this? I understand that the `purchaseUpdatedListener` is being called multiple times

**Comment by Bang9** [comment]
> @Bang9 Do you have a solution for this? I understand that the `purchaseUpdatedListener` is being called multiple times

If you don't want to getting six times of renew transactions after purchased auto-renewable subscription

1. purchase auto-renewable subscription
2. logout previous sandbox account
3. create a new sandbox account
4. login with new sandbox account

I don't think it is efficiently :P

**Comment by jonnyberanek** [comment]
Perhaps a way to handle resubscribe events would be to reference ` originalTransactionDateIOS` which is present in the given ProductPurchase? Is this field undefined on the initial purchase of a subscription?

**Comment by karltaylor** [comment]
> maybe `clearTransactionIOS()` would help you , but i'm not sure :p
> [reference](https://developer.apple.com/library/archive/technotes/tn2387/_index.html)

`clearTransactionIOS` method is deprecated.

If believe it might be worth checking to see if a 'purchase button' has been pressed, and then processing with your normal purchase flow. Otherwise you will have to do some extra logic to handle these resubscribe events.

**Comment by denkeni** [comment]
I would suggest *not* deprecating `clearTransactionIOS`. 

I have experience of implementing iOS IAP subscription that, unexpected numbers of transactions coming. I understand there are condensed intervals for sandbox testing environment, just as @Bang9 mentioned above, but it was not the case. It turned out that I implemented a mechanism similar to `clearTransactionIOS` to ignore any retrying transactions on app launch. So the user would need to manually restore purchase if any error happened, but it's a more clear and expected behavior.

**Comment by bsbilal** [comment]
any updates?

**Comment by Abdulmateenchitrali** [comment]
+1

**Comment by erenkulaksiz** [comment]
Having the same issue on sandbox env. I'm not going to do something for this but calling my API like 10 times in a single go is not the way. Also server validates all receipts and thinks like i received 10 subscriptions.

**Comment by rashonwill** [comment]
Same issue in sandbox, sending multiple receipts to the backend on a consumable purchase and all getting validated making multiple database entries.

**Comment by JuGit-pk** [comment]
### Whats the conclusion ? I need its solution, i am still facing this issue on IOS,
see my implementation,

**1.  INIT IAP**

```
  const initializeIAP = async () => {
    try {
      const isConnected = await initConnection();
      console.log({isConnected});
      setConnection(isConnected);
      if (Platform.OS === 'android') {
        await flushFailedPurchasesCachedAsPendingAndroid();
      } else if (Platform.OS === 'ios') {
        console.log('CLEARTING IOS clearTransactionIOS');
        await clearTransactionIOS();
      }
    } catch (error) {
      console.error('Error initializing IAP: ', error);
    }
  };
  useEffect(() => {
    console.log('💀');
    initializeIAP();

    return () => {
      endConnection();
    };
```

**2. Method to Request Subscription**
```
  const handleBuySubscription = async () => {
    if (selectedPackage) {
      try {
        // ios
        let subsParams: RequestSubscription = {
          sku: selectedPackage.productId,
          andDangerouslyFinishTransactionAutomaticallyIOS: false,
        };
        if (Platform.OS === 'android' && currentSubscriptionOffer) {
          const sku = currentSubscription?.productId as string;
          const offerToken = currentSubscriptionOffer.offerToken;

          subsParams = {
            sku,
            ...(offerToken && {subscriptionOffers: [{sku, offerToken}]}),
          };
        }

        requestSubscription(subsParams);
      } catch (err: any) {
        console.warn(err.code, err.message);
      }
    }
  };
```

**3. Purchase Listener**


```
 useEffect(() => {
    // Initialize purchase listeners
    let purchaseUpdateSubscription = purchaseUpdatedListener(async purchase => {
      const receipt = purchase.transactionReceipt;
      if (receipt) {
        try {
          const payload = {
            receipt,
            os_type: Platform.OS,
          };
          debouncedAcknowledgementReceiptAPI(payload, {
            onSuccess: async () => {
              qc.invalidateQueries({queryKey: ['billing-details']});
              if (isBillingModalVisible) {
                setIsBillingModalVisible(false);
              }
              setIsModalVisible(true);
              await finishTransaction({purchase, isConsumable: false});
              await getPurchaseHistory();
            },
          });
        } catch (error) {
          console.error('Error during purchase handling:', error);
        }
      }
    });

    let purchaseErrorSubscription = purchaseErrorListener(error => {
      console.error('Purchase error:', error);
    });

    // Cleanup listeners on unmount
    return () => {
      lastTransactionRecipe.current = null;
      purchaseUpdateSubscription.remove();
      purchaseUpdateSubscription = null as any;
      purchaseErrorSubscription.remove();
      purchaseErrorSubscription = null as any;
    };
  }, [
    debouncedAcknowledgementReceiptAPI,
    getPurchaseHistory,
    qc,
    isBillingModalVisible,
    setIsBillingModalVisible,
    profileData?.email,
  ]);
```
