### ISSUE TITLE
Changing renewable subscription in iOS In-app purchase triggers “Cannot connect to iTunes Store” error

### ISSUE THREAD

**Issue by grubstarstar** [dooboolab/react-native-iap#803]
I have multiple renewable subscriptions set up for my App in App Store Connect.

![Screen Shot 2019-10-23 at 11 36 05 am](https://user-images.githubusercontent.com/1732170/67348813-d559b580-f591-11e9-95ea-64706d83e52c.png)

There are a handful of renewable subscriptions which are all part of the same subscription group, plus one which is a non-renewable subscription.

I am using a sandbox user account as created under "Users and Access" > "Sandbox" > "Testers" logged in as a sandbox user on the iPhone. I am logged in as that user on the iPhone under "iTunes & App Stores" > "SANDBOX ACCOUNT".

I can successfully fetch the subscriptions using 'RNIap.getSubscriptions()' and display them in the UI. I can then successfully trigger a purchase of a subscription using `RNIap.requestSubscription(productId, false)` after which my registered `RNIap.purchaseUpdatedListener` handler correctly fires, and I finish the transaction using `RNIap.finishTransactionIOS(purchase.transactionId)`. So far, so good.

The problem arises when I try to make subsequent changes to the renewable subscription, by following the same process with one of the other subscriptions. I get a pop-up asking whether I want to confirm the modification to the new subscription, as expected, followed by "You're all set, Your purchase was successful". But I when this happens it actually calls the `RNIap.purchaseErrorListener` event handler, rather than the `RNIap.purchaseUpdatedListener` as expected.

The error message I get from the handler is:
```
{
	responseCode: "0",
	code: "E_UNKNOWN",
	debugMessage: "Cannot connect to iTunes Store",
	message: "Cannot connect to iTunes Store"
}
```
Which originates from the `StoreKit` api itself when `transaction.transactionState` is equal to `SKPaymentTransactionStateFailed`.

If I then ettempt to buy thnon-renewable subscription (1 Week in the above example) the purchase is successful, triggering the `RNIap.purchaseUpdatedListener` as expected. But whenever I try to change the subscription to another renewable subscription again the `RNIap.purchaseErrorListener` handler is triggered.

**Comment by adelrodriguez** [comment]
I'm running into the same issues. I think it might be related to #525?

**Comment by grubstarstar** [comment]
> I'm running into the same issues. I think it might be related to #525?

Yeah that looks like it's the same issue. Thanks for that. Gives me something more to go on.

**Comment by jvandenaardweg** [comment]
Can you verify your subscription group looks something like this? With the numbers next to it? As that shows the correct order to properly allow upgrading/downgrading. You need to re-arrange (drag and drop) this yourself

![Screenshot 2019-10-24 at 11 50 53](https://user-images.githubusercontent.com/5155373/67474398-aeb08300-f654-11e9-9a75-e723dcb4c987.png)

**Comment by grubstarstar** [comment]
> Can you verify your subscription group looks something like this? With the numbers next to it? As that shows the correct order to properly allow upgrading/downgrading. You need to re-arrange (drag and drop) this yourself. So, for example, an upgrade is from 3 to 2. A downgrade is from 2 to 3.
> 
> ![Screenshot 2019-10-24 at 11 50 53](https://user-images.githubusercontent.com/5155373/67474398-aeb08300-f654-11e9-9a75-e723dcb4c987.png)

Ah okay. I will have a look at that and see. Thanks

**Comment by grubstarstar** [comment]
> Can you verify your subscription group looks something like this? With the numbers next to it? As that shows the correct order to properly allow upgrading/downgrading. You need to re-arrange (drag and drop) this yourself. So, for example, an upgrade is from 3 to 2. A downgrade is from 2 to 3.
> 
> ![Screenshot 2019-10-24 at 11 50 53](https://user-images.githubusercontent.com/5155373/67474398-aeb08300-f654-11e9-9a75-e723dcb4c987.png)

I didn't even know that page existed to be honest. I read this article which the page links to https://help.apple.com/app-store-connect/#/dev75708c031. It says that if they are all the same level you should be able to "crossgrade" between each one. Mine are all level 1, which matches the example they give under the section **Identical services at different durations** in that article. This is what it looks like now. I will try it out again when I get hold of a iOS test device.

![Screen Shot 2019-11-04 at 11 12 14 am](https://user-images.githubusercontent.com/1732170/68094419-500cc400-fef4-11e9-9f2d-7781e7959d87.png)

**Comment by DavidGOrtega** [comment]
I have the same error. Subscriptions with same level different duration

**Comment by mustafaaksoy** [comment]
I have the same error.

**Comment by grubstarstar** [comment]
I haven't solved the issue yet. I will probably come back to it in the next month or so.

**Comment by grubstarstar** [comment]
Still active. I will get round to this soon(ish)
