### ISSUE TITLE
How can I handle a successful purchase or error through the requestSubscription method?

### ISSUE THREAD

**Issue by Jack220591** [dooboolab/react-native-iap#804]
### Version of react-native-iap
4.0.7
### Version of react-native
0.59
### Platforms you faced the error (IOS or Android or both?)
ios
### Expected behavior
Handle a successfull purchase and if successfull go to premium content.
### Actual behavior
I use purchaseUpdateListener for this. But that send receipt before user do requestPurchase.
### Tested environment (Emulator? Real Device?)
real device

**Comment by hyochan** [comment]
Did you read the [post](https://medium.com/dooboolab/react-native-iap-v3-1259e0b0c017)? Currently , I feel I am not correctly understanding you.

**Comment by Jack220591** [comment]
Do I understand correctly that the purchaseUpdateListener should handle the event of a successful purchase? 
My problem is that he reacts before the purchase is made. And all the logic in it, which is designed to process a successful purchase, is triggered before the purchase is launched.

**Comment by hyochan** [comment]
You should `finishTransanctionIos` after `requestSubscription` when the purchase has been made.  If your application finishes during the purchase being made by some disasters, your application could receive pending transactions and you may also finish those transactions when your app starts.
