### ISSUE TITLE
getPurchaseHistory and getAvailablePurchases consume purchase without calling finishTransactionIOS

### ISSUE THREAD

**Issue by defualt** [dooboolab/react-native-iap#808]
### Version of react-native-iap
3.4.0
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
IOS ( `__DEV__` mode only so far) 
### Expected behavior
`getPurchaseHistory` and `getAvailablePurchases` do not affect purchases, they just report
### Actual behavior
Calling `getPurchaseHistory` and `getAvailablePurchases` will consume previously unconsumed consumable purchases
### Tested environment (Emulator? Real Device?)
Real device __DEV__ mode
### Steps to reproduce the behavior

- Make an in app purchase of a consumable.
- Do not call `finishTransactionIOS`.
- Call `getPurchaseHistory` or `getAvailablePurchases`, log response, see that the response includes the purchase.
- Call `getPurchaseHistory` or `getAvailablePurchases` again, log response, see that the response NO LONGER includes the purchase.

**Comment by hyochan** [comment]
@defualt Would you like to try it removing [these lines](https://github.com/dooboolab/react-native-iap/blob/e33d06f6ac44f6bf80de7a32d7ace2863f4e4cfe/ios/RNIapIos.m#L424-L432)?

**Comment by defualt** [comment]
Removing those lines, calling `getAvailablePurchases` and `getPurchaseHistory` results in empty array.  However the purchases do not get consumed because when I reset the app, `purchaseUpdatedListener` logs the recent unconsumed purchase.

**Comment by defualt** [comment]
deleting just this line has the desired effect but I don't know if this breaks something else.
https://github.com/dooboolab/react-native-iap/blob/e33d06f6ac44f6bf80de7a32d7ace2863f4e4cfe/ios/RNIapIos.m#L429

**Comment by roberto-buratti** [comment]
I'm experiencing the same issue. 
In fact there are a lot of points in the code where [...finishTransaction:..] is called even if the app *never* calls .finishTransaction().

IMHO this is a serious bug that has to be fixed as soon as possible.

What if my customer makes a purchase but do not consumes it immediately (...there are zillions of reason why this may happen in a real application..)? Today, the net result is that any pending transaction is immediately finished even the purchase has not been consumed, which may imply (and actually does) money loss for the customer.

Please fix it ASAP.

**Comment by roberto-buratti** [comment]
Moreover... this is a signal of another bug: even if the transaction has been finished without request, getPurchaseHistory() should return it but it doesn't...

So, we have no way to work around the problem.

**Comment by roberto-buratti** [comment]
any news about this?

**Comment by roberto-buratti** [comment]
Stale? not at all, we are still waiting for a fix.

**Comment by mcchrish** [comment]
Yes, this is a real issue I'm experiencing as well. Seems to be a critical bug if so.

**Comment by jplandry908** [comment]
I agree, this is a significant issue. Once you verify the purchase once it disappears and cannot verify it again. This is very problematic for lifetime purchases.

**Comment by jplandry908** [comment]
> @defualt Would you like to try removing [these lines](https://github.com/dooboolab/react-native-iap/blob/e33d06f6ac44f6bf80de7a32d7ace2863f4e4cfe/ios/RNIapIos.m#L424-L432)?

FYI - Removing these lines seemed to fix the issue.

**Comment by roberto-buratti** [comment]
Please fix it!!...

**Comment by hyochan** [comment]
> > @defualt Would you like to try removing [these lines](https://github.com/dooboolab/react-native-iap/blob/e33d06f6ac44f6bf80de7a32d7ace2863f4e4cfe/ios/RNIapIos.m#L424-L432)?
> 
> FYI - Removing these lines seemed to fix the issue.

@emilioicai Could you kindly tell the effect of removing [these lines](https://github.com/dooboolab/react-native-iap/blob/e33d06f6ac44f6bf80de7a32d7ace2863f4e4cfe/ios/RNIapIos.m#L424-L432)?

I'll try to remove this and deploy new version if there isn't any answer.

**Comment by jplandry908** [comment]
FYI - Removing the lines worked for me a while back, and I am using it in production. I just need to remember to make the change again for any future upgrades unless it is updated in the next release.

**Comment by hyochan** [comment]
> FYI - Removing the lines worked for me a while back, and I am using it in production. I just need to remember to make the change again for any future upgrades unless it is updated in the next release.

Thanks for your confirm. I'll try to manage to remove the lines in next release when I do not get the answer from @emilioicai who've added the code.

**Comment by jplandry908** [comment]
Any update on this?

**Comment by jplandry908** [comment]
This is still an open issue. I still have a patch commenting out this line.

**Comment by jplandry908** [comment]
This line is still in the production version of the code.
`[[SKPaymentQueue defaultQueue] finishTransaction:transaction];`

I still have it manually removed in my production applications. Without it, I was not able to receive the purchase history on the device after the purchase was made.

**Comment by lukebrandonfarrell** [comment]
Still an issue +1

**Comment by lukebrandonfarrell** [comment]
We should be able to get purchase history without consuming

**Comment by storrdev** [comment]
@hyochan it looks like @emilioicai has only made a few contributions to github in the past few months, and most of them are to react-native-lottie. Is there an assistance anyone else can provide to help get this patched?

**Comment by andresesfm** [comment]
`finishTransactionIOS` has been removed since version `7.2.0` and replaced by a unified `finishTransaction` that works on both platforms. Please try on version `7.3.0` or newer and let us know. Closing this ticket
