### ISSUE TITLE
Dependency to itself?

### ISSUE THREAD

**Issue by StasD** [dooboolab/react-native-iap#811]
Why do you have a dependency to itself in package.json?
I.e. I have version 4.0.7 installed, and, because its package.json contains `"react-native-iap": "^4.0.0-rc13"` in `dependencies` section, the result is that it has its own node-modules folder, with version 4.0.1 of the same library in there.
Does not make any sense to me...

**Comment by hyochan** [comment]
Thanks for update. Should be resolved!

**Comment by hyochan** [comment]
Resolved in `4.0.8`.
