### ISSUE TITLE
There is currently no way to know if an Android purchase has been refunded

### ISSUE THREAD

**Issue by maximedupre** [dooboolab/react-native-iap#817]
### Version of react-native-iap
`4.0.7`

### Version of react-native
`0.60.5`

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior

The `purchaseState` can only be set to "PENDING" (2), "PURCHASED" (1) or "UNSPECIFIED_STATE" (0), which means that there is currently no way to know if a purchase has been refunded. A refunded purchase stays at "PURCHASED (1)". Cancelled purchases (invalid payment, or forgot to acknowledge) are simply not returned when calling `getAvailablePurchases`, which is fair.

The only way to be able to know if a purchase has been refunded, is if you implement a [`getVoidedPurchases` API](https://developers.google.com/android-publisher/api-ref/purchases/voidedpurchases/list). 

Please refer to: https://stackoverflow.com/questions/46543008/how-to-detect-canceled-or-refunded-order-for-google-in-app-billing

### Actual behavior

Refunded purchases simply have a `purchaseState` of 1.

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
1 . Make an IAP
2. Refund the IAP
3. IAP will stay with a `purchaseState` of 1, making it impossible to distinguish between a non-refunded purchase and a refunded purchase

**Comment by Stafox** [comment]
It is not a responsibility of that lib. If you want to track refunded you need a backend server which able to detect that refund was made.

Calling provided API (voided purchases) on the client side is not safe. To use that API you should put your service account to application.
Having that service account you able to do a refund by yourself.

**Comment by maximedupre** [comment]
@Stafox 

Ok thanks. I mostly understand your reply, but what do you mean when you say:

> To use that API you should put your service account to application.

Furthermore, I don't quite understand:

> Having that service account you able to do a refund by yourself.

I am already able to do a refund by myself, I just log into the Google Play console and click on the "Refund" button next to the transaction.

Cheers!

**Comment by Stafox** [comment]
I meant that anyone able to disassembly your apk , extract service account and do a lot using it: refund, validation, read financial data and so on.

**Comment by Stafox** [comment]
Also, read the description of following API
```
startTime long 
The time, in milliseconds since the Epoch, of the oldest voided purchase that you want to see in the response. The value of this parameter cannot be older than 30 days and is ignored if a pagination token is set. Default value is current time minus 30 days. Note: This filter is applied on the time at which the record is seen as voided by our systems and not the actual voided time returned in the response.
```

So only recent (30 days) refunds are returned. It means that you are not able to properly define is there was a refund.

**Comment by maximedupre** [comment]
Understood. Thanks for the help!
