### ISSUE TITLE
Api request for subscription on every renewal

### ISSUE THREAD

**Issue by affanhashone** [dooboolab/react-native-iap#818]
### Steps to reproduce the behavior

Hi, I want to know, how subscription renewal will work every month?.on every renewal, I want to call a api where I need to update user data

**Comment by Bang9** [comment]
You can handle renewal information with server to server notification
[Android](https://developer.android.com/google/play/billing/realtime_developer_notifications)
[iOS](https://developer.apple.com/documentation/storekit/in-app_purchase/enabling_server-to-server_notifications)
