### ISSUE TITLE
getSubscriptions returns E_UNKNOWN if Internet connection is unavailable

### ISSUE THREAD

**Issue by acostalima** [dooboolab/react-native-iap#819]
### Version of react-native-iap

3.4.11

### Version of react-native

0.59.1

### Platforms you faced the error (IOS or Android or both?)

iOS so far

### Expected behavior

`RNIap.getSubscriptions()` should return `E_NETWORK_ERROR` 

### Actual behavior

`RNIap.getSubscriptions()` returns `E_UNKNOWN`.

### Tested environment (Emulator? Real Device?)

Real device: iPhone SE, iOS 13.1.3

### Steps to reproduce the behavior

Simply call `RNIap.getSubscriptions()` connected to a WiFi network without access to the Internet.

**Comment by hyochan** [comment]
Are you saying `iap` should be possible without the internet?

**Comment by acostalima** [comment]
> Are you saying `iap` should be possible without the internet?

No. What I'm saying is that when there is no access to the Internet, I'd would expect to receive `E_NETWORK_ERROR` or something more indicative of the situation.  Makes sense?

**Comment by acostalima** [comment]
In Android, I'm receiving `E_SERVICE_ERROR`. We should probably document in the README which errors are returned in Android and iOS and in what situations. It still remains unclear to me what's the purpose of some error codes even after digging through the Android and iOS source. 😞
