### ISSUE TITLE
Pod install fails due to empty description in package.json

### ISSUE THREAD

**Issue by neilco** [dooboolab/react-native-iap#82]
### Version of react-native-iap

- react-native-iap 0.3.0-beta3
- cocoapods 1.4.0

### Expected behavior

`pod install` completes without any errors

### Actual behavior

`pod install` fails because `description` in `package.json` is empty.

```shell
Fetching podspec for `RNIap` from `../node_modules/react-native-iap`
[!] The `RNIap` pod failed to validate due to 1 error:
    - WARN  | source: The version should be included in the Git tag.
    - ERROR | description: The description is empty.
```

### Steps to reprodue the behavior

- `npm install react-native-iap --save`
- `react-native link react-native-iap`
- `cd ios`
- `pod install`

**Comment by JJMoon** [comment]
We don't use pod in react-native-iap. I followed your steps, but it doesn't reproduce the errors.
Can you share the podfile?

**Comment by neilco** [comment]
It seems that `react-native link react-native-iap` adds this to my Podfile:

```ruby
  pod 'RNIap', :path => '../node_modules/react-native-iap'
```

I guess the README needs to be updated to let others know they should remove this line. I can submit a pull request if you like.

**Comment by dooboolab** [comment]
@neilco Yes it would be helpful if you give us PR. Please give us PR to `dev` branch following the contributing guidelines.
