### ISSUE TITLE
Promise returned by requestSubscription hangs if user cancels login/payment

### ISSUE THREAD

**Issue by acostalima** [dooboolab/react-native-iap#820]
### Version of react-native-iap

4.0.3

### Version of react-native

0.59.1

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

When the user cancels, the promise should reject.

### Actual behavior

When the user cancels, the promise neither resolves or rejects so it never settles.

### Tested environment (Emulator? Real Device?)

Real device: iPhone SE, iOS 13.1.3

### Steps to reproduce the behavior

Call `RNIap.requestSubscription()` and then press cancel when you are requested to either login or proceed with payment.

**Comment by Bang9** [comment]
`requestSubscription` is not return Promise.. You can get the result with event-listener
use `purchaseUpdatedListener` and `purchaseErrorListener`
here is the [example](https://github.com/dooboolab/react-native-iap/blob/b3ab597d9e15cbdf6ef194b57091d6b21ca8f8f1/IapExample/App.js#L122)

**Comment by acostalima** [comment]
I'm using v3.4.11 right now and the Promise doesn't hang but I get it what you're saying. However, `purchaseErrorListener` does not seem to provide any context about the purchase that failed, but only a `PurchaseError`.

**Comment by hyochan** [comment]
> I'm using v3.4.11 right now and the Promise doesn't hang but I get it what you're saying. However, `purchaseErrorListener` does not seem to provide any context about the purchase that failed, but only a `PurchaseError`.

Could you share big of your code to find out the problem easier?

**Comment by Bang9** [comment]
> I'm using v3.4.11 right now and the Promise doesn't hang but I get it what you're saying. However, `purchaseErrorListener` does not seem to provide any context about the purchase that failed, but only a `PurchaseError`.

PurchaseError provide reason, you can find reason with `error.code`

**Comment by acostalima** [comment]
> > I'm using v3.4.11 right now and the Promise doesn't hang but I get it what you're saying. However, `purchaseErrorListener` does not seem to provide any context about the purchase that failed, but only a `PurchaseError`.
> 
> PurchaseError provide reason, you can find reason with `error.code`

Yeah, I know. 😄 
However, is it safe to assume when `purchaseErrorListener` is called it refers to the latest purchase made? If it's not, shouldn't we have a second argument to receive the purchase in question, i.e., `purchaseErrorListener(error, purchase)` or similar? 🤔

**Comment by azharuddinkhan8898** [comment]
Same issue here, when I initiate payment and cancel it without purchase and then when I again initiate payment and complete purchase from another component, 1st component and this component's `purchaseUpdatedListener` gets called.

How to remove purchase listeners when component unmount?

**Comment by acostalima** [comment]
> Same issue here, when I initiate payment and cancel it without purchase and then when I again initiate payment and complete purchase from another component, 1st component and this component's `purchaseUpdatedListener` gets called.
> 
> How to remove purchase listeners when component unmount?

Call `.remove()` on the object returned by each listener.
