### ISSUE TITLE
requestSubscription: buyItemByType got 6 arguments, expected 8

### ISSUE THREAD

**Issue by voxspox** [dooboolab/react-native-iap#822]
### Version of react-native-iap
4.0.7

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Actual behavior
requestSubscription -> red screen

buyItemByType got 6 arguments, expected 8

### Tested environment (Emulator? Real Device?)
device

**Comment by hyochan** [comment]
Looks like you've not correctly installed `react-native-iap`. Please try to delete all the caches and try again.

**Comment by voxspox** [comment]
I using `react-native-iap` in my project and it is live and working. Recently I upgraded from 3.4.13 to 4.0.7

After re-building to project

    cd android && ./gradlew clean
    node node_modules/react-native/local-cli/cli.js start --reset-cache
    react-native run-android

The problem still persists. Any further ideas?

**Comment by voxspox** [comment]
I just cleared everything again and it works now!!
