### ISSUE TITLE
Cannot connect to iTunes Store

### ISSUE THREAD

**Issue by Ilario17** [dooboolab/react-native-iap#823]
"react-native-iap": "^4.0.8"
"react-native": "0.61.2"

### Platforms you faced the error
iOS

### Actual behavior
I get successfully the list of products but when I do 
```
try {
    await RNIap.requestPurchase(sku, false);
} catch (err) {
    console.log(err.code)
}
```
the catch is called with 
```
code: 'E_UNKNOWN',
message: 'Cannot connect to iTunes store'
```

### Tested environment
Real device, iPhone XR with iOS 13.1.2

The alert on iPhone tells me:

> you are currently not authorized to make sandbox purchases

Am i missing something?
Thanks

**Comment by hyochan** [comment]
I think you should understand how to test `iap` in `ios`. Create `sandbox` user and follow the blog in the read me.
