### ISSUE TITLE
Purchase Auto-Renewing Subscription with Discount (Offer / Promo Code)

### ISSUE THREAD

**Issue by alexpchin** [dooboolab/react-native-iap#824]
### Version of react-native-iap
3.5.5 (Happy to upgrade though...)

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
iOS and Android

### Expected behavior
n/a

### Actual behavior
n/a

### Tested environment (Emulator? Real Device?)
n/a

### Steps to reproduce the behavior
n/a

Currently, it is unclear whether it is possible to apply a promo-code when making a purchase of an auto-renewable subscription.

**Scenario**

I have an app that has 3 auto-renewing subscriptions:

1. 3 months @ £19.99
2. 6 months @ £34.99
3. 12 months @ £49.99

I would like to be able to provide 3 promo-codes that can be applied when the user is making this purchase. 

1. "3-months-free" (Example name only)
2. "6-months-free" (Example name only)
3. "12-months-free"  (Example name only)

Personally, I find the terminology of Apple's IAPs are really confusing...

1. **In-App Purchase Promo Codes** - (Promo Codes can only be generated for approved versions.)
2. **Introductory Offer** - An introductory offer is a limited-time discounted price or free trial with a set duration and type (pay as you go, pay up front, free) for the initial period of a subscription. Introductory offers can be set up and managed in App Store Connect. To localize and display information to users within your app, you must implement the appropriate SKProduct APIs. (Customers will automatically be charged the full subscription price when the introductory offer is over unless they cancel their subscription, i.e. x months free then you get billed for the plan)
3. **Promotional Offer** - Apps with auto-renewable subscriptions can provide a discounted price for a specific duration for existing and previously subscribed customers on iOS, macOS, and tvOS. You can use subscription offers to help win back subscribers who have canceled their subscriptions or promote an upgrade to a higher-ranked subscription at a special price. Customers can accept the offer even if they've already completed an introductory offer. https://help.apple.com/app-store-connect/#/dev16dfca448 

I believe that option 2 is what I want to implement... However, it is unclear whether there are any methods for this in the `react-native-iap` library. 

I have found on [this issue](https://github.com/dooboolab/react-native-iap/issues/516) the code:

```js
const offer = {
  identifier: 'TESTOFFER', // from iTunes products discounts array
  keyIdentifier: 'MYK3Y1D' // from server,
  nonce: <nonce>, // from server
  signature: <base64-encoded-string>, // from server
  timestamp: 1560290457029 // from server
};

const uid = <applicationUsername-string>; // I've tried using both empty str and non-empty str values here. This is an optional string value for `applicationUsername` that can be an empty str as noted in the server signature docs: https://developer.apple.com/documentation/storekit/in-app_purchase/generating_a_signature_for_subscription_offers?language=objc

const response = await RNIap.buyProductWithOfferIOS(sku, uid, offer);
```

However, with v4 and v3 and seemingly no documentation in the Readme of `buyProductWithOfferIOS` it is hard to understand whether this is the correct method or how to make this cross-platform with Android?

After checking the [NPM trends for the various React Native Payment Libraries (that I know of)](https://www.npmtrends.com/react-native-billing-vs-react-native-iap-vs-react-native-payments-vs-react-native-in-app-utils-vs-react-native-payments), I am surprised that such a common use-case is not easier to implement?

Any advise, help, examples or tutorials would be very much appreciated.

**Comment by Stafox** [comment]
You have to know that for now there is no promotional offers for Android.

**Comment by hyochan** [comment]
Please guide us if there is any missing features and please share any reference to moving forward 🙏 .

**Comment by voxspox** [comment]
Google introduced promo codes for subscriptions in Mai 2019
https://developer.android.com/google/play/billing/billing_subscriptions#promo

**Comment by voxspox** [comment]
Does IAP [implement a promotion](https://developer.android.com/google/play/billing/billing_promo) ?

**Comment by nafplann** [comment]
I need this

**Comment by nafplann** [comment]
hey I just got mine working based on this tutorial https://www.revenuecat.com/blog/ios-subscription-offers. It needs a server/api to generate signature and nonce for the offer object.

**Comment by BogdanRad** [comment]
is there any solution for android?

**Comment by Stafox** [comment]
> is there any solution for android?

For android it should work from the box. Because the offers work on the billing module side - no special integration is needed on developer side.

The only thing it can be it is a handling purchases made outside the app ([link](https://developer.android.com/google/play/billing/integrate#ooap))
