### ISSUE TITLE
requestSubscription does not return

### ISSUE THREAD

**Issue by voxspox** [dooboolab/react-native-iap#825]
### Version of react-native-iap
4.0.7

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
both

### Actual behavior
I have a auto-renewing subscription. The Promise `requestSubscription` does not return. I used it as stated in the [docs](https://github.com/dooboolab/react-native-iap#purchase).

My code worked in a previous IAP version (3.4.13) already. So I'm wondering what has changed since then.

### Tested environment (Emulator? Real Device?)
devices

### Steps to reproduce the behavior
```
onPurchase = async sku => {
  try {
    console.log(`--> purchasing ${sku}: start`)
    await iap.requestSubscription(sku)
    console.log(`--> purchasing ${sku}: request done`)
    ...
    debug(`purchasing ${sku}: success`)
  } catch (error) {
     error stuff...
  }
}
```
After calling `onPurchase` I can see the `start` log message but I never get `request done`nor `failed`.

**Comment by hyochan** [comment]
Please read the readme. You should use `purchaseUpdateListener` and `purchaseErrorListener` to grab the response.

**Comment by voxspox** [comment]
Hi @hyochan . I have read the docs :) For me there are some points which could be improved:

In the table `requestSubscription` appears twice. The first is a void-function, the second (Android only) returns a Promise. Which one is valid? Is the first one for iOS only? Should I distinguish between Android and iOS when calling `requestSubscription`? 

In section [Purchase](https://github.com/dooboolab/react-native-iap#purchase) the example uses a Promise and awaits it in a try/catch block. I understand from your comment, that this is not the right way.

I've seen the `purchaseUpdateListener`. I use it, but only for purchase acknowledgement.

**Comment by kennym** [comment]
@hyochan it would be great if you could answer @voxspox, I'm also interested in an answer

**Comment by narrafy** [comment]
Same here. requestSubscription does not return. Any fixes?

**Comment by hyochan** [comment]
`requestSubscription` and `requestPurchase` both return a promise, but the purchases should most likely be handled by the `purchaseUpdatedListener`. The promises still exist for `debugging`.
