### ISSUE TITLE
if the purchase is not acknowledge, purchaseUpdatedListener will never been called again. (it just been called once) (Android Only)

### ISSUE THREAD

**Issue by matamicen** [dooboolab/react-native-iap#828]
Hi Guys,

This happens in Android on a Test Purchase.

The purchaseUpdatedListener is it called the **first time** when the purchase is done, i didn't acknowledge the purchase just to emulate a problem with my backend verification receipt. 

So next time I execute the app with the same user the purchaseUpdateListener is not called with the remaing not acknowledge purchase. It works on iOS but not in android.

This is becasue Android and doesn't work the same way as iOS ? or I am missing something?

Thanks @hyochan

**Comment by hyochan** [comment]
I also want to know the exact behavior when `purchase` is lost before `ack` in `android`. Please come back if you find any news. You can try to check this manually tough in `android` with `getAvailablePurchases`.

**Comment by matamicen** [comment]
@hyochan 
I have news, the listener works ok the first time the customer make a purchase. But if the customer make the purchase and I don't call the acknowledgePurchaseAndroid (for a backend problem or whatever) the APP will never call the listener again to process the  reamaining UNacknowledge purchaseToken. So What I did to solve that situation was this:

```
async componentDidMount() {
...
const purchases = await RNIap.getAvailablePurchases();
...
   // check if the purchaseToken is alreadyAcknowledged
   // it is important to avoid GOOGLE error when execute 
   //acknowledgePurchaseAndroid(purchaseToken) more than once on the same purchaseToken.
   // and this routine is called every time on DidMount() that is why I check this.

     if (!purchases[0].isAcknowledgedAndroid)
          {   
              ...
               const ackResult = await acknowledgePurchaseAndroid(purchaseToken);
             ...
           }

}
       
```
Remember, the RNIap.getAvailablePurchases() will always bring the subscription if it still active (not expired) the only way to know if it is already Acknowledged is to execute the code above.

What do you think ?

Thanks.
