### ISSUE TITLE
Weird errors sometimes occur when using getSubscriptions

### ISSUE THREAD

**Issue by nenjamin2405** [dooboolab/react-native-iap#830]
### Version of react-native-iap
^3.5.2
### Version of react-native
0.61.1
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
await RNIap.getSubscriptions(itemSkus) should return array of subs
### Actual behavior
sometimes return different kind of errors on Sentry:
1. Error: The service is disconnected (check your internet connection.) - on Sentry the `online` attribute is true
2. Error: An unknown or unexpected error has occured. Please try again later.
3. Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.

### Tested environment (Emulator? Real Device?)
Real Devices of users on Production
### Steps to reproduce the behavior
await RNIap.endConnectionAndroid() --> await RNIap.initConnection() --> setup purchaseUpdatedListener --> await RNIap.getSubscriptions(itemSkus) --> sometimes return those kinds of errors

**Comment by hyochan** [comment]
1. Error: The service is disconnected (check your internet connection.) - on Sentry the online attribute is true
   - This is internet connection error basically. `iap` need to be connected to network. You may try to 2. enhance your symtom by checking the `internet connection` beforehand.
2. Error: An unknown or unexpected error has occured. Please try again later.
   - I am not sure with this but may be similar problem as in 1.
Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.
   - This occurs when play store does not support `iap`.

**Comment by damialajogun** [comment]
> 1. Error: The service is disconnected (check your internet connection.) - on Sentry the online attribute is true
>    
>    * This is internet connection error basically. `iap` need to be connected to network. You may try to 2. enhance your symtom by checking the `internet connection` beforehand.
> 2. Error: An unknown or unexpected error has occured. Please try again later.
>    
>    * I am not sure with this but may be similar problem as in 1.
>      Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.
>    * This occurs when play store does not support `iap`.

Hi @hyochan, I'm having error 3 'billing is unavailable'. You said 'this occurs when play store does not support iap'. How can this be resolved? I'm running react-native-iap 4.4.7 and RN 0.60.6 and the package is auto-linked. I don't know how to resolve this error. Thanks

**Comment by bastolaxantos** [comment]
> > 1. Error: The service is disconnected (check your internet connection.) - on Sentry the online attribute is true
> >    
> >    * This is internet connection error basically. `iap` need to be connected to network. You may try to 2. enhance your symtom by checking the `internet connection` beforehand.
> > 2. Error: An unknown or unexpected error has occured. Please try again later.
> >    
> >    * I am not sure with this but may be similar problem as in 1.
> >      Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.
> >    * This occurs when play store does not support `iap`.
> 
> Hi @hyochan, I'm having error 3 'billing is unavailable'. You said 'this occurs when play store does not support iap'. How can this be resolved? I'm running react-native-iap 4.4.7 and RN 0.60.6 and the package is auto-linked. I don't know how to resolve this error. Thanks

Having same issue on some users phone.

**Comment by Beamanator** [comment]
I hit this error in my simulator:

> Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down.

The problem was because I wasn't logged into the Google Play Store (see [this issue](https://github.com/dooboolab/react-native-iap/issues/221))

**Comment by Ilario17** [comment]
I also have this problem and the user who is experiencing the bug informs me that he is logged into the Play Store.

this issue should **not** be closed @hyochan

**Comment by jpmazza** [comment]
I'm having the error `Billing is unavailable. This may be a problem with your device, or the Play Store may be down.`

I can see that error on Sentry.

I'm using "react-native-iap": "^5.1.1" and "react-native": "0.63.2"

We should reopen this issue @hyochan

**Comment by Great-hijack** [comment]
@hyochan 
I have same issue on Google Pixel.

```
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-iap": "^7.3.0"
```

**Comment by The0racle** [comment]
Seeing this issue as well. Are you guys finishing pending transactions?

**Comment by aarshad786** [comment]
I had the same problem, noticed later that payment settings were not updated on my account.. 
I was using hooks, also updated the code to call ```getProducts ``` only after connected.

**Comment by RenatoSerra22** [comment]
> I had the same problem, noticed later that payment settings were not updated on my account.. I was using hooks, also updated the code to call `getProducts ` only after connected.

On your developer account or on your user account?

**Comment by JMikeJ** [comment]
It's not happening every time but some time we are getting on Android.
`Error: An unknown or unexpected error has occured. Please try again later.`
