### ISSUE TITLE
NullPointerExceptioncom.dooboolab.RNIap.RNIapModule 

### ISSUE THREAD

**Issue by edo1493** [dooboolab/react-native-iap#831]
### Version of react-native-iap

4.0.3

### Version of react-native

0.61.2

### Platforms you faced the error (IOS or Android or both?)

Android

### Actual behavior

Sentry is reporting these errors in production on Android from time to time. They have started appearing straight after we have moved to react native 0.60+ and upgraded react-native-iap from 2.4.0 to 4.0.3.

### Tested environment (Emulator? Real Device?)

Real Device

This is the message from the error:

> Attempt to invoke virtual method 'void com.android.billingclient.api.BillingClient.acknowledgePurchase(com.android.billingclient.api.AcknowledgePurchaseParams, com.android.billingclient.api.AcknowledgePurchaseResponseListener)' on a null object reference

**Comment by hyochan** [comment]
Try to use `finishTransaction` released in `react-native-iap@4.1.0` #833 with safe null check.
