### ISSUE TITLE
Billing is unavailable. This may be a problem with your device, or the Play Store may be down.

### ISSUE THREAD

**Issue by edo1493** [dooboolab/react-native-iap#832]
### Version of react-native-iap

4.0.3

### Version of react-native

0.61.2

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

No errors thrown.

### Actual behavior

We are seeing lots of exceptions thrown on Android with the above message. This has started happening on the most recent release of the component.

### Tested environment (Emulator? Real Device?)

Real Device

### Steps to reproduce the behavior

Android-only, in production.

**Comment by hyochan** [comment]
Related to one of question in #830. Actually, we need minimal reproduction to resolve your problem.
