### ISSUE TITLE
Price/billing period values

### ISSUE THREAD

**Issue by kevinetore** [dooboolab/react-native-iap#838]
I have an In-app product subscription set up in the Google Play Console to bill on a monthly basis. As shown in the image below, it shows the price/billing period (22.99/5 min). I can't seem to find out where this billing period comes from and how I can change it. I'm using the `getSubscriptions` method and in the return response, I don't see anything about the billing period either.

**Version of react-native-iap**
`4.0.8`

**Version of react-native**
`0.61.2`

**Platforms error**
Android

**Expected behavior**
Price/Billing period to correctly show the subscription on a monthly basis.

**Actual behavior**
<img src="https://user-images.githubusercontent.com/10911831/68109019-d4a61500-fee9-11e9-83db-e53b89e58b43.png" alt="iap_5min" width="300">

**Tested environment (Emulator? Real Device?)**
Emulator

**Comment by hyochan** [comment]
It is expected when you are testing purchase in `test` environment.

**Comment by kevinetore** [comment]
@hyochan I see, thanks for the response. This issue can then be marked as closed.
