### ISSUE TITLE
[ANDROID] Subscription keep being here wherease it has been canceled

### ISSUE THREAD

**Issue by alanlanglois** [dooboolab/react-native-iap#84]
### Version of react-native-iap
0.3.0-beta3
### Expected behavior
if a subscription is canceled, it shouldn't appear anymore when calling: getAvailablePurchases()

### Actual behavior
When calling getAvailablePurchases I keep receiving a subscription I previously canceled (and not present in the google play store anymore

### Steps to reprodue the behabior
> Prepare android
> getProducts()
> getSubscription()
> checkSubscription( itembundleid )

> Buy a subscription.
> Go to the google play store > Subscriptions > (My app) Manage > Cancel > OK
> Close the app and restart
 

Receiving:
`[InApp] checkSubscription :: [{"autoRenewing":false,"purchaseToken":"tokeniiiiiiiddddddd","transactionReceipt":"receiptiiiiiiddddd","transactionDate":"1522356975806","transactionId":"transactioniiiiiiddddd","productId":"com.myapp.subscription"}]`

Note: it worked the first time but not the second one. 
I've tried to uninstall / install the app again and restart exp.

**Comment by alanlanglois** [comment]
I just tried to restart the phone, and it worked, the subscription disappear from the list received callinggetAvailablePurchases()

**Comment by dooboolab** [comment]
@alanlanglois This is quite ambiguous because it may depends on your playstore status. Please tell us again if this is keep happening..
