### ISSUE TITLE
requestSubscription promise return clarification

### ISSUE THREAD

**Issue by kennym** [dooboolab/react-native-iap#841]
### Version of react-native-iap
4.2.0
### Version of react-native
0.61.2
### Expected behavior
The README has two entries on `requestSubscription` - one with a return value of `Promise<void>` another with a return value of `Promise<string>`.

`requestSubscription: Promise<string>` does not exist within the `index.ts` definition. Should that be removed from the README?

**Comment by hyochan** [comment]
I've made this in to `void` since, I recommend users not to use `promises` in this case. However, I've just updated the `typings` in #844

**Comment by hyochan** [comment]
Closes via #890
