### ISSUE TITLE
E_UNKNOWN Cannot connect to iTunes Store on emulator

### ISSUE THREAD

**Issue by DavidGOrtega** [dooboolab/react-native-iap#842]
### Version of react-native-iap
4.1.0

### Version of react-native
0.60.5

### Platforms you faced the error (IOS or Android or both?)
ios

### Expected behavior
App gather my subscription plans (this is OK) then I can subscribe or restore purchases without even having to log in my apple account.

### Actual behavior
I login in my emulator having my profile perfectly setted. The subscriptions (three) are loaded perfectly, however when I try to subscribe or restore purchases the login asking for my apple id and password apperars, I full fill it and after that every operation fails. Real device connected to Xcode works, despite that I have this E_UNKNOWN error for other reasons.

### Tested environment (Emulator? Real Device?)
Emulator fails, real device works

**Comment by lklepner** [comment]
@DavidGOrtega I don't believe its possible to conduct iOS IAP purchases using the Simulator. I believe a real device is required.

**Comment by hyochan** [comment]
@lklepner He is right!

**Comment by DavidGOrtega** [comment]
@lklepner its possible and theoretically according to apple is mandatory to be passed in the emulator. Another question of course is the lack of support and the discrepancies between the sandbox and production

**Comment by wmonecke** [comment]
Whenever I try to 

` const availablePurchases = await RNIap.getAvailablePurchases();` or if I 
`await RNIap.requestSubscription(subscription.productId);`
I get prompted to sign in into iTunes Connect and no matter if its a sandbox user or a real Apple ID I get the error that I am not able to connect. HEEEELP.

**Comment by mxmzb** [comment]
I have the same issue. Btw this:

> @DavidGOrtega I don't believe its possible to conduct iOS IAP purchases using the simulator. I believe a real device is required.

is not true, at least it definitely used to work in emulator a few weeks ago.

**Comment by wouterds** [comment]
We have thousands of these errors in our error logger (different lib). Rarely I can reproduce this by accident but I have no clue how or what causes it exactly (yes I always test payments on a real device).

**Comment by DavideValdo** [comment]
I cannot connect, calling `getAvailablePurchase()` and loggin in with sandbox account results in `Cannot connect to iTunes Store` promise rejection, XCode console just logs `restoreCompletedTransactionsFailedWithError`
