### ISSUE TITLE
purchaseUpdatedListener no longer works

### ISSUE THREAD

**Issue by nateblog** [dooboolab/react-native-iap#843]
### Version of react-native-iap
"react-native-iap": "4.0.3"

### Version of react-native
"react-native": "0.59.10"

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
"purchaseUpdatedListener" should trigger after success purchase

### Actual behavior
called "requestPurchase" or "requestSubscription" then after processing the payment and got the message "You are all set", the "purchaseUpdatedListener" which used to work, now no longer work.

### Tested environment (Emulator? Real Device?)
Real Device (iphone 6)

### Steps to reproduce the behavior
Just trigger **requestPurchase** or **requestSubscription** and complete the payment process using sandbox.

**Comment by nateblog** [comment]
Damn it, I accidentally removed the listener, sorry my bad

**Comment by NMahendroo** [comment]
I am facing this issue in the Production build that is live on App Store.

The purchaseUpdatedListener getting triggered during the Sandbox environment but isn't working in Production.

I am facing this issue with iOS version.
