### ISSUE TITLE
Wrong type for pending_renewal_info in type/apple.d.ts

### ISSUE THREAD

**Issue by StasD** [dooboolab/react-native-iap#845]
It should be:
`pending_renewal_info?: object[];`
instead of
`pending_renewal_info?: string[];`
See https://developer.apple.com/documentation/appstorereceipts/responsebody

**Comment by hyochan** [comment]
@StasD Thanks for checking it out. Would you like to give us a `PR` for this?

**Comment by StasD** [comment]
Done!
