### ISSUE TITLE
validateReceiptAndroid: How to get accessToken?

### ISSUE THREAD

**Issue by ram-b** [dooboolab/react-native-iap#848]
I have read the README and linked articles but I have trouble figuring out how to get the accessToken to make a call to validateReceiptAndroid.

I have set up the backend as referenced in [this link](https://stackoverflow.com/questions/35127086/android-inapp-purchase-receipt-validation-google-play). It appears to be working correctly.

How do I now query the backend server for the accessToken? Do I use fetch? If so, from which url? Any code snippet will be helpful. Thanks in advance.

**Comment by hyochan** [comment]
I used to use [this one](https://github.com/voltrue2/in-app-purchase). Try to check this out.

**Comment by vishaldhanotiya** [comment]
I have faced the same issue. I write down the solution [here](https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880) please check this [link](https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880) it may help you to solve your problem 

https://github.com/dooboolab/react-native-iap/issues/1217#issuecomment-769629880
