### ISSUE TITLE
Intermittent hangs/crashes after requestPurchase on Android

### ISSUE THREAD

**Issue by kennym** [dooboolab/react-native-iap#853]
### Version of react-native-iap

4.2.0 and 3.3.9

### Version of react-native

0.61.2

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

No hangs/crashes. `requestSubscription/requestPurchase` returning

### Actual behavior

The app hangs intermittently after we call `requestSubscription` or `requestPurchase`. It both happens in dev and release mode, with test and/or real credit cards.

This is our application code, after which the hang occurs.

```
RNIap.requestSubscription('sampleproduct.app.id')
```

We've both tested this on react-native-iap 3.3.9 and 4.2.0 and are able to reproduce this.

### Tested environment (Emulator? Real Device?)

We can reproduce on a real device. Both tethered and/or from the Play Store.

### Steps to reproduce the behavior

1. Call `RNIap.requestSubscription`

2. Expect callback to resolve and return answer. Instead app hangs intermittently, and we get errors observable in the logs (see above)

After the purchase overlay closes the app already hangs and is unresponsive to touch. After a while we would see the prompt to force quit.

**Comment by kennym** [comment]
Another observation:

We use a singleton class to call the IAP methods, not a React Native `Component`, so our class does not de-allocate listeners. It doesn't cause any issues for us on iOS, would it cause any for Android?

**Comment by hyochan** [comment]
@kennym Yes. You should always deallocate listeners when you are done with whatever `iap` thing to prevent unexpected behavior. The `iap service` might be dead when it is `idle` for a while. You might have to try to `initialize` the service again after checking when it isn't alive.

**Comment by kennym** [comment]
@hyochan thanks for your answer. I have rephrased the original issue, and removed unrelated information from it.

Our app intermittently hangs after doing a checkout from a new session too, so it might not be the deallocation of listeners? Is there something I should try?

**Comment by hyochan** [comment]
@kennym Would you like to try our `example` project codebase on your app? Since I am not experiencing this in `example` app, I think the issue might be related to something different.
