### ISSUE TITLE
[Announcement] Letter to `react-native-iap` contributors and thoughts on future releases

### ISSUE THREAD

**Issue by hyochan** [dooboolab/react-native-iap#855]
Hi there~! Thank you all for using `react-native-iap`.

Today, I am here to tell you a bit about my story and the future of this module.
I was very close to working on this module since I was working on an app that heavily cares about `in-app-purchase` for more than an year. I was a `co-founder` and was invited to `Y-Combinator` final interview and we had a chance for two times of interview but couldn't get funded.

We've tried hard to find investors to keep our product moving but our budgets were very insufficient to get more developers and celebrities (yes [our app](https://apps.apple.com/kr/app/cooni/id1315512929) was about celebrities communicating with their fans on 1-1 basis) to grow in our platform.

Therefore, after 2 years of challenges,  we've decided to move onto the next career and all of us are not currently involved in our app (we quit in Jan 2019). Therefore, I've had a hard time maintaining this which wasn't related to my current work at all.

Today, I realized that the popular module should be maintained by the devs who seriously participate in the feature and the compatibility of new releases that should be affected by both natives. I am currently looking forward to integrating `iap` feature in my opensource toy app but would take considerable time to get there.

Before I can make a full-featured `iap` app, I want to give others a chance to develop our `example` project with money we've received in [open collective](https://opencollective.com/react-native-iap) during 2 years :sweat_smile: . I'll give a contributor our 2 years of expenses, $300 when the work is done.

The issue is posted in #856 

Thank you for reading.

by Hyo, the dooboolab

**Comment by kennym** [comment]
@hyochan thanks for sharing. Are there any new maintainers you have in mind already?

**Comment by hyochan** [comment]
@kennym Thank you for your response. Currently, no. I am trying to gather contributors for open work in #856 and we can think about this further. I'll also try to maintain this as much as possible.

**Comment by basequatro** [comment]
I can create a example for subscription with auto renew with BE receipt validation, that helps?

**Comment by hyochan** [comment]
@basequatro Thanks for the volunteer. Yes of course. I hope you can integrate that into our `example` app. I'll invite you to our `IAPExample` app (our example app) if you are interested!

**Comment by bradleyflood** [comment]
Great stuff @hyochan and thank you so much for your work 👍
