### ISSUE TITLE
Android price returned is actually the localizedPrice

### ISSUE THREAD

**Issue by ilyakar** [dooboolab/react-native-iap#86]
### Version of react-native-iap
0.2.17

### Expected behavior
On Android, product.price should be a number e.g., 23.99

### Actual behavior
Returns "CZK 23.99"

### Steps to reproduce the behavior
-

**Comment by dooboolab** [comment]
@ilyakar Hi! Thank you for the bug report. I've just fixed this one and published to npm version `0.3.0-beta5`. Could you try this one?

**Comment by ilyakar** [comment]
Okay. I'll give it a try, thanks. The reason I'm still sticking to 0.2.17 is because I had some problems on Android with the `.prepare()` method of 0.3.0-beta4. Apparently, it's expecting some attributes, unlike 0.2.17?

**Comment by dooboolab** [comment]
@ilyakar `prepare()` method is just same for `prepareAndroid()`. If it is not working as expected could you please share?

**Comment by dooboolab** [comment]
I think your primary issue is solved.
