### ISSUE TITLE
[WIP] A list of all of the pop-ups you may encounter and why

### ISSUE THREAD

**Issue by alexpchin** [dooboolab/react-native-iap#863]
At some point, I do intend to do (or contribute to) a PR with a clearer example and slightly reformatted README. However, in the meantime, I thought it might be helpful to put these here for anyone who is struggling to understand the expected flow.

The first thing to remember is that:

**The IAP UI is different in sandbox (development and TestFlight) vs. production, misleading developers about the final user experience**

It is incredibly frustrating that you can't test the final flow until the app is live!

According to [this source](https://developer.apple.com/documentation/storekit/in-app_purchase) and also my experience, there are some weird gotchas when testing IAP mainly around which account details to input when you see a pop-up.

> If you log in to the App Store app with your sandbox credentials, it will ruin your sandbox account.

Therefore it's important to know which details you need to enter in which pop-up!

Before you start:

1. You must ensure that all of your Agreement, Tax and Banking are "Active" in ItunesConnect, [please see](https://developer.apple.com/library/archive/technotes/tn2259/_index.html)
2. You have created a FRESH Sandbox Tester in Users & Access in iTunesConnect
3. In my opinion, when testing, it's best to sign out from iTunes on the device (both your account AND your Sandbox Tester account) in order to make it clearer when you are required to enter information and what this information is for. (Settings > iTunes & App Store > Sign Out).

## Testing locally (on a simulator)

Apple has stated multiple times that IAP must be tested on a device not on the simulator.  There have been versions of iOS and MacOS that have allowed you to test IAP in the simulator - but that is the rare gift rather than something to be expected.

I __wish__ this was more obvious...

## Testing locally (on a device)

First you will see a pop-up that will ask you to sign into your sandbox account:

If you are not logged into your Sandbox iTunes account it will ask you to login to your Sandbox Apple Id. 

**Note: Even though it doesn't say [Environment: Sandbox] on this pop-up this is your Sandbox Account and not your normal Apple Account:**

<img src="https://user-images.githubusercontent.com/40461/69760085-82a88600-115b-11ea-8c01-1d76b9ea4108.jpg" alt="sign-in-local" width="200" />

(The reason why I know it is the sandbox account.. if you login and then go to Settings > iTunes & App Store you will see that you have been logged in to your Sandbox Account and NOT your main Apple Id).

If you were already logged into your Sandbox iTunes account the pop-up will look like this:

<img src="https://user-images.githubusercontent.com/40461/69760101-889e6700-115b-11ea-8f93-38c07ba5ffe7.jpg" alt="sign-in-local-previously-logged-in" width="200" />

Sometimes, you may get this pop-up... (Exactly when this happens requires more research).

<img src="https://user-images.githubusercontent.com/40461/69760355-3f9ae280-115c-11ea-90ac-ee0f5683dcbf.jpg" alt="your-account-is-temporarily-unavailable-local" width="200" />

I have also got these two pop-up at this point too... (Any information on these edge cases would be helpful)

<img src="https://user-images.githubusercontent.com/40461/69760408-66f1af80-115c-11ea-9ec9-9123d07fb034.jpg" alt="enter-the-password-sandbox-local" width="200" />

<img src="https://user-images.githubusercontent.com/40461/69760630-ef705000-115c-11ea-88e9-15efcd7a86ec.jpg" alt="if-you-have-used-the-iTunes-Store-local" width="200" />

After selecting a purchase to buy, you will see a pop-up where you will need to enter the password again for your Sandbox Account in order to purchase (this happens instead of the conventional purchase screen):

<img src="https://user-images.githubusercontent.com/40461/69753904-8b459000-114c-11ea-91b6-6ff001266fea.jpg" alt="confirm-purchase-local" width="200" />

Then you will see a pop-up asking you to confirm the purchase:

<img src="https://user-images.githubusercontent.com/40461/69754001-bcbe5b80-114c-11ea-9123-8b7f2c0298f7.jpg" alt="confirm-subscription-local" width="200" />

If the subscription was a success, you will see:

<img src="https://user-images.githubusercontent.com/40461/69761404-36f7db80-115f-11ea-8603-74628878d097.jpg" alt="your-all-set-local" width="200" />

If the subscription fails, you will see:

<img src="https://user-images.githubusercontent.com/40461/69754057-e081a180-114c-11ea-952c-cb3264314d12.jpg" alt="not-authorised-local" width="200" />

**UPDATE from @jordangrant ** After successfully subscribing, if you try to subscribe again, you will see:

<img src="https://user-images.githubusercontent.com/40461/69766934-0bcab780-1172-11ea-9f7f-604cd2d4d5f4.png" alt="already-subscribed" width="200">

## Testing on TestFlight

> TestFlight users don't require a sandbox account, but they will test against an automatically created sandbox account. This means it's no longer necessary to create test accounts in iTunes Connect. Your TestFlight user is a legitimate App Store user, but doing in-app purchases made with beta builds are free within the context of the beta version.

If you are already logged into your iTunes account and you try to make a purchase, you should see this:

<img src="https://user-images.githubusercontent.com/40461/69767230-32d5b900-1173-11ea-99d9-41daad23c976.jpg" alt="confirm-purchase-testflight" width="200" />

However, if you are logged out, you will see this:

<img src="https://user-images.githubusercontent.com/40461/69767258-4b45d380-1173-11ea-9e7a-e6c7f9c4f4d2.jpg" alt="confirm=purchase-testflight-logged-out" width="200" />

When you see these, you must enter your iTunes credentials rather than a Sandbox account.

## Validating Receipts

In my experience, the main problem is when you are validating receipts with:

```
const decodedReceipt = await RNIap.validateReceiptIos({
    'receipt-data': latestAvailableReceipt,
    password: C.ITUNES_CONNECT_SHARED_SECRET,
  },
  isTestEnvironment,
);             
```

The variable `isTestEnvironment` will toggle between validating using:

- https://buy.itunes.apple.com/verifyReceipt
- https://sandbox.itunes.apple.com/verifyReceipt

And will cause a pop-up to be displayed dependent on which environment you are in.

If you use `__DEV__` for the environment variable, this will be `false` in TestFlight and therefore will try to validate the receipt purchased with the production endpoint. 

Therefore my solution is similar to [this advice](https://github.com/react-native-community/react-native-device-info/issues/228) from @agates4 and create a way to check if the app is running on TestFlight:

In your Xcode workspace, create a file TestFlightChecker.h

```C
#ifndef TestFlightChecker_h
#define TestFlightChecker_h

#if __has_include("RCTBridgeModule.h")
#import "RCTBridgeModule.h"
#else
#import <React/RCTBridgeModule.h>
#endif

@interface TestFlightChecker : NSObject <RCTBridgeModule>
@end 

#endif /* TestFlightChecker_h */
```

In your Xcode workspace, create a file TestFlightChecker.m

```C#
#import "TestFlightChecker.h"

@implementation TestFlightChecker

- (dispatch_queue_t)methodQueue
{
    return dispatch_get_main_queue();
}

+ (BOOL)requiresMainQueueSetup
{
    return YES;
}

RCT_EXPORT_MODULE()

- (NSDictionary *)constantsToExport
{
    NSURL *receiptURL = [[NSBundle mainBundle] appStoreReceiptURL];
    NSString *receiptURLString = [receiptURL path];
    BOOL isRunningTestFlightBeta =  ([receiptURLString rangeOfString:@"sandboxReceipt"].location != NSNotFound);

    return @{ @"isTestFlight" : @(isRunningTestFlightBeta) };
};

@end
```

Those are the files needed to call the objective-c functions from react native. The function above will determine if the app is on the App Store or on TestFlight.

And now the react-native implementation

```js
import { NativeModules } from 'react-native';
const { TestFlightChecker } = NativeModules;
export default TestFlightChecker;
```

This way, you'll be able to do:

```js
import TestFlightChecker from './testflight';
.
.
.
const isTestEnvironment = __DEV__ || TestFlightChecker.isTestFlight;

const decodedReceipt = await RNIap.validateReceiptIos({
    'receipt-data': latestAvailableReceipt,
    password: C.ITUNES_CONNECT_SHARED_SECRET,
  },
   isTestEnvironment,
);
```

**Comment by jordangrant** [comment]
<img width="231" alt="Screen Shot 2019-11-27 at 6 23 56 PM" src="https://user-images.githubusercontent.com/7986493/69765730-246fa900-1143-11ea-818a-2ae12ac22dd4.png">

**Comment by alexpchin** [comment]
Thanks @jordangrant I've added on here

**Comment by hyochan** [comment]
@alexpchin This is really great 🥇 ! Thank you for supporting others.
