### ISSUE TITLE
Testing on same device, same iTunes account, different user logins

### ISSUE THREAD

**Issue by alexpchin** [dooboolab/react-native-iap#866]
When working with auto-renewable subscriptions, it is a common situation that a developer is using their device with their Apple iTunes account with multiple user logins.

I.e. Registering and account on the platform you are building, signing up to an auto-renewable subscription, paying with your iTunes account. Then logging out, registering a new account.

At this point, I think it is possible for `await RNIap.getAvailablePurchases();` to return active purchases for the new second user despite them not having signed up to the auto-renewable subscription yet?

Is this correct?

**Comment by alexpchin** [comment]
Does anyone have any ideas to resolve this?

**Comment by baiross** [comment]
up, same problem :3
