### ISSUE TITLE
no longer broadcast the install_referrer intent 

### ISSUE THREAD

**Issue by akashmi** [dooboolab/react-native-iap#874]
#### Android

I received an email from Google as below.

> Hello Google Play Developer,
> 
> We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.
> 
> Action required
> 
> Migrate to the Play Install Referrer API to track your app installs for the following apps and/or games.
> 
> The Play Install Referrer API offers better performance, uses a secure communication channel between your app and the Play Store, and offers a more robust solution against spoof and attribution fraud.

It may happen due to below receiver

```
<receiver
            android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver"
            android:enabled="true"
            android:exported="true"
            android:permission="android.permission.INSTALL_PACKAGES" >
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
```

How to resolve this?

**Comment by hyochan** [comment]
Since I'm not sure how I can resolve this issue, I hope you can provide any further ideas on how to overcome this problem.

**Comment by akashmi** [comment]
@hyochan 
Google play has suggested required action as below.  this might be useful to you.

[Migrate to the Play Install Referrer API](https://www.google.com/appserve/mkt/p/AFnwnKWP_p5ruCCyIwZl7KKMs_762Jrl9BIcJ6w79RmYS2DypJ-buXD9_PBdN6w-RcKEtQ84HS4sVDaPW9cZI-p7BamoPk1UpjaPtDO0T7jzKaCWieggE3nu_w5vfQg-AeR6B_3MepWIMhqgyA) to track your app installs.

**Comment by hyochan** [comment]
Looks like you are using old version of `react-native-iap`. Please try our recent one which starts from `4.0.0+`
