### ISSUE TITLE
IAP Products based on SKUs are not loaded for Android in Development

### ISSUE THREAD

**Issue by tulpn** [dooboolab/react-native-iap#877]
### Version of react-native-iap
4.3.0
### Version of react-native
0.61.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Get the products from the provider (Google Play)

### Actual behavior
Does not return products from the provider

### Tested environment (Emulator? Real Device?)
Real Device 

### Steps to reproduce the behavior
I am still in the development process. The IAP for iOS are loaded correctly and can be purchased in the sandbox environment. However, the same does not hold for Android.
I have uploaded an AAB to Google Play and it is currently in review for publishment in my Alpha track. 

At the moment I am running the Android app via the `run-android` command on my real device. 

I have pretty much used the code from the documentation, as I considered it a working example. 

```
export const itemSkus = Platform.select({
  ios: [
    'coinpack_350',
    'coinpack_1100',
    'coinpack_1550',
    'coinpack_3750',
    'coinpack_8000',
    'coinpack_17500',
    'coinpack_45000',
    'coinpack_99999',
  ],
  android: [
    'coinpack_350',
    'coinpack_1100',
    'coinpack_1550',
    'coinpack_3750',
    'coinpack_8000',
    'coinpack_17500',
    'coinpack_45000',
    'coinpack_99999',
  ]
});
....
const products = await RNIap.getProducts(itemSkus);
```

In Google Play my IAP are shown as:
```
Product ID - coinpack_350 (Active)
```

I have followed the blog post how to set it up linked in the documentation. 

Is the IAP on Android limited to published apps, that are downloaded from Google Play? Can I not test it with the local development machine?

**Comment by olivinesguerra** [comment]
same here :D

**Comment by tulpn** [comment]
i fixed the issue, should probably be in the documentation:
A build needs to be released to interal or alpha to work. It needs to be "published" and have the status full roll-out. (This does not need to be production!)
