### ISSUE TITLE
purchaseUpdatedListener not trigger in ios

### ISSUE THREAD

**Issue by rajsavaliya** [dooboolab/react-native-iap#879]
###  react-native-iap-4.3.3
4.3.3

### Expected behavior
after successfully payment should gone in purchaseUpdatedListener but it shows Cannot read property 'startListening' of undefined

### Actual behavior
Cannot read property 'startListening' of undefined

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
i have two screen for in app purchase
1) For get select subscription and go to next screen
2) agree terms and condition and make payment  

in above scenario getting list successfully but in make payment getting error:" Cannot read property 'startListening' of undefined"

![Screenshot 2019-12-18 at 5 11 06 PM](https://user-images.githubusercontent.com/50477535/71083642-8313ca00-21b9-11ea-8460-6d9f48721913.png)

**Comment by hyochan** [comment]
Could you verify yourself that you've installed `react-native-iap` correctly?

**Comment by rajsavaliya** [comment]
yes i have installed react-native-iap correctly and in android working perfectally

**Comment by hyochan** [comment]
Well but `startListening` is only triggered for `android` and not `ios`.
![image](https://user-images.githubusercontent.com/27461460/71777841-2d2c8800-2fe9-11ea-9f46-b4b8d5c156fd.png)

The above error message looks very weird to me.

**Comment by rajsavaliya** [comment]
thanks for your suggestion i solved my issue and thanks for your help

**Comment by hyochan** [comment]
> thanks for your suggestion i solved my issue and thanks for your help

Good to hear! What was the cause?

**Comment by rajsavaliya** [comment]
It, caused to i forget to manually link to xcode
