### ISSUE TITLE
'Invalid Product ID Error' but everything is setup correctly

### ISSUE THREAD

**Issue by damialajogun** [dooboolab/react-native-iap#880]
react-native-iap-4.3.2

react-native-0.59.1

Platforms you faced the error (IOS)

Expected behavior

After clicking on button in app, In-app payment should be triggered

Actual behavior
e_developer_error 'invalid product id'

Tested environment - Real device

Steps to reproduce the behavior
please see my code below. When I click on the button triggered by onPress function, the error pops up
![image](https://user-images.githubusercontent.com/53242839/71224895-c139e800-22a4-11ea-845c-b5c2979419d7.png)
![image](https://user-images.githubusercontent.com/53242839/71224907-cf880400-22a4-11ea-8953-6167d6237e00.png)

I have set up certificates, tax and banking agreements, product ids are set up in App store connect..All the steps but it still won't work.

**Comment by yanush** [comment]
For me, i had to do 3 things for purchases to work:

1. Make sure you are actually passing the product sku to RNIap.requestPurchase
2. Make sure that the signed in Apple Id on your device is also a listed as sandbox tester in app store connect (under Users and Access)
3. Make sure that the app is available for the country defined for this apple id user

Hopefully one of these will solve your issue

**Comment by yanush** [comment]
A weird thing with that error is that everything was working for me, until it suddenly stopped when no code changes were made.
The only thing that solved and got it back to work again was to create a new test user and sign in with its apple id on my test device

**Comment by yanush** [comment]
one more thing. make sure it's a release build you're running. for some reason it's not working for me in debug

**Comment by damialajogun** [comment]
@yanush Thanks for responding, unfortunately it has never worked for me to begin with and I've tried all the solutions from other similar threads. I have a sandbox tester account on a real device that I'm using to test but I still get the error 'invalid product id'. I'm also running a release build but no luck.

**Comment by yanush** [comment]
do you have your test apple id configured also under "iTunes & App Store -> Sandbox Account"?
(In the device settings)

**Comment by damialajogun** [comment]
@yanush When I go to setting -> iTunes & App Store, I scrolled all the way down but don't see an option for Sandbox Account. Will it not work even if the apple ID I am signed into is the sandbox account itself?

**Comment by yanush** [comment]
i'm not sure. just started using this package myself.
which ios version are you using? I'm on 12.4.4 (cause it's an old ipad and it didn't get ios 13)
maybe this thread might help you:
https://stackoverflow.com/questions/57850713/ios-13-how-to-login-in-in-app-purchase-sandbox-account

**Comment by damialajogun** [comment]
@yanush Do you have content hosting on? Do you know if that is required for RN's IAP to work in iOS?

**Comment by yanush** [comment]
I don't have it on and therefore it's not mandatory for RNIap to work

**Comment by damialajogun** [comment]
@yanush Sorry for all the questions, I've been stuck on this for the past month. Do you have a server set up for your IAP? That's not needed is it? I don't know what else to look into....

**Comment by yanush** [comment]
you should be able to validate receipts through client only

**Comment by damialajogun** [comment]
@yanush Does your app sell non-consumable, auto-renewable subscription, or non-renewing subscription products by chance?

**Comment by yanush** [comment]
nope. just consumables for now

**Comment by yanush** [comment]
@damialajogun can you show me the part of your code where you call RNIap.getProducts()?

**Comment by damialajogun** [comment]
I actually removed it from my code because it wasn't being called. I added it in initially to console log and make sure the product IDs are being pulled, which they were, but then removed it as the RNIAP.requestPurchase() isn't using it. Do you think this is wrong?

**Comment by yanush** [comment]
yup. you have to call it every time your app starts

**Comment by damialajogun** [comment]
@yanush you were right, it works now! Thank you soooo much! You have no idea!

**Comment by scchess** [comment]
Confirmed that `RNIap.getProducts` needs to be called before `RNIAP.requestPurchase()`.

**Comment by roots-ai** [comment]
@scchess Such strange solution. Only needed for iOS.

**Comment by hafizMDM** [comment]
Wow!!! have been struggle on this for days. Thanks @damialajogun

**Comment by SaeedMuhaisen** [comment]
Just to confirm 2025, you still need to call `getSubscriptions()` or `getProducts()` on every single call to make it work correctly without lags

This is working on React Native 0.76.5 and expo 52.0.1
`ts
	const subscribe = async (sku: string) => {
		try {
			setLoading(true);
			await IAP.endConnection();
			await IAP.initConnection();
			await IAP.getSubscriptions({
				skus: ["your_product_id", "your_product_id"],
			});
			const purchase = await IAP.requestSubscription({
				sku: sku,
			});
			await IAP.finishTransaction({ purchase: purchase as IAP.Purchase });
		} catch (err: any) {
			console.warn(err.code, err.message);
		}
	};
`

**Comment by binitjha452** [comment]
Still facing issue

**Comment by binitjha452** [comment]
any solution please
