### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by avinduhewa** [dooboolab/react-native-iap#883]
### Version of react-native-iap
    "react-native-iap": "^4.3.3"

### Version of react-native
     "react-native": "0.61.5"
### Platforms you faced the error (IOS or Android or both?)
    Android

Build fails with the following message

node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:
uses or overrides a deprecated API.

**Comment by hyochan** [comment]
I've recently tested this in our  [example](https://github.com/dooboolab/react-native-iap/blob/002bf1937df751e01d662eb0fcde165c48c27967/IapExample/package.json#L15) project and it worked fine. Could you also try that?
