### ISSUE TITLE
getProducts returns empty array

### ISSUE THREAD

**Issue by LeeMoonki** [dooboolab/react-native-iap#886]
### Version of react-native-iap
4.3.3
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
return the product list
### Actual behavior
return empty array
### Tested environment (Emulator? Real Device?)
Real Device connected with USB and debug with Safari browser
### Steps to reproduce the behavior
1. insert billing permission in `AndroidManifest.xml` like
```xml
<uses-permission android:name="com.android.vending.BILLING" />
```
2. upload this android app AAB to **alpha version** and didn't release it.
3. create product with id `productid1` and `productid2`. `productid1` is **active apk** and `productid2` is **inactive**.
4. make following code

```javascript
import * as RNIap from 'react-native-iap';

const itemSkus = Platform.select({
  ios: ['productid1', 'productid2'],
  android: ['productid1', 'productid2'],
});

...
componentDidMount() {
  RNIap.initConnection().then(conn => {
    // conn is true
    RNIap.getProducts(itemSkus)
      .then(res => {
        // res is []
      })
      .catch(err => {
        // no err
      });
  });
}
...
```

**Comment by falidd18** [comment]
same here

**Comment by abbas321** [comment]
same here

**Comment by hyochan** [comment]
Have you checked  [this](https://github.com/dooboolab/react-native-iap/issues/159#issuecomment-389413989)?

**Comment by LeeMoonki** [comment]
@hyochan yes I did check the list. The below list is what I did in detail which is not mentioned above.

1. I installed the `react-native-iap` following **[Using React Native >= 0.60](https://github.com/dooboolab/react-native-iap#mostly-automatic-installation)** only(not **[Manual installation](https://github.com/dooboolab/react-native-iap#manual-installation)**.  And write the **android/build/gradle** configuration along with **Android Platform with Android Support**. This is my code in android/build.gradle

```
ext {
    buildToolsVersion = "28.0.3"
    minSdkVersion = 16
    compileSdkVersion = 28
    targetSdkVersion = 28
    supportLibVersion = "28.0.0"
    googlePlayServicesAuthVersion = "17.0.0"
}
```

2. My app is in state **temporary stored**, which is not exact word since I translate it from Korean to English, not **Released**. Does the app have to be **released**? (I registered the app in **closed track** with a comment **There is an unreleased app.**.)

**Comment by hyochan** [comment]
@LeeMoonki apk should only be uploaded. You can also follow [this](https://medium.com/bleeding-edge/testing-in-app-purchases-on-android-a6de74f78878). Cheers 🙏

**Comment by LeeMoonki** [comment]
@hyochan Thank you for answer. I will upload(I think this can be the release of app with Alpha test) the app. But it will takes some time since we need to prepare some informations, for instance app image. After uploading the app, I will try to get the product list.

**Comment by HyeonjuPark** [comment]
@hyochan Have you tried on release version? I have same problem here. When I tested it before, it worked. I purchased my item several times, but suddenly this is not working on Android device.

**Comment by hyochan** [comment]
@LeeMoonki You can only upload apk to alpha stage. Playstore just need your built apk without releasing it to production level. Please check your `in-app-purchases` configuration once more and I think this is what you need in this stage. `react-native-iap` doesn't have the following issue in `example` project.
