### ISSUE TITLE
requestPurchase still returns a promise

### ISSUE THREAD

**Issue by yanush** [dooboolab/react-native-iap#887]
### Version of react-native-iap
4.3.3
### Expected behavior
should return void according to docs
### Actual behavior
returns a promise

**Comment by hyochan** [comment]
Would you like to give us a `PR` on this? We've previously removed `promises` but still, someone wanted to be there to check any internal error.

**Comment by yanush** [comment]
I would also like to keep it this way since i'm using the error returned.
I would suggest to fix the docs, not the code

**Comment by hyochan** [comment]
@yanush PRing on the doc would help us too. I hope you can help us with this.

**Comment by hyochan** [comment]
Closes via #890
