### ISSUE TITLE
RNIap.getSubscriptions() fails to resolve

### ISSUE THREAD

**Issue by stefangiapantzakis** [dooboolab/react-native-iap#894]
### Version of react-native-iap
^3.5.2
### Version of react-native
0.60.3
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
RNIap.getSubscriptions([skus]) should resolve
### Actual behavior
On some devices it hangs forever and never resolves
### Tested environment (Emulator? Real Device?)
Real Device's, live on store
### Steps to reproduce the behavior
Call RNIap.getSubscriptions([skus]) after launching the app.
It has been difficult to reproduce internally, we have only reproduced it once and restarting the device fixed it. For most live users however, restarting their devices does nothing.

**Comment by hyochan** [comment]
We are recommending to use `purchaseUpdatedListener` instead of using `getSubscriptions`. `Promises` can't always be reliable. Please see the [medium blog](https://medium.com/dooboolab/react-native-iap-v3-1259e0b0c017)

**Comment by stefangiapantzakis** [comment]
@hyochan I am using the purchaseUpdatedListener for handling purchases. This is for fetching subscriptions and their data (price etc). The purchaseUpdatedListener doesn't return that information?

**Comment by hyochan** [comment]
@stefangiapantzakis use `requestSubscription`

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/71872691-8539ca80-3160-11ea-9f2a-44a48663232f.png)

Try using above two methods. You might have forgotten to `finishTransaction` which may cause this behavior.

**Comment by stefangiapantzakis** [comment]
@hyochan Ok, thanks, I'll try the above. I am calling `finishTransaction` after validating the receipt in the `purchaseUpdatedListener`. The issue presents itself when a user launches the app and a receipt is generated in the StoreKit Queue because the `purchaseUpdatedListener` calls `fetchSubscription` initially in order to grab the subscription information for analytics purposes (prices etc). When the `fetchSubscription` call happens is when the hang occurs.

**Comment by hyochan** [comment]
I hope you can provide some codes in which it is hanging. We might have to think about how to handle that situation.

**Comment by Exilz** [comment]
If you're hitting this issue on a physical device as well using the sandbox environment just try to... reboot you phone.
It happens sometimes. Apple's sandbox is a buggy mess.
