### ISSUE TITLE
Acknowledging transactions seems to work only 50% of the time

### ISSUE THREAD

**Issue by phillmill** [dooboolab/react-native-iap#899]
### Version of react-native-iap
4.3.0

### Version of react-native
0.61.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Aall purchases are acknowledged

### Actual behavior
I'm having an issue where roughly half of all subscription charges get stuck in "Payment Pending" mode for multiple days. However, the other half of them charge successfully, so I know that my logic is acknowledging the purchase -or at least attempting to- each time. How could this happen?

### Tested environment (Emulator? Real Device?)
Real Devices

### Steps to reproduce the behavior
This has only been happening to the users of my app, I can't seem to reproduce it myself - it's successful every time I test it.

For more context, this is for a 7 day free trial of a subscription. The initial "purchase" works okay with no "payment pending" issues, it's the automatic renewal at the end of the 7 day trial where the payment pending issue happens. Does the second "real" charge after the free trial need to be somehow acknowledged as well even if a user doesn't necessarily open the app around that time?

Perhaps this is nothing to do with acknowledging, but it's the only thing I can think of

I'm basically using the example in the readme for purchase flow, this is my code:

<pre>
this.purchaseUpdateSubscription = purchaseUpdatedListener((purchase: InAppPurchase | SubscriptionPurchase | ProductPurchase ) => {

      const receipt = purchase.transactionReceipt;

      if (receipt) {

        this.activePurchaseSku = null;

        // Enable the purchase
        this.enablePurchaseBySku(purchase.productId, false);
        
        // Aknowledge the transaction
        RNIap.finishTransaction(purchase);

      }

});
</pre>

**Comment by hyochan** [comment]
Looks like it is related #896 which is merged in `4.4.0`. Would you like to try it?

**Comment by phillmill** [comment]
@hyochan I will try it out for sure and report back, thanks!

Although I don't have any RNIap crashes in crashlytics.

**Comment by lklepner** [comment]
We have found that acknowledging android purchases occasionally results in the JS bundle being restarted... which we've found very different to explain.
