### ISSUE TITLE
InApp Purchase error

### ISSUE THREAD

**Issue by IosDevAhmed** [dooboolab/react-native-iap#9]
I got this error from logs : 

TypeError: undefined is not an object (evaluating '**RNIapIos.fetchProducts**')

and thus can't guess what is the issue with that.

Any idea? Thanks.

**Comment by KjellConnelly** [comment]
a) Why don't you call the Javascript fetch method instead? ```getItems()``` I believe
b) Usually I get Undefined in RN Modules when I didn't link properly. What do you get when you call ```console.log(NativeModules.RNIapIos)```? If that's undefined, I am guessing you didn't link properly.

**Comment by dooboolab** [comment]
@IosDevAhmed 
Yes. please check if you are linked correctly. Also as KjellConnelly mentioned in a), it is recommneded to use provided functions we described in readme.
