### ISSUE TITLE
[iOS] Apple reject app : Guideline 3.1.1 - Business - Payments - In-App Purchase

### ISSUE THREAD

**Issue by alanlanglois** [dooboolab/react-native-iap#90]
### Version of react-native-iap
0.3.0-beta3

### Expected behavior
Pass through Apple App Store validation

### Actual behavior
Apple keep rejecting the app invoking Guideline 3.1.1 - Business - Payments - In-App Purchase

> We found that your app offers in-app purchases that can be restored but does not include a "Restore Purchases" feature to allow users to restore the previously purchased in-app purchases, as specified in the "Restoring Purchase Products" section of the In-App Purchase Programming Guide:
> 
> "Users restore transactions to maintain access to content they've already purchased. For example, when they upgrade to a new phone, they don't lose all of the items they purchased on the old phone. Include some mechanism in your app to let the user restore their purchases, such as a Restore Purchases button."
> 
> To restore previously purchased in-app purchase products, it would be appropriate to provide a "Restore" button and initiate the restore process when the "Restore" button is tapped by the user.

We only use consumable products (we don't even have other products set in itunes connect.

### Steps to reprodue the behabior
Submit an app with inapp purchase and subscription and you might be rejected as we are.

Note:  Interesting post that can help us out: https://forums.developer.apple.com/thread/78759

**Comment by JJMoon** [comment]
Is the product you define a consumable product? If it is, you must setup your server and restore process of your own. That contains some steps as follows.
> send receipt to your server.
> you apply the purchase to some properties, like game money, gold, coin, heart whatever.

**Comment by JJMoon** [comment]
I think I misunderstood your question.

I guess you setup a non-consumable products.
In this case, you need 'restore' button in your app, to restore previous purchased non-consumable products. "Restore Purchases" feature means this button (or any other mean).

I hope this is the right answer

**Comment by alanlanglois** [comment]
Yes I use only one consumable product. 
The purpose of this inapp is to kind of speed up the completion of an action.
In my case, we have stories displayed 1 chapter a day, buying an inapp let you "unlock" the story and read all the chapters in one time if you want to (and  not one chapter a day as before)

Apple says I'm using non consumable product (that can be restore) but it's a little confusing cause I'm not. Maybe they mean this kind of usage needs to be aimed with non-consulable inapp ?

**Comment by JJMoon** [comment]
I think your product is 'consumable'. Because, it doesn't match any story. It can vary.
But, it can be considered as non-consumable at the first look. Because, many game stages, stories can be eternally unlock via con-consumable payment.

But, you must implement backend server for this situation.

> User purchase 'one' product to see the next story.
> But, he doesn't see the next story, because of any other interaction.
> He erase the app
> He re-install the app. His purchase has gone.

**Comment by alanlanglois** [comment]
Ok, it doesn't really match the description given by Apple: 

> You'll need to buy these items every time you want them, and you can't download them again for free. If you remove and reinstall an app, or install an app on a new device, you might lose your consumable purchases. For example, if you install a game on your iPod touch that you started playing on your iPhone, the game levels sync, but extra health or experience points you bought on your iPhone don't sync.

There is no account / login system in the app, it will take some time to implement if really needed. 

Nothing in the extension code could let them automaticaly think it is non-consumable products?

**Comment by JJMoon** [comment]
You need 'account / login' system for consumable products. 
Non-consumable products belong to Apple Account (for AppStore), so Apple server takes care of it.

**Comment by dooboolab** [comment]
@alanlanglois Ok. Sounds like not our issue tough. Please come back to us when there is some other issue.

**Comment by ragnorok** [comment]
So would this be the same as having copies of a program for an event? Would you be able to use consumables? Or would it be a non consumable for that event.

**Comment by dooboolab** [comment]
@ragnorok I am not sure, but from my understanding from above, reviewer issues on non-cosumable products.

**Comment by lwansbrough** [comment]
Subscriptions are non-consumable. Any non-consumables must have a restore button. This part of the review process is not determined by what code is in your app, but instead if you expose restore functionality in your UI. Closing as this library is not impacting your review.

**Comment by ragnorok** [comment]
Thanks!
