### ISSUE TITLE
Invalid product ID during requestSubscription on iOS

### ISSUE THREAD

**Issue by varungupta85** [dooboolab/react-native-iap#900]
### Version of react-native-iap
4.3.0
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
See Apple UI to request a subscription
### Actual behavior
Get an error "Invalid product ID"
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
I am having two issues while using subscriptions on iOS that I am not able to resolve for quite some time.

1. User is asked to sign into their iTunes account whenever a user opens the app. That is not a good user experience and I know other apps that have in-app purchases don't ask me to sign in every time I open the app from scratch. I guess I am asked to sign in because I am retrieving the purchases made by the user but I need to know that to know if a user is a premium user or not.
 
2. When I call `requestSubscription`, I get an error "Invalid product ID".  I have looked at issue #256 and #304 and made sure I have followed all the steps. I have a valid subscription in "Ready to Submit" state on the App Store Connect as shown in below screenshot. I have completed all the required agreements. I have created a Sandbox tester and use that to log into the device.

<img width="1138" alt="Screenshot 2020-01-10 at 6 01 01 PM" src="https://user-images.githubusercontent.com/7475133/72153273-7444bf80-33d3-11ea-9dbd-479eb66cdc88.png">

I am stuck on this for last couple of days and not sure what to do.

Please let me know what can I do to resolve these problems.

**Comment by hyochan** [comment]
We need more information to to take care of your issue. Also please check you `javascript` code too.

**Comment by varungupta85** [comment]
I have fixed the issue. We need to sign out of the iTunes account on the phone and sign in using the sandbox account in the app directly. I am having another issue which is I get error `Cannot connect to iTunes store` whenever I try to request a purchase. I will open a separate issue for that. Thanks!

**Comment by binitjha452** [comment]
how you fixed this issue i am also stuck on this issue
