### ISSUE TITLE
Cannot connect to iTunes store error on iOS in sandbox environment.

### ISSUE THREAD

**Issue by varungupta85** [dooboolab/react-native-iap#901]
### Version of react-native-iap
4.3.0
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Sign into the iTunes store and buy the subscription
### Actual behavior
`requestSubscription` call fails with error `Cannot connect to iTunes Store`. 
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Set up the subscription and sandbox environment. Make a call to `requestSubsciption` as a Sandbox tester. Observe error `Cannot connect to iTunes Store`. I have followed the information on this Apple forum to no relief https://forums.developer.apple.com/thread/98763 .

Please let me know if you have come across this problem and know how to get around it.

**Comment by mustafaaksoy** [comment]
what is is resolve this bug?

**Comment by DavideValdo** [comment]
...

**Comment by anastely** [comment]
Are you solve it?
