### ISSUE TITLE
In App Purchase - auto renew subscription - How to get notified if the user cancel or auto renewable subscription?

### ISSUE THREAD

**Issue by iqbalfaisal** [dooboolab/react-native-iap#905]
I am working on an app which has our own user database and cross platforms subscription. and my questions are:

1- What happens if they uninstall the app?  Does the subscription automatically get cancelled?
2- What happens if they have the app installed on two devices, do both of them get notified?
3- What happens if they have the app installed on two devices and Login with different App Account and both of them have login with same Apple ID or Google Account will both of them get notified?
4. If user cancel the subscription from settings, how do we know which user canceled the services? I would like to inform my server that this user canceled subscription.
5-How do we know a user did auto-renew or canceled the subscription without opening app. Is there any unique id in apple's receipt which we can get to validate the user id.

Thanks.

**Comment by denkeni** [comment]
On iOS side:

1. Only since iOS 13, user gets alert about subscription after deleting the app ([ref](https://www.macrumors.com/2019/06/18/ios-13-alert-when-delete-app-with-subscription/)). The subscription does *not* get cancelled automatically.
2. I don't understand what you said about "notified".
3. Same above. With your own user database, you should keep and link receipt to your user identify, so to mark it as subscribed.
4. You should enable [Server-to-Server Notifications](https://developer.apple.com/documentation/storekit/in-app_purchase/enabling_server-to-server_notifications) to receive `DID_CHANGE_RENEWAL_STATUS ` event.
5. Same above. Use `original_transaction_id` as the unique id.

**Comment by ahanusek** [comment]
For Android you should use real-time developer notifications:
https://developer.android.com/google/play/billing/realtime_developer_notifications

**Comment by iqbalfaisal** [comment]
@denkeni  @ahanusek  @hyochan 
when user subscribe the specific package and log out from app account and again login in app with different account and want to subscribe the package which he did last time then he is receive a message by server(Google or Apple) that's "you already subscribe this package "

Kindly help me.

**Comment by denkeni** [comment]
@iqbalfaisal IAP goes with user’s Apple ID or Google Account, *not* with your app account. Deal it with your app logic.

**Comment by iqbalfaisal** [comment]
> @iqbalfaisal IAP goes with user’s Apple ID or Google Account, _not_ with your app account.

Yes i know.

> Deal it with your app logic.

I tried but failed. Can you help me and guide me with the help of instructions generally.

**Comment by Bang9** [comment]
@iqbalfaisal If subscription is valid, you should provide recover flow to user

**Comment by iqbalfaisal** [comment]
@Bang9 i didn't understand. Kindly describe this completely.

**Comment by Bang9** [comment]
@iqbalfaisal 
1. user purchase 1month subscription
2. you can get purchase information
(If you want to know auto_renew_status without app logic, save the information into your server and receipt validation with server to server notification, [android](https://developer.android.com/google/play/billing/realtime_developer_notifications), [ios](https://developer.apple.com/documentation/storekit/in-app_purchase/enabling_server-to-server_notifications), or you can use [revenue cat service](https://www.revenuecat.com/))

3. provide premium feature to user
4. user remove app
5. user reinstall app and login
6. user can not access premium feature
7. user clicked recover purchase
(you can get user purchases with `RNIap.getAvailablePurchases` [refer this](https://github.com/dooboolab/react-native-iap#restoring-purchases))
8. if purchase is valid, provide premium feature to user

**Comment by iqbalfaisal** [comment]
> 2- What happens if they have the app installed on two devices, do both of them get subscription?
> 3- What happens if they have the app installed on two devices and Login with different App Account and both of them have login with same Apple ID or Google Account will both of them get subscription?
>4- when user subscribe the specific package and log out from app account and again login in app with different account and want to subscribe the package which he did last time then he is receive a message by server(Google or Apple) that's "you already subscribe this package "

@Bang9 sorry but my questions are totally different.

**Comment by Bang9** [comment]
> when user subscribe the specific package and log out from app account and again login in app with different account and want to subscribe the package which he did last time then he is receive a message by server(Google or Apple) that's "you already subscribe this package "
> 
> Kindly help me.

@iqbalfaisal I'm answering your question

**Comment by iqbalfaisal** [comment]
> If you want to make a new purchase every time with same subscription when users app account changes, that is impossible

Many Thanks @Bang9. Really appreciate your time and effort. Kindly tell me how to handle point 2 & 3 please.

**Comment by Bang9** [comment]
@iqbalfaisal Read the document of Android and iOS in step 2

**Comment by iqbalfaisal** [comment]
> 
> 
> @iqbalfaisal Read the document of Android and iOS in step 2

@Bang9 i didn't find relevant part about this that's why i asked you. Kindly share with if you know relevant part for both Android & IOS. It'll be very great help. Thanks

**Comment by Bang9** [comment]
> > @iqbalfaisal Read the document of Android and iOS in step 2
> 
> @Bang9 i didn't find relevant part about this that's why i asked you. Kindly share with if you know relevant part for both Android & IOS. It'll be very great help. Thanks

I read that document and I made my payment server(working with server to server notification)
why didn't find relevant part?

on Android, you can receive `SUBSCRIPTION_CANCELED` event via Pub/Sub
on iOS, you can receive `DID_CHANGE_RENEWAL_STATUS ` event via incoming webhook

**Comment by iqbalfaisal** [comment]
@Bang9 i think you didn't understand point 2. Let me describe you. 

Let say one Google account have login on two devices and have login with different accounts in APP and when user1 will subscribe the package then user2 will get the subscription rather then user1. Sometimes both users will received token. When they're both received token then those who've buy the subscription are received a message by after validation which is "invalid signatures " because user2 got subscription and sometimes user1 isn't received a purchase token. 

I hope now you will understand. Kindly me tell me how i validate the purchase token that who is true buyer.

Thanks

**Comment by Bang9** [comment]
@iqbalfaisal I don't understand those situation

1. UserA and UserB has same Google Account, but different App Account and different Device.
2. UserA purchased Subscription
3. UserB getting Subscription rather than UserA -> I don't understand at this point, How to you know UserB getting Subscription or purchaseToken ??
4. Validate with purchaseToken of UserA(result of step2), then result is invalid signatures

Am I understand right?

**Comment by iqbalfaisal** [comment]
> 
> 
> @iqbalfaisal I don't understand those situation
> 
>     1. UserA and UserB has same Google Account, but different App Account and different Device.
> 
>     2. UserA purchased Subscription
> 
>     3. UserB getting Subscription rather than UserA -> I don't understand at this point, How to you know UserB getting Subscription or purchaseToken ??

Because i had tested this case with my two devices and i have consoled the result of both devices. 

> 
>     4. Validate with purchaseToken of UserA(result of step2), then result is invalid signatures

Yes, because UserB got the subscription before userA.

> 
> 
> Am I understand right?

Yes you are.

**Comment by Bang9** [comment]
@iqbafaisal I mean how to UserB get a token when UserA purchased subscription... you can get a purcase token without any actions in UserB device??? No refresh, No getPurchases, No purchase?
Please share your code and testing steps for reproduce.

**Comment by iqbalfaisal** [comment]
> @iqbalfaisal I mean how to UserB get a token when UserA purchased subscription... Can you get a purcase token without any actions in UserB device?? No refresh, No getPurchases, No purchase?

YES no refresh, no getPurchases and no purchase.

> Please share your code and testing steps for reproduce.

just copy from library example code.
[https://github.com/dooboolab/react-native-iap/tree/master/IapExample](url)

**Comment by Bang9** [comment]
@iqbalfaisal 

OK, Lets explain again

1. UserA purchase subscription
2. RNIap.purchaseUpdatedListener of UserA and UserB will generate purchase

Is it right?

**Comment by iqbalfaisal** [comment]
@Bang9 here is my code.

```
async createPurchaseListeners() {
   purchaseUpdateSubscription = purchaseUpdatedListener(
      async (purchase: InAppPurchase | SubscriptionPurchase) => {
        console.log('purchase', purchase);
        const receipt = purchase.transactionReceipt;
        if (receipt) {
          try {
            if (Platform.OS === 'ios') {
              Api.registerIOSSubscription(
                purchase.transactionId,
                purchase.transactionReceipt,
              )
                .then(res => {
                  finishTransaction(purchase);
                  this.props.whoAmI();
                })
                .catch(error => {
                  Toast.show(error, {
                    duration: Toast.durations.LONG,
                    position: Toast.positions.CENTER,
                  });
                });
              // finishTransactionIOS(purchase.transactionId);
            } else if (Platform.OS === 'android') {
              // If consumable (can be purchased again)
              // consumePurchaseAndroid(purchase.purchaseToken);
              // If not consumable
              // acknowledgePurchaseAndroid(purchase.purchaseToken);
              Api.registerAndroidSubscription(
                purchase.purchaseToken,
                purchase.transactionReceipt,
                purchase.signatureAndroid,
              )
                .then(res => {
                  finishTransaction(purchase);
                  this.props.whoAmI();
                })
                .catch(error => {
                  Toast.show(error, {
                    duration: Toast.durations.LONG,
                    position: Toast.positions.CENTER,
                  });
                });
            }

            // const ackResult = await finishTransaction(purchase);
          } catch (ackErr) {
            console.warn('ackErr', ackErr);
          }
        }
      },
    );
```

**Comment by iqbalfaisal** [comment]
>     2. `RNIap.purchaseUpdatedListener` of `UserA App` and `UserB App` will generate `purchase(with purchaseToken)`

@Bang9 I didn't understand what you are trying to asking. Did you mean that will both received purchaseToken? Answer is Yes both of receiving purchaseToken. I really appreciate your time and effort. 

Thanks

**Comment by Bang9** [comment]
@iqbalfaisal I think that is not general situation
nevertheless if you wanna handle the situation
you can validation purchaseToken only once in your server

0. [app] subscription your server data like premium membership state
(e.g. web socket, firebase.on, apollo.subscription)
1. [app] UserA purchase subscription
2. [app] UserA or UserB receive purchaseToken, 
3. [app] send transactionId(e.g.GPA.0000.0000.0000) and purchaseToken to server and save
 - one purchase has only one transaction id ( Android - order id / iOS - web_order_line_id )
3-1. [server] check the request of transactionId If transactionId is already in database, ignore the request
4. [server] receipt validation with purchaseToken, update server data(premium membership state), send data to subscribed clients
5. [server] UserA and UserB receive updated data then can access premium feature via `step.0 - subscription server`

**Comment by iqbalfaisal** [comment]
@Bang9 
what if `userB `send `transactionId `and `purchaseToken `to server before `userA`? Sever don't know who is true buyer.

**Comment by Bang9** [comment]
> @Bang9
> what if `userB `send `transactionId `and `purchaseToken `to server before `userA`? Sever don't know who is true buyer.

why need to know true buyer? Google Account is only one

**Comment by iqbalfaisal** [comment]
> why need to know true buyer? Google Account is only one, just update all users
hmm... i think there is no solution of this specific case.

**Comment by jeonghwanko** [comment]
For anyone still looking for a solution to subscription lifecycle notifications (cancel, renew, expire, refund) — you need a server that receives webhooks from Apple and Google.

I built an open-source Express middleware that handles this automatically:

```bash
npm install @onesub/server
```

```js
app.use(createOneSubMiddleware({
  apple: { bundleId: 'com.yourapp' },
  google: { packageName: 'com.yourapp', serviceAccountKey: process.env.GOOGLE_KEY },
  database: { url: process.env.DATABASE_URL },
}));
```

This creates two webhook endpoints automatically:
- `POST /onesub/webhook/apple` — receives App Store Server Notifications V2 (renewals, cancellations, refunds, grace period, etc.)
- `POST /onesub/webhook/google` — receives Google Real-Time Developer Notifications via Pub/Sub

Subscription state is updated in your database when these events arrive — your app just checks `GET /onesub/status?userId=xxx` to know if the user is still active.

No polling, no client-side checks. The server knows immediately when Apple/Google sends a notification.

GitHub: https://github.com/jeonghwanko/onesub
