### ISSUE TITLE
purchaseUpdatedListener not getting called in Production Environment working fine in Sandbox(iOS)

### ISSUE THREAD

**Issue by NMahendroo** [dooboolab/react-native-iap#909]
### Version of react-native-iap: 

> 4.0.7

### Version of react-native: 

> 0.59.9

### Platforms you faced the error (IOS or Android or both?): 

> iOS

### Expected behavior: 

> The listener should update about the Success

### Actual behavior: 

> Not getting called

### Tested environment (Emulator? Real Device?): 

> Real Device

### Steps to reproduce the behavior: 

> Make a purchase on Live Environment

**Comment by Akeuuh** [comment]
It seems that I have the same issue.

Everything works fine on android but when I test it on apple device, I can't get any product from the store. I have no errors in logs. 
The only weird thing are in the Xcode logs, I get some things as :
`nw_socket_handle_socket_event [C48148.1:1] Socket SO_ERROR [61: Connection refused]`

`nw_connection_get_connected_socket [C48148] Client called nw_connection_get_connected_socket on unconnected nw_connection`

`TCP Conn 0x28160ec40 Failed : error 0:61`

Does anyone have this problem? Solved this?

Thanks

**Comment by NMahendroo** [comment]
@Akeuuh I didn't face any connection problem like yours, but how are you calling it?
I might be able to help with respect to my implementation

**Comment by Akeuuh** [comment]
Hi @NMahendroo !

Thank you for your answer! 

I've solved my probleme late this night but it seems that it was not an error with the code. My products on App Store Connect where not fully set, I had not filled the part for review so my item were not valid.

Now that I've done it, everythings woks fine!

Hope you will find your answers!

**Comment by hyochan** [comment]
Looks like it can be closed
