### ISSUE TITLE
RNIap.getAvailablePurchases() return empty array [iOS]

### ISSUE THREAD

**Issue by davidwico** [dooboolab/react-native-iap#914]
### Version of react-native-iap
4.3.0

### Version of react-native
0.60.4

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
RNIap.getAvailablePurchases() should return non-consumable subscription

### Actual behavior
RNIap.getAvailablePurchases() returns empty array

### Tested environment (Emulator? Real Device?)
Real Device, debug mode, sandbox user

### Steps to reproduce the behavior
1. get available subscriptions: RNIap.getSubscriptions(itemSkus);
2. request RNIap.requestSubscription('product1')
3. handle purchase with listener 
RNIap.purchaseUpdatedListener(purchase => ... ) 
4. handle logic for purchase and finish it by calling RNIap.finishTransaction(purchase, false);
5. purchase successfull
6. get purchased products after next app run with RNIap.getAvailablePurchases() method
7. but it returns empty array 

I checked also other methods
RNIap.getPurchaseHistory()
RNIap.getPendingPurchasesIOS()
but they are also empty arrays

**Comment by Infokora** [comment]
same problem, someone solved this problem?

**Comment by davidwico** [comment]
In my case it was because I used non-renewable subscriptions, which is not supported by under hood Apple method restoreCompletedTransactions()

**Comment by hyochan** [comment]
@davidwico I am glad that you've solved out. Could you give a `PR` on the document if you think this should be written for others coming next?

**Comment by anastely** [comment]
@davidwico if I have Non-renewable subscription what the method should I use to 
-get purchases 
-buy one 
And should I make something in the backend?
