### ISSUE TITLE
Any sample code for monthly subscription?

### ISSUE THREAD

**Issue by ykcadcg** [dooboolab/react-native-iap#925]

**Comment by hyochan** [comment]
I've been planning for this but I am sorry that my time is running out today. I've not had a weekend for half a year. 😢

**Comment by creativemind1** [comment]
I have attempted to help you to code this for Android. It will work for you!
```
async componentDidMount() {
        try {
            await RNIap.initConnection();
           
        } catch (err) {
            console.warn(err.code, err.message);
        }        
    }

androidPayment = async () => {
const itemSkus = Platform.select({
    android: ['YOUR_SUBSCRIPTION_ID'],
});
        try {
            const subscriptions = await RNIap.getSubscriptions(itemSkus);
            if (subscriptions && subscriptions.length) this.requestPurchase(subscriptions[0].productId);
        } catch (err) {
            console.warn(err.code, err.message);
        }
    };

requestPurchase = async (productID) => {
        try {
            const results = await RNIap.requestPurchase(productID);
            console.log(results, '====results=====');
            if (results) RNIap.finishTransaction(results);
        } catch(e) {
            console.log(e);
        }
    }
```

**Comment by krissnawat** [comment]
For androids, a subscription is not fetching by getting product function is get only managed product
![image](https://user-images.githubusercontent.com/26294749/76526371-02a2f380-64a0-11ea-814d-1dd6b2fcb7ea.png)
anything I do wrong
![image](https://user-images.githubusercontent.com/26294749/76526434-164e5a00-64a0-11ea-9da4-429ea913096c.png)

**Comment by creativemind1** [comment]
Hello,

I noticed subsciptions doesnt work soon when you add, wait for 6-10 hours
and then try again.

**Comment by Great-hijack** [comment]
Hi @creativemind1 
Can you explain your case more detail? what do you mean by "....when you add..."?

**Comment by creativemind1** [comment]
Hello,

I meant when we add subscriptions in GooglePlay Console, it doesn't
reflects asap in the API but you have to wait for some time.
