### ISSUE TITLE
purchaseUpdatedListener is repeatedly called

### ISSUE THREAD

**Issue by cgathergood** [dooboolab/react-native-iap#926]
### Version of react-native-iap
4.3.0
### Version of react-native
0.60.5
### Platforms you faced the error (IOS or Android or both?)
Both
### Expected behavior

Following the example I want to call a custom method after my subscription has been purchased. It is my understanding that after acknowledging the purchase the listener should be removed? I have tried explicitly calling `remove` but had no success.

Example
```
 const purchaseListener = purchaseUpdatedListener(purchase => {
      const receipt = purchase.transactionReceipt;
      if (receipt) {
        callCustomEndpoint().then(result => {
          if(result){
            // Subscription is valid
            finishTransaction(purchase);
          }
        }) 
      };
      finishTransaction(purchase);
    });
```

### Actual behavior

The callCustomEndpoint() method is being called multiple times. How can I stop this from happening? As I only need to hit this endpoint once. 

I'm using a functional component instead of class component if it's important.

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by hyochan** [comment]
I am suspecting you've registered purchaseListener multiple times when component rerenders.

**Comment by cgathergood** [comment]
Thanks, I have since rewritten this using hooks so that it isn't called on each render. My mistake was trying to take the provided example in the docs of a class component and port it to a functional component. Great work on the library!

**Comment by wootwoot1234** [comment]
@cgathergood  I'm having this issue too.  Do you mind posting your event handler code using react hooks?

**Comment by osmantuna** [comment]
@cgathergood i would like to see code sample as well. i am little bit struggling with hooks.

**Comment by aravi365** [comment]
@wootwoot1234  @osmantuna  Can you please provide the event handler codes if you managed to fix it?
