### ISSUE TITLE
Test option: Slow credit card not appearing for testing pending transaction

### ISSUE THREAD

**Issue by chetan-plrch** [dooboolab/react-native-iap#928]
### Version of react-native-iap
4.4.0

### Version of react-native
0.61.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Slow credit card option should appear while testing purchases

### Actual behavior
Slow credit card option isn't appearing while testing purchases (only two options are available)
1. Test card, always approves
2. Test card, always declines
(My test region: India)

### Tested environment (Emulator? Real Device?)
Real Device - Redmi note 7 pro

### Steps to reproduce the behavior
1. Setup react-native-iap library on react native app
2. Setup play console with in-app subscription products for alpha testing
3. Click on buy to subscribe to any selected subscription
4. Options available are only two (always approve, always decline)

How do I test pending purchases without the option available ? Any idea ? Or am i missing something ?

And when does this happen (Transaction going into pending state)? Because we haven't come across enabling any cash transaction acceptance for subscription on play console.

**Comment by chetan-plrch** [comment]
@hyochan Any information on this ? Would be really helpful. Thank you

**Comment by hyochan** [comment]
Looks like this is related to https://github.com/android/play-billing-samples/issues/199.
It sounds like it varies on region and not the code itself.
