### ISSUE TITLE
How to properly use initConnection method

### ISSUE THREAD

**Issue by meteorra** [dooboolab/react-native-iap#930]
Could you please explain how to properly use initConnection method? When the application launches & before any other RNIap methods call? Do I need to analyze response from this method somehow? 
Thanks in advance

**Comment by AdamGerthel** [comment]
@meteorra Did you find the answer to your question? I'm wondering the same thing. The example in the readme doesn't even use it but the name `initConnection` implies that it's something that's basically required before doing anything else 🤷🏼‍♂️
