### ISSUE TITLE
[iOS] Crash in the native part if Sign-In With Apple ID is cancelled

### ISSUE THREAD

**Issue by dmitryusikriseapps** [dooboolab/react-native-iap#931]
### Version of react-native-iap
4.4.1
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
There shouldn't be any crashes
### Actual behavior
![image](https://user-images.githubusercontent.com/45354628/74334709-170da680-4da3-11ea-93dd-faa433dd3540.png)
![image](https://user-images.githubusercontent.com/45354628/74334711-19700080-4da3-11ea-976b-46ea202979a9.png)
![image](https://user-images.githubusercontent.com/45354628/74334718-1bd25a80-4da3-11ea-8e2a-8a07d12fe0f8.png)
### Tested environment (Emulator? Real Device?)
Emulator, Real Device
### Steps to reproduce the behavior
1) Use react-native-iap library functional
2) Wait for Sign-In With Apple ID dialog
3) Press cancel

**Comment by hyochan** [comment]
Could you kindly share some of your code?

**Comment by dmitryusikriseapps** [comment]
@hyochan Hey, sorry for the late response,
here is the part of code -> https://pastebin.com/iUhSJZWj
if you have any other questions, feel free to ask me

**Comment by lukebars** [comment]
You have to check if error isn't equal to "E_USER_CANCELLED", in which case you should ignore it.
