### ISSUE TITLE
Not recieving the product evry time

### ISSUE THREAD

**Issue by Akeuuh** [dooboolab/react-native-iap#932]
### Version of react-native-iap
4.2.1
### Version of react-native
0.59.9
### Platforms you faced the error (IOS or Android or both?)
Android

### Tested environment (Emulator? Real Device?)
Real device in production

I've installed and managed to get the lib to work. But I'm facing an issue on android.
The purchases are not catched 100% of the time. It means that when I go on my shop page in my app, I am not receiving the product each time from the store.

I don't why. Anyone has the same issue?

By the way, it seems to work well on iOS.

**Comment by hyochan** [comment]
Without any visible minimal reproduction, I can't help. I think we need to wait for others coming.

**Comment by kentdev92** [comment]
> ### Version of react-native-iap
> 4.2.1
> 
> ### Version of react-native
> 0.59.9
> 
> ### Platforms you faced the error (IOS or Android or both?)
> Android
> 
> ### Tested environment (Emulator? Real Device?)
> Real device in production
> 
> I've installed and managed to get the lib to work. But I'm facing an issue on android.
> The purchases are not catched 100% of the time. It means that when I go on my shop page in my app, I am not receiving the product each time from the store.
> 
> I don't why. Anyone has the same issue?
> 
> By the way, it seems to work well on iOS.

Same here.
I'm also tried to getSubscriptions and getProducts after initConnection.
Here is some pics config product on google console:

<img width="876" alt="Screen Shot 2020-02-17 at 5 13 16 PM" src="https://user-images.githubusercontent.com/17426288/74644464-e5cd1600-51a8-11ea-8fd3-59f86ace4f67.png">
<img width="847" alt="Screen Shot 2020-02-17 at 5 13 26 PM" src="https://user-images.githubusercontent.com/17426288/74644470-e82f7000-51a8-11ea-89b9-1375db47cf43.png">
And there is my code:

<img width="443" alt="Screen Shot 2020-02-17 at 5 16 22 PM" src="https://user-images.githubusercontent.com/17426288/74644687-3e9cae80-51a9-11ea-9ff3-d7119b494ba0.png">
<img width="449" alt="Screen Shot 2020-02-17 at 5 16 28 PM" src="https://user-images.githubusercontent.com/17426288/74644692-40667200-51a9-11ea-9821-ee017eaf175c.png">

All of those functions always return empty list
Even i have tested on Real Device(Samsung galaxy note 10+, Android 10).
@hyochan please help me if possible.

**Comment by hyochan** [comment]
This looks like one of the common issues.
Would this [thread](https://github.com/dooboolab/react-native-iap/issues/159#issuecomment-389413989) help? Have you done it?

**Comment by Akeuuh** [comment]
Hi, thanks for your answer.

No, it is no something like that. As I said, every thing works but not every time. 
It is possible to make purchase when all is clear, but the lib does not fetch the product information on every trigger.
You have to refresh multiple time the purchase page to get the informations.

Tell me what you want me to show and I'll do it very quickly!

PS: this appen only on Android.

PS: There is an other problem (only an Android). It seems that the lib is able to fetch only 20 items. I did worked around this issue by adding something on your java file.

**RNIapModule.java line 232**
_I added +1 after size() in the for loop. Did it quit randomly cause I don't do java, but it works_
`  @ReactMethod
  public void getItemsByType(final String type, final ReadableArray skuArr, final Promise promise) {
    ensureConnection(promise, new Runnable() {
      @Override
      public void run() {
        final ArrayList<String> skuList = new ArrayList<>();
      //!Here I did add +1 to get all my purchases
        for (int i = 0; i < skuArr.size()+1; i++) {
          skuList.add(skuArr.getString(i));
        }`

**Comment by creativemind1** [comment]
I have installed a latest version of this module. For me, `getProducts() `is working perfectly fine after adding them and I got results in less than 5 minutes. I'm getting empty results for `getSubscriptions`. It still not even 3 hours I added the subscription items, do I still have to wait more?

**Comment by creativemind1** [comment]
I've added the original email account of the owner in the licence testing field and that all went fine and now I'm able to get the subscription items. Good to see  that!

**Comment by Akeuuh** [comment]
Ok I solved my issue.
I was not to familiar with async await architecture so I did my research. Now that I understood it, I was able to make a good structure for my code.

It seems to work every where so problem solved.

Meanwhile there is still the issue with the limit of of item fetched on Android, but as I managed to get it work I close the issue.

**Comment by Mihai-github** [comment]
Hi,
    For me is I run this small example inside my app the initConnection returns true but for example getProducts does nothing. No error message, no console.log()... nothing and that's weird...

Code example: 

```
try {
            RNIap.initConnection().then(resp => {
                
                RNIap.getProducts(items)
                    .then(re => console.log(re))
                    .catch(e => console.log([e]));
            });
        } catch (err) {
            console.log(err);
        }
```
