### ISSUE TITLE
This in-app purchase has already been bought Alert though clearTransactionIOS method was used

### ISSUE THREAD

**Issue by meteorra** [dooboolab/react-native-iap#934]
### Version of react-native-iap
4.4.0
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
When buying several consumable products one by one, e.g. six new products, than 'This in-app purchase has already been bought' Alert appears & I'm not able to buy this product any more. I've tried to apply ``` clearTransactionIOS``` on application launch but it doesn't help. Any ideas how to fix that? Where is the proper place to call ``` clearTransactionIOS```?
### Actual behavior
"This in-app purchase has already been bought" doesn't appear & transaction is finished
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
- launch an application
- buy several consumable products. For several first products 'Success' alert appears, but for the lates 'This in-app purchase has already been bought' Alert appears. Though all the transactions are finished with ``` finishTransaction() ``` method. Also ``` clearTransactionIOS()``` is called on app launch

Thanks for help in advance

**Comment by hyochan** [comment]
Is your product `consumable`? Please check if you've created your product correctly in `itunesconnect`.

**Comment by meteorra** [comment]
Yep, it's consumable. Picture is attached. I'm already doing ```clearProductIOS``` once I'm fetching products.
Fetching products looks like this:
```javascript
function* purchasesSaga() {
try {
    yield call(initConnection)
    yield call(clearProductsIOS)
    const products: Product[] = yield call(getProducts, productSkus)
    const subscriptions: Subscription[] = yield call(getSubscriptions,subscriptionSkus)
    yield put(getInAppPurchasesSuccess({ products, subscriptions }))
} catch (e){}
}
```
<img width="940" alt="Screen Shot 2020-02-23 at 2 09 01 PM" src="https://user-images.githubusercontent.com/29917962/75111029-4dbaab00-5646-11ea-8def-2539167adde2.png">

**Comment by hyochan** [comment]
Please download `4.4.2` and see if it resolves the problem!
