### ISSUE TITLE
RNIap.getPurchaseHistory returns only the first purchase of an auto renewing subscription.

### ISSUE THREAD

**Issue by Karthik-B-06** [dooboolab/react-native-iap#942]
### Version of react-native-iap
Using react-native-iap v4.4.0
### Version of react-native
Using react-native v0.59.9
### Platforms you faced the error (IOS or Android or both?)
Android Only
### Expected behavior
Trying to get the purchase history using
`const purchaseHistory = await RNIap.getpurchasehistory(); `
And update my DB with the latest purchase details made by Google Play. 
iOS returns the whole purchase history made.
So I take the latest purchase by 
`const lastPurchaseDetails = 
purchaseHistory.sort(( a, b ) => b.transactionDate - a.transactionDate)[0];
`
### Actual behavior
But for android only the first purchase of the auto renewing subscription is returned by the RNIap.getPurchaseHistory method.
### Tested environment (Emulator? Real Device?)
Tested in Real Device.
### Steps to reproduce the behavior

1. Create an Auto Renewing subscription for 1 month in Google Play Console with/without a Trialing period
2. Add yourself as a licensed tester so that we get to test the subscription without using real cards.
3. Using RNIap request the purchase using the product SKU like this : 
`RNIap.requestPurchase('your_product_id')`

<img width="875" alt="Screenshot 2020-02-26 at 10 57 08 PM" src="https://user-images.githubusercontent.com/35562287/75370722-8d55f100-58eb-11ea-9e88-b1d2b234a99e.png">

> Note: Test subscriptions will renew a maximum of 6 times.

4. Based on the above info. At the end of 30 minutes, there should be 6 purchases done. Try to get the purchase history using 
`RNIap.getPurchaseHistory()`

5. The above would code only listed the 1st Purchase made for android. 

The array returned by iOS

`
[
{
   "transactionReceipt":"<receipt>",
   "transactionDate":<transaction_date>,
   "productId":"sub1_monthly",
   "transactionId":"300000553937461"
},
{
   "transactionReceipt":"<receipt>",
   "transactionDate":<transaction_date>,
   "productId":"sub1_monthly",
   "transactionId":"3000005578937461"
}
]
`

The array returned in Android

`
[
{
   "autoRenewingAndroid":true,
   "isAcknowledgedAndroid":true,
   "purchaseStateAndroid":1,
   "signatureAndroid":"...",
   "developerPayloadAndroid":"",
   "purchaseToken":"",
   "orderId":"GPA.31321-0322-1818-312341",
   "transactionReceipt":"{receiptId: ... ... }",
   "transactionDate":1581644006609,
   "transactionId":"GPA.3332-0322-1818-48628",
   "productId":"sub1_monthly"
}
]
`

**Comment by nochkin** [comment]
I did not tried, but I think Android updates the orderId instead of creating multiple purchases.
For example, the first purchase is GPA.31321-0322-1818-312341, the next one will be GPA.31321-0322-1818-312341..1 and so on.

**Comment by prasanna1211** [comment]
@nochkin I am also getting the same issue. You are correct, but the orderId is not available in the purchases available. There is always a single purchase with the following fields developerPayload,
signatureAndroid, purchaseTime, developerPayload, transactionDate, productId. But none of them are pointing the order ID. I managed to make it work by hitting the [Android subscriptions API](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get) to get the latest details.

**Comment by nochkin** [comment]
I see what you mean. Yes, I do something similar using signareAndroid and getting the reset of the information from Google using their API.

**Comment by Oguntoye** [comment]
> 
> 
> @nochkin I am also getting the same issue. You are correct, but the orderId is not available in the purchases available. There is always a single purchase with the following fields developerPayload,
> signatureAndroid, purchaseTime, developerPayload, transactionDate, productId. But none of them are pointing the order ID. I managed to make it work by hitting the [Android subscriptions API](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get) to get the latest details.

please how do you generate the token required.. I keep getting this message 
Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project

while testing with postman

**Comment by Oguntoye** [comment]
> 
> 
> @nochkin I am also getting the same issue. You are correct, but the orderId is not available in the purchases available. There is always a single purchase with the following fields developerPayload,
> signatureAndroid, purchaseTime, developerPayload, transactionDate, productId. But none of them are pointing the order ID. I managed to make it work by hitting the [Android subscriptions API](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get) to get the latest details.

Can you please explain how you went about it.. I need this so badly.. Didnt know if I'm supplying the right token or not.. please explain how you go about running the android subscription API.. was it at your server end or through your reach native APP. in either case.. Kindly please help with explanation
