### ISSUE TITLE
Receipt Validation trouble

### ISSUE THREAD

**Issue by drews256** [dooboolab/react-native-iap#948]
### Version of react-native-iap
4.4.2
### Version of react-native
61.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
When logging in and attempting to validate the receipt we start by getting receipt data by calling:

getReceiptIOS()

this always returns receiptData consistently.

We then push this off to our backend for validation. 

We are validating receipts properly and falling back to the test environment on status 21007 properly.
All our receipts running from local builds or via testflight are sandbox receipts which makes sense. 

Expected behavior is that if I have subscribed to a IAP and have the receipt from calling getReceiptIOS() it is consistently validatable for the expected time frame (we are accounting for the sandbox time frames).

### Actual behavior

For some users though, it seems as if the receipt is changing or incorrect in between validation attempts. We are subscribing, closing the application, then reopening the application and the receipt is invalid, but if we go to subscribe to an IAP we get a pop up modal that says 

"You're currently subscribed to this."

Our purchase listener gets a receipt and we are on our marry way. 

Why do I have to "re"subscribe to get my receipts to validate?

## Tested environment (Emulator? Real Device?)

Real device. iPad and iPhone 11.

**Comment by hyochan** [comment]
Hey there! Is there any traction wit this issue? Please share how are you going.
Also, have you correctly finished transactions?

**Comment by drews256** [comment]
Sure, the process we have set up right now goes:

1. Read receipt
2. If they do not have a valid receipt take them to the subscription page
3. Display the possible IAP subscriptions
4. Make a purchase
5. Clear all transactions (as this should finish all transactions right?)
6. Start at 1

We are seeing some inconsistency on loop 2 where we go back to read the receipt and it's about 50/50 on the receipt either recognizing a purchase was made or not. Which causes us to show them the subscription page again.
