### ISSUE TITLE
Call getReceiptIOS on mount?

### ISSUE THREAD

**Issue by abraztsov** [dooboolab/react-native-iap#952]
Should I call `getReceiptIOS` on app launch to validate the current user subscription? If I'm not saving and checking subscription receipt on the backend.

**Comment by hyochan** [comment]
I don't think you should. I've only managed to validate receipt once the purchase is succeeded. You may save other info in local database or backend. I recommend not to rely purchase histories in the Apple server because I didn't feel reliable.
