### ISSUE TITLE
Navigating from react-native-app to playstore for cancelling in-app Subscriptions using particular url doesn't work

### ISSUE THREAD

**Issue by LohithaYalavarthi** [dooboolab/react-native-iap#958]
### Version of react-native-iap
2.4.8

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior
When  using this url to navigate to playstore subscription page from react native app it should be able to navigate it
        'https://play.google.com/store/account/subscriptions?package='dummypackage'&sku=box100.subscription.dev' and using the linking api of react-native 

Instead It can only  navigate using 'https://play.google.com/store/apps/details?id=packagename'

### Actual behavior
'https://play.google.com/store/account/subscriptions?package='dummypackage'&sku=box100.subscription.dev' and using the linking api of react-native

this url doesnt work

### Tested environment (Emulator? Real Device?)
Android Oppo 5s

### Steps to reproduce the behavior
Use the code below
navigateToPlaystore = productId => {
    console.log('getDevicePlatform() :', getDevicePlatform(), productId)
    let url = ''
    if (getDevicePlatform() === 'android') {
      url =
        'https://play.google.com/store/account/subscriptions?package=com.peerzacademy.peertutor.dev&sku=box100.subscription.dev'
        } else if (getDevicePlatform() === 'ios' && Platform.version >= 12) {
      url = 'https://apps.apple.com/account/subscriptions'
    } else {
      url =
        'https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/manageSubscriptions'
    }
    Linking.canOpenURL(url)
      .then(supported => {
        if (!supported) {
          console.log("Can't handle url: " + url)
        } else {
          return Linking.openURL(url)
        }
      })
      .catch(err => console.error('An error occurred', err))
  }

**Comment by erickgtzh** [comment]
were you able to navigate to your in-app Subscriptions from react native??
