### ISSUE TITLE
upgraded react-native-iap from 2.4.8 to 4.1.1 and after that trying to install the app in the device  results the issue

### ISSUE THREAD

**Issue by LohithaYalavarthi** [dooboolab/react-native-iap#959]
### Version of react-native-iap
2.4.8->4.1.1
### Version of react-native
0.59.10
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior

 After upgrading the react-native-iap version Should be able to install the app in my device using react-native run-android 

### Actual behavior
<img width="974" alt="Screenshot 2020-03-24 at 1 59 46 PM" src="https://user-images.githubusercontent.com/42953972/77404491-d2c8e980-6dd7-11ea-88c3-46d6facd3e5f.png">
After upgrading the react-native-iap version I am unable to install the app in my device using react-native run-android I am facing the above issues
Should be able to install the app succesfully with out error 

### Tested environment (Emulator? Real Device?)
Android oppo 5s
### Steps to reproduce the behavior
1)Upgrade the react-native-iap@4.1.1  from react-native-iap 2.4.8 version for   react-native 0.59.10 version
2) try to run react-native run-android

**Comment by hyochan** [comment]
Looks like you are having issue on `androidx` migration. Try to install `jetifier` and run `npx jetify` after installation. Reference is [here](https://github.com/mikehardy/jetifier)
