### ISSUE TITLE
Error getAvailablePurchases() 

### ISSUE THREAD

**Issue by Emberice86** [dooboolab/react-native-iap#96]
### Actual behavior Receive next Error: 
{
framesToPop:1,
code: E_NOT_PREPARED,
line:135,
column:4004,
sourceURL:"index.android.bundle"
}

### Steps to reprodue the behabior 
try {
    const purchases = await RNIap.getAvailablePurchases();
    let purchase = '';
    purchases.forEach(p => {
      if (p.productId === PREMIUM_ANDROID_SUBSCRIBE_ID) {
        purchase = PURCHASED;
      }
    });
    return purchase;
  } catch (err) {
    showAlert('ERROR getAndroidPurchases', JSON.stringify(err));
    return '';
  }
};

**Comment by neilco** [comment]
@Emberice86 Did you call `await RNIap.prepare()` before calling `await RNIap.getAvailablePurchases()`?

**Comment by Emberice86** [comment]
Man, thanks a lot! I absolutely forgot about this! You saved my time!
