### ISSUE TITLE
Can not getProducts iOS simulator

### ISSUE THREAD

**Issue by ajouve** [dooboolab/react-native-iap#962]
### Version of react-native-iap

4.4.3

### Version of react-native

0.62.0

### Platforms you faced the error (IOS or Android or both?)

iOS

### Expected behavior

Get products information from apple server

### Actual behavior

`[Error: An SSL error has occurred and a secure connection to the server cannot be made.]`

### Tested environment (Emulator? Real Device?)

Emulator

### Steps to reproduce the behavior

The product is created but not submited

```js
        import * as InAppPurchases from 'react-native-iap';

        InAppPurchases.initConnection()
        .then( canMakePayments => {
            console.log(canMakePayments);
            return InAppPurchases.getProducts(['com.xxx.xxx.abo'])
        })
        .then(result => {
            console.log(result);
        })
        .catch(err => {
            console.log(err);
        })
```

`canMakePayments` is `true`

but `getProducts` catch with `[Error: An SSL error has occurred and a secure connection to the server cannot be made.]`

**Comment by nenjamin2405** [comment]
Any solution for this @ajouve?

**Comment by hyochan** [comment]
Would adding below to `info.plist` help? I don't quite think this is `iap` problem rather I feel your backend uses `http`. Am I right?
```
<key>NSAppTransportSecurity</key>
  <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
  </dict>
```

**Comment by ajouve** [comment]
Seems that the Apple developers endpoints has problems.
I added a retry logic and it works.

**Comment by anastely** [comment]
@ajouve I'm trying to use `getAvailablePurchases()` but in everytime i sign in in sandbox account i got this error

> Cannot connect to iTunes Store
And after research, i see this :( https://forums.developer.apple.com/thread/113343

So how you test in a simulator?

**Comment by socheat1994** [comment]
Yes. How can you test on simulator?.🤔 is it possible?
