### ISSUE TITLE
Understanding the developer mode / sandbox in iOS

### ISSUE THREAD

**Issue by matheuscouto** [dooboolab/react-native-iap#963]
In production apps when I try to use the IAP in iOS, it opens up an interface to conclude my purchase, but when I'm using this lib in development it opens up a series of alerts. Is this only in development? If I publish the app will it appear Apples interface for IAP?

I haven't found this answer in the docs or other issues.

Thanks in advance

**Comment by hyochan** [comment]
@matheuscouto You may face them in development. There are great investigations in #863 for your further reading.
