### ISSUE TITLE
[Android] Getting "purchase is not suitable to be purchased"

### ISSUE THREAD

**Issue by drbarto** [dooboolab/react-native-iap#964]
RN: 0.61.5
RNIap: 4.4.3
Platform: Android
Expected: calling `finishTransaction` succeeds
Actual: `finishTransaction` fails with "purchase is not suitable to be purchased"
Test env: real device

I'm integrating RNIap into a new app (so no real-world experiences yet) in order to purchase a non-consumable product. The iOS part works fine, but on Android I recently started to consistently get the error "purchase is not suitable to be purchased" when calling `RNIap.finishTransaction`.

Looking at [the code](https://github.com/dooboolab/react-native-iap/blob/master/index.ts:438), this indicates that my purchase is not considered to be purchased (`!purchase.isAcknowledgedAndroid && purchase.purchaseStateAndroid === PurchaseStateAndroid.PURCHASED` is `false`).

I'm pretty sure that my general setup (product id, native app configuration, etc.) is correct because a) the process works on iOS and b) it also used to work on Android until recently. 

Some additional background: when starting the app in test mode I try to clean up any leftover data by following [resolve unacknowledged purchase](https://github.com/dooboolab/react-native-iap/issues/828#issuecomment-549084888) and [consume owned items to avoid "already owned" error](https://github.com/dooboolab/react-native-iap/issues/126#issuecomment-439084872). Disabling those calls did not make a difference though.

Anyone has a hint what might be wrong in my setup?

**Comment by drbarto** [comment]
I found a workaround: before calling `finishTransaction`, I re-fetch the purchase object with `RNIap.getAvailablePurchases`. This updates the relevant properties (`isAcknowledgedAndroid`, `purchaseStateAndroid`) so that `finishTransaction` succeeds again. Is this expected behaviour?

**Comment by drbarto** [comment]
Ok, found the problem: I accidentally stripped the Android-specific properties from the purchase object, that's why re-fetching solved my problem. Now, after getting rid of this code, all works as expected 👍

**Comment by haikov** [comment]
@drbarto can you please share a bit more details regarding your fix? I started seeing same errors in the crash reporting tool, but they're not consistently happening and I'm unable to reproduce them locally 🤔

**Comment by drbarto** [comment]
@haikov sorry, but my "fix" is for sure not applicable to you. I have a helper function which converts the purchase JSON data which I receive from RNIap to something our backend can digest, and in this function I accidentally forgot to copy some Android-specific data fields.

**Comment by sbrighiu** [comment]
'purchase is not suitable to be purchased' I see this too for old test payments. I cannot call finish transaction on them.

**Comment by AdamGerthel** [comment]
@haikov @sbrighiu Same for me. Found any solutions?

**Comment by sbrighiu** [comment]
https://github.com/dooboolab/react-native-iap/issues/1092

**Comment by roots-ai** [comment]
Is this in any case related to function params changed to object. Do we have to pass any kind of object in the `finishTransaction ` method? 
Wish there was a better documentation.
