### ISSUE TITLE
duplicate payments

### ISSUE THREAD

**Issue by tarahiw** [dooboolab/react-native-iap#965]
Hi my friends
First of all, I'm sorry, my first language is not English
Example: A user's scenario buys a one-month subscription today
Can he buy again by mistake tomorrow? Or does your system intend to prevent this? Or do I have to deactivate the purchase button myself until that person's credit expires?
I am generally concerned about duplicate payments or the purchase of shared or non-shared subscriptions, but at the same time I am on behalf of the user. Explain who you or we want to prevent from doing this?

Now, if I was in a production environment, would it mean that the user could buy all these purchases in a row?

const getAvailablePurchases = async () => {
try {
setProcessing(true);
console.info(
'Get available purchases (non-consumable or unconsumed consumable)',
);
const purchases = await RNIap.getAvailablePurchases();
const purchasesMap = purchases.map((product) => {
return product.productId;
});
console.log('Available purchases :: ', purchasesMap);
if (purchases && purchases.length > 0) {
setAvailableItemsMessage(purchasesMap);
// setAvailableItemsMessage({
// availableItemsMessage: Got ${purchases.length} items.,
// receipt: purchases[0].transactionReceipt,
// });
setProcessing(false);
}
} catch (err) {
console.warn(err.code, err.message);
Alert.alert(err.message);
setProcessing(false);
}
};
LOG =
Available purchases :: ["com.example.monthly", "com.example.monthly", "com.example.yearly", "com.example.yearly", "com.example.yearly", "com.example.monthly", "com.example.monthly", "com.example.yearly", "com.example.monthly", "com.example.monthly", "com.example.monthly", "com.example.monthly", "com.example.yearly", "com.example.yearly", "com.example.yearly", "com.example.monthly"]

<img width="1400" alt="Screen Shot 2020-04-07 at 12 44 39 PM (2)" src="https://user-images.githubusercontent.com/53799546/78646225-f9a21800-78cd-11ea-97c0-348de9e7d71b.png">

**Comment by hyochan** [comment]
@tarahiw I think you need to test it out yourself for better confidentiality. If the user is already subscribed to `skus` and try to purchase it again, `ios` and `android` should handle them and respond with error something like `user is already subscribed` blablabla.

**Comment by tarahiw** [comment]
Hi, I didn't understand
Should I finally stop this from happening me? Your library or Apple?

**Comment by tarahiw** [comment]
> @tarahiw I think you need to test it out yourself for better confidentiality. If the user is already subscribed to `skus` and try to purchase it again, `ios` and `android` should handle them and respond with error something like `user is already subscribed` blablabla.

Hi, I didn't understand
Should I finally stop this from happening me? Your library or Apple?
