### ISSUE TITLE
Missing originalTransactionIdentifierIOS

### ISSUE THREAD

**Issue by vietvuong1994** [dooboolab/react-native-iap#966]
### Version of react-native-iap
4.4.2
### Version of react-native
0.61.5

I use the originalTransactionIdentifierIOS to distinguish users subscribe auto-renewal IAP from IOS. After listen subscribe success and call finishTransactionIOS, I call getPurchaseHistory to get the originalTransactionIdentifierIOS from the first item of array response and send it to server.
 At Production environment I got some log from server not have originalTransactionIdentifierIOS but testing at sandbox environment is ok and I can't reappear this issue.
Anyone have the same Issue like me and know how to resolve it?

**Comment by Jobeso** [comment]
When testing I noticed `originalTransactionIdentifierIOS` was missing on the first purchase. Then only `transactionId` is defined, so you can just do `originalTransactionIdentifierIOS || transactionId`. 
If you want to distinguish between iOS and Android you can just use `Platform.OS === 'ios'`. Maybe I did not understand what you want to achieve. Can you specify again?

**Comment by rns4731** [comment]
+1 this was unexpected behavior. From the apple docs, I expected to receive the same value for both `transactionId` and `originalTransactionIdentifierIOS` 
https://developer.apple.com/documentation/appstorereceipts/original_transaction_id
