### ISSUE TITLE
Promoted IAP doest work on react-native 61.5

### ISSUE THREAD

**Issue by punjasin** [dooboolab/react-native-iap#971]
### Version of react-native-iap 
4.4.2
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
test link work
itms-services://?action=purchaseIntent&bundleId=com.example.app&productIdentifier=com.example.app.productid
### Actual behavior
nothing happen 
in Xcode Log it show
[Daemon] [SKPaymentQueue]: Tried to send purchase intent: {com.example.app.productid} to delegate, delegate does not respond to method
### Tested environment (Emulator? Real Device?)
IOS Real Device Iphone XR
### Steps to reproduce the behavior
create new project 
install react-native-iap
add listener according to example
open test link

**Comment by punjasin** [comment]
i found solutions by remove the comment code in library out and it work

**Comment by hyochan** [comment]
I hope you to check [this one](https://github.com/dooboolab/react-native-iap/issues/950#issuecomment-613295586) out! 

@punjasin Also, do you mind updating our readme to put the above code in `viewDidLoad` in post-installation section?
