### ISSUE TITLE
No purchases found At Android Emulator

### ISSUE THREAD

**Issue by k8759102** [dooboolab/react-native-iap#972]
### Version of react-native-iap
^4.4.3

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
consumeAllItemsAndroid()
getProducts()
=> ProductList [...]

### Actual behavior
consumeAllItemsAndroid()
=> promise.reject("refreshItem", "No purchases found");
      ProductList []

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior

After creating the ID of the product currently managed by Google Play, the above operation was performed.
I expected to get the product list normally, but I couldn't find the product.
Is it possible to test only in the alpha test and not in the emulator?

=====================================================================

현재 구글플레이에서 관리되는 제품의 ID를 생성한 후, 위와 같은 동작을 시행하였고,
정상적으로 상품리스트를 가져올 것으로 예상했으나 상품을 찾아오지 못하였습니다.
혹여 알파테스트에서만 테스트가 가능하고 에뮬레이터 상에서는 테스트가 불가능 한 것인지요?

**Comment by hyochan** [comment]
Hey there~! You can only test the `IAP` features in the real device for `android`. In `iOS`, it is similar but they can only fetch products in the emulator.

P.S. I hope you share things in English so other people can understand the issues which can be related to their problems.

**Comment by k8759102** [comment]
Ok, I modified my Issue
I appreciate your comment
