### ISSUE TITLE
call RNIap.initConnection() return undefined

### ISSUE THREAD

**Issue by auzankyu** [dooboolab/react-native-iap#973]
### Version of react-native-iap
4.4.2
### Version of react-native
61.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
some return
### Actual behavior
undefined 
### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior
when i call RNIap.initConnection() in componentDidMount it return undefined
so i cannot get RNIap.getProducts()

**Comment by auzankyu** [comment]
solved when installing react-native-iap from Podfile

**Comment by yasikrehman** [comment]
> solved when installing react-native-iap from Podfile

how could i solve this in android ?
