### ISSUE TITLE
Free Trial IOS

### ISSUE THREAD

**Issue by tarahiw** [dooboolab/react-native-iap#974]
### Version of react-native-iap
^4.4.3

### Version of react-native
61.5

### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior

expectation
[
{
    bundleId: <string>,
    transactionId: <string>,
    productId: <string>,
    purchaseDate: <number>,
    quantity: <number>,
    *expirationDate: <number>,
    *isTrialPeriod: <boolean>,              // only for subscriptions and if extented = true
    *isInIntroOfferPeriod: <boolean>,       // only for subscriptions and if extented = true, since v1.5.1
    *environment: <string>,                 // only if extented = true
    *originalPurchaseDate: <number>,        // only if extented = true
    *applicationVersion: <string>,          // only if extented = true
    *originalApplicationVersion: <string>   // only if extented = true
},
...
]

### Actual behavior

Reality
[
  {
    transactionId: '1000000651488382',
    originalTransactionId: '1000000647837650',
    bundleId: 'example',
    productId: 'com.example',
    purchaseDate: 1586849946000,
    expirationDate: 1586850246000,
    quantity: 1,
    isTrialPeriod: false,
    isInIntroOfferPeriod: false,
  }
]

### Tested environment (Emulator? Real Device?)
Real Device sandbox env
### Steps to reproduce the behavior

I went through the following steps correctly, but in this test, buying a negative answer is isTrialPeriod true to be false

https://stackoverflow.com/questions/12297342/how-to-set-up-in-app-purchase-free-trial-period-in-ios-app

**Comment by ue** [comment]
for my case, the text does not display as like 3 days free after 3 days it will be xxx$ for the month, etc.
I just created an in-app purchase item then set a promo offer for that sku. but it seems a normal subscription offer in sandbox mode.

Is there any specific thing to do for the free trial period?

**Comment by Jobeso** [comment]
You can check if your product has the correct keys for the free trial. Also note that a user is only one time eligible for a free trial, this also applies to test users.

**Comment by dhyey001** [comment]
@tarahiw, I face the same issue now. So please guide me how to fix this issue. Thanks.
