### ISSUE TITLE
Subscribing promoted product [IOS] [HELP WANTED]

### ISSUE THREAD

**Issue by ue** [dooboolab/react-native-iap#978]
Hi guys,

I created in-app purchases successfully all set except for my free trial product (promoted product).

I created that subscription as 6 months also set 3 days free trial as the promoted product is coming with that product data as `discounts` coming as an array. Then I created my UI when pressing the buttons it is trying to subscription via productID. For the 6 months product which has a discount (free trial) it **does not display**  as _3 days free after 3 days it will be xxx$ and start date after 3days etc._ 

Should I do any specific thing for the free trial product text displaying product?

Note: I am done with that [How can I handle promoted](https://github.com/dooboolab/react-native-iap#how-do-i-handle-promoted-products-in-ios) but still same.

Anyone can help me I will be grateful

**Comment by ue** [comment]
That's my fault it should be an introductory offer :( sorry for that. closing now

**Comment by lc3t35** [comment]
@ue could you please detail how did you handle introductory offer and promoted **subscription** (not product) offer ?

**Comment by ue** [comment]
@lc3t35 Hi, I created a quick variable for a free trial on ios is;

`const isFreeTrial = item.introductoryPricePaymentModeIOS === 'FREETRIAL';`

for Android there is an item which is coming from the product object is `freeTrialPeriodAndroid` you can check that out as well.

`const isFreeTrial = item.introductoryPricePaymentModeIOS === 'FREETRIAL' || item.freeTrialPeriodAndroid === 'P3D';`

I don't know it seems kind of a workaround but I just find that way on my own and it works as expected.
