### ISSUE TITLE
successful purchase not fired in purchaseUpdatedListener

### ISSUE THREAD

**Issue by AndyYudkin** [dooboolab/react-native-iap#982]
Thanks for great package and sorry for my English.
### Version of react-native-iap
4.4.4
### Version of react-native
0.60.3
### Platforms you faced the error (IOS or Android or both?)
iOS
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior

I try to buy subscription. Enter password and commit. But has not event in purchaseUpdatedListener.
If I return 
 [[SKPaymentQueue defaultQueue] addTransactionObserver:self];
in RNIapIos.m - that's OK!

I tried add 
[IAPPromotionObserver startObserving];
in didFinishLaunchingWithOptions - but I has't any effect.

**Comment by hyochan** [comment]
@AndyYudkin Thanks for the issue and I am suspecting it causes by the last releases trying to fix the #950. I've just pushed a [new commit with release 4.4.5](https://github.com/dooboolab/react-native-iap/commit/c50ef1e156dd62c89e629c67caa952b2cd702113). Could you try this and come back?

**Comment by AndyYudkin** [comment]
@hyochan I was install 4.4.6 and that's OK!

**Comment by hyochan** [comment]
So this is resolved~!
