### ISSUE TITLE
Do we still need developer payload android

### ISSUE THREAD

**Issue by zeritte** [dooboolab/react-native-iap#986]
### Version of react-native-iap
4.4.6

### Version of react-native
0.61.4

### Question?
Thank you for creating this awesome library. I was able to follow steps and create my desired output easily. `We are willing to share same in-app-purchase experience for both Android and iOS.` You achieved to do!
Do we still need to put `developerPayloadAndroid` in `finishTransaction(purchase: InAppPurchase/ProductPurchase, isConsumable?: boolean, developerPayloadAndroid?: string)`. Since the library is changing and growing day by day, I wanted to make sure. And looks like google does not support it [anymore](https://developer.android.com/google/play/billing/developer-payload).
My plan is to validate receipts in a server like this https://github.com/mifi/in-app-subscription-example

**Comment by zeritte** [comment]
@hyochan can you have a look at this

**Comment by zeritte** [comment]
as far as I understood, https://github.com/mifi/in-app-subscription-example/blob/master/in-app-subscription-backend-example/index.js#L135 having something like that will do the same. so there is no need for developerPayloadAndroid. Is it true?

**Comment by hyochan** [comment]
I'm also knowing this to be the legacy field but they are not completed moved away although deprecated. I just exposed those variables.

**Comment by zeritte** [comment]
so its fine not to put it?

**Comment by hyochan** [comment]
@zeritte Yes this is optional I think.

<img width="1171" alt="Screen Shot 2020-04-25 at 5 35 07 PM" src="https://user-images.githubusercontent.com/27461460/80275271-230ad280-871b-11ea-8fbc-1dd626823f17.png">
