### ISSUE TITLE
After upgrading react-native-iap 4.4.7 version in ios -getAvailablePurchases() not responding and other methods also not working in ios

### ISSUE THREAD

**Issue by tarunkasera** [dooboolab/react-native-iap#988]
### Steps to reproduce the behavior - with 4.4.3 it's working but after upgrading the version 4.4.7 in ios it's not working and also i have test in android it's working.

Could you please help me on this my app in production and i need to update it asap.

Please help me

**Comment by hyochan** [comment]
Can you verify you've called `initConnection` in `iOS` just as in `android`?

**Comment by hyochan** [comment]
I've just ran the code in our example project and please check `IapExample` code either.

**Comment by tarunkasera** [comment]
**Can you verify you've called initConnection in iOS just as in android?**

Yes we have called initConnection in both iOS and Android and it was not working and then I have downgrade my version from 4.4.7 to 4.4.3.

After downgrading version now we are facing issue with purchaseUpdatedListener in android , it's calling every time but it need to call when I am taking subscriptions.
In ios it's working correct but in android not.

Could you please help me on this.
Thanks.

**Comment by hyochan** [comment]
> **Can you verify you've called initConnection in iOS just as in android?**
> 
> Yes we have called initConnection in both iOS and Android and it was not working and then I have downgrade my version from 4.4.7 to 4.4.3.
> 
> After downgrading version now we are facing issue with purchaseUpdatedListener in android , it's calling every time but it need to call when I am taking subscriptions.
> In ios it's working correct but in android not.
> 
> Could you please help me on this.
> Thanks.

Have you run `pod install` after installing a new package? I just can't understand why `4.4.7` isn't working. Could you compare the code with the `IapExample` or share some of yours?

**Comment by tarunkasera** [comment]
Yes I have run pod install after installing new package and it's not working properly and I will share the detailed code but for now can you please help me for purchaseUpdatedListener is running every time in android

**Comment by GuilhermeGabriel** [comment]
I'm with the same problem...

**Comment by hyochan** [comment]
Have you guys also called `endConnnection` when you've finished using `billing` functionalities?

**Comment by GuilhermeGabriel** [comment]
I already solved it, the problem was not having called acknowledgePurchaseAndroid and finishTransaction after first buy.

**Comment by aalasolutions** [comment]
@GuilhermeGabriel this was about IOS, your issue was about android... so it dosnt good to mention this here :)

**Comment by jackcb123** [comment]
I had this same problem and fixed it with the initConnection and endConnection. Thanks for the help!
