### ISSUE TITLE
error: 'IAPPromotionObserver.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by gurol** [dooboolab/react-native-iap#989]
### Version of react-native-iap
4.4.4, 4.4.5, 4.4.6, 4.4.7
### Version of react-native
0.59.10
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Successful build
### Actual behavior
Could not be built even after (removing temp directories such as node_modules, ios/build, ~/Library/Developer/Xcode/DerivedData, ...)

`info [APPPATH]/node_modules/react-native-iap/ios/IAPPromotionObserver.m:10:17: warning: class 'IAPPromotionObserver' does not conform to protocol 'SKPaymentTransactionObserver' [-Wprotocol]
@implementation IAPPromotionObserver
                ^
[APPPATH]/node_modules/react-native-iap/ios/IAPPromotionObserver.m:10:17: note: add stubs for missing protocol requirements
@implementation IAPPromotionObserver
                ^
1 warning generated.

info 

info [APPPATH]/node_modules/react-native-iap/ios/RNIapIos.m:4:9: **error: 'IAPPromotionObserver.h' file not found with <angled> include; use "quotes" instead**
#import <IAPPromotionObserver.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~
        "IAPPromotionObserver.h"
**1 error generated**.

info 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening [AppName].xcodeproj

The following build commands failed:
    CompileC [APPPATH]/ios/build/OkuPokus/Build/Intermediates.noindex/RNIap.build/Debug-iphonesimulator/RNIap.build/Objects-normal/x86_64/RNIapIos.o RNIapIos.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
. Run CLI with --verbose flag for more details.`

### Tested environment (Emulator? Real Device?)
Both Emulator and Real Device

**Comment by gurol** [comment]
I have fixed the error by making the following change in node_modules/react-native-iap/ios/RNIapIos.m file:

`#import <IAPPromotionObserver.h>`
to
`#import "IAPPromotionObserver.h"`

**Comment by hyochan** [comment]
Fixed in `4.4.8`. However, I'm not quite sure why this wasn't a problem in my `env`.
