### ISSUE TITLE
Linking the purchase with the user

### ISSUE THREAD

**Issue by mohammedavez** [dooboolab/react-native-iap#991]
The problem is I am using my own authentication system for my app so how do I link the purchase with the user.I tried to give developerIdAndroid and accountIdAndroid as parameters to requestPurchase function but I don't see those 2 parameters are liked with the purchase object from purchaseUpdateListener.

**Comment by nochkin** [comment]
If you do server validation, you could pass the purchase token along with the user information to your server and store it linked in the database.

**Comment by tomerdev** [comment]
I'm using [react-native-iaphub](https://github.com/iaphub/react-native-iaphub) which does the receipt validation for you, it's easy to link with the user, you just have to provide an user id.

**Comment by mohammedavez** [comment]
@nochkin thanks for the reply,I am doing server validation but how do you pass user information and there is one problem that I am facing, lets suppose a user has two accounts and lets suppose that user has purchased something from A account and lets suppose that purchase takes time to complete then in the mean time the user login's into his B account then if the purchase got completed at that time then the B account gets credited.

This can be solved only when we pass some id of the user while running requestPurchase function and that user id should be in purchase object so by this even if the user login's into another account we can validate.

**Comment by mohammedavez** [comment]
> I'm using [react-native-iaphub](https://github.com/iaphub/react-native-iaphub) which does the receipt validation for you, it's easy to link with the user, you just have to provide an user id.

**Comment by mohammedavez** [comment]
@tomerdev thanks for the reply, I will check that out

**Comment by nochkin** [comment]
@mohammedavez 
If you do server validation, then you pass userid with the receipt together. Your server would link the purchase with that userid on the server side.
Does not matter if a user will re-login or even logout after the fact since the validation is done on the server side anyway.
