### ISSUE TITLE
iOS Receipt Lost - Don't get saved in DB

### ISSUE THREAD

**Issue by creativemind1** [dooboolab/react-native-iap#993]
### Version of react-native-iap
"react-native-iap": "^4.4.1",

### Version of react-native
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
(ExpoKit)

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
How to get last receipt Trasaction (only one).

### Actual behavior
Get latest and active one transaction receipt details (JSON)

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
After calling `await RNIap.requestPurchase(productID);` and getting payment I'm saving the `results` in my DB based on the `userID`. However, while taking payment, due to some reason I'm not able to save that in my DB and the payment get successful. 

I know we can get the all receipts with ` getAvailablePurchases()`. But it's like it will load 100s of data (if its available). How to get the recent active transaction details with receipt?

**Comment by creativemind1** [comment]
I don't have problem in getting results after getting payment, what I meant was If for some reason I lost connection and I don't get saved in to my DB then there will be problem for me.

**Comment by Jobeso** [comment]
The purchaseUpdate listener will be called again with a purchase if you did not call `finishTransaction` on the client side. You should only call `finishTransaction` if you get a success response from your backend.
You can also use `getPurchaseHistory` to get everything a user bought except consumables and map over it to find the transaction you want to find.

**Comment by creativemind1** [comment]
It sound very interesting. So until I don't call `finishTransaction` or `finishTransactioniOS`, I will keep on getting updates from `purchaseUpdate` listener?

**Comment by creativemind1** [comment]
`finishTransaction` is not working in android but I'm using `RNIap.acknowledgePurchaseAndroid` and it is working. So is it still require for me to use `finishTransaction`

**Comment by Jobeso** [comment]
`finishTransaction` is the newer api and calls `acknowledgePurchaseAndroid` so you would need no difference between the platforms. So if you call `finishTransaction` there should be no need to call `acknowledgePurchaseAndroid`.

From the README (function acknowledgePurchaseAndroid)
```
Acknowledge a product. Like above for non-consumables. Use finishTransaction instead for both platforms since version 4.1.0 or later.
```

**Comment by creativemind1** [comment]
`finishTransaction` always throw error for me. But `acknowledgePurchaseAndroid` works fine.

**Comment by creativemind1** [comment]
This will be very useful for me for this section. So I will go the answer with the above mentioned given suggestion.
```
componentDidMount () {           
this.purchaseUpdateSubscription = await RNIap.purchaseUpdatedListener(purchase => {
               //get the purchase token and save it in your DB.
              // after that call
              await RNIap.acknowledgePurchaseAndroid(
                    transaction.purchaseToken
                );
             //completes the purchase....
            });

            this.purchaseErrorSubscription = await RNIap.purchaseErrorListener(error => {
                //Handle any error here
            });
}
    componentWillUnmount() {
        if (this.purchaseUpdateSubscription) {
            this.purchaseUpdateSubscription.remove();
            this.purchaseUpdateSubscription = null;
        }
        if (this.purchaseErrorSubscription) {
            this.purchaseErrorSubscription.remove();
            this.purchaseErrorSubscription = null;
        }
    }
```

**Comment by anastely** [comment]
Guys I've faced something like this, Should i use finishTransaction OR finishTransactionIOS If I just Target iOS?

**Comment by creativemind1** [comment]
`finishTransactionIOS` will suffice

**Comment by anastely** [comment]
@creativemind1  I add it but my app crashed :(
Check this [iusse](https://github.com/dooboolab/react-native-iap/issues/1020) please!

**Comment by creativemind1** [comment]
Looks like it is not working for the latest version. I'm not sure. Can you degrade to  "react-native-iap": "^4.4.3", and give a try?  Also just give without any const/let as I heard It doesn't return any value.
`await RNIap.finishTransactionIOS(purchase.transactionId);`

**Comment by anastely** [comment]
@creativemind1  Now i want to delete const/let and add `await` then build the new version for TestFlight, 
If you could try the latest version and let me know if it works with you or not?
I'm debugging in TestFlight and it's Take a lot of time :))

**Comment by creativemind1** [comment]
Other people too facing issue with finishTransactioniOS in 4.4.8 version as well. So I guess the problem is in the module itself. It would not be wise to check if other also facing the same. I suggest you simply get back to the previous versions modules and then revert to the latest when your issue get resolved. Cheers!

**Comment by anastely** [comment]
Well, So `4.4.3` is stable to downgrade to it?
Thanks.
