### ISSUE TITLE
Cannot connect to iTunes Store, XCode says restoreCompletedTransactionsFailedWithError, account is new sandbox account

### ISSUE THREAD

**Issue by DavideValdo** [dooboolab/react-native-iap#998]
### Version of react-native-iap
4.4.2
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Login is prompted, I login with sandbox account, `getAvailablePurchases()` returns the empty array

### Actual behavior
I cannot connect, calling getAvailablePurchase() and loggin in with sandbox account on iPhone XS simulator results in "Cannot connect to iTunes Store" promise rejection, XCode console just logs `restoreCompletedTransactionsFailedWithError`

```
const App: () => React$Node = () => {
  let AudioPlayer

  auth().onAuthStateChanged((user) => {      
    console.log(user)
  })

  useEffect(() => {
    const _myF = async () => {
      console.log("Ciao")
      let outcome = await RNIap.initConnection()
      console.log("Outcome: " + outcome)
      
      let purchases = await RNIap.getAvailablePurchases()
      console.log(purchases)
      purchases.forEach(p => console.log(p))
    }

    _myF()
  })

  return (
    <>
      <Video source={{uri:'https://firebasestorage.googleapis.com/v0/b/relaxmelodies-9e26d.appspot.com/o/test.mp3?alt=media&token=920c58b3-e278-4762-9504-4c457893dffc'}}
        ref={ref => AudioPlayer = ref}
        playInBackground={true}
        controls={true}
        fullscreen={true}
      />
    </>
  );
};


export default App;
```

### Tested environment (Emulator? Real Device?)
iPhone XS Emulator on XCode. Did not test on real device.

### Steps to reproduce the behavior
The in-app purchase I created says "missing meta-data", also I didn't submit any bundle yet to App Store Connect. Sandbox account was created under App Store Connect -> Users & Access -> Sandbox -> Tester

**Comment by DavideValdo** [comment]
Also I cannot get products

```
const App: () => React$Node = () => {
  let AudioPlayer

  auth().onAuthStateChanged((user) => {      
    console.log(user)
  })

  useEffect(() => {
    const _myF = async () => {
      console.log("Ciao")
      let outcome = await RNIap.initConnection()
      console.log("Outcome: " + outcome)
      
      let purchases = await RNIap.getProducts(['modulo_training_autogeno'])
      console.log(purchases)
      purchases.forEach(p => console.log(p))
    }

    _myF()
  })
```
`purchases` is always the empty array, both Android and iOS.

<img width="1008" alt="Screenshot 2020-05-07 at 23 43 36" src="https://user-images.githubusercontent.com/26572302/81347530-a2ee5080-90bc-11ea-802a-66418fc5fee1.png">

**Comment by anastely** [comment]
Are you solve it?

**Comment by DavideValdo** [comment]
Many say you can only test purchase in production app with real device for Apple

**Comment by anastely** [comment]
But my app it's not in production, it's should test IAP before submitting my app to review also IAP!

**Comment by DavideValdo** [comment]
That's the problem! Let me know if you manage to test purchases without production build and/or without device

**Comment by anastely** [comment]
@DavideValdo 
after couple of days Sadly I just using testflight and it takes a lot of time in debugging!!

So i just found a friend how has an iPhone and test it, 
It works and Buys successfully 
But now he's very busy So

I just want when users buy products successfully Dispatch an action to change something in the app 'access to full features'  and send a request to our API.

So how can i know if this user buys successful or not?

here's my code

```

 getProduct = async () => {
    try {
      await RNIap.initConnection();
      // console.log('init?', init);
      const availablePurchases = await RNIap.getProducts(items);
      console.log('availablePurchases', availablePurchases);
      this.setState({
        availablePurchases,
      });
    } catch (err) {
      // console.warn(err);
      Alert.alert('Error purchase available', JSON.stringify(err));
    }
  };

  requestSubscription = async sku => {
    try {
     let req = await RNIap.requestSubscription(sku);
    
    // is here should i check 
   // if (req) dispatch action?

    } catch (err) {
      Alert.alert(err.code, err.message);
    }
  };
```
