### ISSUE TITLE
getProducts() is empty

### ISSUE THREAD

**Issue by DavideValdo** [dooboolab/react-native-iap#999]
### Version of react-native-iap
4.4.2
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
`getProducts(['modulo_training_autogeno'])` returns an array with 1 product
### Actual behavior

Source for the whole application:

```
const App: () => React$Node = () => {
  const [productsJSON, setProductsJSON] = useState()

  auth().onAuthStateChanged((user) => {      
    console.log(user)
  })

  useEffect(() => {
    const _myF = async () => {
      console.log("Ciao")
      let outcome = await RNIap.initConnection()
      console.log("Outcome: " + outcome)
      
      let products = await RNIap.getProducts(['modulo_training_autogeno'])
      console.log(JSON.stringify(products))
      setProductsJSON(JSON.stringify(products))
    }

    _myF()
  })

  return (
    <>
      <Video source={{uri:''}}
        ref={ref => AudioPlayer = ref}
        playInBackground={true}
        controls={true}
        fullscreen={true}
      />

      <Text>{productsJSON}</Text>
    </>
  );
};
```

Got 1 active product on Play Console. Pushed signed apk for internal test. 

<img width="963" alt="Screenshot 2020-05-08 at 01 11 50" src="https://user-images.githubusercontent.com/26572302/81353290-f1a1e780-90c8-11ea-9ce7-d7ef711f5218.png">

`getProducts(['modulo_training_autogeno'])` is the empty array on Android

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
Do everything as said in the medium blog post.

Also seen #977

**Comment by hyochan** [comment]
I hope you followed [the thread](https://github.com/dooboolab/react-native-iap/issues/159#issuecomment-389413989).

If things don't work as expected, I hope you try things all over again because you may have missed somethings. I've been creating products to test this module several times and I've not had failed since then.

**Comment by illiteratewriter** [comment]
I was using `getSubscriptions` and the result was an empty array when I used 
```
const itemSkus = Platform.select({
  android: [
    'com.example.coins100'
  ]
});
``` 
and it started working when i removed `com.example` and made it simply `coins100`.

**Comment by dkfox** [comment]
same problem here. (android)
1) I released the testing app in 'internal test' mode and the status was 'pending publishing'(게시보류중). on the android device, I tried to download, install, and test apk file but still, I got an empty result for getProducts(). is it normal under the 'pending publishing' status? should i wait for the status to be 'published'?
2) According to your instruction (do's and don't), it seems that the app (even if it is just a testing app) should be 'created as product'. do I have to publish it as either alpha or beta version(not internal test version) for testing this module? 
3) I am a bit confused in how to upload the apk file on the device. Should I upload and download apk file from my pc to the android device every time I changed the source for testing or downloading from the play store is the only option? I tried to a) upload and download the apk file that was created by 'gradlew assembleRelease', b) let the app to be installed on the device automatically by typing 'react-native run-android --variant=release' and c) upload the compiled file onto play store console and downloaded apk on the device, but none works. getProducts() just returned empty array.

(I am willing to write a blog that is a detailed how-to manual for testing this module when It works.)

**Comment by mifi** [comment]
FWIW downgrading to `react-native-iap@3.3` worked for me. See https://github.com/dooboolab/react-native-iap/issues/977#issuecomment-662462603

**Comment by DavideValdo** [comment]
Properly setting up sandbox account seems to have solved the problem

**Comment by mifi** [comment]
I got this problem again now that I tried to add some more IAP's, but they were not returned by `getProducts`. For me what seemed to resolve the issue was to release the app to Google Play Alpha track. See also https://stackoverflow.com/questions/24835180/android-inapp-billing-responselist-is-empty

**Comment by baronha** [comment]
same.

**Comment by tosebikan** [comment]
same (ios)

**Comment by tosebikan** [comment]
works now, user agreements status for paid apps on App Store connect (IOS) has to be active, and it seems to only work on an actual device and not on a simulator.

**Comment by ingerable** [comment]
Does the app has to be released on Play store as alpha to get your products (and wait the end of the review) ?  Because to create in app products on the google play console you just have to upload your signed apk to a track. You don't have to _release it_.

**Comment by mifi** [comment]
If i remember correctly yes I had to release it to alpha

**Comment by tosebikan** [comment]
yes @ingerable you need to submit a build to TestFlight at least so your in app subscription becomes active & make sure youve finished submitting all the requirements on the agreement section on App Store connect

**Comment by tosebikan** [comment]
make sure your purchases status are approved & use an actual device not your simulator.

**Comment by ingerable** [comment]
I am using a real device, each of my purchases has the status _active_. My app is currently being reviewed for closed track release, should I be able to retrieve my products ? As I said, currently I have an empty array as response.

**Comment by tosebikan** [comment]
you should get them, after release

**Comment by andresesfm** [comment]
Duplicate of this: https://github.com/dooboolab/react-native-iap/issues/1231. Closing as stale, feel free to reopen if you have more information

**Comment by rajat99938** [comment]
{"_h": 0, "_i": 0, "_j": null, "_k": null}  i am getting this in response
